Repository ydb-platform/ydb, pull requests merged in 2023-12, with the labels that each got.

#625 Add StarvingInRowForNotEnoughCpu for tcp sessions, KIKIMR-20586
  ydb/library/actors/interconnect/interconnect_tcp_input_session.cpp
  ydb/library/actors/interconnect/interconnect_tcp_session.cpp
  ydb/library/actors/interconnect/interconnect_tcp_session.h
Labels: area/actorsystem

#629 Fix metric PotentialMaxThreadCount, KIKIMR-20586
  ydb/library/actors/core/harmonizer.cpp
Labels: area/actorsystem

#685 Fix constrains after expand PartitionsByKeys.
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/core/yql_expr_constraint.cpp
  ydb/library/yql/core/yql_opt_utils.cpp
  ydb/library/yql/core/yql_opt_utils.h
Labels: area/yql

#643 ActorSystem should continue use std atomic
  ydb/library/actors/util/should_continue.cpp
  ydb/library/actors/util/should_continue.h
Labels: area/actorsystem

#645 ActorSystem interrupter use std atomic
  ydb/library/actors/interconnect/ut/lib/interrupter.h
Labels: area/actorsystem

#728 YQ-2548 Add discovery mutator for underlay / Merge to q-stable
  ydb/core/fq/libs/shared_resources/shared_resources.cpp
  ydb/core/fq/libs/shared_resources/ya.make
Labels: ok-to-test

#678 Added import s3 to directory
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.h
  ydb/public/lib/ydb_cli/common/aws.cpp
  ydb/public/lib/ydb_cli/common/aws.h
  ydb/public/lib/ydb_cli/common/ya.make
Labels: area/cli

#695 Add ring activation queue, KIKIMR-19398
  ydb/library/actors/core/executor_pool_base.cpp
  ydb/library/actors/core/executor_pool_base.h
  ydb/library/actors/core/thread_context.h
  ydb/library/actors/util/activation_queue.h
  ydb/library/actors/util/mpmc_ring_queue.h
Labels: area/actorsystem
