Repository ydb-platform/ydb, pull requests merged in 2024-07, with the labels that each got.

#6061 events sender control, extraction optimization, fix writing abortion
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/permutations.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.h
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/engines/storage/chunks/null_column.h
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.cpp
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.h
  ydb/core/tx/columnshard/operations/slice_builder.cpp
  ydb/core/tx/columnshard/resource_subscriber/actor.h
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.h
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/conveyor/service/service.cpp
  ydb/core/tx/conveyor/service/worker.h
  ydb/core/tx/conveyor/usage/service.h
Labels: improvement

#6055 fix TierDraftsGCWithRestart blinking and unmute one
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/write_ut.cpp
Labels: improvement

#6017 fix garbage in describe built with scheme cache response
  ydb/core/viewer/json_describe.h
Labels: bugfix

#5895 Add auto partitioning options to CLI, rename autoscaling and PQ_V1 SDK auto partitioning support
  ydb/core/persqueue/ut/common/autoscaling_ut_common.cpp
  ydb/core/persqueue/ut/common/autoscaling_ut_common.h
  ydb/core/persqueue/ut/ut_with_sdk/autoscaling_ut.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_pq.cpp
  ydb/public/api/protos/ydb_persqueue_v1.proto
  ydb/public/api/protos/ydb_topic.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
  ydb/public/sdk/cpp/client/ydb_persqueue_public/impl/persqueue.cpp
  ydb/public/sdk/cpp/client/ydb_persqueue_public/impl/persqueue_impl.h
  ydb/public/sdk/cpp/client/ydb_persqueue_public/include/control_plane.h
  ydb/public/sdk/cpp/client/ydb_topic/impl/read_session_impl.ipp
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic.cpp
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic_impl.h
  ydb/public/sdk/cpp/client/ydb_topic/include/control_plane.h
  ydb/public/sdk/cpp/client/ydb_topic/include/read_session.h
  ydb/public/sdk/cpp/client/ydb_topic/ut/ut_utils/topic_sdk_test_setup.cpp
  ydb/services/datastreams/datastreams_ut.cpp
  ydb/services/lib/actors/pq_schema_actor.cpp
  ydb/services/persqueue_v1/actors/read_session_actor.cpp
  ydb/services/persqueue_v1/actors/read_session_actor.h
  ydb/services/persqueue_v1/actors/schema_actors.cpp
Labels: not-for-changelog

#6091 Add test for singular hostconfig case
  ydb/library/yaml_config/yaml_config_parser_ut.cpp
Labels: not-for-changelog

#6097 Reduce templates (invoke kernels)
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.h.txt
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_string_kernels.cpp
  ydb/library/yql/minikql/invoke_builtins/ya.make.inc
Labels: not-for-changelog

#5902 recording a large amount of data in a transaction
  ydb/core/grpc_services/local_rpc/local_rpc.h
  ydb/core/persqueue/blob.cpp
  ydb/core/persqueue/blob.h
  ydb/core/persqueue/key.cpp
  ydb/core/persqueue/key.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/ut/internals_ut.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: new-feature

#5835 Preload followers data
  ydb/core/tablet_flat/flat_boot_bundle.h
  ydb/core/tablet_flat/flat_dbase_sz_env.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_ops_compact.h
  ydb/core/tablet_flat/flat_part_keys.h
  ydb/core/tablet_flat/flat_part_loader.cpp
  ydb/core/tablet_flat/flat_part_loader.h
  ydb/core/tablet_flat/flat_part_store.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
  ydb/core/tablet_flat/flat_scan_actor.h
  ydb/core/tablet_flat/tablet_flat_executor.h
  ydb/core/tablet_flat/ut/ut_slice_loader.cpp
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_ut_common_kqp.h
  ydb/core/tx/datashard/datashard_ut_followers.cpp
Labels: not-for-changelog

#6033 skip irrelevant tablets in balancing
  ydb/core/mind/hive/balancer.cpp
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/tablet_info.cpp
  ydb/core/mind/hive/tablet_info.h
Labels: improvement

#5728 Add support for single composite action group
  ydb/core/cms/api_adapters.cpp
  ydb/core/cms/cms.cpp
  ydb/core/cms/cms_impl.h
  ydb/core/cms/cms_maintenance_api_ut.cpp
  ydb/core/cms/cms_state.h
  ydb/core/cms/cms_tx_load_state.cpp
  ydb/core/cms/cms_tx_store_permissions.cpp
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/cms/cms_ut_common.h
  ydb/core/cms/scheme.h
  ydb/core/cms/ut/ya.make
  ydb/core/cms/ut_helpers.h
  ydb/core/cms/walle.h
  ydb/core/cms/walle_create_task_adapter.cpp
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#6125 Remove '--cache-size 512G' (do not erase files between build and test)
  .github/actions/build_ya/action.yml
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#5929 [CBO] JoinKind support added
  ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
  ydb/library/yql/core/cbo/cbo_optimizer_new.h
  ydb/library/yql/dq/opt/dq_opt_dphyp_solver.h
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
  ydb/library/yql/dq/opt/dq_opt_join_tree_node.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
Labels: new-feature

#6101 default value for columns
  ydb/core/kqp/gateway/behaviour/tablestore/operations/alter_column.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/operations/alter_column.h
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/protos/ya.make
  ydb/core/tx/columnshard/blobs_reader/actor.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetched_data.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetched_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/columnshard/engines/scheme/abstract/loader.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/loader.h
  ydb/core/tx/columnshard/engines/scheme/column/info.cpp
  ydb/core/tx/columnshard/engines/scheme/column/info.h
  ydb/core/tx/columnshard/engines/scheme/column_features.h
  ydb/core/tx/columnshard/engines/scheme/defaults/common/scalar.cpp
  ydb/core/tx/columnshard/engines/scheme/defaults/common/scalar.h
  ydb/core/tx/columnshard/engines/scheme/defaults/common/ya.make
  ydb/core/tx/columnshard/engines/scheme/defaults/protos/data.proto
  ydb/core/tx/columnshard/engines/scheme/defaults/protos/ya.make
  ydb/core/tx/columnshard/engines/scheme/defaults/ya.make
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/ya.make
  ydb/core/tx/columnshard/splitter/ut/ut_splitter.cpp
  ydb/core/tx/schemeshard/olap/columns/update.cpp
  ydb/core/tx/schemeshard/olap/columns/update.h
  ydb/core/tx/schemeshard/olap/columns/ya.make
Labels: new-feature

#6112 Lexicographic order of keys
  ydb/core/persqueue/key.h
Labels: bugfix

#6088 Avoid potential column names clash. Add test
  ydb/library/yql/core/common_opt/yql_co_finalizers.cpp
  ydb/library/yql/core/ut/yql_opt_utils_ut.cpp
  ydb/library/yql/core/yql_opt_utils.cpp
  ydb/library/yql/core/yql_opt_utils.h
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/test.test_optimizers-yql-18408_filter_multiusage_pushdown-default.txt-Analyze_/extracted
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/optimizers/yql-18408_filter_multiusage_pushdown.sql
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: area/yql, improvement

#6110 provide seq_no through event. dont use special tx-message
  ydb/core/tx/columnshard/columnshard.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/schemeshard/olap/operations/alter_store.cpp
  ydb/core/tx/schemeshard/olap/operations/alter_table.cpp
  ydb/core/tx/schemeshard/olap/operations/create_store.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_table.cpp
Labels: improvement

#6126 split huge file to appropriate libs
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/operations/batch_builder/builder.cpp
  ydb/core/tx/columnshard/operations/batch_builder/builder.h
  ydb/core/tx/columnshard/operations/batch_builder/merger.cpp
  ydb/core/tx/columnshard/operations/batch_builder/merger.h
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.h
  ydb/core/tx/columnshard/operations/batch_builder/ya.make
  ydb/core/tx/columnshard/operations/slice_builder.cpp
  ydb/core/tx/columnshard/operations/slice_builder/builder.cpp
  ydb/core/tx/columnshard/operations/slice_builder/builder.h
  ydb/core/tx/columnshard/operations/slice_builder/ya.make
  ydb/core/tx/columnshard/operations/write.cpp
  ydb/core/tx/columnshard/operations/write.h
  ydb/core/tx/columnshard/operations/ya.make
Labels: improvement

#6089 fix query parameter folderId
  ydb/library/yql/tools/solomon_emulator/lib/webapp.py
Labels: not-for-changelog

#6117 changes to query replay yt
  ydb/tools/query_replay_yt/main.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
  ydb/tools/query_replay_yt/query_replay.h
Labels: not-for-changelog

#5989 clash has been fixed for TColumnStatistics
  ydb/library/yql/providers/generic/pushdown/ut/match_predicate_ut.cpp
  ydb/library/yql/providers/generic/pushdown/yql_generic_column_statistics.h
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.cpp
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.h
  ydb/library/yql/providers/s3/actors/ya.make
  ydb/library/yql/providers/s3/actors/yql_arrow_push_down.cpp
Labels: bugfix

#6111 Nemesis: ssh flags and py3 fixes
  ydb/tests/library/nemesis/remote_execution.py
Labels: not-for-changelog

#6132 Bloat stats
  ydb/library/yql/scripts/bloat/README.md
  ydb/library/yql/scripts/bloat/bloat.sh
  ydb/library/yql/scripts/bloat/parse_bloat.py
Labels: not-for-changelog

#6130 Upscale some results in order to simplify comparison with pg-version
  ydb/library/benchmarks/gen_queries/consts.yql
  ydb/library/benchmarks/gen_queries/consts_decimal.yql
  ydb/library/benchmarks/queries/tpcds/yql/q20.sql
  ydb/library/benchmarks/queries/tpcds/yql/q36.sql
Labels: not-for-changelog

#6092 Replication stats (total & per item): lag, initial scan progress
  ydb/core/grpc_services/rpc_replication.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/controller_impl.h
  ydb/core/tx/replication/controller/private_events.cpp
  ydb/core/tx/replication/controller/private_events.h
  ydb/core/tx/replication/controller/replication.h
  ydb/core/tx/replication/controller/target_base.cpp
  ydb/core/tx/replication/controller/target_base.h
  ydb/core/tx/replication/controller/tx_describe_replication.cpp
  ydb/library/services/services.proto
  ydb/public/api/protos/draft/ydb_replication.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/sdk/cpp/client/draft/ydb_replication.cpp
  ydb/public/sdk/cpp/client/draft/ydb_replication.h
  ydb/public/sdk/cpp/client/ydb_table/table.cpp
  ydb/public/sdk/cpp/client/ydb_table/table.h
Labels: improvement

#6144 fix saveload logic & support loading custom udfs
  ydb/tools/query_replay_yt/main.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
  ydb/tools/query_replay_yt/query_replay.cpp
  ydb/tools/query_replay_yt/query_replay.h
Labels: not-for-changelog

#6123 Support put tracing with sampling in TestShard
  ydb/core/protos/msgbus.proto
  ydb/core/test_tablet/load_actor_impl.h
  ydb/core/test_tablet/load_actor_state.cpp
  ydb/core/test_tablet/load_actor_write.cpp
Labels: not-for-changelog

#5982 Http authorization support
  ydb/core/grpc_services/base/base.h
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/grpc_services/grpc_request_proxy.h
  ydb/core/mon/async_http_mon.cpp
  ydb/core/mon/mon.cpp
  ydb/core/mon/mon.h
  ydb/core/mon/ya.make
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/core/viewer/json_query.h
  ydb/core/viewer/ut/ya.make
  ydb/core/viewer/viewer_ut.cpp
  ydb/library/actors/testlib/test_runtime.cpp
  ydb/library/actors/testlib/test_runtime.h
Labels: improvement

#6146 More compact catalog initializer
  ydb/library/yql/parser/pg_catalog/catalog.cpp
Labels: not-for-changelog

#6141 Cold throw func
  ydb/library/yql/minikql/computation/mkql_computation_node_impl.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_impl.h
Labels: not-for-changelog

#6119 Improved support of PG OID types
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/regoids.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
Labels: area/pg

#6148 TKeyPrefix constructor
  ydb/core/persqueue/key.cpp
  ydb/core/persqueue/key.h
Labels: bugfix

#6145 Enable FilterPushdownEnableMultiusage, EarlyExpandSkipNull in tests
  ydb/library/yql/cfg/tests/gateways-experimental.conf
Labels: experimental-feature

#6139 Fix loop variable shadowing
  ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
Labels: area/yql, bugfix

#6133 correct extract column methods
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/common/adapter.h
  ydb/core/formats/arrow/permutations.cpp
  ydb/core/formats/arrow/process_columns.cpp
  ydb/core/formats/arrow/process_columns.h
  ydb/core/formats/arrow/program.cpp
  ydb/core/formats/arrow/special_keys.cpp
  ydb/core/formats/arrow/ya.make
  ydb/core/io_formats/arrow/csv_arrow.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.cpp
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/iterator.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/operations/slice_builder/builder.cpp
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
  ydb/core/tx/program/program.h
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
  ydb/services/ydb/ydb_bulk_upsert_olap_ut.cpp
Labels: improvement

#6162 Add conditions in YQL ALTER TABLE
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
Labels: documentation

#6157 YYQ-3398 fixed result set size counting
  ydb/core/grpc_services/query/rpc_fetch_script_results.cpp
  ydb/core/kqp/proxy_service/kqp_script_executions.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
Labels: new-feature, bugfix

#6095 Big datetime in backup/restore CLI
  ydb/library/backup/backup.cpp
  ydb/library/backup/query_builder.cpp
  ydb/public/lib/value/value.cpp
Labels: experimental-feature

#6142 Fix pushdown logical ops with scalar argument.
  ydb/core/kqp/query_compiler/kqp_olap_compiler.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: bugfix

#6169 Fix test timeout after PR #5982
  ydb/core/viewer/ut/ya.make
Labels: not-for-changelog

#6158 configure max in flight and reduce by default
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.h
Labels: improvement

#6086 Isolate unstable sentinel test in separate chunk
  .github/config/muted_ya.txt
  ydb/core/cms/sentinel_ut.cpp
  ydb/core/cms/sentinel_ut_helpers.h
  ydb/core/cms/sentinel_ut_unstable.cpp
  ydb/core/cms/ut_sentinel_unstable/ya.make
  ydb/core/cms/ya.make
Labels: not-for-changelog

#6053 msgbus cleanup: remove whoami api method
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/msgbus_server_whoami.cpp
  ydb/core/client/server/ya.make
  ydb/core/driver_lib/cli_base/cli_cmds.h
  ydb/core/driver_lib/cli_base/cli_cmds_root.cpp
  ydb/core/driver_lib/cli_base/cli_cmds_whoami.cpp
  ydb/core/driver_lib/cli_base/cli_kicli.cpp
  ydb/core/driver_lib/cli_base/cli_kicli.h
  ydb/core/driver_lib/cli_base/ya.make
  ydb/core/driver_lib/cli_config_base/config_base.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_root.cpp
  ydb/core/driver_lib/cli_utils/ya.make
  ydb/core/protos/grpc.proto
  ydb/core/protos/msgbus.proto
  ydb/core/util/address_classifier.cpp
  ydb/core/util/address_classifier.h
  ydb/core/util/address_classifier_ut.cpp
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/client/grpc_client.h
  ydb/public/lib/deprecated/kicli/kicli.h
  ydb/public/lib/deprecated/kicli/kikimr.cpp
  ydb/public/lib/ydb_cli/commands/command_base/ya.make
  ydb/public/lib/ydb_cli/commands/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_command.cpp
  ydb/public/lib/ydb_cli/commands/ydb_discovery/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_service_discovery.h
Labels: not-for-changelog

#6143 Removed GetTongue and GetThroat calls to make LLVM code simpler
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
Labels: not-for-changelog

#6164 YQ-3371 fixed workload service unit tests
  ydb/core/kqp/workload_service/actors/pool_handlers_acors.cpp
  ydb/core/kqp/workload_service/kqp_workload_service.cpp
  ydb/core/kqp/workload_service/ut/common/kqp_workload_service_ut_common.cpp
  ydb/core/kqp/workload_service/ut/common/kqp_workload_service_ut_common.h
  ydb/core/kqp/workload_service/ut/kqp_workload_service_actors_ut.cpp
  ydb/core/kqp/workload_service/ut/kqp_workload_service_tables_ut.cpp
  ydb/core/kqp/workload_service/ut/kqp_workload_service_ut.cpp
Labels: bugfix

#6172 add ut for solomon async io
  ydb/library/yql/providers/solomon/async_io/ut/dq_solomon_write_actor_ut.cpp
  ydb/library/yql/providers/solomon/async_io/ut/ut_helpers.cpp
  ydb/library/yql/providers/solomon/async_io/ut/ut_helpers.h
  ydb/library/yql/providers/solomon/async_io/ut/ya.make
  ydb/library/yql/providers/solomon/async_io/ya.make
Labels: not-for-changelog

#6072 IGNIETFERRO-2059: Fix a couple of string-related use-after-free errors
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_http_request.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/testlib/test_client.cpp
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/dq/actors/spilling/spilling_file_ut.cpp
Labels: bugfix, external

#6191 Muted fq yt test pg/regoids
  ydb/tests/fq/yt/kqp_yt_file.py
Labels: not-for-changelog, new-feature

#6093 Support AVX512 for ChaCha cypher
  util/system/cpu_id.cpp
  ydb/core/blobstorage/crypto/chacha_512.cpp
  ydb/core/blobstorage/crypto/chacha_512.h
  ydb/core/blobstorage/crypto/chacha_512_ut.cpp
  ydb/core/blobstorage/crypto/crypto.cpp
  ydb/core/blobstorage/crypto/crypto.h
  ydb/core/blobstorage/crypto/ut/ya.make
  ydb/core/blobstorage/crypto/ya.make
Labels: performance

#6196 Fix YDB doc
  ydb/docs/ru/core/concepts/glossary.md
Labels: documentation

#6209 Fix !append title in docs
  ydb/docs/en/core/maintenance/manual/dynamic-config-selectors.md
  ydb/docs/ru/core/maintenance/manual/dynamic-config-selectors.md
Labels: documentation

#6204 Incremented YDB CLI version to 2.11.0
  ydb/apps/ydb/version.txt
Labels: not-for-changelog

#6195 YT vs YQL Udfs 2.37 ABI compat
  ydb/library/yql/yt/dynamic/dylib.exports
Labels: not-for-changelog

#6184 Less code for computation nodes
  ydb/library/yql/minikql/computation/mkql_computation_node_impl.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_impl.h
Labels: not-for-changelog

#6193 Fix log actor rendering
  ydb/library/actors/core/log.cpp
Labels: not-for-changelog

#6200 exclude ut for win
  ydb/library/yql/providers/solomon/async_io/ya.make
Labels: not-for-changelog

#6198 add pq async io ut
  ydb/library/yql/providers/pq/provider/ut/ya.make
  ydb/library/yql/providers/pq/provider/ut/yql_pq_ut.cpp
  ydb/library/yql/providers/pq/provider/ya.make
Labels: not-for-changelog

#6211 improve replay execution
  ydb/tools/query_replay_yt/main.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
  ydb/tools/query_replay_yt/query_replay.h
Labels: not-for-changelog

#5859 move time difference issue under database level
  ydb/core/health_check/health_check.cpp
  ydb/public/api/protos/ydb_monitoring.proto
Labels: new-feature, improvement

#6206 init IsTuple in cons
  ydb/library/yql/minikql/computation/mkql_computation_node_holders.h
Labels: not-for-changelog

#6227 rework http tracing, add traceresponse header
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/json_query.h
  ydb/core/viewer/pdisk_info.h
  ydb/core/viewer/viewer.cpp
  ydb/core/viewer/viewer.h
  ydb/library/actors/wilson/wilson_trace.cpp
  ydb/library/actors/wilson/wilson_trace.h
Labels: new-feature

#6153 Sorting load average fix
  ydb/core/viewer/json_compute.h
  ydb/core/viewer/json_nodes.h
Labels: new-feature, bugfix

#6094 Replaced proto types to SDK types in ExecuteScript settings
  ydb/core/fq/libs/compute/common/utils.cpp
  ydb/core/fq/libs/compute/common/utils.h
  ydb/core/fq/libs/compute/ydb/events/events.h
  ydb/core/fq/libs/compute/ydb/executer_actor.cpp
  ydb/core/fq/libs/compute/ydb/executer_actor.h
  ydb/core/fq/libs/compute/ydb/result_writer_actor.cpp
  ydb/core/fq/libs/compute/ydb/status_tracker_actor.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_scripts_ut.cpp
  ydb/public/sdk/cpp/client/ydb_query/client.cpp
  ydb/public/sdk/cpp/client/ydb_query/query.cpp
  ydb/public/sdk/cpp/client/ydb_query/query.h
  ydb/public/sdk/cpp/client/ydb_query/stats.h
Labels: backward-incompatible

#6175 kafka_proxy: tune include paths
  ydb/core/kafka_proxy/actors/actors.h
  ydb/core/kafka_proxy/actors/kafka_produce_actor.cpp
  ydb/core/kafka_proxy/kafka_consumer_protocol.h
  ydb/core/kafka_proxy/kafka_events.h
  ydb/core/kafka_proxy/kafka_records.h
  ydb/core/kafka_proxy/ut/ut_kafka_functions.cpp
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/kafka_proxy/ut/ut_serialization.cpp
Labels: not-for-changelog

#6174 Fix build for darwin x86_64
  ydb/library/actors/queues/mpmc_bitmap_buffer.h
  ydb/library/actors/queues/mpmc_ring_queue_v1.h
  ydb/library/actors/queues/mpmc_ring_queue_v2.h
  ydb/library/actors/queues/mpmc_ring_queue_v3.h
Labels: area/actorsystem, bugfix

#6137 Fix sink updates & empty commit
  .github/config/muted_ya.txt
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_update.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/kqp.proto
Labels: not-for-changelog

#6216 Remove nonexistent argument in examples
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/struct.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/struct.md
Labels: not-for-changelog

#6203 YQ-3371 fixed WM useg without feature flag
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
Labels: improvement

#6208 Tune bloat scripts (more stats)
  ydb/library/yql/scripts/bloat/parse_bloat.py
Labels: not-for-changelog

#6217 Reduce TEventPBBase binary size and probably compilation time
  ydb/library/actors/core/event_pb.cpp
  ydb/library/actors/core/event_pb.h
Labels: not-for-changelog

#6109 [yt provider] Gather all consumers in PhysicalFinalizingTransformer
  ydb/library/yql/core/ut/yql_execution_ut.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_physical_finalizing.cpp
  ydb/library/yql/tests/s-expressions/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: area/yql, bugfix

#6225 Added optimizer join and equijoin counts for debugging
  ydb/core/kqp/host/kqp_explain_prepared.cpp
  ydb/core/kqp/host/kqp_host_impl.h
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/opt/kqp_opt.h
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/kqp_query_plan.h
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log.h
  ydb/library/yql/dq/opt/dq_opt_join.cpp
  ydb/library/yql/dq/opt/dq_opt_join.h
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.h
  ydb/library/yql/dq/opt/dq_opt_log.h
Labels: not-for-changelog

#6223 [CBO] CountMin fix
  ydb/core/kqp/opt/kqp_statistics_transformer.cpp
  ydb/library/yql/core/yql_statistics.h
  ydb/library/yql/dq/opt/dq_opt_predicate_selectivity.cpp
Labels: bugfix

#6260 refactor cli: don't implicitly convert YAML::Node to bool
  ydb/public/lib/ydb_cli/common/profile_manager.cpp
Labels: not-for-changelog, external

#6266 broken test TxUsage::WriteToTopic_Demo_24
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#6245 fix deprecation warning due to pkg_resources usage
  ydb/tests/library/harness/kikimr_config.py
  ydb/tests/library/harness/kikimr_runner.py
  ydb/tests/library/ya.make
Labels: not-for-changelog

#6250 LongTxService subscription id
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition_id.h
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
  ydb/core/persqueue/ut/internals_ut.cpp
  ydb/core/persqueue/ut/partition_ut.cpp
  ydb/core/persqueue/ut/pqtablet_ut.cpp
  ydb/core/persqueue/write_id.cpp
  ydb/core/persqueue/write_id.h
  ydb/core/persqueue/writer/writer.cpp
  ydb/core/persqueue/writer/writer.h
  ydb/core/persqueue/ya.make
  ydb/core/protos/kqp.proto
  ydb/core/protos/msgbus_pq.proto
  ydb/core/protos/pqconfig.proto
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
  ydb/services/persqueue_v1/ut/kqp_mock.cpp
  ydb/services/persqueue_v1/ut/partition_writer_cache_actor_fixture.cpp
Labels: bugfix

#6248 change error format for http handlers
  ydb/core/viewer/json_local_rpc.h
  ydb/core/viewer/json_query.h
  ydb/core/viewer/viewer.cpp
  ydb/core/viewer/viewer.h
Labels: improvement

#6270 Change calculation of actorsystem usage 24-1
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem

#6271 Change calculation of actorsystem usage 24-2
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem

#6267 Change calculation of actorsytem pool usage
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem, not-for-changelog

#6183 Stabilize tpc ds queries q65 and q79 result
  ydb/library/benchmarks/queries/tpcds/pg/q65.sql
  ydb/library/benchmarks/queries/tpcds/pg/q79.sql
  ydb/library/benchmarks/queries/tpcds/yql/q65.sql
  ydb/library/benchmarks/queries/tpcds/yql/q79.sql
Labels: not-for-changelog

#6252 Removed public includes to protos in SDK QueryService
  ydb/public/lib/ydb_cli/commands/benchmark_utils.cpp
  ydb/public/sdk/cpp/client/ydb_query/impl/client_session.h
  ydb/public/sdk/cpp/client/ydb_query/impl/exec_query.cpp
  ydb/public/sdk/cpp/client/ydb_query/tx.h
Labels: not-for-changelog

#6285 fix oltp sink update
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#6159 YQ-3184 fixed CTAS for s3 sources
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/federated_query/common/common.h
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/core/kqp/ut/federated_query/s3/s3_recipe_ut_helpers.cpp
  ydb/core/kqp/ut/federated_query/s3/s3_recipe_ut_helpers.h
  ydb/core/testlib/basics/feature_flags.h
  ydb/tests/tools/kqprun/configuration/app_config.conf
  ydb/tests/tools/kqprun/kqprun.cpp
Labels: new-feature, bugfix

#6114 Fix grace join any spilling
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.h
Labels: bugfix

#6108 grace_join/spilling: fix inflation of memory
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.h
Labels: not-for-changelog

#6256 Fix !EvWrite in data/scan query
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
Labels: not-for-changelog

#6277 Update LLVM part of combiner with spilling.
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
Labels: area/yql

#5079 YQL-18052: Implement Arrow IO spec for purecalc
  ydb/library/yql/public/purecalc/common/interface.h
  ydb/library/yql/public/purecalc/io_specs/arrow/spec.cpp
  ydb/library/yql/public/purecalc/io_specs/arrow/spec.h
  ydb/library/yql/public/purecalc/io_specs/arrow/ut/test_spec.cpp
  ydb/library/yql/public/purecalc/io_specs/arrow/ut/ya.make
  ydb/library/yql/public/purecalc/io_specs/arrow/ya.make
  ydb/library/yql/public/purecalc/io_specs/arrow/ya.make.inc
  ydb/library/yql/public/purecalc/io_specs/ut/ya.make
  ydb/library/yql/public/purecalc/io_specs/ya.make
  ydb/library/yql/public/purecalc/ut/lib/ya.make
Labels: area/yql, new-feature

#6274 Less code for invoke kernels
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/minikql/arrow/arrow_util.h
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_compare.h
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.h.txt
Labels: not-for-changelog

#6294 explicit setup of kqp_data_query_stream_lookup flag in tests
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
  ydb/core/kqp/ut/query/kqp_stats_ut.cpp
Labels: not-for-changelog

#6295 Kqprun fixed fault and logs printing for multi node usage
  ydb/library/actors/testlib/test_runtime.cpp
  ydb/library/actors/testlib/test_runtime.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: new-feature, bugfix

#6304 Fix IC unsubscription race bug
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
Labels: bugfix

#6306 Fix false-positive assertion
  ydb/core/blobstorage/nodewarden/distconf_scatter_gather.cpp
Labels: bugfix

#6293 emerg->crit correction to avoid console spam
  ydb/core/tx/columnshard/background_controller.cpp
Labels: improvement

#6296 remove regular system reask
  ydb/core/tx/columnshard/engines/column_engine.cpp
Labels: performance

#6297 speed up gc tasks construction
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.cpp
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.h
Labels: performance

#6247 Support fo big datetime in Cli: Missed break
  ydb/public/lib/ydb_cli/common/csv_parser.cpp
Labels: bugfix

#6278 fix meta cache forwarding
  ydb/library/actors/http/http.cpp
  ydb/mvp/meta/meta.cpp
Labels: bugfix

#6312 Fix unsubscription race in distconf dynamic node code
  ydb/core/blobstorage/nodewarden/distconf_dynamic.cpp
Labels: bugfix

#6253 Add pragma to grace join runtime node with spilling
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/library/yql/dq/tasks/dq_task_program.cpp
  ydb/library/yql/dq/tasks/dq_task_program.h
  ydb/library/yql/minikql/comp_nodes/mkql_factory.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/mkql_program_builder.cpp
  ydb/library/yql/minikql/mkql_program_builder.h
  ydb/library/yql/providers/common/mkql/yql_provider_mkql.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
  ydb/library/yql/providers/dq/planner/execution_planner.cpp
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
Labels: new-feature

#6307 Add PG upgrade script. Add missing catalog/sql files from 14.2
  ydb/library/yql/parser/pg_wrapper/copy_src.py
  ydb/library/yql/parser/pg_wrapper/copy_src.sh
  ydb/library/yql/parser/pg_wrapper/generate_patch.sh
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/catalog/information_schema.sql
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/catalog/system_constraints.sql
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/catalog/system_functions.sql
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/catalog/system_views.sql
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_authid.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_class.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_collation.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_database.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_namespace.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_range.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_tablespace.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_ts_config.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_ts_config_map.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_ts_dict.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_ts_parser.dat
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_ts_template.dat
  ydb/library/yql/parser/pg_wrapper/source.patch
Labels: area/yql, improvement

#6323 Only members of ReleaseApprovers team can approve changes in this branch
  .github/CODEOWNERS
Labels: not-for-changelog

#6281 Fill change exchange split & activation lists just before commit; unify checks
  ydb/core/tx/datashard/datashard_change_sending.cpp
  ydb/core/tx/datashard/datashard_split_src.cpp
Labels: bugfix

#6314 fix signal value
  ydb/core/tx/conveyor/service/service.cpp
Labels: bugfix

#6310 allow to set trace verbosity and ttl
  ydb/core/viewer/json_pipe_req.h
  ydb/library/actors/wilson/wilson_trace.h
Labels: new-feature

#6336 Revert "Change calculation of actorsystem usage 24-1"
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem

#6337 Revert "Change calculation of actorsystem usage 24-2"
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem

#6332 Fix pushdown JSON_EXISTS on runtime version 4.
  ydb/core/kqp/query_compiler/kqp_olap_compiler.cpp
Labels: bugfix

#6251 Improvements in Write Actor
  ydb/core/engine/mkql_keys.cpp
  ydb/core/engine/mkql_keys.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/scheme/scheme_tablecell.cpp
  ydb/core/scheme/scheme_tablecell.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_async_io.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
Labels: not-for-changelog

#6047 Iterative B-Tree histograms builder
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.h
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.h
  ydb/core/tablet_flat/test/libs/table/test_mixer.h
  ydb/core/tablet_flat/ut/ut_stat.cpp
  ydb/core/tablet_flat/ya.make
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/schemeshard/schemeshard__table_stats_histogram.cpp
  ydb/core/tx/schemeshard/schemeshard_utils.h
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
  ydb/core/tx/schemeshard/ut_compaction/ut_compaction.cpp
Labels: not-for-changelog

#6347 Temporarily disable FilterPushdownEnableMultiusage
  ydb/library/yql/cfg/tests/gateways-experimental.conf
Labels: area/yql, bugfix, rebase-and-check

#6350 solomon tests: sanitize issues, remove line number
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-BrokenJsonResponse-_/extracted
  ydb/library/yql/tests/sql/solomon/test.py
Labels: not-for-changelog

#6348 Fix alter replication config
  ydb/core/tx/datashard/datashard_user_table.cpp
  ydb/core/tx/datashard/datashard_user_table.h
  ydb/core/tx/datashard/datashard_ut_replication.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
Labels: not-for-changelog

#6313 Prepare flat_scheme_op.proto for multiple indexImplTables.
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/testlib/test_client.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_indexed_table.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_index/ut_async_index.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_index_build.cpp
  ydb/core/ydb_convert/table_description.cpp
Labels: improvement

#6339 EvWrite UPDATE
  ydb/core/tx/datashard/datashard__engine_host.cpp
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: experimental-feature

#6136 Implemented HeapIterator for VDisk
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_generic_it.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_generic_it_ut.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_heap_it.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_heap_it_ut.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_ut.h
  ydb/core/blobstorage/vdisk/hulldb/base/ut/ya.make
  ydb/core/blobstorage/vdisk/hulldb/base/ya.make
  ydb/core/blobstorage/vdisk/hulldb/fresh/fresh_appendix.h
  ydb/core/blobstorage/vdisk/hulldb/fresh/fresh_datasnap.h
  ydb/core/blobstorage/vdisk/hulldb/fresh/fresh_segment_impl.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_idxsnap_it.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst_it.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst_it_all_ut.cpp
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst_it_all_ut.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sstslice_it.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sstvec_it.h
Labels: improvement

#6361 Build only postgresql sources in verify.sh
  ydb/library/yql/parser/pg_wrapper/verify.sh
  ydb/library/yql/parser/pg_wrapper/ya.make
Labels: area/yql, bugfix

#6308 Less LLVM templates in base classes
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.h.txt
  ydb/library/yql/minikql/computation/mkql_simple_codegen.h
Labels: not-for-changelog

#6362 Fix unpatched global vars
  ydb/library/yql/parser/pg_wrapper/copy_src.sh
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/storage/ipc/latch.c
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/pg_config-linux.h
  ydb/library/yql/parser/pg_wrapper/postgresql/src/port/strerror.c
  ydb/library/yql/parser/pg_wrapper/vars.txt
Labels: area/yql

#6372 Document copy_src.sh and PostgreSQL update process
  ydb/library/yql/parser/pg_wrapper/readme.md
Labels: area/yql, improvement

#6369 fix test in asan (nullptr possible in original data)
  ydb/core/tx/columnshard/engines/portions/portion_info.h
Labels: bugfix

#6324 serialize special keys in separated thread
  ydb/core/formats/arrow/size_calcer.cpp
  ydb/core/formats/arrow/size_calcer.h
  ydb/core/tx/columnshard/background_controller.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
Labels: performance

#6365 prevent overlimit for ui32 in genstep
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.cpp
Labels: improvement

#6343 reduce logging
  ydb/core/tx/columnshard/columnshard.cpp
Labels: improvement

#6255 Fix kafka RU
  ydb/core/kafka_proxy/actors/kafka_fetch_actor.cpp
Labels: not-for-changelog

#6366 fix huge blobs volume for start mode withno barrier moving
  ydb/core/tx/columnshard/blobs_action/abstract/blob_set.h
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.cpp
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/gc.cpp
  ydb/core/tx/columnshard/blobs_action/bs/gc.h
  ydb/core/tx/columnshard/counters/blobs_manager.cpp
  ydb/core/tx/columnshard/counters/blobs_manager.h
Labels: performance

#6377 remove hard freeing from tablet
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/engines/writer/buffer/actor.cpp
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.cpp
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.h
  ydb/core/tx/columnshard/operations/batch_builder/builder.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/operations/slice_builder/builder.cpp
  ydb/core/tx/data_events/write_data.cpp
  ydb/core/tx/data_events/write_data.h
Labels: performance

#6257 YDB FQ: Support MDB MySQL in DatabaseResolver
  ydb/core/fq/libs/actors/database_resolver.cpp
  ydb/core/fq/libs/actors/ut/database_resolver_ut.cpp
  ydb/core/fq/libs/db_id_async_resolver_impl/mdb_endpoint_generator.cpp
Labels: new-feature

#6379 correct insert table cleaning
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
Labels: bugfix

#6290 Fix HMAC secret key loading for OAuth 2.0 token exchange config
  ydb/docs/en/core/reference/ydb-sdk/_includes/auth.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/auth.md
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/from_file.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/credentials_ut.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/jwt_check_helper.h
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/jwt_token_source_ut.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/ya.make
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ya.make
Labels: bugfix

#6395 YDB FQ: Enabling YDB test for missing table
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/test.py
  ydb/library/yql/providers/generic/connector/tests/utils/database.py
Labels: bugfix

#6178 Obtain UsedTableMemory from private cache stats
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_part_loader.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.cpp
  ydb/core/tablet_flat/test/libs/table/test_store.h
  ydb/core/tablet_flat/test/libs/table/test_writer.h
  ydb/core/tablet_flat/ut/ut_stat.cpp
Labels: not-for-changelog

#6032 Fix pg_tables when not using /Root database
  ydb/core/kqp/provider/yql_kikimr_opt.cpp
  ydb/core/kqp/provider/yql_kikimr_opt_build.cpp
  ydb/core/kqp/provider/yql_kikimr_provider_impl.h
Labels: not-for-changelog

#6298 YDB FQ: Add MySQL to fq proxy
  ydb/core/fq/libs/actors/clusters_from_connections.cpp
  ydb/core/fq/libs/common/util.cpp
  ydb/core/fq/libs/compute/common/config.h
  ydb/core/fq/libs/control_plane_proxy/actors/query_utils.cpp
  ydb/core/fq/libs/control_plane_proxy/utils/utils.h
  ydb/core/fq/libs/control_plane_storage/request_validators.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp
  ydb/public/api/protos/draft/fq.proto
Labels: new-feature

#6359 Less LLVM in block agg
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg.cpp
Labels: not-for-changelog

#6393 Enable update for oltp sink
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_update.cpp
Labels: not-for-changelog

#6330 Several CTAS
  ydb/core/kqp/common/compilation/events.h
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#6333 [dq] Stop early in dq validator
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
Labels: area/yql, performance

#6389 remove portions constructor hard freeing from tablet
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.h
  ydb/core/tx/columnshard/engines/changes/cleanup_tables.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.cpp
  ydb/core/tx/columnshard/engines/changes/ttl.cpp
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.h
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.h
  ydb/core/tx/columnshard/engines/portions/write_with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/write_with_blobs.h
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/engines/writer/compacted_blob_constructor.cpp
Labels: performance

#6357 decompress.sh has been added
  ydb/tests/fq/s3/test_compression_data/decompress.sh
Labels: not-for-changelog

#6407 Hide deprecated operation kinds
  ydb/public/lib/ydb_cli/commands/ydb_service_operation.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_operation.h
Labels: improvement

#6398 Handle empty GC commands correctly
  ydb/core/blobstorage/ut_blobstorage/gc.cpp
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hull.cpp
Labels: bugfix

#6405 Fix VDisk replication stuck sensor bug
  ydb/core/blobstorage/vdisk/repl/blobstorage_repl.cpp
Labels: bugfix

#6408 Fix tests for purecalc Arrow IO spec
  ydb/library/yql/public/purecalc/io_specs/arrow/ut/test_spec.cpp
Labels: area/yql, bugfix

#5984 YDB FQ: validate `DATABASE_NAME` field
  ydb/core/external_sources/external_data_source.cpp
  ydb/core/fq/libs/control_plane_storage/request_validators.cpp
Labels: improvement

#6419 Make tsserver build for linux only
  ydb/tools/tsserver/main.cpp
Labels: not-for-changelog

#6427 fix typo in IsStrict(): ScripUdf -> ScriptUdf
  ydb/library/yql/core/yql_opt_utils.cpp
Labels: not-for-changelog

#6349 Avoid inlining of arrow kernel dispatcher
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.h.txt
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_string_kernels.cpp
Labels: not-for-changelog

#6242 Remove some ancient feature flags
  ydb/core/base/appdata_fwd.h
  ydb/core/base/compile_time_flags.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_yard.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_events.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_events.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_ut_followers.cpp
  ydb/core/tx/datashard/datashard_ut_order.cpp
  ydb/core/tx/datashard/datashard_ut_read_table.cpp
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/ut_sequence/datashard_ut_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
  ydb/services/ydb/ydb_table_ut.cpp
Labels: not-for-changelog
