Repository ydb-platform/ydb, pull requests merged in 2024-04, with the labels that each got.

#3316 Get rid of pedantic check
  ydb/core/tx/datashard/execute_distributed_erase_tx_unit.cpp
Labels: not-for-changelog, bugfix

#3319 Fix PACKAGE declaration in prebuilt tools (for YQL-17642)
  ydb/library/yql/tools/mrjob/ya.make
  ydb/library/yql/tools/udf_resolver/ya.make
  ydb/library/yql/tools/yqlrun/ya.make
  ydb/library/yql/udfs/common/datetime2/ya.make
Labels: not-for-changelog, external

#3336 [YQL-17573] FlatMap over Extend optimizer
  ydb/library/yql/core/common_opt/yql_co_flow1.cpp
  ydb/library/yql/tests/s-expressions/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: improvement

#1541 [YQL-15142] issue a warning on reading secure tables with default cache
  ydb/library/yql/core/issue/protos/issue_id.proto
  ydb/library/yql/core/issue/yql_issue.txt
  ydb/library/yql/providers/yt/common/yql_names.h
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_load_table_meta.cpp
Labels: improvement

#3309 Added tests for jaeger tracing configurator
  ydb/core/cms/console/jaeger_tracing_configurator_ut.cpp
  ydb/core/cms/console/ut/ya.make
  ydb/core/jaeger_tracing/sampling_throttling_configurator.h
  ydb/core/jaeger_tracing/throttler_ut.cpp
Labels: not-for-changelog

#3236 early finish has been fixed YQ-2452 YQL-16433
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_channels.cpp
Labels: bugfix

#3357 Added blank lines around the include block.
  ydb/docs/en/core/postgresql/_includes/statements/create_table/create_table_people.md
  ydb/docs/en/core/postgresql/_includes/statements/create_table/create_table_people_const.md
  ydb/docs/en/core/postgresql/_includes/statements/create_table/create_table_social_card.md
  ydb/docs/en/core/postgresql/_includes/statements/create_table/create_table_sort_cond.md
  ydb/docs/en/core/postgresql/_includes/statements/create_table/create_table_temp.md
  ydb/docs/en/core/postgresql/_includes/statements/create_table/syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/delete_from/syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/drop_table/syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/insert_into/insert_into_table_people.md
  ydb/docs/en/core/postgresql/_includes/statements/insert_into/insert_into_table_people_many_rows.md
  ydb/docs/en/core/postgresql/_includes/statements/insert_into/insert_into_table_people_set_date.md
  ydb/docs/en/core/postgresql/_includes/statements/insert_into/syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_cross_join.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_cross_join_output.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_and.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_example.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_where.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_where_group_by_few_cond.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_where_limit.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_where_limit_offset.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_few_col_where_order_by.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_full_join.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_full_join_output.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_group_by_syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_having_group_by.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_having_where_group_by.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_inner_join.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_inner_join_output.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_join_syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_left_join.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_left_join_output.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_no_target.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_right_join.md
  ydb/docs/en/core/postgresql/_includes/statements/select/select_right_join_output.md
  ydb/docs/en/core/postgresql/_includes/statements/select/syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/update/syntax.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_set_case_where.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_set_few_col_where.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_set_func_where.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_set_where.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_where.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_where_and.md
  ydb/docs/en/core/postgresql/_includes/statements/update/update_where_and_or.md
  ydb/docs/en/core/postgresql/_includes/transactions/example.md
  ydb/docs/en/core/postgresql/statements/begin_commit_rollback.md
  ydb/docs/en/core/postgresql/statements/create_table.md
  ydb/docs/en/core/postgresql/statements/delete_from.md
  ydb/docs/en/core/postgresql/statements/drop_table.md
  ydb/docs/en/core/postgresql/statements/insert_into.md
  ydb/docs/en/core/postgresql/statements/select.md
  ydb/docs/en/core/postgresql/statements/update.md
Labels: documentation

#2986 GetTask counters have been added to fetcher YQ-2669
  ydb/core/fq/libs/actors/pending_fetcher.cpp
Labels: not-for-changelog

#3242 Fixed some examples from documentaion (query service only)
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/kqp/ut/yql/kqp_yql_ut.cpp
  ydb/tests/fq/common/test_unknown_data_source.py
Labels: bugfix

#3363 fix clang14 build
  ydb/library/yql/public/udf/arrow/ut/array_builder_ut.cpp
Labels: not-for-changelog

#3359 Support of YQL dates in ToPg
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_dates.txt
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_dates.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/pg_to_dates.cfg
  ydb/library/yql/tests/sql/suites/blocks/pg_to_dates.sql
  ydb/library/yql/tests/sql/suites/pg/dates_to_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
Labels: improvement

#3261 Fix TABLESAMPLE SYSTEM crashing DQ/hybrid
  ydb/library/yql/providers/yt/provider/yql_yt_dq_hybrid.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
  ydb/library/yql/tests/sql/dq_file/part4/canondata/test.test_sampling-system_sampling--Analyze_/extracted
  ydb/library/yql/tests/sql/dq_file/part7/canondata/test.test_sampling-io_block_size_pragma--Analyze_/extracted
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
Labels: bugfix

#3365 MaxAttachmentsSize setting
  ydb/library/yql/providers/dq/common/yql_dq_settings.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
Labels: not-for-changelog

#3369 [YQL-17709] Fix clang14 build
  ydb/library/yql/dq/actors/spilling/channel_storage.cpp
Labels: not-for-changelog

#3370 Fix memleak: cyclic smart pointers (+ logs)
  ydb/library/yql/providers/dq/task_runner/tasks_runner_pipe.cpp
Labels: bugfix

#3373 Disable style tests in ydb/library/yql/providers/generic/connector/tests
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/ya.make
  ydb/library/yql/providers/generic/connector/tests/join/ya.make
  ydb/library/yql/providers/generic/connector/tests/test_cases/ya.make
  ydb/library/yql/providers/generic/connector/tests/utils/clients/postgresql.py
  ydb/library/yql/providers/generic/connector/tests/utils/clients/ya.make
  ydb/library/yql/providers/generic/connector/tests/utils/scenario/ya.make
  ydb/library/yql/providers/generic/connector/tests/utils/types/ya.make
  ydb/library/yql/providers/generic/connector/tests/utils/ya.make
Labels: not-for-changelog

#2813 Changed interconnect disconnected handler in tenantinfo handler
  ydb/core/viewer/json_tenantinfo.h
Labels: new-feature

#3368 Support of Interval type in ToPg
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_interval.txt
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_interval.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/pg_to_interval.cfg
  ydb/library/yql/tests/sql/suites/blocks/pg_to_interval.sql
  ydb/library/yql/tests/sql/suites/pg/interval_to_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: improvement

#3265 Add balancing monitoring
  ydb/core/blobstorage/vdisk/balance/balancing_actor.cpp
  ydb/core/blobstorage/vdisk/balance/deleter.cpp
  ydb/core/blobstorage/vdisk/balance/sender.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_mongroups.h
Labels: not-for-changelog

#3358 Fix a race between mediator state and pipeline restoring active transactions
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
Labels: bugfix

#3376 File downloader: add logs
  ydb/library/yql/providers/dq/actors/yt/resource_downloader.cpp
  ydb/library/yql/providers/dq/actors/yt/yt_wrapper.cpp
Labels: not-for-changelog

#3389 Make clang-14 happy
  ydb/core/io_formats/arrow/csv_arrow.cpp
Labels: not-for-changelog

#3390 Like to find/grep YQ-3015
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_bindings.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_connections.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp
Labels: bugfix

#3229 YDB-2822 Fix UUID column usage in CDC
  ydb/core/io_formats/cell_maker/cell_maker.cpp
  ydb/core/tx/datashard/change_record_cdc_serializer.cpp
  ydb/core/tx/datashard/datashard_ut_change_collector.cpp
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/datashard/ya.make
  ydb/core/tx/replication/service/table_writer_ut.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/library/uuid/uuid.cpp
  ydb/library/uuid/uuid.h
Labels: new-feature, improvement

#2041 Fix viewer in Safari
  ydb/core/viewer/content/v2/storage
  ydb/core/viewer/content/v2/util.js
Labels: bugfix

#3383 [YQL-17573] Support more callables in FlatMap over Extend optimizer
  ydb/library/yql/core/common_opt/yql_co_flow1.cpp
Labels: improvement

#3397 Add dstool different token types support
  ydb/apps/dstool/lib/common.py
Labels: not-for-changelog

#3380 Update CODEOWNERS for /ydb/library/yql/yt
  .github/CODEOWNERS
Labels: not-for-changelog, external

#3403 fix csv reading
  ydb/core/io_formats/arrow/csv_arrow.cpp
Labels: new-feature

#3404 Fix types for blind deletes
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_returning.cpp
  ydb/core/kqp/ut/opt/kqp_returning_ut.cpp
Labels: not-for-changelog

#3406 [docs] update docs_release.yaml
  .github/workflows/docs_release.yaml
Labels: documentation

#3396 add helpers for huge portions scan processing
  ydb/core/formats/arrow/arrow_batch_builder.cpp
  ydb/core/formats/arrow/arrow_filter.cpp
  ydb/core/formats/arrow/arrow_filter.h
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/common/accessor.cpp
  ydb/core/formats/arrow/common/accessor.h
  ydb/core/formats/arrow/common/adapter.cpp
  ydb/core/formats/arrow/common/adapter.h
  ydb/core/formats/arrow/common/container.cpp
  ydb/core/formats/arrow/common/container.h
  ydb/core/formats/arrow/common/ya.make
  ydb/core/formats/arrow/hash/calcer.cpp
  ydb/core/formats/arrow/hash/calcer.h
  ydb/core/formats/arrow/hash/ya.make
  ydb/core/formats/arrow/merging_sorted_input_stream.cpp
  ydb/core/formats/arrow/permutations.cpp
  ydb/core/formats/arrow/permutations.h
  ydb/core/formats/arrow/program.cpp
  ydb/core/formats/arrow/program.h
  ydb/core/formats/arrow/reader/merger.cpp
  ydb/core/formats/arrow/reader/merger.h
  ydb/core/formats/arrow/reader/position.cpp
  ydb/core/formats/arrow/reader/position.h
  ydb/core/formats/arrow/reader/result_builder.cpp
  ydb/core/formats/arrow/reader/result_builder.h
  ydb/core/formats/arrow/reader/ya.make
  ydb/core/formats/arrow/replace_key.h
  ydb/core/formats/arrow/size_calcer.cpp
  ydb/core/formats/arrow/size_calcer.h
  ydb/core/formats/arrow/switch/compare.cpp
  ydb/core/formats/arrow/switch/compare.h
  ydb/core/formats/arrow/switch/switch_type.h
  ydb/core/formats/arrow/switch/ya.make
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/common/result.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.cpp
  ydb/core/tx/program/program.h
  ydb/library/conclusion/status.cpp
  ydb/library/conclusion/status.h
  ydb/library/conclusion/ya.make
Labels: new-feature

#3417 Changed YQL TPCH schema to accomodate long ints
  ydb/library/benchmarks/gen_queries/bindings_tpch.json
Labels: bugfix

#3408 Changed default behaviour of external_throttling section
  ydb/core/cms/console/jaeger_tracing_configurator.cpp
  ydb/core/cms/console/jaeger_tracing_configurator_ut.cpp
Labels: not-for-changelog

#3402 log converters errors
  ydb/core/formats/arrow/converter.cpp
  ydb/core/formats/arrow/converter.h
  ydb/core/tx/columnshard/engines/ut/ut_program.cpp
  ydb/core/tx/columnshard/transactions/operators/schema.h
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: new-feature, bugfix

#3385 Use designated initializers to pass arguments in to KQP planer
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
Labels: not-for-changelog

#3431 Fix SqlParsingOnly.AlterTableAddIndexWithIsNotSupported
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: not-for-changelog

#3418 sequential read for huge portions (limits for raw bytes in mem)
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/common/accessor.cpp
  ydb/core/formats/arrow/common/accessor.h
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/portions/index_chunk.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/abstract/abstract.h
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/common/result.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/column_assembler.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/column_assembler.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/columns_set.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetched_data.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetched_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/iterator.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/iterator.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/plain_read_data.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/plain_read_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/normalizer/portion/min_max.cpp
  ydb/core/tx/columnshard/splitter/abstract/chunk_meta.h
Labels: new-feature

#3440 fix race condition
  ydb/core/formats/arrow/common/accessor.cpp
  ydb/core/formats/arrow/common/accessor.h
  ydb/core/formats/arrow/hash/calcer.h
  ydb/core/formats/arrow/reader/position.cpp
  ydb/core/formats/arrow/reader/position.h
  ydb/core/formats/arrow/reader/result_builder.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/storage/granule.h
Labels: bugfix

#3448 Temporary restore old config examples due to #3434
  ydb/deploy/yaml_config_examples/block-4-2.yaml
  ydb/deploy/yaml_config_examples/mirror-3dc-3-nodes-in-memory.yaml
  ydb/deploy/yaml_config_examples/mirror-3dc-3-nodes.yaml
  ydb/deploy/yaml_config_examples/mirror-3dc-9-nodes.yaml
  ydb/deploy/yaml_config_examples/single-node-in-memory.yaml
  ydb/deploy/yaml_config_examples/single-node-with-file.yaml
Labels: not-for-changelog

#2805 failed status code metrics and logs have been added YQ-2535
  ydb/core/fq/libs/actors/pending_fetcher.cpp
  ydb/core/fq/libs/compute/common/run_actor_params.h
  ydb/core/fq/libs/compute/common/utils.cpp
  ydb/core/fq/libs/compute/common/utils.h
  ydb/core/fq/libs/compute/common/ya.make
  ydb/core/fq/libs/compute/ydb/actors_factory.cpp
  ydb/core/fq/libs/compute/ydb/actors_factory.h
  ydb/core/fq/libs/compute/ydb/status_tracker_actor.cpp
  ydb/core/fq/libs/compute/ydb/status_tracker_actor.h
  ydb/core/fq/libs/compute/ydb/synchronization_service/ya.make
  ydb/core/fq/libs/control_plane_storage/events/events.h
  ydb/core/fq/libs/control_plane_storage/internal/task_ping.cpp
  ydb/core/fq/libs/control_plane_storage/internal/ya.make
  ydb/core/fq/libs/control_plane_storage/util.cpp
  ydb/core/fq/libs/control_plane_storage/util.h
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_impl.h
  ydb/core/fq/libs/metrics/status_code_counters.cpp
  ydb/core/fq/libs/metrics/status_code_counters.h
  ydb/core/fq/libs/metrics/ut/metrics_ut.cpp
  ydb/core/fq/libs/metrics/ut/ya.make
  ydb/core/fq/libs/metrics/ya.make
  ydb/core/fq/libs/ya.make
Labels: improvement

#3438 Fixed TPCH schema in CLI
  ydb/public/lib/ydb_cli/commands/tpch_schema.sql
Labels: bugfix

#2631 YQL-17766 Fix decimal incompatibility between yqlrun and yt
  ydb/library/yql/minikql/protobuf_udf/ut/value_builder_ut.cpp
  ydb/library/yql/providers/common/codec/ya.make
  ydb/library/yql/providers/common/codec/yql_codec.cpp
  ydb/library/yql/providers/common/codec/yql_codec.h
  ydb/library/yql/providers/yt/codec/codegen/yt_codec_cg.cpp
  ydb/library/yql/providers/yt/codec/yt_codec_io.cpp
  ydb/library/yql/providers/yt/lib/res_pull/res_or_pull.cpp
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/type_v3/decimal_yt.cfg
  ydb/library/yql/tests/sql/suites/type_v3/decimal_yt.sql
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: area/yql, bugfix

#3415 [YQL-17573] Fix handling groping sets + window functions/top level dstinct
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/source.cpp
  ydb/library/yql/sql/v1/source.h
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/aggregate/group_by_ru_with_select_distinct.cfg
  ydb/library/yql/tests/sql/suites/aggregate/group_by_ru_with_select_distinct.sql
  ydb/library/yql/tests/sql/suites/aggregate/group_by_ru_with_window_func.cfg
  ydb/library/yql/tests/sql/suites/aggregate/group_by_ru_with_window_func.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
Labels: bugfix

#3452 split interval mergers into different file
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/ya.make
  ydb/library/actors/prof/tag.cpp
  ydb/library/actors/prof/tag.h
  ydb/library/services/services.proto
Labels: not-for-changelog

#3450 clean legacy code
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/merging_sorted_input_stream.cpp
  ydb/core/formats/arrow/merging_sorted_input_stream.h
  ydb/core/formats/arrow/one_batch_input_stream.h
  ydb/core/formats/arrow/reader/merger.cpp
  ydb/core/formats/arrow/reader/merger.h
  ydb/core/formats/arrow/sort_cursor.h
  ydb/core/formats/arrow/ut/ut_arrow.cpp
  ydb/core/formats/arrow/ut/ut_program_step.cpp
  ydb/core/formats/arrow/ya.make
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
Labels: not-for-changelog

#1331 Tracing documentation
  ydb/docs/ru/core/cluster/toc_i.yaml
  ydb/docs/ru/core/concepts/_includes/index/how_it_works.md
  ydb/docs/ru/core/maintenance/manual/dynamic-config.md
  ydb/docs/ru/core/reference/observability/tracing/_images/spans.png
  ydb/docs/ru/core/reference/observability/tracing/external-traces.md
  ydb/docs/ru/core/reference/observability/tracing/setup.md
  ydb/docs/ru/core/reference/observability/tracing/toc_i.yaml
  ydb/docs/ru/core/reference/observability/tracing/toc_p.yaml
Labels: documentation

#3340 statistics push down has been supported
  ydb/library/yql/providers/generic/pushdown/ut/match_predicate_ut.cpp
  ydb/library/yql/providers/generic/pushdown/ut/ya.make
  ydb/library/yql/providers/generic/pushdown/ya.make
  ydb/library/yql/providers/generic/pushdown/yql_generic_column_statistics.h
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.cpp
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.h
  ydb/library/yql/providers/generic/style/ya.make
  ydb/library/yql/providers/generic/ya.make
Labels: not-for-changelog

#3429 Introduce acceptance check
  .github/workflows/acceptance_run.yml
  .github/workflows/docker_publish.yml
  .github/workflows/nightly_run.yaml
  .github/workflows/prewarm-ccache.yml
  .github/workflows/prewarm-debug.yaml
  .github/workflows/sync_cmakebuild.yml
  ydb/tests/acceptance/ya.make
Labels: not-for-changelog

#3468 Remove permanently failing tests `ydb/core/kqp/ut/federated_query/generic`
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/federated_query/generic/ch_recipe_ut_helpers.cpp
  ydb/core/kqp/ut/federated_query/generic/ch_recipe_ut_helpers.h
  ydb/core/kqp/ut/federated_query/generic/connector_recipe_ut_helpers.cpp
  ydb/core/kqp/ut/federated_query/generic/connector_recipe_ut_helpers.h
  ydb/core/kqp/ut/federated_query/generic/docker-compose.yml
  ydb/core/kqp/ut/federated_query/generic/kqp_generic_plan_ut.cpp
  ydb/core/kqp/ut/federated_query/generic/kqp_generic_provider_join_ut.cpp
  ydb/core/kqp/ut/federated_query/generic/mdb_mock_config.json
  ydb/core/kqp/ut/federated_query/generic/pg_recipe_ut_helpers.cpp
  ydb/core/kqp/ut/federated_query/generic/pg_recipe_ut_helpers.h
  ydb/core/kqp/ut/federated_query/generic/ya.make
  ydb/core/kqp/ut/federated_query/ya.make
Labels: not-for-changelog

#3439 YQ-2899 fix url escaping
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/tests/fq/s3/test_insert.py
Labels: bugfix

#3456 Support of numeric types in ToPg
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/parser/pg_wrapper/arrow.cpp
  ydb/library/yql/parser/pg_wrapper/arrow_impl.h
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_numbers.txt
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_numbers.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/pg_to_numbers.cfg
  ydb/library/yql/tests/sql/suites/blocks/pg_to_numbers.sql
  ydb/library/yql/tests/sql/suites/pg/numbers_to_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: improvement

#3419 Correctly trigger borrow compaction for shadow data
  ydb/core/tx/datashard/build_index.cpp
  ydb/core/tx/datashard/datashard__compact_borrowed.cpp
  ydb/core/tx/datashard/datashard__compaction.cpp
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_loans.cpp
  ydb/core/tx/datashard/datashard_ut_build_index.cpp
  ydb/core/tx/datashard/datashard_ut_compaction.cpp
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/schemeshard/schemeshard__borrowed_compaction.cpp
  ydb/core/tx/schemeshard/schemeshard__compaction.cpp
  ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/util/operation_queue.h
Labels: bugfix

#3437 Add DockerImage YT pragma to YQL
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_spec.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_op_hash.cpp
Labels: new-feature

#3470 chain into script
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/columns_set.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/constructor.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
Labels: improvement

#3338 YDBDOCS-633: review follow-up
  ydb/docs/en/core/devops/ansible/index.md
  ydb/docs/en/core/devops/index.md
  ydb/docs/en/core/devops/kubernetes/index.md
  ydb/docs/ru/core/devops/ansible/index.md
  ydb/docs/ru/core/devops/ansible/toc_p.yaml
  ydb/docs/ru/core/devops/kubernetes/index.md
  ydb/docs/ru/core/devops/kubernetes/toc_p.yaml
Labels: documentation

#3381 [docs] update quickstart.md to make it work on ARM64 Docker
  ydb/docs/en/core/quickstart.md
  ydb/docs/ru/core/quickstart.md
Labels: documentation

#3294 Provide slot names for ui
  ydb/core/base/appdata_fwd.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_schema.h
  ydb/core/mind/hive/node_info.h
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__register_node.cpp
  ydb/core/mind/local.cpp
  ydb/core/protos/hive.proto
  ydb/core/protos/local.proto
  ydb/core/protos/node_whiteboard.proto
  ydb/core/tablet/node_whiteboard.cpp
  ydb/core/viewer/json_nodes.h
Labels: not-for-changelog

#3464 query stats full
  ydb/core/viewer/json_query.h
Labels: new-feature

#3391 HC send whiteboard request when hive knows it's alive
  ydb/core/health_check/health_check.cpp
Labels: new-feature

#3462 hotkeys crush on describe
  ydb/core/viewer/json_hotkeys.h
Labels: new-feature

#3483 Support string-like types in ToPg
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/ya.make
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_strings.txt
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_strings.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/pg_to_strings.cfg
  ydb/library/yql/tests/sql/suites/blocks/pg_to_strings.sql
  ydb/library/yql/tests/sql/suites/pg/strings_to_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: improvement

#3137 YDBDOCS-632: Documentation of temporary tables
  ydb/docs/en/core/_includes/temp-table-description.md
  ydb/docs/en/core/postgresql/_includes/statements/create_table/syntax.md
  ydb/docs/en/core/postgresql/statements/create_table.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/create_table.md
  ydb/docs/presets.yaml
  ydb/docs/ru/core/_includes/temp-table-description.md
  ydb/docs/ru/core/postgresql/statements/create_table.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/create_table.md
Labels: new-feature

#3412 YDBDOCS-650 import from JDBC docs
  ydb/docs/en/core/integrations/import-jdbc.md
  ydb/docs/en/core/integrations/toc_i.yaml
  ydb/docs/ru/core/integrations/import-jdbc.md
  ydb/docs/ru/core/integrations/toc_i.yaml
Labels: documentation

#3479 one threads pool for each s3 backend
  ydb/core/wrappers/s3_storage_config.cpp
Labels: improvement

#3484 process error withno verify and exceptions
  ydb/core/formats/arrow/program.cpp
  ydb/core/formats/arrow/program.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h
  ydb/core/tx/program/program.h
  ydb/library/conclusion/status.h
Labels: improvement

#3480 correct hard verification
  ydb/core/tx/columnshard/background_controller.cpp
  ydb/core/tx/columnshard/background_controller.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write_index.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write_index.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/counters/indexation.cpp
  ydb/core/tx/columnshard/counters/indexation.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
Labels: improvement

#3118 fix query start at calculation
  ydb/core/kqp/proxy_service/kqp_proxy_service_impl.h
  ydb/core/kqp/ut/sysview/kqp_sys_view_ut.cpp
Labels: bugfix

#3455 Attempt to use recipe for SDK tests
  ydb/services/ydb/sdk_credprovider_ut/ya.make
  ydb/services/ydb/ya.make
  ydb/tests/functional/sdk/cpp/sdk_credprovider/dummy_provider_ut.cpp
  ydb/tests/functional/sdk/cpp/sdk_credprovider/ya.make
  ydb/tests/functional/ya.make
Labels: not-for-changelog

#3499 Use NO_BUILD_IF instead of empty library (relates YQL-17642)
  ydb/library/yql/udfs/common/hyperscan/ya.make
Labels: not-for-changelog, external

#3486 overload about portions metadata memory overlimit
  ydb/core/formats/arrow/special_keys.cpp
  ydb/core/formats/arrow/special_keys.h
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/counters/columnshard.cpp
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/counters/engine_logs.cpp
  ydb/core/tx/columnshard/counters/engine_logs.h
  ydb/core/tx/columnshard/data_sharing/destination/session/destination.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/column_engine.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/portions/meta.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/engines/storage/storage.cpp
  ydb/core/tx/columnshard/engines/storage/storage.h
Labels: new-feature

#3503 infly metrics have been fixed for ResolveSubject and ResolveFolder
  ydb/core/fq/libs/control_plane_proxy/control_plane_proxy.cpp
Labels: bugfix

#3481 FileCache: Fix Acquire/Release (Contains and Walk must be synchronized)
  ydb/library/yql/providers/dq/runtime/file_cache.cpp
  ydb/library/yql/providers/dq/runtime/ut/file_cache_ut.cpp
Labels: bugfix

#3501 Remove legacy method
  ydb/core/grpc_services/base/base.h
  ydb/core/grpc_services/local_rpc/local_rpc.h
  ydb/core/grpc_services/rpc_deferrable.h
  ydb/core/grpc_services/rpc_discovery.cpp
  ydb/core/grpc_services/rpc_execute_scheme_query.cpp
  ydb/core/grpc_services/rpc_load_rows.cpp
  ydb/core/grpc_services/rpc_rollback_transaction.cpp
  ydb/core/grpc_services/rpc_scheme_base.h
  ydb/core/kafka_proxy/actors/control_plane_common.h
  ydb/core/kafka_proxy/actors/kafka_create_partitions_actor.cpp
  ydb/services/persqueue_v1/grpc_pq_read.cpp
Labels: not-for-changelog

#3493 Rename slot name to node name
  ydb/core/base/appdata_fwd.h
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init_impl.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/grpc_services/rpc_node_registration.cpp
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/node_info.h
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__register_node.cpp
  ydb/core/mind/local.cpp
  ydb/core/mind/node_broker.cpp
  ydb/core/mind/node_broker__register_node.cpp
  ydb/core/mind/node_broker_impl.h
  ydb/core/mind/node_broker_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/protos/hive.proto
  ydb/core/protos/local.proto
  ydb/core/protos/node_broker.proto
  ydb/core/protos/node_whiteboard.proto
  ydb/core/tablet/node_whiteboard.cpp
  ydb/core/viewer/json_nodes.h
  ydb/public/api/protos/ydb_discovery.proto
  ydb/public/sdk/cpp/client/ydb_discovery/discovery.cpp
  ydb/public/sdk/cpp/client/ydb_discovery/discovery.h
Labels: not-for-changelog

#3471 Option to limit batch size (bytes) for query service
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/gateway/kqp_gateway.h
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/library/yql/dq/actors/compute/dq_compute_actor.h
  ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h
  ydb/public/api/protos/ydb_query.proto
  ydb/public/sdk/cpp/client/ydb_query/impl/exec_query.cpp
  ydb/public/sdk/cpp/client/ydb_query/query.h
Labels: new-feature

#3400 YQL-18051: Add block implementation for Exists callable
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/core/type_ann/type_ann_blocks.cpp
  ydb/library/yql/core/type_ann/type_ann_blocks.h
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/minikql/arrow/arrow_util.h
  ydb/library/yql/minikql/arrow/mkql_bit_utils.h
  ydb/library/yql/minikql/comp_nodes/mkql_block_exists.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_exists.h
  ydb/library/yql/minikql/comp_nodes/mkql_block_logical.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_factory.cpp
  ydb/library/yql/minikql/comp_nodes/ut/mkql_block_exists_ut.cpp
  ydb/library/yql/minikql/comp_nodes/ut/ya.make.inc
  ydb/library/yql/minikql/comp_nodes/ya.make.inc
  ydb/library/yql/minikql/mkql_program_builder.cpp
  ydb/library/yql/minikql/mkql_program_builder.h
  ydb/library/yql/providers/common/mkql/yql_provider_mkql.cpp
  ydb/library/yql/public/udf/arrow/bit_util.h
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/exists.cfg
  ydb/library/yql/tests/sql/suites/blocks/exists.sql
  ydb/library/yql/tests/sql/suites/blocks/input_exists.txt
  ydb/library/yql/tests/sql/suites/blocks/input_exists.txt.attr
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
Labels: improvement

#3524 fix sysview construction
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/abstract.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/granule_view.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/granule_view.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/iterator.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/iterator.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/metadata.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/ya.make
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.h
  ydb/core/tx/columnshard/engines/reader/sys_view/constructor/constructor.h
  ydb/core/tx/columnshard/engines/reader/sys_view/granules/granules.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/granules/granules.h
  ydb/core/tx/columnshard/engines/reader/sys_view/portions/portions.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/portions/portions.h
Labels: improvement

#3523 dont rebuild table into record batch
  ydb/core/formats/arrow/size_calcer.cpp
  ydb/core/formats/arrow/size_calcer.h
  ydb/core/kqp/compute_actor/kqp_compute_events.h
  ydb/core/kqp/compute_actor/kqp_scan_events.h
  ydb/core/kqp/runtime/kqp_scan_data.cpp
  ydb/core/kqp/runtime/kqp_scan_data.h
  ydb/core/tx/columnshard/common/tests/shard_reader.h
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/export/actor/export_actor.cpp
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
  ydb/core/tx/datashard/datashard__kqp_scan.cpp
Labels: improvement

#3525 Win32 build fix: explicit casts
  ydb/library/yql/providers/common/codec/yql_codec.cpp
Labels: not-for-changelog

#3511 Support of wide dates/interval/decimal/dynumber in ToPg
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/parser/pg_wrapper/arrow.cpp
  ydb/library/yql/parser/pg_wrapper/arrow_impl.h
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/ya.make
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_dates.txt
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_dates.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_interval.txt
  ydb/library/yql/tests/sql/suites/blocks/input_to_pg_interval.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/pg_to_dates.sql
  ydb/library/yql/tests/sql/suites/blocks/pg_to_interval.sql
  ydb/library/yql/tests/sql/suites/pg/dates_to_pg.sql
  ydb/library/yql/tests/sql/suites/pg/interval_to_pg.sql
  ydb/library/yql/tests/sql/suites/pg/numeric_to_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: improvement

#3526 add validations for inconsistency states for scanners
  ydb/core/formats/arrow/reader/batch_iterator.cpp
  ydb/core/formats/arrow/reader/batch_iterator.h
  ydb/core/formats/arrow/reader/merger.cpp
  ydb/core/formats/arrow/reader/merger.h
  ydb/core/formats/arrow/reader/position.h
  ydb/core/formats/arrow/reader/ya.make
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetched_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
Labels: improvement

#3528 Fix kafka read session partitions releases
  ydb/core/kafka_proxy/actors/kafka_read_session_actor.cpp
Labels: not-for-changelog

#3529 coded-signals for bulk upsert
  ydb/core/tx/tx_proxy/upload_rows_common_impl.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: improvement

#3530 clean deprecated signal
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
Labels: not-for-changelog

#3535 fix test YdbLogStore.LogTable
  ydb/services/ydb/ydb_logstore_ut.cpp
Labels: bugfix

#3515 Allow customize wall-e provider
  ydb/tools/cfg/walle/walle.py
  ydb/tools/ydbd_slice/__init__.py
  ydb/tools/ydbd_slice/cluster_description.py
  ydb/tools/ydbd_slice/handlers.py
  ydb/tools/ydbd_slice/nodes.py
Labels: improvement

#3500 YQL-18095: Disable plan check for join_left_sample test
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/sampling/join_left_sample.sql
Labels: area/ci, not-for-changelog

#3512 KIKIMR-18545: do not set not_null for default values
  ydb/core/kqp/ut/opt/kqp_not_null_ut.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/ydb_convert/table_description.cpp
  ydb/services/ydb/ydb_ut.cpp
Labels: not-for-changelog

#3239 resource manager to control execution units
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/node_service/kqp_node_ut.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/core/kqp/rm_service/kqp_rm_ut.cpp
Labels: improvement

#3502 YQ-3011 fix parquet type validation
  ydb/library/yql/providers/s3/provider/yql_s3_datasource_type_ann.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_dq_integration.cpp
Labels: bugfix

#2912 patches for zabbix and wiki
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/sql/pg/pg_sql.cpp
Labels: not-for-changelog, new-feature

#3549 Moving kikimr_slice to github
  ydb/tools/ydbd_slice/__init__.py
  ydb/tools/ydbd_slice/kube/docker.py
Labels: improvement

#3540 fix array access for merge on kqp
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/common/accessor.cpp
  ydb/core/formats/arrow/common/accessor.h
  ydb/core/kqp/compute_actor/kqp_compute_events.h
  ydb/core/kqp/runtime/kqp_scan_data.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
Labels: bugfix

#3531 [Configs] Add basic audit for yaml configs
  ydb/core/cms/console/console__replace_yaml_config.cpp
  ydb/core/cms/ui/console_log.js
  ydb/core/cms/ui/ext/myers-diff/LICENSE
  ydb/core/cms/ui/ext/myers-diff/myers_diff.js
  ydb/core/cms/ui/index.html
  ydb/core/cms/ya.make
  ydb/core/protos/console.proto
  ydb/core/protos/console_config.proto
Labels: not-for-changelog

#3556 Add forgotten arg in ydbd_slice
  ydb/tools/ydbd_slice/__init__.py
Labels: not-for-changelog

#3487 fix local db downsampling
  ydb/core/graph/shard/backends.cpp
  ydb/core/graph/shard/backends.h
  ydb/core/graph/ut/graph_ut.cpp
Labels: bugfix

#3451 Add pragma for YT option 'expiration_timeout'
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
Labels: improvement

#3509 Added event attribute to DSProxy.* spans
  ydb/core/blobstorage/backpressure/queue.h
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_assimilate.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_block.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_collect.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_discover.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_discover_m3dc.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_discover_m3of4.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_get.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_indexrestoreget.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_multicollect.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_multiget.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_patch.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_range.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_status.cpp
Labels: not-for-changelog

#3520 Add `REQUIREMENTS(cpu:all)` to the top level of every ya.make in `ydb/library/yql/providers/generic/connector/tests`
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/test.py
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/ya.make
  ydb/library/yql/providers/generic/connector/tests/join/ya.make
  ydb/library/yql/providers/generic/connector/tests/utils/docker_compose.py
  ydb/library/yql/providers/generic/connector/tests/utils/settings.py
Labels: not-for-changelog

#3560 The grpc stream must be finished in case of grpc proxy emmited YDB error
  ydb/core/grpc_services/base/base.h
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/grpc_services/grpc_request_proxy_simple.cpp
  ydb/core/grpc_services/local_grpc/local_grpc.h
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/public_http/grpc_request_context_wrapper.h
  ydb/library/grpc/server/grpc_request.h
  ydb/library/grpc/server/grpc_request_base.h
Labels: bugfix

#3478 BTreeIndex Add GroupDataSize
  ydb/core/tablet_flat/flat_page_btree_index.h
  ydb/core/tablet_flat/flat_page_btree_index_writer.h
  ydb/core/tablet_flat/flat_part_loader.cpp
  ydb/core/tablet_flat/flat_part_writer.h
  ydb/core/tablet_flat/protos/flat_table_part.proto
  ydb/core/tablet_flat/test/libs/table/test_part.h
  ydb/core/tablet_flat/test/libs/table/test_writer.h
  ydb/core/tablet_flat/ut/ut_btree_index_nodes.cpp
  ydb/core/tablet_flat/ut/ut_stat.cpp
  ydb/core/tablet_flat/ut_large/ut_btree_index_large.cpp
Labels: not-for-changelog

#3578 run pr-check on all branches contains -stable-
  .github/workflows/pr_check.yml
Labels: new-feature

#3576 Fix hive scheme tests
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_hive_/flat_hive.schema
Labels: not-for-changelog

#3513 [Pretty Table] Fixed bug
  ydb/public/lib/ydb_cli/common/pretty_table.cpp
  ydb/public/lib/ydb_cli/common/pretty_table.h
  ydb/tests/functional/ydb_cli/canondata/result.json
  ydb/tests/functional/ydb_cli/canondata/test_ydb_scripting.TestExecuteScriptFromStdinWithWideOutput.test_wide_table/result.output
  ydb/tests/functional/ydb_cli/test_ydb_scripting.py
Labels: new-feature, bugfix

#3574 optimize counters construction (reusage now)
  ydb/core/tx/columnshard/blobs_action/abstract/action.h
  ydb/core/tx/columnshard/blobs_action/abstract/storage.h
  ydb/core/tx/columnshard/blobs_action/counters/storage.cpp
  ydb/core/tx/columnshard/blobs_action/counters/storage.h
  ydb/core/tx/columnshard/blobs_action/counters/ya.make
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.h
  ydb/core/tx/columnshard/engines/changes/cleanup_tables.h
  ydb/core/tx/columnshard/engines/changes/compaction.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.h
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/changes/with_appended.h
  ydb/core/tx/columnshard/engines/insert_table/data.h
  ydb/core/tx/columnshard/engines/insert_table/insert_table.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/plain_read_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.h
  ydb/core/tx/columnshard/export/actor/export_actor.cpp
  ydb/core/tx/columnshard/normalizer/portion/normalizer.h
  ydb/core/tx/columnshard/operations/write.cpp
Labels: performance

#3555 use sequential read for data copy
  ydb/core/formats/arrow/common/accessor.h
  ydb/core/kqp/runtime/kqp_scan_data.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.cpp
Labels: improvement

#3568 Support of dates & uuid in FromPg
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_from_pg_dates.txt
  ydb/library/yql/tests/sql/suites/blocks/input_from_pg_dates.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/pg_from_dates.cfg
  ydb/library/yql/tests/sql/suites/blocks/pg_from_dates.sql
  ydb/library/yql/tests/sql/suites/pg/dates_from_pg.sql
  ydb/library/yql/tests/sql/suites/pg/uuid_from_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: improvement

#3475 Add compaction logs
  ydb/core/tablet_flat/flat_comp_create.cpp
  ydb/core/tablet_flat/flat_comp_create.h
  ydb/core/tablet_flat/flat_comp_gen.cpp
  ydb/core/tablet_flat/flat_comp_gen.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor_compaction_logic.cpp
  ydb/core/tablet_flat/flat_scan_spent.h
  ydb/core/tablet_flat/ut/ut_comp_gen.cpp
  ydb/core/tx/datashard/datashard__compaction.cpp
  ydb/core/tx/datashard/datashard_ut_build_index.cpp
Labels: not-for-changelog

#3570 Added blob_id attributes to VDisk spans
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.cpp
  ydb/core/blobstorage/vdisk/query/query_base.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_loggedrec.cpp
Labels: not-for-changelog

#3492 statistics aggregator logic of table scanning
  ydb/core/kqp/gateway/kqp_metadata_loader.cpp
  ydb/core/protos/counters_statistics_aggregator.proto
  ydb/core/protos/statistics.proto
  ydb/core/protos/tx_datashard.proto
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/aggregator_impl.h
  ydb/core/statistics/aggregator/schema.h
  ydb/core/statistics/aggregator/tx_init.cpp
  ydb/core/statistics/aggregator/tx_navigate.cpp
  ydb/core/statistics/aggregator/tx_resolve.cpp
  ydb/core/statistics/aggregator/tx_save_query_response.cpp
  ydb/core/statistics/aggregator/tx_scan_table.cpp
  ydb/core/statistics/aggregator/tx_statistics_scan_response.cpp
  ydb/core/statistics/aggregator/ya.make
  ydb/core/statistics/events.h
  ydb/core/statistics/save_load_stats.cpp
  ydb/core/statistics/save_load_stats.h
  ydb/core/statistics/stat_service.cpp
  ydb/core/statistics/ut/ut_aggregator.cpp
  ydb/core/statistics/ut/ut_save_load_stats.cpp
  ydb/core/statistics/ut/ut_statistics.cpp
  ydb/core/statistics/ut/ya.make
  ydb/core/tx/datashard/datashard__column_stats.cpp
  ydb/core/util/count_min_sketch.cpp
  ydb/core/util/count_min_sketch.h
Labels: not-for-changelog

#3577 Topic's supported codecs was changed while changing partitions count
  ydb/apps/ydb/ut/run_ydb.cpp
  ydb/apps/ydb/ut/run_ydb.h
  ydb/apps/ydb/ut/supported_codecs.cpp
  ydb/apps/ydb/ut/supported_codecs_fixture.cpp
  ydb/apps/ydb/ut/supported_codecs_fixture.h
  ydb/apps/ydb/ut/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
Labels: bugfix

#3566 Fixed multiple inputs to aggeregate in Simplified JSON
  ydb/core/kqp/opt/kqp_query_plan.cpp
Labels: bugfix

#3585 ybdb_slice improvements
  ydb/tools/ydbd_slice/handlers.py
  ydb/tools/ydbd_slice/nodes.py
Labels: not-for-changelog, improvement

#3546 one cycle for processing transactions, writing operations and promoting offsets
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_monitoring.cpp
  ydb/core/persqueue/partition_util.h
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/ut/partition_ut.cpp
  ydb/core/persqueue/ut/pq_ut.cpp
  ydb/core/persqueue/ut/user_action_processor_ut.cpp
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
Labels: improvement

#3596 [import] fix whitespace
  ydb/apps/dstool/lib/common.py
Labels: bugfix

#3454 Fix flake8 warning in arcadia tests
  ydb/public/sdk/python/enable_v3_new_behavior/__init__.py
Labels: not-for-changelog, external

#3435 Add limit for LLVM node count
  ydb/library/yql/providers/yt/common/yql_configuration.h
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
Labels: improvement

#3601 Add single-thread tests for mpmc ring queue
  ydb/library/actors/core/executor_pool_base.h
  ydb/library/actors/core/thread_context.h
  ydb/library/actors/queues/activation_queue.h
  ydb/library/actors/queues/defs.h
  ydb/library/actors/queues/mpmc_ring_queue.h
  ydb/library/actors/queues/mpmc_ring_queue_ut.cpp
  ydb/library/actors/queues/ut/ya.make
  ydb/library/actors/queues/ya.make
Labels: area/actorsystem, bugfix

#3550 Allow uig.sh to load yql udfs outside ydb tree
  ydb/library/yql/tools/yqlrun/uig.sh
Labels: not-for-changelog

#3610 DQ gateways fixes: grpc thread join inside self thread, infinite recu…
  ydb/library/yql/providers/dq/local_gateway/ut/ya.make
  ydb/library/yql/providers/dq/local_gateway/ut/yql_dq_gateway_local_ut.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.cpp
Labels: bugfix

#2606 [Liquibase]: documentation for the Ydb Dialect of Liquibase
  ydb/docs/en/core/integrations/_assets/liquibase-step-1.png
  ydb/docs/en/core/integrations/_assets/liquibase-step-2.png
  ydb/docs/en/core/integrations/_assets/liquibase-step-3.png
  ydb/docs/en/core/integrations/_assets/liquibase-step-4.png
  ydb/docs/en/core/integrations/liquibase.md
  ydb/docs/en/core/integrations/toc_i.yaml
  ydb/docs/ru/core/integrations/_assets/liquibase-step-1.png
  ydb/docs/ru/core/integrations/_assets/liquibase-step-2.png
  ydb/docs/ru/core/integrations/_assets/liquibase-step-3.png
  ydb/docs/ru/core/integrations/_assets/liquibase-step-4.png
  ydb/docs/ru/core/integrations/liquibase.md
  ydb/docs/ru/core/integrations/toc_i.yaml
Labels: documentation, new-feature

#3532 [Configs] Make yaml config page first at CMS
  ydb/core/cms/ui/configs.js
  ydb/core/cms/ui/index.html
Labels: not-for-changelog

#3612 Fix flake8 in ydbd_slice
  ydb/tools/ydbd_slice/handlers.py
  ydb/tools/ydbd_slice/kube/docker.py
  ydb/tools/ydbd_slice/kube/dynconfig.py
  ydb/tools/ydbd_slice/kube/handlers.py
  ydb/tools/ydbd_slice/nodes.py
Labels: not-for-changelog

#3614 fix scanner deadlock and memory overhead usage
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/counters/scan.cpp
  ydb/core/tx/columnshard/counters/scan.h
  ydb/core/tx/columnshard/engines/reader/abstract/abstract.h
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/iterator.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/iterator.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/plain_read_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/iterator.h
Labels: performance

#3352 YQ-3010 Check fields count and types in raw format (s3 and pq)
  ydb/core/external_sources/object_storage.cpp
  ydb/core/external_sources/object_storage.h
  ydb/core/fq/libs/control_plane_storage/request_validators.h
  ydb/library/yql/providers/common/mkql/parser.cpp
  ydb/library/yql/providers/common/provider/yql_provider.cpp
  ydb/library/yql/providers/common/provider/yql_provider.h
  ydb/library/yql/providers/pq/provider/yql_pq_datasource_type_ann.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_datasource_type_ann.cpp
Labels: not-for-changelog

#3562 fix tpch column types
  ydb/public/lib/ydb_cli/commands/tpch_schema.sql
Labels: bugfix

#3626 Fix not piped processes in ydbd_slice
  ydb/tools/ydbd_slice/nodes.py
Labels: not-for-changelog

#3609 Support part size limit in case of request via kqp proxy service
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/common/kqp_event_impl.cpp
  ydb/core/protos/kqp.proto
  ydb/tests/functional/kqp/kqp_query_svc/main.cpp
  ydb/tests/functional/kqp/kqp_query_svc/ya.make
  ydb/tests/functional/kqp/ya.make
Labels: improvement

#3627 Fix static group status calculation logic
  ydb/core/mind/bscontroller/register_node.cpp
Labels: bugfix

#3629 split huge tests file
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/aggregations_ut.cpp
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/kqp/ut/olap/clickbench_ut.cpp
  ydb/core/kqp/ut/olap/helpers/aggregation.cpp
  ydb/core/kqp/ut/olap/helpers/aggregation.h
  ydb/core/kqp/ut/olap/helpers/get_value.cpp
  ydb/core/kqp/ut/olap/helpers/get_value.h
  ydb/core/kqp/ut/olap/helpers/local.cpp
  ydb/core/kqp/ut/olap/helpers/local.h
  ydb/core/kqp/ut/olap/helpers/query_executor.cpp
  ydb/core/kqp/ut/olap/helpers/query_executor.h
  ydb/core/kqp/ut/olap/helpers/typed_local.cpp
  ydb/core/kqp/ut/olap/helpers/typed_local.h
  ydb/core/kqp/ut/olap/helpers/writer.cpp
  ydb/core/kqp/ut/olap/helpers/writer.h
  ydb/core/kqp/ut/olap/helpers/ya.make
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/olap/statistics_ut.cpp
  ydb/core/kqp/ut/olap/sys_view_ut.cpp
  ydb/core/kqp/ut/olap/ya.make
Labels: not-for-changelog

#3628 [backups] fix windows build
  ydb/core/tx/replication/service/ya.make
Labels: not-for-changelog

#3554 YQ-3036 Update ttl on query modify
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_impl.h
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp
Labels: not-for-changelog

#3631 Add basic multithread tests fot MPMCRingQueue
  ydb/library/actors/queues/mpmc_ring_queue.cpp
  ydb/library/actors/queues/mpmc_ring_queue.h
  ydb/library/actors/queues/mpmc_ring_queue_ut_base.h
  ydb/library/actors/queues/mpmc_ring_queue_ut_multi_threads.cpp
  ydb/library/actors/queues/mpmc_ring_queue_ut_single_thread.cpp
  ydb/library/actors/queues/ut/ya.make
  ydb/library/actors/queues/ya.make
Labels: area/actorsystem, bugfix

#3642 Mute `ydb/library/yql/providers/generic/connector/tests`
  .github/config/muted_ya.txt
Labels: not-for-changelog

#3580 Use NO_BUILD_IF instead of empty library (relates YQL-17642), take II
  ydb/library/yql/udfs/common/hyperscan/ya.make
Labels: not-for-changelog, external

#3463 added QuotaStorage to tenantinfo response
  ydb/core/viewer/json_tenantinfo.h
  ydb/core/viewer/protos/viewer.proto
Labels: new-feature

#3077 Add analytical and operational nodes
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
Labels: not-for-changelog

#3639 add signals and logging
  ydb/core/tx/columnshard/counters/common/histogram.cpp
  ydb/core/tx/columnshard/counters/common/histogram.h
  ydb/core/tx/columnshard/counters/common/ya.make
  ydb/core/tx/columnshard/counters/engine_logs.h
  ydb/core/tx/columnshard/counters/scan.cpp
  ydb/core/tx/columnshard/counters/scan.h
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
Labels: improvement

#3643 Add metrics for TMPMCRingQueue
  ydb/library/actors/queues/mpmc_ring_queue.h
  ydb/library/actors/queues/mpmc_ring_queue_ut_multi_threads.cpp
Labels: area/actorsystem, bugfix

#3644 Warning on join hints for cross join
  ydb/library/yql/sql/v1/sql_select.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: improvement

#3648 Fixed ignoring --timeout option
  .github/config/muted_ya.txt
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_table.cpp
  ydb/tests/functional/ydb_cli/canondata/test_ydb_scripting.TestScriptingServiceHelp.test_help/result.output
  ydb/tests/functional/ydb_cli/canondata/test_ydb_scripting.TestScriptingServiceHelp.test_help_ex/result.output
  ydb/tests/functional/ydb_cli/test_ydb_scripting.py
Labels: bugfix

#3590 enable pgwire logging for pg-expirement
  ydb/tests/library/harness/kikimr_config.py
Labels: not-for-changelog

#3216 Git ignore .clangd files
  .gitignore
Labels: not-for-changelog

#3655 Check .attr files too
  ydb/library/yql/tests/sql/dq_file.py
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_file.py
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: not-for-changelog

#3661 improve/fix schema snapshot test
  ydb/core/tablet_flat/flat_executor_ut.cpp
Labels: not-for-changelog

#3658 checkpoint hangup has been fixed
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_channels.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/runtime/dq_input_impl.h
  ydb/tests/fq/yds/test_yq_streaming.py
Labels: bugfix

#3638 do not check explicit sources every cleanup
  ydb/core/persqueue/sourceid.cpp
  ydb/core/persqueue/sourceid.h
  ydb/core/persqueue/ut/sourceid_ut.cpp
Labels: bugfix

#3668 test TxUsage.WriteTopic is broken
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: not-for-changelog

#3670 Fix for empty name in rpc
  ydb/core/grpc_services/rpc_node_registration.cpp
Labels: not-for-changelog
