Repository ydb-platform/ydb, pull requests merged in 2024-01, with the labels that each got.

#897 Refactor thread ctx, KIKIMR-18440
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/executor_thread_ctx.h
Labels: area/actorsystem

#903 Add shared executor thread, KIKIMR-18440
  ydb/core/testlib/actor_helpers.cpp
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/util/testactorsys.h
  ydb/library/actors/core/actor.h
  ydb/library/actors/core/actor_ut.cpp
  ydb/library/actors/core/executor_pool_base.h
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_pool_io.cpp
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/executor_thread.h
  ydb/library/actors/core/executor_thread_ctx.h
  ydb/library/actors/core/worker_context.h
  ydb/library/actors/testlib/test_runtime.cpp
Labels: area/actorsystem

#933 Add shared executor pool, KIKIMR-18440
  ydb/library/actors/core/config.h
  ydb/library/actors/core/cpu_manager.cpp
  ydb/library/actors/core/cpu_manager.h
  ydb/library/actors/core/executor_pool.h
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_pool_basic_ut.cpp
  ydb/library/actors/core/executor_pool_shared.cpp
  ydb/library/actors/core/executor_pool_shared.h
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/executor_thread.h
  ydb/library/actors/core/executor_thread_ctx.h
  ydb/library/actors/core/ya.make
Labels: area/actorsystem

#811 added article about goose into docs
  ydb/docs/en/core/_assets/goose-ydb-ui-after-first-migration.png
  ydb/docs/en/core/_assets/goose-ydb-ui-after-second-migration.png
  ydb/docs/en/core/integrations/goose.md
  ydb/docs/en/core/integrations/toc_i.yaml
  ydb/docs/ru/core/_assets/goose-ydb-ui-after-first-migration.png
  ydb/docs/ru/core/_assets/goose-ydb-ui-after-second-migration.png
  ydb/docs/ru/core/integrations/goose.md
  ydb/docs/ru/core/integrations/toc_i.yaml
Labels: documentation

#983 Cancel previous jobs on re-push changes from PR branch
  .github/workflows/allowed_dirs.yml
  .github/workflows/docs_preview.yaml
  .github/workflows/docs_release.yaml
Labels: area/ci

#982 Scale screenshot images in goose article
  ydb/docs/en/core/integrations/goose.md
  ydb/docs/ru/core/integrations/goose.md
Labels: documentation

#434 [docs] YDBDOCS-98: mention Sentinel in selfheal.md
  ydb/docs/en/core/maintenance/manual/selfheal.md
  ydb/docs/ru/core/maintenance/manual/selfheal.md
Labels: documentation

#435 [docs] YDBDOCS-230: update primitive types restrictions
  ydb/docs/en/core/yql/reference/yql-core/types/_includes/datatypes_primitive_number.md
  ydb/docs/ru/core/yql/reference/yql-core/types/_includes/datatypes_primitive_number.md
Labels: documentation

#1083 Revert "Disable coordinator if no ingress tasks (#472)"
  ydb/core/fq/libs/checkpointing/checkpoint_coordinator.cpp
  ydb/core/fq/libs/checkpointing/ut/checkpoint_coordinator_ut.cpp
Labels: not-for-changelog

#1082 fix build test olap stats
  ydb/core/kqp/ut/olap/kqp_olap_stats_ut.cpp
Labels: bugfix

#1081 Make test actorsystem actor id globally unique #1087
  ydb/core/util/testactorsys.h
Labels: bugfix

#1088 general steps for data fetching
  ydb/core/formats/arrow/arrow_filter.cpp
  ydb/core/formats/arrow/arrow_filter.h
  ydb/core/tx/columnshard/columnshard__read_base.cpp
  ydb/core/tx/columnshard/columnshard__scan.cpp
  ydb/core/tx/columnshard/columnshard__scan.h
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/columns_set.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/columns_set.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/committed_assembler.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/committed_assembler.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/fetched_data.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/fetched_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/fetching.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/filter_assembler.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/filter_assembler.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/interval.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/plain_read_data.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/scanner.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/source.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/source.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/ya.make
  ydb/core/tx/columnshard/engines/reader/read_context.h
  ydb/core/tx/columnshard/engines/reader/read_metadata.cpp
  ydb/core/tx/columnshard/engines/reader/read_metadata.h
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.h
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/splitter/batch_slice.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: improvement

#1101 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#1098 YQ-2744: add tpc bucket option for ydb workload tpch
  ydb/public/lib/ydb_cli/commands/tpch.cpp
  ydb/public/lib/ydb_cli/commands/tpch.h
  ydb/public/lib/ydb_cli/commands/tpch_schema.sql
  ydb/public/lib/ydb_cli/commands/ya.make
Labels: new-feature

#1096 add limits for simultaneous compaction
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/engines/storage/optimizer/lbuckets/optimizer.h
Labels: improvement

#1093 Implemented RemoteTopicReader KIKIMR-20306
  ydb/core/base/events.h
  ydb/core/tx/replication/service/table_writer.cpp
  ydb/core/tx/replication/service/table_writer.h
  ydb/core/tx/replication/service/topic_reader.cpp
  ydb/core/tx/replication/service/topic_reader.h
  ydb/core/tx/replication/service/worker.cpp
  ydb/core/tx/replication/service/worker.h
  ydb/core/tx/replication/service/ya.make
  ydb/library/services/services.proto
Labels: not-for-changelog, new-feature

#1125 Fix typo
  ydb/library/benchmarks/queries/tpcds/pg/q34.sql
Labels: bugfix

#1117 Skip empty description in pr_labels.yaml workflow
  .github/workflows/pr_labels.yaml
Labels: not-for-changelog

#1123 (refactoring) Move TSchemeCacheHelpers to core/tx/scheme_cache KIKIMR-20673
  ydb/core/tx/datashard/change_exchange_split.cpp
  ydb/core/tx/datashard/change_sender_async_index.cpp
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/change_sender_common_ops.h
  ydb/core/tx/scheme_cache/helpers.h
Labels: not-for-changelog, new-feature

#1116 Report status for static group
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/self_heal.cpp
Labels: new-feature

#1131 fix namings
  ydb/core/tx/columnshard/blob_manager.h
  ydb/core/tx/columnshard/blobs_action/abstract/action.h
  ydb/core/tx/columnshard/blobs_action/abstract/remove.h
  ydb/core/tx/columnshard/blobs_action/abstract/write.h
  ydb/core/tx/columnshard/blobs_action/bs/remove.h
  ydb/core/tx/columnshard/blobs_action/bs/write.cpp
  ydb/core/tx/columnshard/blobs_action/bs/write.h
  ydb/core/tx/columnshard/blobs_action/memory.h
  ydb/core/tx/columnshard/blobs_action/tier/remove.h
  ydb/core/tx/columnshard/blobs_action/tier/write.cpp
  ydb/core/tx/columnshard/blobs_action/tier/write.h
Labels: not-for-changelog

#1134 YDB-1060 viewer nodes handler add missing sort
  ydb/core/viewer/json_nodes.h
Labels: new-feature

#1111 KIKIMR-18397 HC node restarts issue
  ydb/core/health_check/health_check.cpp
Labels: new-feature

#1138 Fix dates in TPC-DS/YQL-syntax
  ydb/library/benchmarks/queries/tpcds/yql/q58.sql
  ydb/library/benchmarks/queries/tpcds/yql/q83.sql
Labels: bugfix

#1127 Make MVCC always enabled and no longer optional KIKIMR-20802
  ydb/core/base/feature_flags.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/session_actor/kqp_tx.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
  ydb/core/kqp/ut/tx/kqp_tx_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/feature_flags.proto
  ydb/core/testlib/basics/feature_flags.h
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__init.cpp
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_pipeline.h
  ydb/core/tx/datashard/datashard_switch_mvcc_state.cpp
  ydb/core/tx/datashard/datashard_ut_kqp_errors.cpp
  ydb/core/tx/datashard/datashard_ut_minstep.cpp
  ydb/core/tx/datashard/datashard_ut_order.cpp
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/tx_proxy/datareq.cpp
  ydb/tests/functional/serverless/test_serverless.py
  ydb/tests/library/harness/kikimr_config.py
Labels: new-feature

#1110 Unify test case naming in ydb/library/yql/providers/generic/connector/tests
  ydb/library/yql/providers/generic/connector/tests/clickhouse.py
  ydb/library/yql/providers/generic/connector/tests/join.py
  ydb/library/yql/providers/generic/connector/tests/postgresql.py
  ydb/library/yql/providers/generic/connector/tests/test.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/base.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_datetime.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_missing_database.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_missing_table.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_positive_clickhouse.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_positive_common.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_positive_postgresql.py
  ydb/library/yql/providers/generic/connector/tests/test_cases/select_positive_postgresql_schema.py
  ydb/library/yql/providers/generic/connector/tests/utils/artifacts.py
  ydb/library/yql/providers/generic/connector/tests/utils/dqrun.py
  ydb/library/yql/providers/generic/connector/tests/utils/generate.py
  ydb/library/yql/providers/generic/connector/tests/utils/kqprun.py
  ydb/library/yql/providers/generic/connector/tests/utils/log.py
  ydb/library/yql/providers/generic/connector/tests/utils/postgresql.py
  ydb/library/yql/providers/generic/connector/tests/utils/runner.py
  ydb/library/yql/providers/generic/connector/tests/utils/schema.py
  ydb/library/yql/providers/generic/connector/tests/utils/ya.make
Labels: not-for-changelog

#1148 S3 storage class workaround for minio
  ydb/core/wrappers/s3_storage.cpp
Labels: bugfix

#1094 Rename values of ServerlessComputeResourcesMode enum KIKIMR-20642
  ydb/core/base/subdomain.h
  ydb/core/discovery/discovery.cpp
  ydb/core/mind/hive/domain_info.cpp
  ydb/core/mind/hive/hive_domains.cpp
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/protos/subdomains.proto
  ydb/core/testlib/tablet_helpers.cpp
  ydb/core/tx/scheme_cache/scheme_cache.h
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_extsubdomain.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_extsubdomain.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/ut_serverless/ut_serverless.cpp
  ydb/core/tx/schemeshard/ut_serverless_reboots/ut_serverless_reboots.cpp
  ydb/tests/functional/serverless/conftest.py
  ydb/tests/functional/serverless/test_serverless.py
Labels: not-for-changelog

#1139 fix missing breaks CLOUD-174018
  ydb/core/mind/hive/storage_balancer.cpp
Labels: not-for-changelog

#1130 use policies for memory prediction on compaction
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/general_compaction.h
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lbuckets/optimizer.h
Labels: improvement

#1147 use splitter for abstract data chunks. not columns only
  ydb/core/tx/columnshard/blob.h
  ydb/core/tx/columnshard/columnshard_schema.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/cleanup.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/column_cursor.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/column_cursor.h
  ydb/core/tx/columnshard/engines/changes/compaction/column_portion_chunk.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/column_portion_chunk.h
  ydb/core/tx/columnshard/engines/changes/compaction/merged_column.cpp
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/with_blobs.h
  ydb/core/tx/columnshard/engines/scheme/column_features.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/splitter/batch_slice.cpp
  ydb/core/tx/columnshard/splitter/batch_slice.h
  ydb/core/tx/columnshard/splitter/blob_info.cpp
  ydb/core/tx/columnshard/splitter/blob_info.h
  ydb/core/tx/columnshard/splitter/chunks.cpp
  ydb/core/tx/columnshard/splitter/chunks.h
  ydb/core/tx/columnshard/splitter/column_info.h
  ydb/core/tx/columnshard/splitter/rb_splitter.cpp
  ydb/core/tx/columnshard/splitter/rb_splitter.h
  ydb/core/tx/columnshard/splitter/simple.cpp
  ydb/core/tx/columnshard/splitter/simple.h
  ydb/core/tx/columnshard/splitter/ut/ut_splitter.cpp
  ydb/library/accessor/validator.cpp
  ydb/library/accessor/validator.h
  ydb/library/accessor/ya.make
Labels: improvement

#1160 Fix bulk upsert writing to freshly indexed table due to a race KIKIMR-20765
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/datashard_common_upload.cpp
  ydb/core/tx/datashard/datashard_ut_upload_rows.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: bugfix

#1152 (refactoring) Split TEvChangeExchange into two parts: common & DS KIKIMR-20673
  ydb/core/base/events.h
  ydb/core/change_exchange/change_exchange.cpp
  ydb/core/change_exchange/change_exchange.h
  ydb/core/change_exchange/ya.make
  ydb/core/tx/datashard/change_exchange.cpp
  ydb/core/tx/datashard/change_exchange.h
  ydb/core/tx/datashard/change_sender.cpp
  ydb/core/tx/datashard/change_sender_async_index.cpp
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/change_sender_common_ops.cpp
  ydb/core/tx/datashard/change_sender_common_ops.h
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard_change_sending.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/schemeshard/ut_index/ut_async_index.cpp
Labels: not-for-changelog, new-feature

#1171 ydb/tests/tools: change PY23_LIBRARY -> PY3_LIBRARY
  ydb/tests/tools/docker_compose_helpers/ya.make
  ydb/tests/tools/fq_runner/kikimr_runner.py
  ydb/tests/tools/fq_runner/ya.make
Labels: not-for-changelog, new-feature

#1159 Unittest for mirror-3-dc IndexRestoreGet
  ydb/core/blobstorage/ut_blobstorage/mirror3dc.cpp
  ydb/core/blobstorage/ut_blobstorage/ya.make
Labels: new-feature

#1104 add sensors for metadata cache KIKIMR-20775
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/grpc_services/db_metadata_cache.h
  ydb/core/testlib/test_client.cpp
Labels: improvement

#1178 YQL-16026: Remove PG tests char.sql and varchar.sql from ignored
  ydb/library/yql/tests/postgresql/cases/char.err
  ydb/library/yql/tests/postgresql/cases/char.err.1
  ydb/library/yql/tests/postgresql/cases/char.err.2
  ydb/library/yql/tests/postgresql/cases/char.out
  ydb/library/yql/tests/postgresql/cases/char.sql
  ydb/library/yql/tests/postgresql/cases/json.err
  ydb/library/yql/tests/postgresql/cases/jsonb.err
  ydb/library/yql/tests/postgresql/cases/varchar.err
  ydb/library/yql/tests/postgresql/cases/varchar.err.1
  ydb/library/yql/tests/postgresql/cases/varchar.err.2
  ydb/library/yql/tests/postgresql/cases/varchar.out
  ydb/library/yql/tests/postgresql/cases/varchar.sql
  ydb/library/yql/tests/postgresql/cases/window.err
  ydb/library/yql/tests/postgresql/make-tests.sh
  ydb/library/yql/tests/postgresql/pg_tests.csv
  ydb/library/yql/tests/postgresql/status.md
  ydb/library/yql/tests/postgresql/status.old
Labels: not-for-changelog

#1182 scheme tests have been fixed
  ydb/core/testlib/test_client.cpp
Labels: bugfix, performance

#1186 Fix ShardHint for read actor
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
Labels: bugfix

#1170 docs: fix typo
  ydb/docs/en/core/getting_started/self_hosted/_includes/ydb_docker/02_install.md
Labels: documentation

#1192 Fix build KIKIMR-20673
  ydb/core/tx/datashard/datashard_ut_upload_rows.cpp
Labels: not-for-changelog, new-feature

#1164 replace into olap table
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/host/kqp_type_ann.cpp
  ydb/core/kqp/opt/kqp_opt_build_txs.cpp
  ydb/core/kqp/opt/kqp_opt_effects.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_source.cpp
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_actor.h
  ydb/core/kqp/runtime/ya.make
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/kqp_physical.proto
  ydb/core/tx/data_events/columnshard_splitter.h
  ydb/core/tx/data_events/shards_splitter.h
Labels: new-feature

#1180 Scheme correction for indexes usage
  ydb/core/formats/arrow/hash/calcer.cpp
  ydb/core/formats/arrow/hash/calcer.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/upsert_index.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/operations/upsert_index.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/ya.make
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract.h
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom.h
  ydb/core/tx/columnshard/engines/scheme/indexes/ya.make
  ydb/core/tx/columnshard/engines/scheme/ya.make
  ydb/core/tx/columnshard/splitter/ut/ut_splitter.cpp
  ydb/core/tx/columnshard/splitter/ut/ya.make
  ydb/core/tx/schemeshard/olap/columns/schema.cpp
  ydb/core/tx/schemeshard/olap/columns/schema.h
  ydb/core/tx/schemeshard/olap/columns/update.cpp
  ydb/core/tx/schemeshard/olap/columns/update.h
  ydb/core/tx/schemeshard/olap/columns/ya.make
  ydb/core/tx/schemeshard/olap/common/common.cpp
  ydb/core/tx/schemeshard/olap/common/common.h
  ydb/core/tx/schemeshard/olap/common/ya.make
  ydb/core/tx/schemeshard/olap/indexes/schema.cpp
  ydb/core/tx/schemeshard/olap/indexes/schema.h
  ydb/core/tx/schemeshard/olap/indexes/update.cpp
  ydb/core/tx/schemeshard/olap/indexes/update.h
  ydb/core/tx/schemeshard/olap/indexes/ya.make
  ydb/core/tx/schemeshard/olap/operations/alter_store.cpp
  ydb/core/tx/schemeshard/olap/operations/alter_table.cpp
  ydb/core/tx/schemeshard/olap/operations/create_store.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_store.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_table.cpp
  ydb/core/tx/schemeshard/olap/operations/ya.make
  ydb/core/tx/schemeshard/olap/schema/schema.cpp
  ydb/core/tx/schemeshard/olap/schema/schema.h
  ydb/core/tx/schemeshard/olap/schema/update.cpp
  ydb/core/tx/schemeshard/olap/schema/update.h
  ydb/core/tx/schemeshard/olap/schema/ya.make
  ydb/core/tx/schemeshard/olap/ya.make
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_olap_types.cpp
  ydb/core/tx/schemeshard/schemeshard_olap_types.h
  ydb/core/tx/schemeshard/schemeshard_validate_ttl.cpp
  ydb/core/tx/schemeshard/ya.make
  ydb/services/bg_tasks/abstract/interface.cpp
  ydb/services/bg_tasks/abstract/interface.h
Labels: new-feature

#1150 S3 add switch for virtual style addressing
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
  ydb/core/tx/schemeshard/schemeshard_import_flow_proposals.cpp
  ydb/core/wrappers/s3_storage.h
  ydb/core/wrappers/s3_storage_config.cpp
  ydb/core/wrappers/s3_storage_config.h
  ydb/public/api/protos/ydb_export.proto
  ydb/public/api/protos/ydb_import.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_export.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_export.h
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.h
  ydb/public/sdk/cpp/client/ydb_export/export.cpp
  ydb/public/sdk/cpp/client/ydb_import/import.cpp
  ydb/public/sdk/cpp/client/ydb_types/s3_settings.h
Labels: improvement

#1145 Fix unknown type name 'size_t' in actors/core/buffer
  ydb/library/actors/core/buffer.h
Labels: not-for-changelog

#1198 DebugString methods for debug prints
  ydb/core/formats/arrow/program.h
  ydb/core/tx/columnshard/splitter/stats.h
  ydb/core/tx/program/program.cpp
  ydb/core/tx/program/program.h
Labels: improvement

#1187 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1032 Fix 404 and fix files names.
  ydb/docs/en/core/_includes/alerts/no-translation.md
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/concepts/datamodel/external_data_source.md
  ydb/docs/en/core/concepts/datamodel/external_table.md
  ydb/docs/en/core/concepts/datamodel/secrets.md
  ydb/docs/en/core/concepts/datamodel/toc_i.yaml
  ydb/docs/en/core/concepts/federated_query.md
  ydb/docs/en/core/concepts/federated_query/clickhouse.md
  ydb/docs/en/core/concepts/federated_query/index.md
  ydb/docs/en/core/concepts/federated_query/postgresql.md
  ydb/docs/en/core/concepts/federated_query/s3/external_data_source.md
  ydb/docs/en/core/concepts/federated_query/s3/external_table.md
  ydb/docs/en/core/concepts/federated_query/s3/formats.md
  ydb/docs/en/core/concepts/federated_query/s3/partition_projection.md
  ydb/docs/en/core/concepts/federated_query/s3/partitioning.md
  ydb/docs/en/core/concepts/federated_query/s3/toc_i.yaml
  ydb/docs/en/core/concepts/federated_query/s3/toc_p.yaml
  ydb/docs/en/core/concepts/federated_query/s3/write_data.md
  ydb/docs/en/core/concepts/federated_query/toc_i.yaml
  ydb/docs/en/core/concepts/federated_query/toc_p.yaml
  ydb/docs/en/core/concepts/toc_i.yaml
  ydb/docs/en/core/maintenance/backup_and_recovery.md
  ydb/docs/en/core/maintenance/manual/config-overview.md
  ydb/docs/en/core/maintenance/manual/dynamic-config-selectors.md
  ydb/docs/en/core/maintenance/manual/dynamic-config-volatile-config.md
  ydb/docs/en/core/maintenance/manual/dynamic-config.md
  ydb/docs/en/core/maintenance/manual/replacing_nodes.md
  ydb/docs/en/core/maintenance/manual/toc_i.yaml
  ydb/docs/en/core/operations/query_plans_optimization.md
  ydb/docs/en/core/operations/toc_i.yaml
  ydb/docs/en/core/reference/ydb-cli/_includes/commands.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/file_structure.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/import-file.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/index.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_conn.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_conn_procure_overlay.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_export.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_import.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/tools_dump.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/tools_restore.md
  ydb/docs/en/core/reference/ydb-cli/export-import/auth-s3.md
  ydb/docs/en/core/reference/ydb-cli/export-import/export-s3.md
  ydb/docs/en/core/reference/ydb-cli/export-import/file-structure.md
  ydb/docs/en/core/reference/ydb-cli/export-import/import-file.md
  ydb/docs/en/core/reference/ydb-cli/export-import/import-s3.md
  ydb/docs/en/core/reference/ydb-cli/export-import/index.md
  ydb/docs/en/core/reference/ydb-cli/export-import/toc_i.yaml
  ydb/docs/en/core/reference/ydb-cli/export-import/toc_p.yaml
  ydb/docs/en/core/reference/ydb-cli/export-import/tools-dump.md
  ydb/docs/en/core/reference/ydb-cli/export-import/tools-restore.md
  ydb/docs/en/core/reference/ydb-cli/export_import/_includes/index.md
  ydb/docs/en/core/reference/ydb-cli/export_import/file_structure.md
  ydb/docs/en/core/reference/ydb-cli/export_import/s3_export.md
  ydb/docs/en/core/reference/ydb-cli/export_import/s3_import.md
  ydb/docs/en/core/reference/ydb-cli/export_import/tools_dump.md
  ydb/docs/en/core/reference/ydb-cli/toc_i.yaml
  ydb/docs/redirects.yaml
Labels: documentation

#1207 Move TBaseChangeSender to ydb/core/change_exchange KIKIMR-20673
  ydb/core/change_exchange/change_sender_common_ops.cpp
  ydb/core/change_exchange/change_sender_common_ops.h
  ydb/core/change_exchange/change_sender_monitoring.cpp
  ydb/core/change_exchange/change_sender_monitoring.h
  ydb/core/change_exchange/ya.make
  ydb/core/tx/datashard/change_exchange_split.cpp
  ydb/core/tx/datashard/change_sender.cpp
  ydb/core/tx/datashard/change_sender_async_index.cpp
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/ya.make
Labels: not-for-changelog, new-feature

#1213 [YQL-17298] Fix data race on ICompare::TPtr
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
Labels: bugfix

#1206 fix coverity
  ydb/services/ext_index/metadata/extractor/hash_by_columns.cpp
Labels: bugfix

#1212 fix allow single partition optimization
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
Labels: bugfix

#1154 fix KqpRequestContext::TraceIdInErrorMessage KIKIMR-20753
  ydb/core/kqp/ut/scan/kqp_scan_ut.cpp
Labels: not-for-changelog

#1211 Fix malloc size
  ydb/library/yql/sql/pg/optimizer.cpp
Labels: bugfix

#1216 Fix external dep on opentelemetry
  ydb/library/actors/wilson/wilson_span.h
  ydb/library/actors/wilson/wilson_uploader.cpp
  ydb/library/actors/wilson/wilson_uploader.h
  ydb/library/actors/wilson/ya.make
Labels: not-for-changelog

#1195 [YQL-17621] fix ListUniqStable bug
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/core/type_ann/type_ann_list.cpp
  ydb/library/yql/core/type_ann/type_ann_list.h
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/list_uniq.sql
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
Labels: bugfix

#1218 Make ydb_root_common use only stderr to avoid command output pollution
  ydb/public/lib/ydb_cli/commands/ydb_root_common.cpp
  ydb/public/lib/ydb_cli/common/progress_bar.cpp
  ydb/public/lib/ydb_cli/import/import.cpp
Labels: bugfix

#1214 LocalTableWriter skeleton KIKIMR-20673
  ydb/core/change_exchange/change_sender_common_ops.cpp
  ydb/core/change_exchange/change_sender_common_ops.h
  ydb/core/tx/datashard/change_sender_async_index.cpp
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/replication/service/table_writer.cpp
  ydb/core/tx/replication/service/table_writer.h
  ydb/core/tx/replication/service/topic_reader.cpp
  ydb/core/tx/replication/service/ya.make
  ydb/core/tx/scheme_cache/helpers.h
Labels: not-for-changelog, new-feature

#1137 not null constraint fix for column addition
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/ut/scheme/kqp_constraints_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/protos/index_builder.proto
  ydb/core/testlib/basics/feature_flags.h
  ydb/core/tx/schemeshard/schemeshard__operation_alter_table.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__create.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_column_build/ut_column_build.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.h
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#1191 Add use local self heal option to ds tool
  ydb/apps/dstool/lib/dstool_cmd_cluster_set.py
Labels: not-for-changelog

#1237 fix counters KIKIMR-20841
  ydb/core/grpc_services/db_metadata_cache.h
Labels: not-for-changelog

#1233 Add missing <cstddef> include
  ydb/core/util/btree.h
  ydb/core/util/btree_common.h
Labels: not-for-changelog

#1201 remove useless call
  ydb/core/kqp/provider/yql_kikimr_results.cpp
Labels: not-for-changelog

#1226 fix break
  ydb/core/formats/arrow/converter.cpp
Labels: bugfix

#1232 improve switch
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
Labels: improvement

#1239 fix column build with indexed table
  ydb/core/kqp/ut/scheme/kqp_constraints_ut.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: not-for-changelog

#1236 Add shared logic to executor pool
  ydb/library/actors/core/actor_benchmark_helper.h
  ydb/library/actors/core/actor_ut.cpp
  ydb/library/actors/core/cpu_manager.cpp
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_pool_basic.h
  ydb/library/actors/core/executor_pool_shared.cpp
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/executor_thread_ctx.h
  ydb/library/actors/core/worker_context.h
Labels: area/actorsystem, experimental-feature

#1229 [YQL] add missing break in formatting code
  ydb/library/yql/sql/v1/format/sql_format.cpp
Labels: not-for-changelog

#1244 ci: run pr checks on a merge commit instead of the PR head, add rebase-and-check label support
  .github/workflows/build_and_test_ya.yml
  .github/workflows/build_and_test_ya_provisioned.yml
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#1240 Remove support for non-scan read columns requests
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__read_columns.cpp
  ydb/core/tx/datashard/datashard_impl.h
Labels: not-for-changelog

#1253 Add range read border to key sampler KIKIMR-20859
  ydb/core/tx/datashard/datashard__read_iterator.cpp
Labels: improvement

#1149 Show exclusive nodes in embedded ui KIKIMR-20675
  ydb/core/viewer/json_compute.h
  ydb/core/viewer/json_nodes.h
  ydb/core/viewer/json_tenantinfo.h
  ydb/core/viewer/viewer_ut.cpp
Labels: not-for-changelog

#1255 Cell maker lib & parsing from json KIKIMR-20673
  ydb/core/grpc_services/rpc_import_data.cpp
  ydb/core/grpc_services/ya.make
  ydb/core/io_formats/arrow/csv_arrow.cpp
  ydb/core/io_formats/arrow/csv_arrow.h
  ydb/core/io_formats/arrow/csv_arrow_ut.cpp
  ydb/core/io_formats/arrow/ut/ya.make
  ydb/core/io_formats/arrow/ya.make
  ydb/core/io_formats/cell_maker/cell_maker.cpp
  ydb/core/io_formats/cell_maker/cell_maker.h
  ydb/core/io_formats/cell_maker/ya.make
  ydb/core/io_formats/ya.make
  ydb/core/io_formats/ydb_dump/csv_ydb_dump.cpp
  ydb/core/io_formats/ydb_dump/csv_ydb_dump.h
  ydb/core/io_formats/ydb_dump/ya.make
  ydb/core/tx/datashard/import_s3.cpp
  ydb/core/tx/datashard/ya.make
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
  ydb/core/tx/tx_proxy/ya.make
Labels: not-for-changelog, new-feature

#1238 DS proxy mirror-3-dc restoration strategy test
  ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h
  ydb/core/blobstorage/dsproxy/ut_strategy/strategy_ut.cpp
  ydb/core/blobstorage/dsproxy/ut_strategy/ya.make
Labels: new-feature

#1256 the UseDeduplication flag for persqueue_v0
  ydb/services/deprecated/persqueue_v0/grpc_pq_write_actor.cpp
Labels: bugfix

#1264 ci: add actual merge commit sha instead of PR head in the PR commit
  .github/workflows/build_and_test_ya.yml
Labels: not-for-changelog

#1257 Fixed a minor bug in simplified plan JSON generation
  ydb/public/lib/ydb_cli/common/format.cpp
Labels: new-feature, bugfix

#1270 Json change record & serialization to TEvApplyReplicationChanges::TChange KIKIMR-20673
  ydb/core/change_exchange/change_record.h
  ydb/core/tx/datashard/change_record.h
  ydb/core/tx/replication/service/json_change_record.cpp
  ydb/core/tx/replication/service/json_change_record.h
  ydb/core/tx/replication/service/ya.make
Labels: not-for-changelog, new-feature

#1258 Remove second read stage during uniq index update
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_upsert_index.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
Labels: improvement

#1231 Make separate app data for different nodes in test actor system
  ydb/core/blobstorage/ut_blobstorage/blob_depot_test_env.h
  ydb/core/blobstorage/ut_blobstorage/blob_depot_test_functions.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/blobstorage/ut_blobstorage/monitoring.cpp
  ydb/core/blobstorage/ut_testshard/env.h
  ydb/core/mind/bscontroller/ut_selfheal/env.h
  ydb/core/util/testactorsys.cpp
  ydb/core/util/testactorsys.h
Labels: bugfix

#1242 YQ-2790 fixed uncaught exception in TS3FileWriteActor
  ydb/library/yql/providers/s3/actors/yql_s3_write_actor.cpp
  ydb/tests/tools/kqprun/kqprun.cpp
Labels: bugfix

#1047 KeyValue tracing sampling
  ydb/core/cms/json_proxy_proto.h
  ydb/core/control/common_controls/tracing_control.cpp
  ydb/core/control/common_controls/tracing_control.h
  ydb/core/control/common_controls/ya.make
  ydb/core/control/immediate_control_board_sampler.h
  ydb/core/control/immediate_control_board_throttler.h
  ydb/core/control/ya.make
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/grpc_services/base/base.h
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/grpc_services/grpc_request_proxy.h
  ydb/core/keyvalue/keyvalue_flat_impl.h
  ydb/core/keyvalue/ya.make
  ydb/core/protos/config.proto
  ydb/core/testlib/test_client.cpp
Labels: new-feature

#1272 Refactor GroupDiskRequests and remove unused stuff
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h
  ydb/core/blobstorage/dsproxy/dsproxy_cookies.h
  ydb/core/blobstorage/dsproxy/dsproxy_get.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_get_impl.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_get_impl.h
  ydb/core/blobstorage/dsproxy/dsproxy_put_impl.h
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
  ydb/core/blobstorage/dsproxy/ut/dsproxy_env_mock_ut.h
  ydb/core/blobstorage/dsproxy/ut/dsproxy_get_ut.cpp
  ydb/core/blobstorage/dsproxy/ut/dsproxy_sequence_ut.cpp
  ydb/core/blobstorage/dsproxy/ut/dsproxy_vdisk_mock_ut.h
  ydb/core/blobstorage/dsproxy/ut_strategy/strategy_ut.cpp
  ydb/core/blobstorage/ut_blobstorage/counting_events.cpp
Labels: new-feature

#1289 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1219 Add ExecuteMode to YQL plugin for YT. Support validate and explain modes
  ydb/library/yql/yt/bridge/interface.h
  ydb/library/yql/yt/dynamic/impl.cpp
  ydb/library/yql/yt/native/plugin.cpp
  ydb/library/yql/yt/plugin.h
Labels: new-feature

#1284 ci: don't override old PR build status comment on every build
  .github/scripts/tests/comment-pr.py
  .github/scripts/tests/generate-summary.py
  .github/scripts/tests/gh_status.py
Labels: not-for-changelog

#1283 Fix delete table
  ydb/core/tx/columnshard/counters/engine_logs.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
Labels: bugfix

#1297 YQ-2803 Move log to trace
  ydb/library/yql/dq/actors/compute/dq_compute_actor_checkpoints.cpp
Labels: not-for-changelog

#1293 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1290 validate & lineage modes in dqrun
  ydb/library/yql/tools/dqrun/dqrun.cpp
Labels: new-feature

#981 YDB-2321 Add subnet operations in IP UDF
  ydb/docs/en/core/yql/reference/yql-core/udf/list/ip.md
  ydb/docs/ru/core/yql/reference/yql-core/udf/list/ip.md
  ydb/library/yql/udfs/common/ip_base/lib/ip_base_udf.h
  ydb/library/yql/udfs/common/ip_base/test/canondata/result.json
  ydb/library/yql/udfs/common/ip_base/test/canondata/test.test_Subnets_/results.txt
  ydb/library/yql/udfs/common/ip_base/test/cases/Subnets.in
  ydb/library/yql/udfs/common/ip_base/test/cases/Subnets.in.attr
  ydb/library/yql/udfs/common/ip_base/test/cases/Subnets.sql
Labels: new-feature

#1309 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1316 Add Federated Query team to CODEOWNERS
  .github/CODEOWNERS
Labels: not-for-changelog

#1323 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1310 Support table changes observer KIKIMR-20853
  ydb/core/tablet_flat/CMakeLists.darwin-arm64.txt
  ydb/core/tablet_flat/CMakeLists.darwin-x86_64.txt
  ydb/core/tablet_flat/CMakeLists.linux-aarch64.txt
  ydb/core/tablet_flat/CMakeLists.linux-x86_64.txt
  ydb/core/tablet_flat/CMakeLists.windows-x86_64.txt
  ydb/core/tablet_flat/flat_database.cpp
  ydb/core/tablet_flat/flat_database.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_table.cpp
  ydb/core/tablet_flat/flat_table.h
  ydb/core/tablet_flat/flat_table_observer.cpp
  ydb/core/tablet_flat/flat_table_observer.h
  ydb/core/tablet_flat/tablet_flat_executor.cpp
  ydb/core/tablet_flat/tablet_flat_executor.h
  ydb/core/tablet_flat/ya.make
Labels: not-for-changelog

#1332 [docs] remove odd comment in topic.md and changelog-cli.md
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/reference/ydb-sdk/topic.md
Labels: documentation

#1334 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1315 Fix windows build for invoke_builtins/no_llvm
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.h.txt
Labels: new-feature

#1322 Table partition writer skeleton KIKIMR-20673
  ydb/core/tx/replication/service/json_change_record.cpp
  ydb/core/tx/replication/service/json_change_record.h
  ydb/core/tx/replication/service/table_writer.cpp
Labels: not-for-changelog, new-feature

#1307 YQL-17418 Support of Merge in lineage
  ydb/library/yql/core/services/yql_lineage.cpp
Labels: new-feature

#1327 YQL-17264 static part of tables
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/providers/pg/provider/yql_pg_datasource_type_ann.cpp
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_tables.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/tables.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/pgrun/pgrun.cpp
  ydb/library/yql/tools/sql2yql/sql2yql.cpp
  ydb/library/yql/tools/yqlrun/http/yql_server.cpp
  ydb/library/yql/tools/yqlrun/yqlrun.cpp
Labels: new-feature

#1280 Fix args order bug
  ydb/services/persqueue_v1/actors/partition_actor.cpp
Labels: new-feature

#1251 Move functionality to UserDb
  ydb/core/tx/datashard/build_distributed_erase_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/datashard__engine_host.cpp
  ydb/core/tx/datashard/datashard__engine_host.h
  ydb/core/tx/datashard/datashard_active_transaction.cpp
  ydb/core/tx/datashard/datashard_common_upload.cpp
  ydb/core/tx/datashard/datashard_direct_erase.cpp
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/core/tx/datashard/datashard_kqp.h
  ydb/core/tx/datashard/datashard_kqp_compute.cpp
  ydb/core/tx/datashard/datashard_kqp_compute.h
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/datashard_write_operation.h
  ydb/core/tx/datashard/execute_distributed_erase_tx_unit.cpp
  ydb/core/tx/datashard/key_validator.cpp
  ydb/core/tx/datashard/key_validator.h
  ydb/core/tx/datashard/write_unit.cpp
Labels: new-feature

#1263 Checking "not found or already stopped" status has been added to Stopper YQ-2797
  ydb/core/fq/libs/compute/ydb/stopper_actor.cpp
Labels: bugfix

#1249 s3 arrow converters have been added YQ-2570
  ydb/library/yql/providers/s3/actors/ya.make
  ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.cpp
  ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.h
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/tests/fq/s3/test_format_setting.py
Labels: improvement

#1291 Add arithmetic kernels for float & double.
  ydb/library/yql/core/arrow_kernels/registry/ut/registry_ut.cpp
  ydb/library/yql/minikql/arrow/mkql_functions.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_abs.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_add.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_div.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_equals.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_greater.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_greater_or_equal.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.h.txt
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_less.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_less_or_equal.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_minus.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_mod.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_mul.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_not_equals.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_string_kernels.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_sub.cpp
  ydb/library/yql/minikql/mkql_function_metadata.cpp
  ydb/library/yql/minikql/mkql_function_metadata.h
Labels: new-feature

#1313 Fix get return type for binary arithmetic.
  ydb/core/kqp/query_compiler/kqp_olap_compiler.cpp
Labels: bugfix

#1344 Make sure out-of-order volatile commits are not visible on followers …
  ydb/core/tablet/tablet_resolver.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
  ydb/core/tx/datashard/follower_edge.cpp
  ydb/core/tx/datashard/volatile_tx.cpp
  ydb/core/tx/datashard/volatile_tx.h
Labels: bugfix

#1349 Fix consistency check complaining about borrowed tx status parts KIKI…
  ydb/core/tablet_flat/flat_executor.cpp
Labels: bugfix

#1348 YQL-17678 throw exception instead of abort
  ydb/library/yql/minikql/mkql_terminator.cpp
  ydb/library/yql/minikql/mkql_terminator.h
  ydb/library/yql/providers/dq/actors/proto_builder.cpp
Labels: new-feature

#1345 TEvWriteResult STATUS_SCHEME_CHANGED
  ydb/core/protos/data_events.proto
  ydb/core/tx/datashard/datashard__write.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_write.h
Labels: new-feature

#1343 indexes construction on first compaction stage (from insert table to …
  ydb/core/formats/arrow/arrow_filter.h
  ydb/core/formats/arrow/hash/calcer.cpp
  ydb/core/formats/arrow/hash/calcer.h
  ydb/core/formats/arrow/ut/ut_hash.cpp
  ydb/core/formats/arrow/ut/ya.make
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/ssa.proto
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/source.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/composite.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/simple.h
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom/checker.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom/meta.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom/meta.h
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/splitter/batch_slice.h
  ydb/core/tx/columnshard/splitter/chunks.h
  ydb/core/tx/columnshard/splitter/rb_splitter.cpp
  ydb/core/tx/columnshard/splitter/rb_splitter.h
  ydb/core/tx/schemeshard/olap/indexes/schema.cpp
Labels: improvement

#1354 YQL-17264 static part of columns
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/catalog.h
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/providers/pg/provider/yql_pg_datasource_type_ann.cpp
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg_catalog/columns.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
Labels: new-feature

#1360 YQL-17583: DELETE with alias crash fix
  ydb/library/yql/sql/pg/pg_sql.cpp
  ydb/library/yql/tests/postgresql/cases/delete.err
  ydb/library/yql/tests/postgresql/cases/delete.out
  ydb/library/yql/tests/postgresql/cases/delete.sql
  ydb/library/yql/tests/postgresql/pg_tests.csv
  ydb/library/yql/tests/postgresql/status.md
Labels: bugfix

#1363 Add marker module for python sdk v3 new behaviour
  ydb/public/sdk/python/enable_v3_new_behavior/__init__.py
  ydb/public/sdk/python/enable_v3_new_behavior/ya.make
Labels: not-for-changelog

#1364 KIKIMR-20842: make error non-retryable again
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
Labels: new-feature

#1367 fix test for indexes
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: bugfix

#1365 Add TxOperators
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard__notify_tx_completion.cpp
  ydb/core/tx/columnshard/columnshard__progress_tx.cpp
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/transactions/operators/ev_write.cpp
  ydb/core/tx/columnshard/transactions/operators/ev_write.h
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.cpp
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.h
  ydb/core/tx/columnshard/transactions/operators/schema.cpp
  ydb/core/tx/columnshard/transactions/operators/schema.h
  ydb/core/tx/columnshard/transactions/operators/ya.make
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.h
  ydb/core/tx/columnshard/transactions/ya.make
  ydb/core/tx/columnshard/ya.make
Labels: improvement

#1352 Enable real arithmetic.
  ydb/core/kqp/opt/physical/kqp_opt_phy_olap_filter.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: new-feature

#1340 YQ-2708: add IAM credentials to protobuf
  ydb/library/yql/providers/generic/connector/api/common/data_source.proto
Labels: new-feature

#1373 Support --test-param for specifying logging level in KQP tests
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/common/ya.make
Labels: improvement

#1321 build: add a CI flow for Embedded UI refresh
  .github/workflows/embedded_ui_refresh.yaml
  ydb/core/viewer/ya.make
Labels: not-for-changelog

#1259 Check empty stats
  ydb/core/tx/columnshard/splitter/stats.cpp
Labels: bugfix

#1368 Fix counter for granules normalizer
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/granule/normalizer.cpp
  ydb/core/tx/columnshard/normalizer/granule/normalizer.h
  ydb/core/tx/columnshard/normalizer/portion/chunks.h
  ydb/core/tx/columnshard/normalizer/portion/min_max.h
Labels: bugfix

#1372 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1287 Fix kafka metadata actor for Topics.size() == 0 and fix read by short topic name
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.h
  ydb/core/kafka_proxy/actors/kafka_offset_commit_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_read_session_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_read_session_actor.h
Labels: new-feature

#1347 resolves #1346
  ydb/library/yql/tools/mrrun/README.md
  ydb/library/yql/tools/mrrun/mrrun.cpp
  ydb/library/yql/tools/mrrun/mrrun.h
  ydb/library/yql/tools/mrrun/ya.make
  ydb/library/yql/tools/ya.make
Labels: not-for-changelog

#1359 Fix PDisk log flush completion action use after free
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_state.h
Labels: bugfix

#1380 KIKIMR-20939: mute red test
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1358 YQL-17388: fix generate_series zero step
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/tests/postgresql/cases/int8.err
  ydb/library/yql/tests/postgresql/cases/int8.out
  ydb/library/yql/tests/postgresql/cases/int8.sql
  ydb/library/yql/tests/postgresql/cases/numeric.err
  ydb/library/yql/tests/postgresql/cases/numeric.out
  ydb/library/yql/tests/postgresql/cases/numeric.sql
  ydb/library/yql/tests/postgresql/cases/strings.err
  ydb/library/yql/tests/postgresql/cases/strings.out
  ydb/library/yql/tests/postgresql/cases/strings.sql
  ydb/library/yql/tests/postgresql/cases/timestamp.out
  ydb/library/yql/tests/postgresql/cases/timestamp.sql
  ydb/library/yql/tests/postgresql/cases/timestamptz.err
  ydb/library/yql/tests/postgresql/cases/timestamptz.out
  ydb/library/yql/tests/postgresql/cases/timestamptz.sql
  ydb/library/yql/tests/postgresql/pg_tests.csv
  ydb/library/yql/tests/postgresql/status.md
  ydb/library/yql/tests/postgresql/status.old
Labels: bugfix

#1378 Fix linker
  ydb/core/tx/columnshard/ya.make
Labels: not-for-changelog

#1375 fix mkql warnings
  ydb/library/yql/minikql/codegen/codegen.cpp
  ydb/library/yql/minikql/codegen/codegen_ut.cpp
  ydb/library/yql/minikql/codegen/ut/ya.make.inc
  ydb/library/yql/minikql/codegen/ya.make.inc
  ydb/library/yql/minikql/comp_nodes/llvm/ut/ya.make
  ydb/library/yql/minikql/comp_nodes/llvm/ya.make
  ydb/library/yql/minikql/comp_nodes/llvm14/ut/ya.make
  ydb/library/yql/minikql/comp_nodes/llvm14/ya.make
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_compress.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_top.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_blocks.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_chopper.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_decimal_mod.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_discard.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_ensure.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_extend.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_flow.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_fromstring.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_logical.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_map_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_size.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_squeeze_to_list.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_switch.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_todict.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_tostring.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_chopper.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_filter.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_map.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_withcontext.cpp
  ydb/library/yql/minikql/computation/llvm/ut/ya.make
  ydb/library/yql/minikql/computation/llvm/ya.make
  ydb/library/yql/minikql/computation/llvm14/ut/ya.make
  ydb/library/yql/minikql/computation/llvm14/ya.make
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_pack_ut.cpp
  ydb/library/yql/minikql/invoke_builtins/llvm/ya.make
  ydb/library/yql/minikql/invoke_builtins/llvm14/ya.make
  ydb/library/yql/parser/pg_catalog/catalog.cpp
Labels: new-feature

#1379 [YQL-16903] Support BlockEngine=auto/force/disable (peephole + channels)
  ydb/library/yql/core/expr_nodes/yql_expr_nodes.json
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/dq/opt/dq_opt_build.cpp
  ydb/library/yql/dq/opt/dq_opt_build.h
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
Labels: experimental-feature

#1371 sys view and drop method for indexes
  ydb/core/kqp/gateway/behaviour/tablestore/operations/drop_index.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/operations/drop_index.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/ya.make
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/sys_view/common/schema.h
  ydb/core/tx/columnshard/columnshard__stats_scan.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/reader/read_metadata.h
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/constructor.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.h
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom/constructor.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom/constructor.h
  ydb/core/tx/columnshard/engines/scheme/indexes/bloom/meta.h
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
  ydb/core/tx/schemeshard/olap/indexes/schema.cpp
Labels: improvement

#1387 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#1395 fix pg sql warnings
  ydb/library/yql/sql/pg/optimizer.cpp
  ydb/library/yql/sql/pg/optimizer_impl_ut.cpp
  ydb/library/yql/sql/pg/optimizer_ut.cpp
  ydb/library/yql/sql/pg/pg_sql.cpp
  ydb/library/yql/sql/pg/ut/ya.make
  ydb/library/yql/sql/pg/ya.make
Labels: new-feature

#1391 (refactoring) UT helpers lib KIKIMR-20902
  ydb/core/tx/replication/ut_helpers/test_env.h
  ydb/core/tx/replication/ut_helpers/ya.make
  ydb/core/tx/replication/ydb_proxy/ut/ya.make
  ydb/core/tx/replication/ydb_proxy/ydb_proxy_ut.cpp
Labels: not-for-changelog, new-feature

#1397 YQL-17343 information_schema.table_constraints
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg_catalog/table_constraints.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
Labels: new-feature

#1394 fix sql2yql warnings
  ydb/library/yql/tools/sql2yql/sql2yql.cpp
  ydb/library/yql/tools/sql2yql/ya.make
Labels: new-feature

#1333 Fixes for replace select
  ydb/core/base/appdata_fwd.h
  ydb/core/formats/arrow/arrow_batch_builder.cpp
  ydb/core/formats/arrow/arrow_batch_builder.h
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: bugfix

#1306 JsonDocument support added YQL-17658
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
Labels: new-feature

#1401 Do not lock already locked node KIKIMR-20904
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/node_checkers.cpp
  ydb/core/cms/node_checkers.h
Labels: not-for-changelog

#1318 [YQ-1997] OR REPLACE grammar support for EXTERNAL DATA SOURCE and EXTERNAL TABLE
  ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/gateway/utils/scheme_helpers.cpp
  ydb/core/kqp/gateway/utils/scheme_helpers.h
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_expr_nodes.json
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_gateway_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/format/sql_format_ut.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/object_processing.h
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/source.h
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
  ydb/services/metadata/abstract/parsing.h
Labels: new-feature

#1407 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1413 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1409 Fix empty yaml config handling in ydb cli
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.cpp
Labels: bugfix

#1381 Use EnableForceFollowers in some datashard tests
  ydb/core/tx/datashard/datashard_ut_followers.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
Labels: not-for-changelog

#1404 Blocks for first stages
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: improvement

#1223 Health check for exclusive dynamic nodes KIKIMR-20818
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
  ydb/public/api/protos/out/out.cpp
Labels: not-for-changelog

#1393 create statistics aggregator tablet during migration
  ydb/core/protos/statistics.proto
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/aggregator_impl.h
  ydb/core/statistics/aggregator/tx_init.cpp
  ydb/core/statistics/events.h
  ydb/core/statistics/stat_service.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/schemeshard_svp_migration.cpp
  ydb/core/tx/schemeshard/schemeshard_svp_migration.h
  ydb/library/services/services.proto
Labels: new-feature
