Repository ydb-platform/ydb, pull requests merged in 2024-02, with the labels that each got.

#1454 Remove TActiveTransaction from datashard_kqp.h
  ydb/core/tx/datashard/build_kqp_data_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/datashard__engine_host.cpp
  ydb/core/tx/datashard/datashard__engine_host.h
  ydb/core/tx/datashard/datashard_active_transaction.cpp
  ydb/core/tx/datashard/datashard_active_transaction.h
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/core/tx/datashard/datashard_kqp.h
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/datashard_write_operation.h
  ydb/core/tx/datashard/execute_kqp_data_tx_unit.cpp
Labels: improvement

#1472 type TPartitionId
  ydb/core/persqueue/account_read_quoter.cpp
  ydb/core/persqueue/account_read_quoter.h
  ydb/core/persqueue/blob.cpp
  ydb/core/persqueue/blob.h
  ydb/core/persqueue/cache_eviction.h
  ydb/core/persqueue/event_helpers.cpp
  ydb/core/persqueue/event_helpers.h
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/key.h
  ydb/core/persqueue/ownerinfo.cpp
  ydb/core/persqueue/ownerinfo.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_id.h
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/partition_init.h
  ydb/core/persqueue/partition_monitoring.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/partition_sourcemanager.cpp
  ydb/core/persqueue/partition_sourcemanager.h
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/read.h
  ydb/core/persqueue/read_quoter.h
  ydb/core/persqueue/sourceid.cpp
  ydb/core/persqueue/sourceid.h
  ydb/core/persqueue/subscriber.cpp
  ydb/core/persqueue/subscriber.h
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
  ydb/core/persqueue/ut/common/pq_ut_common.cpp
  ydb/core/persqueue/ut/internals_ut.cpp
  ydb/core/persqueue/ut/partition_ut.cpp
  ydb/core/persqueue/ut/pq_ut.cpp
  ydb/core/persqueue/ut/sourceid_ut.cpp
Labels: improvement

#1511 Drop LLVM12
  ydb/library/yql/minikql/codegen/llvm/ut/ya.make
  ydb/library/yql/minikql/codegen/llvm/ya.make
  ydb/library/yql/minikql/codegen/ya.make
  ydb/library/yql/minikql/comp_nodes/llvm/CMakeLists.darwin-arm64.txt
  ydb/library/yql/minikql/comp_nodes/llvm/CMakeLists.darwin-x86_64.txt
  ydb/library/yql/minikql/comp_nodes/llvm/CMakeLists.linux-aarch64.txt
  ydb/library/yql/minikql/comp_nodes/llvm/CMakeLists.linux-x86_64.txt
  ydb/library/yql/minikql/comp_nodes/llvm/CMakeLists.txt
  ydb/library/yql/minikql/comp_nodes/llvm/CMakeLists.windows-x86_64.txt
  ydb/library/yql/minikql/comp_nodes/llvm/ut/ya.make
  ydb/library/yql/minikql/comp_nodes/llvm/ya.make
  ydb/library/yql/minikql/comp_nodes/ya.make
  ydb/library/yql/minikql/computation/llvm/CMakeLists.darwin-arm64.txt
  ydb/library/yql/minikql/computation/llvm/CMakeLists.darwin-x86_64.txt
  ydb/library/yql/minikql/computation/llvm/CMakeLists.linux-aarch64.txt
  ydb/library/yql/minikql/computation/llvm/CMakeLists.linux-x86_64.txt
  ydb/library/yql/minikql/computation/llvm/CMakeLists.txt
  ydb/library/yql/minikql/computation/llvm/CMakeLists.windows-x86_64.txt
  ydb/library/yql/minikql/computation/llvm/ut/ya.make
  ydb/library/yql/minikql/computation/llvm/ya.make
  ydb/library/yql/minikql/computation/ya.make
  ydb/library/yql/minikql/invoke_builtins/llvm/CMakeLists.darwin-arm64.txt
  ydb/library/yql/minikql/invoke_builtins/llvm/CMakeLists.darwin-x86_64.txt
  ydb/library/yql/minikql/invoke_builtins/llvm/CMakeLists.linux-aarch64.txt
  ydb/library/yql/minikql/invoke_builtins/llvm/CMakeLists.linux-x86_64.txt
  ydb/library/yql/minikql/invoke_builtins/llvm/CMakeLists.txt
  ydb/library/yql/minikql/invoke_builtins/llvm/CMakeLists.windows-x86_64.txt
  ydb/library/yql/minikql/invoke_builtins/llvm/ut/ya.make
  ydb/library/yql/minikql/invoke_builtins/llvm/ya.make
  ydb/library/yql/minikql/invoke_builtins/ya.make
  ydb/library/yql/providers/yt/comp_nodes/llvm/ya.make
  ydb/library/yql/providers/yt/comp_nodes/ya.make
Labels: new-feature

#1512 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1516 Mute flaky kv tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1509 Document proto bytes field decoding with a test
  ydb/library/yaml_config/yaml_config_parser.cpp
  ydb/library/yaml_config/yaml_config_parser.h
  ydb/library/yaml_config/yaml_config_ut.cpp
Labels: not-for-changelog

#1513 Initialize fields needed for CA (preps for WA removing)
  ydb/library/yql/providers/dq/global_worker_manager/global_worker_manager_ut.cpp
  ydb/library/yql/providers/dq/global_worker_manager/ut/ya.make
Labels: not-for-changelog

#1517 [yql] Plan: add InputSections (YQL-17549)
  ydb/library/yql/providers/yt/provider/yql_yt_datasink.cpp
  ydb/library/yql/tests/s-expressions/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: improvement

#1505 optimizer predicates usage on fetching
  ydb/core/tx/columnshard/engines/predicate/filter.cpp
  ydb/core/tx/columnshard/engines/predicate/filter.h
  ydb/core/tx/columnshard/engines/predicate/range.cpp
  ydb/core/tx/columnshard/engines/predicate/range.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/plain_read_data.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/source.h
  ydb/core/tx/columnshard/engines/reader/read_metadata.cpp
Labels: performance

#1499 random shuffle has been fixed YQ-2797
  ydb/core/fq/libs/control_plane_storage/internal/task_get.cpp
Labels: bugfix

#1377 KIKIMR-20082: TableStore/ColumnTable with QueryService
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/kqp_physical.proto
Labels: new-feature

#1524 Fix yaml-config requirement
  ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp
Labels: not-for-changelog

#1533 Enable cmake workflow to build a specified target
  .github/actions/build/action.yml
  .github/workflows/build_and_test_provisioned.yml
Labels: not-for-changelog

#1531 Fix Defragmentation::DoesItWork unit test
  .github/config/muted_ya.txt
  ydb/core/blobstorage/ut_blobstorage/defrag.cpp
Labels: not-for-changelog

#1460 Init yt dq jobs
  ydb/library/yql/providers/dq/actors/yt/resource_manager.h
  ydb/library/yql/providers/dq/actors/yt/yt_resource_manager.cpp
  ydb/library/yql/tools/dq/worker_job/dq_worker.cpp
  ydb/library/yql/yt/dq_vanilla_job.lite/main.cpp
  ydb/library/yql/yt/dq_vanilla_job.lite/ya.make
  ydb/library/yql/yt/dq_vanilla_job/main.cpp
  ydb/library/yql/yt/dq_vanilla_job/ya.make
  ydb/library/yql/yt/ya.make
Labels: not-for-changelog

#1534 YQL-15682 Cleanup previous yson attributes
  ydb/library/yql/udfs/common/yson2/test/canondata/test.test_WithAttrs_/results.txt
  ydb/library/yql/udfs/common/yson2/test/cases/WithAttrs.sql
  ydb/library/yql/udfs/common/yson2/yson2_udf.cpp
Labels: new-feature

#1543 Unmute working tests
  .github/config/muted_ya.txt
  ydb/core/blobstorage/ut_blobstorage/ya.make
Labels: not-for-changelog

#1376 Remove broken optimizer YQL-17555
  ydb/library/yql/providers/dq/opt/physical_optimize.cpp
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
Labels: not-for-changelog

#1518 ignore set escape_string_warning
  ydb/library/yql/sql/pg/pg_sql.cpp
Labels: new-feature

#1528 YQL-17725 unicode string literals
  ydb/library/yql/core/issue/protos/issue_id.proto
  ydb/library/yql/core/issue/yql_issue.txt
  ydb/library/yql/sql/settings/translation_settings.h
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/context.cpp
  ydb/library/yql/sql/v1/context.h
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/unicode_literals.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
Labels: new-feature

#1406 Add yaml config support to ydbd_slice
  ydb/tools/ydbd_slice/__init__.py
  ydb/tools/ydbd_slice/kube/dynconfig.py
  ydb/tools/ydbd_slice/kube/generate.py
  ydb/tools/ydbd_slice/kube/handlers.py
  ydb/tools/ydbd_slice/kube/templates/common/dynconfig.yaml
  ydb/tools/ydbd_slice/ya.make
Labels: new-feature

#1425 add settings and downsample algorithms
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/graph/protos/graph.proto
  ydb/core/graph/shard/backends.cpp
  ydb/core/graph/shard/backends.h
  ydb/core/graph/shard/protos/counters_shard.proto
  ydb/core/graph/shard/shard_impl.cpp
  ydb/core/graph/shard/shard_impl.h
  ydb/core/graph/shard/tx_aggregate_data.cpp
  ydb/core/graph/shard/tx_clear_data.cpp
  ydb/core/graph/shard/tx_get_metrics.cpp
  ydb/core/graph/shard/tx_monitoring.cpp
  ydb/core/graph/shard/tx_startup.cpp
  ydb/core/graph/shard/tx_store_metrics.cpp
  ydb/core/graph/shard/ut/shard_ut.cpp
  ydb/core/graph/shard/ya.make
  ydb/core/graph/ut/graph_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/console_config.proto
  ydb/core/sys_view/service/ext_counters.cpp
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/basics/appdata.cpp
  ydb/core/testlib/basics/appdata.h
  ydb/core/testlib/test_client.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.h
Labels: new-feature

#1545 Unmute read-only VDisk unittest
  .github/config/muted_ya.txt
Labels: not-for-changelog

#1489 BTreeIndex Charge Bytes Limit
  ydb/core/tablet_flat/flat_part_charge_btree_index.h
  ydb/core/tablet_flat/ut/ut_btree_index_iter_charge.cpp
Labels: not-for-changelog

#1527 [YQ-1997] Extra tests
  ydb/core/tx/schemeshard/schemeshard__operation_alter_external_table.cpp
  ydb/core/tx/schemeshard/ut_external_data_source/ut_external_data_source.cpp
  ydb/core/tx/schemeshard/ut_external_table/ut_external_table.cpp
Labels: not-for-changelog

#1548 Fix YT yql plugin build
  ydb/library/yql/yt/native/ya.make
Labels: bugfix

#1547 YQL-17725 docs for unicode literals
  .gitignore
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/lexer.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/pragma/global.md
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/tests/sql/dq_file/part14/canondata/test.test_expr-unicode_literals-default.txt-Analyze_/extracted
  ydb/library/yql/tests/sql/dq_file/part14/canondata/test.test_expr-unicode_literals-default.txt-Results_/extracted
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/test.test_expr-unicode_literals-default.txt-Results_/extracted
Labels: documentation

#1288 add restricting tablet availability to hive ui KIKIMR-20617
  ydb/core/mind/hive/hive.cpp
  ydb/core/mind/hive/hive.h
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/hive_impl_ut.cpp
  ydb/core/mind/hive/hive_schema.h
  ydb/core/mind/hive/hive_statics.cpp
  ydb/core/mind/hive/leader_tablet_info.cpp
  ydb/core/mind/hive/leader_tablet_info.h
  ydb/core/mind/hive/monitoring.cpp
  ydb/core/mind/hive/node_info.cpp
  ydb/core/mind/hive/node_info.h
  ydb/core/mind/hive/object_distribution_ut.cpp
  ydb/core/mind/hive/tx__create_tablet.cpp
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__register_node.cpp
  ydb/core/mind/hive/tx__seize_tablets_reply.cpp
  ydb/core/protos/counters_hive.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_hive_/flat_hive.schema
Labels: new-feature

#1559 Fix flaky build
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_compress.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_top.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_blocks.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_extend.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_squeeze_to_list.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_switch.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_todict.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
  ydb/library/yql/minikql/comp_nodes/ya.make.inc
  ydb/library/yql/minikql/computation/header.ya.make.inc
  ydb/library/yql/minikql/computation/mkql_block_impl_codegen.h.txt
  ydb/library/yql/minikql/computation/mkql_computation_node_graph.cpp
  ydb/library/yql/minikql/computation/mkql_llvm_base.cpp
  ydb/library/yql/minikql/computation/mkql_llvm_base.h.txt
  ydb/library/yql/minikql/computation/ya.make.inc
Labels: new-feature

#1562 Fix compilation of tpc-ds queries in yql syntax
  ydb/library/benchmarks/queries/tpcds/yql/q14.sql
  ydb/library/benchmarks/queries/tpcds/yql/q8.sql
Labels: not-for-changelog

#1441 support trailing generic query responses
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/common/kqp_event_impl.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.h
  ydb/core/kqp/gateway/kqp_gateway.h
  ydb/core/kqp/query_data/kqp_query_data.cpp
  ydb/core/kqp/query_data/kqp_query_data.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/protos/kqp.proto
Labels: improvement

#1570 Fix for unequal nulls bitmap size YQL-17564
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
Labels: bugfix

#1484 Implemented first version of dynamic jaeger tracing configuration
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/cms/console/jaeger_tracing_configurator.cpp
  ydb/core/cms/console/jaeger_tracing_configurator.h
  ydb/core/cms/console/ya.make
  ydb/core/driver_lib/run/factories.h
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/driver_lib/run/ya.make
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/grpc_services/grpc_request_proxy.h
  ydb/core/jaeger_tracing/control.h
  ydb/core/jaeger_tracing/control_wrapper.h
  ydb/core/jaeger_tracing/request_discriminator.h
  ydb/core/jaeger_tracing/sampler.h
  ydb/core/jaeger_tracing/sampling_throttling_configurator.cpp
  ydb/core/jaeger_tracing/sampling_throttling_configurator.h
  ydb/core/jaeger_tracing/sampling_throttling_control.h
  ydb/core/jaeger_tracing/throttler.h
  ydb/core/jaeger_tracing/ya.make
  ydb/core/protos/config.proto
  ydb/core/testlib/test_client.cpp
  ydb/core/ya.make
  ydb/library/actors/wilson/wilson_uploader.cpp
  ydb/library/actors/wilson/wilson_uploader.h
  ydb/library/services/services.proto
  ydb/tools/cfg/static.py
  ydb/tools/cfg/validation.py
Labels: new-feature

#1567 YQL-17704 switch GWM ut to CA
  ydb/library/yql/providers/dq/global_worker_manager/global_worker_manager_ut.cpp
Labels: new-feature

#1551 KQP locks in EvWrite
  ydb/core/protos/data_events.proto
  ydb/core/tx/data_events/events.h
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/datashard_write_operation.h
  ydb/core/tx/datashard/key_validator.cpp
  ydb/core/tx/datashard/key_validator.h
  ydb/core/tx/datashard/write_unit.cpp
Labels: experimental-feature

#1564 [YQL-16903] Change default value for dq.UseBlockReader and yt.UseRPCReaderInDQ if BlockEngine is enabled
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_mkql_compiler.cpp
Labels: experimental-feature

#1574 Update github.com/ydb-platform/fq-connector-go image to v0.1.2
  ydb/library/yql/providers/generic/connector/tests/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/fq-connector-go/config.conf
Labels: not-for-changelog

#1561 YQL-17713 warning for unsupported callable
  ydb/library/yql/core/issue/protos/issue_id.proto
  ydb/library/yql/core/issue/yql_issue.txt
  ydb/library/yql/core/services/yql_lineage.cpp
  ydb/library/yql/core/services/yql_lineage.h
  ydb/library/yql/core/services/yql_transform_pipeline.cpp
Labels: new-feature

#1556 fix coverity issues: evaluation order violations
  ydb/library/yql/ast/yql_constraint.cpp
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
Labels: improvement

#1578 Fix some unnecessary copies reported by coverity
  ydb/core/tablet_flat/flat_boot_blobs.h
  ydb/core/tablet_flat/flat_dbase_naked.h
  ydb/core/tablet_flat/flat_part_store.h
  ydb/core/tablet_flat/flat_sausage_packet.h
  ydb/core/tablet_flat/flat_sausage_slicer.h
  ydb/core/tablet_flat/flat_writer_bundle.h
  ydb/core/tablet_flat/logic_redo_queue.h
  ydb/core/tablet_flat/ut/ut_proto.cpp
Labels: not-for-changelog

#1575 Make coordination session ping period dependent on session timeout KIKIMR-20993
  ydb/services/kesus/grpc_service.cpp
Labels: improvement

#1500 Add missing <exception> include
  ydb/library/yql/udfs/common/clickhouse/client/src/Common/Exception.h
Labels: not-for-changelog

#1572 Moved sampler and throttler tests to jaeger_tracing folder
  ydb/core/control/ut/ya.make
  ydb/core/jaeger_tracing/control_wrapper.h
  ydb/core/jaeger_tracing/sampler_ut.cpp
  ydb/core/jaeger_tracing/throttler_ut.cpp
  ydb/core/jaeger_tracing/ut/ya.make
  ydb/core/jaeger_tracing/ya.make
Labels: not-for-changelog

#1580 Coverity fix in TPutRecordsActorBase
  ydb/services/datastreams/put_records_actor.h
Labels: not-for-changelog, new-feature

#1579 Mute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog, new-feature

#1588 Add stable release 23.3.17 to documentation
  ydb/docs/en/core/downloads/_includes/server/docker.md
  ydb/docs/en/core/downloads/_includes/server/linux.md
  ydb/docs/en/core/downloads/_includes/server/source_code.md
  ydb/docs/ru/core/downloads/_includes/server/docker.md
  ydb/docs/ru/core/downloads/_includes/server/linux.md
  ydb/docs/ru/core/downloads/_includes/server/source_code.md
Labels: documentation

#1598 fix aarch64 compile flags
  ydb/library/yql/minikql/comp_nodes/ut/ya.make.inc
  ydb/library/yql/minikql/comp_nodes/ya.make.inc
  ydb/library/yql/minikql/perf/mprefetch/ya.make
Labels: new-feature

#1594 YQL-17339 import all columns from real PG
  ydb/library/yql/parser/pg_catalog/.gitignore
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/columns.generated.h
  ydb/library/yql/parser/pg_catalog/columns.sql
  ydb/library/yql/parser/pg_catalog/dump_system_columns.sh
  ydb/library/yql/parser/pg_catalog/generate_system_columns.py
  ydb/library/yql/parser/pg_catalog/pg_class.generated.h
  ydb/library/yql/parser/pg_catalog/pg_class.sql
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg_catalog/columns.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_am_pg_syntax.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_class.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_namespace_pg_syntax.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_tables.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/tables.sql
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
Labels: new-feature

#1590 Consider inflight in full result writer (fix large memory consumption) YQL-17720
  ydb/library/yql/providers/dq/actors/actors_ut.cpp
  ydb/library/yql/providers/dq/actors/result_actor_base.h
  ydb/library/yql/providers/dq/actors/result_receiver.cpp
Labels: bugfix

#1596 Fix crash during s3 backup.
  contrib/libs/curl/CMakeLists.darwin-x86_64.txt
  contrib/libs/curl/CMakeLists.linux-aarch64.txt
  contrib/libs/curl/CMakeLists.linux-x86_64.txt
  contrib/libs/curl/CMakeLists.windows-x86_64.txt
  contrib/libs/curl/ya.make
Labels: bugfix

#1591 Made tvm url optional
  ydb/core/protos/config.proto
  ydb/tools/cfg/static.py
  ydb/tools/cfg/validation.py
Labels: not-for-changelog

#1584 Use std::atomic in shared data header
  ydb/library/actors/util/shared_data.cpp
  ydb/library/actors/util/shared_data.h
  ydb/library/actors/util/shared_data_backtracing_owner.h
  ydb/library/actors/util/shared_data_ut.cpp
Labels: improvement

#1577 Remove obsolete controllers
  ydb/core/cms/json_proxy_proto.h
  ydb/core/control/common_controls/tracing_control.cpp
  ydb/core/control/common_controls/tracing_control.h
  ydb/core/control/common_controls/ya.make
  ydb/core/control/immediate_control_board_sampler.h
  ydb/core/control/immediate_control_board_throttler.h
  ydb/core/control/ya.make
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/keyvalue/ya.make
  ydb/core/protos/config.proto
Labels: not-for-changelog

#1613 Rename method to BuildCompleted
  ydb/core/tx/columnshard/transactions/operators/ev_write.h
  ydb/core/tx/data_events/events.h
  ydb/core/tx/datashard/write_unit.cpp
Labels: not-for-changelog

#1597 [YQ-2800] Fixed path pruning for large amount of files
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
Labels: bugfix

#1618 Fix GetColumnSerializationStats and ResourceSubscriber task name
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/splitter/batch_slice.h
Labels: bugfix

#1608 YQL-17476 check for cycle during evaluation of file args
  ydb/library/yql/providers/config/yql_config_provider.cpp
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/test.test_action-file_cycle--Results_/extracted
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/action/file_cycle.cfg
  ydb/library/yql/tests/sql/suites/action/file_cycle.sql
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/test.test_action-file_cycle--Results_/extracted
Labels: new-feature

#1617 [YQL-17625] Fix ORDER BY by column missing in projections
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/order_by/order_by_missing_project_column.sql
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: bugfix

#1610 YQL-17542 remove transition guards
  ydb/library/yql/dq/actors/compute/dq_compute_actor.h
  ydb/library/yql/dq/actors/task_runner/task_runner_actor.h
  ydb/library/yql/tools/dq/worker_job/dq_worker.cpp
Labels: not-for-changelog

#1616 [yt provider] Remove aux columns in PushDownYtMapOverSortedMerge optimizer (YQL-17715)
  ydb/library/yql/providers/yt/provider/yql_yt_physical_optimize.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/optimizers/yql-17715_concat_sort_desc.cfg
  ydb/library/yql/tests/sql/suites/optimizers/yql-17715_concat_sort_desc.sql
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
Labels: bugfix

#1628 correct libraries for use in future
  ydb/core/tx/tiering/rule/object.h
  ydb/core/tx/tiering/rule/ya.make
  ydb/library/conclusion/result.h
  ydb/services/bg_tasks/abstract/interface.h
Labels: improvement

#1638 [YQL-17776] Canonize test
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
Labels: bugfix

#1636 Removed required fields from tracing configs
  ydb/core/cms/console/jaeger_tracing_configurator.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/jaeger_tracing/sampling_throttling_configurator.cpp
  ydb/core/protos/config.proto
  ydb/tools/cfg/validation.py
Labels: not-for-changelog

#1632 graceful tiering stop
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/manager.h
Labels: bugfix

#1629 fix filter apply and serializer usage
  ydb/core/formats/arrow/serializer/abstract.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/fetched_data.h
  ydb/core/tx/columnshard/engines/scheme/column_features.cpp
  ydb/services/bg_tasks/abstract/interface.h
Labels: bugfix

#1630 snapshot serialization
  ydb/core/tx/columnshard/engines/defs.h
  ydb/core/tx/columnshard/engines/filter.h
  ydb/core/tx/columnshard/engines/insert_table/data.h
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lbuckets/optimizer.h
  ydb/core/tx/columnshard/tables_manager.cpp
Labels: improvement

#1635 YQL-17542 get rid of std::any in handling sources state
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
Labels: not-for-changelog

#1626 YQL-17755 ut for TComputeActorAsyncInputHelperTest::PollAsyncInput
  ydb/library/yql/dq/actors/compute/ut/dq_compute_actor_async_input_helper_ut.cpp
  ydb/library/yql/dq/actors/compute/ut/ya.make
Labels: not-for-changelog

#1457 YQ-2734 added retries for internal queries
  ydb/core/kqp/common/events/script_executions.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_actor.cpp
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_service.cpp
  ydb/core/kqp/proxy_service/kqp_script_executions.cpp
  ydb/core/kqp/proxy_service/kqp_script_executions.h
  ydb/library/query_actor/query_actor.h
Labels: area/queryprocessor, bugfix, improvement

#1640 Fix scrubbing and flapping unittest
  ydb/core/blobstorage/backpressure/queue.h
  ydb/core/blobstorage/backpressure/queue_backpressure_client.cpp
  ydb/core/blobstorage/backpressure/queue_backpressure_server.h
  ydb/core/blobstorage/dsproxy/dsproxy_get_impl.cpp
  ydb/core/blobstorage/pdisk/mock/pdisk_mock.cpp
  ydb/core/blobstorage/pdisk/mock/pdisk_mock.h
  ydb/core/blobstorage/ut_blobstorage/scrub_fast.cpp
  ydb/core/blobstorage/vdisk/scrub/blob_recovery_impl.h
  ydb/core/blobstorage/vdisk/scrub/blob_recovery_process.cpp
  ydb/core/blobstorage/vdisk/scrub/blob_recovery_request.cpp
  ydb/core/blobstorage/vdisk/scrub/restore_corrupted_blob_actor.cpp
Labels: not-for-changelog

#1644 add initialization for pool stats CLOUD-176662
  ydb/core/mind/hive/storage_pool_info.cpp
Labels: not-for-changelog

#1649 Memory control and search fix
  ydb/core/protos/config.proto
  ydb/core/tablet/resource_broker.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/common/protos/snapshot.proto
  ydb/core/tx/columnshard/common/protos/ya.make
  ydb/core/tx/columnshard/common/snapshot.cpp
  ydb/core/tx/columnshard/common/snapshot.h
  ydb/core/tx/columnshard/common/ya.make
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.h
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.cpp
  ydb/core/tx/columnshard/engines/ut_logs_engine.cpp
Labels: improvement

#1523 Add force io pool threads
  ydb/core/driver_lib/run/auto_config_initializer.cpp
  ydb/core/protos/config.proto
  ydb/tools/cfg/base.py
  ydb/tools/cfg/dynamic.py
  ydb/tools/cfg/validation.py
Labels: area/actorsystem, new-feature

#1549 Add patching to keyvalue
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/dsproxy/mock/dsproxy_mock.cpp
  ydb/core/blobstorage/dsproxy/mock/model.h
  ydb/core/keyvalue/keyvalue_intermediate.h
  ydb/core/keyvalue/keyvalue_state.cpp
  ydb/core/keyvalue/keyvalue_state.h
  ydb/core/keyvalue/keyvalue_storage_request.cpp
  ydb/core/keyvalue/keyvalue_ut.cpp
  ydb/core/protos/msgbus.proto
  ydb/core/protos/msgbus_kv.proto
Labels: new-feature

#1652 Removed aborts in service initialization
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/tx/datashard/export_common.h
  ydb/library/actors/wilson/wilson_uploader.cpp
Labels: not-for-changelog

#1653 fix tests
  ydb/core/tx/columnshard/engines/ut/helper.cpp
  ydb/core/tx/columnshard/engines/ut/helper.h
  ydb/core/tx/columnshard/engines/ut/ut_insert_table.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/engines/ut/ut_program.cpp
  ydb/core/tx/columnshard/engines/ut/ya.make
Labels: bugfix

#1592 YQ-2549 Move yds integration tests to github
  ydb/tests/fq/yds/test_recovery.py
  ydb/tests/fq/yds/test_recovery_match_recognize.py
  ydb/tests/fq/yds/test_recovery_mz.py
  ydb/tests/fq/yds/ya.make
Labels: not-for-changelog

#1563 Optimized DPccp
  ydb/core/kqp/opt/logical/kqp_opt_cbo.cpp
  ydb/core/kqp/opt/logical/kqp_opt_cbo.h
  ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
  ydb/library/yql/core/cbo/cbo_optimizer_new.h
  ydb/library/yql/core/yql_cost_function.cpp
  ydb/library/yql/core/yql_statistics.cpp
  ydb/library/yql/core/yql_statistics.h
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
Labels: new-feature, performance

#1668 use only thread for async s3 interaction
  ydb/core/wrappers/s3_storage_config.cpp
Labels: improvement

#1606 Generate single JSON with all types of plans in the server
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/public/lib/ydb_cli/common/format.cpp
  ydb/public/lib/ydb_cli/common/format.h
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_explain.script-script_/explain.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_join_group_by_lookup.script-script_/join_group_by_lookup.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_simple_ct.script-script_/simple_ct.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_simple_script_params.script-script_/simple_script_params.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_table_types.script-script_/table_types.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage.script-script_/write_multi_usage.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage_key.script-script_/write_multi_usage_key.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_write_group_by.script-script_/write_write_group_by.script.plan
  ydb/tests/functional/canonical/test_sql.py
  ydb/tests/functional/suite_tests/test_base.py
Labels: new-feature, experimental-feature

#1665 add strip port for ssl outgoing connection
  ydb/library/actors/http/http_proxy_sock_impl.h
Labels: bugfix

#1620 Add CMS request priorities KIKIMR-9024
  ydb/core/cms/api_adapters.cpp
  ydb/core/cms/cluster_info.cpp
  ydb/core/cms/cluster_info.h
  ydb/core/cms/cluster_info_ut.cpp
  ydb/core/cms/cms.cpp
  ydb/core/cms/cms_impl.h
  ydb/core/cms/cms_tx_load_state.cpp
  ydb/core/cms/cms_tx_store_permissions.cpp
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/cms/cms_ut_common.h
  ydb/core/cms/node_checkers.cpp
  ydb/core/cms/scheme.h
  ydb/core/cms/walle.h
  ydb/core/cms/walle_create_task_adapter.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_cms.cpp
  ydb/core/protos/cms.proto
  ydb/core/protos/feature_flags.proto
  ydb/core/testlib/basics/feature_flags.h
  ydb/public/api/protos/draft/ydb_maintenance.proto
Labels: new-feature

#1667 YQL-17725 tune doc
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/lexer.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/pragma/global.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/lexer.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/pragma/global.md
Labels: new-feature

#1660 YQL-17725 drop b and t suffixes
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/test.test_expr-unicode_literals-default.txt-Analyze_/extracted
  ydb/library/yql/tests/sql/dq_file/part14/canondata/test.test_expr-unicode_literals-default.txt-Results_/extracted
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/unicode_literals.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/test.test_expr-unicode_literals-default.txt-Results_/extracted
Labels: new-feature

#1587 Pg patches
  ydb/docs/en/core/postgresql/docker-connect.md
  ydb/docs/ru/core/postgresql/docker-connect.md
  ydb/library/yql/sql/pg/pg_sql.cpp
  ydb/public/tools/lib/cmds/__init__.py
  ydb/tests/library/harness/kikimr_config.py
Labels: experimental-feature

#1631 Fix mistype in YQL plugin
  ydb/library/yql/yt/dynamic/impl.cpp
Labels: bugfix

#1675 KIKIMR-20539: resolve static information_schema tables
  ydb/core/kqp/host/kqp_translate.cpp
  ydb/core/kqp/ut/pg/pg_catalog_ut.cpp
  ydb/library/yql/sql/pg/pg_sql.cpp
Labels: not-for-changelog

#1666 YQL-17542 move TaskRunner to TDqSyncComputeActorBase
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h
Labels: not-for-changelog

#1540 YQ-2803 Exception checking in checkpoint storages
  ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
  ydb/core/fq/libs/checkpoint_storage/ydb_state_storage.cpp
  ydb/core/fq/libs/ydb/ut/ya.make
  ydb/core/fq/libs/ydb/ut/ydb_ut.cpp
  ydb/core/fq/libs/ydb/ya.make
  ydb/core/fq/libs/ydb/ydb.cpp
Labels: not-for-changelog

#1661 KqpRun add results into clear execution
  ydb/tests/tools/kqprun/.gitignore
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/actors.cpp
  ydb/tests/tools/kqprun/src/actors.h
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/kqp_runner.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.h
Labels: area/dev, improvement

#1692 Some BlobDepot hardening checks
  ydb/core/blob_depot/given_id_range.cpp
  ydb/core/blob_depot/op_commit_blob_seq.cpp
Labels: not-for-changelog

#1691 fix tierings db usage
  ydb/core/tx/columnshard/blobs_action/tier/gc.cpp
Labels: bugfix

#1693 Fix TEvPatch interface and remove unnecessary patching-related output in KV tablet
  ydb/core/base/blobstorage.h
  ydb/core/keyvalue/keyvalue_storage_request.cpp
Labels: not-for-changelog

#1669 Fix autoconfig's compute cpu table
  ydb/core/driver_lib/run/auto_config_initializer.cpp
Labels: area/actorsystem, bugfix

#1700 Make UTs reachable KIKIMR-20902
  ydb/core/tx/replication/service/ya.make
Labels: not-for-changelog, new-feature

#1671 Implement converter yt join tree -> optimizer join tree YQL-17437
  ydb/library/yql/providers/yt/provider/ut/yql_yt_cbo_ut.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_join_impl.h
  ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
Labels: not-for-changelog

#1544 [YQL-17174] added spilling library for compute actors
  ydb/library/yql/dq/actors/spilling/compute_storage.cpp
  ydb/library/yql/dq/actors/spilling/compute_storage.h
  ydb/library/yql/dq/actors/spilling/compute_storage_actor.cpp
  ydb/library/yql/dq/actors/spilling/compute_storage_actor.h
  ydb/library/yql/dq/actors/spilling/spiller_factory.h
  ydb/library/yql/dq/actors/spilling/ya.make
  ydb/library/yql/minikql/computation/mkql_spiller.h
  ydb/library/yql/minikql/computation/mkql_spiller_factory.h
  ydb/library/yql/minikql/computation/ya.make.inc
Labels: new-feature

#1701 Fix autoconfig's compute cpu table
  ydb/core/driver_lib/run/auto_config_initializer.cpp
Labels: area/actorsystem

#1650 parallel for
  ydb/library/yql/core/services/yql_eval_expr.cpp
  ydb/library/yql/core/yql_type_annotation.h
  ydb/library/yql/providers/config/yql_config_provider.cpp
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/context.h
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/format/sql_format_ut.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/test.test_action-parallel_for-default.txt-Analyze_/extracted
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/action/parallel_for.sql
  ydb/library/yql/tests/sql/suites/action/parallel_for_select.sqlx
  ydb/library/yql/tests/sql/suites/action/parallel_for_values.sqlx
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tools/yqlrun/http/www/js/mode-sql.js
Labels: new-feature

#1699 Support KV patching in TestShard
  ydb/core/protos/msgbus.proto
  ydb/core/test_tablet/load_actor_impl.cpp
  ydb/core/test_tablet/load_actor_impl.h
  ydb/core/test_tablet/load_actor_mon.cpp
  ydb/core/test_tablet/load_actor_read_validate.cpp
  ydb/core/test_tablet/load_actor_write.cpp
Labels: new-feature

#1568 Convert mismatched types of arg/sequence when applying optimization of ShuffleByKeys/PartitionsByKeys to empty sequence
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
Labels: not-for-changelog

#1710 Forbid new required fields in config
  ydb/core/config/ut/main.cpp
  ydb/core/config/ut/ya.make
  ydb/core/config/utils/config_traverse.cpp
  ydb/core/config/utils/config_traverse.h
  ydb/core/config/utils/ya.make
  ydb/core/config/ya.make
  ydb/core/ya.make
Labels: not-for-changelog

#1715 Make UTs reachable (attempt 2) KIKIMR-20902
  ydb/core/tx/replication/service/ut/ya.make
  ydb/core/tx/replication/service/ya.make
  ydb/core/tx/replication/ut/ya.make
  ydb/core/tx/replication/ya.make
Labels: not-for-changelog, new-feature

#1603 Enable DDL in ExecuteScript. Allow not to specify TxControl in QueryService queries
  ydb/core/grpc_services/query/rpc_execute_script.cpp
  ydb/core/kqp/session_actor/kqp_query_state.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_scripts_ut.cpp
Labels: new-feature

#1730 Implement cbo join tree -> yt join tree converter YQL-17437
  ydb/library/yql/providers/yt/provider/ut/yql_yt_cbo_ut.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_join_impl.h
  ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
Labels: not-for-changelog

#1711 unmute test
  .github/config/muted_ya.txt
Labels: new-feature

#1709 Switch pg_parser BC tests on again
  ydb/library/yql/parser/pg_wrapper/ya.make
Labels: new-feature

#1745 Fix race condition between callback and destructor in TS3ExternalStorage
  ydb/core/wrappers/s3_storage.h
Labels: not-for-changelog

#1740 TPartitionId constructors
  ydb/core/persqueue/partition_id.h
Labels: bugfix

#1748 [YQL-16903] Change default value for EmitAggApply and dq.EnableDqReplicate if BlockEngine is enabled
  ydb/library/yql/core/common_opt/yql_co_pgselect.cpp
  ydb/library/yql/core/yql_type_annotation.h
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
  ydb/library/yql/providers/dq/opt/logical_optimize.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_datasink.cpp
  ydb/library/yql/sql/v1/aggregation.cpp
  ydb/library/yql/sql/v1/context.cpp
  ydb/library/yql/sql/v1/context.h
Labels: improvement

#1680 Make stopping result/notification sending dependent on operation type…
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard_active_transaction.cpp
  ydb/core/tx/datashard/datashard_active_transaction.h
  ydb/core/tx/datashard/datashard_ut_order.cpp
  ydb/core/tx/datashard/operation.cpp
  ydb/core/tx/datashard/operation.h
Labels: bugfix

#1674 BTreeIndex Bugfix partially-loaded tree
  ydb/core/tablet_flat/flat_part_charge_btree_index.h
  ydb/core/tablet_flat/ut/ut_btree_index_iter_charge.cpp
Labels: not-for-changelog

#1757 Fix pq writer and few renames
  ydb/core/persqueue/writer/writer.cpp
Labels: not-for-changelog, new-feature

#1713 LOGBROKER-8783 bugfix
  .github/config/muted_ya.txt
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_read_session.cpp
Labels: new-feature, bugfix

#1758 Moved optimizers from yql/providers/dq to yql/dq
  ydb/library/yql/dq/expr_nodes/dq_expr_nodes.json
  ydb/library/yql/dq/opt/dq_opt_log.cpp
  ydb/library/yql/dq/opt/dq_opt_log.h
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.h
  ydb/library/yql/providers/clickhouse/provider/yql_clickhouse_logical_opt.cpp
  ydb/library/yql/providers/clickhouse/provider/yql_clickhouse_physical_opt.cpp
  ydb/library/yql/providers/dq/expr_nodes/dqs_expr_nodes.json
  ydb/library/yql/providers/dq/opt/logical_optimize.cpp
  ydb/library/yql/providers/dq/opt/physical_optimize.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_logical_opt.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_physical_opt.cpp
  ydb/library/yql/providers/ydb/provider/yql_ydb_logical_opt.cpp
Labels: area/yql, improvement

#1762 Return back dq_arrow_helpers
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
Labels: bugfix

#1417 LOGBROKER-8792 remove redundant checks
  ydb/library/persqueue/topic_parser/topic_parser.cpp
  ydb/library/persqueue/topic_parser/ut/topic_names_converter_ut.cpp
  ydb/services/persqueue_v1/actors/schema_actors.cpp
  ydb/services/persqueue_v1/persqueue_compat_ut.cpp
Labels: new-feature, improvement

#1760 Fix win build
  ydb/library/yql/providers/s3/provider/ya.make
  ydb/library/yql/providers/s3/provider/yql_s3_dq_integration.cpp
Labels: bugfix

#1751 add testcases for PgConvertNumericDecimal128Big
  ydb/library/yql/parser/pg_wrapper/arrow.cpp
  ydb/library/yql/parser/pg_wrapper/ut/arrow_ut.cpp
Labels: improvement

#1771 [yt provider] Raise error on invalid poller_interval value
  ydb/library/yql/providers/yt/lib/init_yt_api/init.cpp
Labels: not-for-changelog

#1754 support cast in default values
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/pg/kqp_pg_ut.cpp
Labels: not-for-changelog

#1663 Allow arithmetic operations and operator* for const iterators
  ydb/library/yql/minikql/comp_nodes/mkql_sort.cpp
Labels: not-for-changelog

#1769 Added 'FQ_CONNECTOR_ENDPOINT' env variable to `local_ydb`
  ydb/public/tools/lib/cmds/__init__.py
  ydb/public/tools/lib/cmds/ut/test.py
  ydb/public/tools/lib/cmds/ut/ya.make
  ydb/public/tools/lib/cmds/ya.make
  ydb/public/tools/local_ydb/__main__.py
  ydb/public/tools/local_ydb/ya.make
  ydb/tests/library/harness/kikimr_config.py
  ydb/tests/library/ut/kikimr_config.py
  ydb/tests/library/ut/ya.make
  ydb/tests/library/ya.make
Labels: new-feature

#1753 Change numeric.c according to postgres 14
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/adt/numeric.c
  ydb/library/yql/parser/pg_wrapper/ut/arrow_ut.cpp
Labels: improvement

#1775 [YQL-17637] Revive merging PERCENTILE/MEDIAN aggregation traits for same column
  ydb/library/yql/mount/lib/yql/aggregate.yql
  ydb/library/yql/sql/v1/aggregation.cpp
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/source.cpp
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
Labels: area/yql, performance

#1779 hive ui fixes after tablet availability feature
  ydb/core/mind/hive/hive_statics.cpp
  ydb/core/mind/hive/monitoring.cpp
Labels: not-for-changelog

#1781 Break deps from core/grpc_services to core/fq/libs/actors
  ydb/core/fq/libs/actors/proxy_private.h
  ydb/core/fq/libs/control_plane_proxy/control_plane_proxy.cpp
  ydb/core/fq/libs/control_plane_proxy/events/events.h
  ydb/core/fq/libs/control_plane_proxy/utils/utils.h
  ydb/core/fq/libs/control_plane_proxy/utils/ya.make
  ydb/core/fq/libs/control_plane_proxy/ya.make
  ydb/core/fq/libs/events/events.h
  ydb/core/grpc_services/rpc_fq.cpp
  ydb/core/grpc_services/rpc_fq_internal.cpp
  ydb/core/grpc_services/service_fq.h
  ydb/core/grpc_services/ya.make
  ydb/core/kqp/executer_actor/ya.make
  ydb/core/kqp/node_service/ya.make
Labels: bugfix

#1637 store history of changes made to hive via http
  ydb/core/mind/hive/hive_schema.h
  ydb/core/mind/hive/monitoring.cpp
  ydb/core/mind/hive/monitoring.h
  ydb/core/mind/hive/ya.make
  ydb/core/tablet/tablet_monitoring_proxy.cpp
  ydb/library/actors/protos/actors.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_hive_/flat_hive.schema
Labels: new-feature

#1765 Make it possible to return skiff from dq
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.h
Labels: new-feature

#1741 improve base stats propagation logic
  ydb/core/protos/statistics.proto
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/aggregator_impl.h
  ydb/core/statistics/aggregator/tx_init.cpp
  ydb/core/statistics/events.h
  ydb/core/statistics/stat_service.cpp
Labels: not-for-changelog, improvement

#1773 Cannonized two plans
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join3.test_/query_4.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join3.test_/query_5.plan
Labels: new-feature, bugfix

#1676 KIKIMR-20580: enable stream lookup
  ydb/core/kqp/ut/opt/kqp_sqlin_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: new-feature

#1799 fix segfault
  ydb/core/graph/shard/backends.cpp
  ydb/core/graph/ut/graph_ut.cpp
Labels: bugfix

#1816 docs: fix presentation url
  ydb/docs/ru/core/public-talks.md
Labels: documentation

#1833 Use six's 'urllib.parse' in 'PY23_LIBRARY' modules
  ydb/public/tools/lib/cmds/__init__.py
Labels: bugfix

#1809 Do not move protobuf from TValue during BulkUpsert execution.
  ydb/public/sdk/cpp/client/ydb_table/impl/table_client.cpp
  ydb/services/ydb/ydb_bulk_upsert_ut.cpp
Labels: bugfix

#1351 Manage releases docs
  ydb/docs/en/core/administration/upgrade.md
  ydb/docs/en/core/development/_includes/corp_cli_tags.md
  ydb/docs/en/core/development/_includes/corp_release_stable.md
  ydb/docs/en/core/development/_includes/corp_release_testing.md
  ydb/docs/en/core/development/_includes/index.md
  ydb/docs/en/core/development/manage-releases.md
  ydb/docs/en/core/development/toc_i.yaml
  ydb/docs/ru/core/administration/upgrade.md
  ydb/docs/ru/core/development/_includes/corp_cli_tags.md
  ydb/docs/ru/core/development/_includes/corp_release_stable.md
  ydb/docs/ru/core/development/_includes/corp_release_testing.md
  ydb/docs/ru/core/development/_includes/index.md
  ydb/docs/ru/core/development/manage-releases.md
  ydb/docs/ru/core/development/toc_i.yaml
Labels: documentation, new-feature

#1847 runtime dispatching (fixed)
  ydb/library/yql/utils/simd/exec/runtime_dispatching/AVX2_algo/avx2_algo.cpp
  ydb/library/yql/utils/simd/exec/runtime_dispatching/AVX2_algo/ya.make
  ydb/library/yql/utils/simd/exec/runtime_dispatching/Fallback_algo/fallback_algo.cpp
  ydb/library/yql/utils/simd/exec/runtime_dispatching/Fallback_algo/ya.make
  ydb/library/yql/utils/simd/exec/runtime_dispatching/SSE42_algo/sse42_algo.cpp
  ydb/library/yql/utils/simd/exec/runtime_dispatching/SSE42_algo/ya.make
  ydb/library/yql/utils/simd/exec/runtime_dispatching/algo.h
  ydb/library/yql/utils/simd/exec/runtime_dispatching/main/main.cpp
  ydb/library/yql/utils/simd/exec/runtime_dispatching/main/ya.make
  ydb/library/yql/utils/simd/exec/runtime_dispatching/ya.make
  ydb/library/yql/utils/simd/simd_avx2.h
  ydb/library/yql/utils/simd/simd_fallback.h
  ydb/library/yql/utils/simd/simd_sse42.h
Labels: new-feature

#1817 Support of database sys cache
  ydb/library/yql/parser/pg_wrapper/parser.cpp
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/current_database.sql
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
Labels: new-feature, area/pg

#1855 Expose a factory for new native cbo YQL-17437
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
  ydb/library/yql/dq/opt/dq_opt_log.h
Labels: not-for-changelog

#1856 Fixed missing PEERDIR in ydb/public/tools/lib/cmds
  ydb/public/tools/lib/cmds/ya.make
Labels: not-for-changelog

#1865 Test supported types KIKIMR-20902
  ydb/core/tx/replication/service/table_writer_ut.cpp
  ydb/core/tx/replication/service/ut_table_writer/ya.make
Labels: not-for-changelog, new-feature

#1867 Do not call TypeName for trace in tablet transactions if no trace exists
  ydb/core/tablet_flat/tablet_flat_executor.h
Labels: performance

#1863 [Configs Refactor] Split protobufs
  ydb/core/protos/bootstrap.proto
  ydb/core/protos/compile_service_config.proto
  ydb/core/protos/config.proto
  ydb/core/protos/ya.make
Labels: not-for-changelog

#1874 YDBDOCS-596: extra clarifications to upgrade.md
  ydb/docs/en/core/administration/upgrade.md
  ydb/docs/ru/core/administration/upgrade.md
Labels: documentation

#1788 Remove duplicated defines
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/port/win32_port.h
Labels: not-for-changelog

#1879 bring simple queue tool to oss
  ydb/tools/simple_queue/__main__.py
  ydb/tools/simple_queue/ya.make
  ydb/tools/ya.make
Labels: not-for-changelog

#1353 YQ-2417 show ast in case of compilation error
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_host_impl.h
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/public/sdk/cpp/client/ydb_query/impl/exec_query.cpp
  ydb/public/sdk/cpp/client/ydb_query/stats.cpp
  ydb/public/sdk/cpp/client/ydb_query/stats.h
  ydb/tests/fq/s3/test_bindings.py
  ydb/tests/fq/yds/test_select_1.py
Labels: area/sdk, new-feature, improvement

#1876 [Configs Refactor] Deprecate old yaml_config_parser
  ydb/core/driver_lib/cli_utils/cli_cmds_config.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp
  ydb/core/driver_lib/cli_utils/ya.make
  ydb/library/yaml_config/deprecated/ya.make
  ydb/library/yaml_config/deprecated/yaml_config_parser.cpp
  ydb/library/yaml_config/deprecated/yaml_config_parser.h
  ydb/library/yaml_config/ut/ya.make
  ydb/library/yaml_config/ya.make
  ydb/library/yaml_config/yaml_config.cpp
  ydb/library/yaml_config/yaml_config_ut.cpp
Labels: not-for-changelog

#1889 Unmute some flaky tests
  .github/config/muted_ya.txt
Labels: not-for-changelog
