Repository ydb-platform/ydb, pull requests merged in 2024-12, with the labels that each got.

#12159 [YQL-19342][CBO] Use proper error codes
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
Labels: area/yql, bugfix

#12158 [YQL-19309] Switch YT provider to DQ nodes from yql/essentials
  ydb/library/yql/providers/yt/gateway/file/yql_yt_file_mkql_compiler.cpp
  ydb/library/yql/providers/yt/gateway/native/ya.make
  ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_key_range.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_write.cpp
  ydb/library/yql/providers/yt/provider/ya.make
  ydb/library/yql/providers/yt/provider/yql_yt_dq_hybrid.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_helpers.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_mkql_compiler.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_op_hash.cpp
Labels: area/yql, improvement

#12066 YQ-3894 RD supported pushdown for SafeCast, ToBytes, FlatMap
  ydb/library/yql/providers/common/pushdown/collection.cpp
  ydb/library/yql/providers/common/pushdown/physical_opt.cpp
  ydb/library/yql/providers/common/pushdown/physical_opt.h
  ydb/library/yql/providers/common/pushdown/predicate_node.cpp
  ydb/library/yql/providers/common/pushdown/predicate_node.h
  ydb/library/yql/providers/common/pushdown/settings.h
  ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.h
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: improvement

#11892 Enable kafka api by env variable
  ydb/public/tools/lib/cmds/__init__.py
  ydb/tests/library/harness/kikimr_config.py
Labels: improvement

#12163 lock categories to control different lock-purposes
  ydb/core/tx/columnshard/data_locks/locks/abstract.h
  ydb/core/tx/columnshard/data_locks/locks/composite.h
  ydb/core/tx/columnshard/data_locks/locks/list.h
  ydb/core/tx/columnshard/data_locks/locks/snapshot.h
  ydb/core/tx/columnshard/data_locks/manager/manager.cpp
  ydb/core/tx/columnshard/data_locks/manager/manager.h
  ydb/core/tx/columnshard/data_sharing/common/session/common.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.h
  ydb/core/tx/columnshard/engines/changes/cleanup_tables.h
  ydb/core/tx/columnshard/engines/changes/compaction.h
  ydb/core/tx/columnshard/engines/changes/indexation.h
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/changes/with_appended.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/storage/granule/storage.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lbuckets/planner/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/accumulation_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/common_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/index/bucket.cpp
Labels: improvement

#12151 Fix follower reads sometimes crashing during split
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_common_kqp.h
  ydb/core/tx/datashard/datashard_ut_followers.cpp
Labels: bugfix

#12203 Enhanced parallelism of data restoring in `ydb tools restore`
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_compat.cpp
  ydb/public/lib/ydb_cli/dump/restore_compat.h
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/restore_impl.h
  ydb/public/lib/ydb_cli/dump/restore_import_data.cpp
  ydb/public/lib/ydb_cli/dump/restore_import_data.h
  ydb/public/sdk/cpp/client/ydb_import/out.cpp
  ydb/public/sdk/cpp/client/ydb_import/ya.make
Labels: performance

#12207 Remove TString nullptr ctor usages
  ydb/core/blobstorage/dsproxy/ut_fat/dsproxy_ut.cpp
  ydb/core/client/object_storage_listing_ut.cpp
  ydb/core/tablet_flat/ut/ut_db_iface.cpp
  ydb/core/tablet_flat/ut/ut_part.cpp
Labels: not-for-changelog, external

#12157 enable chooser by default
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#11449 oidc impersonation
  ydb/mvp/oidc_proxy/context.cpp
  ydb/mvp/oidc_proxy/context.h
  ydb/mvp/oidc_proxy/mvp.cpp
  ydb/mvp/oidc_proxy/mvp.h
  ydb/mvp/oidc_proxy/oidc_client.cpp
  ydb/mvp/oidc_proxy/oidc_client.h
  ydb/mvp/oidc_proxy/oidc_impersonate_start_page_nebius.cpp
  ydb/mvp/oidc_proxy/oidc_impersonate_start_page_nebius.h
  ydb/mvp/oidc_proxy/oidc_impersonate_stop_page_nebius.cpp
  ydb/mvp/oidc_proxy/oidc_impersonate_stop_page_nebius.h
  ydb/mvp/oidc_proxy/oidc_protected_page.cpp
  ydb/mvp/oidc_proxy/oidc_protected_page.h
  ydb/mvp/oidc_proxy/oidc_protected_page_handler.cpp
  ydb/mvp/oidc_proxy/oidc_protected_page_handler.h
  ydb/mvp/oidc_proxy/oidc_protected_page_nebius.cpp
  ydb/mvp/oidc_proxy/oidc_protected_page_nebius.h
  ydb/mvp/oidc_proxy/oidc_protected_page_yandex.cpp
  ydb/mvp/oidc_proxy/oidc_protected_page_yandex.h
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
  ydb/mvp/oidc_proxy/oidc_session_create.cpp
  ydb/mvp/oidc_proxy/oidc_session_create.h
  ydb/mvp/oidc_proxy/oidc_session_create_handler.cpp
  ydb/mvp/oidc_proxy/oidc_session_create_handler.h
  ydb/mvp/oidc_proxy/oidc_session_create_nebius.cpp
  ydb/mvp/oidc_proxy/oidc_session_create_nebius.h
  ydb/mvp/oidc_proxy/oidc_session_create_yandex.cpp
  ydb/mvp/oidc_proxy/oidc_session_create_yandex.h
  ydb/mvp/oidc_proxy/oidc_settings.cpp
  ydb/mvp/oidc_proxy/oidc_settings.h
  ydb/mvp/oidc_proxy/openid_connect.cpp
  ydb/mvp/oidc_proxy/openid_connect.h
  ydb/mvp/oidc_proxy/ya.make
Labels: new-feature

#12108 docs: publish YDB CLI 2.16.0 with release notes
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/linux.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/windows.md
  ydb/docs/ru/core/changelog-cli.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/linux.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/windows.md
Labels: documentation

#12213 Explicit ydb/tools/cfg/bin/ydb_configure path
  ydb/tests/library/harness/kikimr_cluster.py
  ydb/tests/library/harness/kikimr_runner.py
  ydb/tests/library/harness/param_constants.py
  ydb/tests/library/harness/ydbd_slice.py
  ydb/tests/stability/ydb/test_stability.py
  ydb/tests/tools/nemesis/driver/__main__.py
Labels: not-for-changelog

#12217 Fix use-after-free when access line location in `ydb tools restore`
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
Labels: not-for-changelog

#12136 YQ-3925 RD remove mutex for purecalc compilation
  ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.h
  ydb/core/fq/libs/row_dispatcher/common.cpp
  ydb/core/fq/libs/row_dispatcher/common.h
  ydb/core/fq/libs/row_dispatcher/events/data_plane.h
  ydb/core/fq/libs/row_dispatcher/json_filter.cpp
  ydb/core/fq/libs/row_dispatcher/json_filter.h
  ydb/core/fq/libs/row_dispatcher/purecalc_compilation/compile_service.cpp
  ydb/core/fq/libs/row_dispatcher/purecalc_compilation/compile_service.h
  ydb/core/fq/libs/row_dispatcher/purecalc_compilation/ya.make
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.h
  ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ya.make
Labels: performance

#12212 YQ fix unused argument
  ydb/library/yql/providers/common/pushdown/collection.cpp
Labels: not-for-changelog

#12216 `--upload-batch-bytes` when it is set to maximum returns `Too much data` in `ydb tools restore`
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_import_data.cpp
Labels: bugfix

#8833 Support PG types in YT export
  ydb/core/ya.make
  ydb/core/yt/export_yt.cpp
  ydb/core/yt/export_yt.h
  ydb/core/yt/ya.make
  ydb/core/yt/yt_wrapper.cpp
  ydb/core/yt/yt_wrapper.h
Labels: improvement

#12160 YQ-3933 Fix FlagTrackDelivery
  ydb/library/yql/dq/actors/common/retry_queue.h
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#12223 Fix the wrong default value in docs
  ydb/docs/en/core/yql/reference/yql-core/syntax/alter-topic.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/create-topic.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-topic.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/create-topic.md
Labels: documentation

#11485 Update docker quick start section in docs
  ydb/docs/en/core/quickstart.md
  ydb/docs/ru/core/quickstart.md
Labels: documentation, external

#11325 Updated the intro to the session pool limit article
  ydb/docs/en/core/recipes/ydb-sdk/session-pool-limit.md
  ydb/docs/ru/core/recipes/ydb-sdk/session-pool-limit.md
Labels: documentation

#12238 Remove explicit codegen in cmake export
  .github/workflows/sync_cmakebuild.yml
  ydb/core/base/generated/ya.make
Labels: not-for-changelog

#12230 Add missing tsan.supp file (copy from ydb/library/actors/core)
  ydb/library/actors/core/harmonizer/tsan.supp
Labels: bugfix

#12220 AvgWriteBytes and transactions
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_write.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/ut_utils/topic_sdk_test_setup.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/ut_utils/topic_sdk_test_setup.h
Labels: bugfix

#12064 YQ-3912 Add read_group ( ~ connection_id) to pq cluster config
  ydb/core/fq/libs/actors/clusters_from_connections.cpp
  ydb/core/fq/libs/actors/clusters_from_connections.h
  ydb/core/fq/libs/test_connection/test_data_streams.cpp
  ydb/library/yql/providers/pq/common/yql_names.h
  ydb/library/yql/providers/pq/proto/dq_io.proto
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_settings.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_settings.h
  ydb/library/yql/tools/dqrun/examples/gateways.conf
Labels: not-for-changelog

#12167 Improve WriteActor
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/protos/kqp.proto
Labels: improvement

#12233 allow to keep rows order for stream lookup join
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.h
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/kqp_physical.proto
Labels: experimental-feature

#12243 activate included option
  ydb/docs/.yfm
Labels: documentation, external

#12240 Explicitly specify codegen binary name in ydb/core/base
  ydb/core/base/generated/codegen/ya.make
Labels: not-for-changelog

#12239 Typo: remove access
  ydb/core/tx/schemeshard/schemeshard_audit_log.cpp
Labels: bugfix

#12242 use YDB_KAFKA_PROXY_PORT for enable kafka
  ydb/public/tools/lib/cmds/__init__.py
Labels: not-for-changelog

#12229 Fix whitespace in schemeshard logging
  ydb/core/tx/schemeshard/schemeshard__operation_alter_solomon.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common_subdomain.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_solomon.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_indexed_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_finalize_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_initiate_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_table_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_upgrade_subdomain.cpp
Labels: not-for-changelog

#12042 parse and filter stat
  ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: new-feature

#12250 writing enabled flag for ev write
  ydb/core/tx/columnshard/columnshard__write.cpp
Labels: new-feature

#11920 The test `TxUsage:: WriteToTopic_Invalid_*` flashes
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#12249 fix cleanup volume limits and speed up versions index copy
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.h
Labels: improvement

#12111 Consistency option (kqp part)
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
Labels: not-for-changelog

#12258 add debug service changelog entry
  ydb/apps/ydb/CHANGELOG.md
Labels: not-for-changelog

#12260 Increment YDB CLI version to 2.17.0
  ydb/apps/ydb/CHANGELOG.md
  ydb/apps/ydb/version.txt
Labels: not-for-changelog

#12265 Fix olap linkage
  ydb/core/tx/columnshard/common/portion.h
Labels: bugfix

#12271 adjust grpc request latency buckets
  ydb/core/grpc_services/counters/counters.cpp
Labels: not-for-changelog

#12266 Fix bare domain backup collection behavior
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
Labels: bugfix

#11810 Fix LogPrefix initialization in Source/Sink/Transform/Channel helpers
  ydb/library/yql/dq/actors/compute/dq_compute_actor_async_input_helper.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_watermarks.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_watermarks.h
  ydb/library/yql/dq/actors/compute/ut/dq_compute_actor_async_input_helper_ut.cpp
Labels: bugfix

#12204 Support explicit bootstrap command using distconf
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/core/protos/config.proto
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#12281 regression run fix
  .github/workflows/regression_run.yml
Labels: not-for-changelog

#12279 Oltp EvWrite fixes
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/common/kqp_tx_manager.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: bugfix

#12262 aws credentials have been fixed
  ydb/core/external_sources/s3/ut/s3_aws_credentials_ut.cpp
  ydb/core/external_sources/ya.make
  ydb/library/yql/providers/common/http_gateway/yql_aws_signature.cpp
  ydb/library/yql/providers/common/http_gateway/yql_aws_signature_ut.cpp
Labels: new-feature

#12218 fix various problems in stream lookup
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
Labels: not-for-changelog

#12282 Support intersecting hosts in MergeBoxes
  ydb/core/mind/bscontroller/cmds_box.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/ut_bscontroller/main.cpp
Labels: not-for-changelog

#12273 compaction. lc levels configuration
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/ya.make
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.h
Labels: new-feature

#12198 Store sticky pages separately
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_executor_counters.h
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_part_loader.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
  ydb/core/tablet_flat/flat_writer_blocks.h
  ydb/core/tablet_flat/shared_page.h
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
Labels: not-for-changelog

#12285 Allow to decrease dq query timeout from SQL
  ydb/library/yql/providers/dq/actors/resource_allocator.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
Labels: area/yql, improvement

#12067 Refactor tracing configurator to be available from actor system threads
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/base/wilson_tracing_control.cpp
  ydb/core/base/wilson_tracing_control.h
  ydb/core/base/ya.make
  ydb/core/cms/console/jaeger_tracing_configurator.cpp
  ydb/core/cms/console/jaeger_tracing_configurator.h
  ydb/core/cms/console/jaeger_tracing_configurator_ut.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/grpc_services/grpc_request_proxy.h
  ydb/core/jaeger_tracing/sampling_throttling_configurator.cpp
  ydb/core/jaeger_tracing/sampling_throttling_configurator.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/test_client.cpp
Labels: improvement

#12280 Make incr backup tests independent of order
  ydb/core/tx/datashard/datashard_ut_incremental_backup.cpp
Labels: not-for-changelog

#12252 Changed docker registry for local-ydb docker image in quick-start article
  ydb/docs/presets.yaml
Labels: documentation

#12301 Snapshot livetime control
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/inflight_request_tracker.cpp
  ydb/core/tx/columnshard/inflight_request_tracker.h
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
Labels: bugfix

#12305 YDB FQ: extend data source settings for Logging data source
  ydb/library/yql/providers/generic/connector/api/common/data_source.proto
Labels: not-for-changelog

#12286 Optionally allow nullable pk in column tables
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/tx/schemeshard/olap/operations/alter/standalone/update.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/schema/update.h
  ydb/core/tx/schemeshard/olap/store/store.cpp
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: new-feature

#12296 correct synchronization after tablet reboot
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.h
  ydb/core/tx/columnshard/engines/changes/actualization/controller/controller.h
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.h
  ydb/core/tx/columnshard/engines/changes/cleanup_tables.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.h
  ydb/core/tx/columnshard/engines/changes/indexation.h
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/scheme/column/info.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/index/index.h
  ydb/core/tx/columnshard/engines/storage/actualizer/scheme/counters.h
  ydb/core/tx/columnshard/engines/storage/actualizer/scheme/scheme.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/scheme/scheme.h
  ydb/core/tx/columnshard/engines/storage/granule/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule/granule.h
  ydb/library/services/services.proto
Labels: improvement

#12319 Simplify ds incr backup test helper
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
Labels: not-for-changelog

#12317 Few more dread cache counters
  ydb/core/persqueue/dread_cache_service/caching_service.cpp
Labels: improvement

#12290 Grpc authentication tests
  ydb/services/ydb/ut/ya.make
  ydb/services/ydb/ydb_login_ut.cpp
Labels: not-for-changelog

#12315 Dont consider prefix indices
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
Labels: bugfix

#12329 setup large hard limit bytes for ydb in tpch test
  ydb/tests/functional/tpc/ya.make
Labels: not-for-changelog

#12322 Fixed Cost Based Optimizer Level 2
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
Labels: bugfix

#12304 Fix parsing multiple csv columns with escaped quotes in `ydb import file csv`
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/common/csv_parser.cpp
  ydb/public/lib/ydb_cli/common/csv_parser.h
  ydb/public/lib/ydb_cli/common/csv_parser_ut.cpp
Labels: area/cli, bugfix

#12272 EnableImmediateWritingOnBulkUpsert by default
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/testlib/test_client.h
Labels: experimental-feature

#12332 fix script construction
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.cpp
Labels: bugfix

#12346 Fix misleading schemeshard logs
  ydb/core/tx/schemeshard/schemeshard__operation_part.cpp
Labels: not-for-changelog

#12347 Add more fields in describe consumer in cpp sdk
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic.cpp
  ydb/public/sdk/cpp/client/ydb_topic/include/control_plane.h
  ydb/public/sdk/cpp/client/ydb_topic/ut/describe_topic_ut.cpp
Labels: improvement

#12333 Process heartbeats
  ydb/core/protos/counters_replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/controller_impl.h
  ydb/core/tx/replication/controller/schema.h
  ydb/core/tx/replication/controller/session_info.cpp
  ydb/core/tx/replication/controller/session_info.h
  ydb/core/tx/replication/controller/tx_heartbeat.cpp
  ydb/core/tx/replication/controller/tx_init.cpp
  ydb/core/tx/replication/controller/ya.make
Labels: not-for-changelog

#12298 Add new UT in PDisk for TEvChunkWrite contract
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_actions.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_races.cpp
  ydb/core/blobstorage/ut_pdiskfit/lib/basic_test.cpp
  ydb/core/load_test/pdisk_read.cpp
Labels: bugfix

#12337 The value of `PQ/BytesWriteOK` for writing to a transaction
  ydb/core/persqueue/partition_write.cpp
Labels: bugfix

#12341 Fix TArrowBlock::From usage for temporary objects in DQ sources
  ydb/library/yql/dq/runtime/dq_input_impl.h
Labels: area/yql, bugfix

#11303 streamlookup join: add lru size monitoring
  ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
Labels: not-for-changelog

#11352 Add no-consumer cli flag to topic read
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
Labels: improvement

#12312 Add ydb cli replace and fetch storage config commands
  ydb/public/lib/ydb_cli/commands/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_admin.cpp
  ydb/public/lib/ydb_cli/commands/ydb_storage_config.cpp
  ydb/public/lib/ydb_cli/commands/ydb_storage_config.h
  ydb/public/sdk/cpp/client/ydb_bsconfig/ya.make
  ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.cpp
  ydb/public/sdk/cpp/client/ydb_bsconfig/ydb_storage_config.h
  ydb/public/sdk/cpp/ya.make
Labels: new-feature

#12361 Fix more misleading schemeshard logs
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
Labels: not-for-changelog

#12364 The test `TxUsage:: WriteToTopic_Demo_17`
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#12369 Upd regression workflow
  .github/workflows/regression_run.yml
Labels: not-for-changelog

#12351 fix compaction levels constuction
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
Labels: bugfix

#12343 Add the rest stuff for autoscaling
  ydb/core/cms/console/console__alter_tenant.cpp
  ydb/core/cms/console/console__create_tenant.cpp
  ydb/core/cms/console/console_tenants_manager.cpp
  ydb/core/cms/console/console_tenants_manager.h
  ydb/core/cms/console/feature_flags_configurator_ut.cpp
  ydb/core/mind/hive/domain_info.cpp
  ydb/core/mind/hive/domain_info.h
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/hive_schema.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/monitoring.cpp
  ydb/core/mind/hive/scale_recommender_policy_ut.cpp
  ydb/core/mind/hive/tx__configure_scale_recommender.cpp
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/ut/ya.make
  ydb/core/mind/hive/ya.make
  ydb/core/protos/config.proto
  ydb/core/protos/counters_hive.proto
  ydb/core/protos/feature_flags.proto
  ydb/core/protos/hive.proto
  ydb/core/testlib/tenant_helpers.h
  ydb/core/testlib/tenant_runtime.cpp
  ydb/public/api/protos/ydb_cms.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_hive_/flat_hive.schema
Labels: not-for-changelog

#12374 Revert "rework grpc monitoring (#11191)"
  ydb/core/fq/libs/compute/ydb/control_plane/compute_database_control_plane_service.cpp
  ydb/core/fq/libs/compute/ydb/control_plane/ya.make
  ydb/core/fq/libs/config/protos/compute.proto
Labels: new-feature

#12375 Added CODEOWNERS for C++ SDK
  .github/CODEOWNERS
Labels: not-for-changelog

#12371 Fix path to local ydb docker image
  ydb/docs/presets.yaml
Labels: new-feature

#12385 fix timeout regression_run.yml
  .github/workflows/regression_run.yml
Labels: not-for-changelog

#12132 Add reference to YDB SQLAlchemy + Jupyter Notebook example
  ydb/docs/en/core/integrations/gui/_includes/toc-table.md
  ydb/docs/en/core/integrations/gui/jupyter.md
  ydb/docs/en/core/integrations/gui/toc-ide.yaml
  ydb/docs/ru/core/integrations/gui/_includes/toc-table.md
  ydb/docs/ru/core/integrations/gui/jupyter.md
  ydb/docs/ru/core/integrations/gui/toc-ide.yaml
Labels: documentation

#12314 [docs] consolidate the coordination nodes content
  ydb/docs/en/core/concepts/datamodel/coordination-node.md
  ydb/docs/en/core/concepts/datamodel/toc_i.yaml
  ydb/docs/en/core/concepts/glossary.md
  ydb/docs/en/core/recipes/ydb-sdk/config-publication.md
  ydb/docs/en/core/recipes/ydb-sdk/distributed-lock.md
  ydb/docs/en/core/recipes/ydb-sdk/index.md
  ydb/docs/en/core/recipes/ydb-sdk/leader-election.md
  ydb/docs/en/core/recipes/ydb-sdk/service-discovery.md
  ydb/docs/en/core/recipes/ydb-sdk/toc_i.yaml
  ydb/docs/en/core/reference/ydb-sdk/coordination.md
  ydb/docs/en/core/reference/ydb-sdk/toc_i.yaml
  ydb/docs/ru/core/concepts/datamodel/coordination-node.md
  ydb/docs/ru/core/concepts/datamodel/toc_i.yaml
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/recipes/ydb-sdk/config-publication.md
  ydb/docs/ru/core/recipes/ydb-sdk/distributed-lock.md
  ydb/docs/ru/core/recipes/ydb-sdk/index.md
  ydb/docs/ru/core/recipes/ydb-sdk/leader-election.md
  ydb/docs/ru/core/recipes/ydb-sdk/service-discovery.md
  ydb/docs/ru/core/recipes/ydb-sdk/toc_i.yaml
  ydb/docs/ru/core/reference/ydb-sdk/coordination.md
  ydb/docs/ru/core/reference/ydb-sdk/index.md
  ydb/docs/ru/core/reference/ydb-sdk/toc_i.yaml
Labels: documentation

#12383 dont use removed portions before remove from local_db - prevent race …
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/filler.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/filler.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/granule_view.h
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.h
  ydb/core/tx/columnshard/engines/reader/sys_view/optimizer/optimizer.h
Labels: bugfix

#12382 split logging services through huge messages volume in summary logs
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/sparsed/logic.cpp
  ydb/core/tx/columnshard/engines/column_engine.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/data_events/events.h
  ydb/library/services/services.proto
Labels: improvement

#12384 fix compaction policy modification
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.h
Labels: bugfix

#12377 Publish YDB CLI 2.17.0
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/linux.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/windows.md
  ydb/docs/ru/core/changelog-cli.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/linux.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/windows.md
Labels: documentation

#12391 fix value parsing recursion issues
  ydb/core/viewer/viewer_query.h
Labels: bugfix

#12380 dont use default columns for merger
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.h
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.h
Labels: performance

#12378 alter columns for many columns in time
  ydb/core/kqp/gateway/behaviour/tablestore/operations/alter_column.cpp
Labels: improvement

#12276 Make configurable timeout for waiting CAs
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/protos/table_service_config.proto
Labels: improvement

#12388 Fix whitespace in some schemeshard logs
  ydb/core/tx/schemeshard/olap/operations/alter_store.cpp
  ydb/core/tx/schemeshard/olap/operations/alter_table.cpp
  ydb/core/tx/schemeshard/olap/operations/create_store.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_store.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_fs.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_kesus.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common.h
  ydb/core/tx/schemeshard/schemeshard__operation_common_subdomain.h
  ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_copy_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_fs.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_kesus.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_rtmr.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_kesus.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_pq.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_solomon.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_subdomain.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_finalize_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_initiate_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_mkdir.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_split_merge.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_upgrade_subdomain.cpp
Labels: not-for-changelog

#12335 Handle backup collection structure on restore
  .github/config/muted_ya.txt
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/datashard/datashard_ut_incremental_backup.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/schemeshard/schemeshard__backup_collection_common.cpp
  ydb/core/tx/schemeshard/schemeshard__backup_collection_common.h
  ydb/core/tx/schemeshard/schemeshard__op_traits.h
  ydb/core/tx/schemeshard/schemeshard__operation_backup_backup_collection.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_backup_incremental_backup_collection.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_restore_incremental_backup.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_restore_backup_collection.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log_fragment.cpp
  ydb/core/tx/tx_proxy/schemereq.cpp
Labels: not-for-changelog

#12410 channels count fix for standalone table
  ydb/core/statistics/service/ut/ut_http_request.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
Labels: bugfix

#12404 Allow data query for olap
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/opt/kqp_opt.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#12420 Fix benchmarks/run_tests
  ydb/library/benchmarks/runner/run_tests/run_tests.py
Labels: not-for-changelog

#12414 portions index simplification
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/storage/granule/granule.h
  ydb/core/tx/columnshard/engines/storage/granule/portions_index.cpp
  ydb/core/tx/columnshard/engines/storage/granule/portions_index.h
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
Labels: improvement

#12401 Split IC peer name labels
  ydb/library/actors/interconnect/interconnect_counters.cpp
  ydb/library/actors/interconnect/interconnect_counters.h
  ydb/library/actors/interconnect/interconnect_tcp_proxy.cpp
  ydb/library/actors/interconnect/ut/channel_scheduler_ut.cpp
Labels: not-for-changelog

#12428 Update regression_run.yml
  .github/workflows/regression_run.yml
Labels: not-for-changelog

#12201 ContinueExecute on non-empty transform
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
Labels: not-for-changelog

#11865 streamlookup: Fix UAF when GetAsyncInputData called before Bootstrap or after PassAway
  ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
Labels: bugfix

#11935 add kafka port to quick start
  ydb/docs/en/core/quickstart.md
  ydb/docs/ru/core/quickstart.md
Labels: not-for-changelog

#12402 Fix uuid storage state
  ydb/docs/en/core/yql/reference/yql-core/types/_includes/datatypes_primitive_string.md
  ydb/docs/ru/core/yql/reference/yql-core/types/_includes/datatypes_primitive_string.md
Labels: documentation

#12302 YQ-3943 Fix TopicPartitionsLimitPerNode limit
  ydb/core/fq/libs/row_dispatcher/coordinator.cpp
  ydb/core/fq/libs/row_dispatcher/ut/coordinator_ut.cpp
Labels: not-for-changelog

#12102 YQ-3912 Add read group to row dispatcher
  ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.h
  ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.h
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#12422 Fix miscalculated budget in THarmonizer
  ydb/library/actors/core/cpu_manager.cpp
  ydb/library/actors/core/cpu_manager.h
  ydb/library/actors/core/executor_pool.h
  ydb/library/actors/core/executor_pool_base.cpp
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_pool_basic.h
  ydb/library/actors/core/executor_pool_io.cpp
  ydb/library/actors/core/executor_pool_io.h
  ydb/library/actors/core/executor_pool_shared.cpp
  ydb/library/actors/core/executor_pool_shared.h
  ydb/library/actors/core/executor_thread_ctx.h
  ydb/library/actors/core/harmonizer.cpp
  ydb/library/actors/core/harmonizer/cpu_consumption.cpp
  ydb/library/actors/core/harmonizer/cpu_consumption.h
  ydb/library/actors/core/harmonizer/debug.h
  ydb/library/actors/core/harmonizer/defs.h
  ydb/library/actors/core/harmonizer/harmonizer.cpp
  ydb/library/actors/core/harmonizer/harmonizer.h
  ydb/library/actors/core/harmonizer/history.h
  ydb/library/actors/core/harmonizer/pool.cpp
  ydb/library/actors/core/harmonizer/pool.h
  ydb/library/actors/core/harmonizer/shared_info.cpp
  ydb/library/actors/core/harmonizer/shared_info.h
  ydb/library/actors/core/harmonizer/ut/harmonizer_ut.cpp
  ydb/library/actors/core/harmonizer/ut/history_ut.cpp
  ydb/library/actors/core/harmonizer/ut/ya.make
  ydb/library/actors/core/harmonizer/waiting_stats.cpp
  ydb/library/actors/core/harmonizer/waiting_stats.h
  ydb/library/actors/core/harmonizer/ya.make
  ydb/library/actors/core/mon_stats.h
  ydb/library/actors/core/probes.h
  ydb/library/actors/core/ya.make
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem, bugfix

#12418 Fix not allocated vectors when used MovedPatch
  ydb/core/blobstorage/dsproxy/dsproxy_patch.cpp
Labels: area/blobstorage, bugfix

#12429 YDB FQ: more support for Logging as an external data source
  ydb/library/yql/providers/generic/actors/yql_generic_read_actor.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_token_provider.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_token_provider.h
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
Labels: not-for-changelog

#12442 YDBDOCS-935: fix mistype in stock.md
  ydb/docs/ru/core/reference/ydb-cli/commands/workload/_includes/stock.md
Labels: documentation

#12441 [docs] update Apple Silicon note in quickstart.md
  ydb/docs/en/core/quickstart.md
  ydb/docs/ru/core/quickstart.md
Labels: documentation

#12436 [docs] add ydbops to downloads page
  ydb/docs/en/core/downloads/_includes/ydbops/darwin_amd64.md
  ydb/docs/en/core/downloads/_includes/ydbops/darwin_arm64.md
  ydb/docs/en/core/downloads/_includes/ydbops/linux.md
  ydb/docs/en/core/downloads/index.md
  ydb/docs/ru/core/downloads/_includes/ydbops/darwin_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydbops/darwin_arm64.md
  ydb/docs/ru/core/downloads/_includes/ydbops/linux.md
  ydb/docs/ru/core/downloads/index.md
Labels: documentation

#12426 Simple queue improvements
  ydb/tools/simple_queue/__main__.py
Labels: not-for-changelog

#12437 avoid code duplication of cell vectors hascode and equals
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.cpp
  ydb/core/scheme/scheme_tablecell.cpp
  ydb/core/scheme/scheme_tablecell.h
  ydb/core/scheme/ya.make
  ydb/core/tx/datashard/conflicts_cache.h
Labels: not-for-changelog

#12446 fix time sync check
  ydb/core/health_check/health_check.cpp
Labels: bugfix

#12287 Audit log: No permission to connect to the database
  ydb/core/grpc_services/audit_log.cpp
  ydb/core/grpc_services/audit_log.h
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/services/ydb/ydb_login_ut.cpp
Labels: bugfix

#12434 YQ-3912 Add read group to row dispatcher / to stable
  ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.h
  ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.h
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#12452 Added TYQLConclusionStatusImpl with NYql::TIssues as error
  ydb/library/conclusion/generic/generic_status.h
  ydb/library/conclusion/generic/result.h
  ydb/library/conclusion/generic/status.h
  ydb/library/conclusion/generic/string_status.h
  ydb/library/conclusion/generic/ya.make
  ydb/library/conclusion/generic/yql_status.h
  ydb/library/conclusion/status.h
Labels: improvement

#12421 Mute unstable tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#12463 Fix olap reads in data query
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#12366 PDisk's noop scheduler, second attempt
  ydb/core/blobstorage/lwtrace_probes/blobstorage_probes.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.cpp
  ydb/core/protos/blobstorage_pdisk_config.proto
  ydb/core/protos/config.proto
Labels: performance

#12473 Prepare test to migration
  ydb/tests/fq/s3/test_insert.py
  ydb/tests/fq/s3/ya.make
Labels: external

#12396 YDB FQ: fix list of datasources supported by fq-connector-go
  ydb/docs/en/core/devops/manual/federated-queries/connector-deployment.md
  ydb/docs/ru/core/devops/manual/federated-queries/connector-deployment.md
Labels: documentation

#12465 YQ-3955 RD fixed uncaught exception error
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: bugfix

#12397 YQ-3893 Remove query_id metrics on terminate
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_write_actor.cpp
Labels: not-for-changelog

#11963 fstec: Add rules for password strength
  ydb/core/cms/console/console__replace_yaml_config.cpp
  ydb/core/config/init/init_impl.h
  ydb/core/config/validation/auth_config_validator.cpp
  ydb/core/config/validation/auth_config_validator_ut/auth_config_validator_ut.cpp
  ydb/core/config/validation/auth_config_validator_ut/ya.make
  ydb/core/config/validation/validators.cpp
  ydb/core/config/validation/validators.h
  ydb/core/config/validation/ya.make
  ydb/core/protos/auth.proto
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
  ydb/library/login/login.cpp
  ydb/library/login/login.h
  ydb/library/login/login_ut.cpp
  ydb/library/login/password_checker/password_checker.cpp
  ydb/library/login/password_checker/password_checker.h
  ydb/library/login/password_checker/password_checker_ut.cpp
  ydb/library/login/password_checker/ut/ya.make
  ydb/library/login/password_checker/ya.make
  ydb/library/login/ya.make
Labels: new-feature

#12499 Enable SystemView.Nodes test
  ydb/core/sys_view/ut/ya.make
  ydb/core/sys_view/ut_kqp.cpp
  ydb/core/sys_view/ya.make
Labels: not-for-changelog

#12501 Changes minidump_script.py
  ydb/deploy/docker/breakpad/minidump_script.py
Labels: improvement

#12489 Fix incorrect counter of inflight requests for get_storage_channel_st…
  ydb/core/keyvalue/keyvalue_state.cpp
  ydb/services/keyvalue/grpc_service_ut.cpp
Labels: area/blobstorage

#12488 Merge to 24-3: Fix incorrect counter of inflight requests for get_storage_channel_status
  ydb/core/keyvalue/keyvalue_state.cpp
  ydb/services/keyvalue/grpc_service_ut.cpp
Labels: area/blobstorage

#12504 Mute unstable and unmute stable
  .github/config/muted_ya.txt
Labels: not-for-changelog

#12431 Add GetBlock request
  ydb/core/base/blobstorage.cpp
  ydb/core/base/blobstorage.h
  ydb/core/blob_depot/agent/agent_impl.h
  ydb/core/blob_depot/agent/comm.cpp
  ydb/core/blob_depot/agent/request.cpp
  ydb/core/blob_depot/agent/storage_get_block.cpp
  ydb/core/blob_depot/agent/ya.make
  ydb/core/blob_depot/blob_depot.cpp
  ydb/core/blob_depot/blocks.cpp
  ydb/core/blob_depot/blocks.h
  ydb/core/blob_depot/events.h
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_get_block.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_impl.h
  ydb/core/blobstorage/dsproxy/dsproxy_mon.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_mon.h
  ydb/core/blobstorage/dsproxy/dsproxy_nodemon.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_nodemon.h
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
  ydb/core/blobstorage/dsproxy/mock/dsproxy_mock.cpp
  ydb/core/blobstorage/dsproxy/mock/model.h
  ydb/core/blobstorage/dsproxy/ut_fat/dsproxy_ut.cpp
  ydb/core/blobstorage/dsproxy/ya.make
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/testing/group_overseer/group_overseer.cpp
  ydb/core/blobstorage/ut_blobstorage/get_block.cpp
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/protos/blob_depot.proto
  ydb/library/services/services.proto
Labels: new-feature

#12476 scan optimization for filter applying in case simple chunks
  ydb/core/formats/arrow/arrow_filter.cpp
  ydb/core/formats/arrow/arrow_filter.h
  ydb/core/formats/arrow/common/adapter.h
  ydb/core/formats/arrow/program.cpp
  ydb/core/formats/arrow/reader/merger.cpp
  ydb/core/formats/arrow/ut/ut_column_filter.cpp
  ydb/core/tx/columnshard/counters/scan.cpp
  ydb/core/tx/columnshard/counters/scan.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetched_data.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.h
  ydb/library/formats/arrow/accessor/abstract/accessor.h
Labels: improvement

#12514 Don't run spilling (unused) with asan
  ydb/library/yql/core/spilling/ut/ya.make
Labels: not-for-changelog

#11155 Add BS performance metrics dashboards
  ydb/deploy/helm/ydb-prometheus/dashboards/distributed-storage-performance-metrics.json
Labels: new-feature

#12519 commit processing fixes
  ydb/core/tx/columnshard/columnshard__progress_tx.cpp
  ydb/core/tx/columnshard/engines/column_engine.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/constructor/read_metadata.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/read_metadata.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/plain_read_data.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/constructor/read_metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/plain_read_data.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
  ydb/core/tx/columnshard/transactions/operators/ev_write/secondary.h
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.h
  ydb/library/services/services.proto
Labels: bugfix

#12432 Library "files" for ydb/public/lib/ydb_cli/dump
  ydb/library/backup/backup.cpp
  ydb/library/backup/ya.make
  ydb/public/lib/ydb_cli/commands/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/dump/dump.cpp
  ydb/public/lib/ydb_cli/dump/dump.h
  ydb/public/lib/ydb_cli/dump/files/files.cpp
  ydb/public/lib/ydb_cli/dump/files/files.h
  ydb/public/lib/ydb_cli/dump/files/ya.make
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/ya.make
Labels: not-for-changelog

#12508 Revert incorrect changes in BlobDepot
  ydb/core/blob_depot/agent/agent_impl.h
  ydb/core/blob_depot/agent/comm.cpp
  ydb/core/blob_depot/agent/request.cpp
  ydb/core/blob_depot/blob_depot.cpp
  ydb/core/blob_depot/blocks.cpp
  ydb/core/blob_depot/blocks.h
  ydb/core/blob_depot/events.h
  ydb/core/protos/blob_depot.proto
Labels: not-for-changelog

#12520 Add config option for ArrayBufferMinFillPercentage
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_impl.h
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/runtime/kqp_tasks_runner.cpp
  ydb/core/kqp/runtime/kqp_tasks_runner.h
  ydb/core/protos/table_service_config.proto
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor.h
  ydb/library/yql/dq/proto/dq_tasks.proto
  ydb/library/yql/dq/runtime/dq_output_consumer.cpp
  ydb/library/yql/dq/runtime/dq_output_consumer.h
  ydb/library/yql/dq/runtime/dq_tasks_runner.cpp
  ydb/library/yql/dq/runtime/dq_tasks_runner.h
Labels: experimental-feature

#12516 fix TPDiskTest::AllRequestsAreAnsweredOnPDiskRestart
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
Labels: bugfix

#12506 Clarify ListHas docs
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/list.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/list.md
Labels: documentation

#12539 Update VisitOrDefault docs
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
Labels: documentation, area/yql

#12540 Update StructMerge docs
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/struct.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/struct.md
Labels: documentation, area/yql

#12268 Register a custom audit log item builder
  ydb/core/audit/audit_log.h
  ydb/core/audit/audit_log_impl.cpp
  ydb/core/audit/audit_log_item_builder.h
  ydb/core/audit/ya.make
  ydb/core/protos/config.proto
Labels: not-for-changelog

#12530 v2 portions usage only available
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/db_wrapper.h
  ydb/core/tx/columnshard/engines/storage/granule/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule/stages.cpp
  ydb/core/tx/columnshard/engines/storage/granule/stages.h
  ydb/core/tx/columnshard/engines/ut/ut_insert_table.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/normalizer/portion/chunks_actualization.cpp
  ydb/core/tx/columnshard/normalizer/portion/clean_empty.cpp
  ydb/core/tx/columnshard/normalizer/portion/leaked_blobs.cpp
  ydb/core/tx/columnshard/normalizer/portion/normalizer.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_v1_chunks.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_v2_chunks.cpp
Labels: performance

#12536 Refactoring ydb/library/backup/backup.cpp
  ydb/library/backup/backup.cpp
Labels: not-for-changelog
