Repository ydb-platform/ydb, pull requests merged in 2024-09, with the labels that each got.

#8477 validations for prevent incorrect data in local db
  ydb/core/tx/columnshard/columnshard_schema.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.h
Labels: improvement

#8446 Add unit test: drop then add column with different type
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
Labels: not-for-changelog

#8567 Allow multiple LoadSystemFunctions calls
  ydb/library/yql/parser/pg_catalog/catalog.cpp
Labels: improvement

#8573 YDBDOCS-740: update dev/primary-key/column-oriented.md
  ydb/docs/en/core/dev/primary-key/column-oriented.md
  ydb/docs/ru/core/dev/primary-key/column-oriented.md
Labels: documentation

#7583 only check resource maximum for memory
  ydb/core/mind/hive/node_info.cpp
Labels: improvement

#8570 ExtractCommonPredicatesFromLogicalOps setting and optimizers
  ydb/library/yql/core/common_opt/ya.make
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/common_opt/yql_co_simple2.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/optimizers/and_absorption.cfg
  ydb/library/yql/tests/sql/suites/optimizers/and_absorption.sql
  ydb/library/yql/tests/sql/suites/optimizers/or_absorption.cfg
  ydb/library/yql/tests/sql/suites/optimizers/or_absorption.sql
  ydb/library/yql/tests/sql/suites/optimizers/or_distributive.cfg
  ydb/library/yql/tests/sql/suites/optimizers/or_distributive.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: area/yql, experimental-feature

#8504 [KQP] Make KqpOlapFilter be shown in a query plan
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/kqp_statistics_transformer.cpp
  ydb/core/kqp/ut/olap/clickbench_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/query/kqp_explain_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.h
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-1
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-10
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-11
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-12
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-13
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-14
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-19
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-20
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-21
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-22
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-23
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-24
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-25
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-26
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-27
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-28
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-30
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-31
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-36
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-37
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-38
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-39
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-40
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-41
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-42
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-7
Labels: new-feature

#8535 Add registrator to TTxChainSession
  ydb/core/tx/schemeshard/olap/bg_tasks/tx_chain/session.h
Labels: new-feature

#8586 Do not ignore configure errors
  build/internal/ya.conf
Labels: not-for-changelog

#8396 Add new INFO LOG message for groups which cannot be healed by SelfHeal
  ydb/core/mind/bscontroller/self_heal.cpp
Labels: improvement

#8599 Fix error processing
  ydb/tests/olap/lib/ydb_cluster.py
  ydb/tests/olap/scenario/helpers/scenario_tests_helper.py
Labels: new-feature

#8600 -o pipefail in graph_compare
  .github/scripts/graph_compare.sh
Labels: not-for-changelog

#8580 Fix column livecycle
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/snapshot_scheme.h
Labels: bugfix

#8591 provide correct path id to lock info
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/read_metadata.cpp
Labels: improvement

#8547 Timestamp arrow -> clickhouse parsing fix
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/core/external_sources/object_storage/inference/infer_config.cpp
  ydb/core/external_sources/object_storage/inference/ya.make
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#8598 Use IS_CTX_LOG_PRIORITY_ENABLED in STLOGX to get actual logger settings
  ydb/core/util/stlog.h
Labels: bugfix

#8592 Fix external reference precharging in datashard read iterators
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator_ext_blobs.cpp
  ydb/core/tx/datashard/read_iterator.h
Labels: bugfix

#8606 Don't run large_serializable in PR (2nd attempt)
  ydb/tests/functional/large_serializable/ya.make
Labels: not-for-changelog

#8236 remove anon namespace
  ydb/core/grpc_services/base/base.h
Labels: not-for-changelog

#8590 Introduce a common Shared Cache cache interface
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/util/cache_cache.h
  ydb/core/util/cache_cache_iface.h
  ydb/core/util/cache_cache_ut.cpp
Labels: not-for-changelog

#8517 The race between `TEvProposeTransaction` and `TEvLockStatus`
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/topics/kqp_topics.cpp
  ydb/core/kqp/topics/kqp_topics.h
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#8501 Implement computation node for BlockMapJoinCore (Left and Inner) with multi dict
  ydb/library/yql/minikql/comp_nodes/mkql_block_map_join.cpp
  ydb/library/yql/minikql/comp_nodes/ut/mkql_block_map_join_ut.cpp
  ydb/library/yql/minikql/mkql_program_builder.cpp
Labels: area/yql, new-feature

#8610 Reset __async_replica attr after changing REPLICATION_MODE to NONE
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_table.cpp
  ydb/core/tx/schemeshard/schemeshard_path_element.cpp
  ydb/core/tx/schemeshard/schemeshard_path_element.h
  ydb/core/tx/schemeshard/ut_replication/ut_replication.cpp
Labels: not-for-changelog

#8588 fix race on enqueue tx_commit in case long synchronization
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write_index.cpp
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__plan_step.cpp
  ydb/core/tx/columnshard/columnshard__progress_tx.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
  ydb/core/tx/columnshard/transactions/operators/ev_write/secondary.h
Labels: improvement

#8609 remove validation throught available reask in timeout
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
Labels: bugfix

#8614 we have to notify cs at first to add lock information
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
Labels: improvement

#8506 delete query from compile cache if it is existed during insert
  ydb/core/kqp/common/simple/query_id.cpp
  ydb/core/kqp/common/simple/query_id.h
  ydb/core/kqp/common/simple/settings.h
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
Labels: improvement

#8604 YDB FQ: fix use of Greenplum as an external datasource
  ydb/core/fq/libs/control_plane_proxy/actors/query_utils.cpp
  ydb/core/fq/libs/db_id_async_resolver_impl/mdb_endpoint_generator.cpp
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ms_sql_server/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/mysql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/oracle/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/join/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/utils/docker_compose.py
  ydb/tests/fq/generic/docker-compose.yml
  ydb/tests/fq/generic/greenplum/Dockerfile
  ydb/tests/fq/generic/greenplum/README.md
  ydb/tests/fq/generic/greenplum/init_db.sh
  ydb/tests/fq/generic/test_greenplum.py
  ydb/tests/fq/generic/test_join.py
  ydb/tests/fq/generic/utils/endpoint_determiner.py
  ydb/tests/fq/generic/utils/settings.py
  ydb/tests/fq/generic/ya.make
  ydb/tests/tools/fq_runner/fq_client.py
  ydb/tests/tools/fq_runner/kikimr_utils.py
  ydb/tests/tools/mdb_mock/__main__.py
Labels: bugfix

#8626 Relax FlatMap over Extend requirements
  ydb/library/yql/core/common_opt/yql_co_flow1.cpp
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: area/yql, improvement

#8548 FixNamespaceComments in /contrib/ydb
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/federated_query/common/common.h
  ydb/library/yql/providers/generic/actors/yql_generic_provider_factories.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_provider_factories.h
  ydb/library/yql/providers/generic/connector/libcpp/client.cpp
  ydb/library/yql/providers/generic/connector/libcpp/client.h
  ydb/library/yql/providers/generic/connector/libcpp/error.cpp
  ydb/library/yql/providers/generic/connector/libcpp/error.h
  ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/stream_iterator_mock.h
  ydb/library/yql/providers/generic/connector/libcpp/utils.cpp
  ydb/library/yql/providers/generic/connector/libcpp/utils.h
  ydb/library/yql/providers/generic/expr_nodes/yql_generic_expr_nodes.h
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.h
  ydb/library/yql/providers/generic/provider/yql_generic_datasink.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_datasink_execution.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_datasource.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.h
  ydb/library/yql/providers/generic/provider/yql_generic_io_discovery.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_logical_opt.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_mkql_compiler.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_mkql_compiler.h
  ydb/library/yql/providers/generic/provider/yql_generic_physical_opt.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_settings.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_state.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_state.h
  ydb/library/yql/providers/generic/provider/yql_generic_utils.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_utils.h
  ydb/library/yql/providers/generic/pushdown/ut/match_predicate_ut.cpp
  ydb/library/yql/providers/generic/pushdown/yql_generic_column_statistics.h
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.cpp
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.h
  ydb/library/yql/utils/actor_system/manager.cpp
  ydb/library/yql/utils/actor_system/manager.h
Labels: not-for-changelog, external

#8608 Test runtime: Easy wait for a single event
  ydb/core/testlib/actors/block_events.h
  ydb/core/testlib/actors/test_runtime_ut.cpp
  ydb/core/testlib/actors/wait_events.cpp
  ydb/core/testlib/actors/wait_events.h
  ydb/core/testlib/actors/ya.make
Labels: not-for-changelog

#8576 Use actual cores count
  ydb/core/kqp/runtime/kqp_compute_scheduler.cpp
  ydb/core/kqp/runtime/kqp_compute_scheduler.h
Labels: bugfix

#7698 Update python app docs
  ydb/docs/en/core/dev/example-app/python/index.md
  ydb/docs/ru/core/dev/example-app/python/index.md
Labels: documentation

#8648 [docs] some fixes for en/core/dev/example-app/
  ydb/docs/en/core/dev/example-app/_includes/auxilary/addition.md
  ydb/docs/en/core/dev/example-app/_includes/auxilary/pragmatablepathprefix.md
  ydb/docs/en/core/dev/example-app/_includes/index.md
  ydb/docs/en/core/dev/example-app/_includes/steps/01_init.md
  ydb/docs/en/core/dev/example-app/_includes/steps/02_create_table.md
  ydb/docs/en/core/dev/example-app/_includes/steps/03_write_queries.md
  ydb/docs/en/core/dev/example-app/_includes/steps/04_query_processing.md
  ydb/docs/en/core/dev/example-app/_includes/steps/06_param_queries.md
  ydb/docs/en/core/dev/example-app/_includes/steps/07_param_prep_queries.md
  ydb/docs/en/core/dev/example-app/_includes/steps/08_scan_query.md
  ydb/docs/en/core/dev/example-app/_includes/steps/09_multistep_transactions.md
  ydb/docs/en/core/dev/example-app/_includes/steps/10_transaction_control.md
  ydb/docs/en/core/dev/example-app/_includes/steps/11_async_requests.md
  ydb/docs/en/core/dev/example-app/_includes/steps/50_error_handling.md
  ydb/docs/en/core/dev/example-app/go/_includes/run_custom.md
  ydb/docs/en/core/dev/example-app/go/index.md
  ydb/docs/en/core/dev/example-app/java/_includes/run_custom.md
  ydb/docs/en/core/dev/example-app/java/index.md
  ydb/docs/en/core/dev/example-app/python/_includes/run_custom.md
  ydb/docs/en/core/dev/example-app/python/index.md
Labels: documentation

#8472 Add UpsertWhileSplitTest
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
Labels: new-feature

#8644 Add const to the condition function
  ydb/core/testlib/actors/block_events.h
  ydb/core/testlib/actors/test_runtime_ut.cpp
  ydb/core/tx/datashard/datashard_ut_build_index.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/core/tx/mediator/mediator_ut.cpp
  ydb/core/tx/time_cast/time_cast_ut.cpp
Labels: not-for-changelog

#8646 Statistics: TWaitForFirstEvent
  ydb/core/statistics/ut_common/ut_common.cpp
Labels: not-for-changelog

#8611 More confident DS proxy phantom blob checking logic
  ydb/core/blobstorage/dsproxy/dsproxy_get_impl.cpp
Labels: area/blobstorage, improvement

#8664 CDC supported types test
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
Labels: not-for-changelog

#8578 Enable CTAS Immediate EvWrite for CS
  .github/config/muted_ya.txt
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
Labels: not-for-changelog

#8627 YT: add pagination for the GetJobStderr command
  ydb/library/yql/providers/dq/actors/yt/yt_wrapper.cpp
Labels: external

#8553 Fix stats inside plan for full stats mode
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_executer_stats.cpp
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/protos/dq_stats.proto
Labels: bugfix

#8632 data query uses different local compute tasks param
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#8221 Consumer describe command in ydb cli
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.h
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
  ydb/public/lib/ydb_cli/common/print_utils.cpp
  ydb/public/lib/ydb_cli/common/print_utils.h
Labels: new-feature

#8657 More jsonb funcs, no examples in the docs
  ydb/library/yql/parser/pg_catalog/safe_procs.h
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
Labels: improvement

#8661 fixes applied to sessions sysview
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service_impl.h
  ydb/core/kqp/proxy_service/kqp_session_info.cpp
  ydb/core/protos/kqp.proto
  ydb/core/sys_view/sessions/sessions.cpp
Labels: not-for-changelog

#8550 auditlog: add exports/imports
  ydb/core/grpc_services/rpc_export.cpp
  ydb/core/grpc_services/rpc_import.cpp
  ydb/core/protos/export.proto
  ydb/core/protos/import.proto
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log.h
  ydb/core/tx/schemeshard/schemeshard_build_index__create.cpp
  ydb/core/tx/schemeshard/schemeshard_export.cpp
  ydb/core/tx/schemeshard/schemeshard_export__cancel.cpp
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/schemeshard_import__cancel.cpp
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/schemeshard_xxport__helpers.cpp
  ydb/core/tx/schemeshard/schemeshard_xxport__helpers.h
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_helpers/auditlog_helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/auditlog_helpers.h
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/core/tx/schemeshard/ut_helpers/ya.make
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/core/tx/schemeshard/ya.make
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: improvement

#8665 Interactive cli over query service and some minor improvements
  ydb/public/lib/ydb_cli/commands/interactive/interactive_cli.cpp
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.cpp
  ydb/public/lib/ydb_cli/commands/ydb_sql.cpp
  ydb/public/lib/ydb_cli/commands/ydb_sql.h
Labels: enhancement, improvement

#8607 Implement Shared Cache replacement policy hot switch
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/protos/shared_cache.proto
  ydb/core/protos/ya.make
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/tablet_flat/shared_sausagecache.h
  ydb/core/testlib/basics/services.cpp
  ydb/core/util/cache_cache.h
  ydb/core/util/cache_cache_ut.cpp
Labels: not-for-changelog

#8691 Remove YT migration helper
  ydb/library/yql/providers/dq/actors/yt/yt_wrapper.cpp
Labels: not-for-changelog

#8656 Fix wrong links to stderr in html report
  .github/scripts/tests/transform-ya-junit.py
Labels: not-for-changelog

#8679 Remove load_network (it was commented for 2+ years)
  ydb/core/actorlib_impl/load_network.cpp
  ydb/core/actorlib_impl/load_network.h
  ydb/core/actorlib_impl/ya.make
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
Labels: not-for-changelog

#8663 Publish testmo.json
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#8246 add histogram on history sizes
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/monitoring.cpp
  ydb/core/mind/hive/tx__cut_tablet_history.cpp
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__start_tablet.cpp
  ydb/core/mind/hive/tx__update_tablet_groups.cpp
  ydb/core/protos/counters_hive.proto
Labels: not-for-changelog

#8562 Remove DEFINE_SIMPLE_NONLOCAL_EVENT, add TEventSimpleNonLocal
  ydb/core/tablet/bootstrapper.h
  ydb/library/actors/core/event.h
  ydb/library/actors/core/event_simple_non_local.h
  ydb/library/actors/core/events.h
  ydb/library/actors/core/ut/ask_ut.cpp
  ydb/library/yql/providers/dq/actors/events.h
Labels: not-for-changelog

#8693 Fix Terraform instructuion
  ydb/docs/en/core/devops/ansible/_includes/terraform/aws.md
  ydb/docs/en/core/devops/ansible/_includes/terraform/azure.md
  ydb/docs/en/core/devops/ansible/_includes/terraform/yc.md
  ydb/docs/en/presets.yaml
  ydb/docs/ru/core/devops/ansible/_includes/terraform/azure.md
  ydb/docs/ru/core/devops/ansible/_includes/terraform/yc.md
  ydb/docs/ru/presets.yaml
Labels: documentation

#8697 immediate writing with no tx
  .github/config/muted_ya.txt
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/operations/manager.cpp
  ydb/core/tx/columnshard/operations/manager.h
  ydb/core/tx/columnshard/operations/write.cpp
  ydb/core/tx/columnshard/operations/write.h
  ydb/core/tx/data_events/events.h
Labels: new-feature

#5703 hc api doc
  ydb/docs/en/core/reference/ydb-sdk/_assets/hc_cards_hierarchy.png
  ydb/docs/en/core/reference/ydb-sdk/_assets/hc_types_hierarchy.png
  ydb/docs/en/core/reference/ydb-sdk/health-check-api.md
  ydb/docs/ru/core/reference/ydb-sdk/_assets/hc_cards_hierarchy.png
  ydb/docs/ru/core/reference/ydb-sdk/_assets/hc_types_hierarchy.png
  ydb/docs/ru/core/reference/ydb-sdk/health-check-api.md
Labels: documentation, new-feature

#8582 feat: integration spring data jdbc docs
  ydb/docs/en/core/integrations/spring-data-jdbc.md
  ydb/docs/en/core/integrations/toc_i.yaml
  ydb/docs/ru/core/integrations/spring-data-jdbc.md
  ydb/docs/ru/core/integrations/toc_i.yaml
Labels: documentation

#8653 Debug logs for EvWrite/EvRead
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
Labels: not-for-changelog

#8619 optimize cluster handler
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/viewer_cluster.h
  ydb/core/viewer/viewer_feature_flags.h
  ydb/core/viewer/viewer_helper.h
  ydb/core/viewer/viewer_nodes.h
  ydb/core/viewer/viewer_vdiskinfo.h
Labels: performance

#8683 reduce logging rate for stats info
  ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
Labels: improvement

#8682 switch on mkql factory for cs
  ydb/core/tx/columnshard/columnshard_impl.cpp
Labels: new-feature

#8684 use ss tablet id for schemeshard and sender for tx_proxy
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.cpp
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.h
  ydb/core/tx/columnshard/transactions/operators/propose_tx.cpp
  ydb/core/tx/columnshard/transactions/operators/propose_tx.h
  ydb/core/tx/columnshard/transactions/operators/schema.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
Labels: improvement

#8595 Make error for impossible TzDate casts more friendly (again)
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/test.test_datetime-date_tz_impossible_cast--Results_/extracted
  ydb/library/yql/udfs/common/datetime2/datetime_udf.cpp
Labels: area/yql, bugfix

#8699 Reduce huge amount of PDisk's chunks info printed into log
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
Labels: bugfix

#8690 another fix for feature flags
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/storage_groups.h
  ydb/core/viewer/viewer_feature_flags.h
  ydb/core/viewer/viewer_tenantinfo.h
  ydb/core/viewer/viewer_ut.cpp
  ydb/core/viewer/ya.make
Labels: bugfix

#8714 Fix broken txs
  ydb/core/tx/columnshard/columnshard__progress_tx.cpp
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/normalizer/tablet/broken_txs.cpp
  ydb/core/tx/columnshard/normalizer/tablet/broken_txs.h
  ydb/core/tx/columnshard/normalizer/tablet/ya.make
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.h
Labels: improvement

#8713 fix case indexation removed table
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/insert_table/data.h
Labels: bugfix

#8720 Replace image by diagram
  ydb/docs/ru/core/concepts/_assets/async-replication-diagram.drawio
  ydb/docs/ru/core/concepts/_assets/async-replication-diagram.png
  ydb/docs/ru/core/concepts/async-replication.md
Labels: documentation

#8622 streamlookupjoin: fix joining from multi-partition stream
  ydb/library/yql/dq/tasks/dq_connection_builder.h
  ydb/tests/fq/generic/test_join_streaming.py
Labels: bugfix

#8694 Docs: resource broker config
  ydb/docs/ru/core/concepts/_includes/secondary_indexes.md
  ydb/docs/ru/core/deploy/configuration/config.md
  ydb/docs/ru/core/devops/manual/backup-and-recovery.md
Labels: documentation

#8721 [backport/yql-stable-2024-09-03] Make error for impossible TzDate casts more friendly (again)
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/test.test_datetime-date_tz_impossible_cast--Results_/extracted
  ydb/library/yql/udfs/common/datetime2/datetime_udf.cpp
Labels: area/yql

#8729 additional signals for commit timings control
  ydb/core/tx/columnshard/columnshard__progress_tx.cpp
  ydb/core/tx/columnshard/counters/columnshard.cpp
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/counters/tx_progress.h
  ydb/core/tx/columnshard/transactions/tx_controller.h
  ydb/core/tx/tx_proxy/upload_rows_common_impl.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: improvement

#8704 YDBDOCS-740: update query limits
  ydb/docs/en/core/concepts/_includes/limits-ydb.md
  ydb/docs/ru/core/concepts/_includes/limits-ydb.md
Labels: documentation

#8736 Fix false-positive assertion in RecoverLostData mode
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer.cpp
Labels: bugfix

#8707 Add EnableAlterSharding option
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/schemeshard/olap/operations/alter_table.cpp
Labels: new-feature

#8738 fix query multiple rowsets
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/viewer_query.h
Labels: bugfix

#8723 Make it easier to use IEventHandle as an unfiltered event type in tests
  ydb/library/actors/core/event.h
  ydb/library/actors/testlib/test_runtime.h
Labels: not-for-changelog

#8712 Fix use-after-free in CommittingOps tracking
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_pipeline.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/operation.h
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
Labels: bugfix

#8755 validate logical execution before lineage
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/lineage/error_type.cfg
  ydb/library/yql/tests/sql/suites/lineage/error_type.sql
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/test.test_lineage-error_type--Results_/extracted
Labels: area/yql, improvement

#8760 Replay GetTableRange
  ydb/library/yql/ast/ya.make
  ydb/library/yql/ast/yql_expr.cpp
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/core/services/ya.make
  ydb/library/yql/core/services/yql_eval_expr.cpp
  ydb/library/yql/providers/yt/gateway/qplayer/yql_yt_qplayer_gateway.cpp
Labels: area/yql, improvement

#7443 YQ WM resource pools enabled
  ydb/core/protos/feature_flags.proto
Labels: new-feature

#8522 YDBDOCS-743-optimizer: Optimizer documentation
  ydb/docs/ru/core/concepts/_assets/Star-Schema.png
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/concepts/optimizer.md
  ydb/docs/ru/core/concepts/toc_i.yaml
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/pragma/ydb.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/analyze.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/pragma.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/toc_i.yaml
Labels: documentation

#8747 Fix incorrect DC comparison
  ydb/core/mind/hive/hive_impl.cpp
Labels: not-for-changelog

#8768 YQ kqprun added cancel after for script requests
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.h
Labels: improvement

#8716 [docs] changed link name from "docker" to "source code"
  ydb/docs/en/core/downloads/index.md
  ydb/docs/ru/core/downloads/index.md
Labels: documentation

#8741 Change all PerSessionCounters to AdaptiveCounters
  ydb/library/actors/interconnect/interconnect_counters.cpp
Labels: area/actorsystem, not-for-changelog

#8776 Move graph_compare logic into tests_ya/action.yml
  .github/actions/build_and_test_ya/action.yml
  .github/actions/graph_compare/action.yml
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#8777 Fixed unit test ManyColumnShards
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#8782 Mute ydb/core/kqp/ut/olap KqpOlap.ManyColumnShards
  .github/config/muted_ya.txt
Labels: not-for-changelog

#8753 Revert "Fix hash spreading in HashPartitionConsumer (#4364)"
  ydb/library/yql/dq/runtime/dq_output_consumer.cpp
Labels: bugfix

#8445 single node scheduler has been added
  ydb/core/fq/libs/actors/nodes_manager.cpp
  ydb/library/yql/providers/dq/actors/executer_actor.cpp
  ydb/library/yql/providers/dq/api/protos/dqs.proto
  ydb/library/yql/providers/dq/common/yql_dq_settings.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
  ydb/tests/fq/yds/test_3_selects.py
Labels: new-feature

#8785 [oidc proxy] Improve error message for forbidden host and null response
  ydb/mvp/oidc_proxy/oidc_protected_page.h
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
  ydb/mvp/oidc_proxy/openid_connect.cpp
  ydb/mvp/oidc_proxy/openid_connect.h
Labels: improvement

#8602 [CBO] Join Order test improvement
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
Labels: improvement

#8763 Always show table with broken locks
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/provider/yql_kikimr_provider.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/tx/kqp_locks_ut.cpp
Labels: improvement

#8784 Reply UNAVAILABLE in case EvStartKqpTasksRequest is undelivered because of disconnect
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
Labels: bugfix

#8794 Revert "merge the additional yaml config to the main yaml config"
  ydb/public/tools/lib/cmds/__init__.py
  ydb/public/tools/lib/cmds/ut/canondata/result.json
  ydb/public/tools/lib/cmds/ut/canondata/test.test_merge_two_yaml_configs/patched.yaml
  ydb/public/tools/lib/cmds/ut/config.yaml
  ydb/public/tools/lib/cmds/ut/patch.yaml
  ydb/public/tools/lib/cmds/ut/test.py
  ydb/public/tools/lib/cmds/ut/ya.make
Labels: external

#8758 Revert macro (broken arcadia and nbs)
  ydb/library/actors/core/event.h
Labels: not-for-changelog

#8766 Report errors on databases
  ydb/library/actors/http/http_cache.cpp
  ydb/mvp/meta/meta_cp_databases.h
Labels: improvement

#8790 Fix tablets on nodes
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/viewer_nodes.h
  ydb/core/viewer/viewer_request.cpp
Labels: bugfix

#7448 Add YQL syntax highlighting to YDB CLI
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.cpp
  ydb/public/lib/ydb_cli/commands/interactive/ut/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.h
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight_ut.cpp
  ydb/public/lib/ydb_cli/commands/ya.make
Labels: area/yql, area/cli, new-feature, external

#8810 Mute TxUsage.WriteToTopic_Invalid_Session
  .github/config/muted_ya.txt
Labels: not-for-changelog

#8769 fix import build
  ydb/core/tx/columnshard/operations/manager.h
Labels: bugfix

#8818 increase timeout for tests
  ydb/services/keyvalue/ut/ya.make
Labels: not-for-changelog

#8820 YQ kqprun enable column shard by default
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: improvement

#8334 Introduce P_LOG and new TPDiskCtx to make pdisk logging easier
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_async.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_driveestimator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_http.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_metadata.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_logreader.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_logreader.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_req_creator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_sectorrestorator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_sectorrestorator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_state.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_syslogreader.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_syslogreader.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_tools.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_writer.h
Labels: new-feature

#8803 Rename EOutputFormat -> EDataFormat and AddFormats -> AddOutputFormats
  ydb/public/lib/ydb_cli/commands/ydb_benchmark.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_export.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.h
  ydb/public/lib/ydb_cli/commands/ydb_service_monitoring.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_operation.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_operation.h
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.h
  ydb/public/lib/ydb_cli/commands/ydb_service_scripting.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_table.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_sql.cpp
  ydb/public/lib/ydb_cli/commands/ydb_yql.cpp
  ydb/public/lib/ydb_cli/common/format.cpp
  ydb/public/lib/ydb_cli/common/format.h
  ydb/public/lib/ydb_cli/common/formats.h
  ydb/public/lib/ydb_cli/common/parameters.cpp
  ydb/public/lib/ydb_cli/common/print_operation.cpp
  ydb/public/lib/ydb_cli/common/print_operation.h
  ydb/public/lib/ydb_cli/import/import.cpp
  ydb/public/lib/ydb_cli/import/import.h
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/common.h
Labels: area/cli, not-for-changelog

#8748 result_format: data parser & builder
  ydb/core/kqp/provider/yql_kikimr_results.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/interface/codec.h
  ydb/library/yql/parser/pg_wrapper/ya.make
  ydb/library/yql/providers/common/codec/ut/ya.make
  ydb/library/yql/providers/common/codec/ya.make
  ydb/library/yql/providers/common/codec/yql_codec.cpp
  ydb/library/yql/providers/yt/codec/ya.make
  ydb/library/yql/providers/yt/codec/yt_codec_io.cpp
  ydb/library/yql/public/result_format/ut/ya.make
  ydb/library/yql/public/result_format/ut/yql_restricted_yson_ut.cpp
  ydb/library/yql/public/result_format/ut/yql_result_format_data_ut.cpp
  ydb/library/yql/public/result_format/ut/yql_result_format_response_ut.cpp
  ydb/library/yql/public/result_format/ut/yql_result_format_type_ut.cpp
  ydb/library/yql/public/result_format/ya.make
  ydb/library/yql/public/result_format/yql_codec_results.cpp
  ydb/library/yql/public/result_format/yql_codec_results.h
  ydb/library/yql/public/result_format/yql_restricted_yson.cpp
  ydb/library/yql/public/result_format/yql_restricted_yson.h
  ydb/library/yql/public/result_format/yql_result_format_common.h
  ydb/library/yql/public/result_format/yql_result_format_data.cpp
  ydb/library/yql/public/result_format/yql_result_format_data.h
  ydb/library/yql/public/result_format/yql_result_format_impl.h
  ydb/library/yql/public/result_format/yql_result_format_response.cpp
  ydb/library/yql/public/result_format/yql_result_format_response.h
  ydb/library/yql/public/result_format/yql_result_format_type.cpp
  ydb/library/yql/public/result_format/yql_result_format_type.h
  ydb/library/yql/sql/pg_dummy/pg_sql_dummy.cpp
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/yqlrun/yqlrun.cpp
Labels: area/yql, new-feature

#8827 Use exprnode only from main thread
  ydb/library/yql/providers/yt/gateway/qplayer/yql_yt_qplayer_gateway.cpp
Labels: area/yql, bugfix

#8829 Fix PDisk's ColorBorderOccupancy calculation
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_chunk_tracker.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_color_limits.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
Labels: bugfix

#8809 the `TEvTxCalcPredicate` message for the completed transaction
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
Labels: bugfix

#8812 Better spilling errors
  ydb/core/kqp/ut/spilling/kqp_scan_spilling_ut.cpp
  ydb/library/yql/dq/actors/spilling/channel_storage_actor.cpp
  ydb/library/yql/dq/actors/spilling/compute_storage_actor.cpp
  ydb/library/yql/dq/actors/spilling/spilling_file.cpp
  ydb/library/yql/dq/actors/spilling/spilling_file_ut.cpp
Labels: improvement

#8770 Fix monitoring page registration races in tests
  ydb/core/mon/sync_http_mon.cpp
  ydb/core/testlib/actors/test_runtime.cpp
Labels: not-for-changelog

#8761 Do not invalidate request with INTERNAL_ERROR in case of cancelation tx on the follower using depended reads
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
Labels: bugfix

#8779 support solomon reading from subquery
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/tests/sql/solomon/canondata/result.json
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-Subquery-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-Subquery-default.txt_/plan.txt
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-Subquery-default.txt_/results.txt
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/solomon/Subquery.sql
Labels: not-for-changelog

#8840 Always show table name in locks broken error 2
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
Labels: not-for-changelog

#8734 Allow SelfHeal operation while in DEGRADED state
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/protos/config.proto
Labels: improvement

#8850 Mute HugeCluster.AllToAl
  .github/config/muted_ya.txt
Labels: not-for-changelog

#8638 Test report: links to history
  .github/config/mute_rules.md
  .github/scripts/tests/generate-summary.py
  .github/scripts/tests/templates/summary.html
Labels: not-for-changelog

#8834 Fix erroneous finish on TDqInputMergeBlockStreamValue
  ydb/library/yql/dq/runtime/dq_input_producer.cpp
Labels: area/yql, bugfix

#8839 fix grammar in healthcheck messages
  ydb/core/health_check/health_check.cpp
Labels: not-for-changelog

#8852 Mute ydb/tests/functional/hive/test_drain.py.TestHive.test_drain_on_stop
  .github/config/muted_ya.txt
Labels: not-for-changelog

#8842 Add CRC64 to docs
  ydb/docs/en/core/yql/reference/yql-core/udf/list/digest.md
  ydb/docs/ru/core/yql/reference/yql-core/udf/list/digest.md
Labels: not-for-changelog

#6288 Data integrity trails in DataShard
  ydb/core/cms/json_proxy_proto.h
  ydb/core/data_integrity_trails/data_integrity_trails.h
  ydb/core/kqp/ut/data_integrity/kqp_data_integrity_trails_ut.cpp
  ydb/core/tx/datashard/check_data_tx_unit.cpp
  ydb/core/tx/datashard/check_write_unit.cpp
  ydb/core/tx/datashard/complete_data_tx_unit.cpp
  ydb/core/tx/datashard/complete_write_unit.cpp
  ydb/core/tx/datashard/datashard_integrity_trails.h
  ydb/core/tx/datashard/finish_propose_unit.cpp
  ydb/core/tx/datashard/finish_propose_write_unit.cpp
  ydb/core/tx/datashard/store_data_tx_unit.cpp
Labels: experimental-feature

#8780 merge 24-3: add ring queue config
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/protos/config.proto
  ydb/library/actors/core/config.h
  ydb/library/actors/core/executor_pool_base.cpp
  ydb/library/actors/core/executor_pool_base.h
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_pool_io.cpp
  ydb/library/actors/core/executor_pool_io.h
Labels: area/actorsystem

#8832 Validate protos from antlr4
  ydb/library/yql/sql/settings/translation_settings.cpp
  ydb/library/yql/sql/settings/translation_settings.h
  ydb/library/yql/sql/sql.cpp
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/proto_parser/proto_parser.cpp
  ydb/library/yql/sql/v1/proto_parser/proto_parser.h
  ydb/library/yql/sql/v1/sql.cpp
  ydb/library/yql/tests/sql/sql2yql/test_sql2yql.py
  ydb/library/yql/tools/sql2yql/sql2yql.cpp
  ydb/library/yql/tools/yqlrun/yqlrun.cpp
Labels: area/yql, not-for-changelog

#8848 Fix Date32 json serialization for column store
  ydb/core/viewer/viewer_query.h
Labels: new-feature

#8847 Fix resolved timestamp emitted too early for some displaced upserts
  ydb/core/tx/datashard/cdc_stream_heartbeat.cpp
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
Labels: bugfix

#8865 mute rules upd
  .github/config/mute_rules.md
Labels: not-for-changelog

#8863 NodesManager cleanup
  ydb/core/fq/libs/actors/nodes_manager.cpp
Labels: not-for-changelog

#8686 Fix MakeBlocks usage in BlockMapJoinCore computation node
  ydb/library/yql/minikql/comp_nodes/mkql_block_map_join.cpp
  ydb/library/yql/minikql/comp_nodes/ut/mkql_block_map_join_ut.cpp
  ydb/library/yql/minikql/computation/mkql_block_impl.cpp
Labels: area/yql, bugfix

#8879 Update summary.html build type
  .github/scripts/tests/templates/summary.html
Labels: not-for-changelog

#8787 Post graph_compare.sh logs
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#8883 Fix error message about merge conflicts
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#8556 add report
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#8880 Fix crash on ic counters
  ydb/library/actors/interconnect/interconnect_counters.cpp
Labels: area/actorsystem, bugfix

#8874 [yt provider] Add ForceTransform optimizer
  ydb/library/yql/providers/yt/gateway/native/yql_yt_native.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt.h
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_merge.cpp
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
Labels: area/yql, bugfix

#8744 Inference projections support
  ydb/core/external_sources/object_storage.cpp
  ydb/core/kqp/provider/read_attributes_utils.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: improvement

#8676 Bugfixes
  ydb/library/yql/providers/s3/actors/yql_s3_raw_read_actor.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_source_queue.cpp
  ydb/library/yql/providers/s3/events/events.h
  ydb/library/yql/providers/s3/object_listers/yql_s3_list.cpp
  ydb/library/yql/providers/s3/proto/file_queue.proto
Labels: bugfix

#7564 Fix typo
  ydb/public/lib/ydb_cli/common/csv_parser.cpp
Labels: new-feature, external

#8858 Olap TableStore read/write test
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/helpers/local.h
  ydb/core/kqp/ut/olap/helpers/typed_local.cpp
  ydb/core/kqp/ut/olap/helpers/typed_local.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/testlib/cs_helper.cpp
  ydb/core/testlib/cs_helper.h
Labels: not-for-changelog

#8894 Avoid block aggregation in auto mode for YT
  ydb/library/yql/core/yql_aggregate_expander.h
  ydb/library/yql/dq/opt/dq_opt_log.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_logical_optimize.cpp
Labels: area/yql, bugfix

#8899 Fix wrong YQL_ENSURE in PushdownComplexFiltersOverAggregate
  ydb/library/yql/core/common_opt/yql_co_flow2.cpp
Labels: area/yql, bugfix

#8901 Do not try to call IsComplete() on Arguments
  ydb/library/yql/core/common_opt/yql_co_flow2.cpp
Labels: area/yql

#8902 Handle non-ascii in comments
  ydb/library/yql/sql/v1/proto_parser/proto_parser.cpp
Labels: area/yql, improvement

#8903 Better handling of antlr4 errors
  ydb/library/yql/parser/proto_ast/proto_ast.h
Labels: bugfix

#8904 fix cluster tablets grouping
  ydb/core/viewer/viewer_cluster.h
  ydb/core/viewer/viewer_nodes.h
Labels: bugfix

#8822 remove table only for empty insert table
  ydb/core/formats/arrow/modifier/schema.h
  ydb/core/formats/arrow/process_columns.cpp
  ydb/core/formats/arrow/process_columns.h
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup_tables.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/abstract/merger.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/insert_table/data.h
  ydb/core/tx/columnshard/engines/insert_table/insert_table.cpp
  ydb/core/tx/columnshard/engines/insert_table/insert_table.h
  ydb/core/tx/columnshard/engines/insert_table/path_info.h
  ydb/core/tx/columnshard/engines/insert_table/rt_insertion.cpp
  ydb/core/tx/columnshard/engines/insert_table/rt_insertion.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/predicate/range.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/read_metadata.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/read_metadata.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/resolver.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/iterator.h
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/columnshard/engines/scheme/column/info.cpp
  ydb/core/tx/columnshard/engines/scheme/column/info.h
  ydb/core/tx/columnshard/engines/scheme/column_features.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/snapshot_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/snapshot_scheme.h
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/operations/batch_builder/merger.cpp
  ydb/core/tx/columnshard/operations/write_data.cpp
  ydb/core/tx/columnshard/splitter/ut/batch_slice.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/data_events/shard_writer.cpp
  ydb/core/tx/data_events/shard_writer.h
  ydb/core/tx/data_events/shards_splitter.h
  ydb/core/tx/program/program.h
  ydb/core/tx/tx_proxy/global.cpp
  ydb/core/tx/tx_proxy/global.h
  ydb/core/tx/tx_proxy/rpc_long_tx.cpp
  ydb/core/tx/tx_proxy/ya.make
  ydb/library/conclusion/result.h
Labels: bugfix

#8909 Fix write ids usage
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.h
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_common.cpp
  ydb/core/tx/columnshard/columnshard_common.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/columnshard_schema.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/engines/changes/indexation.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.h
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/db_wrapper.h
  ydb/core/tx/columnshard/engines/defs.cpp
  ydb/core/tx/columnshard/engines/defs.h
  ydb/core/tx/columnshard/engines/insert_table/committed.cpp
  ydb/core/tx/columnshard/engines/insert_table/committed.h
  ydb/core/tx/columnshard/engines/insert_table/data.h
  ydb/core/tx/columnshard/engines/insert_table/insert_table.cpp
  ydb/core/tx/columnshard/engines/insert_table/insert_table.h
  ydb/core/tx/columnshard/engines/insert_table/inserted.cpp
  ydb/core/tx/columnshard/engines/insert_table/inserted.h
  ydb/core/tx/columnshard/engines/insert_table/path_info.cpp
  ydb/core/tx/columnshard/engines/insert_table/path_info.h
  ydb/core/tx/columnshard/engines/insert_table/rt_insertion.cpp
  ydb/core/tx/columnshard/engines/insert_table/rt_insertion.h
  ydb/core/tx/columnshard/engines/insert_table/user_data.cpp
  ydb/core/tx/columnshard/engines/insert_table/user_data.h
  ydb/core/tx/columnshard/engines/insert_table/ya.make
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/read_metadata.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/read_metadata.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/ut/ut_insert_table.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.h
  ydb/core/tx/columnshard/engines/ya.make
  ydb/core/tx/columnshard/operations/manager.cpp
  ydb/core/tx/columnshard/operations/manager.h
  ydb/core/tx/columnshard/operations/write.cpp
  ydb/core/tx/columnshard/operations/write.h
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.cpp
  ydb/core/tx/columnshard/transactions/operators/long_tx_write.h
  ydb/core/tx/columnshard/ya.make
Labels: bugfix
