Repository ydb-platform/ydb, pull requests merged in 2024-10, with the labels that each got.

#6565 Add OLAP info to dev section
  ydb/docs/ru/core/_includes/not_allow_for_olap_note_main.md
  ydb/docs/ru/core/_includes/ways_add_data_to_olap.md
  ydb/docs/ru/core/dev/cdc.md
  ydb/docs/ru/core/dev/custom-attributes.md
  ydb/docs/ru/core/dev/example-app/_includes/example-dotnet.md
  ydb/docs/ru/core/dev/example-app/_includes/example-nodejs.md
  ydb/docs/ru/core/dev/example-app/_includes/example-php.md
  ydb/docs/ru/core/dev/example-app/_includes/index.md
  ydb/docs/ru/core/dev/example-app/_includes/steps/02_create_table.md
  ydb/docs/ru/core/dev/example-app/_includes/steps/03_write_queries.md
  ydb/docs/ru/core/dev/example-app/go/index.md
  ydb/docs/ru/core/dev/example-app/java/index.md
  ydb/docs/ru/core/dev/primary-key/row-oriented.md
  ydb/docs/ru/core/dev/query-plans-optimization.md
  ydb/docs/ru/core/dev/secondary-indexes.md
  ydb/docs/ru/core/dev/terraform.md
  ydb/docs/ru/core/dev/yql-tutorial/alter_table.md
  ydb/docs/ru/core/dev/yql-tutorial/basic_aggregation.md
  ydb/docs/ru/core/dev/yql-tutorial/basic_filter_and_sort.md
  ydb/docs/ru/core/dev/yql-tutorial/conditional_values.md
  ydb/docs/ru/core/dev/yql-tutorial/create_demo_tables.md
  ydb/docs/ru/core/dev/yql-tutorial/delete.md
  ydb/docs/ru/core/dev/yql-tutorial/delete_table.md
  ydb/docs/ru/core/dev/yql-tutorial/fill_tables_with_data.md
  ydb/docs/ru/core/dev/yql-tutorial/insert_into.md
  ydb/docs/ru/core/dev/yql-tutorial/join_tables.md
  ydb/docs/ru/core/dev/yql-tutorial/replace_into.md
  ydb/docs/ru/core/dev/yql-tutorial/select_all_columns.md
  ydb/docs/ru/core/dev/yql-tutorial/select_specific_columns.md
  ydb/docs/ru/core/dev/yql-tutorial/update.md
  ydb/docs/ru/core/dev/yql-tutorial/upsert_into.md
Labels: documentation

#6190 Fixed typo in "Build using CMake" section
  BUILD.md
Labels: documentation, new-feature

#9881 Register pathes for insert table
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/insert_table/insert_table.cpp
  ydb/core/tx/columnshard/engines/insert_table/insert_table.h
  ydb/core/tx/columnshard/engines/insert_table/rt_insertion.cpp
  ydb/core/tx/columnshard/engines/insert_table/rt_insertion.h
  ydb/core/tx/columnshard/engines/ut/ut_insert_table.cpp
  ydb/core/tx/columnshard/engines/writer/indexed_blob_constructor.h
Labels: improvement

#9920 Rename IsTxDataReleased -> GetIsReleased
  ydb/core/tx/datashard/datashard_active_transaction.cpp
  ydb/core/tx/datashard/datashard_active_transaction.h
Labels: not-for-changelog

#7975 Description of the parameter AUTO_PARTITIONING_PARTITION_SIZE_MB
  ydb/docs/en/core/concepts/_includes/datamodel/table.md
  ydb/docs/en/core/concepts/datamodel/_includes/table.md
  ydb/docs/ru/core/concepts/datamodel/_includes/table.md
Labels: documentation

#9811 get rid of mkql results
  ydb/core/client/server/msgbus_server_pq_metacache.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/persqueue/cluster_tracker.cpp
  ydb/core/persqueue/writer/partition_chooser_impl__table_helper.h
  ydb/services/deprecated/persqueue_v0/grpc_pq_clusters_updater_actor.cpp
Labels: not-for-changelog

#9624 work
  ydb/core/statistics/aggregator/ut/ut_analyze_columnshard.cpp
  ydb/core/statistics/aggregator/ut/ut_traverse_columnshard.cpp
  ydb/core/statistics/service/http_request.cpp
  ydb/core/statistics/service/http_request.h
  ydb/core/statistics/service/service_impl.cpp
  ydb/core/statistics/service/ut/ut_http_request.cpp
  ydb/core/statistics/service/ut/ya.make
  ydb/core/statistics/ut_common/ut_common.cpp
  ydb/core/statistics/ut_common/ut_common.h
Labels: not-for-changelog

#9758 streamlookup, generic lookup, yt lookup: remove TUVMap usage from events
  ydb/library/yql/dq/actors/compute/dq_compute_actor_async_io.h
  ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
  ydb/library/yql/providers/generic/actors/ut/yql_generic_lookup_actor_ut.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
  ydb/library/yql/providers/yt/actors/ut/yql_yt_lookup_actor_ut.cpp
  ydb/library/yql/providers/yt/actors/yql_yt_lookup_actor.cpp
Labels: not-for-changelog

#9916 http_proxy_config support
  ydb/tools/cfg/base.py
  ydb/tools/cfg/static.py
Labels: new-feature, external

#9914 Parse topic's partitioning once and more efficiently
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/ya.make
  ydb/core/tx/scheme_board/cache.cpp
  ydb/core/tx/scheme_board/ya.make
  ydb/core/tx/scheme_cache/scheme_cache.h
Labels: performance

#9872 fix test_mkql_not_increased
  ydb/tests/fq/mem_alloc/test_alloc_default.py
  ydb/tests/fq/mem_alloc/ya.make
Labels: not-for-changelog

#9081 Add option for unconditional printing of microseconds in Datetime UDF
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/udfs/common/datetime2/datetime_udf.cpp
  ydb/library/yql/udfs/common/datetime2/test/canondata/result.json
  ydb/library/yql/udfs/common/datetime2/test/canondata/test.test_FormatMicroseconds_/results.txt
  ydb/library/yql/udfs/common/datetime2/test/cases/FormatMicroseconds.sql
Labels: area/yql, new-feature

#9927 Change spamming BS_QUEUE log line to INFO priority
  ydb/core/blobstorage/backpressure/queue_backpressure_client.cpp
Labels: not-for-changelog

#9739 Make pragma ForceJobSizeAdjuster public
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_spec.cpp
Labels: area/yql, not-for-changelog

#9932 Fix GetAliveChildren with filter by type
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_index_build.cpp
Labels: bugfix

#9936 [KQP] Fix plan olap filter selectivity estimation
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/ut/join/data/queries/test_join_hint1.sql
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
Labels: improvement

#8172 Traslate YDB concepts
  ydb/docs/en/core/concepts/_includes/index/how_it_works.md
  ydb/docs/en/core/concepts/_includes/index/intro.md
  ydb/docs/en/core/concepts/_includes/index/when_use.md
  ydb/docs/en/core/concepts/_includes/scan_query.md
  ydb/docs/en/core/concepts/_includes/ttl.md
  ydb/docs/en/core/concepts/cdc.md
  ydb/docs/en/core/deploy/manual/deploy-ydb-on-premises.md
Labels: documentation

#9947 Speed up TPDiskTest::SmallDisk10Gb
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
Labels: not-for-changelog

#9921 Improve cluster workload run
  ydb/apps/dstool/lib/dstool_cmd_cluster_workload_run.py
Labels: not-for-changelog

#9865 Configure BufferPool size depending on device type, second attempt
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_logreader.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_logreader.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_actions.cpp
Labels: performance

#9462 Update changelog server.md RU for 24.1
  ydb/docs/ru/core/changelog-server.md
Labels: documentation

#9944 Fix YDB CLI build for windows
  .github/workflows/build_ydb_cli.yml
  build/internal/ya.conf
Labels: area/cli, not-for-changelog

#9942 fix potential GetStatistics hanging during rolling update
  ydb/core/statistics/service/service_impl.cpp
Labels: bugfix

#3289 Add reason for pending action in maintenance public API
  ydb/core/cms/api_adapters.cpp
  ydb/core/cms/cluster_info.h
  ydb/core/cms/cms.cpp
  ydb/core/cms/cms_maintenance_api_ut.cpp
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/erasure_checkers.cpp
  ydb/core/cms/error_info.h
  ydb/core/cms/node_checkers.cpp
  ydb/core/cms/node_checkers.h
  ydb/core/cms/ya.make
  ydb/core/protos/cms.proto
  ydb/core/protos/out/out_cms.cpp
  ydb/public/api/protos/draft/ydb_maintenance.proto
  ydb/public/api/protos/out/out.cpp
Labels: improvement

#9890 use `TTxControl` to commit transactions
  ydb/public/sdk/cpp/client/ydb_table/impl/table_client.h
  ydb/public/sdk/cpp/client/ydb_table/impl/transaction.cpp
  ydb/public/sdk/cpp/client/ydb_table/impl/transaction.h
  ydb/public/sdk/cpp/client/ydb_table/table.cpp
  ydb/public/sdk/cpp/client/ydb_table/table.h
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: new-feature

#9962 dqrun pq simulation: add queue limit
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_file_topic_client.cpp
Labels: not-for-changelog

#9949 Disable row_dispatcher tests during export CMake
  ydb/core/fq/libs/row_dispatcher/ya.make
Labels: bugfix, external

#9923 Stop supporting non-mvcc legacy modes in DataShards
  ydb/core/testlib/tablet_helpers.cpp
  ydb/core/tx/datashard/build_and_wait_dependencies_unit.cpp
  ydb/core/tx/datashard/build_scheme_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/check_data_tx_unit.cpp
  ydb/core/tx/datashard/create_table_unit.cpp
  ydb/core/tx/datashard/create_volatile_snapshot_unit.cpp
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__cancel_tx_proposal.cpp
  ydb/core/tx/datashard/datashard__cleanup_tx.cpp
  ydb/core/tx/datashard/datashard__init.cpp
  ydb/core/tx/datashard/datashard__progress_tx.cpp
  ydb/core/tx/datashard/datashard__propose_tx_base.cpp
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard__write.cpp
  ydb/core/tx/datashard/datashard_dep_tracker.cpp
  ydb/core/tx/datashard/datashard_dep_tracker.h
  ydb/core/tx/datashard/datashard_direct_transaction.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_s3_upload_rows.cpp
  ydb/core/tx/datashard/datashard_snapshots.cpp
  ydb/core/tx/datashard/datashard_snapshots.h
  ydb/core/tx/datashard/datashard_split_dst.cpp
  ydb/core/tx/datashard/datashard_split_src.cpp
  ydb/core/tx/datashard/datashard_switch_mvcc_state.cpp
  ydb/core/tx/datashard/datashard_txs.h
  ydb/core/tx/datashard/datashard_ut_trace.cpp
  ydb/core/tx/datashard/execution_unit.cpp
  ydb/core/tx/datashard/finish_propose_unit.cpp
  ydb/core/tx/datashard/finish_propose_write_unit.cpp
  ydb/core/tx/datashard/follower_edge.cpp
  ydb/core/tx/datashard/make_scan_snapshot_unit.cpp
  ydb/core/tx/datashard/read_table_scan_unit.cpp
  ydb/core/tx/datashard/receive_snapshot_unit.cpp
  ydb/core/tx/datashard/setup_sys_locks.h
  ydb/core/tx/datashard/ya.make
  ydb/core/tx/schemeshard/ut_helpers/test_env.cpp
Labels: not-for-changelog

#7223 YQ: Fix task id on pq sink
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
Labels: not-for-changelog

#9948 Test bloat for every PR
  .github/actions/build_analytics/action.yml
  .github/actions/test_ya/action.yml
  ydb/ci/build_bloat/html/tree_map.html
  ydb/ci/build_bloat/test_bloat.py
  ydb/ci/build_bloat/tree_map.py
Labels: not-for-changelog

#8383 Removed legacy KV API
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/msgbus_server_keyvalue.cpp
  ydb/core/client/server/msgbus_server_local_enumerate_tablets.cpp
  ydb/core/client/server/ya.make
  ydb/core/driver_lib/cli_utils/cli.h
  ydb/core/driver_lib/cli_utils/cli_cmds_admin.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_tablet.cpp
  ydb/core/driver_lib/cli_utils/cli_keyvalue.cpp
  ydb/core/driver_lib/cli_utils/ya.make
  ydb/core/driver_lib/run/main.cpp
  ydb/core/protos/grpc.proto
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/kicli/kikimr.cpp
  ydb/tests/functional/blobstorage/test_tablet_channel_migration.py
  ydb/tests/functional/cms/test_cms_erasure.py
  ydb/tests/functional/cms/test_cms_restart.py
  ydb/tests/functional/cms/test_cms_state_storage.py
  ydb/tests/functional/cms/utils.py
  ydb/tests/functional/hive/hive_matchers.py
  ydb/tests/functional/hive/test_create_tablets.py
  ydb/tests/functional/hive/test_drain.py
  ydb/tests/functional/hive/test_kill_tablets.py
  ydb/tests/library/common/delayed.py
  ydb/tests/library/common/protobuf.py
  ydb/tests/library/common/protobuf_kv.py
  ydb/tests/library/harness/kikimr_client.py
  ydb/tests/library/harness/kikimr_cluster_interface.py
  ydb/tests/library/harness/kikimr_keyvalue_client.py
  ydb/tests/library/harness/kikimr_runner.py
  ydb/tests/library/harness/kikimr_scheme_client.py
  ydb/tests/library/kv/helpers.py
  ydb/tests/library/matchers/response.py
  ydb/tests/library/ya.make
Labels: not-for-changelog

#9980 Remove yds from asan PR checks
  ydb/tests/fq/yds/ya.make
Labels: not-for-changelog

#9955 YQ-3583 Improvements after load tests
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
Labels: not-for-changelog

#9931 Do not use block reader on overridden schemas, columns, tables with inferred schemas
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
Labels: bugfix

#9951 Implement different modes of Arrow memory tracking
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/serializer/native.cpp
  ydb/core/formats/arrow/serializer/native.h
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.h
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/runtime/kqp_arrow_memory_pool.cpp
  ydb/core/kqp/runtime/kqp_arrow_memory_pool.h
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/runtime/kqp_scan_data.h
  ydb/core/kqp/runtime/ya.make
  ydb/core/protos/table_service_config.proto
  ydb/library/formats/arrow/arrow_helpers.cpp
  ydb/library/formats/arrow/arrow_helpers.h
Labels: new-feature

#9986 Test bloat in links
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#9998 Mute ydb/core/statistics/service/ut/ 1 tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#10004 Remove schemeshard/*_reboot tests from asan PR checks
  ydb/core/tx/schemeshard/ut_base_reboots/ya.make
  ydb/core/tx/schemeshard/ut_bsvolume_reboots/ya.make
  ydb/core/tx/schemeshard/ut_cdc_stream_reboots/ya.make
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ya.make
  ydb/core/tx/schemeshard/ut_external_data_source_reboots/ya.make
  ydb/core/tx/schemeshard/ut_external_table_reboots/ya.make
  ydb/core/tx/schemeshard/ut_extsubdomain_reboots/ya.make
  ydb/core/tx/schemeshard/ut_filestore_reboots/ya.make
  ydb/core/tx/schemeshard/ut_index_build_reboots/ya.make
  ydb/core/tx/schemeshard/ut_olap_reboots/ya.make
  ydb/core/tx/schemeshard/ut_reboots/ya.make
  ydb/core/tx/schemeshard/ut_resource_pool_reboots/ya.make
  ydb/core/tx/schemeshard/ut_rtmr_reboots/ya.make
  ydb/core/tx/schemeshard/ut_sequence_reboots/ya.make
  ydb/core/tx/schemeshard/ut_serverless_reboots/ya.make
  ydb/core/tx/schemeshard/ut_subdomain_reboots/ya.make
  ydb/core/tx/schemeshard/ut_user_attributes_reboots/ya.make
Labels: not-for-changelog

#10010 Mute ydb/library/yql/providers/generic/connector/tests/join/ 1 tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#9945 inflight has been fixed for TCreateComputeDatabaseActor in case of Ti…
  ydb/core/fq/libs/control_plane_proxy/control_plane_proxy.cpp
Labels: bugfix

#9974 [CBO] Fix LeftOnly (LeftAntiJoin) algebraic matrix
  ydb/library/yql/core/cbo/cbo_optimizer_new.h
  ydb/library/yql/dq/opt/dq_opt_conflict_rules_collector.cpp
Labels: bugfix

#10011 Fix mime type in build artifacts
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#9993 Better handling of connection loss
  ydb/core/change_exchange/change_sender.cpp
  ydb/core/change_exchange/change_sender.h
  ydb/core/change_exchange/util.cpp
  ydb/core/change_exchange/util.h
  ydb/core/change_exchange/ya.make
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/change_sender_table_base.h
  ydb/core/tx/replication/service/base_table_writer.cpp
Labels: performance

#9997 get rid of mkql results in scripting
  ydb/core/grpc_services/rpc_execute_data_query.cpp
  ydb/core/grpc_services/rpc_execute_yql_script.cpp
  ydb/core/grpc_services/rpc_stream_execute_yql_script.cpp
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/common/kqp.h
  ydb/core/kqp/common/kqp_event_impl.cpp
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/host/kqp_transform.h
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_results.cpp
  ydb/core/kqp/provider/yql_kikimr_results.h
  ydb/core/kqp/session_actor/kqp_response.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/session_actor/kqp_worker_actor.cpp
  ydb/core/kqp/session_actor/kqp_worker_common.cpp
  ydb/core/kqp/ut/yql/kqp_scripting_ut.cpp
  ydb/core/load_test/aggregated_result.cpp
  ydb/core/protos/kqp.proto
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/viewer_query_old.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: not-for-changelog

#10015 Support of replay of credentials
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/core/ut/yql_qplayer_ut.cpp
Labels: area/yql, improvement

#9988 Temporarily fix data race in PDisk
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_metadata.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_request_id.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
Labels: bugfix

#9571 replaced yexception with TCodeLineException in s3_read_actor
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
Labels: improvement

#9983 Increment YDB CLI version to 2.14.0
  ydb/apps/ydb/version.txt
Labels: area/cli, not-for-changelog

#9977 Infer parsing error message improvement
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: improvement

#9982 Stop generating legacy readset format in CopyTable
  ydb/core/tx/datashard/build_scheme_tx_out_rs_unit.cpp
Labels: not-for-changelog

#10024 Revert "Mute ydb/core/statistics/service/ut/ 1 tests"
  .github/config/muted_ya.txt
Labels: not-for-changelog

#10002 Update ydbtech ru downloads page
  ydb/docs/ru/core/downloads/_includes/server/docker.md
  ydb/docs/ru/core/downloads/_includes/server/linux.md
  ydb/docs/ru/core/downloads/_includes/server/source_code.md
Labels: documentation

#9999 Blobs balancer: fix unhadled event in case of chunk read timeout
  ydb/core/blobstorage/vdisk/balance/sender.cpp
Labels: not-for-changelog

#10020 fix unregister group race
  ydb/core/tx/limiter/grouped_memory/service/process.h
Labels: bugfix

#9897 Add dqrun rlimit
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/dqrun/ya.make
Labels: new-feature

#9886 Bestow forward-compatibility with libpq17
  ydb/library/yql/parser/pg_wrapper/cflags.inc
Labels: not-for-changelog, external

#10005 Replace TMemorizableControlWrapper to TControlWrapper
  ydb/core/blobstorage/vdisk/common/blobstorage_cost_tracker.h
  ydb/core/control/immediate_control_board_wrapper.h
Labels: not-for-changelog

#10023 add lost pragma once
  ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h
  ydb/library/yql/dq/actors/spilling/channel_storage_actor.h
Labels: not-for-changelog

#10052 Remove RAM reqs for tests with less 4gb RSS in asan (part 2)
  ydb/core/blobstorage/incrhuge/ut/ya.make
  ydb/core/blobstorage/ut_testshard/ya.make
  ydb/core/client/minikql_result_lib/ut/ya.make
  ydb/core/client/ut/ya.make
  ydb/core/kqp/ut/cost/ya.make
  ydb/core/kqp/ut/pg/ya.make
  ydb/core/tx/datashard/ut_local_kmeans/ya.make
  ydb/core/tx/datashard/ut_reshuffle_kmeans/ya.make
  ydb/core/tx/datashard/ut_sample_k/ya.make
  ydb/core/tx/datashard/ut_volatile/ya.make
  ydb/core/tx/schemeshard/ut_bsvolume_reboots/ya.make
  ydb/core/tx/schemeshard/ut_external_data_source_reboots/ya.make
  ydb/core/tx/schemeshard/ut_external_table_reboots/ya.make
  ydb/core/tx/schemeshard/ut_resource_pool_reboots/ya.make
  ydb/core/tx/schemeshard/ut_rtmr_reboots/ya.make
  ydb/library/ycloud/impl/ut/ya.make
Labels: not-for-changelog

#9991 Fix unimportant deadlock in TBlockDevice and add new UT
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_async.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
Labels: bugfix

#10035 disable set_config proc
  ydb/library/yql/parser/pg_catalog/safe_procs.h
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
Labels: bugfix, area/pg

#10061 Specify explicit cpu requirement (speed up asan)
  ydb/tests/functional/audit/ya.make
  ydb/tests/functional/autoconfig/ya.make
  ydb/tests/functional/backup/s3_path_style/ya.make
  ydb/tests/functional/backup/ya.make
  ydb/tests/functional/blobstorage/ya.make
  ydb/tests/functional/cms/ya.make
  ydb/tests/functional/encryption/ya.make
  ydb/tests/functional/hive/ya.make
  ydb/tests/functional/kqp/kqp_indexes/ya.make
  ydb/tests/functional/kqp/kqp_query_session/ya.make
  ydb/tests/functional/kqp/kqp_query_svc/ya.make
  ydb/tests/functional/limits/ya.make
  ydb/tests/functional/query_cache/ya.make
  ydb/tests/functional/rename/ya.make
  ydb/tests/functional/replication/ya.make
  ydb/tests/functional/restarts/ya.make
  ydb/tests/functional/sdk/cpp/sdk_credprovider/ya.make
  ydb/tests/functional/serverless/ya.make
  ydb/tests/functional/sqs/cloud/ya.make
  ydb/tests/functional/sqs/common/ya.make
  ydb/tests/functional/sqs/large/ya.make
  ydb/tests/functional/sqs/merge_split_common_table/fifo/ya.make
  ydb/tests/functional/sqs/merge_split_common_table/std/ya.make
  ydb/tests/functional/sqs/messaging/ya.make
  ydb/tests/functional/sqs/with_quotas/ya.make
  ydb/tests/functional/tenants/ya.make
Labels: not-for-changelog

#10057 [yt provider] Add YtMaterialize callable
  ydb/library/yql/providers/yt/expr_nodes/yql_yt_expr_nodes.json
  ydb/library/yql/providers/yt/provider/yql_yt_datasink_constraints.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasink_type_ann.cpp
Labels: area/yql, not-for-changelog

#10009 Rework FormatRead and SysLogRead, move their execution to PDisk to avoid race
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_request_id.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
Labels: bugfix

#10030 Renamed files to match the RU section
  ydb/docs/en/core/changelog-server.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/alter-topic.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/create-topic.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/toc_i.yaml
  ydb/docs/redirects.yaml
Labels: documentation

#9956 Fixes for YDB Import 617
  ydb/docs/ru/core/security/encryption/data-in-transit.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/changefeed.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
Labels: documentation

#10026 Remove TTypeInfo from TRawTypeValue
  ydb/core/engine/minikql/flat_local_tx_read_columns.h
  ydb/core/engine/minikql/minikql_engine_host.cpp
  ydb/core/scheme/scheme_tablecell.h
  ydb/core/scheme/scheme_types_defs.cpp
  ydb/core/scheme/scheme_types_defs.h
  ydb/core/scheme_types/scheme_raw_type_value.h
  ydb/core/scheme_types/scheme_types_defs.h
  ydb/core/tablet_flat/flat_cxx_database.h
  ydb/core/tablet_flat/flat_database.cpp
  ydb/core/tablet_flat/flat_executor_db_mon.cpp
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_redo_player.h
  ydb/core/tablet_flat/test/libs/rows/rows.h
  ydb/core/tablet_flat/test/libs/rows/tool.h
  ydb/core/tablet_flat/ut/flat_test_db_helpers.h
  ydb/core/tablet_flat/ut/ut_decimal.cpp
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
  ydb/core/tablet_flat/ut_pg/flat_database_pg_ut.cpp
  ydb/core/tx/datashard/build_distributed_erase_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/cdc_stream_scan.cpp
  ydb/core/tx/datashard/change_collector_async_index.cpp
  ydb/core/tx/datashard/change_collector_async_index.h
  ydb/core/tx/datashard/change_collector_cdc_stream.cpp
  ydb/core/tx/datashard/datashard__object_storage_listing.cpp
  ydb/core/tx/datashard/datashard__read_columns.cpp
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_change_receiving.cpp
  ydb/core/tx/datashard/datashard_common_upload.cpp
  ydb/core/tx/datashard/datashard_direct_erase.cpp
  ydb/core/tx/datashard/datashard_repl_apply.cpp
  ydb/core/tx/datashard/datashard_split_src.cpp
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/execute_distributed_erase_tx_unit.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/incr_restore_helpers.cpp
  ydb/core/tx/datashard/stream_scan_common.cpp
Labels: not-for-changelog

#10074 schemeshard: fix enable_alter_database_create_hive_first mode
  ydb/core/tx/schemeshard/schemeshard__operation_alter_extsubdomain.cpp
  ydb/core/tx/schemeshard/ut_extsubdomain/ut_extsubdomain.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
Labels: bugfix

#10076 add url params to trace attributes
  ydb/core/viewer/json_pipe_req.cpp
Labels: improvement

#10075 fix nodes grouping and uptime calculations
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/viewer_nodes.h
Labels: new-feature

#9715 Implement configurable number of completion threads
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_async.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_driveestimator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/protos/blobstorage_pdisk_config.proto
Labels: performance

#10080 Add Gridnev PB
  ydb/docs/ru/core/public-materials/_includes/conferences/2024/Heisenbug.md
  ydb/docs/ru/core/public-materials/videos.md
Labels: documentation

#9895 Refactor SDK list to table with docs column
  ydb/docs/en/core/reference/ydb-sdk/_includes/index.md
  ydb/docs/ru/core/reference/ydb-sdk/index.md
Labels: documentation

#10084 Avoid local truncation if no full result created
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.cpp
Labels: area/yql, bugfix

#10069 Fix release repl token after poisson pill
  ydb/core/blobstorage/vdisk/balance/balancing_actor.cpp
Labels: not-for-changelog

#10034 Harden huge blob placement checks in VDisk, fix HugeKeeper WAL
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge_ut.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugedefs.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap_ut.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_public.cpp
Labels: not-for-changelog

#8530 Use AssumeConstraints for YtDqProcessWrite
  ydb/library/yql/core/yql_expr_constraint.cpp
  ydb/library/yql/providers/yt/common/yql_configuration.h
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt.h
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_sort.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_write.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
Labels: area/yql, not-for-changelog

#10097 Enable Olap settings
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#10104 [dq] Add Top optimizer
  ydb/library/yql/providers/dq/opt/physical_optimize.cpp
Labels: area/yql, bugfix

#10107 Rework BlockDevice tests
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/library/pdisk_io/buffers.h
  ydb/library/pdisk_io/sector_map.h
Labels: not-for-changelog

#10114 Fixed import of pg extensions
  ydb/library/yql/parser/pg_catalog/catalog.cpp
Labels: area/yql, bugfix

#10118 Fix encryption test
  ydb/tests/functional/encryption/test_encryption.py
Labels: not-for-changelog

#10111 Fix HasValue misuse for LLVM codegen
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_compress.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_top.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_blocks.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_extend.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_switch.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
  ydb/library/yql/providers/yt/comp_nodes/dq/dq_yt_reader_impl.h
  ydb/library/yql/providers/yt/comp_nodes/yql_mkql_input.cpp
Labels: area/yql, bugfix

#10122 Revert "Rework FormatRead and SysLogRead, move their execution to PDisk to avoid race"
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_request_id.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
Labels: not-for-changelog

#10096 fix allocation cleaning race from separated thread after scope cleani…
  ydb/core/tx/limiter/grouped_memory/service/allocation.h
  ydb/core/tx/limiter/grouped_memory/service/group.h
  ydb/core/tx/limiter/grouped_memory/service/process.h
Labels: improvement

#10131 Optimized batch processing
  ydb/core/persqueue/blob.cpp
  ydb/core/persqueue/blob.h
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/ut/internals_ut.cpp
Labels: performance

#10132 Restore legacy kv server
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/msgbus_server_keyvalue.cpp
  ydb/core/client/server/msgbus_server_local_enumerate_tablets.cpp
  ydb/core/client/server/ya.make
  ydb/core/protos/grpc.proto
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/kicli/kikimr.cpp
Labels: not-for-changelog

#10148 [docs] hotfix for insert_into.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/insert_into.md
Labels: documentation

#10095 Fix use-after-free in Datetime2::Format
  ydb/library/yql/udfs/common/datetime2/datetime_udf.cpp
Labels: bugfix

#10065 Added debug logging for table stats
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/ya.make
  ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
Labels: new-feature

#10113 Fix PDisk race in restart
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/util/testactorsys.cpp
Labels: bugfix

#10126 Ported fix for import of extensions
  ydb/library/yql/parser/pg_catalog/catalog.cpp
Labels: area/yql

#9768 YQ-3689 added database id for workload manager
  ydb/core/kqp/common/events/workload_service.h
  ydb/core/kqp/common/kqp_user_request_context.cpp
  ydb/core/kqp/common/kqp_user_request_context.h
  ydb/core/kqp/common/simple/query_id.cpp
  ydb/core/kqp/common/simple/query_id.h
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/executer_actor/ut/kqp_executer_ut.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/checker.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/manager.cpp
  ydb/core/kqp/gateway/kqp_gateway.h
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway_ut.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.h
  ydb/core/kqp/proxy_service/kqp_proxy_databases_cache.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service_impl.h
  ydb/core/kqp/runtime/kqp_compute_scheduler.cpp
  ydb/core/kqp/runtime/kqp_compute_scheduler.h
  ydb/core/kqp/session_actor/kqp_query_state.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/session_actor/kqp_worker_actor.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/kqp/workload_service/actors/actors.h
  ydb/core/kqp/workload_service/actors/pool_handlers_acors.cpp
  ydb/core/kqp/workload_service/actors/scheme_actors.cpp
  ydb/core/kqp/workload_service/common/events.h
  ydb/core/kqp/workload_service/common/helpers.cpp
  ydb/core/kqp/workload_service/common/helpers.h
  ydb/core/kqp/workload_service/kqp_workload_service.cpp
  ydb/core/kqp/workload_service/kqp_workload_service_impl.h
  ydb/core/kqp/workload_service/tables/table_queries.cpp
  ydb/core/kqp/workload_service/tables/table_queries.h
  ydb/core/kqp/workload_service/ut/common/kqp_workload_service_ut_common.cpp
  ydb/core/kqp/workload_service/ut/common/kqp_workload_service_ut_common.h
  ydb/core/kqp/workload_service/ut/kqp_workload_service_tables_ut.cpp
  ydb/core/kqp/workload_service/ut/kqp_workload_service_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/services/metadata/manager/abstract.h
  ydb/tools/query_replay/query_compiler.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
Labels: improvement

#10117 Support of PG extensions in YQL embedded
  ydb/library/yql/public/embedded/no_llvm/ya.make
  ydb/library/yql/public/embedded/ya.make
  ydb/library/yql/public/embedded/yql_embedded.cpp
  ydb/library/yql/public/embedded/yql_embedded.h
Labels: area/yql, new-feature

#10159 [docs] update redirects.yaml
  ydb/docs/redirects.yaml
Labels: documentation

#9370 YQ-3617: fix GROUP BY HOP + AS_TABLE
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/ut/yql_expr_constraint_ut.cpp
  ydb/library/yql/core/ya.make
  ydb/library/yql/core/yql_expr_constraint.cpp
  ydb/library/yql/core/yql_opt_hopping.cpp
  ydb/library/yql/core/yql_opt_hopping.h
  ydb/library/yql/dq/opt/dq_opt_hopping.cpp
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/aggregate/group_by_hop_static.sql
  ydb/library/yql/tests/sql/suites/aggregate/group_by_hop_static_list_key.sql
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: new-feature

#10146 [KQP] Binary symbols in range breaks plan json and make server crash
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/tests/functional/canonical/canondata/result.json
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_pk_predicate_pk_predicate_random_chars.sql-plan_/pk_predicate_pk_predicate_random_chars.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_pk_predicate_pk_predicate_random_chars.sql-result_sets_/pk_predicate_pk_predicate_random_chars.sql.results
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_pk_predicate_pk_predicate_random_chars_ranges.sql-plan_/pk_predicate_pk_predicate_random_chars_ranges.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_pk_predicate_pk_predicate_random_chars_ranges.sql-result_sets_/pk_predicate_pk_predicate_random_chars_ranges.sql.results
  ydb/tests/functional/canonical/sql/Input5.data
  ydb/tests/functional/canonical/sql/input5.table
  ydb/tests/functional/canonical/sql/pk_predicate/pk_predicate_random_chars.sql
  ydb/tests/functional/canonical/sql/pk_predicate/pk_predicate_random_chars_ranges.sql
Labels: bugfix

#10046 Use DWARF symbols in backtrace only on Linux
  ydb/core/mon_alloc/tcmalloc.cpp
  ydb/core/mon_alloc/ya.make
Labels: not-for-changelog

#10102 AssumeUnique/AssumeDistinct optimizers
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.h
  ydb/library/yql/providers/dq/opt/physical_optimize.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_sort.cpp
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/test.test_insert-unique_distinct_hints--Analyze_/extracted
  ydb/library/yql/tests/sql/dq_file/part14/canondata/test.test_insert-unique_distinct_hints--Results_/extracted
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/test.test_select-unique_distinct_hints--Analyze_/extracted
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/insert/unique_distinct_hints.cfg
  ydb/library/yql/tests/sql/suites/insert/unique_distinct_hints.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/test.test_insert-unique_distinct_hints--Results_/extracted
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
Labels: area/yql, improvement

#9460 Remote address in audit log
  ydb/core/client/server/msgbus_blobstorage_config.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/msgbus_server_cms.cpp
  ydb/core/client/server/msgbus_server_console.cpp
  ydb/core/client/server/msgbus_server_drain_node.cpp
  ydb/core/client/server/msgbus_server_fill_node.cpp
  ydb/core/client/server/msgbus_server_local_minikql.cpp
  ydb/core/client/server/msgbus_server_local_scheme_tx.cpp
  ydb/core/client/server/msgbus_server_node_registration.cpp
  ydb/core/client/server/msgbus_server_proxy.cpp
  ydb/core/client/server/msgbus_server_request.cpp
  ydb/core/client/server/msgbus_server_scheme_initroot.cpp
  ydb/core/client/server/msgbus_server_scheme_request.cpp
  ydb/core/grpc_services/query/rpc_execute_script.cpp
  ydb/core/grpc_services/query/rpc_kqp_tx.cpp
  ydb/core/grpc_services/rpc_begin_transaction.cpp
  ydb/core/grpc_services/rpc_commit_transaction.cpp
  ydb/core/grpc_services/rpc_dynamic_config.cpp
  ydb/core/grpc_services/rpc_execute_scheme_query.cpp
  ydb/core/grpc_services/rpc_explain_data_query.cpp
  ydb/core/grpc_services/rpc_explain_yql_script.cpp
  ydb/core/grpc_services/rpc_prepare_data_query.cpp
  ydb/core/grpc_services/rpc_rollback_transaction.cpp
  ydb/core/kqp/common/compilation/events.h
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/common/kqp_event_impl.cpp
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.h
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/run_script_actor/kqp_run_script_actor.cpp
  ydb/core/kqp/session_actor/kqp_query_state.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/protos/console_config.proto
  ydb/core/security/secure_request.h
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/viewer_query_old.h
Labels: bugfix

#10190 [KQP] fix plan range scan bug with empty string in bounds
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/tests/functional/canonical/canondata/result.json
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_pk_predicate_pk_predicate_comparison_empty_string.sql-plan_/pk_predicate_pk_predicate_comparison_empty_string.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_pk_predicate_pk_predicate_comparison_empty_string.sql-result_sets_/pk_predicate_pk_predicate_comparison_empty_string.sql.results
  ydb/tests/functional/canonical/sql/pk_predicate/pk_predicate_comparison_empty_string.sql
Labels: bugfix

#10141 [KQP] turn off CBO IsLookupJoinApplicable for not row column.
  ydb/core/kqp/opt/logical/kqp_opt_cbo.cpp
Labels: performance

#10193 Fix uninitialized value in PDisk UT
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
Labels: not-for-changelog

#10161 YDB FQ: set up filtering options for YQL Generic Read Actor and Lookup Actor
  ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp
  ydb/library/yql/providers/generic/actors/ut/yql_generic_lookup_actor_ut.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_read_actor.cpp
  ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/connector_client_mock.h
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ms_sql_server/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/mysql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/oracle/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/join/docker-compose.yml
  ydb/tests/fq/generic/analytics/docker-compose.yml
  ydb/tests/fq/generic/streaming/docker-compose.yml
Labels: new-feature

#10168 Allow zero decimal scale
  ydb/core/kqp/ut/query/kqp_params_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/scheme_types/scheme_decimal_type.cpp
  ydb/core/scheme_types/scheme_decimal_type.h
  ydb/services/ydb/ydb_table_ut.cpp
  ydb/services/ydb/ydb_ut.cpp
Labels: not-for-changelog

#10181 -DDEBUGINFO_LINES_ONLY only for CI checks
  .github/actions/test_ya/action.yml
  .github/workflows/build_analytics.yml
  .github/workflows/postcommit_asan.yml
  .github/workflows/postcommit_relwithdebinfo.yml
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#10209 Fixed build with new pqlib
  ydb/library/yql/parser/pg_wrapper/cflags.inc
Labels: area/yql, not-for-changelog

#10211 Simplify TSubOperation
  ydb/core/tx/schemeshard/schemeshard__operation_part.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_part.h
Labels: not-for-changelog

#10219 Fix typing mistake in Datetime::Format
  ydb/library/yql/udfs/common/datetime2/datetime_udf.cpp
Labels: bugfix

#10216 Add prewarm workflow
  .github/workflows/prewarm-debug.yaml
Labels: not-for-changelog

#10199 Support of replay of isolated views with inner udfs
  ydb/library/yql/core/qplayer/udf_resolver/yql_qplayer_udf_resolver.cpp
  ydb/library/yql/providers/common/provider/yql_provider.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_load_table_meta.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_provider.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_provider.h
  ydb/library/yql/providers/yt/provider/yql_yt_table_desc.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_table_desc.h
Labels: area/yql, improvement

#10215 Add op context to some TSubOperation calls
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.h
  ydb/core/tx/schemeshard/schemeshard__operation_part.h
Labels: not-for-changelog

#10227 Fix build
  ydb/library/yql/dq/actors/common/ut/ya.make
Labels: not-for-changelog

#10195 Returning upsert test
  ydb/core/kqp/ut/opt/kqp_returning_ut.cpp
Labels: bugfix

#10217 Add debug info to TPathChecker
  ydb/core/config/init/init.h
  ydb/core/tx/schemeshard/schemeshard_path.cpp
  ydb/core/tx/schemeshard/schemeshard_path.h
  ydb/core/util/source_location.cpp
  ydb/core/util/source_location.h
  ydb/core/util/ya.make
Labels: not-for-changelog

#9989 stylistic edits
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-dump.md
Labels: documentation

#10201 [docs] add missing code block in cast_examples.md
  ydb/docs/en/core/yql/reference/yql-core/_includes/cast_examples.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/expressions/cast.md
Labels: documentation

#10232 Update github.com/ydb-platform/fq-connector-go to 0.5.11-rc.2
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ms_sql_server/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/mysql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/oracle/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/join/docker-compose.yml
  ydb/tests/fq/generic/analytics/docker-compose.yml
  ydb/tests/fq/generic/streaming/docker-compose.yml
Labels: not-for-changelog

#10058 Remove unused table versions along with schema versions in TSchemaVer…
  ydb/core/tx/columnshard/normalizer/schema_version/version.cpp
  ydb/core/tx/columnshard/ut_rw/ut_normalizer.cpp
Labels: new-feature

#10204 YQ-3722 add simdjson parser into RD
  ydb/core/fq/libs/row_dispatcher/json_filter.cpp
  ydb/core/fq/libs/row_dispatcher/json_filter.h
  ydb/core/fq/libs/row_dispatcher/json_parser.cpp
  ydb/core/fq/libs/row_dispatcher/json_parser.h
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/json_parser_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/ya.make
  ydb/core/fq/libs/row_dispatcher/ya.make
Labels: performance

#10241 Remove EvWrite from followers
  ydb/core/tx/datashard/datashard_impl.h
Labels: bugfix

#10224 [KQP] Make TKqpColumnStatisticsRequester async
  ydb/core/kqp/opt/kqp_column_statistics_requester.cpp
  ydb/core/kqp/opt/kqp_column_statistics_requester.h
Labels: improvement

#10240 disable validation for useless columns
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.h
Labels: bugfix

#10220 Speed up blobstorage build
  ydb/core/blobstorage/base/blobstorage_syncstate.h
  ydb/core/blobstorage/base/ptr.h
  ydb/core/blobstorage/base/utility.h
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_nodemon.h
  ydb/core/blobstorage/dsproxy/dsproxy_timestats.h
  ydb/core/blobstorage/dsproxy/root_cause.h
  ydb/core/blobstorage/dsproxy/ut_fat/dsproxy_ut.cpp
  ydb/core/blobstorage/groupinfo/blobstorage_groupinfo.h
  ydb/core/blobstorage/incrhuge/ut/incrhuge_basic_ut.cpp
  ydb/core/blobstorage/nodewarden/defs.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actorsystem_creator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_defs.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_mon.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_space_color.h
  ydb/core/blobstorage/ut_vdisk/lib/prepare.cpp
  ydb/core/blobstorage/ut_vdisk/lib/test_brokendevice.cpp
  ydb/core/blobstorage/ut_vdisk/lib/test_huge.cpp
  ydb/core/blobstorage/vdisk/common/blobstorage_cost_tracker.cpp
  ydb/core/blobstorage/vdisk/common/blobstorage_cost_tracker.h
  ydb/core/blobstorage/vdisk/common/blobstorage_dblogcutter.cpp
  ydb/core/blobstorage/vdisk/common/blobstorage_dblogcutter.h
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/common/vdisk_context.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_context.h
  ydb/core/blobstorage/vdisk/common/vdisk_costmodel.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_costmodel.h
  ydb/core/blobstorage/vdisk/common/vdisk_handle_class.h
  ydb/core/blobstorage/vdisk/common/vdisk_histograms.h
  ydb/core/blobstorage/vdisk/common/vdisk_mongroups.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_mongroups.h
  ydb/core/blobstorage/vdisk/common/vdisk_outofspace.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_pdiskctx.h
  ydb/core/blobstorage/vdisk/common/vdisk_recoverylogwriter.cpp
  ydb/core/blobstorage/vdisk/common/ya.make
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_block.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_logoblob.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_heap_it_ut.cpp
  ydb/core/blobstorage/vdisk/hulldb/fresh/fresh_segment_impl.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hulllog.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hulllog.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_readbatch.h
  ydb/core/blobstorage/vdisk/hullop/hullcompdelete/blobstorage_hullcompdelete.cpp
  ydb/core/blobstorage/vdisk/hullop/hullcompdelete/blobstorage_hullcompdelete.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_defs.h
  ydb/core/blobstorage/vdisk/query/query_readactor.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_oos_tracker.cpp
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer_committer.cpp
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer_data.cpp
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer_data.h
  ydb/core/blobstorage/vdisk/syncer/syncer_job_task.cpp
  ydb/core/blobstorage/vdisk/syncer/syncer_job_task.h
  ydb/core/blobstorage/vdisk/synclog/blobstorage_synclogdata.h
  ydb/core/blobstorage/vdisk/synclog/blobstorage_synclogwriteparts.h
  ydb/core/memory_controller/memory_controller.cpp
  ydb/core/node_whiteboard/node_whiteboard.h
Labels: not-for-changelog

#10239 more detailed trace in viewer/tenantinfo
  ydb/core/viewer/viewer_tenantinfo.h
Labels: improvement

#10047 Wait until db is populated in connector/fq tests
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/init/01_basic.sh
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/test.py
  ydb/library/yql/providers/generic/connector/tests/utils/scenario/ya.make
  ydb/library/yql/providers/generic/connector/tests/utils/scenario/ydb.py
  ydb/tests/fq/generic/analytics/conftest.py
  ydb/tests/fq/generic/analytics/test_join.py
  ydb/tests/fq/generic/analytics/test_ydb.py
  ydb/tests/fq/generic/analytics/ya.make
  ydb/tests/fq/generic/analytics/ydb/01_basic.sh
  ydb/tests/fq/generic/streaming/conftest.py
  ydb/tests/fq/generic/streaming/test_join.py
  ydb/tests/fq/generic/streaming/ya.make
  ydb/tests/fq/generic/streaming/ydb/01_basic.sh
Labels: not-for-changelog

#10249 minor fixes for storage groups
  ydb/core/viewer/storage_groups.h
Labels: improvement

#10210 Remove arm architecture form YDB CLI installation script
  ydb/apps/ydb/install/install.sh
Labels: area/cli, not-for-changelog

#10253 Test a few small completion threads count
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
Labels: not-for-changelog

#10229 Delay making EquiJoin inputs unordered until CROSS JOIN is rewritten to inner
  ydb/library/yql/core/common_opt/yql_co_last.cpp
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/join/do_not_suppres_equijoin_input_sorts.cfg
  ydb/library/yql/tests/sql/suites/join/do_not_suppres_equijoin_input_sorts.sql
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: area/yql, improvement

#10256 YQ-3736 Shared reading: fix unsupported predicates
  ydb/core/fq/libs/row_dispatcher/coordinator.cpp
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#10147 Added a section about the JDBC driver
  ydb/docs/en/core/reference/languages-and-apis/index.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/_includes/jdbc-url-examples.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/authentication.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/building.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/index.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/maven.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/properties.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/quickstart.md
  ydb/docs/en/core/reference/languages-and-apis/jdbc-driver/toc_p.yaml
  ydb/docs/en/core/reference/languages-and-apis/toc_p.yaml
  ydb/docs/en/core/reference/toc_p.yaml
  ydb/docs/ru/core/reference/languages-and-apis/index.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/_includes/jdbc-url-examples.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/authentication.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/building.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/index.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/maven.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/properties.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/quickstart.md
  ydb/docs/ru/core/reference/languages-and-apis/jdbc-driver/toc_p.yaml
  ydb/docs/ru/core/reference/languages-and-apis/toc_p.yaml
  ydb/docs/ru/core/reference/toc_p.yaml
Labels: documentation

#10242 YDB FQ: actualize predicate pushdown docs
  ydb/docs/en/core/concepts/federated_query/_includes/predicate_pushdown.md
  ydb/docs/en/core/concepts/federated_query/clickhouse.md
  ydb/docs/en/core/concepts/federated_query/greenplum.md
  ydb/docs/en/core/concepts/federated_query/ms_sql_server.md
  ydb/docs/en/core/concepts/federated_query/mysql.md
  ydb/docs/en/core/concepts/federated_query/postgresql.md
  ydb/docs/en/core/concepts/federated_query/ydb.md
  ydb/docs/ru/core/concepts/federated_query/_includes/predicate_pushdown.md
  ydb/docs/ru/core/concepts/federated_query/clickhouse.md
  ydb/docs/ru/core/concepts/federated_query/greenplum.md
  ydb/docs/ru/core/concepts/federated_query/ms_sql_server.md
  ydb/docs/ru/core/concepts/federated_query/mysql.md
  ydb/docs/ru/core/concepts/federated_query/postgresql.md
  ydb/docs/ru/core/concepts/federated_query/ydb.md
Labels: documentation

#10237 [docs] describe version() builtin
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/version.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/basic.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/version.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/basic.md
Labels: documentation

#10029 Fix kafka produce codec
  ydb/core/kafka_proxy/actors/kafka_produce_actor.cpp
Labels: not-for-changelog

#10269 switch to json2proto to allow decode of Any
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
Labels: new-feature

#10261 Fixed crash in pg_show_all_settings
  ydb/library/yql/parser/pg_catalog/safe_procs.h
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/misc/guc_funcs.c
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
Labels: bugfix, area/pg

#10279 [doc] Fix feature name
  ydb/docs/en/core/yql/reference/yql-core/syntax/select.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/select/index.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/select/toc_i.yaml
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/table_path_name_recindex.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/select.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/select/from.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/select/index.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/select/toc_i.yaml
Labels: documentation, area/yql

#10188 [ticket parser] Fix add to refresh queue when receive retryable error
  ydb/core/security/ticket_parser_impl.h
Labels: bugfix

#10287 Unmute tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#10066 Replace conanfile.txt by conanfile.py
  conanfile.py
  conanfile.txt
Labels: improvement, external

#10067 Exporting CMake with skip platforms with errors
  generate_cmake
Labels: experimental-feature, external

#10292 Option `partitions-per-tablet`
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
Labels: improvement

#10271 Yq 3560 Add row dispatcher to dqrun
  ydb/core/fq/libs/control_plane_storage/ya.make
  ydb/core/fq/libs/init/init.cpp
  ydb/library/yql/providers/dq/local_gateway/yql_dq_gateway_local.cpp
  ydb/library/yql/providers/dq/local_gateway/yql_dq_gateway_local.h
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/dqrun/examples/fq.conf
  ydb/library/yql/tools/dqrun/examples/gateways.conf
  ydb/library/yql/tools/dqrun/ya.make
Labels: not-for-changelog

#10259 Update doc about WriteNanAsString option of Yson::SerializeJson
  ydb/docs/en/core/yql/reference/yql-core/udf/list/yson.md
  ydb/docs/ru/core/yql/reference/yql-core/udf/list/yson.md
Labels: documentation, area/yql

#10274 fix groups allocation cleaning
  ydb/core/tx/limiter/grouped_memory/service/ids.cpp
  ydb/core/tx/limiter/grouped_memory/service/ids.h
  ydb/core/tx/limiter/grouped_memory/service/process.h
Labels: bugfix

#10262 New UT to check that all requests are answered on PDisk restart
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
Labels: not-for-changelog

#10255 ci: save job steps, partially pr event fields in webhook receiver server
  ydb/ci/gh-webhook-job/app.py
  ydb/ci/gh-webhook-job/schema.sql
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/variables.tf
Labels: not-for-changelog

#10288 Lowered MapJoin threshold to avoid excessive broadcasts
  ydb/core/kqp/opt/logical/kqp_opt_cbo.cpp
  ydb/core/kqp/ut/join/data/join_order/tpcds64_1000s.json
  ydb/core/kqp/ut/join/data/join_order/tpcds64_1000s_column_store.json
  ydb/core/kqp/ut/join/data/join_order/tpch2_1000s.json
  ydb/core/kqp/ut/join/data/join_order/tpch2_1000s_column_store.json
Labels: performance

#10101 meta deadline exceeded
  ydb/mvp/core/core_ydb.cpp
  ydb/mvp/core/core_ydb.h
  ydb/mvp/core/mvp_tokens.h
  ydb/mvp/oidc_proxy/openid_connect.h
Labels: improvement
