Repository ydb-platform/ydb, pull requests merged in 2024-11, with the labels that each got.

#11161 column chunks v1 schema
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/common/blob.h
  ydb/core/tx/columnshard/data_sharing/destination/events/transfer.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/db_wrapper.h
  ydb/core/tx/columnshard/engines/portions/column_record.cpp
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/portions/common.cpp
  ydb/core/tx/columnshard/engines/portions/common.h
  ydb/core/tx/columnshard/engines/portions/constructor.cpp
  ydb/core/tx/columnshard/engines/portions/constructor.h
  ydb/core/tx/columnshard/engines/portions/constructor_meta.cpp
  ydb/core/tx/columnshard/engines/portions/constructor_meta.h
  ydb/core/tx/columnshard/engines/portions/data_accessor.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.h
  ydb/core/tx/columnshard/engines/portions/meta.cpp
  ydb/core/tx/columnshard/engines/portions/meta.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.cpp
  ydb/core/tx/columnshard/engines/protos/portion_info.proto
  ydb/core/tx/columnshard/engines/ut/ut_insert_table.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/portion/normalizer.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_v1_chunks.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_v1_chunks.h
  ydb/core/tx/columnshard/normalizer/portion/ya.make
Labels: improvement

#11180 fix v1 chunks processing
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
Labels: bugfix

#11085 introduce snapshot_ro isolation level
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/protos/kqp.proto
Labels: improvement

#11023 Support PG types in schemeshard
  ydb/core/tx/schemeshard/schemeshard__table_stats_histogram.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
  ydb/core/tx/schemeshard/ut_split_merge/ut_split_merge.cpp
  ydb/core/tx/schemeshard/ut_split_merge/ya.make
Labels: improvement

#11145 fix erronious retry timeout behaviour in fq-proxy
  ydb/core/fq/libs/compute/ydb/events/events.h
  ydb/core/fq/libs/compute/ydb/executer_actor.cpp
  ydb/core/fq/libs/compute/ydb/ydb_connector_actor.cpp
Labels: bugfix

#10837 YQ-3713 Shared reading: IS DISTINCT FROM predicates
  ydb/library/yql/providers/common/pushdown/collection.cpp
  ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#11171 Fix backup collection working dir interaction
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/schemeshard/schemeshard__backup_collection_common.cpp
  ydb/core/tx/schemeshard/schemeshard__backup_collection_common.h
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_backup_collection.cpp
Labels: not-for-changelog

#10930 Leader could be empty at the very beginning in partitions stats
  ydb/core/sys_view/partition_stats/partition_stats.cpp
Labels: bugfix

#11183 Add feature flag to enable drive serial numbers discovery
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#11189 EnableFollowerStats = true
  ydb/core/protos/feature_flags.proto
Labels: new-feature

#11190 Add simplified mirror-3dc support in CMS
  ydb/core/cms/cms.cpp
  ydb/core/cms/cms_maintenance_api_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/cms/cms_ut_common.h
  ydb/core/cms/erasure_checkers.cpp
  ydb/core/cms/erasure_checkers.h
  ydb/core/protos/counters_cms.proto
Labels: improvement

#10522 Fix multiput's multiple counting buffer size
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
Labels: area/blobstorage, bugfix

#10997 Stop wide combiner state from growing unlimited
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
Labels: improvement

#11140 YQ-3713 Shared reading: do not check compare arguments types
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#11191 rework grpc monitoring
  ydb/core/fq/libs/compute/ydb/control_plane/compute_database_control_plane_service.cpp
  ydb/core/fq/libs/compute/ydb/control_plane/ya.make
  ydb/core/fq/libs/config/protos/compute.proto
  ydb/library/grpc/actor_client/grpc_service_client.h
  ydb/library/grpc/actor_client/grpc_service_settings.h
Labels: not-for-changelog

#11203 Fix PhysicalOptimizer-BypassMerge with key ranges
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_merge.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/key_filter/no_bypass_merge.cfg
  ydb/library/yql/tests/sql/suites/key_filter/no_bypass_merge.sql
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
Labels: area/yql, bugfix

#11210 Backport #11203
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_merge.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/key_filter/no_bypass_merge.cfg
  ydb/library/yql/tests/sql/suites/key_filter/no_bypass_merge.sql
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
Labels: area/yql

#11207 [yt provider] Check table content weight for local execution
  ydb/library/yql/providers/yt/common/yql_configuration.h
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_transform.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_fuse.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasink_exec.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasource_exec.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasource_type_ann.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_helpers.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_horizontal_join.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_mkql_compiler.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_op_settings.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_op_settings.h
  ydb/library/yql/providers/yt/provider/yql_yt_optimize.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_optimize.h
  ydb/library/yql/providers/yt/provider/yql_yt_physical_finalizing.cpp
Labels: area/yql, improvement

#11214 Use AddAfterFatalCallback to flush yt log
  ydb/library/yql/providers/yt/lib/log/ya.make
  ydb/library/yql/providers/yt/lib/log/yt_logger.cpp
Labels: area/yql, not-for-changelog

#11219 Replay YT anonymous table name
  ydb/library/yql/providers/yt/provider/yql_yt_intent_determination.cpp
Labels: improvement

#11218 Drop old epoch reorder impl
  ydb/library/yql/providers/yt/common/yql_yt_settings.cpp
  ydb/library/yql/providers/yt/common/yql_yt_settings.h
  ydb/library/yql/providers/yt/lib/graph_reorder/ya.make
  ydb/library/yql/providers/yt/lib/graph_reorder/yql_graph_reorder_old.cpp
  ydb/library/yql/providers/yt/lib/graph_reorder/yql_graph_reorder_old.h
  ydb/library/yql/providers/yt/provider/ut/yql_yt_epoch_ut.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_epoch.cpp
Labels: area/yql, not-for-changelog

#11232 Fixed broken links in the documentation in Import 622
  ydb/docs/ru/core/concepts/_includes/index/how_it_works.md
  ydb/docs/ru/core/reference/configuration/tls.md
Labels: documentation

#11248 Add table id to DataShard integrity trails
  ydb/core/tx/datashard/datashard_integrity_trails.h
Labels: improvement

#10913 EvWrite: Immediate & Prepare
  ydb/core/kqp/common/buffer/buffer.h
  ydb/core/kqp/common/buffer/events.cpp
  ydb/core/kqp/common/buffer/events.h
  ydb/core/kqp/common/buffer/ya.make
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/common/kqp_tx_manager.h
  ydb/core/kqp/common/simple/kqp_event_ids.h
  ydb/core/kqp/common/ya.make
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/host/kqp_type_ann.cpp
  ydb/core/kqp/opt/kqp_opt_build_txs.cpp
  ydb/core/kqp/opt/kqp_opt_effects.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_actor.h
  ydb/core/kqp/runtime/kqp_write_actor_settings.h
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/kqp/runtime/ya.make
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.h
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/kqp/ut/tx/kqp_sink_tx_ut.cpp
  ydb/core/protos/kqp.proto
Labels: not-for-changelog

#11238 Use node info from labels in configs dispatcher instead of tenant pool
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/cms/console/console_configs_subscriber.cpp
  ydb/core/cms/console/console_configs_subscriber.h
  ydb/core/cms/console/log_settings_configurator_ut.cpp
Labels: not-for-changelog

#11164 Try remaking Builders for every output
  ydb/library/yql/dq/runtime/dq_output_consumer.cpp
Labels: not-for-changelog

#11257 Fix shard ranges sort
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
Labels: bugfix

#11268 fix crash in storage/groups
  ydb/core/viewer/storage_groups.h
Labels: bugfix

#11244 Fix sqs json api folder service token
  ydb/core/http_proxy/http_req.cpp
  ydb/core/http_proxy/ut/datastreams_fixture.h
  ydb/core/ymq/actor/auth_factory.h
  ydb/core/ymq/actor/auth_multi_factory.cpp
Labels: not-for-changelog

#11284 Fix RACE not handled correctly in bootstrapper
  ydb/core/tablet/bootstrapper.cpp
Labels: bugfix

#11277 [KQP] fix column statistics requester non exist column bug
  ydb/core/kqp/opt/kqp_column_statistics_requester.cpp
Labels: bugfix

#11201 Support batch/scan mode for TEvRead
  ydb/core/tablet_flat/flat_scan_actor.h
  ydb/core/tablet_flat/flat_scan_feed.h
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard.h
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/read_iterator.h
  ydb/library/services/services.proto
Labels: not-for-changelog

#9959 Transfer scheme history to new partitions
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/protos/counters_columnshard.proto
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/data_sharing/common/session/common.cpp
  ydb/core/tx/columnshard/data_sharing/common/session/common.h
  ydb/core/tx/columnshard/data_sharing/destination/events/transfer.h
  ydb/core/tx/columnshard/data_sharing/destination/session/destination.cpp
  ydb/core/tx/columnshard/data_sharing/destination/session/destination.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_data_from_source.cpp
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_data_from_source.h
  ydb/core/tx/columnshard/data_sharing/manager/sessions.cpp
  ydb/core/tx/columnshard/data_sharing/manager/sessions.h
  ydb/core/tx/columnshard/data_sharing/protos/events.proto
  ydb/core/tx/columnshard/data_sharing/protos/sessions.proto
  ydb/core/tx/columnshard/data_sharing/protos/transfer.proto
  ydb/core/tx/columnshard/data_sharing/protos/ya.make
  ydb/core/tx/columnshard/data_sharing/source/session/cursor.cpp
  ydb/core/tx/columnshard/data_sharing/source/session/cursor.h
  ydb/core/tx/columnshard/data_sharing/source/session/source.cpp
  ydb/core/tx/columnshard/data_sharing/source/session/source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_data_ack_to_source.cpp
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_source_cursor.cpp
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_source_cursor.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/ya.make
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/scheme/schema_version.cpp
  ydb/core/tx/columnshard/engines/scheme/schema_version.h
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.h
  ydb/core/tx/columnshard/engines/scheme/ya.make
Labels: new-feature

#10773 Update information about LoadActor management via CLI, YDBDOCS-877
  ydb/docs/en/core/contributor/load-actors-overview.md
  ydb/docs/ru/core/contributor/load-actors-overview.md
Labels: documentation

#11233 #9227 Support ANSI SQL syntax highlighting
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/lexer.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/lexer.md
  ydb/public/lib/ydb_cli/commands/interactive/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.cpp
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.h
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight_ut.cpp
Labels: bugfix, external

#11234 #9227 Add YQL highlighting tests
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight_ut.cpp
Labels: improvement, external

#11056 Add ports info to Ansible initial dep article
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
Labels: documentation

#11213 Fix typos in BUILD.md and update "Install dependencies" section
  BUILD.md
Labels: external

#10966 [docs] improve topology.md based on feedback from #7690
  ydb/docs/en/core/concepts/topology.md
  ydb/docs/en/core/contributor/distributed-storage.md
  ydb/docs/ru/core/concepts/topology.md
  ydb/docs/ru/core/contributor/distributed-storage.md
Labels: documentation

#11301 Set providers/common/pushdown owner to fq
  .github/CODEOWNERS
Labels: not-for-changelog

#11132 YQ-3713 Shared reading: SqlIn predicate
  ydb/library/yql/providers/common/pushdown/collection.cpp
  ydb/library/yql/providers/common/pushdown/settings.h
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/pq/expr_nodes/yql_pq_expr_nodes.json
  ydb/library/yql/providers/pq/provider/yql_pq_datasource_type_ann.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#11175 YQ-3809 Shared reading: fix logging
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#11280 ensure reads are sequential
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
Labels: bugfix

#11311 Fix last/next in harness
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#11297 Switch off the ColumnStatistics feature flag for tenant tests
  ydb/core/cms/console/feature_flags_configurator_ut.cpp
  ydb/core/testlib/tenant_runtime.cpp
Labels: not-for-changelog

#11205 YQ-3811 Shared reading: check the same consumer in all clients
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
Labels: not-for-changelog

#11310 Report IC session state to Node Whiteboard
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/protos/node_whiteboard.proto
  ydb/core/tablet/node_whiteboard.cpp
  ydb/library/actors/interconnect/interconnect_common.h
  ydb/library/actors/interconnect/interconnect_tcp_session.cpp
  ydb/library/actors/interconnect/interconnect_tcp_session.h
Labels: not-for-changelog

#11316 Harness: fix start/stop
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#11229 Harness refactor 4 (explicit ssh_user param)
  ydb/tests/library/harness/daemon.py
  ydb/tests/library/harness/kikimr_cluster.py
  ydb/tests/library/harness/kikimr_runner.py
  ydb/tests/library/harness/param_constants.py
  ydb/tests/library/harness/ydbd_slice.py
  ydb/tests/stability/ydb/test_stability.py
  ydb/tests/tools/nemesis/driver/__main__.py
Labels: not-for-changelog

#11292 YQ-3822 Don't use connect() in retry_queue
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/library/yql/dq/actors/common/retry_queue.cpp
  ydb/library/yql/dq/actors/common/retry_queue.h
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#11304 Metrics for buffer actor
  ydb/core/kqp/common/buffer/buffer.h
  ydb/core/kqp/counters/kqp_counters.cpp
  ydb/core/kqp/counters/kqp_counters.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/library/wilson_ids/wilson.h
Labels: not-for-changelog

#11324 Harness refactor 5 (explicit binary path)
  ydb/tests/library/harness/kikimr_cluster.py
  ydb/tests/library/harness/kikimr_runner.py
  ydb/tests/library/harness/param_constants.py
  ydb/tests/library/harness/ydbd_slice.py
  ydb/tests/stability/ydb/test_stability.py
  ydb/tests/tools/nemesis/driver/__main__.py
Labels: not-for-changelog

#11254 Fix kqp test on spilling in selfjoin
  ydb/core/kqp/ut/spilling/kqp_scan_spilling_ut.cpp
Labels: not-for-changelog

#11328 Harness refactor 6 (remove yatest.common.get_param from harness)
  ydb/tests/library/harness/kikimr_cluster.py
  ydb/tests/library/harness/param_constants.py
  ydb/tests/stability/ydb/test_stability.py
Labels: not-for-changelog

#11332 Refactor harness 7 (less param_constants)
  ydb/tests/library/harness/kikimr_runner.py
  ydb/tests/library/harness/param_constants.py
  ydb/tests/stability/ydb/test_stability.py
Labels: not-for-changelog

#11336 Fix param_constants.ssh_user
  ydb/tests/library/wardens/factories.py
  ydb/tests/library/wardens/logs.py
  ydb/tests/stability/ydb/test_stability.py
  ydb/tests/tools/nemesis/driver/__main__.py
  ydb/tests/tools/nemesis/library/catalog.py
Labels: not-for-changelog

#10967 Use ReadRows for loading COUNT_MIN_SKETCH statistics
  ydb/core/grpc_services/rpc_read_rows.cpp
  ydb/core/statistics/database/database.cpp
  ydb/core/statistics/database/database.h
  ydb/core/statistics/database/ut/ut_database.cpp
  ydb/core/statistics/database/ya.make
  ydb/core/statistics/events.h
  ydb/core/statistics/service/http_request.cpp
  ydb/core/statistics/service/http_request.h
  ydb/core/statistics/service/service_impl.cpp
  ydb/core/statistics/service/ut/ut_aggregation/ut_aggregate_statistics.cpp
  ydb/core/statistics/service/ut/ut_aggregation/ya.make
  ydb/core/statistics/service/ut/ut_column_statistics.cpp
  ydb/core/statistics/service/ut/ut_http_request.cpp
  ydb/core/statistics/service/ut/ya.make
  ydb/core/statistics/ut_common/ut_common.cpp
  ydb/core/statistics/ut_common/ut_common.h
Labels: not-for-changelog

#11340 YDBDOCS-909: fix a table in ru topology.md
  ydb/docs/ru/core/concepts/topology.md
Labels: documentation

#11331 YQ RD support strings parsing in Json columns
  ydb/core/fq/libs/row_dispatcher/json_parser.cpp
  ydb/core/fq/libs/row_dispatcher/ut/json_parser_ut.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: improvement

#11322 rd reconnect has been supported
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#11271 updated retry policy in fq proxy
  ydb/core/fq/libs/actors/pending_fetcher.cpp
  ydb/core/fq/libs/compute/common/run_actor_params.cpp
  ydb/core/fq/libs/compute/common/run_actor_params.h
  ydb/core/fq/libs/compute/ydb/executer_actor.cpp
  ydb/core/fq/libs/control_plane_storage/internal/task_get.cpp
  ydb/core/fq/libs/control_plane_storage/internal/task_ping.cpp
  ydb/core/fq/libs/protos/fq_private.proto
Labels: bugfix

#11337 YQ-3820 Shared reading: remove Y_ENSURE / add log message
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#11363 Disable control_plane_storage ut under asan in PR
  ydb/tests/fq/control_plane_storage/ya.make
Labels: not-for-changelog

#9825 Huge defrag smooth linear threshold
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/ut_blobstorage/defrag.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/common/vdisk_mongroups.h
  ydb/core/blobstorage/vdisk/defrag/defrag_actor.cpp
  ydb/core/blobstorage/vdisk/defrag/defrag_actor.h
  ydb/core/blobstorage/vdisk/defrag/defrag_actor_ut.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#11366 remove unused stream profile event
  ydb/core/grpc_services/rpc_stream_execute_scan_query.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/tx/datashard/datashard_ut_kqp.cpp
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/viewer_query_old.h
Labels: not-for-changelog

#11361 Fix db param and show error message
  ydb/core/load_test/kqp.cpp
Labels: not-for-changelog

#10033 Enabled column statistics by default
  ydb/core/protos/feature_flags.proto
Labels: new-feature

#11312 Copy TS3Uploader to shared module
  ydb/core/backup/common/backup_restore_traits.cpp
  ydb/core/backup/common/backup_restore_traits.h
  ydb/core/backup/s3/export_s3_uploader.cpp
  ydb/core/backup/s3/extstorage_usage_config.cpp
  ydb/core/backup/s3/extstorage_usage_config.h
Labels: not-for-changelog

#11367 oidc add cookie logs
  ydb/mvp/oidc_proxy/oidc_protected_page_nebius.cpp
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
  ydb/mvp/oidc_proxy/oidc_session_create_nebius.cpp
  ydb/mvp/oidc_proxy/openid_connect.cpp
Labels: improvement

#11344 add network diagnostics columns to viewer/nodes handler
  ydb/core/protos/node_whiteboard.proto
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/viewer_nodes.h
  ydb/core/viewer/viewer_request.cpp
Labels: new-feature

#11384 fix timeout in tenantinfo handler
  ydb/core/viewer/viewer_tenantinfo.h
Labels: bugfix

#11374 Write changes using WriteTxId in consistent mode
  ydb/core/base/row_version.cpp
  ydb/core/base/row_version.h
  ydb/core/change_exchange/change_record.h
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/service/base_table_writer.cpp
  ydb/core/tx/replication/service/base_table_writer.h
  ydb/core/tx/replication/service/json_change_record.cpp
  ydb/core/tx/replication/service/json_change_record.h
  ydb/core/tx/replication/service/service.cpp
  ydb/core/tx/replication/service/service.h
  ydb/core/tx/replication/service/table_writer.cpp
  ydb/core/tx/replication/service/table_writer.h
  ydb/core/tx/replication/service/table_writer_ut.cpp
  ydb/core/tx/replication/service/worker.cpp
  ydb/core/tx/replication/ut_helpers/test_env.h
Labels: not-for-changelog

#11394 YQ RD optimized purecalc memory usage
  ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.h
  ydb/core/fq/libs/row_dispatcher/json_filter.cpp
  ydb/core/fq/libs/row_dispatcher/json_filter.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.h
  ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
Labels: improvement

#11391 Fix --metadata-fields name in docs
  ydb/docs/en/core/reference/ydb-cli/topic-read.md
  ydb/docs/ru/core/reference/ydb-cli/topic-read.md
Labels: bugfix

#11329 Force oldest locks into shard locks due to range limits
  ydb/core/client/locks_ut.cpp
  ydb/core/tx/locks/locks.cpp
  ydb/core/tx/locks/locks.h
Labels: improvement

#11387 Timestamp topic options: parse in different formats, describe which timestamp is in option
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
Labels: improvement

#10626 fix waiting in test
  ydb/core/mind/hive/hive_ut.cpp
Labels: not-for-changelog

#10969 optimize initializiton of allocation units
  ydb/core/mind/hive/hive_events.h
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/leader_tablet_info.cpp
  ydb/core/mind/hive/leader_tablet_info.h
  ydb/core/mind/hive/storage_group_info.h
  ydb/core/mind/hive/storage_pool_info.cpp
  ydb/core/mind/hive/tx__generate_data_ut.cpp
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/ya.make
Labels: performance

#11397 YQ-3832 RD supported COALESCE and IF pushdown
  ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
  ydb/library/yql/providers/generic/provider/ut/pushdown/pushdown_ut.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: improvement

#11407 Fix read session correct close ut
  ydb/public/sdk/cpp/client/ydb_topic/ut/basic_usage_ut.cpp
Labels: not-for-changelog

#11393 Try to lsof, when fail to lock file
  ydb/tools/stress_tool/device_test_tool_aio_test.h
Labels: new-feature

#11401 realign mvp core library with arcadia
  ydb/mvp/core/core_ydb.cpp
  ydb/mvp/core/core_ydb.h
  ydb/mvp/core/core_ydb_impl.h
  ydb/mvp/core/core_ydbc.h
Labels: improvement

#11378 YQ-3824 Shared reading: fix `is not distinct from` with optional field
  ydb/library/yql/providers/common/pushdown/collection.cpp
  ydb/library/yql/providers/common/pushdown/settings.h
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#11403 ticket-parser: Add error message for log to TError struct of ticket parser
  ydb/core/base/ticket_parser.h
  ydb/core/security/secure_request.h
  ydb/core/security/ticket_parser_impl.h
Labels: improvement

#11410 Incorrect label name
  ydb/services/persqueue_v1/actors/write_session_actor.cpp
Labels: bugfix

#11404 ldap: Return special error messages for write to log from ldap auth provider
  ydb/core/security/ldap_auth_provider/ldap_auth_provider.cpp
  ydb/core/security/ldap_auth_provider/ldap_auth_provider_ut.cpp
  ydb/services/ydb/ydb_ldap_login_ut.cpp
Labels: improvement

#11422 Throw exception instead of calling exit(1) in TBasicServicesInitializer
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
Labels: bugfix

#11429 Remove obsolete map from backpressure queue client
  ydb/core/blobstorage/backpressure/defs.h
  ydb/core/blobstorage/backpressure/queue.cpp
  ydb/core/blobstorage/backpressure/queue.h
Labels: not-for-changelog

#11420 Move balancer to batch pool
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
Labels: not-for-changelog

#11434 verify tasksSize == actorIds.size() has been changed to internal error
  ydb/core/fq/libs/checkpointing/checkpoint_coordinator.cpp
Labels: not-for-changelog

#11417 Fix `TMultiConstraintNode(): requirement Items_.size() failed` error
  ydb/library/yql/providers/yt/provider/yql_yt_datasink_constraints.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasource_constraints.cpp
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/suites/produce/reduce_multi_in-empty.cfg
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
Labels: area/yql, bugfix

#11435 [yt provider] Fix column group calculation for YtCopy
  ydb/library/yql/providers/yt/provider/yql_yt_physical_finalizing.cpp
Labels: area/yql, bugfix

#11443 mon page has been added to row dispatcher
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/ya.make
Labels: improvement

#11415 ReconnectPeriod cleanup
  ydb/core/fq/libs/config/protos/common.proto
  ydb/core/fq/libs/init/init.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.h
Labels: not-for-changelog

#11291 do not use basic statistics if it is not fully gathered in schemeshard
  ydb/core/protos/statistics.proto
  ydb/core/statistics/aggregator/tx_schemeshard_stats.cpp
  ydb/core/statistics/service/ut/ut_basic_statistics.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: bugfix

#11470 more information about columns in autocomplete handler
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/viewer_autocomplete.h
Labels: improvement

#11411 Remove destination session after partitioning finish
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/tx/columnshard/transactions/operators/sharing.cpp
  ydb/core/tx/columnshard/transactions/operators/sharing.h
Labels: new-feature

#9287 Sanitized token field for audit log
  ydb/core/audit/audit_log_impl.cpp
  ydb/core/cms/console/console__replace_yaml_config.cpp
  ydb/core/cms/console/console_audit.cpp
  ydb/core/cms/console/console_audit.h
  ydb/core/cms/console/console_configs_manager.cpp
  ydb/core/grpc_services/audit_dml_operations.cpp
  ydb/core/grpc_services/audit_dml_operations.h
  ydb/core/grpc_services/audit_log.cpp
  ydb/core/grpc_services/audit_log.h
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/grpc_services/rpc_export.cpp
  ydb/core/grpc_services/rpc_import.cpp
  ydb/core/protos/export.proto
  ydb/core/protos/import.proto
  ydb/core/security/login_page.cpp
  ydb/core/security/secure_request.h
  ydb/core/security/ticket_parser.cpp
  ydb/core/security/ticket_parser_impl.h
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log.h
  ydb/library/aclib/aclib.h
  ydb/library/aclib/protos/aclib.proto
  ydb/library/security/ut/util_ut.cpp
  ydb/library/security/util.cpp
  ydb/library/security/util.h
Labels: new-feature

#11441 Fix: remove kqp config settings from audit/metering lib's resources
  ydb/core/audit/ya.make
  ydb/core/metering/ya.make
Labels: bugfix

#11428 Evwrite optimizations
  ydb/core/kqp/common/buffer/buffer.h
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
Labels: improvement

#11439 YQ-3846 RD support OR split during pushdown
  ydb/library/yql/providers/common/pushdown/physical_opt.cpp
  ydb/library/yql/providers/common/pushdown/predicate_node.cpp
  ydb/library/yql/providers/common/pushdown/predicate_node.h
  ydb/library/yql/providers/common/pushdown/settings.h
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: improvement

#11286 [TKqpExecuter] if got poisoned - die silently
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
Labels: improvement

#11483 Reset pipeline in datashard init
  ydb/core/tx/datashard/datashard__init.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_pipeline.h
Labels: bugfix

#11495 YQ-3844 Change dq/actors/common owner to fq
  .github/CODEOWNERS
Labels: not-for-changelog

#11479 YQ-3844 Add internal states to log
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/library/yql/dq/actors/common/retry_queue.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
Labels: not-for-changelog

#11467 YQ-3837 Add Heartbeat messages
  ydb/core/fq/libs/row_dispatcher/events/data_plane.h
  ydb/core/fq/libs/row_dispatcher/protos/events.proto
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/library/yql/dq/actors/common/retry_queue.cpp
  ydb/library/yql/dq/actors/common/retry_queue.h
  ydb/library/yql/dq/actors/common/ut/retry_events_queue_ut.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
Labels: not-for-changelog

#11426 Improved Q9 by moving BuildFlatmapStage to a later stage and adding a Flatmap pushdown
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
  ydb/core/kqp/ut/join/data/queries/tpcds9.sql
  ydb/core/kqp/ut/join/data/queries/tpcds9_small.sql
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.h
Labels: performance

#11349 ensure nodes manually set as Up do not revert to Down
  ydb/core/mind/hive/monitoring.cpp
Labels: bugfix

#11497 Fix parameter substitution in Package pragma
  ydb/library/yql/ast/yql_expr.cpp
  ydb/library/yql/core/url_lister/interface/url_lister.h
  ydb/library/yql/core/url_lister/interface/url_lister_manager.h
  ydb/library/yql/core/url_lister/interface/ya.make
  ydb/library/yql/core/url_lister/url_lister_manager.cpp
  ydb/library/yql/core/url_lister/ya.make
  ydb/library/yql/providers/yt/lib/yt_url_lister/ya.make
  ydb/library/yql/providers/yt/lib/yt_url_lister/yt_url_lister.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/library/p_package_cluster.json
  ydb/library/yql/tests/sql/suites/library/package.cfg
  ydb/library/yql/tests/sql/suites/library/package.sql
Labels: external

#11469 remove duplicated log messages
  ydb/library/yql/dq/actors/compute/dq_compute_memory_quota.h
Labels: not-for-changelog

#11493 Break persistent locks on scheme tx
  ydb/core/tx/datashard/alter_table_unit.cpp
  ydb/core/tx/datashard/create_cdc_stream_unit.cpp
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/datashard/drop_cdc_stream_unit.cpp
  ydb/core/tx/datashard/drop_index_notice_unit.cpp
  ydb/core/tx/datashard/initiate_build_index_unit.cpp
Labels: bugfix

#10973 Implement intermixed inplace and huge blobs and add test for this case
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/ut_blobstorage/huge.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/defs.h
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/blobstorage/ut_blobstorage/ut_huge/ya.make
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/blobstorage/ut_vdisk2/huge.cpp
  ydb/core/blobstorage/vdisk/balance/handoff_map.h
  ydb/core/blobstorage/vdisk/common/disk_part.h
  ydb/core/blobstorage/vdisk/common/vdisk_config.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/common/vdisk_events.h
  ydb/core/blobstorage/vdisk/common/vdisk_hugeblobctx.h
  ydb/core/blobstorage/vdisk/defrag/defrag_search.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugedefs.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugedefs_ut.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.h
  ydb/core/blobstorage/vdisk/huge/ut/ya.make
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_blob.h
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_blob_ut.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_hulldefs.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_hulldefs.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_barrier.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_block.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_ut.h
  ydb/core/blobstorage/vdisk/hulldb/compstrat/hulldb_compstrat_defs.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hulldatamerger.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hullrecmerger.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hullwritesst.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hullwritesst_ut.cpp
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_idx.cpp
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_idx.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hull.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hull.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullactor.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullactor.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcommit.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompact.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompactdeferredqueue.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompactdeferredqueue_ut.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompactworker.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_readbatch.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_readbatch_ut.cpp
  ydb/core/blobstorage/vdisk/hullop/hullcompdelete/blobstorage_hullcompdelete.cpp
  ydb/core/blobstorage/vdisk/hullop/hullcompdelete/blobstorage_hullcompdelete.h
  ydb/core/blobstorage/vdisk/ingress/blobstorage_ingress_matrix.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_logreplay.cpp
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_public.cpp
  ydb/core/blobstorage/vdisk/protos/events.proto
  ydb/core/blobstorage/vdisk/query/query_readbatch.cpp
  ydb/core/blobstorage/vdisk/query/query_readbatch.h
  ydb/core/blobstorage/vdisk/repl/blobstorage_hullreplwritesst.h
  ydb/core/blobstorage/vdisk/repl/blobstorage_hullreplwritesst_ut.cpp
  ydb/core/blobstorage/vdisk/scrub/restore_corrupted_blob_actor.cpp
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_capturevdisklayout.h
  ydb/core/protos/blobstorage_vdisk_internal.proto
Labels: new-feature

#11474 EvWrite: add mvcc snapshot
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/protos/kqp.proto
Labels: bugfix

#11382 remove result channel proxies
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/grpc_services/rpc_stream_execute_scan_query.cpp
  ydb/core/grpc_services/rpc_stream_execute_yql_script.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_result_channel.cpp
  ydb/core/kqp/executer_actor/kqp_result_channel.h
  ydb/core/kqp/executer_actor/ya.make
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/run_script_actor/kqp_run_script_actor.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/scan/kqp_scan_ut.cpp
  ydb/core/kqp/ut/scan/kqp_split_ut.cpp
  ydb/core/kqp/workload_service/ut/common/kqp_workload_service_ut_common.cpp
  ydb/core/local_pgwire/pgwire_kqp_proxy.cpp
  ydb/core/tx/datashard/datashard_ut_kqp_scan.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/viewer_query_old.h
  ydb/tests/tools/kqprun/src/actors.cpp
Labels: not-for-changelog

#11445 [SchemeShard] Add required path creation
  ydb/core/tx/schemeshard/generated/codegen/main.cpp
  ydb/core/tx/schemeshard/generated/codegen/ya.make
  ydb/core/tx/schemeshard/generated/dispatch_op.h.in
  ydb/core/tx/schemeshard/generated/traits.h
  ydb/core/tx/schemeshard/generated/ya.make
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.h
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/ya.make
Labels: not-for-changelog

#11501 fix node_id filter in viewer/nodes handler
  ydb/core/viewer/viewer_nodes.h
Labels: bugfix

#11517 Break persistent locks on scheme tx
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/tx/datashard/alter_table_unit.cpp
  ydb/core/tx/datashard/create_cdc_stream_unit.cpp
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/datashard/drop_cdc_stream_unit.cpp
  ydb/core/tx/datashard/drop_index_notice_unit.cpp
  ydb/core/tx/datashard/initiate_build_index_unit.cpp
Labels: bugfix

#11147 Request DataShard compaction if scheme has been changeed
  ydb/core/protos/table_stats.proto
  ydb/core/tablet_flat/flat_comp.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_table.cpp
  ydb/core/tablet_flat/tablet_flat_executor.h
  ydb/core/tablet_flat/ut/flat_comp_ut_common.h
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__compaction.cpp
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_user_table.h
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator_ext_blobs.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/schemeshard/operation_queue_timer.h
  ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_path_describer.cpp
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_stats/ut_stats.cpp
  ydb/services/ydb/ydb_ut.cpp
Labels: not-for-changelog

#11507 Fix busy-wait in async compute actor
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
Labels: bugfix

#11509 dont scan unappropriate portions in tiering
  ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.cpp
  ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.h
  ydb/core/tx/columnshard/engines/storage/actualizer/tiering/tiering.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/test_helper/controllers.h
Labels: performance

#11446 Support PG literals in KQP
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_build_stage.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.cpp
  ydb/core/kqp/provider/yql_kikimr_provider_impl.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/opt/kqp_extract_predicate_unpack_ut.cpp
  ydb/core/kqp/ut/opt/kqp_sqlin_ut.cpp
  ydb/core/kqp/ut/yql/kqp_yql_ut.cpp
Labels: improvement

#11510 YQ-3844 Shared reading: add restart session sensor
  ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#11516 Add missing precharges in datashard init tx
  ydb/core/tablet_flat/flat_database.cpp
  ydb/core/tablet_flat/flat_database.h
  ydb/core/tx/datashard/datashard__init.cpp
Labels: not-for-changelog

#11535 Remove YQL_PACKAGED
  ydb/library/yql/tools/mrjob/ya.make
  ydb/library/yql/tools/yqlrun/ya.make
  ydb/library/yql/udfs/common/datetime/ya.make
Labels: area/yql, not-for-changelog

#11530 Fix counters not decremented on bs_queue destruction
  ydb/core/blobstorage/backpressure/queue.cpp
Labels: bugfix

#11289 fix error on start internal scanner
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/data_reader/actor.cpp
  ydb/core/tx/columnshard/data_reader/actor.h
  ydb/core/tx/columnshard/operations/batch_builder/builder.h
  ydb/core/tx/columnshard/operations/common/context.h
  ydb/core/tx/columnshard/operations/write.cpp
Labels: bugfix

#11543 YQ-3848 RD support mod pushdown
  ydb/library/yql/providers/common/pushdown/collection.cpp
  ydb/library/yql/providers/common/pushdown/settings.h
  ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: improvement

#11487 YQ-3841 RD add column types validation
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
Labels: bugfix

#11542 Fix test
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#11558 YDB FQ: tests for `JsonDocument` support
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ms_sql_server/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/mysql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/oracle/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/init/01_basic.sh
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/select_positive.py
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/test.py
  ydb/library/yql/providers/generic/connector/tests/join/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/utils/types/ydb.py
  ydb/tests/fq/generic/analytics/docker-compose.yml
  ydb/tests/fq/generic/streaming/docker-compose.yml
Labels: not-for-changelog

#11563 Add YQL_BASE_TEST_DIR
  build/internal/conf/internal.conf
Labels: not-for-changelog

#11559 native memory control
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.h
  ydb/core/tx/limiter/grouped_memory/service/allocation.h
  ydb/core/tx/limiter/grouped_memory/service/counters.h
  ydb/core/tx/limiter/grouped_memory/usage/abstract.h
  ydb/core/tx/limiter/grouped_memory/usage/config.cpp
  ydb/core/tx/limiter/grouped_memory/usage/config.h
  ydb/core/tx/limiter/grouped_memory/usage/service.h
Labels: improvement

#11553 Don't recreate snapshots in transaction
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
Labels: bugfix

#11529 YQ-3844 Shared reading: add restart session sensor / to stable
  ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#11466 Audit log json envelope
  ydb/core/audit/audit_log_impl.cpp
  ydb/core/log_backend/json_envelope.cpp
  ydb/core/log_backend/json_envelope.h
  ydb/core/log_backend/json_envelope_ut.cpp
  ydb/core/log_backend/log_backend.cpp
  ydb/core/log_backend/ut/ya.make
  ydb/core/log_backend/ya.make
  ydb/core/protos/config.proto
Labels: new-feature

#11212 Add issued at leeway for verifying static credentials token
  ydb/library/login/login.cpp
Labels: bugfix

#11442 YQ RD enable LLVM in purecalc filters
  ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.h
  ydb/core/fq/libs/row_dispatcher/common.cpp
  ydb/core/fq/libs/row_dispatcher/common.h
  ydb/core/fq/libs/row_dispatcher/json_filter.cpp
  ydb/core/fq/libs/row_dispatcher/json_filter.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.h
  ydb/core/fq/libs/row_dispatcher/ut/json_filter_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ya.make
  ydb/library/yql/providers/pq/proto/dq_io.proto
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
Labels: performance

#11548 Fix SinkSend argument order
  ydb/library/yql/dq/actors/task_runner/task_runner_actor_local.cpp
Labels: bugfix

#11579 Improve schemeshard codegen
  ydb/core/tx/schemeshard/generated/codegen/main.cpp
  ydb/core/tx/schemeshard/generated/dispatch_op.h.in
  ydb/core/tx/schemeshard/generated/ya.make
  ydb/core/tx/schemeshard/schemeshard__dispatch_op.h
  ydb/core/tx/schemeshard/schemeshard__op_traits.h
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
Labels: not-for-changelog

#11576 YQ WM fixed race with actor context
  ydb/core/kqp/workload_service/kqp_workload_service.cpp
  ydb/core/kqp/workload_service/kqp_workload_service_impl.h
Labels: bugfix

#11575 [yt provider] Fix `unordered_map::at: key not found` error
  ydb/library/yql/providers/yt/provider/yql_yt_physical_finalizing.cpp
Labels: area/yql, bugfix

#11569 Fix reads from many shards
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: bugfix

#11313 Add fetch and replace public api
  ydb/core/driver_lib/run/run.cpp
  ydb/core/driver_lib/run/ya.make
  ydb/core/grpc_services/rpc_bsconfig.cpp
  ydb/core/grpc_services/rpc_bsconfig_base.h
  ydb/core/grpc_services/service_bsconfig.h
  ydb/core/grpc_services/ya.make
  ydb/core/jaeger_tracing/request_discriminator.h
  ydb/library/grpc/server/grpc_method_setup.h
  ydb/library/services/services.proto
  ydb/library/yaml_config/protos/blobstorage_config.proto
  ydb/library/yaml_config/protos/config.proto
  ydb/library/yaml_config/protos/ya.make
  ydb/library/yaml_config/ut/ya.make
  ydb/library/yaml_config/yaml_config_parser.cpp
  ydb/library/yaml_config/yaml_config_parser.h
  ydb/library/yaml_config/yaml_config_proto2yaml_ut.cpp
  ydb/public/api/grpc/ya.make
  ydb/public/api/grpc/ydb_bsconfig_v1.proto
  ydb/public/api/protos/ya.make
  ydb/public/api/protos/ydb_bsconfig.proto
  ydb/services/bsconfig/bsconfig_ut.cpp
  ydb/services/bsconfig/grpc_service.cpp
  ydb/services/bsconfig/grpc_service.h
  ydb/services/bsconfig/ut/ya.make
  ydb/services/bsconfig/ya.make
  ydb/services/keyvalue/grpc_service.cpp
  ydb/services/keyvalue/grpc_service_ut.cpp
  ydb/services/rate_limiter/grpc_service.cpp
  ydb/services/ya.make
Labels: new-feature

#11585 scope mapping has been supported for streaming
  ydb/core/fq/libs/control_plane_config/control_plane_config.cpp
  ydb/core/fq/libs/control_plane_config/events/events.h
  ydb/core/fq/libs/quota_manager/events/events.h
Labels: new-feature

#10214 add test to dsproxy put
  ydb/core/blobstorage/dsproxy/ut/dsproxy_env_mock_ut.h
  ydb/core/blobstorage/dsproxy/ut/dsproxy_get_ut.cpp
  ydb/core/blobstorage/dsproxy/ut/dsproxy_put_ut.cpp
  ydb/core/blobstorage/dsproxy/ut/dsproxy_test_state_ut.h
  ydb/core/blobstorage/dsproxy/ut/dsproxy_vdisk_mock_ut.h
Labels: improvement

#11565 fix compaction memory prediction for special case
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/general_compaction.h
Labels: improvement

#11605 YT block input fix for empty input
  ydb/library/yql/providers/yt/codec/yt_codec_io.cpp
Labels: bugfix, external

#11602 [yt provider] Fix YtCopy type annotation check for column groups
  ydb/library/yql/providers/yt/provider/yql_yt_datasink_type_ann.cpp
Labels: area/yql, bugfix

#11609 Fix some artifacts of yql move
  ydb/library/yql/dq/integration/transform/ya.make
  ydb/library/yql/dq/integration/transform/yql_dq_task_transform.cpp
  ydb/library/yql/dq/integration/transform/yql_dq_task_transform.h
  ydb/library/yql/dq/integration/ya.make
  ydb/library/yql/dq/integration/yql_dq_integration.cpp
  ydb/library/yql/dq/integration/yql_dq_integration.h
  ydb/library/yql/dq/integration/yql_dq_optimization.cpp
  ydb/library/yql/dq/integration/yql_dq_optimization.h
  ydb/library/yql/providers/common/codec/arrow/ya.make
  ydb/library/yql/providers/common/codec/arrow/yql_codec_buf_input_stream.cpp
  ydb/library/yql/providers/common/codec/arrow/yql_codec_buf_input_stream.h
  ydb/library/yql/providers/common/codec/ya.make
  ydb/library/yql/providers/yt/codec/ya.make
  ydb/library/yql/providers/yt/codec/yt_codec_io.cpp
  ydb/library/yql/utils/line_split.cpp
  ydb/library/yql/utils/line_split.h
  ydb/public/lib/ydb_cli/commands/interactive/yql_position.cpp
Labels: area/yql, not-for-changelog

#11620 Drop moved dir
  ydb/library/yql/providers/common/dq/ya.make
  ydb/library/yql/providers/common/dq/yql_dq_integration_impl.cpp
  ydb/library/yql/providers/common/dq/yql_dq_integration_impl.h
  ydb/library/yql/providers/common/dq/yql_dq_optimization_impl.cpp
  ydb/library/yql/providers/common/dq/yql_dq_optimization_impl.h
Labels: area/yql, not-for-changelog
