Repository ydb-platform/ydb, pull requests merged in 2024-08, with the labels that each got.

#7334 fix empty column usage
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
Labels: bugfix

#7256 fixed metadata credentials code snippet for Go
  ydb/docs/en/core/recipes/ydb-sdk/auth-metadata.md
  ydb/docs/ru/core/recipes/ydb-sdk/auth-metadata.md
Labels: documentation

#7322 [misc] add 24-1-18 to releases page
  ydb/docs/en/core/downloads/_includes/server/docker.md
  ydb/docs/en/core/downloads/_includes/server/linux.md
  ydb/docs/en/core/downloads/_includes/server/source_code.md
  ydb/docs/ru/core/downloads/_includes/server/docker.md
  ydb/docs/ru/core/downloads/_includes/server/linux.md
  ydb/docs/ru/core/downloads/_includes/server/source_code.md
Labels: documentation

#7318 Fix BlobDepot docs
  ydb/docs/ru/core/maintenance/manual/blobdepot_decommit.md
Labels: documentation

#7327 Add value to config.proto for ICB DefaultHugeGarbagePerMille
  ydb/core/protos/config.proto
Labels: bugfix

#7292 Statistics: lternate between forced and scheduled traversals
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/aggregator_impl.h
  ydb/core/statistics/aggregator/tx_schemeshard_stats.cpp
Labels: not-for-changelog

#7340 fix columns normalization for absent
  ydb/core/formats/arrow/common/container.cpp
  ydb/core/formats/arrow/common/container.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/kqp/ut/service/ya.make
  ydb/core/tx/columnshard/engines/changes/compaction/abstract/merger.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/abstract/merger.h
  ydb/core/tx/columnshard/engines/changes/compaction/merger.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
Labels: improvement

#7342 YDBOPS-9957: [docs] updating executables with Ansible
  ydb/docs/en/core/devops/ansible/toc_p.yaml
  ydb/docs/en/core/devops/ansible/update-config.md
  ydb/docs/en/core/devops/ansible/update-executable.md
  ydb/docs/ru/core/devops/ansible/update-config.md
  ydb/docs/ru/core/devops/ansible/update-executable.md
Labels: documentation

#7289 [docs/glossary] add "compute nodes" as synonym to "database nodes"
  ydb/docs/en/core/concepts/glossary.md
  ydb/docs/ru/core/concepts/glossary.md
Labels: documentation

#7212 fix missing static group issue
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: bugfix

#7259 fixed inferring datatypes for columns with all null values
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#7344 Faster MapperSequentialCalls test
  ydb/core/mind/bscontroller/group_mapper_ut.cpp
Labels: not-for-changelog

#7341 Fix block device size calculcation code
  ydb/library/pdisk_io/wcache.cpp
Labels: bugfix

#7331 add test for parse_double
  ydb/library/yql/utils/parse_double_ut.cpp
Labels: not-for-changelog

#6878 meta nebius iam
  ydb/mvp/core/core_ydb.cpp
  ydb/mvp/core/core_ydb.h
  ydb/mvp/core/mvp_tokens.cpp
  ydb/mvp/core/mvp_tokens.h
  ydb/mvp/core/protos/mvp.proto
  ydb/mvp/meta/example-config.yaml
  ydb/mvp/meta/meta.cpp
  ydb/mvp/meta/meta_cloud.h
  ydb/mvp/meta/meta_cluster.h
  ydb/mvp/meta/meta_clusters.h
  ydb/mvp/meta/meta_cp_databases.h
  ydb/mvp/meta/meta_db_clusters.h
  ydb/mvp/meta/mvp.cpp
  ydb/mvp/meta/mvp.h
  ydb/mvp/oidc_proxy/example-config.yaml
  ydb/mvp/oidc_proxy/mvp.cpp
  ydb/mvp/oidc_proxy/oidc_protected_page_handler.cpp
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
  ydb/mvp/oidc_proxy/oidc_session_create_handler.cpp
  ydb/mvp/oidc_proxy/openid_connect.cpp
  ydb/mvp/oidc_proxy/openid_connect.h
Labels: new-feature

#7343 Add missing include for mutex
  ydb/library/yql/minikql/computation/mkql_computation_pattern_cache.h
  ydb/library/yql/providers/s3/provider/yql_s3_listing_strategy.cpp
  ydb/library/yql/providers/yt/comp_nodes/dq/dq_yt_rpc_reader.h
  ydb/public/lib/ydb_cli/commands/query_workload.cpp
  ydb/public/lib/ydb_cli/common/scheme_printers.h
Labels: external

#6118 Add few auto partitioning fields to describe and SDK. Add important consumer to CLI
  ydb/core/persqueue/ut/ut_with_sdk/autoscaling_ut.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_pq.cpp
  ydb/public/api/protos/ydb_topic.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic.cpp
  ydb/public/sdk/cpp/client/ydb_topic/include/control_plane.h
  ydb/services/persqueue_v1/actors/schema_actors.cpp
Labels: not-for-changelog

#7338 DML API for pg extensions
  ydb/library/yql/core/pg_ext/yql_pg_ext.cpp
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/catalog.h
  ydb/library/yql/parser/pg_wrapper/interface/parser.h
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/yql/read_table.h
  ydb/library/yql/parser/pg_wrapper/read_table.cpp
  ydb/library/yql/parser/pg_wrapper/ya.make
  ydb/library/yql/protos/pg_ext.proto
  ydb/library/yql/sql/pg/pg_sql.cpp
  ydb/library/yql/sql/pg_dummy/pg_sql_dummy.cpp
  ydb/library/yql/tools/exports.symlist
  ydb/library/yql/tools/yqlrun/pg_ext.txt
  ydb/library/yql/tools/yqlrun/yqlrun.cpp
Labels: area/yql, new-feature, area/pg

#6951 grace join: add bloom filters
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.h
Labels: performance

#4668 dqrun benchmark/result comarator scripts fixes and updates
  ydb/library/benchmarks/runner/result_compare/compare.py
  ydb/library/benchmarks/runner/result_convert/gen-report.py
  ydb/library/benchmarks/runner/run-tests.sh
  ydb/library/benchmarks/runner/runner/runner.py
  ydb/library/benchmarks/runner/runner/test-gateways.conf
Labels: not-for-changelog

#7377 ci: remove use ubuntu-2204 without oslogin for gh runner image
  ydb/ci/gh-runner-image/image.pkr.hcl
Labels: not-for-changelog

#7387 Mute ydb/tests/functional/clickbench
  .github/config/muted_ya.txt
Labels: not-for-changelog

#7378 Remove MemoryStats from SystemStateInfo
  ydb/core/memory_controller/memory_controller.cpp
  ydb/core/node_whiteboard/node_whiteboard.h
  ydb/core/protos/node_whiteboard.proto
  ydb/core/tablet/node_whiteboard.cpp
  ydb/core/viewer/json_tenantinfo.h
  ydb/core/viewer/protos/viewer.proto
Labels: not-for-changelog

#4891 Throttle compute-intensive tasks
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.h
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.h
  ydb/core/kqp/counters/kqp_counters.cpp
  ydb/core/kqp/counters/kqp_counters.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/runtime/kqp_compute_scheduler.cpp
  ydb/core/kqp/runtime/kqp_compute_scheduler.h
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/runtime/ya.make
  ydb/core/protos/kqp.proto
  ydb/core/protos/table_service_config.proto
Labels: new-feature

#7375 Memory leaks
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
Labels: bugfix

#7384 grace join: fix FROM ANY vs bloomfilter
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
Labels: bugfix

#7330 Transitional flag FIX_UNUSED_PARAMETR_PLS=1 (devtools request)
  build/internal/ya.conf
  ydb/core/blobstorage/nodewarden/node_warden_pdisk.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_metadata.cpp
  ydb/core/config/tools/protobuf_plugin/main.cpp
  ydb/core/formats/arrow/accessor/composite/accessor.h
  ydb/core/formats/arrow/accessor/composite_serial/accessor.h
  ydb/core/formats/arrow/accessor/plain/accessor.h
  ydb/core/formats/arrow/accessor/sparsed/accessor.h
  ydb/core/formats/arrow/accessor/sparsed/constructor.cpp
  ydb/core/formats/arrow/reader/position.h
  ydb/core/grpc_services/rpc_alter_table.cpp
  ydb/core/persqueue/read_balancer__balancing.cpp
  ydb/core/statistics/aggregator/tx_ack_timeout.cpp
  ydb/core/statistics/aggregator/tx_analyze_table.cpp
  ydb/core/statistics/aggregator/ut/ut_traverse_columnshard.cpp
  ydb/core/tx/columnshard/engines/changes/indexation.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/datashard/build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_apply_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_restore_incremental_backup.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
  ydb/library/yql/providers/yt/lib/res_pull/res_or_pull.cpp
  ydb/library/yql/sql/v1/select.cpp
Labels: not-for-changelog

#7362 fix uninit read in DqRewriteEquiJoin
  ydb/library/yql/dq/opt/dq_opt_join.cpp
Labels: not-for-changelog

#7356 fix UB with reading uninit var
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
Labels: not-for-changelog

#7316 Fix actor system usage after it was freed
  ydb/core/testlib/actors/test_runtime.cpp
Labels: not-for-changelog

#7380 Add tests for block support for JsonDocument type
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/input_json_document.txt
  ydb/library/yql/tests/sql/suites/blocks/input_json_document.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/json_document_type.cfg
  ydb/library/yql/tests/sql/suites/blocks/json_document_type.sql
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: area/yql, not-for-changelog

#7383 ToPg for wide tz types
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/strings_to_pg.sql
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
Labels: area/yql, new-feature, area/pg

#7366 Statistics: TAnalyze event contains many tables + Cookie
  ydb/core/protos/counters_statistics_aggregator.proto
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/aggregator_impl.h
  ydb/core/statistics/aggregator/schema.h
  ydb/core/statistics/aggregator/tx_analyze_table.cpp
  ydb/core/statistics/aggregator/tx_delete_query_response.cpp
  ydb/core/statistics/aggregator/tx_finish_trasersal.cpp
  ydb/core/statistics/aggregator/tx_init.cpp
  ydb/core/statistics/aggregator/tx_save_query_response.cpp
  ydb/core/statistics/aggregator/ut/ut_analyze_columnshard.cpp
  ydb/core/statistics/aggregator/ya.make
  ydb/core/statistics/database/database.cpp
  ydb/core/statistics/events.h
  ydb/core/statistics/ut_common/ut_common.cpp
Labels: not-for-changelog

#7358 inferred types for csv files are now optional
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/core/external_sources/object_storage/inference/ut/arrow_inference_ut.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#7357 Test report: mute history
  .github/scripts/tests/generate-summary.py
  .github/scripts/tests/get_test_history.py
  .github/scripts/tests/templates/summary.html
Labels: not-for-changelog

#7416 grace join: fix switching to spilling mode with LEFT* JOIN
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
Labels: new-feature

#7397 Statistics: Pass ColumnTags and Types
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/aggregator_impl.h
  ydb/core/statistics/aggregator/schema.h
  ydb/core/statistics/aggregator/tx_analyze_table.cpp
  ydb/core/statistics/aggregator/tx_init.cpp
  ydb/core/statistics/aggregator/tx_response_tablet_distribution.cpp
  ydb/core/statistics/aggregator/ut/ut_analyze_columnshard.cpp
  ydb/core/statistics/ut_common/ut_common.cpp
  ydb/core/statistics/ut_common/ut_common.h
Labels: not-for-changelog

#7427 Fix: Python udf not working when the function has name 'func'
  ydb/library/yql/mount/lib/yql/core.yql
Labels: bugfix

#7430 An option to disable YT calls inside DQ
  ydb/library/yql/providers/dq/config/config.proto
  ydb/library/yql/tools/dq/worker_job/dq_worker.cpp
Labels: area/yql, new-feature

#7347 Add tests for spilling in GraceJoin
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/ut/mkql_computation_node_ut.h
  ydb/library/yql/minikql/comp_nodes/ut/mkql_grace_join_ut.cpp
Labels: not-for-changelog

#7429 fix handling of schema elements in .sys directory
  ydb/core/viewer/viewer_acl.h
  ydb/core/viewer/viewer_describe.h
  ydb/core/viewer/viewer_hotkeys.h
Labels: improvement

#7396 FIX_UNUSED_PARAMETR_PLS=1 (devtools request)
  build/internal/ya.conf
  ydb/mvp/meta/mvp.cpp
Labels: not-for-changelog

#7441 move test TShardReader to a common place
  ydb/core/tx/columnshard/common/tests/shard_reader.cpp
  ydb/core/tx/columnshard/common/tests/ya.make
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/shard_reader.h
  ydb/core/tx/columnshard/test_helper/ya.make
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
  ydb/core/tx/columnshard/ut_rw/ya.make
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: improvement

#7408 Overlimit read memory
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/common/limits.h
  ydb/core/tx/columnshard/common/ya.make
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/counters/engine_logs.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.h
  ydb/core/tx/columnshard/engines/storage/granule/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule/portions_index.cpp
  ydb/core/tx/columnshard/engines/storage/granule/portions_index.h
Labels: improvement

#7431 make local internal CS persistent snapshot pinger
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/columnshard_private_events.h
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/common/snapshot.cpp
  ydb/core/tx/columnshard/common/snapshot.h
  ydb/core/tx/columnshard/counters/counters_manager.cpp
  ydb/core/tx/columnshard/counters/counters_manager.h
  ydb/core/tx/columnshard/counters/req_tracer.cpp
  ydb/core/tx/columnshard/counters/req_tracer.h
  ydb/core/tx/columnshard/counters/ya.make
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/constructor.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
  ydb/core/tx/columnshard/inflight_request_tracker.cpp
  ydb/core/tx/columnshard/inflight_request_tracker.h
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
Labels: new-feature

#7421 Added defaults args values in PgCall
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/minikql/mkql_type_builder.cpp
  ydb/library/yql/minikql/mkql_type_builder.h
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/catalog.h
  ydb/library/yql/sql/pg/pg_sql.cpp
  ydb/library/yql/sql/pg/ya.make
Labels: area/yql, bugfix, area/pg

#7432 pg extensions in dqrun
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/dqrun/ya.make
Labels: area/yql, new-feature, area/pg

#7350 Enable blocking tests policy (relwithdebinfo)
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#7401 oidc-proxy needs return 401 on ajax request
  ydb/mvp/oidc_proxy/oidc_protected_page.h
  ydb/mvp/oidc_proxy/oidc_protected_page_yandex.h
Labels: bugfix

#7246 renaming mvp config parameters
  ydb/mvp/oidc_proxy/mvp.cpp
  ydb/mvp/oidc_proxy/openid_connect.cpp
  ydb/mvp/oidc_proxy/openid_connect.h
Labels: improvement

#7451 removed tabs and fixed RENAME example in ALTER TABLE
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/alter_table.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/alter_table.md
Labels: documentation

#7452 better emulate YT job inside DQ
  ydb/library/yql/tools/dq/worker_job/dq_worker.cpp
Labels: bugfix

#7453 added attributes to session cookie
  ydb/mvp/oidc_proxy/openid_connect.cpp
Labels: improvement

#6900 Topics auto partitioning DDL
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/services/persqueue_v1/topic_yql_ut.cpp
Labels: not-for-changelog

#7439 Use jinja for html in build_analytics
  ydb/ci/build_bloat/html/index.html
  ydb/ci/build_bloat/html/webtreemap.css
  ydb/ci/build_bloat/html_template_bloat/bloat.css
  ydb/ci/build_bloat/html_template_bloat/index.html
  ydb/ci/build_bloat/html_template_bloat/webtreemap.css
  ydb/ci/build_bloat/html_template_bloat/webtreemap.js
  ydb/ci/build_bloat/main.py
  ydb/ci/build_bloat/template_bloat.py
Labels: not-for-changelog

#7423 Fix KqpOlapAggregations.Aggregation_ResultCountAll_Filter
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/aggregations_ut.cpp
Labels: bugfix

#7255 Add backup collection sql
  ydb/core/testlib/basics/feature_flags.h
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/format/sql_format_ut.cpp
  ydb/library/yql/sql/v1/sql.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_translation.h
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: experimental-feature

#7392 implement rows duplication check
  ydb/core/kqp/counters/kqp_counters.cpp
  ydb/core/kqp/counters/kqp_counters.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/protos/table_service_config.proto
  ydb/core/protos/tx_datashard.proto
Labels: not-for-changelog

#7456 futher fixing type inferring
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/core/external_sources/object_storage/inference/ut/arrow_inference_ut.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: improvement

#6996 SQL command ANALYZE
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/gateway/actors/analyze_actor.cpp
  ydb/core/kqp/gateway/actors/analyze_actor.h
  ydb/core/kqp/gateway/actors/ya.make
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_expr_nodes.json
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_provider.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.h
  ydb/core/kqp/provider/yql_kikimr_provider_impl.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/query/kqp_analyze_ut.cpp
  ydb/core/kqp/ut/query/ya.make
  ydb/core/protos/kqp_physical.proto
  ydb/core/statistics/ut_common/ut_common.cpp
  ydb/core/statistics/ut_common/ut_common.h
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/format/sql_format_ut.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/source.h
  ydb/library/yql/sql/v1/sql.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: new-feature

#7159 Add debuginfo helpers for LLVM codegeneration
  ydb/library/yql/minikql/codegen/codegen.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_callable.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_chain1_map.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_chain_map.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_chopper.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_condense.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_condense1.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_dictitems.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_discard.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_filter.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_flatmap.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_flow.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_iterator.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_map.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_map_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_multimap.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_switch.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_while.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.h.txt
Labels: area/yql, not-for-changelog

#7470 fix build for win-x86_64
  ydb/library/actors/core/mailbox.h
Labels: area/actorsystem, not-for-changelog

#7464 fix help typo for local_ydb
  ydb/public/tools/local_ydb/__main__.py
Labels: not-for-changelog

#7476 add default values for from/to
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
Labels: not-for-changelog

#7480 Storage groups group by
  ydb/core/viewer/json_handlers_storage.cpp
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/storage_groups.h
  ydb/core/viewer/viewer_query.h
Labels: improvement

#7459 temporary fix for SA tablet local db schema
  .github/config/muted_ya.txt
  ydb/core/statistics/aggregator/aggregator_impl.cpp
  ydb/core/statistics/aggregator/schema.h
  ydb/core/statistics/aggregator/tx_analyze_table.cpp
  ydb/core/statistics/aggregator/tx_init.cpp
Labels: not-for-changelog

#6807 YDB-2568 Enable match_recognize in ydb
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/executer_actor/ut/kqp_executer_ut.cpp
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_host.h
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/core/kqp/session_actor/kqp_worker_actor.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/kqp/ut/yql/kqp_pragma_ut.cpp
  ydb/core/protos/config.proto
  ydb/library/yql/core/yql_opt_match_recognize.cpp
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/test.test_match_recognize-without_order_by--Results_/extracted
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/match_recognize/alerts_without_order.sql
  ydb/library/yql/tests/sql/suites/match_recognize/test_type.sql
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/test.test_match_recognize-without_order_by--Results_/extracted
  ydb/library/yql/tools/dqrun/examples/gateways.conf
  ydb/tests/fq/yt/kqp_yt_file.py
  ydb/tests/tools/kqprun/configuration/app_config.conf
  ydb/tools/query_replay/query_compiler.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
Labels: not-for-changelog

#7466 do not look at active/inactive pdisk status in healthcheck
  ydb/core/health_check/health_check.cpp
Labels: bugfix

#7481 do not collect stats on error
  ydb/core/mon/async_http_mon.cpp
Labels: improvement

#7389 YQ-3491 support sql for resource pool classifiers
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/format/sql_format_ut.cpp
  ydb/library/yql/sql/v1/sql.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_translation.h
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: new-feature

#7479 Incremental optimizer for Wide&Block channels
  ydb/core/kqp/opt/kqp_opt_build_txs.cpp
  ydb/library/yql/dq/opt/dq_opt_build.cpp
Labels: area/yql, bugfix

#7496 YDB FQ: update outdated FQ architecture image
  ydb/docs/ru/core/concepts/federated_query/_assets/architecture.png
Labels: documentation

#7490 YQ kqprun remove start message
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: improvement

#7503 Fixes for tpcds
  ydb/library/benchmarks/gen_queries/consts.yql
  ydb/library/benchmarks/gen_queries/consts_decimal.yql
  ydb/library/benchmarks/gen_queries/pragmas_scalar.yql
  ydb/library/benchmarks/queries/tpcds/yql/q23.sql
  ydb/library/benchmarks/queries/tpcds/yql/q32.sql
Labels: new-feature

#7450 Yq 3428 fix
  ydb/core/external_sources/object_storage.cpp
  ydb/core/kqp/gateway/kqp_metadata_loader.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#7507 Rm -rf in actions (and it will be used in all workflows)
  .github/actions/build_and_test_ya/action.yml
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#7498 Move yql/tests/sql/kikimr_tpch/ to github
  ydb/core/kqp/tests/kikimr_tpch/kqp_tpch_ut.cpp
  ydb/core/kqp/tests/kikimr_tpch/ya.make
  ydb/core/kqp/tests/tpch/cmd_drop.cpp
  ydb/core/kqp/tests/tpch/cmd_drop.h
  ydb/core/kqp/tests/tpch/cmd_prepare.cpp
  ydb/core/kqp/tests/tpch/cmd_prepare.h
  ydb/core/kqp/tests/tpch/cmd_prepare_scheme.cpp
  ydb/core/kqp/tests/tpch/cmd_prepare_scheme.h
  ydb/core/kqp/tests/tpch/cmd_run_bench.cpp
  ydb/core/kqp/tests/tpch/cmd_run_bench.h
  ydb/core/kqp/tests/tpch/cmd_run_query.cpp
  ydb/core/kqp/tests/tpch/cmd_run_query.h
  ydb/core/kqp/tests/tpch/commands.cpp
  ydb/core/kqp/tests/tpch/commands.h
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/customer.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/lineitem.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/nation.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/orders.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/part.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/partsupp.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/region.tbl
  ydb/core/kqp/tests/tpch/lib/data/ps_0.001/supplier.tbl
  ydb/core/kqp/tests/tpch/lib/data/queries/01_Pricing_Summary_Report_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/02_Minimum_Cost_Supplier_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/03_Shipping_Priority_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/04_Order_Priority_Checking_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/05_Local_Supplier_Volume_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/06_Forecasting_Revenue_Change_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/07_Volume_Shipping_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/08_National_Market_Share_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/09_Product_Type_Profit_Measure_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/10_Returned_Item_Reporting_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/11_Important_Stock_Identification_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/12_Shipping_Modes_and_Order_Priority_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/13_Customer_Distribution_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/14_Promotion_Effect_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/15_Top_Supplier_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/16_Parts_Supplier_Relationship_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/17_Small_Quantity_Order_Revenue_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/18_Large_Volume_Customer_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/19_Discounted_Revenue_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/20_Potential_Part_Promotion_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/21_Suppliers_Who_Kept_Orders_Waiting_Query.sql
  ydb/core/kqp/tests/tpch/lib/data/queries/22_Global_Sales_Opportunity_Query.sql
  ydb/core/kqp/tests/tpch/lib/tpch_runner.cpp
  ydb/core/kqp/tests/tpch/lib/tpch_runner.h
  ydb/core/kqp/tests/tpch/lib/tpch_tables.cpp
  ydb/core/kqp/tests/tpch/lib/tpch_tables.h
  ydb/core/kqp/tests/tpch/lib/ya.make
  ydb/core/kqp/tests/tpch/main.cpp
  ydb/core/kqp/tests/tpch/ya.make
  ydb/core/kqp/tests/ya.make
  ydb/core/kqp/ya.make
Labels: not-for-changelog

#7515 Fix DQ input union/merge values with zero input channels
  ydb/library/yql/dq/runtime/dq_input_producer.cpp
  ydb/library/yql/dq/runtime/dq_input_producer.h
  ydb/library/yql/dq/runtime/dq_tasks_runner.cpp
Labels: area/yql, bugfix

#7517 [docs] more internal build fixes
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/delete.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/replace_into.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/update.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/upsert_into.md
Labels: documentation

#7520 [docs] delete outdated and unused public-talks.md
  ydb/docs/en/core/public-talks.md
Labels: documentation

#7518 [docs] add slides from https://coscup.org/2024/en/session/XZ98GN
  ydb/docs/en/core/public-materials/_includes/conferences/2024/coscup.md
  ydb/docs/en/core/public-materials/videos.md
  ydb/docs/en/presets.yaml
Labels: documentation

#7521 correctly check WB requests requirement, improve swagger description
  ydb/core/viewer/storage_groups.h
Labels: bugfix

#7436 Fix usage single UDF object from many threads in DQ.
  ydb/core/tx/datashard/datashard_kqp_lookup_table.cpp
  ydb/core/tx/datashard/datashard_kqp_read_table.cpp
  ydb/core/tx/program/registry.cpp
  ydb/library/yql/dq/runtime/dq_tasks_runner.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_scalar_apply.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_udf.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node.h
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.cpp
  ydb/library/yql/minikql/computation/mkql_computation_node_codegen.h.txt
  ydb/library/yql/providers/yt/lib/lambda_builder/lambda_builder.cpp
Labels: area/yql

#7487 mvp remove unnecessary methods
  ydb/mvp/meta/mvp.cpp
  ydb/mvp/meta/mvp.h
  ydb/mvp/oidc_proxy/oidc_protected_page.h
  ydb/mvp/oidc_proxy/oidc_protected_page_nebius.h
  ydb/mvp/oidc_proxy/oidc_protected_page_yandex.h
  ydb/mvp/oidc_proxy/oidc_session_create.h
  ydb/mvp/oidc_proxy/oidc_session_create_nebius.h
  ydb/mvp/oidc_proxy/oidc_session_create_yandex.h
Labels: improvement

#7529 Remove PSQL_BINARY setting in action
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#7482 `TEvReadSet` messages are being sent too often
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
Labels: bugfix

#7499 add database parameter to viewer/tabletinfo handler
  ydb/core/viewer/json_wb_req.cpp
  ydb/core/viewer/json_wb_req.h
  ydb/core/viewer/viewer_tabletinfo.h
  ydb/core/viewer/wb_req.h
Labels: new-feature

#7512 cbo/debug: fix Print with missing Stats
  ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
Labels: not-for-changelog

#7492 Remove old Json UDF (used only in SQL v0).
  ydb/apps/ydbd/ya.make
  ydb/library/yql/udfs/common/json/json_udf.cpp
  ydb/library/yql/udfs/common/json/test/canondata/result.json
  ydb/library/yql/udfs/common/json/test/canondata/test.test_Basic_/results.txt
  ydb/library/yql/udfs/common/json/test/cases/Basic.sql
  ydb/library/yql/udfs/common/json/test/ya.make
  ydb/library/yql/udfs/common/json/ya.make
  ydb/library/yql/udfs/common/ya.make
  ydb/tools/query_replay/common_deps.inc
  ydb/tools/query_replay_yt/common_deps.inc
Labels: area/yql

#7474 check vector access
  ydb/services/metadata/ds_table/accessor_snapshot_base.cpp
Labels: not-for-changelog

#7524 Print proper column names for wide connections
  ydb/core/kqp/opt/kqp_query_plan.cpp
Labels: bugfix

#7531 fixes applied to tpch tests
  ydb/core/kqp/tests/kikimr_tpch/ya.make
Labels: not-for-changelog

#7447 Allow use GraceJoinCore for map (Broadcast-et) joins
  ydb/core/kqp/opt/peephole/kqp_opt_peephole.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/library/yql/dq/expr_nodes/dq_expr_nodes.json
  ydb/library/yql/dq/opt/dq_opt_join.cpp
  ydb/library/yql/dq/opt/dq_opt_join.h
  ydb/library/yql/dq/opt/dq_opt_peephole.cpp
  ydb/library/yql/dq/opt/dq_opt_peephole.h
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/type_ann/dq_type_ann.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
  ydb/library/yql/providers/dq/opt/dqs_opt.cpp
  ydb/library/yql/providers/dq/opt/physical_optimize.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_datasink_constraints.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_datasink_type_ann.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_validate.cpp
Labels: new-feature

#7516 Pass pg extensions & catalog to mrjob
  ydb/library/yql/ast/yql_expr.cpp
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/core/pg_ext/yql_pg_ext.cpp
  ydb/library/yql/core/yql_user_data.h
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/catalog.h
  ydb/library/yql/parser/pg_catalog/proto/pg_catalog.proto
  ydb/library/yql/parser/pg_catalog/proto/ya.make
  ydb/library/yql/parser/pg_catalog/ya.make
  ydb/library/yql/protos/pg_ext.proto
  ydb/library/yql/providers/common/provider/ya.make
  ydb/library/yql/providers/common/provider/yql_provider.cpp
  ydb/library/yql/providers/common/provider/yql_provider.h
  ydb/library/yql/providers/yt/gateway/lib/user_files.cpp
  ydb/library/yql/providers/yt/gateway/lib/user_files.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_transform.cpp
  ydb/library/yql/providers/yt/job/ya.make
  ydb/library/yql/providers/yt/job/yql_job_base.cpp
  ydb/library/yql/sql/pg/pg_sql_ut.cpp
Labels: area/yql, new-feature, area/pg

#7547 Added casts to TPCH Q22
  ydb/library/benchmarks/queries/tpch/nice/q22.sql
Labels: bugfix

#7510 support memory pools configurations & tune spilling settings
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/core/kqp/rm_service/kqp_rm_ut.cpp
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
  ydb/core/kqp/ut/spilling/kqp_scan_spilling_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/table_service_config.proto
Labels: improvement

#7541 [refactoring] Remove unused GatherParents API
  ydb/core/kqp/opt/kqp_opt_phy_finalize.cpp
  ydb/library/yql/ast/yql_expr.cpp
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/dq/opt/dq_opt_phy_finalizing.cpp
Labels: area/yql, improvement

#7542 fix segfault in deserializer stream usage
  ydb/core/formats/arrow/accessor/composite_serial/accessor.cpp
  ydb/core/formats/arrow/accessor/composite_serial/accessor.h
Labels: bugfix

#7544 ci: move nodejs and testmo-cli install into gh-runner-image building process
  .github/actions/test_ya/action.yml
  ydb/ci/gh-runner-image/image.pkr.hcl
Labels: not-for-changelog

#7548 Pass pg extensions to dq TaskCommandExecutor
  ydb/library/yql/minikql/mkql_node.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/ut/pack_ut.cpp
  ydb/library/yql/parser/pg_wrapper/ut/ya.make
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
  ydb/library/yql/providers/dq/runtime/task_command_executor.cpp
  ydb/library/yql/providers/dq/runtime/ya.make
Labels: area/yql, new-feature, area/pg

#7553 Remove debug output
  ydb/core/kqp/runtime/kqp_compute_scheduler.h
Labels: bugfix

#7549 Transactions are loaded in chunks
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/ut/make_config.cpp
  ydb/core/persqueue/ut/make_config.h
  ydb/core/persqueue/ut/pqtablet_ut.cpp
Labels: bugfix

#7409 secrets have been fixed
  ydb/core/fq/libs/compute/ydb/synchronization_service/synchronization_service.cpp
  ydb/core/fq/libs/control_plane_proxy/actors/query_utils.cpp
  ydb/core/fq/libs/control_plane_proxy/actors/query_utils.h
  ydb/core/fq/libs/control_plane_proxy/actors/ydb_schema_query_actor.cpp
Labels: bugfix

#7471 Use common tool in treemap view
  ydb/ci/build_bloat/main.py
  ydb/ci/build_bloat/template_bloat.py
  ydb/ci/build_bloat/tree_map.py
Labels: not-for-changelog

#7561 Futher fix for YQ-3428
  ydb/core/external_sources/object_storage.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#7555 YQ revert local grpc peer value
  ydb/core/grpc_services/local_grpc/local_grpc.h
Labels: bugfix

#7577 Fix duplicate junit upload
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#7543 Add simple stability test for olap queries
  ydb/tools/cfg/static.py
  ydb/tools/olap_workload/__main__.py
  ydb/tools/olap_workload/ya.make
  ydb/tools/ya.make
Labels: new-feature

#7570 Revert "Fix cross join with list iterator. (#4683)"
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
Labels: area/yql

#7559 Enable finalizeByKey by default in kqp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
Labels: new-feature

#6151 Add decimal support to arrow reader
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/library/yql/minikql/arrow/arrow_util.h
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg_minmax.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg_state_helper.h
  ydb/library/yql/minikql/comp_nodes/mkql_block_agg_sum.cpp
  ydb/library/yql/minikql/computation/mkql_block_impl.cpp
  ydb/library/yql/minikql/computation/mkql_block_reader.cpp
  ydb/library/yql/minikql/mkql_type_builder.cpp
  ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.cpp
  ydb/library/yql/public/decimal/yql_decimal.cpp
  ydb/library/yql/public/decimal/yql_decimal.h
  ydb/library/yql/public/udf/arrow/block_builder.h
  ydb/library/yql/public/udf/arrow/block_io_buffer.h
  ydb/library/yql/public/udf/arrow/block_item.h
  ydb/library/yql/public/udf/arrow/block_item_comparator.h
  ydb/library/yql/public/udf/arrow/block_item_hasher.h
  ydb/library/yql/public/udf/arrow/block_reader.h
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/add_decimal.cfg
  ydb/library/yql/tests/sql/suites/blocks/add_decimal.sql
  ydb/library/yql/tests/sql/suites/blocks/combine_all_decimal.cfg
  ydb/library/yql/tests/sql/suites/blocks/combine_all_decimal.sql
  ydb/library/yql/tests/sql/suites/blocks/combine_all_decimal_max.sql
  ydb/library/yql/tests/sql/suites/blocks/input_decimal.txt
  ydb/library/yql/tests/sql/suites/blocks/input_decimal.txt.attr
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: not-for-changelog

#7562 fix query id for recompilation
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
Labels: bugfix

#7588 Limit transformation count while trying to annotate single node
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/core/type_ann/type_ann_expr.cpp
  ydb/library/yql/providers/config/yql_config_provider.cpp
Labels: area/yql, improvement

#7596 Delete empty portions normalizer
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/portion/clean_empty.cpp
  ydb/core/tx/columnshard/normalizer/portion/clean_empty.h
  ydb/core/tx/columnshard/normalizer/portion/normalizer.cpp
  ydb/core/tx/columnshard/normalizer/portion/ya.make
  ydb/core/tx/columnshard/ut_rw/ut_normalizer.cpp
Labels: bugfix

#7222 integrations and ide
  ydb/docs/build.sh
  ydb/docs/presets.yaml
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-connection-test.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-driver-create-new-driver-set-name_ru.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-driver-create-new-driver_ru.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-driver-management-driver_ru.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-driver-management-driver_set.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-driver-management_ru.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-query.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-table-structure.png
  ydb/docs/ru/core/integrations/ide/_assets/dbeaver-ydb-connection.png
  ydb/docs/ru/core/integrations/ide/_assets/ydb-connection-path.png
  ydb/docs/ru/core/integrations/ide/dbeaver.md
  ydb/docs/ru/core/integrations/index.md
  ydb/docs/ru/core/integrations/toc_i.yaml
  ydb/docs/ru/core/reference/toc_p.yaml
Labels: documentation

#7185 added functionality for the "--dont-use-log-files" flag
  ydb/public/tools/lib/cmds/__init__.py
  ydb/tests/library/harness/daemon.py
  ydb/tests/library/harness/kikimr_runner.py
Labels: bugfix, external

#7218 improve node deletion in hive
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/protos/config.proto
Labels: improvement

#7573 Allow logging AST with free arguments.
  ydb/library/yql/core/services/yql_out_transformers.cpp
Labels: area/yql, bugfix

#7587 Drop unused flag in IsYtCompleteIsolatedLambda
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_join.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_map.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_misc.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_partition.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_push.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_sort.cpp
  ydb/library/yql/providers/yt/provider/phy_opt/yql_yt_phy_opt_write.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasource.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasource_exec.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_optimize.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_helpers.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_helpers.h
  ydb/library/yql/providers/yt/provider/yql_yt_logical_optimize.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_physical_finalizing.cpp
Labels: area/yql, not-for-changelog

#7604 Merge #7758 to stable
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/core/type_ann/type_ann_expr.cpp
  ydb/library/yql/providers/config/yql_config_provider.cpp
Labels: area/yql

#7605 Add decimal types to bindings
  ydb/library/benchmarks/gen_queries/bindings_tpcds.json
  ydb/library/benchmarks/gen_queries/bindings_tpch.json
  ydb/library/benchmarks/gen_queries/gen_queries.py
Labels: new-feature

#7111 Remove cpu reqs from tests in order to speed up checks
  ydb/core/blobstorage/dsproxy/ut/ya.make
  ydb/core/blobstorage/ut_blobstorage/ut_group_reconfiguration/ya.make
  ydb/core/blobstorage/ut_blobstorage/ut_osiris/ya.make
  ydb/core/blobstorage/ut_blobstorage/ut_replication/ya.make
  ydb/core/blobstorage/ut_blobstorage/ut_scrub/ya.make
  ydb/core/blobstorage/vdisk/hullop/ut/ya.make
  ydb/core/client/ut/ya.make
  ydb/core/kqp/ut/idx_test/ya.make
  ydb/core/mind/bscontroller/ut_bscontroller/ya.make
  ydb/core/mind/ut/ya.make
  ydb/core/quoter/ut/ya.make
  ydb/core/tx/tx_proxy/ut_encrypted_storage/ya.make
  ydb/library/actors/interconnect/ut_huge_cluster/ya.make
  ydb/tests/functional/autoconfig/ya.make
  ydb/tests/functional/blobstorage/ya.make
  ydb/tests/functional/clickbench/ya.make
  ydb/tests/functional/cms/ya.make
  ydb/tests/functional/hive/ya.make
  ydb/tests/functional/kv_workload/ya.make
  ydb/tests/functional/large_serializable/ya.make
  ydb/tests/functional/rename/ya.make
  ydb/tests/functional/restarts/ya.make
  ydb/tests/functional/serverless/ya.make
  ydb/tests/functional/sqs/cloud/ya.make
  ydb/tests/functional/sqs/common/ya.make
  ydb/tests/functional/sqs/large/ya.make
  ydb/tests/functional/sqs/merge_split_common_table/fifo/ya.make
  ydb/tests/functional/sqs/merge_split_common_table/std/ya.make
  ydb/tests/functional/sqs/messaging/ya.make
  ydb/tests/functional/sqs/multinode/ya.make
  ydb/tests/functional/sqs/with_quotas/ya.make
Labels: not-for-changelog

#7606 Fix integer overflow in TTimeSliceLogic::DoCalcWeight
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/logic/slices/logic.cpp
Labels: bugfix

#7595 ExtractMembers from pg_tables read. Resolves #7286
  ydb/core/kqp/provider/yql_kikimr_opt_build.cpp
  ydb/core/kqp/ut/pg/pg_catalog_ut.cpp
Labels: not-for-changelog

#7622 YDB FQ: add MySQL / Greenplum to yql_generic_source_factory.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_source_factory.cpp
Labels: bugfix

#7607 YDB FQ: add missing types of connections to cloud audit
  ydb/core/fq/libs/cloud_audit/yq_cloud_audit_service.cpp
Labels: bugfix

#7574 Add basic dynconfig audit
  ydb/core/cms/console/console__replace_yaml_config.cpp
  ydb/core/cms/console/console_audit.cpp
  ydb/core/cms/console/console_audit.h
  ydb/core/cms/console/console_configs_manager.cpp
  ydb/core/cms/console/console_configs_manager.h
  ydb/core/cms/console/ya.make
  ydb/core/protos/console_config.proto
  ydb/tests/functional/audit/test_auditlog.py
Labels: improvement

#7569 handle EVFileError event in TObjectStorageExternalSource
  ydb/core/external_sources/object_storage.cpp
  ydb/core/external_sources/object_storage/events.h
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#7435 Handle spilling errors correctly
  ydb/core/kqp/compute_actor/kqp_compute_actor_impl.h
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/ut/spilling/kqp_scan_spilling_ut.cpp
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h
  ydb/library/yql/dq/actors/compute/dq_task_runner_exec_ctx.cpp
  ydb/library/yql/dq/actors/compute/dq_task_runner_exec_ctx.h
  ydb/library/yql/dq/actors/spilling/channel_storage.cpp
  ydb/library/yql/dq/actors/spilling/channel_storage.h
  ydb/library/yql/dq/actors/spilling/channel_storage_actor.cpp
  ydb/library/yql/dq/actors/spilling/channel_storage_actor.h
  ydb/library/yql/dq/actors/spilling/compute_storage.cpp
  ydb/library/yql/dq/actors/spilling/compute_storage.h
  ydb/library/yql/dq/actors/spilling/compute_storage_actor.cpp
  ydb/library/yql/dq/actors/spilling/compute_storage_actor.h
  ydb/library/yql/dq/actors/spilling/spiller_factory.h
  ydb/library/yql/dq/actors/task_runner/task_runner_actor_local.cpp
  ydb/library/yql/dq/common/dq_common.h
  ydb/library/yql/dq/runtime/dq_channel_storage.h
  ydb/library/yql/dq/runtime/dq_tasks_runner.h
  ydb/library/yql/providers/dq/actors/worker_actor.cpp
Labels: improvement

#7626 Flaky tests research
  .github/scripts/analytics/flaky_tests_history.py
  .github/workflows/collect_analytics.yml
Labels: not-for-changelog

#7623 fixes in memory pools
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/core/kqp/rm_service/kqp_rm_ut.cpp
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
  ydb/core/protos/kqp.proto
Labels: not-for-changelog

#7615 Fix testmo name in retry
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#7618 Fix env var name in CI
  .github/actions/test_ya/action.yml
Labels: not-for-changelog

#7563 Extracted yson result formatting from DQ service node
  ydb/core/fq/libs/actors/result_writer.cpp
  ydb/core/fq/libs/actors/run_actor.cpp
  ydb/library/yql/dq/common/dq_serialized_batch.cpp
  ydb/library/yql/dq/common/dq_serialized_batch.h
  ydb/library/yql/providers/common/schema/mkql/yql_mkql_schema.cpp
  ydb/library/yql/providers/dq/actors/proto_builder.cpp
  ydb/library/yql/providers/dq/actors/result_actor_base.h
  ydb/library/yql/providers/dq/actors/result_aggregator.cpp
  ydb/library/yql/providers/dq/actors/task_controller_impl.h
  ydb/library/yql/providers/dq/api/protos/dqs.proto
  ydb/library/yql/providers/dq/api/protos/service.proto
  ydb/library/yql/providers/dq/common/yql_dq_common.h
  ydb/library/yql/providers/dq/provider/ya.make
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.cpp
  ydb/library/yql/providers/dq/service/grpc_service.cpp
Labels: area/yql, not-for-changelog

#7576 [Http] Reply with structured issues when client accepts json data
  ydb/core/mon/async_http_mon.cpp
  ydb/core/mon/mon.cpp
  ydb/core/mon/mon.h
  ydb/core/mon/ya.make
  ydb/core/viewer/json_local_rpc.h
  ydb/core/viewer/viewer.cpp
  ydb/core/viewer/viewer.h
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/ya.make
Labels: improvement

#7631 Wrap ctor arguments in structs
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_assimilate.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_block.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_collect.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_discover.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_discover_m3dc.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_discover_m3of4.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_get.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_indexrestoreget.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_multicollect.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_multiget.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_patch.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_range.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_status.cpp
  ydb/core/blobstorage/dsproxy/ut/dsproxy_env_mock_ut.h
  ydb/core/blobstorage/dsproxy/ut_fat/dsproxy_ut.cpp
Labels: improvement

#7609 Fix syntax
  ydb/library/benchmarks/queries/tpcds/yql/q58.sql
Labels: new-feature

#7422 Mark SystemPython udfs for remote execution
  ydb/library/yql/providers/yt/gateway/native/yql_yt_transform.cpp
Labels: not-for-changelog

#7632 Decompression support for schema inference
  ydb/core/external_sources/object_storage.cpp
  ydb/core/external_sources/object_storage/inference/arrow_fetcher.cpp
  ydb/core/external_sources/object_storage/inference/arrow_fetcher.h
  ydb/core/external_sources/object_storage/inference/ut/arrow_inference_ut.cpp
  ydb/core/external_sources/object_storage/inference/ut/ya.make
  ydb/core/external_sources/object_storage/inference/ya.make
  ydb/tests/fq/s3/test_compression_data/test.csv.br
  ydb/tests/fq/s3/test_compression_data/test.csv.bz2
  ydb/tests/fq/s3/test_compression_data/test.csv.gz
  ydb/tests/fq/s3/test_compression_data/test.csv.lz4
  ydb/tests/fq/s3/test_compression_data/test.csv.xz
  ydb/tests/fq/s3/test_compression_data/test.csv.zst
  ydb/tests/fq/s3/test_compressions.py
Labels: new-feature

#7528 add pgport to command line args and to port allocator
  ydb/core/config/init/init_impl.h
  ydb/tests/functional/postgresql/test_postgres.py
  ydb/tests/library/harness/kikimr_config.py
  ydb/tests/library/harness/kikimr_port_allocator.py
  ydb/tests/library/harness/kikimr_runner.py
Labels: improvement

#7590 Set KQP & Resource Broker limits from MemoryController
  ydb/core/memory_controller/memory_controller.cpp
  ydb/core/memory_controller/memory_controller.h
  ydb/core/memory_controller/memory_controller_config.h
  ydb/core/memory_controller/memory_controller_ut.cpp
  ydb/core/memory_controller/ya.make
  ydb/core/protos/memory_controller_config.proto
  ydb/core/tablet/resource_broker.cpp
  ydb/core/tablet/resource_broker.h
  ydb/core/tablet/resource_broker_impl.h
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/tests/library/harness/resources/default_yaml.yml
Labels: not-for-changelog

#7554 tenantinfo handler added DatabaseStorage
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/viewer_tenantinfo.h
Labels: improvement

#7642 Collect statistic about unsuccessful block rewrites for callables and types
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/core/facade/yql_facade.h
  ydb/library/yql/core/issue/protos/issue_id.proto
  ydb/library/yql/core/issue/yql_issue.txt
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/core/yql_arrow_resolver.h
  ydb/library/yql/core/yql_expr_type_annotation.cpp
  ydb/library/yql/core/yql_expr_type_annotation.h
  ydb/library/yql/core/yql_type_annotation.cpp
  ydb/library/yql/core/yql_type_annotation.h
  ydb/library/yql/minikql/mkql_type_builder.cpp
  ydb/library/yql/minikql/mkql_type_builder.h
  ydb/library/yql/providers/common/arrow_resolve/yql_simple_arrow_resolver.cpp
  ydb/library/yql/providers/common/mkql/yql_type_mkql.cpp
  ydb/library/yql/providers/common/mkql/yql_type_mkql.h
  ydb/library/yql/tests/common/test_framework/yql_utils.py
  ydb/library/yql/tests/sql/dq_file.py
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/test.test_blocks-type_and_callable_stats--Results_/extracted
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/type_and_callable_stats.cfg
  ydb/library/yql/tests/sql/suites/blocks/type_and_callable_stats.sql
  ydb/library/yql/tests/sql/utils.py
  ydb/library/yql/tests/sql/yt_file.py
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/test.test_blocks-type_and_callable_stats--Results_/extracted
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/yqlrun/http/yql_server.cpp
  ydb/library/yql/tools/yqlrun/http/yql_servlet.h
  ydb/library/yql/tools/yqlrun/yqlrun.cpp
Labels: area/yql, new-feature

#7651 Restore LogAccEnabled in Discover and Get requests
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
Labels: bugfix

#7668 Storage dashboards
  ydb/deploy/helm/ydb-prometheus/dashboards/distributed-storage-latencies-leveled.json
  ydb/deploy/helm/ydb-prometheus/dashboards/distributed-storage-self-heal.json
  ydb/deploy/helm/ydb-prometheus/dashboards/replication-factor.json
  ydb/deploy/helm/ydb-prometheus/dashboards/single-pdisk.json
Labels: not-for-changelog

#7675 Merge #7570 to stable
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
Labels: area/yql

#7491 YQ-3492 support resource pool classifiers objects saving
  ydb/core/kqp/gateway/behaviour/resource_pool/manager.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/behaviour.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/behaviour.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/checker.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/checker.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/fetcher.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/fetcher.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/initializer.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/initializer.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/manager.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/manager.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/object.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/object.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/snapshot.cpp
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/snapshot.h
  ydb/core/kqp/gateway/behaviour/resource_pool_classifier/ya.make
  ydb/core/kqp/gateway/behaviour/ya.make
  ydb/core/kqp/gateway/ya.make
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/kqp/workload_service/actors/actors.h
  ydb/core/kqp/workload_service/actors/scheme_actors.cpp
  ydb/core/kqp/workload_service/common/events.h
  ydb/core/kqp/workload_service/common/helpers.cpp
  ydb/core/kqp/workload_service/ut/kqp_workload_service_ut.cpp
  ydb/core/resource_pools/resource_pool_classifier_settings.cpp
  ydb/core/resource_pools/resource_pool_classifier_settings.h
  ydb/core/resource_pools/resource_pool_classifier_settings_ut.cpp
  ydb/core/resource_pools/resource_pool_settings.cpp
  ydb/core/resource_pools/resource_pool_settings.h
  ydb/core/resource_pools/resource_pool_settings_ut.cpp
  ydb/core/resource_pools/settings_common.h
  ydb/core/resource_pools/ut/ya.make
  ydb/core/resource_pools/ya.make
  ydb/core/tx/tiering/rule/manager.cpp
  ydb/core/tx/tiering/rule/manager.h
  ydb/core/tx/tiering/tier/manager.cpp
  ydb/core/tx/tiering/tier/manager.h
  ydb/services/ext_index/metadata/manager.cpp
  ydb/services/ext_index/metadata/manager.h
  ydb/services/metadata/abstract/decoder.cpp
  ydb/services/metadata/abstract/decoder.h
  ydb/services/metadata/initializer/manager.cpp
  ydb/services/metadata/initializer/manager.h
  ydb/services/metadata/manager/abstract.h
  ydb/services/metadata/manager/alter_impl.h
  ydb/services/metadata/manager/common.h
  ydb/services/metadata/manager/object.cpp
  ydb/services/metadata/manager/object.h
  ydb/services/metadata/manager/table_record.cpp
  ydb/services/metadata/manager/table_record.h
  ydb/services/metadata/manager/ydb_value_operator.cpp
  ydb/services/metadata/manager/ydb_value_operator.h
  ydb/services/metadata/secret/manager.cpp
  ydb/services/metadata/secret/manager.h
Labels: new-feature

#7676 Resharper transactions are hanging
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
  ydb/core/persqueue/ut/pqtablet_ut.cpp
  ydb/core/protos/pqconfig.proto
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#7445 Fix configuration of ticket parser. Pass server certificates file path
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
Labels: bugfix

#7251 Pass AddressResolver config to DQ worker
  ydb/library/yql/providers/dq/actors/yt/resource_manager.h
  ydb/library/yql/providers/dq/actors/yt/yt_resource_manager.cpp
  ydb/library/yql/tools/dq/worker_job/dq_worker.cpp
  ydb/library/yql/yt/native/dq_manager.cpp
  ydb/library/yql/yt/native/dq_manager.h
Labels: not-for-changelog
