Repository ydb-platform/ydb, pull requests merged in 2024-05, with the labels that each got.

#4205 Fix viewer content type header parsing
  ydb/core/viewer/json_autocomplete.h
  ydb/core/viewer/json_query.h
  ydb/core/viewer/viewer_request.cpp
  ydb/core/viewer/viewer_request.h
  ydb/core/viewer/viewer_ut.cpp
Labels: bugfix

#3774 fix(http_proxy): remove cached resolve
  ydb/library/actors/http/http_proxy.cpp
Labels: not-for-changelog

#4202 Fix ss test and temporary disable kafka balance ut
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/persqueue/read_balancer__txinit.h
Labels: not-for-changelog

#4217 Add key for slice in acceptance workflow
  .github/workflows/acceptance_run.yml
Labels: not-for-changelog

#4194 Unbuffered variant of file qstorage
  ydb/library/yql/core/qplayer/storage/file/ut/yql_qstorage_file_ut.cpp
  ydb/library/yql/core/qplayer/storage/file/yql_qstorage_file.cpp
  ydb/library/yql/core/qplayer/storage/file/yql_qstorage_file.h
  ydb/library/yql/core/qplayer/storage/memory/yql_qstorage_memory.cpp
Labels: new-feature

#4103 [backup] Add draft backup controller tablet
  ydb/core/backup/controller/tablet.cpp
  ydb/core/backup/controller/tablet.h
  ydb/core/backup/controller/tablet_impl.h
  ydb/core/backup/controller/tx_init.cpp
  ydb/core/backup/controller/tx_init_schema.cpp
  ydb/core/backup/controller/ya.make
  ydb/core/backup/ya.make
  ydb/core/cms/console/console__create_tenant.cpp
  ydb/core/cms/console/console__scheme.h
  ydb/core/cms/console/console_tenants_manager.cpp
  ydb/core/cms/console/console_tenants_manager.h
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/driver_lib/run/ya.make
  ydb/core/mind/configured_tablet_bootstrapper.cpp
  ydb/core/mind/hive/hive.cpp
  ydb/core/protos/counters_backup.proto
  ydb/core/protos/counters_schemeshard.proto
  ydb/core/protos/flat_tx_scheme.proto
  ydb/core/protos/subdomains.proto
  ydb/core/protos/tablet.proto
  ydb/core/protos/ya.make
  ydb/core/tx/schemeshard/schemeshard__delete_tablet_reply.cpp
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__init_root.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_extsubdomain.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common.h
  ydb/core/tx/schemeshard/schemeshard__operation_common_subdomain.h
  ydb/core/tx/schemeshard/schemeshard__sync_update_tenants.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_svp_migration.cpp
  ydb/core/tx/schemeshard/schemeshard_svp_migration.h
  ydb/core/ya.make
  ydb/library/services/services.proto
Labels: not-for-changelog

#4220 Fix scheduled build
  .github/workflows/acceptance_run.yml
Labels: not-for-changelog

#4037 json_storage added pdiskid filter
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/actors/test_runtime.h
  ydb/core/viewer/json_storage.h
  ydb/core/viewer/json_storage_base.h
  ydb/core/viewer/viewer_ut.cpp
Labels: new-feature

#4209 Add kernel method for applying any abstract lambda.
  ydb/library/yql/core/arrow_kernels/registry/ut/registry_ut.cpp
  ydb/library/yql/core/arrow_kernels/request/request.cpp
  ydb/library/yql/core/arrow_kernels/request/request.h
Labels: new-feature

#4232 Check VDisk status before reassigning disk in static group
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/protos/blobstorage_distributed_config.proto
Labels: not-for-changelog

#4243 Support of mrjob in dqrun
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/dqrun/ya.make
Labels: new-feature

#4248 Mute tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#4251 Support of parameters & gateways replaying
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/core/facade/yql_facade.h
  ydb/library/yql/core/ut/ya.make
  ydb/library/yql/core/ut/yql_qplayer_ut.cpp
  ydb/library/yql/tools/dqrun/dqrun.cpp
Labels: new-feature

#4256 [YQL-18107] Do not reset expected types/column order in ParseType
  ydb/library/yql/core/type_ann/type_ann_types.cpp
Labels: area/yql, bugfix

#4216 fix race on select scan
  ydb/core/testlib/common_helper.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/interval.cpp
Labels: bugfix

#4239 split proto library for future deps usage
  ydb/core/formats/arrow/protos/ssa.proto
  ydb/core/formats/arrow/protos/ya.make
  ydb/core/formats/arrow/ssa_program_optimizer.h
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_fetcher_actor.cpp
  ydb/core/kqp/compute_actor/ya.make
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/ya.make
  ydb/core/kqp/query_compiler/kqp_olap_compiler.cpp
  ydb/core/kqp/query_compiler/kqp_olap_compiler.h
  ydb/core/protos/tx_columnshard.proto
  ydb/core/protos/tx_datashard.proto
  ydb/core/protos/ya.make
  ydb/core/tx/columnshard/common/scalars.cpp
  ydb/core/tx/columnshard/common/scalars.h
  ydb/core/tx/columnshard/common/tests/ya.make
  ydb/core/tx/columnshard/common/ya.make
  ydb/core/tx/columnshard/data_sharing/protos/data.proto
  ydb/core/tx/columnshard/data_sharing/protos/events.proto
  ydb/core/tx/columnshard/data_sharing/protos/sessions.proto
  ydb/core/tx/columnshard/data_sharing/protos/ya.make
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/portions/meta.h
  ydb/core/tx/columnshard/engines/portions/ya.make
  ydb/core/tx/columnshard/engines/protos/portion_info.proto
  ydb/core/tx/columnshard/engines/protos/ya.make
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/checker.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/ya.make
  ydb/core/tx/columnshard/engines/ya.make
  ydb/core/tx/columnshard/operations/write_data.h
  ydb/core/tx/program/program.h
  ydb/core/tx/program/ya.make
  ydb/core/util/ui64id.h
  ydb/library/conclusion/result.h
  ydb/library/conclusion/status.cpp
  ydb/library/conclusion/status.h
Labels: improvement

#4262 fix test SchemeActualizationOnceOnStart after new normalizer
  ydb/core/kqp/ut/olap/indexes_ut.cpp
Labels: bugfix

#4261 fix optimizer tasks constructions
  ydb/core/tx/columnshard/engines/storage/optimizer/lbuckets/optimizer.h
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.cpp
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.cpp
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
  ydb/core/tx/columnshard/hooks/testing/ya.make
  ydb/core/tx/tiering/ut/ut_tiers.cpp
Labels: improvement

#4249 The TxUsage::WriteTopic_Demo_8 test is flashing
  ydb/public/sdk/cpp/client/ydb_topic/impl/write_session_impl.cpp
  ydb/public/sdk/cpp/client/ydb_topic/impl/write_session_impl.h
Labels: bugfix

#4266 Fix ya make indent
  ydb/core/backup/controller/ya.make
Labels: not-for-changelog

#4096 Verify input Arrow Datum in WideFromBlocks
  ydb/library/yql/minikql/comp_nodes/mkql_blocks.cpp
Labels: not-for-changelog

#4269 Fix buffer overflow
  ydb/core/persqueue/ut/partition_ut.cpp
Labels: bugfix

#4193 Pass pgwire user connection param to pg_roles table. resolves #3124
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/proxy_service/kqp_session_info.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.h
  ydb/core/kqp/ut/pg/pg_catalog_ut.cpp
  ydb/core/local_pgwire/local_pgwire_connection.cpp
  ydb/core/protos/kqp.proto
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/memory_context.h
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
  ydb/tests/functional/postgresql/cases/roles.out
  ydb/tests/functional/postgresql/cases/roles.sql
Labels: not-for-changelog

#4238 Add slice tests
  ydb/tests/acceptance/cluster.yaml
  ydb/tests/acceptance/setup_slice/ya.make
  ydb/tests/acceptance/test_slice.py
  ydb/tests/acceptance/ya.make
  ydb/tests/library/harness/ydbd_slice.py
  ydb/tests/library/ya.make
  ydb/tools/ydbd_slice/handlers.py
  ydb/tools/ydbd_slice/ya.make
Labels: not-for-changelog

#4265 Mute tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#4226 Don't erase first numerical character in sensor name in prometheus format
  library/cpp/monlib/encode/prometheus/prometheus_encoder.cpp
  library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp
Labels: bugfix

#4270 autocomplete check word containing
  ydb/core/viewer/json_autocomplete.h
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/query_autocomplete_helper.h
  ydb/core/viewer/viewer_ut.cpp
Labels: new-feature, improvement

#4240 More types support for literal expressions.
  ydb/core/kqp/provider/yql_kikimr_provider.cpp
  ydb/core/kqp/provider/yql_kikimr_provider_impl.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_constraints_ut.cpp
Labels: bugfix

#4264 relax local compute tasks
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/rm_service/kqp_rm_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/core/tx/datashard/datashard_ut_trace.cpp
Labels: improvement

#4279 Support of libraries in qplayer
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/core/ut/ya.make
  ydb/library/yql/core/ut/yql_qplayer_ut.cpp
  ydb/library/yql/core/yql_type_annotation.cpp
  ydb/library/yql/core/yql_type_annotation.h
Labels: new-feature

#4225 Limits for qwriters
  ydb/library/yql/core/qplayer/storage/file/yql_qstorage_file.cpp
  ydb/library/yql/core/qplayer/storage/interface/yql_qstorage.h
  ydb/library/yql/core/qplayer/storage/memory/yql_qstorage_memory.cpp
  ydb/library/yql/core/qplayer/storage/ut_common/yql_qstorage_ut_common.cpp
  ydb/library/yql/core/qplayer/storage/ut_common/yql_qstorage_ut_common.h
  ydb/library/yql/core/qplayer/storage/ydb/yql_qstorage_ydb.cpp
Labels: new-feature

#4292 [YQL-18107] Fix CalcOverWindow with non-null default value in WindowTraits
  ydb/library/yql/core/type_ann/type_ann_list.cpp
  ydb/library/yql/core/yql_opt_window.cpp
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/window/udaf_with_def_value.sql
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
Labels: area/yql, bugfix

#4283 fix
  ydb/core/tx/tiering/ut/ya.make
Labels: bugfix

#4281 Improve distconf compatibility with BSC
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/protos/blobstorage_config.proto
  ydb/core/protos/blobstorage_distributed_config.proto
Labels: not-for-changelog

#4286 Fix distconf <-> BSC interaction issues
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/impl.h
Labels: not-for-changelog

#4291 Support of evaluation & WalkFolders in qplayer
  ydb/library/yql/ast/yql_expr.cpp
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/core/services/ya.make
  ydb/library/yql/core/services/yql_eval_expr.cpp
  ydb/library/yql/core/ut/yql_qplayer_ut.cpp
  ydb/library/yql/core/yql_type_annotation.h
  ydb/library/yql/providers/yt/gateway/qplayer/yql_yt_qplayer_gateway.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_io_discovery_walk_folders.cpp
Labels: new-feature

#4282 fix arrow type utf8 -> binary
  ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp
Labels: not-for-changelog

#4293 [YQL-18107] Use Uint32 instead of String as parent argument when expanding CalcOverWindow
  ydb/library/yql/core/yql_opt_window.cpp
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: area/yql, bugfix

#4294 Early cleanup of uncommited qstorage files
  ydb/library/yql/core/qplayer/storage/file/yql_qstorage_file.cpp
  ydb/library/yql/core/qplayer/storage/ut_common/yql_qstorage_ut_common.cpp
  ydb/library/yql/core/qplayer/storage/ut_common/yql_qstorage_ut_common.h
  ydb/library/yql/tools/dqrun/dqrun.cpp
Labels: improvement

#4296 Changed version of fluentbit-ydb output plugin
  ydb/docs/en/core/integrations/fluent-bit.md
  ydb/docs/ru/core/integrations/fluent-bit.md
Labels: documentation

#4297 [YQL-18313] Mark Datetime::Split as strict
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/udfs/common/datetime2/datetime_udf.cpp
Labels: area/yql, performance

#4295 reduce deps for sys view usage
  ydb/core/tx/columnshard/engines/reader/abstract/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/constructor.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/filler.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/filler.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/policy.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/policy.h
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/ya.make
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.h
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/ya.make
  ydb/core/tx/columnshard/engines/reader/sys_view/constructor/constructor.h
  ydb/core/tx/columnshard/engines/reader/sys_view/granules/granules.h
  ydb/core/tx/columnshard/engines/reader/sys_view/granules/ya.make
  ydb/core/tx/columnshard/engines/reader/sys_view/portions/portions.h
  ydb/core/tx/columnshard/engines/reader/sys_view/portions/ya.make
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
Labels: improvement

#4301 fix read checker
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
Labels: bugfix

#4304 [docs] update index.yaml ru translation
  ydb/docs/ru/core/index.yaml
Labels: documentation

#4255 YQL-18053: Add block implementation for AsStruct callable (v2)
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/core/type_ann/type_ann_blocks.cpp
  ydb/library/yql/core/type_ann/type_ann_blocks.h
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/core/yql_expr_constraint.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_container.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_block_container.h
  ydb/library/yql/minikql/comp_nodes/mkql_block_tuple.h
  ydb/library/yql/minikql/comp_nodes/mkql_factory.cpp
  ydb/library/yql/minikql/comp_nodes/ya.make.inc
  ydb/library/yql/minikql/mkql_program_builder.cpp
  ydb/library/yql/minikql/mkql_program_builder.h
  ydb/library/yql/providers/common/mkql/yql_provider_mkql.cpp
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/member.sql
  ydb/library/yql/tests/sql/suites/blocks/sort_one_asc.sql
  ydb/library/yql/tests/sql/suites/blocks/sort_one_desc.sql
  ydb/library/yql/tests/sql/suites/blocks/sort_two_asc.sql
  ydb/library/yql/tests/sql/suites/blocks/sort_two_desc.sql
  ydb/library/yql/tests/sql/suites/blocks/sort_two_mix.sql
  ydb/library/yql/tests/sql/suites/blocks/top_sort_one_asc.sql
  ydb/library/yql/tests/sql/suites/blocks/top_sort_one_desc.sql
  ydb/library/yql/tests/sql/suites/blocks/top_sort_two_asc.sql
  ydb/library/yql/tests/sql/suites/blocks/top_sort_two_desc.sql
  ydb/library/yql/tests/sql/suites/blocks/top_sort_two_mix.sql
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: improvement

#4298 YQL-18327 Disable yellow zone of allocator on 50%. Update yellow zone on free
  ydb/library/yql/minikql/aligned_page_pool.cpp
  ydb/library/yql/minikql/aligned_page_pool.h
  ydb/library/yql/minikql/aligned_page_pool_ut.cpp
Labels: improvement

#4186 Add issues for refresh token errors
  ydb/core/grpc_services/rpc_calls.h
  ydb/services/persqueue_v1/actors/direct_read_actor.cpp
  ydb/services/persqueue_v1/actors/read_session_actor.cpp
  ydb/services/persqueue_v1/actors/write_session_actor.cpp
Labels: not-for-changelog

#4278 Switch some tests to enable_v3_new_behavior
  ydb/tests/functional/api/test_isolation.py
  ydb/tests/functional/api/test_public_api.py
  ydb/tests/library/ya.make
Labels: not-for-changelog

#4308 Make Arrow Datum check message more verbose
  ydb/library/yql/minikql/comp_nodes/mkql_blocks.cpp
  ydb/library/yql/minikql/computation/mkql_block_impl.cpp
  ydb/library/yql/public/udf/arrow/defs.h
Labels: not-for-changelog

#4320 Drop replication with invalid credentials
  ydb/core/tx/replication/controller/replication.cpp
  ydb/core/tx/schemeshard/ut_replication/ut_replication.cpp
Labels: not-for-changelog

#4322 Require credentials & connection_string/endpoint
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
Labels: not-for-changelog

#4315 General SelfHeal fixes
  ydb/core/mind/bscontroller/config_cmd.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/register_node.cpp
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/mind/bscontroller/self_heal.h
  ydb/core/mind/bscontroller/ut_bscontroller/main.cpp
  ydb/core/mind/bscontroller/ut_selfheal/self_heal_actor_ut.cpp
  ydb/core/mind/bscontroller/vdisk_status_tracker.h
  ydb/core/mind/bscontroller/ya.make
Labels: bugfix

#4250 Implement OAuth 2.0 Token Exchange credentials provider in C++ SDK
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/credentials.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/credentials.h
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/jwt_token_source.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/jwt_token_source.h
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/credentials_ut.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/jwt_token_source_ut.cpp
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ut/ya.make
  ydb/public/sdk/cpp/client/ydb_types/credentials/oauth2_token_exchange/ya.make
  ydb/public/sdk/cpp/client/ydb_types/credentials/ya.make
Labels: new-feature

#4328 [YQL-17412] Clone named expression before using it
  ydb/library/yql/sql/v1/context.cpp
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/aggregate/should_use_clone_for_bind_params.sqlx
Labels: area/yql, bugfix

#4329 [YQL-18337] Check for strictness in sort-by-constant-expression optimizer
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/yql_opt_utils.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/optimizers/sort_by_nonstrict_const.cfg
  ydb/library/yql/tests/sql/suites/optimizers/sort_by_nonstrict_const.sql
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/test.test_optimizers-sort_by_nonstrict_const--Results_/extracted
Labels: area/yql, bugfix

#4312 fix coverity issue: use after move
  ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
Labels: not-for-changelog

#4336 Adapt BS_CONTROLLER's SelfHeal for static groups too
  ydb/core/blobstorage/groupinfo/blobstorage_groupinfo.cpp
  ydb/core/blobstorage/groupinfo/blobstorage_groupinfo.h
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/config.h
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/register_node.cpp
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/mind/bscontroller/ut_selfheal/self_heal_actor_ut.cpp
Labels: new-feature

#4122 Decrease soft limit to 75%
  ydb/core/mon_alloc/monitor.cpp
Labels: not-for-changelog

#3908 Changed the DataShard stats collection actor using coroutine
  ydb/core/tablet_flat/benchmark/b_part.cpp
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table.h
  ydb/core/tablet_flat/ut/ut_stat.cpp
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_stats.cpp
Labels: not-for-changelog

#4339 Differentiate simple & cascade drop
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/counters_schemeshard.proto
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/nodes_manager.cpp
  ydb/core/tx/replication/controller/nodes_manager.h
  ydb/core/tx/replication/controller/tx_drop_replication.cpp
  ydb/core/tx/replication/controller/tx_drop_stream_result.cpp
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_replication.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_part.h
  ydb/core/tx/schemeshard/schemeshard_audit_log_fragment.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_tx_infly.h
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/core/tx/tx_proxy/schemereq.cpp
Labels: not-for-changelog

#4314 Fix followers not reading system tables and not processing requests
  ydb/core/tablet_flat/flat_database.cpp
  ydb/core/tablet_flat/flat_database.h
  ydb/core/tx/datashard/datashard__init.cpp
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_user_table.h
  ydb/core/tx/datashard/datashard_ut_followers.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: bugfix

#4333 Alter replication config
  ydb/core/tx/replication/controller/dst_creator_ut.cpp
  ydb/core/tx/replication/ut_helpers/test_table.cpp
  ydb/core/tx/replication/ut_helpers/test_table.h
  ydb/core/tx/schemeshard/schemeshard__operation_alter_table.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/core/tx/schemeshard/ut_replication/ut_replication.cpp
  ydb/core/tx/schemeshard/ut_replication_reboots/ut_replication_reboots.cpp
Labels: not-for-changelog

#4342 Report detailed PDisk metrics to whiteboard
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/protos/node_whiteboard.proto
Labels: not-for-changelog

#4058 Add builtins for struct operations
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/struct_merge.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
Labels: area/yql, new-feature

#4341 Fixed RH hash table bucket policy
  ydb/library/yql/minikql/comp_nodes/mkql_rh_hash.h
  ydb/library/yql/minikql/comp_nodes/ut/mkql_rh_hash_ut.cpp
Labels: bugfix

#4321 Block channels flag
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/opt/kqp_opt_build_txs.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#4331 Support arbiters in volatile transactions
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/protos/data_events.proto
  ydb/core/protos/feature_flags.proto
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__init.cpp
  ydb/core/tx/datashard/datashard_common_upload.cpp
  ydb/core/tx/datashard/datashard_direct_erase.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/core/tx/datashard/datashard_kqp.h
  ydb/core/tx/datashard/datashard_outreadset.cpp
  ydb/core/tx/datashard/datashard_outreadset.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/execute_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_distributed_erase_tx_unit.cpp
  ydb/core/tx/datashard/execute_kqp_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/volatile_tx.cpp
  ydb/core/tx/datashard/volatile_tx.h
Labels: new-feature

#4353 the actor of the partition deleted the configuration of the PQ tablet
  ydb/core/persqueue/key.cpp
  ydb/core/persqueue/key.h
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/ya.make
Labels: bugfix

#4365 Fix tpcds q70 syntax
  ydb/library/benchmarks/queries/tpcds/yql/q70.sql
Labels: not-for-changelog

#4263 Evwrite Immediate sink
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/protos/kqp.proto
Labels: not-for-changelog

#4360 Report UserSID for all gRPC-issued BSC operations
  ydb/core/client/server/msgbus_blobstorage_config.cpp
  ydb/core/protos/blobstorage_config.proto
Labels: not-for-changelog

#4362 [YQL-17412] Fix DoClone()
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/insert.cpp
  ydb/library/yql/sql/v1/match_recognize.cpp
  ydb/library/yql/sql/v1/match_recognize.h
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
Labels: area/yql, bugfix

#4361 Remove obsolete gRPC commands
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/grpc_server.h
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server_get.cpp
  ydb/core/client/server/msgbus_server_load.cpp
  ydb/core/client/server/ya.make
  ydb/core/driver_lib/cli_utils/cli.h
  ydb/core/driver_lib/cli_utils/cli_cmd_config.h
  ydb/core/driver_lib/cli_utils/cli_cmds_bs.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_get.cpp
  ydb/core/driver_lib/cli_utils/cli_load.cpp
  ydb/core/driver_lib/cli_utils/ya.make
  ydb/core/driver_lib/run/driver.h
  ydb/core/driver_lib/run/main.cpp
  ydb/core/protos/grpc.proto
  ydb/core/protos/msgbus.proto
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/client/grpc_client.h
  ydb/public/lib/deprecated/kicli/kikimr.cpp
  ydb/public/lib/deprecated/kicli/result.cpp
Labels: not-for-changelog

#4337 pgwire HACK for converting results to binary format. closes #3997
  ydb/core/local_pgwire/pgwire_kqp_proxy.cpp
Labels: not-for-changelog

#4379 Refactor a common SendProposeToCoordinator
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: not-for-changelog

#4377 set ImmediateTx = true for pure selects
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
Labels: not-for-changelog

#4374 Special message for OAuth token
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/replication.cpp
  ydb/core/tx/replication/service/service.cpp
Labels: not-for-changelog

#4367 Adjust compaction logic to remove unneeded items more quickly
  ydb/core/blobstorage/vdisk/anubis_osiris/blobstorage_anubisfinder.cpp
  ydb/core/blobstorage/vdisk/anubis_osiris/blobstorage_osiris.cpp
  ydb/core/blobstorage/vdisk/defrag/defrag_search.h
  ydb/core/blobstorage/vdisk/hulldb/barriers/barriers_essence.cpp
  ydb/core/blobstorage/vdisk/hulldb/barriers/barriers_essence.h
  ydb/core/blobstorage/vdisk/hulldb/blobstorage_hullgcmap.h
  ydb/core/blobstorage/vdisk/hulldb/compstrat/hulldb_compstrat_ratio.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hullrecmerger.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_idxsnap_it.h
  ydb/core/blobstorage/vdisk/query/query_extr.cpp
  ydb/core/blobstorage/vdisk/query/query_range.cpp
  ydb/core/blobstorage/vdisk/repl/blobstorage_hullrepljob.cpp
  ydb/core/blobstorage/vdisk/scrub/scrub_actor_huge.cpp
  ydb/core/blobstorage/vdisk/scrub/scrub_actor_sst_blob_merger.h
  ydb/core/blobstorage/vdisk/scrub/scrub_actor_unreadable.cpp
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_syncfull.cpp
Labels: not-for-changelog

#4369 error description in NKikimrPQ::TEvProposeTransactionResult
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/protos/pqconfig.proto
Labels: improvement

#4069 Add docs for struct operations
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/struct.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/struct.md
Labels: documentation

#4355 do not treat initial tablet metrics values as 0
  ydb/core/tablet/tablet_metrics.cpp
  ydb/core/tablet/tablet_metrics.h
Labels: bugfix

#4359 Just to be sure avoid an nre in GetStickyColumns
  ydb/core/tablet_flat/flat_executor.cpp
Labels: not-for-changelog

#4344 Add BuildStats error handling test
  ydb/core/tx/datashard/datashard_ut_stats.cpp
Labels: not-for-changelog

#4267 [docs] recommend to use 3 nodes for Ansible initial deployment
  ydb/docs/en/core/devops/ansible/_includes/repo-tree.md
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/en/core/devops/ansible/preparing-vms-with-terraform.md
  ydb/docs/ru/core/devops/ansible/_includes/repo-tree.md
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/ansible/preparing-vms-with-terraform.md
Labels: documentation

#4327 health-check lacks iterator validation vulnerability
  ydb/core/health_check/health_check.cpp
Labels: improvement

#4382 Disable auth to /postgres, increase current_database oid. resolves #4285
  ydb/core/local_pgwire/local_pgwire.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/pg_catalog_consts.h
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
Labels: not-for-changelog

#4386 Support of lineage over session window inside window
  ydb/library/yql/core/services/yql_lineage.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/lineage/window_session.sql
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: new-feature

#4373 Fixed position of Evaluate* errors
  ydb/library/yql/ast/yql_expr.cpp
  ydb/library/yql/ast/yql_expr.h
  ydb/library/yql/core/services/yql_eval_expr.cpp
  ydb/library/yql/core/services/yql_eval_params.cpp
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/context.cpp
  ydb/library/yql/sql/v1/context.h
  ydb/library/yql/sql/v1/list_builtin.cpp
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/source.h
  ydb/library/yql/sql/v1/sql_call_expr.cpp
  ydb/library/yql/sql/v1/sql_into_tables.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
  ydb/library/yql/tests/sql/dq_file/part16/canondata/test.test_action-pending_arg_fail--Results_/extracted
  ydb/library/yql/tests/sql/dq_file/part2/canondata/test.test_view-file_outer--Results_/extracted
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/action/eval_atom_wrong_type_expr.cfg
  ydb/library/yql/tests/sql/suites/action/eval_atom_wrong_type_expr.sql
  ydb/library/yql/tests/sql/suites/action/eval_atom_wrong_type_param.cfg
  ydb/library/yql/tests/sql/suites/action/eval_atom_wrong_type_param.sql
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/test.test_action-eval_atom_wrong_type_expr--Results_/extracted
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/test.test_action-pending_arg_fail--Results_/extracted
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/test.test_view-file_outer--Results_/extracted
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/test.test_action-eval_atom_wrong_type_param--Results_/extracted
Labels: bugfix

#4397 Support of replaying of YtGateway::ResolveLinks
  ydb/library/yql/providers/yt/gateway/qplayer/yql_yt_qplayer_gateway.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_io_discovery_walk_folders.cpp
Labels: new-feature

#4402 [YQL-17700] More tests for TryMember
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/try_member.cfg
  ydb/library/yql/tests/sql/suites/expr/try_member.sql
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
Labels: area/yql, improvement

#4305 YQL-18097: add support for non-struct SCHEMA for YT
  ydb/library/yql/sql/v1/sql_into_tables.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_translation.h
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: area/yql, bugfix

#4356 Add node name prefix
  ydb/core/mind/node_broker.cpp
  ydb/core/mind/node_broker_impl.h
  ydb/core/protos/node_broker.proto
Labels: not-for-changelog

#4408 [YQL-17700] Fix handling extra optionals in TryMember() third arg
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/extra_opt_try_member.cfg
  ydb/library/yql/tests/sql/suites/expr/extra_opt_try_member.sql
  ydb/library/yql/tests/sql/suites/expr/pg_try_member.cfg
  ydb/library/yql/tests/sql/suites/expr/pg_try_member.sql
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
Labels: area/yql, bugfix

#4414 Fix use full column id and view at the same time.
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: area/yql, bugfix

#4420 Stabilize tpcds q67 results
  ydb/library/benchmarks/queries/tpcds/yql/q67.sql
  ydb/library/benchmarks/queries/tpcds/yql/q89.sql
Labels: not-for-changelog

#4421 Stabilize tpcds q18 results
  ydb/library/benchmarks/queries/tpcds/pg/q18.sql
  ydb/library/benchmarks/queries/tpcds/yql/q18.sql
Labels: not-for-changelog

#4067 Count cache hits and misses
  ydb/core/tablet/tablet_counters_aggregator.cpp
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor_counters.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
Labels: not-for-changelog

#4422 Stabilize tpcds q77 results
  ydb/library/benchmarks/queries/tpcds/pg/q77.sql
  ydb/library/benchmarks/queries/tpcds/yql/q77.sql
Labels: not-for-changelog

#4423 Stabilize tpcds q75 results
  ydb/library/benchmarks/queries/tpcds/yql/q75.sql
Labels: not-for-changelog

#4428 convert timestamp to uint64 for yql adoptation
  .github/config/muted_ya.txt
  ydb/core/kqp/runtime/kqp_scan_data.cpp
Labels: bugfix

#4368 Not null support for ReadTable key boundary
  ydb/core/engine/mkql_proto.cpp
  ydb/core/engine/mkql_proto.h
  ydb/core/engine/mkql_proto_ut.cpp
  ydb/core/grpc_services/rpc_read_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_pq.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/ut_helpers/ls_checks.cpp
  ydb/core/tx/tx_proxy/datareq.cpp
  ydb/core/tx/tx_proxy/read_table_impl.cpp
  ydb/core/tx/tx_proxy/resolvereq.cpp
  ydb/services/ydb/ydb_table_ut.cpp
Labels: bugfix

#4429 advance time of metrics aggregates
  ydb/core/mind/hive/tablet_info.cpp
  ydb/core/util/metrics.h
Labels: bugfix

#4406 ci: restore test_type support
  .github/actions/build_and_test_ya/action.yml
  .github/actions/test_ya/action.yml
  .github/workflows/build_and_test_ya.yml
  .github/workflows/postcommit_asan.yml
  .github/workflows/postcommit_relwithdebinfo.yml
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#4439 Fix whitespace
  ydb/tools/cfg/walle/walle.py
Labels: bugfix

#4416 [YQL-17700][refactoring] Improve EnsureStructOrOptionalStructType()
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/core/type_ann/type_ann_types.cpp
  ydb/library/yql/core/yql_expr_type_annotation.cpp
  ydb/library/yql/core/yql_expr_type_annotation.h
Labels: area/yql, improvement

#4443 [asan] Use proper std::string constructor
  ydb/library/yql/minikql/computation/mkql_computation_node_holders_ut.cpp
Labels: area/yql, bugfix

#4390 YQ-3192 Fix validate settings fail on start
  ydb/public/sdk/cpp/client/ydb_topic/impl/read_session.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/basic_usage_ut.cpp
Labels: not-for-changelog

#4444 Enable py2 in enable_v3_new_behavior (fix build)
  ydb/public/sdk/python/enable_v3_new_behavior/ya.make
Labels: not-for-changelog

#4409 Fix VDisk log and chunk status flags logic
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_actions.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_context.h
  ydb/core/blobstorage/vdisk/common/vdisk_outofspace.h
  ydb/core/blobstorage/vdisk/common/vdisk_outofspace_ut.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_oos_logic.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_oos_tracker.cpp
Labels: bugfix

#4375 Fix flapping B-Tree tests
  ydb/core/tablet_flat/ut/ut_btree_index_iter_charge.cpp
  ydb/core/util/btree_benchmark/ya.make
Labels: not-for-changelog

#4442 Remove duplicate check added by commit c30f11a748
  ydb/core/engine/mkql_proto.cpp
Labels: bugfix

#4449 Fix static group SelfHeal bug
  ydb/core/mind/bscontroller/self_heal.cpp
Labels: bugfix

#3620 hc fallback when static group has unknown status
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: new-feature

#4190 Fix pdisk restart race on vdisk log reading
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_pdisk.cpp
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/ut_blobstorage/restart_pdisk.cpp
Labels: bugfix

#4412 YQ-3184 support create table as select in kqprun
  ydb/tests/tools/kqprun/configuration/app_config.conf
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/actors.cpp
  ydb/tests/tools/kqprun/src/actors.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: new-feature, improvement

#4464 Add decimal
  ydb/library/benchmarks/queries/tpcds/yql/q15.sql
  ydb/library/benchmarks/queries/tpcds/yql/q3.sql
  ydb/library/benchmarks/queries/tpcds/yql/q47.sql
  ydb/library/benchmarks/queries/tpcds/yql/q52.sql
  ydb/library/benchmarks/queries/tpcds/yql/q63.sql
  ydb/library/benchmarks/queries/tpcds/yql/q98.sql
Labels: not-for-changelog

#4389 Support secrets: core part
  ydb/core/protos/counters_replication.proto
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/controller_impl.h
  ydb/core/tx/replication/controller/private_events.cpp
  ydb/core/tx/replication/controller/private_events.h
  ydb/core/tx/replication/controller/replication.cpp
  ydb/core/tx/replication/controller/replication.h
  ydb/core/tx/replication/controller/secret_resolver.cpp
  ydb/core/tx/replication/controller/secret_resolver.h
  ydb/core/tx/replication/controller/tx_resolve_secret_result.cpp
  ydb/core/tx/replication/controller/ya.make
  ydb/library/services/services.proto
Labels: not-for-changelog

#4438 Allow create_pq op to be a cancelable part of multipart operation
  ydb/core/tx/schemeshard/schemeshard__operation_create_pq.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_db_changes.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_db_changes.h
Labels: improvement

#4394 Add extra note to initial-deployment.md
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
Labels: documentation

#4364 Fix hash spreading in HashPartitionConsumer
  ydb/library/yql/dq/runtime/dq_output_consumer.cpp
Labels: new-feature, improvement

#4468 [docs] suggest Ansible playbook from the installed collection
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
Labels: documentation

#4470 Add decimal
  ydb/library/benchmarks/queries/tpcds/yql/q57.sql
Labels: not-for-changelog

#4307 YDBDOCS-668: viewing logs for Ansible clusters
  ydb/docs/en/core/devops/ansible/observability/index.md
  ydb/docs/en/core/devops/ansible/observability/logging.md
  ydb/docs/en/core/devops/ansible/observability/toc_p.yaml
  ydb/docs/en/core/devops/ansible/toc_p.yaml
  ydb/docs/en/core/reference/observability/index.md
  ydb/docs/en/core/reference/observability/toc_p.yaml
  ydb/docs/ru/core/devops/ansible/observability/index.md
  ydb/docs/ru/core/devops/ansible/observability/logging.md
  ydb/docs/ru/core/devops/ansible/observability/toc_p.yaml
  ydb/docs/ru/core/devops/ansible/toc_p.yaml
  ydb/docs/ru/core/reference/observability/index.md
  ydb/docs/ru/core/reference/observability/toc_p.yaml
Labels: documentation

#4474 YDBDOCS-668: use proper playbook name
  ydb/docs/en/core/devops/ansible/observability/logging.md
  ydb/docs/ru/core/devops/ansible/observability/logging.md
Labels: documentation

#4465 Support StateStorage reconfiguration through distconf
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_resource.cpp
  ydb/core/protos/blobstorage_distributed_config.proto
Labels: new-feature

#4476 Support secrets: yql & kqp parts
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: not-for-changelog

#4405 Reimplement IFunctionTypeInfoBuilder15 via NVI
  ydb/library/yql/minikql/mkql_type_builder.cpp
  ydb/library/yql/minikql/mkql_type_builder.h
  ydb/library/yql/public/udf/arrow/udf_arrow_helpers.h
  ydb/library/yql/public/udf/udf_type_builder.h
Labels: not-for-changelog

#4477 Ansible deployment instruction fix
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
Labels: documentation

#4494 FIx accuracy
  ydb/library/benchmarks/queries/tpcds/pg/q21.sql
Labels: not-for-changelog

#4502 Comparison tpcds yql/pg
  ydb/library/benchmarks/queries/tpcds/pg/q04.sql
  ydb/library/benchmarks/queries/tpcds/pg/q26.sql
  ydb/library/benchmarks/queries/tpcds/pg/q70.sql
  ydb/library/benchmarks/queries/tpcds/yql/q15.sql
  ydb/library/benchmarks/queries/tpcds/yql/q19.sql
  ydb/library/benchmarks/queries/tpcds/yql/q23.sql
  ydb/library/benchmarks/queries/tpcds/yql/q45.sql
  ydb/library/benchmarks/queries/tpcds/yql/q62.sql
  ydb/library/benchmarks/queries/tpcds/yql/q79.sql
  ydb/library/benchmarks/queries/tpcds/yql/q8.sql
  ydb/library/benchmarks/queries/tpcds/yql/q85.sql
  ydb/library/benchmarks/queries/tpcds/yql/q99.sql
Labels: not-for-changelog

#4480 YQL-17175 added maximum memory limit reached flag
  ydb/library/yql/minikql/aligned_page_pool.cpp
  ydb/library/yql/minikql/aligned_page_pool.h
Labels: new-feature

#4506 Comparison tpcds yql/pg
  ydb/library/benchmarks/queries/tpcds/pg/q04.sql
  ydb/library/benchmarks/queries/tpcds/pg/q11.sql
Labels: not-for-changelog

#4485 Kafka new metering
  ydb/core/kafka_proxy/actors/kafka_fetch_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_produce_actor.cpp
  ydb/core/persqueue/fetch_request_actor.cpp
  ydb/core/persqueue/fetch_request_actor.h
  ydb/core/persqueue/writer/writer.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/msgbus_pq.proto
Labels: not-for-changelog, new-feature

#4492 SecureDebugString() helper
  ydb/core/persqueue/partition_monitoring.cpp
  ydb/core/tx/replication/common/sensitive_event_pb.h
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/tx_proxy/schemereq.cpp
  ydb/library/grpc/server/logger.h
  ydb/library/protobuf_printer/security_printer.h
Labels: not-for-changelog

#4496 CalculateKeyBytes operator precedence fix
  ydb/core/tx/datashard/datashard_user_db.cpp
Labels: bugfix

#4516 Tests are temporarily disabled
  .github/config/muted_ya.txt
Labels: bugfix

#4489 transactions propose phase preparing to async
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.h
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/transactions/operators/backup.h
  ydb/core/tx/columnshard/transactions/operators/schema.h
  ydb/core/tx/columnshard/transactions/propose_transaction_base.cpp
  ydb/core/tx/columnshard/transactions/propose_transaction_base.h
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.h
  ydb/core/tx/columnshard/transactions/ya.make
Labels: improvement

#4299 YQ-3079 fix drop results after forget retry
  ydb/core/fq/libs/actors/run_actor.cpp
  ydb/core/fq/libs/compute/ydb/finalizer_actor.cpp
  ydb/core/fq/libs/compute/ydb/result_writer_actor.cpp
  ydb/core/fq/libs/control_plane_storage/internal/task_ping.cpp
Labels: bugfix

#4501 Drop passthrough constraint
  ydb/library/yql/ast/yql_constraint.cpp
  ydb/library/yql/ast/yql_constraint.h
  ydb/library/yql/core/ut/yql_expr_constraint_ut.cpp
  ydb/library/yql/core/yql_expr_constraint.cpp
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-4
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-5
  ydb/tests/functional/clickbench/canondata/test.test_plans_row_/queries-original-plan-row-4
  ydb/tests/functional/clickbench/canondata/test.test_plans_row_/queries-original-plan-row-5
Labels: area/yql, not-for-changelog

#4521 Comparison tpcds yql/pg
  ydb/library/benchmarks/queries/tpcds/pg/q33.sql
  ydb/library/benchmarks/queries/tpcds/pg/q49.sql
  ydb/library/benchmarks/queries/tpcds/pg/q64.sql
  ydb/library/benchmarks/queries/tpcds/pg/q66.sql
  ydb/library/benchmarks/queries/tpcds/pg/q74.sql
  ydb/library/benchmarks/queries/tpcds/pg/q79.sql
  ydb/library/benchmarks/queries/tpcds/pg/q80.sql
  ydb/library/benchmarks/queries/tpcds/pg/q82.sql
  ydb/library/benchmarks/queries/tpcds/pg/q85.sql
  ydb/library/benchmarks/queries/tpcds/pg/q88.sql
Labels: not-for-changelog

#4519 Add binary size stats
  .github/actions/build_ya/action.yml
  .github/actions/setup_ci_ydb_service_account_key_file_credentials/action.yml
  .github/scripts/send_build_stats.py
  .github/workflows/acceptance_run.yml
  .github/workflows/build_and_test_ya.yml
  .github/workflows/postcommit_asan.yml
  .github/workflows/postcommit_relwithdebinfo.yml
Labels: not-for-changelog

#4522 Cast to decimal
  ydb/library/benchmarks/queries/tpcds/yql/q49.sql
Labels: not-for-changelog

#4491 cast has been fixed for ArrowTypeAsYqlDatetime
  ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.cpp
Labels: bugfix

#4510 Refactor memory tracking
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/node_service/kqp_node_state.h
  ydb/core/kqp/node_service/kqp_node_ut.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
Labels: not-for-changelog

#3591 add link to python topic examples
  ydb/docs/en/core/reference/ydb-sdk/topic.md
  ydb/docs/ru/core/reference/ydb-sdk/topic.md
Labels: documentation

#4505 Fix a bug in additional YPath attrs deserialization
  ydb/library/yql/providers/yt/gateway/lib/yt_helpers.cpp
Labels: area/yql, bugfix

#4500 Added group id for vdisks in PDisk http page
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_http.cpp
Labels: improvement

#4458 Changed http title with decimal GroupID
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeletonfront.cpp
Labels: improvement

#4450 hc hive sync status
  ydb/core/health_check/health_check.cpp
Labels: bugfix

#4528 YDBDOCS-653: restore minikube quickstart instructions
  ydb/docs/en/core/quickstart.md
  ydb/docs/ru/core/quickstart.md
Labels: documentation
