Repository ydb-platform/ydb, pull requests merged in 2024-06, with the labels that each got.

#4934 add techinternals ydb vs. tpcc presentation
  ydb/docs/en/core/public-materials/_includes/conferences/2024/TechInternals.md
  ydb/docs/en/core/public-materials/videos.md
Labels: documentation

#4981 Add Bondars PB from True Tech 2024
  ydb/docs/ru/core/public-materials/_includes/conferences/2024/True_Tech.md
  ydb/docs/ru/core/public-materials/videos.md
Labels: documentation

#5077 move ydb-tech-ci cloud deploy manifests into ydb/ci folder
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/ansible.cfg
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/bazel-remote.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/host_vars/cachesrv.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/hosts.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/roles/bazel-remote/defaults/main.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/roles/bazel-remote/handlers/main.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/roles/bazel-remote/tasks/htpasswd.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/roles/bazel-remote/tasks/main.yaml
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/roles/bazel-remote/templates/bazel-remote.service.j2
  ydb/ci/ydb-ci-cloud/ansible/ydb-ci-cloud/roles/bazel-remote/templates/bazel-remote.yaml.j2
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/.gitignore
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/.terraform.lock.hcl
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/README.md
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/ansible-vault.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/cachesrv.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/get-backend-configuration.sh
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/clickhouse.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/controller.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/logging.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/outputs.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/providers.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/secrets.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/variables.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gh-runner/webhook.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/github-sa.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/gw.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/instance-metadata.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/main.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/net.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/outputs.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/providers.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/registry.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/s3-ydb-gh-canondata.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/s3-ydb-gh-logs.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/secrets.tf
  ydb/ci/ydb-ci-cloud/terraform/ydb-ci-cloud/variables.tf
Labels: not-for-changelog

#5064 YDB FQ: integration tests for YDB as an external data source
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/collection.py
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/init/01_basic.sh
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/select_positive.py
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/test.py
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/ya.make
  ydb/library/yql/providers/generic/connector/tests/join/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/join/scenario.py
  ydb/library/yql/providers/generic/connector/tests/utils/comparator.py
  ydb/library/yql/providers/generic/connector/tests/utils/database.py
  ydb/library/yql/providers/generic/connector/tests/utils/run/dqrun.py
  ydb/library/yql/providers/generic/connector/tests/utils/run/kqprun.py
  ydb/library/yql/providers/generic/connector/tests/utils/scenario/clickhouse.py
  ydb/library/yql/providers/generic/connector/tests/utils/scenario/postgresql.py
  ydb/library/yql/providers/generic/connector/tests/utils/scenario/ydb.py
  ydb/library/yql/providers/generic/connector/tests/utils/types/ydb.py
Labels: not-for-changelog

#5107 fix signals about blob size distribution
  ydb/core/tx/columnshard/counters/engine_logs.cpp
Labels: bugfix

#5060 tiers info initialization fix
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/columnshard/tables_manager.h
Labels: improvement

#5086 Allow untag for optional tagged types & null
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/core/yql_expr_type_annotation.cpp
  ydb/library/yql/core/yql_expr_type_annotation.h
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/expr/untag.sql
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
Labels: improvement

#5112 Fix VDisk chunks leaking in runtime
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcommit.h
  ydb/core/blobstorage/vdisk/hullop/hullcompdelete/blobstorage_hullcompdelete.h
Labels: bugfix

#4968 Add logs for changing spilling states
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
Labels: not-for-changelog

#5111 Fixed backward compatibility in fq-proxy result_writer_actor
  ydb/core/fq/libs/compute/ydb/result_writer_actor.cpp
Labels: not-for-changelog, new-feature

#5108 don't start actualization tasks construction so often
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/tiering/tiering.cpp
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/engines/storage/storage.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: performance

#5118 More cases for data->pg conversions
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/core/yql_expr_type_annotation.cpp
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/interface/utils.h
  ydb/library/yql/sql/pg_dummy/pg_sql_dummy.cpp
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/all_data.cfg
  ydb/library/yql/tests/sql/suites/pg/all_data.sql
  ydb/library/yql/tests/sql/suites/pg/all_data.txt
  ydb/library/yql/tests/sql/suites/pg/all_data.txt.attr
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: improvement

#5132 Put build analytics results in GITHUB_STEP_SUMMARY
  .github/actions/build_analytics/action.yml
Labels: not-for-changelog

#5134 Fix quotes in action
  .github/actions/build_analytics/action.yml
Labels: not-for-changelog

#5129 [YQL-18511] Fix GROUPING + CASE
  ydb/library/yql/sql/v1/sql_expression.cpp
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/aggregate/yql-18511.cfg
  ydb/library/yql/tests/sql/suites/aggregate/yql-18511.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
Labels: area/yql, bugfix

#5133 Filter modules only in ydb
  .github/scripts/graph_compare.sh
Labels: not-for-changelog

#5142 [YQL-18511] Fix GROUPING + CASE (merge to stable)
  ydb/library/yql/sql/v1/sql_expression.cpp
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/aggregate/yql-18511.cfg
  ydb/library/yql/tests/sql/suites/aggregate/yql-18511.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
Labels: area/yql

#5126 Stop replication workers
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/controller_impl.h
  ydb/core/tx/replication/controller/private_events.cpp
  ydb/core/tx/replication/controller/private_events.h
  ydb/core/tx/replication/controller/replication.h
  ydb/core/tx/replication/controller/session_info.cpp
  ydb/core/tx/replication/controller/session_info.h
  ydb/core/tx/replication/controller/target_base.cpp
  ydb/core/tx/replication/controller/target_base.h
  ydb/core/tx/replication/controller/target_with_stream.cpp
  ydb/core/tx/replication/service/service.cpp
  ydb/core/tx/replication/service/service.h
Labels: not-for-changelog

#5123 tiering waiting index policy simplification to use instants directly
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.cpp
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/tiering/tiering.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/tiering/tiering.h
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
Labels: improvement

#5146 [YQL-18511] Detect GROUPING() column count mismatch (merge to stable)
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/source.cpp
  ydb/library/yql/sql/v1/source.h
Labels: area/yql

#4909 [docs/experiment] edit "ru" articles about Ansible
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/en/core/devops/ansible/restart.md
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/ansible/observability/index.md
  ydb/docs/ru/core/devops/ansible/observability/logging.md
  ydb/docs/ru/core/devops/ansible/preparing-vms-with-terraform.md
  ydb/docs/ru/core/devops/ansible/restart.md
  ydb/docs/ru/core/devops/ansible/update-config.md
Labels: documentation

#5138 switch on normalizer state
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/data_locks/manager/manager.cpp
  ydb/core/tx/columnshard/data_locks/manager/manager.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/transactions/tx_controller.h
Labels: improvement

#5104 [docs] change ydb variable to "YDB"
  ydb/docs/presets.yaml
Labels: documentation

#5144 nth_value window function (+pg syntax)
  ydb/library/yql/core/common_opt/yql_co_pgselect.cpp
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/mount/lib/yql/window.yql
  ydb/library/yql/sql/v1/aggregation.cpp
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/select_win_nth_value.sql
  ydb/library/yql/tests/sql/suites/window/win_func_nth_value.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
Labels: area/yql, new-feature, area/pg

#5131 YDB FQ: support Microsoft SQL Server as the external data source
  ydb/core/external_sources/external_source_factory.cpp
  ydb/library/yql/providers/common/db_id_async_resolver/db_async_resolver.h
  ydb/library/yql/providers/generic/actors/yql_generic_provider_factories.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
Labels: new-feature, external

#5148 update vslot sysview on pdisk disconnect
  ydb/core/mind/bscontroller/register_node.cpp
Labels: bugfix

#4850 allow alter config in replication
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.cpp
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/replication.cpp
  ydb/core/tx/replication/controller/replication.h
  ydb/core/tx/replication/controller/tx_alter_replication.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_replication.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
Labels: improvement

#5139 fix(http_proxy): actually perform DNS resolution when entry is stale
  ydb/library/actors/http/http_proxy.cpp
Labels: bugfix

#5159 Operator precedence
  ydb/core/persqueue/pq_l2_cache.h
Labels: bugfix

#5130 More compile stats
  ydb/ci/build_bloat/main.py
  ydb/ci/build_bloat/ydb_upload.py
Labels: not-for-changelog

#5156 Fix SysView updates from BSC
  ydb/core/mind/bscontroller/register_node.cpp
  ydb/core/mind/bscontroller/self_heal.cpp
Labels: bugfix

#5176 docs: use pull_request.head.sha for build
  .github/workflows/docs_build.yaml
Labels: not-for-changelog

#5109 YQL-18356: Refactor WideTopSort to be able use LLVM compilation
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
Labels: new-feature

#5179 Less output in build analytics
  ydb/ci/build_bloat/main.py
Labels: not-for-changelog

#5184 Mute flake KqpScheme.AlterAsyncReplication
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
Labels: not-for-changelog

#5153 Add export start and end times
  ydb/core/protos/export.proto
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_export.cpp
  ydb/core/tx/schemeshard/schemeshard_export__cancel.cpp
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/public/api/protos/out/out.cpp
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#5100 Add tpcds-100 downloader
  ydb/library/benchmarks/runner/download_files_ds_100.sh
Labels: not-for-changelog

#4790 YDB FQ: docs for YDB as an external datasource
  ydb/docs/ru/core/concepts/_includes/index/how_it_works.md
  ydb/docs/ru/core/concepts/federated_query/_assets/architecture.png
  ydb/docs/ru/core/concepts/federated_query/_includes/connector_deployment.md
  ydb/docs/ru/core/concepts/federated_query/_includes/datetime_limits.md
  ydb/docs/ru/core/concepts/federated_query/_includes/supported_requests.md
  ydb/docs/ru/core/concepts/federated_query/architecture.md
  ydb/docs/ru/core/concepts/federated_query/clickhouse.md
  ydb/docs/ru/core/concepts/federated_query/index.md
  ydb/docs/ru/core/concepts/federated_query/postgresql.md
  ydb/docs/ru/core/concepts/federated_query/toc_i.yaml
  ydb/docs/ru/core/concepts/federated_query/ydb.md
  ydb/docs/ru/core/deploy/manual/connector.md
Labels: documentation

#5010 split pool stats collector processing
  ydb/library/actors/helpers/pool_stats_collector.h
Labels: area/actorsystem, not-for-changelog

#5167 Fix autospin
  ydb/library/actors/core/activity_guard.h
  ydb/library/actors/core/actorsystem.cpp
  ydb/library/actors/core/executor_pool_base.cpp
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/executor_pool_basic.h
  ydb/library/actors/core/harmonizer.cpp
Labels: area/actorsystem, bugfix

#5163 Re-run workers
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/controller_impl.h
  ydb/core/tx/replication/controller/tx_resolve_secret_result.cpp
  ydb/core/tx/replication/service/service.cpp
  ydb/core/tx/replication/service/table_writer.cpp
  ydb/core/tx/replication/service/topic_reader.cpp
  ydb/core/tx/replication/service/worker.cpp
  ydb/core/tx/replication/service/worker.h
  ydb/core/tx/replication/service/worker_ut.cpp
Labels: not-for-changelog

#5093 vdisk evict
  ydb/core/viewer/json_handlers_vdisk.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/json_vdisk_evict.h
  ydb/core/viewer/ya.make
Labels: new-feature

#5175 gc simplification and avoid race with reduce barrier for cleanup
  ydb/core/protos/counters_columnshard.proto
  ydb/core/tx/columnshard/blobs_action/abstract/gc.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/gc.h
  ydb/core/tx/columnshard/blobs_action/abstract/storage.h
  ydb/core/tx/columnshard/blobs_action/blob_manager_db.cpp
  ydb/core/tx/columnshard/blobs_action/blob_manager_db.h
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.cpp
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/gc.cpp
  ydb/core/tx/columnshard/blobs_action/bs/gc.h
  ydb/core/tx/columnshard/blobs_action/bs/gc_actor.h
  ydb/core/tx/columnshard/blobs_action/bs/storage.cpp
  ydb/core/tx/columnshard/blobs_action/bs/storage.h
  ydb/core/tx/columnshard/blobs_action/tier/gc.h
  ydb/core/tx/columnshard/blobs_action/tier/storage.cpp
  ydb/core/tx/columnshard/blobs_action/tier/storage.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_indexed.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_indexed.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/data_sharing/manager/shared_blobs.h
Labels: improvement

#5187 zstd has been fixed
  ydb/library/yql/providers/s3/compressors/zstd.cpp
  ydb/library/yql/providers/s3/compressors/zstd.h
  ydb/tests/fq/s3/test_compression_data/unknown_frame_descriptor.json.zst
  ydb/tests/fq/s3/test_compressions.py
Labels: bugfix

#5193 Separate TGenStep class from BlobDepot and move it to common utils
  ydb/core/blob_depot/data.cpp
  ydb/core/blob_depot/defs.h
  ydb/core/blob_depot/types.h
  ydb/core/util/gen_step.cpp
  ydb/core/util/gen_step.h
  ydb/core/util/ya.make
Labels: not-for-changelog

#4655 .sys/pg_tables implementation
  ydb/core/sys_view/common/schema.cpp
  ydb/core/sys_view/common/schema.h
  ydb/core/sys_view/common/ya.make
  ydb/core/sys_view/pg_tables/pg_tables.cpp
  ydb/core/sys_view/pg_tables/pg_tables.h
  ydb/core/sys_view/pg_tables/ya.make
  ydb/core/sys_view/scan.cpp
  ydb/core/sys_view/ut_kqp.cpp
  ydb/core/sys_view/ut_kqp/ya.make
  ydb/core/sys_view/ya.make
Labels: not-for-changelog

#5191 require admin access for force operations
  ydb/core/viewer/json_pdisk_restart.h
  ydb/core/viewer/json_vdisk_evict.h
  ydb/core/viewer/viewer.cpp
  ydb/core/viewer/viewer.h
Labels: improvement

#5194 big json test has been added for different compressions
  ydb/tests/fq/s3/test_compression_data/big.json.br
  ydb/tests/fq/s3/test_compression_data/big.json.bz2
  ydb/tests/fq/s3/test_compression_data/big.json.gz
  ydb/tests/fq/s3/test_compression_data/big.json.lz4
  ydb/tests/fq/s3/test_compression_data/big.json.xz
  ydb/tests/fq/s3/test_compression_data/big.json.zst
  ydb/tests/fq/s3/test_compressions.py
Labels: not-for-changelog

#5087 YQL-18516 reduce grace join with spilling memory consumption
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.h
Labels: new-feature, bugfix

#5189 Fix build analytics (create dir)
  ydb/ci/build_bloat/main.py
Labels: not-for-changelog

#5188 Fix indirect leaks
  ydb/core/tx/replication/controller/dst_alterer.cpp
  ydb/core/tx/replication/controller/dst_alterer.h
  ydb/core/tx/replication/controller/dst_creator.cpp
  ydb/core/tx/replication/controller/dst_creator.h
  ydb/core/tx/replication/controller/dst_remover.cpp
  ydb/core/tx/replication/controller/dst_remover.h
  ydb/core/tx/replication/controller/replication.cpp
  ydb/core/tx/replication/controller/stream_creator.cpp
  ydb/core/tx/replication/controller/stream_creator.h
  ydb/core/tx/replication/controller/stream_remover.cpp
  ydb/core/tx/replication/controller/stream_remover.h
  ydb/core/tx/replication/controller/target_base.cpp
  ydb/core/tx/replication/controller/target_base.h
  ydb/core/tx/replication/controller/target_table.cpp
  ydb/core/tx/replication/controller/target_table.h
Labels: not-for-changelog

#5200 Added lost file
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
Labels: not-for-changelog

#5124 add test for ddl with explicit transaction
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: improvement

#5192 Add support for named args in ICallableTypeBuilder
  ydb/library/yql/minikql/mkql_type_builder.cpp
  ydb/library/yql/public/udf/udf_type_builder.h
  ydb/library/yql/public/udf/udf_version.h
  ydb/library/yql/udfs/examples/callables/callables_udf.cpp
  ydb/library/yql/udfs/examples/callables/test/canondata/result.json
  ydb/library/yql/udfs/examples/callables/test/canondata/test.test_TestReturnNamedArgCallable_/results.txt
  ydb/library/yql/udfs/examples/callables/test/cases/TestReturnNamedArgCallable.sql
  ydb/library/yql/udfs/examples/callables/test/ya.make
  ydb/library/yql/udfs/examples/callables/ya.make
Labels: improvement

#5069 quota and consumption for hdd storage types
  ydb/core/viewer/json_tenantinfo.h
  ydb/core/viewer/protos/viewer.proto
Labels: new-feature, improvement

#4795 Add docs for ListTop builtins
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/list.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/list.md
Labels: documentation

#5212 Remove cross join from grace join and add assert (crossjoin must be processed in optimizers)
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join_imp.cpp
Labels: not-for-changelog

#5067 errors in case of exec have been processed
  ydb/core/fq/libs/common/util.h
  ydb/core/fq/libs/control_plane_config/control_plane_config.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_quotas.cpp
  ydb/core/fq/libs/quota_manager/quota_manager.cpp
Labels: bugfix

#5217 Handle worker error
  ydb/core/protos/counters_replication.proto
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/controller_impl.h
  ydb/core/tx/replication/controller/tx_worker_error.cpp
  ydb/core/tx/replication/controller/ya.make
  ydb/core/tx/replication/service/service.cpp
  ydb/core/tx/replication/service/service.h
  ydb/core/tx/replication/service/table_writer.cpp
  ydb/core/tx/replication/service/topic_reader.cpp
  ydb/core/tx/replication/service/worker.cpp
  ydb/core/tx/replication/service/worker.h
Labels: not-for-changelog

#5048 Support CompactNamedExprs mode
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/context.cpp
  ydb/library/yql/sql/v1/context.h
  ydb/library/yql/sql/v1/join.cpp
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/select.cpp
  ydb/library/yql/sql/v1/sql_call_expr.cpp
  ydb/library/yql/sql/v1/sql_expression.cpp
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_translation.h
  ydb/library/yql/sql/v1/sql_ut.cpp
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/action/action_eval_cluster_use_compact_named_exprs.cfg
  ydb/library/yql/tests/sql/suites/action/action_eval_cluster_use_compact_named_exprs.sql
  ydb/library/yql/tests/sql/suites/binding/compact_named_exprs.cfg
  ydb/library/yql/tests/sql/suites/binding/compact_named_exprs.sql
  ydb/library/yql/tests/sql/suites/binding/compact_named_subq_actions.cfg
  ydb/library/yql/tests/sql/suites/binding/compact_named_subq_actions.sql
  ydb/library/yql/tests/sql/suites/binding/compact_named_with_subq_contexts.cfg
  ydb/library/yql/tests/sql/suites/binding/compact_named_with_subq_contexts.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
Labels: area/yql, improvement

#5228 Fix PDisk FAULTY status in CMS UI
  ydb/core/cms/ui/sentinel_state.js
Labels: bugfix

#5236 [backups] add incremetnal backup to offload config
  ydb/core/protos/pqconfig.proto
  ydb/core/tx/schemeshard/schemeshard__operation_alter_continuous_backup.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_pq.cpp
  ydb/core/tx/schemeshard/ut_continuous_backup/ut_continuous_backup.cpp
  ydb/core/tx/schemeshard/ut_helpers/ls_checks.cpp
  ydb/core/tx/schemeshard/ut_helpers/ls_checks.h
Labels: not-for-changelog

#5215 Create one spill file per Sort task
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
Labels: area/yql, improvement

#5241 cleanup
  ydb/core/fq/libs/common/util.h
Labels: not-for-changelog

#5248 Drop replication with unknown secret
  ydb/core/tx/replication/controller/replication.cpp
  ydb/core/tx/schemeshard/ut_replication/ut_replication.cpp
Labels: not-for-changelog

#5240 Propagate error
  ydb/core/grpc_services/rpc_replication.cpp
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/tx_alter_dst_result.cpp
  ydb/core/tx/replication/controller/tx_create_dst_result.cpp
  ydb/core/tx/replication/controller/tx_create_stream_result.cpp
  ydb/core/tx/replication/controller/tx_describe_replication.cpp
  ydb/core/tx/replication/controller/tx_worker_error.cpp
  ydb/public/api/protos/draft/ydb_replication.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/sdk/cpp/client/draft/ydb_replication.cpp
  ydb/public/sdk/cpp/client/draft/ydb_replication.h
Labels: not-for-changelog

#5218 fix race on gc data writing
  ydb/core/tx/columnshard/blobs_action/abstract/gc.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/read.h
  ydb/core/tx/columnshard/blobs_action/blob_manager_db.cpp
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.cpp
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/write.cpp
  ydb/core/tx/columnshard/blobs_action/bs/write.h
  ydb/core/tx/columnshard/blobs_action/tier/gc_actor.cpp
  ydb/core/tx/columnshard/blobs_action/tier/gc_info.h
  ydb/core/tx/columnshard/blobs_action/tier/storage.cpp
  ydb/core/tx/columnshard/blobs_reader/task.h
  ydb/library/services/services.proto
Labels: improvement

#5198 compress script has been added
  ydb/tests/fq/s3/test_compression_data/compress.sh
Labels: not-for-changelog

#5147 new converters have been added
  ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.cpp
  ydb/tests/fq/s3/test_format_setting.py
Labels: new-feature

#5247 Implemented two pass window functions
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/library/yql/core/common_opt/yql_co_flow2.cpp
  ydb/library/yql/core/common_opt/yql_co_pgselect.cpp
  ydb/library/yql/core/peephole_opt/yql_opt_peephole_physical.cpp
  ydb/library/yql/core/services/yql_lineage.cpp
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/core/type_ann/type_ann_list.cpp
  ydb/library/yql/core/type_ann/type_ann_list.h
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/core/yql_opt_window.cpp
  ydb/library/yql/core/yql_opt_window.h
  ydb/library/yql/dq/opt/dq_opt_log.cpp
  ydb/library/yql/dq/opt/dq_opt_log.h
  ydb/library/yql/providers/dq/opt/logical_optimize.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_logical_optimize.cpp
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/select_win_cume_dist.sql
  ydb/library/yql/tests/sql/suites/pg/select_win_ntile.sql
  ydb/library/yql/tests/sql/suites/pg/select_win_percent_rank.sql
  ydb/library/yql/tests/sql/suites/window/win_func_cume_dist.sql
  ydb/library/yql/tests/sql/suites/window/win_func_ntile.sql
  ydb/library/yql/tests/sql/suites/window/win_func_percent_rank.sql
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: area/yql, new-feature, area/pg

#5266 Do not write an error if ydbd not present
  .github/scripts/send_build_stats.py
Labels: not-for-changelog

#5227 Support dynamic node configuration updates through NodeWarden
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/nodewarden/bind_queue.h
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
  ydb/core/blobstorage/nodewarden/distconf_dynamic.cpp
  ydb/core/blobstorage/nodewarden/distconf_mon.cpp
  ydb/core/blobstorage/nodewarden/node_warden_events.h
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/ya.make
  ydb/core/protos/blobstorage_distributed_config.proto
Labels: improvement

#5233 hive metastore ut has been fixed
  ydb/core/external_sources/hive_metastore/ut/hive_metastore_client_ut.cpp
Labels: not-for-changelog

#5257 new pdisk/status handler to change pdisk statuses
  ydb/core/viewer/json_handlers_pdisk.cpp
  ydb/core/viewer/json_pdisk_restart.h
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/pdisk_info.h
  ydb/core/viewer/pdisk_status.h
  ydb/core/viewer/viewer.cpp
  ydb/core/viewer/viewer.h
  ydb/core/viewer/ya.make
Labels: new-feature

#5251 [backups] add local partition reader draft
  ydb/core/backup/impl/local_partition_reader.cpp
  ydb/core/backup/impl/local_partition_reader.h
  ydb/core/backup/impl/local_partition_reader_ut.cpp
  ydb/core/backup/impl/logging.h
  ydb/core/backup/impl/ut_local_partition_reader/ya.make
  ydb/core/backup/impl/ya.make
  ydb/core/backup/ya.make
  ydb/core/base/services_assert.cpp
  ydb/library/services/services.proto
Labels: not-for-changelog

#5276 Add LLVM support to Grace Join with spilling
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
Labels: new-feature

#5285 add MaximumDisksPerNode parameter
  ydb/core/viewer/json_nodes.h
  ydb/core/viewer/protos/viewer.proto
Labels: new-feature

#5301 Revert to the initial behavour in order to reduce huge memory consump…
  ydb/library/yql/minikql/comp_nodes/mkql_grace_join.cpp
Labels: not-for-changelog

#5166 Move QueryStatus handle to Executer Actor
  ydb/library/yql/providers/dq/actors/executer_actor.cpp
  ydb/library/yql/providers/dq/api/protos/service.proto
  ydb/library/yql/providers/dq/global_worker_manager/global_worker_manager.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.cpp
  ydb/library/yql/providers/dq/service/grpc_service.cpp
  ydb/library/yql/providers/dq/service/grpc_session.cpp
  ydb/library/yql/providers/dq/service/grpc_session.h
Labels: not-for-changelog

#5304 fix inf scan
  ydb/core/formats/arrow/reader/position.h
Labels: bugfix

#5260 fix [0] access for empty arrayRef
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: not-for-changelog

#5273 Fix event processing time counter
  ydb/library/actors/core/worker_context.h
Labels: area/actorsystem, bugfix

#5303 Ansi mode for CumeDist
  ydb/library/yql/core/common_opt/yql_co_flow2.cpp
  ydb/library/yql/core/common_opt/yql_co_pgselect.cpp
  ydb/library/yql/core/common_opt/yql_co_simple1.cpp
  ydb/library/yql/core/type_ann/type_ann_core.cpp
  ydb/library/yql/core/type_ann/type_ann_list.cpp
  ydb/library/yql/core/type_ann/type_ann_list.h
  ydb/library/yql/core/yql_opt_window.cpp
  ydb/library/yql/sql/v1/builtin.cpp
  ydb/library/yql/sql/v1/node.cpp
  ydb/library/yql/sql/v1/node.h
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/select_win_cume_dist.sql
  ydb/library/yql/tests/sql/suites/window/win_func_cume_dist_ansi.sql
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
Labels: area/yql, new-feature, area/pg

#5311 Add test timer into ut_group to prevent it from timing out
  ydb/core/blobstorage/ut_group/main.cpp
Labels: not-for-changelog

#5316 Refactor tests for activation queues
  ydb/library/actors/queues/bench/bench_cases.h
  ydb/library/actors/queues/bench/defs.h
  ydb/library/actors/queues/bench/main.cpp
  ydb/library/actors/queues/bench/queue.h
  ydb/library/actors/queues/bench/worker.h
  ydb/library/actors/queues/bench/ya.make
  ydb/library/actors/queues/mpmc_ring_queue_ut_multi_threads.cpp
  ydb/library/actors/queues/mpmc_ring_queue_ut_single_thread.cpp
Labels: area/actorsystem, not-for-changelog

#5279 global mute for external sources ut
  .github/config/muted_ya.txt
Labels: not-for-changelog

#4793 curl aws signature has been fixed
  ydb/core/external_sources/s3/ut/docker-compose.yml
  ydb/core/external_sources/s3/ut/s3_aws_credentials_ut.cpp
  ydb/core/external_sources/s3/ut/test.json
  ydb/core/external_sources/s3/ut/ya.make
  ydb/core/external_sources/s3/ya.make
  ydb/library/yql/providers/common/http_gateway/ut/ya.make
  ydb/library/yql/providers/common/http_gateway/ya.make
  ydb/library/yql/providers/common/http_gateway/yql_aws_signature.cpp
  ydb/library/yql/providers/common/http_gateway/yql_aws_signature.h
  ydb/library/yql/providers/common/http_gateway/yql_aws_signature_ut.cpp
  ydb/library/yql/providers/common/http_gateway/yql_http_gateway.cpp
  ydb/library/yql/providers/common/http_gateway/yql_http_header.h
Labels: bugfix

#5339 fix when limit per node logic assigns incorrect shard hints in single shard scenario
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/runtime/kqp_read_actor.cpp
Labels: bugfix

#5332 Sync FieldSubsetEnableMultiusage,UseFastPickleTransport with prod settings
  ydb/library/yql/cfg/tests/gateways.conf
  ydb/library/yql/tests/s-expressions/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: area/yql, bugfix

#5334 speed up logic for slices and enqueueBP run
  ydb/core/tx/columnshard/blobs_action/transaction/tx_gc_insert_table.cpp
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/common/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/logic/slices/logic.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/logic/slices/logic.h
Labels: performance

#5333 Pass dq metrics to progressWriter
  ydb/library/yql/providers/dq/actors/executer_actor.cpp
  ydb/library/yql/providers/dq/provider/exec/yql_dq_exectransformer.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.cpp
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.h
Labels: not-for-changelog

#5347 code clarifying for coverity
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
Labels: not-for-changelog

#5343 improve normalizers control in local db
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/normalizer/abstract/abstract.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/portion/broken_blobs.cpp
Labels: improvement

#5315 Remarks about absence of secondary vector index
  ydb/docs/en/core/yql/reference/yql-core/udf/list/knn.md
  ydb/docs/ru/core/yql/reference/yql-core/udf/list/knn.md
Labels: documentation

#5335 Remove pqconfig.pb.h from appdata
  ydb/core/base/appdata.h
  ydb/core/blobstorage/backpressure/queue_backpressure_client_ut.cpp
  ydb/core/blobstorage/dsproxy/ut_fat/dsproxy_ut.cpp
  ydb/core/blobstorage/dsproxy/ut_ftol/dsproxy_fault_tolerance_ut.cpp
  ydb/core/blobstorage/incrhuge/ut/incrhuge_basic_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_driveestimator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_tools.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_helpers.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_races.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_run.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_sectormap.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_ut.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_bsc.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_pipe.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_state.cpp
  ydb/core/blobstorage/ut_group/main.cpp
  ydb/core/blobstorage/ut_mirror3of4/main.cpp
  ydb/core/blobstorage/ut_pdiskfit/pdiskfit/pdiskfit.cpp
  ydb/core/blobstorage/ut_pdiskfit/ut/main.cpp
  ydb/core/blobstorage/ut_testshard/main.cpp
  ydb/core/blobstorage/ut_vdisk/lib/prepare.cpp
  ydb/core/blobstorage/ut_vdisk/mon_reregister_ut.cpp
  ydb/core/blobstorage/ut_vdisk2/huge.cpp
  ydb/core/control/immediate_control_board_actor_ut.cpp
  ydb/core/external_sources/object_storage/inference/ut/arrow_inference_ut.cpp
  ydb/core/keyvalue/keyvalue_storage_read_request_ut.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.cpp
  ydb/core/mind/bscontroller/ut_selfheal/main.cpp
  ydb/core/mind/bscontroller/ut_selfheal/self_heal_actor_ut.cpp
  ydb/core/persqueue/events/global.h
  ydb/core/sys_view/partition_stats/partition_stats_ut.cpp
  ydb/core/tablet_flat/datetime_ut.cpp
  ydb/core/tablet_flat/decimal_ut.cpp
  ydb/core/tablet_flat/flat_executor_database_ut.cpp
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_executor_ut_large.cpp
  ydb/core/tablet_flat/ut/ut_rename_table_column.cpp
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/actors/test_runtime_ut.cpp
  ydb/core/testlib/basics/runtime.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/util/single_thread_ic_mock.cpp
  ydb/core/util/testactorsys.cpp
  ydb/library/ncloud/impl/access_service_ut.cpp
  ydb/services/persqueue_cluster_discovery/cluster_discovery_service.cpp
  ydb/services/persqueue_cluster_discovery/grpc_service.cpp
Labels: not-for-changelog

#5355 fix TString init to avoid overrun
  ydb/core/persqueue/ut/partition_ut.cpp
Labels: not-for-changelog

#5353 remove ydb/core/wrappers/ut_helpers from ydbd
  ydb/core/wrappers/ya.make
Labels: not-for-changelog

#5344 fix replicas terminating
  ydb/core/blobstorage/nodewarden/node_warden_resource.cpp
Labels: new-feature

#5345 init scalar field of TPartitionFamily
  ydb/core/persqueue/read_balancer__balancing.h
Labels: bugfix

#3573 Write documentation on distributed transactions YDBDOCS-429
  ydb/docs/en/core/contributor/datashard-distributed-txs.md
  ydb/docs/en/core/contributor/toc_i.yaml
  ydb/docs/ru/core/contributor/datashard-distributed-txs.md
  ydb/docs/ru/core/contributor/toc_i.yaml
Labels: documentation

#5367 Refactor TAppData instantiation code
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/blobstorage/backpressure/queue_backpressure_client_ut.cpp
  ydb/core/blobstorage/dsproxy/ut_fat/dsproxy_ut.cpp
  ydb/core/blobstorage/dsproxy/ut_ftol/dsproxy_fault_tolerance_ut.cpp
  ydb/core/blobstorage/incrhuge/ut/incrhuge_basic_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_driveestimator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_tools.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_helpers.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_races.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_run.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_sectormap.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_ut.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_bsc.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_pipe.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_state.cpp
  ydb/core/blobstorage/ut_group/main.cpp
  ydb/core/blobstorage/ut_mirror3of4/main.cpp
  ydb/core/blobstorage/ut_pdiskfit/pdiskfit/pdiskfit.cpp
  ydb/core/blobstorage/ut_pdiskfit/ut/main.cpp
  ydb/core/blobstorage/ut_testshard/main.cpp
  ydb/core/blobstorage/ut_vdisk/lib/prepare.cpp
  ydb/core/blobstorage/ut_vdisk/mon_reregister_ut.cpp
  ydb/core/blobstorage/ut_vdisk2/huge.cpp
  ydb/core/cms/console/shared_cache_configurator.cpp
  ydb/core/control/immediate_control_board_actor_ut.cpp
  ydb/core/driver_lib/run/run.cpp
  ydb/core/external_sources/object_storage/inference/ut/arrow_inference_ut.cpp
  ydb/core/keyvalue/keyvalue_storage_read_request_ut.cpp
  ydb/core/mind/bscontroller/ut_selfheal/main.cpp
  ydb/core/mind/bscontroller/ut_selfheal/self_heal_actor_ut.cpp
  ydb/core/sys_view/partition_stats/partition_stats_ut.cpp
  ydb/core/tablet_flat/datetime_ut.cpp
  ydb/core/tablet_flat/decimal_ut.cpp
  ydb/core/tablet_flat/flat_executor_database_ut.cpp
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_executor_ut_large.cpp
  ydb/core/tablet_flat/ut/ut_rename_table_column.cpp
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
  ydb/core/testlib/actors/test_runtime_ut.cpp
  ydb/core/testlib/basics/runtime.cpp
  ydb/core/util/single_thread_ic_mock.cpp
  ydb/core/util/testactorsys.cpp
  ydb/library/ncloud/impl/access_service_ut.cpp
Labels: not-for-changelog

#5314 Prepare for update LLVM part. Split TopSort node on Top and Sort.
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
Labels: area/yql

#5372 fix volatile configs in ui
  ydb/core/cms/ui/yaml_config.js
Labels: not-for-changelog

#5361 fix calculation of label 'dynamic'
  ydb/core/config/init/init_impl.h
Labels: not-for-changelog

#5360 fixes for resharding tests
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/blob_set.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/blob_set.h
  ydb/core/tx/columnshard/blobs_action/abstract/gc.h
  ydb/core/tx/columnshard/blobs_action/abstract/gc_actor.h
  ydb/core/tx/columnshard/blobs_action/abstract/remove.h
  ydb/core/tx/columnshard/blobs_action/abstract/storage.h
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/gc_actor.h
  ydb/core/tx/columnshard/blobs_action/bs/storage.h
  ydb/core/tx/columnshard/blobs_action/events/delete_blobs.h
  ydb/core/tx/columnshard/blobs_action/protos/events.proto
  ydb/core/tx/columnshard/blobs_action/tier/gc_actor.h
  ydb/core/tx/columnshard/blobs_action/tier/gc_info.h
  ydb/core/tx/columnshard/blobs_action/tier/remove.cpp
  ydb/core/tx/columnshard/blobs_action/tier/remove.h
  ydb/core/tx/columnshard/blobs_action/tier/storage.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_remove_blobs.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_remove_blobs.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/data_locks/locks/abstract.h
  ydb/core/tx/columnshard/data_locks/locks/composite.h
  ydb/core/tx/columnshard/data_locks/locks/list.h
  ydb/core/tx/columnshard/data_locks/locks/snapshot.h
  ydb/core/tx/columnshard/data_locks/manager/manager.cpp
  ydb/core/tx/columnshard/data_locks/manager/manager.h
  ydb/core/tx/columnshard/data_sharing/common/session/common.cpp
  ydb/core/tx/columnshard/data_sharing/common/session/common.h
  ydb/core/tx/columnshard/data_sharing/destination/events/transfer.cpp
  ydb/core/tx/columnshard/data_sharing/destination/events/transfer.h
  ydb/core/tx/columnshard/data_sharing/destination/session/destination.cpp
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_finish_from_source.cpp
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_start_from_initiator.cpp
  ydb/core/tx/columnshard/data_sharing/manager/sessions.cpp
  ydb/core/tx/columnshard/data_sharing/manager/sessions.h
  ydb/core/tx/columnshard/data_sharing/manager/shared_blobs.cpp
  ydb/core/tx/columnshard/data_sharing/manager/shared_blobs.h
  ydb/core/tx/columnshard/data_sharing/source/session/cursor.cpp
  ydb/core/tx/columnshard/data_sharing/source/session/cursor.h
  ydb/core/tx/columnshard/data_sharing/source/session/source.cpp
  ydb/core/tx/columnshard/data_sharing/source/session/source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_data_ack_to_source.cpp
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_to_source.cpp
  ydb/core/tx/columnshard/hooks/testing/controller.cpp
  ydb/core/tx/columnshard/hooks/testing/controller.h
Labels: improvement

#5385 channels usage for cs writing (64 by default)
  ydb/core/tx/columnshard/blobs_action/bs/address.cpp
  ydb/core/tx/columnshard/blobs_action/bs/address.h
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.cpp
  ydb/core/tx/columnshard/blobs_action/bs/blob_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/gc.cpp
  ydb/core/tx/columnshard/blobs_action/bs/gc.h
  ydb/core/tx/columnshard/blobs_action/bs/gc_actor.cpp
  ydb/core/tx/columnshard/blobs_action/bs/gc_actor.h
  ydb/core/tx/columnshard/blobs_action/bs/ya.make
  ydb/core/tx/columnshard/counters/blobs_manager.cpp
  ydb/core/tx/columnshard/counters/blobs_manager.h
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/store/store.cpp
Labels: improvement

#5364 Stable blob id generation tiers
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.h
  ydb/core/tx/columnshard/blobs_action/bs/storage.h
  ydb/core/tx/columnshard/blobs_action/storages_manager/manager.cpp
  ydb/core/tx/columnshard/blobs_action/tier/storage.cpp
  ydb/core/tx/columnshard/blobs_action/tier/storage.h
  ydb/core/tx/columnshard/blobs_action/tier/write.cpp
  ydb/core/tx/columnshard/blobs_action/tier/write.h
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/export/session/storage/s3/storage.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/helper.cpp
  ydb/core/tx/columnshard/test_helper/helper.h
Labels: improvement

#5341 [block] subtraction for datetime, interval
  ydb/library/yql/minikql/computation/mkql_block_impl.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_impl.h.txt
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_sub.cpp
  ydb/library/yql/minikql/mkql_type_builder.h
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/blocks/date_sub.cfg
  ydb/library/yql/tests/sql/suites/blocks/date_sub.sql
  ydb/library/yql/tests/sql/suites/blocks/date_sub_interval.cfg
  ydb/library/yql/tests/sql/suites/blocks/date_sub_interval.sql
  ydb/library/yql/tests/sql/suites/blocks/date_sub_interval_scalar.cfg
  ydb/library/yql/tests/sql/suites/blocks/date_sub_interval_scalar.sql
  ydb/library/yql/tests/sql/suites/blocks/date_sub_scalar.cfg
  ydb/library/yql/tests/sql/suites/blocks/date_sub_scalar.sql
  ydb/library/yql/tests/sql/suites/blocks/dates.txt
  ydb/library/yql/tests/sql/suites/blocks/dates.txt.attr
  ydb/library/yql/tests/sql/suites/blocks/interval_sub_interval.cfg
  ydb/library/yql/tests/sql/suites/blocks/interval_sub_interval.sql
  ydb/library/yql/tests/sql/suites/blocks/interval_sub_interval_scalar.cfg
  ydb/library/yql/tests/sql/suites/blocks/interval_sub_interval_scalar.sql
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
Labels: new-feature

#5155 nth_value docs
  ydb/docs/en/core/postgresql/_includes/functions.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/window/nth_value.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/window.md
  ydb/docs/ru/core/postgresql/_includes/functions.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/window/nth_value.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/window.md
Labels: documentation, area/pg

#5387 external source ut has been fixed
  ydb/core/external_sources/ya.make
Labels: not-for-changelog, new-feature

#5378 [docs] update redirects.yaml
  ydb/docs/redirects.yaml
Labels: documentation

#5393 attach to kqp session
  ydb/core/viewer/json_query.h
Labels: bugfix

#5388 Remove unneded includes from appdata.h
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata.h
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/client/server/msgbus_server_login_request.cpp
  ydb/core/cms/console/configs_dispatcher_ut.cpp
  ydb/core/cms/console/shared_cache_configurator.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_cms.cpp
  ydb/core/grpc_services/rpc_read_table.cpp
  ydb/core/grpc_services/rpc_stream_execute_scan_query.cpp
  ydb/core/grpc_services/rpc_stream_execute_yql_script.cpp
  ydb/core/http_proxy/auth_factory.cpp
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.cpp
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.h
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_actor.h
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_service.cpp
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_service.h
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/mind/configured_tablet_bootstrapper.h
  ydb/core/mon/mon.cpp
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/actors/test_runtime.h
  ydb/core/testlib/basics/appdata.cpp
  ydb/core/testlib/basics/appdata.h
  ydb/core/testlib/basics/services.cpp
  ydb/core/tx/columnshard/columnshard__scan.cpp
  ydb/core/tx/columnshard/engines/column_engine.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/index/bucket.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/sbuckets/index/bucket.h
  ydb/core/tx/columnshard/export/session/selector/backup/selector.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.cpp
  ydb/core/tx/datashard/export_s3_uploader.cpp
  ydb/core/tx/schemeshard/olap/store/store.cpp
  ydb/core/ymq/actor/auth_multi_factory.cpp
Labels: not-for-changelog

#5352 init scalar fields in serializer opts
  ydb/core/tx/datashard/change_record_cdc_serializer.h
Labels: not-for-changelog

#5292 Deterministic B-Tree histogram builder
  ydb/core/tablet_flat/flat_page_btree_index.h
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.h
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.h
  ydb/core/tablet_flat/ut/ut_stat.cpp
Labels: not-for-changelog

#5422 Disable RunOnOpt plan diff after FieldSubsetEnableMultiusage is enabled
  ydb/library/yql/tests/sql/suites/pg-tpch/q11.sql
Labels: area/yql, bugfix

#5389 Add import start and end times
  ydb/core/protos/import.proto
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_import.cpp
  ydb/core/tx/schemeshard/schemeshard_import__cancel.cpp
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/public/api/protos/out/out.cpp
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#5354 [backups] refactor change sender
  ydb/core/change_exchange/change_exchange.cpp
  ydb/core/change_exchange/change_exchange.h
  ydb/core/change_exchange/change_record.h
  ydb/core/change_exchange/change_sender_common_ops.cpp
  ydb/core/change_exchange/change_sender_common_ops.h
  ydb/core/change_exchange/change_sender_resolver.h
  ydb/core/change_exchange/ya.make
  ydb/core/scheme/scheme_tabledefs.h
  ydb/core/tx/datashard/cdc_stream_heartbeat.cpp
  ydb/core/tx/datashard/cdc_stream_scan.cpp
  ydb/core/tx/datashard/change_collector.cpp
  ydb/core/tx/datashard/change_record.h
  ydb/core/tx/datashard/change_sender_async_index.cpp
  ydb/core/tx/datashard/change_sender_cdc_stream.cpp
  ydb/core/tx/datashard/datashard_change_sending.cpp
  ydb/core/tx/datashard/datashard_ut_change_collector.cpp
  ydb/core/tx/replication/service/json_change_record.h
  ydb/core/tx/replication/service/table_writer.cpp
Labels: not-for-changelog

#5415 Two pass window functions: documentation
  ydb/docs/en/core/postgresql/_includes/functions.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/window/cume_dist.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/window/ntile.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/window/rank_dense.md
  ydb/docs/en/core/yql/reference/yql-core/builtins/window.md
  ydb/docs/ru/core/postgresql/_includes/functions.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/window/cume_dist.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/window/ntile.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/window/rank_dense.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/window.md
Labels: documentation

#5428 fixes to pdisk/info handler
  ydb/core/viewer/pdisk_info.h
Labels: bugfix

#5419 wait tables clearing before new initialization in tablet
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/data_sharing/common/context/context.cpp
  ydb/core/tx/columnshard/data_sharing/common/context/context.h
  ydb/core/tx/columnshard/data_sharing/destination/session/destination.h
  ydb/core/tx/columnshard/engines/changes/cleanup_tables.cpp
  ydb/core/tx/columnshard/subscriber/abstract/events/event.cpp
  ydb/core/tx/columnshard/subscriber/abstract/events/event.h
  ydb/core/tx/columnshard/subscriber/abstract/events/ya.make
  ydb/core/tx/columnshard/subscriber/abstract/manager/manager.cpp
  ydb/core/tx/columnshard/subscriber/abstract/manager/manager.h
  ydb/core/tx/columnshard/subscriber/abstract/manager/ya.make
  ydb/core/tx/columnshard/subscriber/abstract/subscriber/subscriber.cpp
  ydb/core/tx/columnshard/subscriber/abstract/subscriber/subscriber.h
  ydb/core/tx/columnshard/subscriber/abstract/subscriber/ya.make
  ydb/core/tx/columnshard/subscriber/abstract/ya.make
  ydb/core/tx/columnshard/subscriber/events/tables_erased/event.cpp
  ydb/core/tx/columnshard/subscriber/events/tables_erased/event.h
  ydb/core/tx/columnshard/subscriber/events/tables_erased/ya.make
  ydb/core/tx/columnshard/subscriber/events/ya.make
  ydb/core/tx/columnshard/subscriber/ya.make
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/columnshard/transactions/operators/schema.cpp
  ydb/core/tx/columnshard/transactions/operators/schema.h
  ydb/core/tx/columnshard/transactions/transactions/tx_finish_async.cpp
  ydb/core/tx/columnshard/transactions/transactions/tx_finish_async.h
  ydb/core/tx/columnshard/transactions/transactions/ya.make
  ydb/core/tx/columnshard/transactions/tx_controller.h
  ydb/core/tx/columnshard/ya.make
Labels: improvement

#5214 db metadata cache: feature flag + config
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/driver_lib/run/run.cpp
  ydb/core/grpc_services/db_metadata_cache.h
  ydb/core/protos/config.proto
  ydb/core/protos/console_config.proto
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#4989 CREATE TABLE AS with inconsistent write
  ydb/core/kqp/common/kqp_yql.cpp
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/host/kqp_type_ann.cpp
  ydb/core/kqp/opt/kqp_opt_effects.cpp
  ydb/core/kqp/opt/kqp_opt_kql.cpp
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
  ydb/library/yql/core/yql_opt_utils.cpp
  ydb/library/yql/core/yql_opt_utils.h
Labels: not-for-changelog

#5436 ci: add test log url
  .github/actions/test_ya/action.yml
  .github/scripts/tests/generate-summary.py
Labels: not-for-changelog

#5322 YQ-2824: find a file to infer types in request to directory
  ydb/core/external_sources/object_storage.cpp
  ydb/core/external_sources/object_storage/inference/arrow_inferencinator.cpp
  ydb/core/external_sources/ya.make
  ydb/core/kqp/gateway/kqp_metadata_loader.cpp
Labels: improvement

#5150 Remove the dependency on the S3 provider implementation
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/driver_lib/run/ya.make
  ydb/core/fq/libs/actors/pending_fetcher.cpp
  ydb/core/fq/libs/actors/proxy.h
  ydb/core/fq/libs/actors/run_actor.cpp
  ydb/core/fq/libs/actors/ya.make
  ydb/core/fq/libs/compute/common/run_actor_params.cpp
  ydb/core/fq/libs/compute/common/run_actor_params.h
  ydb/core/fq/libs/compute/common/ya.make
  ydb/core/fq/libs/init/init.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.h
  ydb/core/kqp/compute_actor/ya.make
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_actor.cpp
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_actor.h
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_service.cpp
  ydb/core/kqp/finalize_script_service/kqp_finalize_script_service.h
  ydb/core/kqp/finalize_script_service/ya.make
  ydb/core/kqp/host/ya.make
  ydb/core/kqp/node_service/ya.make
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service.h
  ydb/core/kqp/proxy_service/ya.make
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/common/ya.make
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/federated_query/common/common.h
  ydb/core/kqp/ut/federated_query/common/ya.make
  ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp
  ydb/core/kqp/ut/federated_query/generic_ut/ya.make
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_scheme_ut.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_s3_plan_ut.cpp
  ydb/core/kqp/ut/federated_query/s3/s3_recipe_ut_helpers.cpp
  ydb/core/kqp/ut/federated_query/s3/s3_recipe_ut_helpers.h
  ydb/core/kqp/ut/federated_query/s3/ya.make
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/core/testlib/ya.make
  ydb/library/yql/providers/s3/actors/ya.make
  ydb/library/yql/providers/s3/actors/yql_s3_actors_factory_impl.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_actors_factory_impl.h
  ydb/library/yql/providers/s3/actors/yql_s3_raw_read_actor.h
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.h
  ydb/library/yql/providers/s3/actors/yql_s3_sink_factory.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_sink_factory.h
  ydb/library/yql/providers/s3/actors/yql_s3_source_factory.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_source_factory.h
  ydb/library/yql/providers/s3/actors/yql_s3_source_queue.cpp
  ydb/library/yql/providers/s3/actors_factory/ya.make
  ydb/library/yql/providers/s3/actors_factory/yql_s3_actors_factory.cpp
  ydb/library/yql/providers/s3/actors_factory/yql_s3_actors_factory.h
  ydb/library/yql/providers/s3/provider/yql_s3_dq_integration.cpp
  ydb/library/yql/providers/s3/ya.make
  ydb/library/yql/tools/dq/worker_node/main.cpp
  ydb/library/yql/tools/dqrun/dqrun.cpp
  ydb/library/yql/tools/mrrun/mrrun.cpp
Labels: not-for-changelog

#5430 more tablets in tabletinfo by path
  ydb/core/protos/node_whiteboard.proto
  ydb/core/viewer/json_tabletinfo.h
Labels: improvement

#5433 Disable spilling in WideLastCombiner if non-serializable types are used inside
  ydb/library/yql/minikql/comp_nodes/mkql_factory.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.h
  ydb/library/yql/minikql/mkql_program_builder.cpp
  ydb/library/yql/minikql/mkql_program_builder.h
  ydb/library/yql/minikql/mkql_runtime_version.h
  ydb/library/yql/providers/common/mkql/yql_provider_mkql.cpp
Labels: area/yql, improvement

#5450 COMPOSE_HTTP_TIMEOUT has been increased to 240
  ydb/core/external_sources/hive_metastore/ut/ya.make
Labels: not-for-changelog

#5413 Added statistics override via pragma
  ydb/core/kqp/opt/kqp_statistics_transformer.cpp
  ydb/core/kqp/opt/logical/kqp_opt_cbo.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
  ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
  ydb/library/yql/core/yql_statistics.cpp
  ydb/library/yql/core/yql_statistics.h
  ydb/library/yql/dq/opt/dq_opt_predicate_selectivity.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_dq_integration.cpp
Labels: experimental-feature

#5441 Fix tsan error
  ydb/library/actors/core/mon_stats.cpp
  ydb/library/actors/core/mon_stats.h
  ydb/library/actors/core/ya.make
Labels: area/actorsystem, bugfix

#5453 [dq] Fallback selfjoin without spilling
  ydb/library/yql/providers/dq/provider/yql_dq_validate.cpp
  ydb/library/yql/tests/sql/dq_file/part3/canondata/test.test_join-selfjoin_on_sorted_with_filter-replicate-Analyze_/extracted
Labels: area/yql, not-for-changelog

#5420 Refactoring of WideCombiner for adding LLVM support
  ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp
Labels: new-feature, improvement

#5445 Use --build-all
  .github/actions/test_ya/action.yml
  .github/scripts/graph_compare.sh
Labels: not-for-changelog

#5461 metadata cache keeps merged issues
  ydb/core/grpc_services/db_metadata_cache.h
  ydb/core/grpc_services/rpc_monitoring.cpp
Labels: improvement

#5437 use proper compaction policy for SA tables
  ydb/core/statistics/aggregator/tx_init_schema.cpp
Labels: not-for-changelog

#5456 Fix connector_deployment condinions
  ydb/docs/ru/core/concepts/federated_query/_includes/connector_deployment.md
Labels: documentation

#5245 docs: change visibility in transactions
  ydb/docs/en/core/concepts/_includes/transactions.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/delete.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/update.md
  ydb/docs/ru/core/concepts/_includes/transactions.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/delete.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/update.md
Labels: documentation

#3646 First iteration of Logstash plugin docs
  ydb/docs/en/core/integrations/logstash.md
  ydb/docs/en/core/integrations/toc_i.yaml
  ydb/docs/ru/core/integrations/logstash.md
  ydb/docs/ru/core/integrations/toc_i.yaml
Labels: documentation

#5484 [docs] don't mention a file that no longer exists in Ansible instrucions
  ydb/docs/en/core/devops/ansible/_includes/repo-tree.md
  ydb/docs/ru/core/devops/ansible/_includes/repo-tree.md
Labels: documentation

#5485 [docs] add a lost step in Ansible initial deployment
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/ansible/initial-deployment.md
Labels: documentation

#5460 Update LLVM part for Sort with spiling.
  ydb/library/yql/minikql/comp_nodes/mkql_wide_top_sort.cpp
Labels: area/yql

#5090 YDB FQ: support Managed Greenplum
  ydb/core/fq/libs/actors/database_resolver.cpp
  ydb/core/fq/libs/actors/ut/database_resolver_ut.cpp
  ydb/core/fq/libs/db_id_async_resolver_impl/mdb_endpoint_generator.cpp
Labels: new-feature

#5383 Fix split by load ut
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/ut/autoscaling_ut.cpp
  ydb/core/persqueue/ut/common/autoscaling_ut_common.cpp
  ydb/core/persqueue/ut/common/autoscaling_ut_common.h
Labels: not-for-changelog

#5310 Fix build
  ydb/services/lib/actors/pq_schema_actor.cpp
Labels: not-for-changelog

#5489 Add missing WakeUp() call in dq channels spilling
  ydb/library/yql/dq/actors/spilling/channel_storage_actor.cpp
Labels: bugfix

#5298 Improve erase cache to better work with uncommitted changes
  ydb/core/tablet_flat/flat_database.cpp
  ydb/core/tablet_flat/flat_database.h
  ydb/core/tablet_flat/flat_dbase_naked.h
  ydb/core/tablet_flat/flat_iterator.h
  ydb/core/tablet_flat/flat_mem_iter.h
  ydb/core/tablet_flat/flat_part_iter.h
  ydb/core/tablet_flat/flat_range_cache.cpp
  ydb/core/tablet_flat/flat_range_cache.h
  ydb/core/tablet_flat/flat_range_cache_ut.cpp
  ydb/core/tablet_flat/flat_table.cpp
  ydb/core/tablet_flat/flat_table.h
  ydb/core/tablet_flat/flat_table_committed.cpp
  ydb/core/tablet_flat/flat_table_committed.h
  ydb/core/tablet_flat/flat_table_stats.h
  ydb/core/tablet_flat/test/libs/table/wrap_part.h
  ydb/core/tablet_flat/ut/ut_db_iface.cpp
  ydb/core/tablet_flat/ya.make
Labels: improvement

#5499 fix yql arcadia build
  ydb/library/yql/providers/s3/actors/yql_s3_sink_factory.h
  ydb/library/yql/providers/s3/actors/yql_s3_source_factory.h
Labels: not-for-changelog

#5432 fix statistics aggregator migration logic
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
Labels: not-for-changelog

#5465 json_hc metadata cache
  ydb/core/viewer/json_healthcheck.h
  ydb/core/viewer/json_pipe_req.h
Labels: new-feature, improvement
