Repository ydb-platform/ydb, pull requests merged in 2024-03, with the labels that each got.

#2341 EvWrite OverloadSubscribe
  ydb/core/tx/datashard/check_write_unit.cpp
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__op_rows.cpp
  ydb/core/tx/datashard/datashard__write.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/datashard_write_operation.h
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/execution_unit.cpp
Labels: not-for-changelog

#2217 YDB-1470 added database filter for time difference
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/health_check/health_check.cpp
  ydb/library/actors/interconnect/interconnect_common.h
  ydb/library/actors/interconnect/interconnect_tcp_session.cpp
Labels: new-feature

#2373 Preserve original join node if ForceSortedMerge=true
  ydb/library/yql/providers/yt/provider/ut/yql_yt_cbo_ut.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
Labels: not-for-changelog

#2365 Support of nulls first/last
  ydb/library/yql/core/common_opt/yql_co_pgselect.cpp
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/sql/pg/pg_sql.cpp
  ydb/library/yql/sql/settings/translation_settings.h
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/sort_nulls_priority.sql
  ydb/library/yql/tests/sql/suites/pg/sort_nulls_priority_window.sql
  ydb/library/yql/tests/sql/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: new-feature, area/pg

#2384 Remove TraceId from EvWrite tests
  ydb/core/tx/datashard/datashard_ut_trace.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: not-for-changelog

#2385 Disable CBO for unsupported link settings
  ydb/library/yql/providers/yt/provider/yql_yt_join_reorder.cpp
Labels: not-for-changelog

#2389 fix windows build
  ydb/core/tx/columnshard/blobs_action/storages_manager/manager.cpp
Labels: bugfix

#2392 add query replay tool to oss
  ydb/tools/query_replay/common_deps.inc
  ydb/tools/query_replay/main.cpp
  ydb/tools/query_replay/query_compiler.cpp
  ydb/tools/query_replay/query_proccessor.cpp
  ydb/tools/query_replay/query_replay.cpp
  ydb/tools/query_replay/query_replay.h
  ydb/tools/query_replay/ya.make
  ydb/tools/ya.make
Labels: not-for-changelog

#2387 implemented syscache RELNAMENSP
  ydb/library/yql/parser/pg_wrapper/parser.cpp
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/cache/syscache.c
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/misc/guc.c
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
  ydb/library/yql/parser/pg_wrapper/ya.make
Labels: new-feature, area/pg

#2344 YQL-17935 delete non deterministic test
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/sampling/sample.sql
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: not-for-changelog

#2406 Fix muted tests and adjust tablet ids
  .github/config/muted_ya.txt
  ydb/core/tx/schemeshard/ut_base/ut_allocate_pq.cpp
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
  ydb/core/tx/schemeshard/ut_base_reboots/ut_allocate_reboot_pq.cpp
  ydb/core/tx/schemeshard/ut_cdc_stream/ut_cdc_stream.cpp
  ydb/core/tx/schemeshard/ut_column_build/ut_column_build.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_index_build.cpp
  ydb/core/tx/schemeshard/ut_move/ut_move.cpp
  ydb/core/tx/schemeshard/ut_pq_reboots/ut_pq_reboots.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/core/tx/schemeshard/ut_split_merge/ut_split_merge.cpp
  ydb/core/tx/schemeshard/ut_split_merge_reboots/ut_split_merge_reboots.cpp
  ydb/core/tx/schemeshard/ut_subdomain_reboots/ut_subdomain_reboots.cpp
  ydb/core/tx/tx.h
Labels: not-for-changelog

#2395 Fixed iterator invalidation in graph shard
  ydb/core/graph/shard/backends.cpp
  ydb/core/graph/ut/graph_ut.cpp
Labels: not-for-changelog

#2408 Temporary mute kv tests
  .github/config/muted_test.txt
Labels: not-for-changelog

#2303 Disable LogBatching for already existed kv tablets
  ydb/core/keyvalue/keyvalue_flat_impl.h
  ydb/core/protos/feature_flags.proto
Labels: improvement

#2407 Add MySQL and MS SQL Server to the list of external data sources
  ydb/library/yql/providers/generic/connector/api/common/data_source.proto
Labels: not-for-changelog

#2106 YQ-2885 fix issue script execution is canceled
  ydb/core/fq/libs/compute/ydb/actors_factory.cpp
  ydb/core/fq/libs/compute/ydb/actors_factory.h
  ydb/core/fq/libs/compute/ydb/base_status_updater_actor.h
  ydb/core/fq/libs/compute/ydb/status_tracker_actor.cpp
  ydb/core/fq/libs/compute/ydb/stopper_actor.cpp
  ydb/core/fq/libs/compute/ydb/stopper_actor.h
  ydb/core/fq/libs/compute/ydb/ydb_run_actor.cpp
  ydb/core/kqp/run_script_actor/kqp_run_script_actor.cpp
Labels: area/queryprocessor, bugfix, improvement

#2400 Links instead of full blobid
  ydb/core/tx/columnshard/columnshard__stats_scan.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/common/blob.cpp
  ydb/core/tx/columnshard/common/blob.h
  ydb/core/tx/columnshard/common/protos/blob_range.proto
  ydb/core/tx/columnshard/data_sharing/protos/data.proto
  ydb/core/tx/columnshard/engines/changes/compaction/column_portion_chunk.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/portions/column_record.cpp
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/portions/index_chunk.cpp
  ydb/core/tx/columnshard/engines/portions/index_chunk.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/with_blobs.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/source.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.h
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/normalizer/portion/min_max.cpp
  ydb/core/tx/columnshard/splitter/chunks.cpp
  ydb/core/tx/columnshard/splitter/chunks.h
Labels: improvement

#2240 YQ-2898 fix query failed with unknown uncommitted upload issue
  ydb/library/yql/providers/s3/actors/yql_s3_applicator_actor.cpp
Labels: area/yql, improvement

#2396 statistics for columnshard
  ydb/core/kqp/gateway/behaviour/tablestore/operations/drop_stat.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/operations/drop_stat.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/upsert_stat.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/operations/upsert_stat.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/ya.make
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/protos/tx_columnshard.proto
  ydb/core/protos/ya.make
  ydb/core/tx/columnshard/columnshard_ut_common.h
  ydb/core/tx/columnshard/counters/engine_logs.cpp
  ydb/core/tx/columnshard/counters/engine_logs.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/portions/meta.cpp
  ydb/core/tx/columnshard/engines/portions/meta.h
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/with_blobs.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/common.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/common.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/constructor.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/constructor.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/operator.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/operator.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/portion_storage.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/portion_storage.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/ya.make
  ydb/core/tx/columnshard/engines/scheme/statistics/max/constructor.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/max/constructor.h
  ydb/core/tx/columnshard/engines/scheme/statistics/max/operator.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/max/operator.h
  ydb/core/tx/columnshard/engines/scheme/statistics/max/ya.make
  ydb/core/tx/columnshard/engines/scheme/statistics/protos/data.proto
  ydb/core/tx/columnshard/engines/scheme/statistics/protos/ya.make
  ydb/core/tx/columnshard/engines/scheme/statistics/ya.make
  ydb/core/tx/columnshard/engines/scheme/ya.make
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
  ydb/core/tx/schemeshard/common/validation.cpp
  ydb/core/tx/schemeshard/common/validation.h
  ydb/core/tx/schemeshard/common/ya.make
  ydb/core/tx/schemeshard/olap/indexes/update.cpp
  ydb/core/tx/schemeshard/olap/indexes/update.h
  ydb/core/tx/schemeshard/olap/schema/schema.cpp
  ydb/core/tx/schemeshard/olap/schema/schema.h
  ydb/core/tx/schemeshard/olap/schema/update.cpp
  ydb/core/tx/schemeshard/olap/schema/update.h
  ydb/core/tx/schemeshard/olap/schema/ya.make
  ydb/core/tx/schemeshard/olap/statistics/schema.cpp
  ydb/core/tx/schemeshard/olap/statistics/schema.h
  ydb/core/tx/schemeshard/olap/statistics/update.cpp
  ydb/core/tx/schemeshard/olap/statistics/update.h
  ydb/core/tx/schemeshard/olap/statistics/ya.make
  ydb/core/tx/schemeshard/olap/ya.make
  ydb/core/tx/schemeshard/schemeshard_validate_ttl.cpp
  ydb/core/tx/schemeshard/ya.make
Labels: new-feature

#1860 YQ-2549 Checkpointing in match_recognize
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize.cpp
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_list.h
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_matched_vars.h
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_measure_arg.h
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_nfa.h
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_save_load.h
  ydb/library/yql/minikql/comp_nodes/mkql_time_order_recover.cpp
  ydb/library/yql/minikql/comp_nodes/ut/mkql_match_recognize_ut.cpp
  ydb/library/yql/minikql/comp_nodes/ut/ya.make.inc
  ydb/tests/fq/yds/test_recovery_match_recognize.py
Labels: not-for-changelog

#2410 trace raw queries
  ydb/core/pgproxy/pg_proxy_types.cpp
Labels: not-for-changelog

#2414 YQ-2840 Move pq_async_actor tests to github
  ydb/tests/fq/pq_async_io/dq_pq_read_actor_ut.cpp
  ydb/tests/fq/pq_async_io/dq_pq_write_actor_ut.cpp
  ydb/tests/fq/pq_async_io/ut_helpers.cpp
  ydb/tests/fq/pq_async_io/ut_helpers.h
  ydb/tests/fq/pq_async_io/ya.make
  ydb/tests/fq/ya.make
Labels: not-for-changelog

#2429 YQL-18005: fix statement cleanup in pgrun
  ydb/library/yql/tests/postgresql/cases/uuid.err
  ydb/library/yql/tests/postgresql/cases/uuid.out
  ydb/library/yql/tests/postgresql/cases/uuid.sql
  ydb/library/yql/tests/postgresql/make-tests.sh
  ydb/library/yql/tests/postgresql/pg_tests.csv
  ydb/library/yql/tools/pgrun/pgrun.cpp
Labels: bugfix

#2386 New methods to provide IAM-tokens when accessing managed YDB from `dqrun`.
  ydb/library/yql/providers/common/proto/gateways_config.proto
  ydb/library/yql/providers/generic/actors/ya.make
  ydb/library/yql/providers/generic/actors/yql_generic_read_actor.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_read_actor.h
  ydb/library/yql/providers/generic/actors/yql_generic_source_factory.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_token_provider.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_token_provider.h
  ydb/library/yql/providers/generic/proto/source.proto
  ydb/library/yql/providers/generic/provider/ut/pushdown/pushdown_ut.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
Labels: new-feature, improvement

#2393 EvWrite Delete
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/core/tx/datashard/datashard_ut_trace.cpp
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/datashard_write_operation.h
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: not-for-changelog

#2380 commit off set ranges fix
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/read_session.ipp
  ydb/public/sdk/cpp/client/ydb_persqueue_core/ut/read_session_ut.cpp
Labels: bugfix

#2430 YQ+2549 Try to fix clang14 build
  ydb/library/yql/minikql/comp_nodes/mkql_match_recognize_save_load.h
Labels: not-for-changelog

#2421 Add File Acquire/Release to FileCache + unittests
  ydb/library/yql/providers/dq/global_worker_manager/global_worker_manager.cpp
  ydb/library/yql/providers/dq/runtime/file_cache.cpp
  ydb/library/yql/providers/dq/runtime/file_cache.h
  ydb/library/yql/providers/dq/runtime/ut/file_cache_ut.cpp
  ydb/library/yql/providers/dq/runtime/ut/ya.make
  ydb/library/yql/providers/dq/runtime/ya.make
  ydb/library/yql/providers/dq/task_runner/file_cache.h
Labels: not-for-changelog

#2432 Implemented pg_proc/pg_aggregate/pg_language tables + small fixes
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/catalog.h
  ydb/library/yql/parser/pg_catalog/ya.make
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/generate_kernels.py
  ydb/library/yql/parser/pg_wrapper/pg_aggs.inc
  ydb/library/yql/parser/pg_wrapper/pg_aggs.slow.inc
  ydb/library/yql/parser/pg_wrapper/pg_aggs_register.inc
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/cache/syscache.c
  ydb/library/yql/parser/pg_wrapper/postgresql/src/include/catalog/pg_language.dat
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_aggregate.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_language.sql
  ydb/library/yql/tests/sql/suites/pg_catalog/pg_proc.sql
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
  ydb/library/yql/tools/pg_catalog_dump/dump.json
  ydb/library/yql/tools/pg_catalog_dump/pg_catalog_dump.cpp
  ydb/library/yql/tools/pg_catalog_dump/ya.make
  ydb/library/yql/tools/ya.make
Labels: new-feature, area/pg

#2431 Avoid copying event observers before each call
  ydb/library/actors/testlib/test_runtime.cpp
Labels: not-for-changelog

#2397 Add denylist and allowlist to configsdispatcher
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/cms/console/configs_dispatcher.h
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/testlib/tenant_runtime.cpp
  ydb/core/testlib/test_client.cpp
Labels: not-for-changelog

#2444 cut useless dependencies
  ydb/core/kqp/gateway/behaviour/tablestore/operations/ya.make
  ydb/core/tx/columnshard/blobs_action/abstract/storage.h
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.h
  ydb/core/tx/columnshard/blobs_action/abstract/ya.make
  ydb/core/tx/columnshard/blobs_action/bs/storage.h
  ydb/core/tx/columnshard/blobs_action/tier/storage.cpp
  ydb/core/tx/columnshard/blobs_action/tier/storage.h
  ydb/core/tx/columnshard/engines/portions/with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/with_blobs.h
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/columnshard/engines/scheme/abstract/loader.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/loader.h
  ydb/core/tx/columnshard/engines/scheme/abstract/saver.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract/saver.h
  ydb/core/tx/columnshard/engines/scheme/abstract/ya.make
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/column_features.cpp
  ydb/core/tx/columnshard/engines/scheme/column_features.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/operator.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/ya.make
  ydb/core/tx/columnshard/engines/scheme/statistics/max/operator.cpp
  ydb/core/tx/columnshard/engines/scheme/statistics/max/operator.h
  ydb/core/tx/columnshard/engines/scheme/statistics/max/ya.make
  ydb/core/tx/columnshard/engines/scheme/ya.make
  ydb/core/tx/columnshard/splitter/abstract/chunk_meta.cpp
  ydb/core/tx/columnshard/splitter/abstract/chunk_meta.h
  ydb/core/tx/columnshard/splitter/abstract/chunks.cpp
  ydb/core/tx/columnshard/splitter/abstract/chunks.h
  ydb/core/tx/columnshard/splitter/abstract/ya.make
  ydb/core/tx/columnshard/splitter/chunk_meta.cpp
  ydb/core/tx/columnshard/splitter/chunk_meta.h
  ydb/core/tx/columnshard/splitter/chunks.h
  ydb/core/tx/columnshard/splitter/ya.make
  ydb/core/tx/tiering/abstract/manager.cpp
  ydb/core/tx/tiering/abstract/manager.h
  ydb/core/tx/tiering/abstract/ya.make
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/manager.h
  ydb/services/metadata/common/ya.make
Labels: improvement

#2445 Properly calculate size of cached files
  ydb/library/yql/providers/dq/task_runner/tasks_runner_pipe.cpp
Labels: not-for-changelog

#2453 Add log message
  ydb/library/yql/providers/dq/runtime/file_cache.cpp
Labels: not-for-changelog

#2457 Removed pragmas from query
  ydb/library/benchmarks/queries/tpch/yql/q11.sql
Labels: not-for-changelog

#2415 Tracing levels proposal implementation
  ydb/core/keyvalue/keyvalue_intermediate.cpp
  ydb/core/keyvalue/keyvalue_storage_read_request.cpp
  ydb/core/keyvalue/keyvalue_storage_request.cpp
  ydb/core/tablet/tablet_req_writelog.cpp
  ydb/core/tablet_flat/flat_exec_seat.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/tablet_flat_executor.h
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/library/wilson_ids/wilson.h
Labels: not-for-changelog, new-feature

#2403 Missing tracing in table/query service
  ydb/core/grpc_services/rpc_begin_transaction.cpp
  ydb/core/grpc_services/rpc_commit_transaction.cpp
  ydb/core/grpc_services/rpc_common/rpc_common_kqp_session.cpp
  ydb/core/grpc_services/rpc_deferrable.h
  ydb/core/grpc_services/rpc_execute_data_query.cpp
  ydb/core/grpc_services/rpc_execute_scheme_query.cpp
  ydb/core/grpc_services/rpc_execute_yql_script.cpp
  ydb/core/grpc_services/rpc_explain_data_query.cpp
  ydb/core/grpc_services/rpc_explain_yql_script.cpp
  ydb/core/grpc_services/rpc_prepare_data_query.cpp
  ydb/core/grpc_services/rpc_read_rows.cpp
  ydb/core/grpc_services/rpc_rollback_transaction.cpp
  ydb/core/grpc_services/ya.make
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/tx/datashard/datashard_ut_trace.cpp
  ydb/core/util/wilson.h
  ydb/core/util/ya.make
Labels: not-for-changelog

#2463 fix race in case abort and merge processing in time
  ydb/core/tx/columnshard/engines/reader/plain_reader/interval.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/interval.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/plain_read_data.h
Labels: bugfix

#2464 fix storages manager stop flags usage
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.h
Labels: bugfix

#2258 Create table as select
  ydb/core/kqp/common/compilation/events.h
  ydb/core/kqp/common/compilation/result.h
  ydb/core/kqp/common/events/events.h
  ydb/core/kqp/common/simple/kqp_event_ids.h
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.h
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_host.h
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/host/kqp_statement_rewrite.h
  ydb/core/kqp/host/kqp_translate.h
  ydb/core/kqp/host/ya.make
  ydb/core/kqp/provider/rewrite_io_utils.cpp
  ydb/core/kqp/provider/rewrite_io_utils.h
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/session_actor/kqp_query_state.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
  ydb/core/protos/table_service_config.proto
  ydb/library/yql/sql/v1/SQLv1.g.in
  ydb/library/yql/sql/v1/format/sql_format.cpp
  ydb/library/yql/sql/v1/format/sql_format_ut.cpp
  ydb/library/yql/sql/v1/query.cpp
  ydb/library/yql/sql/v1/source.h
  ydb/library/yql/sql/v1/sql_query.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_translation.h
  ydb/library/yql/sql/v1/sql_ut.cpp
  ydb/library/yql/sql/v1/sql_values.cpp
  ydb/library/yql/sql/v1/sql_values.h
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
Labels: new-feature

#2452 [cms] add start_time in public cms maintenance api
  ydb/core/cms/api_adapters.cpp
  ydb/core/cms/cms.cpp
  ydb/core/protos/cms.proto
  ydb/public/api/protos/draft/ydb_maintenance.proto
Labels: new-feature

#2441 YDB-647 add media type field
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/json_storage.h
  ydb/core/viewer/json_storage_base.h
  ydb/core/viewer/protos/viewer.proto
Labels: new-feature

#2388 two writing sessions and one transaction
  ydb/core/persqueue/writer/writer.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#2144 YDBD binary args: pass tenant path to database quotas
  ydb/core/driver_lib/cli_utils/cli_cmds_tenant.cpp
Labels: bugfix

#2456 [pg] Tune print of function arguments
  ydb/core/kqp/ut/pg/pg_catalog_ut.cpp
  ydb/library/yql/parser/pg_catalog/catalog.cpp
  ydb/library/yql/parser/pg_catalog/catalog.h
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: improvement

#2476 [docs] improve search snippet for the index page
  ydb/docs/en/core/index.yaml
  ydb/docs/ru/core/index.yaml
Labels: documentation

#1895 Add docs for YDB Federated Query + Connector deployment
  ydb/docs/ru/core/concepts/datamodel/external_data_source.md
  ydb/docs/ru/core/concepts/federated_query/_assets/architecture.png
  ydb/docs/ru/core/concepts/federated_query/architecture.md
  ydb/docs/ru/core/concepts/federated_query/index.md
  ydb/docs/ru/core/concepts/federated_query/toc_i.yaml
  ydb/docs/ru/core/deploy/manual/_images/ydb_fq_onprem.png
  ydb/docs/ru/core/deploy/manual/connector.md
  ydb/docs/ru/core/deploy/manual/deploy-ydb-federated-query.md
  ydb/docs/ru/core/deploy/manual/toc_i.yaml
  ydb/docs/ru/core/deploy/toc_i.yaml
  ydb/docs/ru/core/getting_started/self_hosted/_images/ydb_fq_docker.png
  ydb/docs/ru/core/getting_started/self_hosted/_includes/ydb_docker.md
Labels: documentation

#2471 tests TPartitionWriterCacheActorTests::*
  .github/config/muted_ya.txt
  ydb/services/persqueue_v1/ut/partition_writer_cache_actor_fixture.cpp
  ydb/services/persqueue_v1/ut/partition_writer_cache_actor_fixture.h
Labels: bugfix

#2446 Printable status & results
  ydb/public/sdk/cpp/client/ydb_scheme/scheme.cpp
  ydb/public/sdk/cpp/client/ydb_scheme/scheme.h
  ydb/public/sdk/cpp/client/ydb_table/table.cpp
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic.cpp
  ydb/public/sdk/cpp/client/ydb_types/status/status.cpp
  ydb/public/sdk/cpp/client/ydb_types/status/status.h
Labels: not-for-changelog

#1975 enable pg flags
  ydb/tests/library/harness/kikimr_config.py
Labels: not-for-changelog

#2470 Raised timeouts in ydb tools restore command
  ydb/library/backup/query_uploader.cpp
Labels: not-for-changelog

#2488 ci: add "external" label for PRs made by external contributors
  .github/workflows/pr_check.yml
Labels: new-feature

#2477 Fix kv trace tests
  .github/config/muted_ya.txt
  ydb/core/keyvalue/keyvalue_ut_trace.cpp
Labels: bugfix

#492 maintenance: fix typo
  clang.toolchain
Labels: external

#1712 Fix using std::move after moving
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
Labels: area/blobstorage, bugfix

#2485 fix build
  ydb/core/tx/columnshard/splitter/abstract/ya.make
Labels: bugfix

#2439 YQ-2915 DdResolver / Pass errors to Response
  ydb/core/fq/libs/actors/database_resolver.cpp
  ydb/core/fq/libs/actors/ut/database_resolver_ut.cpp
Labels: not-for-changelog

#2490 Fix sync
  ydb/core/base/domain.h
Labels: not-for-changelog

#2503 Get rid of hard-coded test table name
  ydb/core/tx/replication/service/table_writer_ut.cpp
  ydb/core/tx/replication/service/worker_ut.cpp
  ydb/core/tx/replication/ut_helpers/test_table.cpp
Labels: not-for-changelog

#2497 Fix dst creator, add tests
  ydb/core/tx/replication/controller/dst_creator.cpp
  ydb/core/tx/replication/controller/dst_creator_ut.cpp
  ydb/core/tx/replication/controller/ut_dst_creator/ya.make
  ydb/core/tx/replication/controller/ya.make
  ydb/core/tx/replication/ut_helpers/test_env.h
Labels: area/tablets, not-for-changelog

#2499 Fix tests with create and drop pq tablet
  .github/config/muted_ya.txt
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
Labels: bugfix

#2468 YQL-17795 Bigdate casts
  ydb/library/yql/core/yql_expr_type_annotation.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_convert.cpp
  ydb/library/yql/minikql/invoke_builtins/mkql_builtins_datetime.h
  ydb/library/yql/providers/yt/provider/yql_yt_table.cpp
  ydb/library/yql/public/udf/udf_data_type.cpp
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/bigdate/common_type.sql
  ydb/library/yql/tests/sql/suites/bigdate/explicit_cast.sql
  ydb/library/yql/tests/sql/suites/bigdate/implicit_cast_callable.sql
  ydb/library/yql/tests/sql/suites/bigdate/int_cast.sql
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
Labels: new-feature

#2498 Fix TWithDefault Behavior
  ydb/core/config/init/init_impl.h
Labels: not-for-changelog

#2502 Move printers to corresponding */out.cpp files
  ydb/core/tx/replication/ydb_proxy/ydb_proxy.h
  ydb/public/sdk/cpp/client/ydb_export/export.h
  ydb/public/sdk/cpp/client/ydb_export/out.cpp
  ydb/public/sdk/cpp/client/ydb_export/ya.make
  ydb/public/sdk/cpp/client/ydb_result/out.cpp
  ydb/public/sdk/cpp/client/ydb_result/result.h
  ydb/public/sdk/cpp/client/ydb_result/ya.make
  ydb/public/sdk/cpp/client/ydb_scheme/out.cpp
  ydb/public/sdk/cpp/client/ydb_scheme/scheme.cpp
  ydb/public/sdk/cpp/client/ydb_scheme/ya.make
  ydb/public/sdk/cpp/client/ydb_table/out.cpp
  ydb/public/sdk/cpp/client/ydb_table/table.cpp
  ydb/public/sdk/cpp/client/ydb_table/table.h
  ydb/public/sdk/cpp/client/ydb_table/ya.make
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic.cpp
  ydb/public/sdk/cpp/client/ydb_topic/out.cpp
  ydb/public/sdk/cpp/client/ydb_topic/ya.make
  ydb/public/sdk/cpp/client/ydb_types/operation/operation.h
  ydb/public/sdk/cpp/client/ydb_types/operation/out.cpp
  ydb/public/sdk/cpp/client/ydb_types/operation/ya.make
  ydb/public/sdk/cpp/client/ydb_types/status/status.cpp
  ydb/public/sdk/cpp/client/ydb_value/out.cpp
  ydb/public/sdk/cpp/client/ydb_value/value.h
  ydb/public/sdk/cpp/client/ydb_value/ya.make
Labels: not-for-changelog

#2525 correct histogram aggregation
  ydb/core/graph/api/events.h
  ydb/core/graph/api/service.h
  ydb/core/graph/protos/graph.proto
  ydb/core/graph/service/service_impl.cpp
  ydb/core/graph/shard/backends.cpp
  ydb/core/graph/shard/backends.h
  ydb/core/graph/shard/shard_impl.cpp
  ydb/core/graph/shard/shard_impl.h
  ydb/core/graph/shard/tx_store_metrics.cpp
  ydb/core/graph/shard/ut/shard_ut.cpp
  ydb/core/graph/ut/graph_ut.cpp
  ydb/core/sys_view/service/ext_counters.cpp
Labels: bugfix

#2399 Added support for PG into CBO
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_join.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_sqlin_compact.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
  ydb/library/yql/core/expr_nodes/yql_expr_nodes.json
  ydb/library/yql/core/type_ann/type_ann_join.cpp
  ydb/library/yql/core/ut/yql_expr_constraint_ut.cpp
  ydb/library/yql/dq/expr_nodes/dq_expr_nodes.json
  ydb/library/yql/dq/opt/dq_opt_join.cpp
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
  ydb/library/yql/dq/opt/dq_opt_peephole.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/opt/dq_opt_predicate_selectivity.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
  ydb/library/yql/dq/type_ann/dq_type_ann.cpp
  ydb/library/yql/mount/lib/yql/aggregate.yql
  ydb/library/yql/mount/lib/yql/core.yql
  ydb/library/yql/mount/lib/yql/id.yql
  ydb/library/yql/mount/lib/yql/sqr.yql
  ydb/library/yql/mount/lib/yql/walk_folders.yql
  ydb/library/yql/mount/lib/yql/window.yql
  ydb/library/yql/tests/s-expressions/suites/GraceJoin/GraceJoinCore_Flow.yql
  ydb/library/yql/tests/s-expressions/suites/GraceJoin/SelfJoinCore_Flow.yql
  ydb/library/yql/tests/s-expressions/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part9/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part9/canondata/result.json
Labels: improvement

#2524 alignment of PG strings in blocks
  ydb/library/yql/minikql/computation/mkql_block_reader.cpp
  ydb/library/yql/parser/pg_wrapper/arrow.h
  ydb/library/yql/parser/pg_wrapper/comp_factory.cpp
  ydb/library/yql/public/udf/arrow/block_builder.h
  ydb/library/yql/public/udf/arrow/util.h
Labels: bugfix

#2522 Improved cardinality estimation for joins
  ydb/library/yql/core/yql_cost_function.cpp
  ydb/library/yql/core/yql_statistics.h
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
Labels: improvement

#2487 fix TKeyValueTest::TestWriteReadWhileWriteWorks
  .github/config/muted_ya.txt
  ydb/core/keyvalue/keyvalue_ut.cpp
Labels: bugfix

#2537 [ratelimiter] fix not_allowed message if no admins on cluster in configuration
  ydb/core/grpc_services/rpc_rate_limiter_api.cpp
Labels: new-feature, bugfix

#2118 Fix kv init 'It is not allowed to create not null data column' 23-3 error
  .gitignore
  ydb/docs/en/core/reference/ydb-cli/workload-kv.md
  ydb/docs/ru/core/reference/ydb-cli/workload-kv.md
  ydb/library/workload/kv_workload.cpp
Labels: bugfix

#2505 Fix planning of volatile transactions with uncommitted effects
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/tx/datashard/datashard_ut_order.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_rs.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
Labels: not-for-changelog

#2356 Support for temporary tokens in yql_plugin
  ydb/library/yql/core/facade/yql_facade.cpp
  ydb/library/yql/core/facade/yql_facade.h
  ydb/library/yql/yt/bridge/interface.h
  ydb/library/yql/yt/dynamic/dylib.exports
  ydb/library/yql/yt/dynamic/impl.cpp
  ydb/library/yql/yt/native/plugin.cpp
  ydb/library/yql/yt/plugin.h
Labels: new-feature

#2534 YQL-18016 fix peerdir in gnereic provider cpp lib
  ydb/library/yql/providers/generic/connector/libcpp/ya.make
Labels: not-for-changelog

#2460 sessions system table
  ydb/core/kqp/common/events/events.h
  ydb/core/kqp/common/simple/kqp_event_ids.h
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service_impl.h
  ydb/core/kqp/ut/sysview/kqp_sys_view_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/sys_view/common/schema.cpp
  ydb/core/sys_view/common/schema.h
  ydb/core/sys_view/scan.cpp
  ydb/core/sys_view/sessions/sessions.cpp
  ydb/core/sys_view/sessions/sessions.h
  ydb/core/sys_view/sessions/ya.make
  ydb/core/sys_view/ut_kqp.cpp
  ydb/core/sys_view/ya.make
Labels: experimental-feature

#2556 Add scripts for downloading datasets
  ydb/library/benchmarks/runner/download_files_ds_1.sh
  ydb/library/benchmarks/runner/download_files_h_1.sh
  ydb/library/benchmarks/runner/download_files_h_10.sh
  ydb/library/benchmarks/runner/download_files_h_100.sh
  ydb/library/benchmarks/runner/download_lib.sh
  ydb/library/benchmarks/runner/download_tables.sh
  ydb/library/benchmarks/runner/download_tpcds_tables.sh
Labels: not-for-changelog

#2536 YQL-17958: use PG's common type algorithm for PG types
  ydb/library/yql/core/yql_expr_type_annotation.cpp
  ydb/library/yql/tests/postgresql/cases/arrays.out
  ydb/library/yql/tests/postgresql/cases/arrays.sql
  ydb/library/yql/tests/postgresql/cases/date.err
  ydb/library/yql/tests/postgresql/cases/date.out
  ydb/library/yql/tests/postgresql/cases/date.sql
  ydb/library/yql/tests/postgresql/cases/expressions.err
  ydb/library/yql/tests/postgresql/cases/float8.err
  ydb/library/yql/tests/postgresql/cases/float8.out
  ydb/library/yql/tests/postgresql/cases/float8.sql
  ydb/library/yql/tests/postgresql/cases/horology.err
  ydb/library/yql/tests/postgresql/cases/horology.out
  ydb/library/yql/tests/postgresql/cases/horology.sql
  ydb/library/yql/tests/postgresql/cases/interval.err
  ydb/library/yql/tests/postgresql/cases/interval.out
  ydb/library/yql/tests/postgresql/cases/interval.sql
  ydb/library/yql/tests/postgresql/cases/join.err
  ydb/library/yql/tests/postgresql/cases/select.err
  ydb/library/yql/tests/postgresql/cases/select.out
  ydb/library/yql/tests/postgresql/cases/select.sql
  ydb/library/yql/tests/postgresql/cases/subselect.err
  ydb/library/yql/tests/postgresql/cases/subselect.out
  ydb/library/yql/tests/postgresql/cases/subselect.sql
  ydb/library/yql/tests/postgresql/cases/timestamp.err
  ydb/library/yql/tests/postgresql/cases/timestamp.out
  ydb/library/yql/tests/postgresql/cases/timestamp.sql
  ydb/library/yql/tests/postgresql/cases/timestamptz.err
  ydb/library/yql/tests/postgresql/cases/timestamptz.out
  ydb/library/yql/tests/postgresql/cases/timestamptz.sql
  ydb/library/yql/tests/postgresql/cases/window.err
  ydb/library/yql/tests/postgresql/cases/window.out
  ydb/library/yql/tests/postgresql/cases/window.sql
  ydb/library/yql/tests/postgresql/pg_tests.csv
  ydb/library/yql/tests/postgresql/status.md
  ydb/library/yql/tests/postgresql/status.old
  ydb/library/yql/tests/sql/dq_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/select_common_type_if.sql
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
Labels: bugfix

#2563 schemeboard: fix path updates from both root and tenant schemeshards
  ydb/core/tx/scheme_board/replica.cpp
Labels: not-for-changelog

#2549 Remove duplicates of columns declaration in unit tests
  ydb/core/tx/datashard/datashard_ut_change_collector.cpp
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/datashard/datashard_ut_kqp_stream_lookup.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/core/tx/datashard/datashard_ut_trace.cpp
  ydb/core/tx/datashard/datashard_ut_upload_rows.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: not-for-changelog

#2554 fix default for delete on
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/scheme/kqp_constraints_ut.cpp
Labels: bugfix

#2571 Can insert custom pragmas
  ydb/library/benchmarks/gen_queries/gen_queries.py
  ydb/library/benchmarks/gen_queries/header.sql.jinja
Labels: not-for-changelog

#2360 Workload Treat verbose option
  ydb/public/lib/ydb_cli/commands/ydb_workload.cpp
  ydb/public/lib/ydb_cli/commands/ydb_workload.h
Labels: not-for-changelog

#2577 queries with pagination have been speed up
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_bindings.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_connections.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp
  ydb/core/kqp/proxy_service/kqp_script_executions.cpp
Labels: performance

#2582 Queries Generator: Add YtSaurus support
  ydb/library/benchmarks/gen_queries/README.md
  ydb/library/benchmarks/gen_queries/gen_queries.py
  ydb/library/benchmarks/gen_queries/pragmas_ytsaurus.yql
  ydb/library/benchmarks/gen_queries/pragmas_ytsaurus_pg.yql
  ydb/library/benchmarks/gen_queries/tables_ytsaurus_pg.jinja
  ydb/library/benchmarks/gen_queries/ya.make
  ydb/library/benchmarks/template/__init__.py
  ydb/library/benchmarks/template/ut/test.py
Labels: not-for-changelog

#2581 Replace trace macro with source_location based calls
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/config/init/source_location.h
Labels: not-for-changelog

#2583 [Init] Move cerr/cout calls to separate interface
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_server.h
Labels: not-for-changelog

#2586 Clean. Prepare validation.
  ydb/core/kqp/ut/common/columnshard.cpp
  ydb/core/kqp/ut/common/columnshard.h
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/kqp/ut/scheme/ya.make
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/columnshard_ttl.h
  ydb/core/tx/columnshard/columnshard_ut_common.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/scheme/tier_info.h
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/tables_manager.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
  ydb/core/tx/tiering/manager.cpp
  ydb/services/metadata/secret/secret.h
Labels: bugfix

#2585 tiering usage validations and control incorrect state usage
  ydb/core/tx/columnshard/blobs_action/abstract/storage.h
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.cpp
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/engines/column_engine.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/columnshard/tables_manager.h
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/manager.h
Labels: bugfix

#2545 support of range scans in pg sys cache
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/cache/catcache.c
  ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/cache/syscache.c
  ydb/library/yql/parser/pg_wrapper/syscache.cpp
Labels: improvement

#466 Fix typo (test -> tests)
  ydb/library/yql/tests/common/test_framework/yql_utils.py
Labels: external

#2570 YQ-2892 supported yt pragmas
  ydb/library/yql/providers/yt/provider/yql_yt_datasource_constraints.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_datasource_type_ann.cpp
Labels: area/yql, improvement

#2440 Exclude PQ (YDS) Stats from Metering Records
  ydb/core/fq/libs/control_plane_storage/internal/utils.cpp
  ydb/tests/fq/yds/test_kill_pq_bill.py
  ydb/tests/fq/yds/ya.make
Labels: not-for-changelog

#2572 Add _cluster_name field to yql_statistics part of YT query progress
  ydb/library/yql/providers/yt/gateway/native/yql_yt_exec_ctx.h
  ydb/library/yql/providers/yt/gateway/native/yql_yt_op_tracker.cpp
  ydb/library/yql/providers/yt/gateway/native/yql_yt_op_tracker.h
Labels: improvement, external

#2591 lock names usage correction
  ydb/core/tx/columnshard/data_locks/locks/abstract.h
  ydb/core/tx/columnshard/data_locks/locks/composite.h
  ydb/core/tx/columnshard/data_locks/locks/list.h
  ydb/core/tx/columnshard/data_locks/locks/snapshot.h
  ydb/core/tx/columnshard/data_locks/manager/manager.cpp
  ydb/core/tx/columnshard/data_locks/manager/manager.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup.h
  ydb/core/tx/columnshard/engines/changes/compaction.h
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/changes/with_appended.h
Labels: improvement

#2514 Forward cache simplify
  ydb/core/tablet_flat/flat_fwd_cache.h
  ydb/core/tablet_flat/flat_fwd_env.h
  ydb/core/tablet_flat/flat_part_forward.h
  ydb/core/tablet_flat/test/libs/table/test_part.h
  ydb/core/tablet_flat/test/libs/table/test_steps.h
  ydb/core/tablet_flat/ut/ut_forward.cpp
Labels: not-for-changelog

#2588 query replay: add query type checker
  ydb/tools/query_replay/query_compiler.cpp
Labels: not-for-changelog

#2600 Additional tests for dst creator
  ydb/core/tx/replication/controller/dst_creator_ut.cpp
Labels: not-for-changelog, new-feature

#2551 Pick join implementations with CBO in YDB
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/kqp_statistics_transformer.cpp
  ydb/core/kqp/opt/logical/kqp_opt_cbo.cpp
  ydb/core/kqp/opt/logical/kqp_opt_cbo.h
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_join.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_rules.h
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy.h
  ydb/library/yql/core/cbo/cbo_optimizer_new.cpp
  ydb/library/yql/core/cbo/cbo_optimizer_new.h
  ydb/library/yql/core/type_ann/type_ann_join.cpp
  ydb/library/yql/core/yql_cost_function.cpp
  ydb/library/yql/core/yql_cost_function.h
  ydb/library/yql/core/yql_join.cpp
  ydb/library/yql/core/yql_join.h
  ydb/library/yql/core/yql_statistics.cpp
  ydb/library/yql/core/yql_statistics.h
  ydb/library/yql/dq/expr_nodes/dq_expr_nodes.json
  ydb/library/yql/dq/opt/dq_cbo_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_join.cpp
  ydb/library/yql/dq/opt/dq_opt_join.h
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
  ydb/library/yql/dq/type_ann/dq_type_ann.cpp
  ydb/library/yql/providers/dq/opt/logical_optimize.cpp
  ydb/library/yql/sql/pg/optimizer.cpp
  ydb/public/lib/ydb_cli/common/format.cpp
Labels: performance

#2603 fix cleanup for huge volume removing
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
Labels: bugfix

#2604 fix restore portion with index too
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/with_blobs.h
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.h
  ydb/core/tx/columnshard/engines/scheme/statistics/abstract/operator.h
  ydb/core/tx/columnshard/splitter/batch_slice.cpp
  ydb/core/tx/columnshard/splitter/batch_slice.h
Labels: bugfix

#2607 correct activity for concept execute/complete
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
Labels: improvement

#2605 [KIKIMR-21174] Remove wrong RuntimeVersion check
  ydb/library/yql/minikql/mkql_node.cpp
Labels: bugfix

#2614 resources manager correction for zero resources allocation immediately
  ydb/core/tx/columnshard/resource_subscriber/actor.cpp
  ydb/core/tx/columnshard/resource_subscriber/actor.h
  ydb/core/tx/columnshard/resource_subscriber/task.cpp
Labels: improvement

#2578 HC made storage issue RED when no bsc reply
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: new-feature

#2567 YQL-18007: Fix implicit casts in PgLike
  ydb/library/yql/core/type_ann/type_ann_pg.cpp
  ydb/library/yql/tests/postgresql/cases/alter_table.err
  ydb/library/yql/tests/postgresql/cases/strings.err
  ydb/library/yql/tests/postgresql/cases/strings.out
  ydb/library/yql/tests/postgresql/cases/strings.sql
  ydb/library/yql/tests/postgresql/cases/uuid.err
  ydb/library/yql/tests/postgresql/cases/xml.err
  ydb/library/yql/tests/postgresql/cases/xml.err.1
  ydb/library/yql/tests/postgresql/cases/xml.err.2
  ydb/library/yql/tests/postgresql/pg_tests.csv
  ydb/library/yql/tests/postgresql/status.md
  ydb/library/yql/tests/postgresql/status.old
  ydb/library/yql/tests/sql/dq_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/sql2yql/canondata/result.json
  ydb/library/yql/tests/sql/suites/pg/pg_like_cast.sql
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
Labels: bugfix

#2627 Apply table profiles
  ydb/core/tx/replication/controller/dst_creator.cpp
Labels: not-for-changelog

#1355 Add new article: Run YDB cluster in cloud.
  README.md
  ydb/docs/en/core/getting_started/_assets/ydb-cluster-check.png
  ydb/docs/en/core/getting_started/_assets/ydb-storage-gr-check.png
  ydb/docs/en/core/getting_started/_assets/ydb-web-console.png
  ydb/docs/en/core/getting_started/_includes/ansible/ansible-install-steps.md
  ydb/docs/en/core/getting_started/_includes/ansible/ansible.md
  ydb/docs/en/core/getting_started/_includes/ansible/repo-tree.md
  ydb/docs/en/core/getting_started/ansible.md
  ydb/docs/en/core/toc_i.yaml
  ydb/docs/ru/core/getting_started/_assets/ydb-cluster-check.png
  ydb/docs/ru/core/getting_started/_assets/ydb-storage-gr-check.png
  ydb/docs/ru/core/getting_started/_assets/ydb-web-console.png
  ydb/docs/ru/core/getting_started/_includes/ansible/ansible-install-steps.md
  ydb/docs/ru/core/getting_started/_includes/ansible/ansible.md
  ydb/docs/ru/core/getting_started/_includes/ansible/repo-tree.md
  ydb/docs/ru/core/getting_started/ansible.md
  ydb/docs/ru/core/toc_i.yaml
Labels: documentation, ok-to-test

#2625 lighter lock - dont lock whole granule on background process
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/blob_size.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/blob_size.h
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/counters.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/counters.h
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lbuckets/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/levels/counters.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/levels/counters.h
  ydb/core/tx/columnshard/engines/storage/optimizer/levels/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/levels/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/ya.make
  ydb/core/tx/columnshard/engines/storage/storage.cpp
Labels: performance

#2613 split library
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/filtered_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/filtered_scheme.h
  ydb/core/tx/columnshard/engines/scheme/snapshot_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/snapshot_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/snapshot_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/snapshot_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.h
  ydb/core/tx/columnshard/engines/scheme/versions/ya.make
  ydb/core/tx/columnshard/engines/scheme/ya.make
Labels: improvement

#2612 ttl correction for further usage
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/engines/scheme/tier_info.cpp
  ydb/core/tx/columnshard/engines/scheme/tier_info.h
  ydb/core/tx/columnshard/engines/scheme/tiering/common.cpp
  ydb/core/tx/columnshard/engines/scheme/tiering/common.h
  ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.cpp
  ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.h
  ydb/core/tx/columnshard/engines/scheme/tiering/ya.make
  ydb/core/tx/columnshard/engines/scheme/ya.make
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/rule/manager.cpp
  ydb/core/tx/tiering/rule/object.cpp
  ydb/core/tx/tiering/tier/manager.cpp
Labels: improvement

#2638 YQ-2926 Remove offset commit logs
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
Labels: not-for-changelog

#2646 Added statistics calculation for AsList structure
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.h
  ydb/library/yql/dq/opt/dq_opt_stat_transformer_base.cpp
Labels: improvement

#2495 Support Nebius IAM in server
  ydb/core/base/events.h
  ydb/core/protos/auth.proto
  ydb/core/security/ticket_parser_impl.h
  ydb/core/security/ticket_parser_ut.cpp
  ydb/core/security/ut/ya.make
  ydb/core/security/ya.make
  ydb/core/testlib/test_client.cpp
  ydb/library/aclib/aclib.cpp
  ydb/library/ncloud/api/access_service.h
  ydb/library/ncloud/api/events.h
  ydb/library/ncloud/api/ya.make
  ydb/library/ncloud/impl/access_service.cpp
  ydb/library/ncloud/impl/access_service.h
  ydb/library/ncloud/impl/access_service_ut.cpp
  ydb/library/ncloud/impl/ut/ya.make
  ydb/library/ncloud/impl/ya.make
  ydb/library/ncloud/ya.make
  ydb/library/testlib/service_mocks/nebius_access_service_mock.h
  ydb/library/testlib/service_mocks/ya.make
  ydb/library/ya.make
  ydb/library/yql/providers/generic/connector/libcpp/ya.make
  ydb/public/api/client/nc_private/accessservice/access.proto
  ydb/public/api/client/nc_private/accessservice/access_service.proto
  ydb/public/api/client/nc_private/accessservice/ya.make
  ydb/public/api/client/nc_private/ya.make
  ydb/public/api/client/ya.make
  ydb/public/api/client/yc_private/ya.make
Labels: new-feature

#2632 pq reader/writer logs have been improved YQ-2926
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_write_actor.cpp
Labels: improvement

#2649 Set & check replication config
  ydb/core/protos/out/out.cpp
  ydb/core/tx/replication/controller/dst_creator.cpp
  ydb/core/tx/replication/controller/dst_creator_ut.cpp
  ydb/core/tx/replication/ut_helpers/test_table.cpp
  ydb/core/tx/replication/ut_helpers/test_table.h
Labels: not-for-changelog

#2623 Inflight for result writer has been supported
  ydb/core/fq/libs/compute/ydb/result_writer_actor.cpp
  ydb/core/fq/libs/private_client/loopback_service.cpp
Labels: performance

#2658 Removed tracing level Full
  ydb/core/tablet/tablet_req_writelog.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/library/wilson_ids/wilson.h
Labels: not-for-changelog

#2644 Split ttl tasks by rw address of storages read/write
  ydb/core/tx/columnshard/background_controller.cpp
  ydb/core/tx/columnshard/background_controller.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write_index.cpp
  ydb/core/tx/columnshard/columnshard__stats_scan.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_private_events.h
  ydb/core/tx/columnshard/counters/engine_logs.cpp
  ydb/core/tx/columnshard/counters/engine_logs.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.cpp
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.h
  ydb/core/tx/columnshard/engines/changes/actualization/construction/ya.make
  ydb/core/tx/columnshard/engines/changes/actualization/controller/controller.cpp
  ydb/core/tx/columnshard/engines/changes/actualization/controller/controller.h
  ydb/core/tx/columnshard/engines/changes/actualization/controller/ya.make
  ydb/core/tx/columnshard/engines/changes/actualization/ya.make
  ydb/core/tx/columnshard/engines/changes/ttl.cpp
  ydb/core/tx/columnshard/engines/changes/ttl.h
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/changes/ya.make
  ydb/core/tx/columnshard/engines/column_engine.cpp
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/with_blobs.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/ya.make
  ydb/core/tx/columnshard/engines/storage/actualizer/common/address.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/common/address.h
  ydb/core/tx/columnshard/engines/storage/actualizer/common/ya.make
  ydb/core/tx/columnshard/engines/storage/actualizer/index/counters.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/index/counters.h
  ydb/core/tx/columnshard/engines/storage/actualizer/index/index.cpp
  ydb/core/tx/columnshard/engines/storage/actualizer/index/index.h
  ydb/core/tx/columnshard/engines/storage/actualizer/index/ya.make
  ydb/core/tx/columnshard/engines/storage/actualizer/ya.make
  ydb/core/tx/columnshard/engines/storage/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule.h
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/intervals/ya.make
  ydb/core/tx/columnshard/engines/storage/optimizer/levels/ya.make
  ydb/core/tx/columnshard/engines/storage/ya.make
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/tiering/ut/ut_tiers.cpp
Labels: improvement

#2568 Added proper request finishing in grpc request proxy
  ydb/core/grpc_services/base/base.h
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/library/actors/wilson/wilson_span.cpp
  ydb/library/actors/wilson/wilson_span.h
Labels: not-for-changelog

#2618 [Config Validation] add static group validation
  ydb/core/config/validation/ut/ya.make
  ydb/core/config/validation/validators.cpp
  ydb/core/config/validation/validators.h
  ydb/core/config/validation/validators_ut.cpp
  ydb/core/config/validation/ya.make
  ydb/core/config/ya.make
Labels: not-for-changelog

#2665 Create target discoverer once
  ydb/core/tx/replication/controller/replication.cpp
Labels: not-for-changelog

#2592 Add original keys to MapJoinCore
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/library/yql/core/common_opt/yql_co_extr_members.cpp
  ydb/library/yql/core/expr_nodes/yql_expr_nodes.json
  ydb/library/yql/core/type_ann/type_ann_join.cpp
  ydb/library/yql/core/ut/yql_expr_constraint_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_join.cpp
  ydb/library/yql/dq/opt/dq_opt_peephole.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_join_impl.cpp
  ydb/library/yql/tests/s-expressions/suites/Join/EmptyLeftJoin.yql
  ydb/library/yql/tests/s-expressions/suites/Join/MapJoinCore.yql
  ydb/library/yql/tests/s-expressions/suites/Join/MapJoinCoreOnStrings.yql
  ydb/library/yql/tests/s-expressions/suites/Join/MapJoinCoreOnStrings_Flow.yql
  ydb/library/yql/tests/s-expressions/suites/Join/MapJoinCore_Flow.yql
  ydb/library/yql/tests/s-expressions/suites/Join/MapJoinCore_FlowOfTuples.yql
  ydb/library/yql/tests/s-expressions/yt_native_file/part0/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/s-expressions/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/dq_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part0/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/hybrid_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part1/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part10/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part11/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part12/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part13/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part14/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part15/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part16/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part17/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part18/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part19/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part2/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part3/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part4/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part5/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part6/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part7/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part8/canondata/result.json
  ydb/library/yql/tests/sql/yt_native_file/part9/canondata/result.json
Labels: not-for-changelog, new-feature

#2662 Support Managed YDB as an external data source for YDB
  ydb/core/fq/libs/compute/common/config.h
  ydb/core/fq/libs/control_plane_proxy/actors/query_utils.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_queries.cpp
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.cpp
  ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp
  ydb/core/testlib/test_client.cpp
  ydb/library/yql/providers/common/proto/gateways_config.proto
  ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/defaults.cpp
  ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/defaults.h
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
Labels: new-feature

#2675 simplify query service enable
  ydb/core/driver_lib/run/run.cpp
Labels: improvement

#2424 Update github.com/ydb-platform/fq-connector-go to 0.2.5
  ydb/library/yql/providers/generic/connector/tests/docker-compose.yml
  ydb/library/yql/providers/generic/connector/tests/fq-connector-go/config.conf
  ydb/library/yql/providers/generic/connector/tests/fq-connector-go/config.debug.yaml
  ydb/library/yql/providers/generic/connector/tests/utils/settings.py
Labels: not-for-changelog

#2641 Discovery request check spans
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/grpc_services/rpc_discovery.cpp
  ydb/library/wilson_ids/wilson.h
Labels: not-for-changelog

#2683 Relax configuration requirements when starting `DatabaseAsyncResolver` from KQP
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.cpp
Labels: not-for-changelog

#2684 Fixed query replay tool build
  ydb/tools/query_replay/common_deps.inc
Labels: new-feature, bugfix

#2669 Update GitHub workflows to include stream-nb-* branches
  .github/workflows/postcommit_asan.yml
  .github/workflows/postcommit_relwithdebinfo.yml
  .github/workflows/pr_check.yml
Labels: new-feature

#2690 fix linker error
  ydb/core/tx/columnshard/engines/scheme/ya.make
Labels: bugfix

#2692 tests: mute ydb/services/ydb/table_split_ut, YdbTableSplit.SplitByLoadWithReadsMultipleSplitsWithData
  .github/config/muted_ya.txt
Labels: not-for-changelog

#2682 Fixed a bug where Lookup Join was always picked by CBO
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log.h
Labels: bugfix

#2680 [Config Validation] add config validate command
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/config/init/init_noop.cpp
  ydb/core/config/init/ya.make
  ydb/core/driver_lib/cli_base/cli_cmds_db.cpp
  ydb/core/driver_lib/cli_base/cli_command.h
  ydb/core/driver_lib/cli_utils/cli_cmds.h
  ydb/core/driver_lib/cli_utils/cli_cmds_cms.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_console.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_genconfig.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_root.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_tablet.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_validate_config.cpp
  ydb/core/driver_lib/cli_utils/ya.make
  ydb/core/driver_lib/run/driver.h
  ydb/core/driver_lib/run/main.cpp
  ydb/public/lib/ydb_cli/common/command.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: new-feature

#2656 [CLI] double print fix
  ydb/public/lib/ydb_cli/common/format.cpp
Labels: new-feature, bugfix

#2713 Updated roadmap
  ROADMAP.md
Labels: documentation

#2611 YQ-2871 fix error broadcast is not supported
  ydb/library/yql/dq/opt/dq_opt.cpp
  ydb/library/yql/dq/opt/dq_opt.h
  ydb/library/yql/dq/opt/dq_opt_join.cpp
Labels: bugfix

#2709 Compute statistics for stream lookup
  ydb/core/kqp/opt/kqp_statistics_transformer.cpp
Labels: improvement

#2703 add arithmetic aggregate, add per-pool cpu usage
  ydb/core/graph/api/events.h
  ydb/core/graph/protos/graph.proto
  ydb/core/graph/shard/backends.h
  ydb/core/graph/shard/shard_impl.cpp
  ydb/core/graph/shard/shard_impl.h
  ydb/core/graph/shard/tx_store_metrics.cpp
  ydb/core/sys_view/service/ext_counters.cpp
Labels: experimental-feature

#2702 YQ-2957 fix error in s3 stream read actor
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/tests/tools/kqprun/.gitignore
  ydb/tests/tools/kqprun/kqprun.cpp
Labels: new-feature, bugfix

#2561 YQ-2737 add TOKEN auth for YT datasource
  ydb/core/external_sources/external_source_factory.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
  ydb/core/kqp/gateway/kqp_metadata_loader.cpp
  ydb/core/kqp/provider/yql_kikimr_datasource.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_gateway_ut.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/protos/kqp_physical.proto
  ydb/core/tx/schemeshard/schemeshard__operation_common_external_data_source.cpp
  ydb/library/yql/providers/common/structured_token/ut/yql_token_builder_ut.cpp
  ydb/library/yql/providers/common/structured_token/yql_token_builder.cpp
  ydb/library/yql/providers/common/structured_token/yql_token_builder.h
  ydb/library/yql/providers/yt/provider/ya.make
  ydb/library/yql/providers/yt/provider/yql_yt_datasource.cpp
  ydb/library/yql/providers/yt/provider/yql_yt_dq_integration.cpp
  ydb/library/yql/sql/v1/sql_translation.cpp
  ydb/library/yql/sql/v1/sql_ut.cpp
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/kqp_runner.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.h
Labels: area/queryprocessor, area/yql, new-feature

#2663 implement ICodec and its support in clients
  ydb/public/sdk/cpp/client/ydb_federated_topic/federated_topic.h
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_read_session.cpp
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_read_session.h
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_topic.cpp
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_topic_impl.cpp
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_topic_impl.h
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_write_session.cpp
  ydb/public/sdk/cpp/client/ydb_federated_topic/impl/federated_write_session.h
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/persqueue.cpp
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/persqueue_impl.h
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/read_session.cpp
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/read_session.h
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/read_session.ipp
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/write_session_impl.cpp
  ydb/public/sdk/cpp/client/ydb_persqueue_core/impl/write_session_impl.h
  ydb/public/sdk/cpp/client/ydb_persqueue_core/persqueue.h
  ydb/public/sdk/cpp/client/ydb_persqueue_core/ut/read_session_ut.cpp
  ydb/public/sdk/cpp/client/ydb_topic/codecs/codecs.cpp
  ydb/public/sdk/cpp/client/ydb_topic/codecs/codecs.h
  ydb/public/sdk/cpp/client/ydb_topic/impl/read_session.cpp
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic.cpp
  ydb/public/sdk/cpp/client/ydb_topic/impl/topic_impl.h
  ydb/public/sdk/cpp/client/ydb_topic/impl/write_session_impl.cpp
  ydb/public/sdk/cpp/client/ydb_topic/impl/write_session_impl.h
  ydb/public/sdk/cpp/client/ydb_topic/topic.h
Labels: new-feature

#2562 YQ-2892 support emulate YT in KqpRun
  ydb/core/fq/libs/common/cache_ut.cpp
  ydb/core/grpc_services/ya.make
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/compute_actor/ya.make
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/executer_actor/ya.make
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.cpp
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.h
  ydb/core/kqp/federated_query/ya.make
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/node_service/kqp_node_service.h
  ydb/core/kqp/node_service/kqp_node_ut.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/ya.make
  ydb/tools/query_replay/query_compiler.cpp
Labels: area/queryprocessor, new-feature

#2729 fix debugging to bultin monitoring
  ydb/core/graph/shard/tx_monitoring.cpp
Labels: not-for-changelog, new-feature

#2730 Remove explicit casts
  ydb/library/benchmarks/queries/tpch/pg/q1.sql
  ydb/library/benchmarks/queries/tpch/pg/q10.sql
  ydb/library/benchmarks/queries/tpch/pg/q11.sql
  ydb/library/benchmarks/queries/tpch/pg/q14.sql
  ydb/library/benchmarks/queries/tpch/pg/q15.sql
  ydb/library/benchmarks/queries/tpch/pg/q17.sql
  ydb/library/benchmarks/queries/tpch/pg/q18.sql
  ydb/library/benchmarks/queries/tpch/pg/q19.sql
  ydb/library/benchmarks/queries/tpch/pg/q20.sql
  ydb/library/benchmarks/queries/tpch/pg/q22.sql
  ydb/library/benchmarks/queries/tpch/pg/q3.sql
  ydb/library/benchmarks/queries/tpch/pg/q5.sql
  ydb/library/benchmarks/queries/tpch/pg/q6.sql
  ydb/library/benchmarks/queries/tpch/pg/q7.sql
  ydb/library/benchmarks/queries/tpch/pg/q8.sql
  ydb/library/benchmarks/queries/tpch/pg/q9.sql
Labels: not-for-changelog

#2727 arrow serializers method for comparision
  ydb/core/formats/arrow/dictionary/object.h
  ydb/core/formats/arrow/serializer/abstract.h
  ydb/core/formats/arrow/serializer/native.h
  ydb/core/formats/arrow/transformer/abstract.h
  ydb/core/formats/arrow/transformer/dictionary.h
  ydb/core/tx/columnshard/engines/scheme/abstract/loader.h
Labels: new-feature

#2728 fix problem on search in case absent index
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/context.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/source.h
Labels: bugfix

#2733 constant separate from to reduce dependencies
  ydb/core/tx/columnshard/blobs_action/abstract/storage.h
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.h
  ydb/core/tx/columnshard/blobs_action/abstract/ya.make
  ydb/core/tx/columnshard/blobs_action/common/const.cpp
  ydb/core/tx/columnshard/blobs_action/common/const.h
  ydb/core/tx/columnshard/blobs_action/common/ya.make
Labels: not-for-changelog

#2726 Olap scheme options control
  ydb/core/kqp/gateway/behaviour/tablestore/operations/upsert_opt.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/operations/upsert_opt.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/ya.make
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/schemeshard/olap/options/schema.cpp
  ydb/core/tx/schemeshard/olap/options/schema.h
  ydb/core/tx/schemeshard/olap/options/update.cpp
  ydb/core/tx/schemeshard/olap/options/update.h
  ydb/core/tx/schemeshard/olap/options/ya.make
  ydb/core/tx/schemeshard/olap/schema/schema.cpp
  ydb/core/tx/schemeshard/olap/schema/schema.h
  ydb/core/tx/schemeshard/olap/schema/update.cpp
  ydb/core/tx/schemeshard/olap/schema/update.h
  ydb/core/tx/schemeshard/olap/schema/ya.make
  ydb/core/tx/schemeshard/olap/ya.make
Labels: new-feature

#2731 Get rid of BSAdm command and GroupReconfigureWipe event/tx
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/base/blobstorage_events.h
  ydb/core/blobstorage/vdisk/common/blobstorage_event_filter.cpp
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_bsadm.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/ya.make
  ydb/core/driver_lib/cli_base/cli_kicli.cpp
  ydb/core/driver_lib/cli_base/cli_kicli.h
  ydb/core/driver_lib/cli_utils/cli.h
  ydb/core/driver_lib/cli_utils/cli_cmds_bs.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_group.cpp
  ydb/core/driver_lib/cli_utils/ya.make
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/group_reconfigure_wipe.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/ya.make
  ydb/core/protos/blobstorage.proto
  ydb/core/protos/grpc.proto
  ydb/core/protos/msgbus.proto
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/client/grpc_client.h
  ydb/public/lib/deprecated/kicli/kikimr.cpp
Labels: not-for-changelog

#2732 storage proxy logs have been improved
  ydb/core/fq/libs/checkpoint_storage/storage_proxy.cpp
Labels: not-for-changelog
