Repository ydb-platform/ydb, pull requests merged in 2025-06, with the labels that each got.

#19071 Refactor sink: shards state updating
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
Labels: not-for-changelog

#19116 Allow last two portions on a level to be compacted
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/level/common_level.h
Labels: not-for-changelog

#13912 Use lc-buckets optimizer by default
  ydb/core/kqp/ut/olap/aggregations_ut.cpp
  ydb/core/kqp/ut/olap/dictionary_ut.cpp
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/olap/sys_view_ut.cpp
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/testlib/cs_helper.cpp
  ydb/core/testlib/cs_helper.h
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
  ydb/core/tx/tiering/ut/ut_tiers.cpp
  ydb/tests/olap/ttl_tiering/ttl_delete_s3.py
Labels: not-for-changelog

#19132 mute ydb/tests/olap/ttl_tiering/ttl_delete_s3.py.TestDeleteS3Ttl.test_data_unchanged_after_ttl_change
  .github/config/muted_ya.txt
Labels: not-for-changelog

#19093 providers/s3: prevent sigsegv on RuntimeListing with YQL service
  ydb/library/yql/providers/s3/provider/yql_s3_dq_integration.cpp
Labels: not-for-changelog

#19127 guard SecretKey in fake_storage to fix data race reported by tsan
  ydb/core/wrappers/fake_storage.h
Labels: not-for-changelog

#19105 Added support of parquet format to `ydb workload query import` and `ydb workload clickbench import files` commands.
  ydb/apps/ydb/CHANGELOG.md
  ydb/library/workload/benchmark_base/data_generator.cpp
  ydb/library/workload/benchmark_base/data_generator.h
  ydb/library/workload/benchmark_base/ya.make
  ydb/library/workload/clickbench/data_generator.cpp
  ydb/library/workload/query/query.cpp
  ydb/tests/functional/tpc/data/e1/import/test_table_2/data2.csv
  ydb/tests/functional/tpc/data/e1/import/test_table_2/data2.parquet
Labels: not-for-changelog

#19133 Use uncommitted changes for INSERT without volatile commit
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#19124 add support of check canonical results in `ydb workload query run` command.
  ydb/apps/ydb/CHANGELOG.md
  ydb/library/workload/benchmark_base/workload.cpp
  ydb/library/workload/benchmark_base/workload.h
  ydb/library/workload/clickbench/clickbench.cpp
  ydb/library/workload/clickbench/clickbench.h
  ydb/library/workload/query/query.cpp
  ydb/library/workload/tpc_base/tpc_base.cpp
  ydb/library/workload/tpc_base/tpc_base.h
  ydb/tests/functional/tpc/data/e1/run/first_query_set/1.sql.result
  ydb/tests/functional/tpc/data/e1/run/first_query_set/2.yql.result
  ydb/tests/functional/tpc/data/e1/run/second_query_set/join.sql.result
  ydb/tests/olap/load/lib/external.py
Labels: not-for-changelog

#19138 add verbose memory limit exception
  ydb/tests/library/harness/resources/default_yaml.yml
Labels: not-for-changelog

#18986 TPC-C WIP #17333
  ydb/library/workload/tpcc/histogram.cpp
  ydb/library/workload/tpcc/histogram.h
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/runner.h
  ydb/library/workload/tpcc/terminal.cpp
  ydb/library/workload/tpcc/terminal.h
  ydb/library/workload/tpcc/transaction_delivery.cpp
  ydb/library/workload/tpcc/transaction_neworder.cpp
  ydb/library/workload/tpcc/transaction_orderstatus.cpp
  ydb/library/workload/tpcc/transaction_payment.cpp
  ydb/library/workload/tpcc/transaction_simulation.cpp
  ydb/library/workload/tpcc/transaction_stocklevel.cpp
  ydb/library/workload/tpcc/transactions.h
  ydb/library/workload/tpcc/ut/histogram_ut.cpp
  ydb/library/workload/tpcc/ya.make
Labels: not-for-changelog

#18669 Compatibility test for all types
  ydb/tests/compatibility/test_data_type.py
  ydb/tests/compatibility/ya.make
  ydb/tests/datashard/lib/create_table.py
Labels: not-for-changelog

#19095 Add timeout for bootstrap in kikimr_runner.py
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#19141 Extract methods to format records with rows
  ydb/core/base/table_index.cpp
  ydb/core/base/table_index.h
  ydb/core/tx/datashard/build_index/reshuffle_kmeans.cpp
  ydb/core/tx/datashard/build_index/sample_k.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
Labels: not-for-changelog

#18720 Streaming write to index (INSERT)
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_table_resolver.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.h
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_insert_index.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#19176 YDB debug latency improvements
  ydb/public/lib/ydb_cli/commands/ydb_latency.cpp
  ydb/public/lib/ydb_cli/commands/ydb_latency.h
Labels: not-for-changelog

#19178 change ApiVersion for LEAVE_GROUP
  ydb/core/kafka_proxy/actors/kafka_api_versions_actor.cpp
Labels: not-for-changelog

#19186 fix retry for already finished read
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
Labels: not-for-changelog

#19036 Add secondary index followers compatibility test
  ydb/tests/compatibility/test_followers.py
Labels: improvement, external

#18889 Fix prefixed vector index with PK columns (#18196)
  ydb/core/kqp/ut/indexes/kqp_indexes_prefixed_vector_ut.cpp
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/build_index/kmeans_helper.cpp
  ydb/core/tx/datashard/build_index/kmeans_helper.h
  ydb/core/tx/datashard/build_index/local_kmeans.cpp
  ydb/core/tx/datashard/build_index/prefix_kmeans.cpp
  ydb/core/tx/datashard/build_index/reshuffle_kmeans.cpp
  ydb/core/tx/datashard/build_index/ut/ut_prefix_kmeans.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
Labels: not-for-changelog

#18988 Support pile identifiers for dynamic nodes too
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/base/id_wrapper.h
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/grpc_services/rpc_config.cpp
  ydb/core/grpc_services/rpc_node_registration.cpp
  ydb/core/mind/node_broker.cpp
  ydb/core/mind/node_broker__register_node.cpp
  ydb/core/mind/node_broker__scheme.h
  ydb/core/mind/node_broker_impl.h
  ydb/core/protos/node_broker.proto
  ydb/public/api/protos/ydb_discovery.proto
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/discovery/discovery.h
  ydb/public/sdk/cpp/src/client/discovery/discovery.cpp
  ydb/tests/functional/config/test_distconf.py
Labels: new-feature

#19230 ignore empty dirs when restoring with `ydb tools restore`
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#19111 expected portion size has been added for zero layer
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/level/zero_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/tests/olap/common/column_table_helper.py
  ydb/tests/olap/ttl_tiering/ttl_portion_size.py
  ydb/tests/olap/ttl_tiering/ya.make
Labels: improvement

#19203 Support export encryption for changefeeds
  ydb/core/backup/common/metadata.cpp
  ydb/core/backup/common/metadata.h
  ydb/core/tx/datashard/export_s3_uploader.cpp
  ydb/core/tx/datashard/extstorage_usage_config.h
  ydb/core/tx/schemeshard/schemeshard_import_getters.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/services/ydb/backup_ut/encrypted_backup_ut.cpp
Labels: not-for-changelog

#19019 Fix not consistent generation counters for data erasure in SchemeShard tablet and BSC tablet
  ydb/core/tx/schemeshard/schemeshard__data_erasure_manager.h
  ydb/core/tx/schemeshard/schemeshard__root_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/schemeshard__tenant_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/ut_data_erasure/ut_data_erasure.cpp
  ydb/core/tx/schemeshard/ut_data_erasure/ya.make
Labels: bugfix

#19249 Increment YDB CLI version to 2.22.0
  ydb/apps/ydb/CHANGELOG.md
  ydb/apps/ydb/version.txt
Labels: area/cli, not-for-changelog

#18861 Vector index compatibility
  ydb/tests/compatibility/test_vector_index.py
  ydb/tests/compatibility/ya.make
Labels: not-for-changelog

#19215 generic lookup: Reduce limit for MaxKeysInRequest to 100
  ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
Labels: not-for-changelog

#19128 Refactor FillVectorIndex state machine (#18579)
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: not-for-changelog

#19243 Fixed diplodoc errors in arcadia
  ydb/docs/ru/core/changelog-server.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/yql/reference/_includes/vector_search_approximate.md
  ydb/docs/ru/core/yql/reference/_includes/vector_search_exact.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/vector_index.md
  ydb/docs/ru/core/yql/reference/syntax/select/index.md
  ydb/docs/ru/core/yql/reference/udf/list/knn.md
Labels: documentation

#19265 Library import 250604-0050
  build/conf/python.conf
  build/external_resources/ymake/public.resources.json
  build/external_resources/ymake/resources.json
  build/mapping.conf.json
  build/ymake.core.conf
  contrib/libs/croaring/.yandex_meta/override.nix
  contrib/libs/croaring/include/roaring/roaring.h
  contrib/libs/croaring/include/roaring/roaring64.h
  contrib/libs/croaring/src/art/art.c
  contrib/libs/croaring/src/roaring64.c
  contrib/libs/croaring/ya.make
  contrib/libs/tcmalloc/patches/020-user-data.patch
  contrib/libs/tcmalloc/tcmalloc/internal/logging.h
  contrib/libs/tcmalloc/tcmalloc/stack_trace_table.cc
  contrib/python/multidict/.dist-info/METADATA
  contrib/python/multidict/multidict/__init__.py
  contrib/python/multidict/multidict/_multidict.c
  contrib/python/multidict/multidict/_multidict_py.py
  contrib/python/multidict/multidict/_multilib/views.h
  contrib/python/multidict/tests/test_multidict.py
  contrib/python/multidict/tests/test_multidict_benchmarks.py
  contrib/python/multidict/tests/test_mutable_multidict.py
  contrib/python/multidict/tests/test_version.py
  contrib/python/multidict/ya.make
  library/cpp/lwtrace/mon/mon_lwtrace.cpp
  library/cpp/monlib/metrics/metric_registry.cpp
  library/cpp/monlib/metrics/metric_registry.h
  library/cpp/threading/chunk_queue/queue.h
  ydb/ci/rightlib.txt
  yql/essentials/ast/yql_constraint.cpp
  yql/essentials/core/peephole_opt/yql_opt_peephole_physical.cpp
  yql/essentials/core/ut/yql_expr_constraint_ut.cpp
  yql/essentials/core/yql_expr_constraint.cpp
  yql/essentials/core/yql_opt_utils.cpp
  yql/essentials/core/yql_opt_utils.h
  yql/essentials/minikql/comp_nodes/mkql_block_logical.cpp
  yql/essentials/minikql/comp_nodes/ut/mkql_block_logical_ut.cpp
  yql/essentials/minikql/comp_nodes/ut/ya.make.inc
  yql/essentials/sql/v1/format/sql_format_ut.h
  yql/essentials/sql/v1/node.h
  yql/essentials/sql/v1/query.cpp
  yql/essentials/sql/v1/sql_expression.cpp
  yql/essentials/sql/v1/sql_ut_common.h
  yql/essentials/tests/sql/minirun/part3/canondata/result.json
  yql/essentials/tests/sql/sql2yql/canondata/result.json
  yql/essentials/tests/sql/sql2yql/canondata/test_sql_format.test_join-prune_keys_YQL-19979_/formatted.sql
  yql/essentials/tests/sql/suites/join/prune_keys_YQL-19979.sql
  yt/cpp/mapreduce/interface/config.h
  yt/yql/tests/sql/suites/blocks/boolean_ops_scalar.cfg
  yt/yql/tests/sql/suites/blocks/boolean_ops_scalar.sql
  yt/yt/client/driver/driver.cpp
  yt/yt_proto/yt/client/api/rpc_proxy/proto/api_service.proto
Labels: rightlib

#19266 fix darwin build
  ydb/library/workload/benchmark_base/data_generator.cpp
Labels: not-for-changelog

#19212 log expectations for split-processing control
  ydb/core/formats/arrow/save_load/loader.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/merger.cpp
  ydb/core/tx/columnshard/splitter/batch_slice.h
  ydb/core/tx/columnshard/splitter/column_info.h
  ydb/core/tx/columnshard/splitter/settings.h
  ydb/library/formats/arrow/splitter/similar_packer.cpp
  ydb/library/formats/arrow/splitter/stats.h
  ydb/library/formats/arrow/splitter/ya.make
Labels: improvement

#18859 Reconfig Board
  ydb/core/base/board_lookup.cpp
  ydb/core/base/board_publish.cpp
  ydb/core/base/board_subscriber_ut.cpp
  ydb/core/base/statestorage.cpp
  ydb/core/base/statestorage.h
  ydb/core/base/statestorage_guardian.cpp
  ydb/core/base/statestorage_impl.h
  ydb/core/base/statestorage_monitoring.cpp
  ydb/core/base/statestorage_proxy.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_state_storage.cpp
  ydb/core/blobstorage/nodewarden/node_warden_resource.cpp
  ydb/core/tx/scheme_board/monitoring.cpp
  ydb/core/tx/scheme_board/subscriber.cpp
  ydb/tests/functional/config/test_distconf.py
  ydb/tests/stress/common/common.py
  ydb/tests/stress/reconfig_state_storage_workload/tests/reconfig_state_storage_workload_test.py
  ydb/tests/stress/reconfig_state_storage_workload/tests/test_board_workload.py
  ydb/tests/stress/reconfig_state_storage_workload/tests/test_state_storage_workload.py
  ydb/tests/stress/reconfig_state_storage_workload/tests/ya.make
  ydb/tests/stress/reconfig_state_storage_workload/workload/__init__.py
  ydb/tests/stress/reconfig_state_storage_workload/ya.make
  ydb/tests/stress/ya.make
Labels: new-feature

#19259 Rename for the sake of windows build
  ydb/core/kafka_proxy/actors/control_plane_common.h
  ydb/core/kafka_proxy/actors/kafka_create_topics_actor.cpp
Labels: not-for-changelog

#19246 Handle unhandled exceptions during build index on SchemeShard
  ydb/core/tx/schemeshard/schemeshard_build_index__cancel.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__create.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__forget.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__get.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__list.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index_tx_base.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index_tx_base.h
  ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
Labels: not-for-changelog

#19308 Reset counters
  ydb/core/cms/console/console_configs_provider.h
Labels: not-for-changelog

#19290 Library import 250604-0942
  build/conf/ts/ts_test.conf
  build/plugins/nots.py
  library/python/testing/yatest_common/yatest/common/process.py
  ydb/ci/rightlib.txt
  yql/essentials/core/peephole_opt/yql_opt_peephole_physical.cpp
  yql/essentials/udfs/common/string/string_udf.cpp
  yt/cpp/mapreduce/http/helpers.cpp
  yt/cpp/mapreduce/http/helpers.h
  yt/yt/core/concurrency/execution_stack.cpp
Labels: rightlib

#19326 Add RAM for test with sanitizers
  ydb/core/tx/conveyor_composite/ut/ya.make
Labels: not-for-changelog

#19252 Prepare StreamLookupWorker for index write
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.h
Labels: not-for-changelog

#19248 Support export encryption for views/topics
  ydb/core/backup/common/metadata.cpp
  ydb/core/backup/common/metadata.h
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/schemeshard_export_uploaders.cpp
  ydb/core/tx/schemeshard/schemeshard_export_uploaders.h
  ydb/core/tx/schemeshard/schemeshard_export_uploaders_fallback.cpp
  ydb/services/ydb/backup_ut/encrypted_backup_ut.cpp
  ydb/services/ydb/backup_ut/s3_backup_test_base.h
  ydb/services/ydb/backup_ut/ya.make
Labels: not-for-changelog

#19303 New CHANGEFEED's option: SCHEMA_CHANGES
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/sys_view/show_create/create_table_formatter.cpp
  ydb/core/sys_view/ut_kqp.cpp
  ydb/core/ydb_convert/table_description.cpp
  ydb/public/api/protos/ydb_table.proto
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
  ydb/public/sdk/cpp/src/client/table/table.cpp
Labels: not-for-changelog

#19233 test log scenario has been fixed
  .github/config/muted_ya.txt
  ydb/tests/olap/test_log_scenario.py
Labels: not-for-changelog

#19336 Add reconfig_state_storage_workload to recourse in ydb/tests/stress
  ydb/tests/stress/ya.make
Labels: not-for-changelog

#19334 restore ascii ignore case match
  .github/config/muted_ya.txt
  ydb/core/formats/arrow/program/kernel_logic.h
  ydb/core/kqp/opt/physical/predicate_collector.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#19223 Fix TPC-C transactions logic and improve logs (#17333)
  ydb/library/workload/tpcc/common_queries.cpp
  ydb/library/workload/tpcc/constants.h
  ydb/library/workload/tpcc/transaction_delivery.cpp
  ydb/library/workload/tpcc/transaction_neworder.cpp
  ydb/library/workload/tpcc/transaction_orderstatus.cpp
  ydb/library/workload/tpcc/transaction_payment.cpp
  ydb/library/workload/tpcc/transaction_simulation.cpp
  ydb/library/workload/tpcc/transaction_stocklevel.cpp
Labels: not-for-changelog

#19338 fix style and import tests in reconfig_state_storage_workload
  ydb/tests/stress/reconfig_state_storage_workload/workload/__init__.py
  ydb/tests/stress/reconfig_state_storage_workload/workload/ya.make
Labels: not-for-changelog

#19322 streamlookup/MultiGet: fix running over MaxKeysForLookup limit
  ydb/library/yql/dq/actors/input_transforms/dq_input_transform_lookup.cpp
  ydb/tests/fq/generic/streaming/test_join.py
Labels: not-for-changelog

#19363 Removed a link to a missing document
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/ru/core/changelog-cli.md
Labels: documentation

#19312 Handle unhandled exceptions during build index SchemeShard init
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__monitoring.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__create.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index_tx_base.cpp
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
Labels: not-for-changelog

#19340 fix test compatibility data type
  ydb/tests/compatibility/test_data_type.py
Labels: not-for-changelog

#19299 Add jitter and exponential delay to configs request
  ydb/core/config/init/init.cpp
  ydb/tests/functional/ydb_cli/test_ydb_backup.py
  ydb/tests/functional/ydb_cli/ya.make
  ydb/tests/library/harness/kikimr_cluster_interface.py
Labels: not-for-changelog

#19300 Refactor write actor buffers
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
Labels: not-for-changelog

#19386 Add External M1
  ydb/tests/olap/load/lib/external.py
Labels: not-for-changelog

#19357 Rename Statement column to CreateQuery
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/sys_view/common/schema.h
  ydb/core/sys_view/show_create/create_table_formatter.cpp
  ydb/core/sys_view/show_create/show_create.cpp
  ydb/core/sys_view/ut_kqp.cpp
  ydb/tests/stress/show_create/view/workload/__init__.py
Labels: not-for-changelog

#19355 add retries to bulk upsert in scenario tests
  ydb/tests/olap/scenario/helpers/scenario_tests_helper.py
Labels: not-for-changelog

#19398 Fix state usage in csv files upload
  ydb/apps/ydb/CHANGELOG.md
  ydb/library/workload/benchmark_base/data_generator.cpp
Labels: not-for-changelog

#19365 Fix CTAS with view
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/host/kqp_statement_rewrite.h
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
Labels: not-for-changelog

#19401 Use `/tmp` for temporary files when download binary by ydbd_slice instead `/home`
  ydb/tools/ydbd_slice/nodes.py
Labels: not-for-changelog

#19366 Fix quorum for distconf when in Bridge mode
  ydb/core/base/blobstorage.h
  ydb/core/base/bridge.h
  ydb/core/base/id_wrapper.h
  ydb/core/blobstorage/dsproxy/bridge/bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_quorum.h
  ydb/core/blobstorage/nodewarden/ya.make
  ydb/library/services/services.proto
Labels: not-for-changelog

#19281 Autodropping stress test
  ydb/tests/stress/s3_backups/__main__.py
  ydb/tests/stress/s3_backups/tests/test_workload.py
  ydb/tests/stress/s3_backups/tests/ya.make
  ydb/tests/stress/s3_backups/workload/__init__.py
  ydb/tests/stress/s3_backups/workload/ya.make
  ydb/tests/stress/s3_backups/ya.make
  ydb/tests/stress/ya.make
Labels: not-for-changelog

#19457 Add External B1
  ydb/tests/olap/load/lib/external.py
Labels: not-for-changelog

#19463 Fixes for BATCH operations for tables with index and empty result rows
  ydb/core/kqp/executer_actor/kqp_partitioned_executer.cpp
  ydb/core/kqp/opt/kqp_opt_kql.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_delete_ut.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_update_ut.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
Labels: not-for-changelog

#19135 Added new publish materials
  ydb/docs/ru/core/public-materials/_includes/conferences/2024/joker.md
  ydb/docs/ru/core/public-materials/_includes/conferences/2025/misc.md
  ydb/docs/ru/core/public-materials/videos.md
Labels: documentation

#19452 Enable tag event and nightly builds
  .github/actions/test_ya/action.yml
  .github/workflows/nightly_build.yml
Labels: not-for-changelog

#19324 Remove adding new shards for data erasure from SetPartitioning
  ydb/core/tx/schemeshard/schemeshard__operation_common.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_copy_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_split_merge.cpp
  ydb/core/tx/schemeshard/schemeshard__tenant_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/schemeshard_private.h
Labels: not-for-changelog

#19437 Extract TTxShardReply to deduplicate code
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
Labels: not-for-changelog

#19390 Universal test that checks common export encryption requirements
  ydb/services/ydb/backup_ut/encrypted_backup_ut.cpp
  ydb/services/ydb/backup_ut/s3_backup_test_base.h
  ydb/services/ydb/backup_ut/ya.make
Labels: not-for-changelog

#19475 Implement TPC-C import and update TPC-C CLI (#17333)
  ydb/library/workload/tpcc/constants.h
  ydb/library/workload/tpcc/data_splitter.cpp
  ydb/library/workload/tpcc/data_splitter.h
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/import.h
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/runner.h
  ydb/library/workload/tpcc/terminal.cpp
  ydb/library/workload/tpcc/terminal.h
  ydb/library/workload/tpcc/ut/data_splitter_ut.cpp
  ydb/library/workload/tpcc/util.cpp
  ydb/library/workload/tpcc/util.h
  ydb/library/workload/tpcc/ya.make
  ydb/library/workload/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_workload.cpp
  ydb/public/lib/ydb_cli/commands/ydb_workload_tpcc.cpp
  ydb/public/lib/ydb_cli/commands/ydb_workload_tpcc.h
Labels: not-for-changelog

#19502 The TPersQueueTest::TopicServiceCommitOffset test is flashing
  ydb/services/persqueue_v1/persqueue_ut.cpp
Labels: not-for-changelog

#19518 Increment YDB CLI version to 2.22.1
  ydb/apps/ydb/CHANGELOG.md
  ydb/apps/ydb/version.txt
Labels: area/cli, not-for-changelog

#19513 Fix start delay for info exchanger
  ydb/core/kqp/rm_service/kqp_resource_info_exchanger.cpp
Labels: not-for-changelog

#19483 initial commit: DqHashCombine, DqHashAggregate
  ydb/core/kqp/runtime/kqp_program_builder.cpp
  ydb/core/kqp/runtime/kqp_program_builder.h
  ydb/core/kqp/tools/combiner_perf/factories.cpp
  ydb/core/kqp/tools/combiner_perf/kqp_setup.h
  ydb/core/kqp/tools/combiner_perf/simple.cpp
  ydb/core/kqp/tools/combiner_perf/simple_last.cpp
  ydb/core/kqp/tools/combiner_perf/ya.make
  ydb/library/yql/dq/comp_nodes/dq_hash_aggregate.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_aggregate.h
  ydb/library/yql/dq/comp_nodes/dq_hash_combine.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_combine.h
  ydb/library/yql/dq/comp_nodes/dq_hash_operator_common.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_operator_common.h
  ydb/library/yql/dq/comp_nodes/dq_hash_operator_serdes.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_operator_serdes.h
  ydb/library/yql/dq/comp_nodes/dq_program_builder.cpp
  ydb/library/yql/dq/comp_nodes/dq_program_builder.h
  ydb/library/yql/dq/comp_nodes/ya.make
  ydb/library/yql/dq/comp_nodes/yql_common_dq_factory.cpp
Labels: not-for-changelog

#19462 composite conveyor usage
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/kqp/query_data/kqp_predictor.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/console_config.proto
  ydb/core/testlib/test_client.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/actor/actor.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetch_steps.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
  ydb/core/tx/columnshard/engines/writer/buffer/actor2.cpp
  ydb/core/tx/columnshard/normalizer/portion/normalizer.h
  ydb/core/tx/columnshard/operations/batch_builder/builder.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/operations/write.cpp
  ydb/core/tx/columnshard/ya.make
  ydb/core/tx/conveyor/usage/service.h
  ydb/core/tx/conveyor_composite/service/category.cpp
  ydb/core/tx/conveyor_composite/service/category.h
  ydb/core/tx/conveyor_composite/service/common.cpp
  ydb/core/tx/conveyor_composite/service/common.h
  ydb/core/tx/conveyor_composite/service/counters.cpp
  ydb/core/tx/conveyor_composite/service/counters.h
  ydb/core/tx/conveyor_composite/service/events.h
  ydb/core/tx/conveyor_composite/service/manager.h
  ydb/core/tx/conveyor_composite/service/process.h
  ydb/core/tx/conveyor_composite/service/scope.cpp
  ydb/core/tx/conveyor_composite/service/scope.h
  ydb/core/tx/conveyor_composite/service/service.cpp
  ydb/core/tx/conveyor_composite/service/service.h
  ydb/core/tx/conveyor_composite/service/worker.cpp
  ydb/core/tx/conveyor_composite/service/worker.h
  ydb/core/tx/conveyor_composite/service/workers_pool.cpp
  ydb/core/tx/conveyor_composite/service/workers_pool.h
  ydb/core/tx/conveyor_composite/usage/common.cpp
  ydb/core/tx/conveyor_composite/usage/common.h
  ydb/core/tx/conveyor_composite/usage/config.cpp
  ydb/core/tx/conveyor_composite/usage/config.h
  ydb/core/tx/conveyor_composite/usage/events.cpp
  ydb/core/tx/conveyor_composite/usage/events.h
  ydb/core/tx/conveyor_composite/usage/service.h
  ydb/core/tx/conveyor_composite/ut/ut_simple.cpp
  ydb/library/signals/owner.cpp
Labels: improvement

#19482 Docs: Parameterized decimal
  ydb/docs/en/core/reference/ydb-cli/_includes/workload/init_options_tpc.md
  ydb/docs/en/core/yql/reference/types/json.md
  ydb/docs/en/core/yql/reference/types/primitive.md
  ydb/docs/ru/core/reference/ydb-cli/_includes/workload/init_options_tpc.md
  ydb/docs/ru/core/yql/reference/types/primitive.md
Labels: documentation

#19532 fix build on Macs
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/terminal.cpp
  ydb/library/workload/tpcc/transaction_delivery.cpp
  ydb/library/workload/tpcc/transaction_neworder.cpp
  ydb/library/workload/tpcc/transaction_orderstatus.cpp
  ydb/library/workload/tpcc/transaction_payment.cpp
  ydb/library/workload/tpcc/transaction_stocklevel.cpp
  ydb/library/workload/tpcc/util.h
Labels: not-for-changelog

#19376 Add read iterator cancellation to ReadRows RPC
  ydb/core/grpc_services/rpc_read_rows.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/opt/kqp_kv_ut.cpp
  ydb/core/tx/datashard/datashard__read_iterator.cpp
Labels: improvement

#19492 Support scepterless operations in distconf for bridge mode
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_storage_config.cpp
  ydb/core/blobstorage/nodewarden/distconf_mon.cpp
  ydb/core/blobstorage/nodewarden/distconf_scatter_gather.cpp
Labels: not-for-changelog

#19522 25-1: impl drain timeout config (#19323)
  ydb/core/driver_lib/run/run.cpp
  ydb/core/driver_lib/run/run.h
  ydb/core/protos/config.proto
Labels: bugfix

#19140 Add logs to fast tests
  .github/scripts/analytics/test_history_fast.py
Labels: not-for-changelog

#19555 Update muted_ya.txt
  .github/config/muted_ya.txt
Labels: not-for-changelog, mute-unmute

#18969 Impl compatibility tests for BATCH operations
  ydb/tests/compatibility/test_batch_operations.py
  ydb/tests/compatibility/ya.make
  ydb/tests/library/harness/kikimr_config.py
Labels: not-for-changelog

#19517 Fix CTAS Not Null
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#19359 filter iterator corrections
  ydb/core/formats/arrow/arrow_filter.cpp
  ydb/core/formats/arrow/arrow_filter.h
  ydb/core/formats/arrow/reader/batch_iterator.h
  ydb/core/tx/columnshard/common/snapshot.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/default_fetching.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/sub_columns_fetching.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/merge.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sync_points/limit.h
Labels: not-for-changelog

#18444 YDB FQ: support `OpenSearch` as an external data source
  ydb/core/external_sources/external_source_factory.cpp
  ydb/library/yql/providers/common/db_id_async_resolver/database_type.cpp
  ydb/library/yql/providers/common/db_id_async_resolver/database_type.h
  ydb/library/yql/providers/generic/actors/yql_generic_provider_factories.cpp
  ydb/library/yql/providers/generic/connector/tests/utils/run/kqprun.py
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: new-feature, external

#19515 Refactor topic-to-table docs for C++ SDK
  ydb/docs/en/core/reference/ydb-sdk/topic.md
  ydb/docs/ru/core/reference/ydb-sdk/topic.md
Labels: documentation

#19572 CDC stress test (basic)
  ydb/tests/stress/cdc/__main__.py
  ydb/tests/stress/cdc/tests/test_workload.py
  ydb/tests/stress/cdc/tests/ya.make
  ydb/tests/stress/cdc/workload/__init__.py
  ydb/tests/stress/cdc/workload/ya.make
  ydb/tests/stress/cdc/ya.make
  ydb/tests/stress/ya.make
Labels: not-for-changelog

#19594 ci: add stable-25-1-2 to nightly build list
  .github/workflows/nightly_build.yml
Labels: not-for-changelog

#19495 bump acl version, add list_permissions
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/viewer_acl.h
Labels: not-for-changelog

#19287 Unmute CompactionVariants #17929
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/combinatory/select.cpp
  ydb/core/kqp/ut/olap/combinatory/variator.cpp
  ydb/core/kqp/ut/olap/combinatory/variator.h
  ydb/core/kqp/ut/olap/dictionary_ut.cpp
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/kqp/ut/olap/ya.make
Labels: not-for-changelog

#19590 Use Y_ENSURE for usage errors in intersection tree
  ydb/library/intersection_tree/intersection_tree.h
Labels: not-for-changelog

#19542 Split TLoginProvider::LoginUser to several methods
  ydb/library/login/login.cpp
  ydb/library/login/login.h
Labels: not-for-changelog

#19583 ensure that there aren't 2 locals on 1 node in 1 hive
  ydb/core/mind/local.cpp
Labels: not-for-changelog

#19596 Fix optimizer comparison when protobuf serializations are the same
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
Labels: not-for-changelog

#19547 YDBDOCS-1155: remove incorrect entries from redirects.yaml
  ydb/docs/redirects.yaml
Labels: documentation

#19599 Add basic validation for tiling compaction settings
  ydb/core/tx/columnshard/engines/storage/optimizer/tiling/tiling.cpp
Labels: not-for-changelog

#19617 On Windows build YDB cli with UNICODE defined (#17333)
  ydb/apps/ydb/ya.make
Labels: not-for-changelog

#19612 Properly rewrite log capturing (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/log_backend.cpp
  ydb/library/workload/tpcc/log_backend.h
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/stderr_capture.cpp
  ydb/library/workload/tpcc/stderr_capture.h
  ydb/library/workload/tpcc/ut/log_capture_ut.cpp
  ydb/library/workload/tpcc/ut/ya.make
  ydb/library/workload/tpcc/ya.make
Labels: not-for-changelog

#19597 clean deprecated immediate write option
  ydb/core/protos/feature_flags.proto
  ydb/core/transfer/transfer_writer.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/columnshard.h
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.h
  ydb/core/tx/data_events/columnshard_splitter.cpp
  ydb/core/tx/data_events/columnshard_splitter.h
  ydb/core/tx/data_events/shard_writer.cpp
  ydb/core/tx/data_events/shard_writer.h
  ydb/core/tx/data_events/shards_splitter.h
  ydb/core/tx/tx_proxy/rpc_long_tx.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: improvement

#19631 Added error forwarding
  ydb/tests/olap/scenario/conftest.py
Labels: not-for-changelog

#19630 add new test #14696
  ydb/tests/olap/data_quotas/test_quota_exhaustion.py
Labels: not-for-changelog

#19662 TPC-C ui/text cleanup (#17333)
  ydb/library/workload/tpcc/runner.cpp
Labels: not-for-changelog

#19627 add test for full table cleaning control
  ydb/core/kqp/ut/olap/optimizer_ut.cpp
Labels: improvement

#19664 additional logging
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
Labels: improvement

#19660 generate internal path id
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/columnshard/tables_manager.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: not-for-changelog

#19665 Fix categories usage with scope limits
  ydb/core/tx/conveyor_composite/service/category.cpp
  ydb/core/tx/conveyor_composite/service/category.h
  ydb/core/tx/conveyor_composite/service/workers_pool.cpp
Labels: bugfix

#19658 Move TBillingStats to schemeshard_billing_helpers
  ydb/core/tx/schemeshard/schemeshard_billing_helpers.cpp
  ydb/core/tx/schemeshard/schemeshard_billing_helpers.h
  ydb/core/tx/schemeshard/schemeshard_build_index_tx_base.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: not-for-changelog

#19632 Fix shard key types verify in SS monitoring
  ydb/core/tx/schemeshard/schemeshard__monitoring.cpp
Labels: not-for-changelog

#19605 autosplit doc for go
  ydb/docs/en/core/reference/ydb-sdk/topic.md
  ydb/docs/ru/core/reference/ydb-sdk/topic.md
Labels: documentation

#19679 YDB FQ: add default protocol for OpenSearch
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
Labels: new-feature

#19113 Release notes 24.4.4.12
  ydb/docs/en/core/changelog-server.md
  ydb/docs/en/core/downloads/ydb-open-source-database.md
  ydb/docs/ru/core/changelog-server.md
  ydb/docs/ru/core/downloads/ydb-open-source-database.md
Labels: documentation

#19653 OIDC needs pass tracing headers
  ydb/mvp/oidc_proxy/oidc_protected_page.cpp
  ydb/mvp/oidc_proxy/oidc_protected_page.h
Labels: improvement

#19692 Fix request unit calculator references and description
  ydb/core/tx/schemeshard/schemeshard_billing_helpers.cpp
  ydb/core/tx/schemeshard/schemeshard_billing_helpers.h
Labels: not-for-changelog

#19626 Fix ftxui build in windows
  contrib/libs/ftxui/ya.make
Labels: not-for-changelog

#19170 Docs: describe show create
  ydb/docs/en/core/yql/reference/syntax/index.md
  ydb/docs/en/core/yql/reference/syntax/show_create.md
  ydb/docs/en/core/yql/reference/syntax/toc_i.yaml
  ydb/docs/ru/core/yql/reference/syntax/index.md
  ydb/docs/ru/core/yql/reference/syntax/show_create.md
  ydb/docs/ru/core/yql/reference/syntax/toc_i.yaml
Labels: documentation

#19598 Support bridge mode for BSC storage pools
  ydb/core/base/bridge.h
  ydb/core/blobstorage/dsproxy/dsproxy_impl.h
  ydb/core/blobstorage/dsproxy/dsproxy_state.cpp
  ydb/core/blobstorage/groupinfo/blobstorage_groupinfo.cpp
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_genconfig.cpp
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/config.h
  ydb/core/mind/bscontroller/config_fit_groups.cpp
  ydb/core/mind/bscontroller/group_geometry_info.h
  ydb/core/mind/bscontroller/group_mapper.cpp
  ydb/core/mind/bscontroller/group_mapper.h
  ydb/core/mind/bscontroller/group_mapper_ut.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/mind/bscontroller/select_groups.h
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/mind/bscontroller/storage_stats_calculator.cpp
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_bs_controller_/flat_bs_controller.schema
Labels: not-for-changelog

#19285 [docs] hide education for audience = "tech"
  ydb/docs/ru/core/toc_i.yaml
Labels: documentation

#19505 [docs] fix mistype in ru initial-deployment.md
  ydb/docs/ru/core/devops/deployment-options/manual/initial-deployment.md
Labels: documentation

#19695 Add tpch upload test
  ydb/tests/functional/tpc/medium/test_upload.py
  ydb/tests/functional/tpc/medium/ya.make
  ydb/tests/olap/load/lib/upload.py
  ydb/tests/olap/load/lib/ya.make
  ydb/tests/olap/load/test_upload.py
  ydb/tests/olap/load/ya.make
Labels: not-for-changelog

#19716 Revert "Fix ftxui build in windows (#17333, #19626)"
  contrib/libs/ftxui/ya.make
Labels: not-for-changelog

#19720 Update muted_ya.txt
  .github/config/muted_ya.txt
Labels: not-for-changelog

#19694 Add delete row by explicit row id test (#14694)
  ydb/tests/olap/delete/base.py
  ydb/tests/olap/delete/test_delete_by_explicit_row_id.py
  ydb/tests/olap/delete/ya.make
Labels: not-for-changelog

#19395 Nemesis: OLTP + new report
  .github/config/muted_ya.txt
  ydb/tests/functional/tpc/medium/test_workload_oltp.py
  ydb/tests/functional/tpc/medium/ya.make
  ydb/tests/olap/lib/allure_utils.py
  ydb/tests/olap/lib/remote_execution.py
  ydb/tests/olap/lib/ydb_cluster.py
  ydb/tests/olap/load/lib/conftest.py
  ydb/tests/olap/load/lib/workload_executor.py
  ydb/tests/olap/load/lib/workload_oltp.py
  ydb/tests/olap/load/lib/workload_simple_queue.py
  ydb/tests/olap/load/lib/ya.make
  ydb/tests/olap/load/test_workload_oltp.py
  ydb/tests/olap/load/ya.make
Labels: not-for-changelog

#19762 Fix bug with absolute paths in workloads
  ydb/apps/ydb/CHANGELOG.md
  ydb/library/workload/benchmark_base/workload.cpp
  ydb/library/workload/benchmark_base/workload.h
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestClickbenchInit.test_s1_column/s1_column
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestClickbenchInit.test_s1_row/s1_row
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestClickbenchInit.test_s1_s3/s1_s3
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpcdsInit.test_s100_column/s100_column
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpcdsInit.test_s1_column/s1_column
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpcdsInit.test_s1_column_decimal/s1_column_decimal
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpcdsInit.test_s1_column_decimal_ydb/s1_column_decimal_ydb
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpcdsInit.test_s1_row/s1_row
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpcdsInit.test_s1_s3/s1_s3
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpchInit.test_s100_column/s100_column
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpchInit.test_s1_column/s1_column
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpchInit.test_s1_column_decimal/s1_column_decimal
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpchInit.test_s1_column_decimal_ydb/s1_column_decimal_ydb
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpchInit.test_s1_row/s1_row
  ydb/tests/functional/benchmarks_init/canondata/test_init.TestTpchInit.test_s1_s3/s1_s3
Labels: bugfix

#19765 fix whiteboard retries
  ydb/core/health_check/health_check.cpp
Labels: not-for-changelog

#19772 first version of AI annotation for the codebase
  AGENTS.md
Labels: not-for-changelog

#19771 Tpcc cli and import cleanup (#17333)
  ydb/library/workload/tpcc/constants.h
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/runner.h
  ydb/public/lib/ydb_cli/commands/ydb_workload_tpcc.cpp
Labels: not-for-changelog

#18696 Kafka api transactions in kqp
  ydb/core/kafka_proxy/actors/kafka_transaction_actor.cpp
  ydb/core/kafka_proxy/kafka.h
  ydb/core/kafka_proxy/kafka_producer_instance_id.h
  ydb/core/kafka_proxy/ut/kafka_test_client.cpp
  ydb/core/kafka_proxy/ut/kafka_test_client.h
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_query_state.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/topics/kqp_topics.cpp
  ydb/core/kqp/topics/kqp_topics.h
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/write_id.cpp
  ydb/core/persqueue/write_id.h
  ydb/core/persqueue/writer/writer.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/pqconfig.proto
Labels: new-feature

#18292 add committedMetadata in PQ tablet
  ydb/core/kafka_proxy/actors/kafka_offset_fetch_actor.cpp
  ydb/core/kafka_proxy/kafka_events.h
  ydb/core/kafka_proxy/ut/kafka_test_client.h
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/user_info.cpp
  ydb/core/persqueue/user_info.h
  ydb/core/protos/msgbus_pq.proto
  ydb/core/protos/pqconfig.proto
Labels: not-for-changelog

#19791 Tpcc import imrovements (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/ut/data_splitter_ut.cpp
  ydb/public/lib/ydb_cli/commands/ydb_workload_tpcc.cpp
Labels: not-for-changelog

#19567 Add operation increment in datashard
  ydb/core/io_formats/cell_maker/cell_maker.cpp
  ydb/core/io_formats/cell_maker/cell_maker.h
  ydb/core/protos/data_events.proto
  ydb/core/scheme/scheme_tablecell.cpp
  ydb/core/scheme/scheme_tablecell.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
  ydb/core/tx/columnshard/operations/batch_builder/builder.cpp
  ydb/core/tx/data_events/common/modification_type.h
  ydb/core/tx/data_events/write_data.h
  ydb/core/tx/datashard/datashard__engine_host.cpp
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/datashard/ya.make
Labels: new-feature

#19565 [KQP] A point consolidation for parallel ReadRange
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_partition_helper.cpp
  ydb/core/kqp/executer_actor/kqp_partition_helper.h
  ydb/core/kqp/ut/query/kqp_stats_ut.cpp
  ydb/core/kqp/ut/scan/kqp_point_consolidation_ut.cpp
  ydb/core/kqp/ut/scan/ya.make
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#19807 Optimize the writing session creation time
  ydb/core/persqueue/writer/writer.cpp
Labels: performance

#19822 Tests for uncommited changes dml at ColumnShard
  ydb/core/kqp/ut/tx/kqp_sink_locks_ut.cpp
Labels: not-for-changelog

#19766 [KQP] Fix nullptr errors with BATCH operations and not created tables
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_delete_ut.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_update_ut.cpp
Labels: not-for-changelog

#19820 fix: added cluster.yaml to deploy_tools
  ydb/tests/stability/tool/__main__.py
Labels: not-for-changelog

#19503 Fix bug with long timeout when consumer left ungracefully
  ydb/core/kafka_proxy/actors/kafka_balance_actor_sql.cpp
  ydb/core/kafka_proxy/actors/kafka_balancer_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_balancer_actor.h
Labels: not-for-changelog

#19856 Add local tests for clickbench pg
  .github/config/muted_ya.txt
  ydb/tests/functional/tpc/medium/test_clickbench.py
Labels: not-for-changelog

#19857 Fix workloads working with empty path
  ydb/library/workload/benchmark_base/workload.cpp
  ydb/library/workload/query/query.cpp
  ydb/tests/functional/tpc/medium/test_external.py
  ydb/tests/olap/lib/allure_utils.py
  ydb/tests/olap/lib/results_processor.py
  ydb/tests/olap/lib/ydb_cluster.py
  ydb/tests/olap/load/lib/clickbench.py
  ydb/tests/olap/load/lib/conftest.py
  ydb/tests/olap/load/lib/external.py
  ydb/tests/olap/load/lib/import_csv.py
  ydb/tests/olap/load/lib/tpcds.py
  ydb/tests/olap/load/lib/tpch.py
  ydb/tests/olap/load/lib/upload.py
  ydb/tests/olap/s3_import/large/test_large_import.py
  ydb/tests/olap/scenario/helpers/scenario_tests_helper.py
Labels: not-for-changelog

#19860 Fix compilation error darwin
  ydb/core/ymq/actor/cloud_events/cloud_events.h
Labels: bugfix

#19853 fix deadline logging
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/actor/actor.h
Labels: bugfix

#19344 Add seed nodes option to ydbd
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/config/init/init_noop.cpp
  ydb/core/config/init/init_ut.cpp
  ydb/core/config/init/mock.h
  ydb/core/config/init/ya.make
  ydb/core/driver_lib/cli_utils/cli_cmds_server.cpp
  ydb/core/driver_lib/cli_utils/cli_cmds_server.h
  ydb/core/driver_lib/cli_utils/cli_cmds_validate_config.cpp
  ydb/tests/functional/config/test_distconf.py
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#19866 ignore size_bytes completely
  ydb/core/viewer/tests/test.py
Labels: area/ui, not-for-changelog

#19808 The writing time for blobs should not decrease
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_compaction.cpp
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/read.h
  ydb/core/persqueue/ut/pq_ut.cpp
Labels: not-for-changelog

#19506 #9056 Improve YDB CLI completion
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/commands/interactive/complete/dummy_name_service.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/dummy_name_service.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/complete/yql_completer.cpp
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.cpp
  ydb/public/lib/ydb_cli/commands/interactive/ya.make
Labels: not-for-changelog, external

#19783 [docs] fix mistype in ydb-open-source-database.md
  ydb/docs/en/core/downloads/ydb-open-source-database.md
Labels: documentation

#19835 Completely remove LoopStep from SchemeShard TxState
  .github/config/muted_ya.txt
  ydb/core/tx/schemeshard/schemeshard__operation_create_restore_incremental_backup.cpp
  ydb/core/tx/schemeshard/schemeshard_tx_infly.h
Labels: not-for-changelog

#19887 Use our common pretty table (#17333)
  ydb/library/workload/tpcc/runner.cpp
Labels: not-for-changelog

#19693 Improve behaviour in corner cases when used shared threads
  ydb/library/actors/core/executor_pool_basic.cpp
  ydb/library/actors/core/harmonizer/cpu_consumption.cpp
  ydb/library/actors/core/harmonizer/cpu_consumption.h
  ydb/library/actors/core/harmonizer/harmonizer.cpp
  ydb/library/actors/core/harmonizer/harmonizer.h
  ydb/library/actors/core/harmonizer/shared_info.cpp
  ydb/library/actors/core/harmonizer/shared_info.h
  ydb/library/actors/core/manual_test/shared_threads/main.cpp
  ydb/library/actors/core/manual_test/shared_threads/ya.make
  ydb/library/actors/core/mon_stats.h
Labels: area/actorsystem, not-for-changelog

#19497 Added row about `Implicit session` option into feature parity table
  ydb/docs/en/core/reference/ydb-sdk/feature-parity.md
  ydb/docs/ru/core/reference/ydb-sdk/feature-parity.md
Labels: documentation
