Repository ydb-platform/ydb, pull requests merged in 2025-07, with the labels that each got.

#20409 [docs] disable GTM
  ydb/docs/.yfm
Labels: documentation

#16415 wait time has been added
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/actor/actor.h
Labels: not-for-changelog

#18856 Automatic blobstorage balancing
  ydb/core/base/blobstorage_common.h
  ydb/core/blobstorage/ut_blobstorage/cluster_balancing.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/blobstorage/ut_blobstorage/ut_cluster_balancing/ya.make
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/cluster_balancing.cpp
  ydb/core/mind/bscontroller/cluster_balancing.h
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/mind/bscontroller/config.h
  ydb/core/mind/bscontroller/config_cmd.cpp
  ydb/core/mind/bscontroller/config_fit_groups.cpp
  ydb/core/mind/bscontroller/error.h
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/monitoring.cpp
  ydb/core/mind/bscontroller/ya.make
  ydb/core/protos/blobstorage_config.proto
  ydb/library/services/services.proto
Labels: experimental-feature

#20295 async CA: add streamlookup/inputtransform test and verify watermarks
  ydb/library/yql/dq/actors/compute/ut/dq_async_compute_actor_ut.cpp
  ydb/library/yql/dq/actors/compute/ut/mock_lookup_factory.cpp
  ydb/library/yql/dq/actors/compute/ut/mock_lookup_factory.h
  ydb/library/yql/dq/actors/compute/ut/proto/mock.proto
  ydb/library/yql/dq/actors/compute/ut/proto/ya.make
  ydb/library/yql/dq/actors/compute/ut/ya.make
Labels: not-for-changelog

#20245 Account usage from ColumnShards
  ydb/core/base/appdata_fwd.h
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/runtime/scheduler/new/kqp_schedulable_actor.cpp
  ydb/core/kqp/runtime/scheduler/new/kqp_schedulable_actor.h
  ydb/core/kqp/runtime/scheduler/new/tree/common.h
  ydb/core/kqp/runtime/scheduler/new/tree/dynamic.cpp
  ydb/core/kqp/runtime/scheduler/new/tree/dynamic.h
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/actor/actor.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_internal_scan.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
Labels: experimental-feature

#20277 YQ-4384 Add scope to pq metrics
  ydb/core/fq/libs/actors/pending_fetcher.cpp
  ydb/core/fq/libs/actors/run_actor.cpp
  ydb/core/fq/libs/compute/common/run_actor_params.cpp
  ydb/core/fq/libs/compute/common/run_actor_params.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
  ydb/library/yql/providers/pq/proto/dq_io.proto
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_provider.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_provider.h
Labels: not-for-changelog

#20360 Removed unnecessary code
  ydb/core/fq/libs/actors/clusters_from_connections.cpp
  ydb/core/fq/libs/actors/clusters_from_connections.h
  ydb/core/fq/libs/actors/run_actor.cpp
  ydb/core/fq/libs/test_connection/test_monitoring.cpp
Labels: not-for-changelog

#20434 oidc whoami proper asan fix
  ydb/mvp/oidc_proxy/extension_final.cpp
  ydb/mvp/oidc_proxy/extension_manager.cpp
  ydb/mvp/oidc_proxy/extension_whoami.cpp
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
Labels: bugfix

#20441 Run incremental restore pipeline with control op after restarts
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_cansel_build_index.cpp
  ydb/core/tx/schemeshard/ut_incremental_restore_reboots/ut_incremental_restore_reboots.cpp
  ydb/core/tx/schemeshard/ya.make
Labels: not-for-changelog

#20446 Fix config guid size in StateStorage info
  ydb/core/base/statestorage.h
  ydb/core/blobstorage/ut_blobstorage/statestorage.cpp
Labels: not-for-changelog

#20451 [RBO] Cleaned up left join handling
  ydb/core/kqp/opt/rbo/kqp_rbo_rules.cpp
  ydb/core/kqp/opt/rbo/kqp_rbo_transformer.cpp
Labels: not-for-changelog

#20473 Revert "Add YAML config validation on node init (#20151)"
  ydb/public/lib/ydb_cli/commands/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_node_config.cpp
Labels: not-for-changelog

#20472 [C++ SDK] Refactor topic tests and moved heavy tests
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/query/client.h
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
  ydb/public/sdk/cpp/tests/integration/topic/setup/fixture.cpp
  ydb/public/sdk/cpp/tests/integration/topic/setup/fixture.h
  ydb/public/sdk/cpp/tests/integration/topic/topic_to_table.cpp
  ydb/public/sdk/cpp/tests/integration/topic/utils/setup.cpp
Labels: not-for-changelog

#20416 [docs] explicitly set metrika
  ydb/docs/.yfm
Labels: documentation

#20391 AllowExtraSymbolsForColumnTableColumns flag has been supported
  ydb/core/protos/config.proto
  ydb/core/tx/schemeshard/olap/columns/update.cpp
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: not-for-changelog

#20447 Add args description to `tools infer csv --help`
  ydb/public/lib/ydb_cli/commands/ydb_tools_infer.cpp
Labels: not-for-changelog

#20274 Add compaction page
  ydb/core/tx/columnshard/columnshard_view.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/tiling/tiling.cpp
Labels: not-for-changelog

#20448 Remove legacy split to read and write versions, execute operations at a single mvcc version
  ydb/core/tx/datashard/build_data_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/build_distributed_erase_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/build_kqp_data_tx_out_rs_unit.cpp
  ydb/core/tx/datashard/change_collector_cdc_stream.cpp
  ydb/core/tx/datashard/change_collector_cdc_stream.h
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__engine_host.cpp
  ydb/core/tx/datashard/datashard__engine_host.h
  ydb/core/tx/datashard/datashard_active_transaction.h
  ydb/core/tx/datashard/datashard_change_receiving.cpp
  ydb/core/tx/datashard/datashard_common_upload.cpp
  ydb/core/tx/datashard/datashard_common_upload.h
  ydb/core/tx/datashard/datashard_direct_erase.cpp
  ydb/core/tx/datashard/datashard_direct_erase.h
  ydb/core/tx/datashard/datashard_direct_transaction.cpp
  ydb/core/tx/datashard/datashard_direct_transaction.h
  ydb/core/tx/datashard/datashard_direct_upload.cpp
  ydb/core/tx/datashard/datashard_direct_upload.h
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/core/tx/datashard/datashard_kqp.h
  ydb/core/tx/datashard/datashard_kqp_compute.cpp
  ydb/core/tx/datashard/datashard_kqp_compute.h
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_repl_apply.cpp
  ydb/core/tx/datashard/datashard_s3_upload_rows.cpp
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/direct_tx_unit.cpp
  ydb/core/tx/datashard/execute_commit_writes_tx_unit.cpp
  ydb/core/tx/datashard/execute_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_distributed_erase_tx_unit.cpp
  ydb/core/tx/datashard/execute_kqp_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/finish_propose_unit.cpp
  ydb/core/tx/datashard/finish_propose_write_unit.cpp
  ydb/core/tx/datashard/operation.h
  ydb/core/tx/datashard/read_table_scan_unit.cpp
  ydb/core/tx/datashard/setup_sys_locks.h
Labels: not-for-changelog

#20444 Fix ACL for temp tables
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/ut/scheme/kqp_acl_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#20461 [asan] core/kqp/ut/tx/kqp_locks_tricky_ut: fix out-of-scope use
  ydb/core/kqp/ut/tx/kqp_locks_tricky_ut.cpp
Labels: not-for-changelog

#20154 [docs] remove outdated limitation from cdc.md
  ydb/docs/en/core/concepts/cdc.md
  ydb/docs/ru/core/concepts/cdc.md
Labels: documentation

#20337 remove some outdated code
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
Labels: not-for-changelog

#20506 fix nemesis test report
  ydb/tests/olap/load/lib/conftest.py
Labels: not-for-changelog

#20502 Drop failed CTAS tables
  ydb/core/kqp/common/simple/temp_tables.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/session_actor/kqp_temp_tables_manager.cpp
Labels: not-for-changelog

#19926 [stable-25-1] Improve tiny ydb perfomance (#19909)
  ydb/core/driver_lib/run/auto_config_initializer.cpp
  ydb/core/driver_lib/run/config_helpers.cpp
  ydb/core/driver_lib/run/run.cpp
  ydb/core/protos/config.proto
  ydb/library/actors/core/config.h
  ydb/library/actors/core/cpu_manager.cpp
  ydb/library/actors/core/executor_pool_shared.cpp
  ydb/library/actors/core/executor_pool_shared.h
  ydb/library/actors/core/executor_thread_ctx.h
  ydb/library/actors/core/manual_test/shared_threads/main.cpp
Labels: area/actorsystem

#20513 Switch from flow to stream i/o in the DQ hash combiner
  ydb/library/yql/dq/comp_nodes/dq_hash_aggregate.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_combine.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_operator_serdes.cpp
  ydb/library/yql/dq/comp_nodes/dq_hash_operator_serdes.h
  ydb/library/yql/dq/comp_nodes/dq_program_builder.cpp
  ydb/library/yql/dq/comp_nodes/ut/dq_hash_combine_ut.cpp
Labels: not-for-changelog

#20514 Fix unexpected unique constraint violation errors from datashards
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/datashard_user_db.h
  ydb/core/tx/datashard/datashard_ut_common_kqp.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/datashard_write_operation.cpp
  ydb/core/tx/datashard/datashard_write_operation.h
  ydb/core/tx/datashard/execute_write_unit.cpp
Labels: not-for-changelog

#20529 Fix TIndexBuildInfo::AddParent access beyond map end (#20527)
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/ut_base/ut_info_types.cpp
Labels: not-for-changelog

#20495 cpu time has been fixed
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.cpp
Labels: bugfix

#20321 Bridge Mode in SB: more thorough disconnected group ignoring in subscriber
  ydb/core/tx/scheme_board/subscriber.cpp
  ydb/core/tx/scheme_board/subscriber_ut.cpp
Labels: not-for-changelog

#20547 The request should contain only known partitions
  ydb/core/kqp/topics/kqp_topics.cpp
  ydb/core/kqp/topics/kqp_topics.h
  ydb/services/persqueue_v1/ut/topic_service_ut.cpp
Labels: not-for-changelog

#20556 YQ-4349 Remove query_id from ping
  ydb/core/fq/libs/control_plane_storage/internal/task_ping.cpp
Labels: not-for-changelog

#20515 additional logging in scheme board replica in case of config change
  ydb/core/base/statestorage.cpp
  ydb/core/base/statestorage_impl.h
  ydb/core/tx/scheme_board/events_internal.h
  ydb/core/tx/scheme_board/replica.cpp
Labels: not-for-changelog

#20564 include has been fixed for import
  ydb/core/driver_lib/run/run.cpp
Labels: not-for-changelog

#20561 properly load piles in hive
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/tx__load_everything.cpp
Labels: not-for-changelog

#20539 Support quorum of specific bridge pile ids when changing cluster state in Bridge mode
  ydb/core/blobstorage/bridge/syncer/syncer.cpp
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_connectivity.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/blobstorage/nodewarden/distconf_mon.cpp
  ydb/core/blobstorage/nodewarden/distconf_quorum.h
  ydb/core/grpc_services/rpc_bridge.cpp
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/public/api/protos/draft/ydb_bridge.proto
  ydb/public/lib/ydb_cli/commands/ydb_bridge.cpp
  ydb/public/lib/ydb_cli/commands/ydb_bridge.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/draft/ydb_bridge.h
  ydb/public/sdk/cpp/src/client/draft/ydb_bridge.cpp
Labels: not-for-changelog

#20234 Ydb issue 19821
  ydb/core/kqp/ut/common/columnshard.cpp
  ydb/core/kqp/ut/common/columnshard.h
  ydb/core/kqp/ut/olap/decimal_ut.cpp
Labels: not-for-changelog

#20582 Avoid unnecessary activations before reclaiming free mailboxes
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/mailbox_lockfree.h
Labels: not-for-changelog

#20583 Replace Y_ABORT_UNLESS with FailWithError in channel spilling actor
  ydb/library/yql/dq/actors/spilling/channel_storage_actor.cpp
Labels: not-for-changelog

#20589 Bridge Mode in SB: do not send updates to disconnected replicas from main populators
  ydb/core/tx/scheme_board/helpers.cpp
  ydb/core/tx/scheme_board/helpers.h
  ydb/core/tx/scheme_board/populator.cpp
  ydb/core/tx/scheme_board/populator.h
  ydb/core/tx/scheme_board/populator_ut.cpp
  ydb/core/tx/scheme_board/subscriber_ut.cpp
Labels: not-for-changelog

#20584 node segments for balancing
  ydb/core/mind/hive/hive_events.h
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/monitoring.cpp
  ydb/core/mind/hive/node_info.h
  ydb/core/protos/config.proto
Labels: not-for-changelog

#20596 Bridge Mode in SB: partial sync response on config mismatch
  ydb/core/tx/scheme_board/subscriber.cpp
  ydb/core/tx/scheme_board/subscriber_ut.cpp
Labels: not-for-changelog

#20585 Make shard range index more granular and fix the "shards do not intersect" error (#20574)
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/ut_base/ut_info_types.cpp
Labels: not-for-changelog

#20142 [docs] update review.md with details about backports
  ydb/docs/en/core/contributor/documentation/review.md
  ydb/docs/ru/core/contributor/documentation/review.md
Labels: documentation

#20613 [C++ SDK] Fixed topic tests build on darwin
  ydb/public/sdk/cpp/src/client/topic/ut/local_partition_ut.cpp
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
Labels: not-for-changelog

#20476 clean useless scheme versions
  ydb/core/kqp/compute_actor/kqp_scan_compute_manager.h
  ydb/core/kqp/ut/olap/combinatory/compaction.cpp
  ydb/core/kqp/ut/olap/combinatory/compaction.h
  ydb/core/kqp/ut/olap/combinatory/select.cpp
  ydb/core/kqp/ut/olap/combinatory/variator.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/protos/counters_columnshard.proto
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/columnshard/background_controller.h
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/objects_cache.cpp
  ydb/core/tx/columnshard/engines/scheme/objects_cache.h
  ydb/core/tx/columnshard/engines/scheme/schema_diff.cpp
  ydb/core/tx/columnshard/engines/scheme/schema_diff.h
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.h
  ydb/core/tx/columnshard/engines/storage/actualizer/scheme/scheme.cpp
  ydb/core/tx/columnshard/engines/storage/granule/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule/storage.h
  ydb/core/tx/columnshard/engines/ut/ut_script.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/columnshard/tables_manager.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/wrappers/fake_storage.h
Labels: improvement

#19919 [KQP] Add configuration for the custom partition pruning for DataExecuter and PartitionedExecuter
  ydb/core/kqp/common/batch/batch_operation_settings.cpp
  ydb/core/kqp/common/batch/batch_operation_settings.h
  ydb/core/kqp/common/batch/params.h
  ydb/core/kqp/common/batch/ya.make
  ydb/core/kqp/common/kqp_batch_operations.cpp
  ydb/core/kqp/common/kqp_batch_operations.h
  ydb/core/kqp/common/ya.make
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_partition_helper.cpp
  ydb/core/kqp/executer_actor/kqp_partition_helper.h
  ydb/core/kqp/executer_actor/kqp_partitioned_executer.cpp
  ydb/core/kqp/executer_actor/kqp_partitioned_executer.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_delete_ut.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_update_ut.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/kqp/ut/sysview/kqp_sys_view_ut.cpp
  ydb/core/kqp/ut/tx/kqp_locks_tricky_ut.cpp
  ydb/core/protos/tx_datashard.proto
  ydb/tests/compatibility/test_batch_operations.py
Labels: not-for-changelog

#20620 Better empty table name validation
  ydb/core/tx/datashard/build_index/local_kmeans.cpp
  ydb/core/tx/datashard/build_index/prefix_kmeans.cpp
  ydb/core/tx/datashard/build_index/reshuffle_kmeans.cpp
  ydb/core/tx/datashard/build_index/secondary_index.cpp
  ydb/core/tx/datashard/build_index/ut/ut_secondary_index.cpp
Labels: not-for-changelog

#18773 Mantain the revision on the server side.
  ydb/apps/etcd_proxy/proxy.cpp
  ydb/apps/etcd_proxy/readme.txt
  ydb/apps/etcd_proxy/service/create.sql
  ydb/apps/etcd_proxy/service/etcd_base_init.cpp
  ydb/apps/etcd_proxy/service/etcd_base_init.h
  ydb/apps/etcd_proxy/service/etcd_events.h
  ydb/apps/etcd_proxy/service/etcd_gate.cpp
  ydb/apps/etcd_proxy/service/etcd_gate.h
  ydb/apps/etcd_proxy/service/etcd_grpc.cpp
  ydb/apps/etcd_proxy/service/etcd_grpc.h
  ydb/apps/etcd_proxy/service/etcd_impl.cpp
  ydb/apps/etcd_proxy/service/etcd_lease.cpp
  ydb/apps/etcd_proxy/service/etcd_lease.h
  ydb/apps/etcd_proxy/service/etcd_shared.cpp
  ydb/apps/etcd_proxy/service/etcd_shared.h
  ydb/apps/etcd_proxy/service/etcd_watch.cpp
  ydb/apps/etcd_proxy/service/leases.sql
  ydb/apps/etcd_proxy/service/revision.sql
  ydb/apps/etcd_proxy/service/ut/etcd_service_ut.cpp
  ydb/apps/etcd_proxy/service/ya.make
Labels: new-feature

#20604 always uses block engine reader for olap tables
  .github/config/muted_ya.txt
  ydb/core/kqp/opt/peephole/kqp_opt_peephole_wide_read.cpp
Labels: not-for-changelog

#20681 oidc: fix empty error reporting
  ydb/mvp/oidc_proxy/extension_manager.cpp
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
Labels: bugfix

#20676 increasing wait time
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
Labels: improvement

#20652 Fix snapshots
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/ut/tx/kqp_locks_tricky_ut.cpp
  ydb/core/kqp/ut/tx/kqp_sink_tx_ut.cpp
Labels: not-for-changelog

#20655 [C++ SDK] Added vector index example for docs
  ydb/public/sdk/cpp/examples/vector_index_builtin/main.cpp
  ydb/public/sdk/cpp/examples/vector_index_builtin/vector_index.cpp
  ydb/public/sdk/cpp/examples/vector_index_builtin/vector_index.h
  ydb/public/sdk/cpp/examples/vector_index_builtin/ya.make
  ydb/public/sdk/cpp/examples/ya.make
Labels: not-for-changelog

#20700 YQ-4317 Fix federated query ut recurse
  ydb/core/kqp/ut/federated_query/ya.make
Labels: not-for-changelog

#20649 column assembling in data fetching on cs
  ydb/core/tx/columnshard/blobs_action/abstract/read.h
  ydb/core/tx/columnshard/blobs_reader/task.h
  ydb/core/tx/columnshard/columnshard__statistics.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/data_reader/contexts.cpp
  ydb/core/tx/columnshard/data_reader/contexts.h
  ydb/core/tx/columnshard/data_reader/fetcher.cpp
  ydb/core/tx/columnshard/data_reader/fetcher.h
  ydb/core/tx/columnshard/data_reader/fetching_steps.h
  ydb/core/tx/columnshard/engines/portions/data_accessor.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/default_fetching.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/sub_columns_fetching.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/fetcher.h
  ydb/core/tx/columnshard/normalizer/portion/chunks.cpp
Labels: not-for-changelog

#20714 [KQP] Remove the CA nodes from ParticipantNodes in KqpDataExecuter
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/ut/query/kqp_stats_ut.cpp
Labels: not-for-changelog

#20729 add ut for stream index lookup join
  ydb/core/kqp/ut/join/kqp_index_lookup_join_ut.cpp
Labels: not-for-changelog

#20734 Vector index workload improvements for large tables
  ydb/library/workload/vector/registrar.cpp
  ydb/library/workload/vector/vector_recall_evaluator.cpp
  ydb/library/workload/vector/vector_recall_evaluator.h
  ydb/library/workload/vector/vector_sampler.cpp
  ydb/library/workload/vector/vector_sampler.h
  ydb/library/workload/vector/vector_sql.cpp
  ydb/library/workload/vector/vector_sql.h
  ydb/library/workload/vector/vector_workload_generator.cpp
  ydb/library/workload/vector/vector_workload_params.cpp
  ydb/library/workload/vector/vector_workload_params.h
Labels: not-for-changelog

#20607 Shared Cache: remove ECacheTier::None
  ydb/core/tablet_flat/shared_cache_counters.cpp
  ydb/core/tablet_flat/shared_cache_counters.h
  ydb/core/tablet_flat/shared_cache_tiered.h
  ydb/core/tablet_flat/shared_cache_tiered_ut.cpp
  ydb/core/tablet_flat/shared_cache_tiers.h
  ydb/core/tablet_flat/shared_page.h
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/tablet_flat/ut/shared_cache_ut_common.h
  ydb/core/tablet_flat/ut/ut_shared_sausagecache_actor.cpp
Labels: not-for-changelog

#20720 return CORS to bad 403 response
  ydb/mvp/oidc_proxy/extension_whoami.cpp
  ydb/mvp/oidc_proxy/oidc_proxy_ut.cpp
Labels: bugfix

#20744 Fix cluster permissions check under grpc
  ydb/core/grpc_services/grpc_request_check_actor.h
Labels: not-for-changelog

#20715 Set EnableDataShardInMemoryStateMigrationAcrossGenerations = true by default
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#20765 Fix create_mute_test_issue
  .github/scripts/tests/create_new_muted_ya.py
  .github/scripts/tests/update_mute_issues.py
Labels: not-for-changelog

#20525 YMQ: Do not send x-amz-crc32 HTTP header (AWS does not do it)
  ydb/core/http_proxy/http_req.cpp
Labels: improvement

#20625 Add epoch version & nodes count sensors in NodeBroker & DynamicNameserver
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/mind/dynamic_nameserver_impl.h
  ydb/core/mind/dynamic_nameserver_mon.cpp
  ydb/core/mind/node_broker.cpp
  ydb/core/mind/node_broker__extend_lease.cpp
  ydb/core/mind/node_broker__graceful_shutdown.cpp
  ydb/core/mind/node_broker__migrate_state.cpp
  ydb/core/mind/node_broker__register_node.cpp
  ydb/core/mind/node_broker__update_config.cpp
  ydb/core/mind/node_broker__update_config_subscription.cpp
  ydb/core/mind/node_broker__update_epoch.cpp
  ydb/core/mind/node_broker_impl.h
  ydb/core/protos/counters_node_broker.proto
Labels: not-for-changelog

#20762 “remove_message_limit”
  ydb/docs/en/core/concepts/_includes/limits-ydb.md
  ydb/docs/ru/core/concepts/_includes/limits-ydb.md
Labels: documentation

#20673 YQ fixed ast output for ctas
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
Labels: bugfix

#20796 Fix kikimr_runner.py compatibility with py2
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#19997 DataShard: rename DataCleanup to Vacuum
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/datashard.h
  ydb/core/tx/datashard/datashard__data_cleanup.cpp
  ydb/core/tx/datashard/datashard__vacuum.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_vacuum.cpp
  ydb/core/tx/datashard/ut_vacuum/ya.make
  ydb/core/tx/datashard/ya.make
  ydb/core/tx/schemeshard/schemeshard__tenant_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
Labels: not-for-changelog

#20800 Fixed memory leak since CreateSystemViewResolver returned raw pointer
  ydb/core/sys_view/common/schema.cpp
  ydb/core/sys_view/common/schema.h
Labels: bugfix

#20508 Add ICB to control VDisk compaction InFlight
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_hulldefs.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_hulldefs.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_ut.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompactworker.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_public.cpp
  ydb/core/blobstorage/vdisk/repl/blobstorage_hullreplwritesst_ut.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#20756 Tpcc import with arenas (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/value/value.h
  ydb/public/sdk/cpp/src/client/value/value.cpp
Labels: not-for-changelog

#20807 extend DSProxy diagnostics
  ydb/core/blobstorage/dsproxy/dsproxy_blackboard.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_blackboard.h
  ydb/core/blobstorage/dsproxy/dsproxy_get_impl.cpp
Labels: not-for-changelog

#20810 Add a new library ini_config that only works with ini format
  ydb/public/lib/ydb_cli/common/aws.cpp
  ydb/public/lib/ydb_cli/common/aws.h
  ydb/public/lib/ydb_cli/common/ini_config/config.cpp
  ydb/public/lib/ydb_cli/common/ini_config/config.h
  ydb/public/lib/ydb_cli/common/ini_config/config_ut.cpp
  ydb/public/lib/ydb_cli/common/ini_config/ini.cpp
  ydb/public/lib/ydb_cli/common/ini_config/ini.h
  ydb/public/lib/ydb_cli/common/ini_config/ut/ya.make
  ydb/public/lib/ydb_cli/common/ini_config/value.cpp
  ydb/public/lib/ydb_cli/common/ini_config/value.h
  ydb/public/lib/ydb_cli/common/ini_config/ya.make
  ydb/public/lib/ydb_cli/common/ya.make
Labels: not-for-changelog

#20809 [KQP] Add new rule to KQP pipeline
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
  ydb/core/kqp/ut/opt/kqp_agg_ut.cpp
  ydb/library/yql/dq/opt/dq_opt.cpp
  ydb/library/yql/dq/opt/dq_opt.h
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.h
Labels: not-for-changelog

#20738 Add stats for grouped limiter and caches
  ydb/core/base/memory_controller_iface.h
  ydb/core/base/ut/memory_stats_ut.cpp
  ydb/core/memory_controller/memory_controller.cpp
  ydb/core/protos/memory_stats.proto
  ydb/core/testlib/test_client.cpp
  ydb/core/tx/columnshard/blob_cache.cpp
  ydb/core/tx/columnshard/blob_cache.h
  ydb/core/tx/columnshard/data_accessor/cache_policy/policy.h
  ydb/core/tx/general_cache/service/manager.h
  ydb/core/tx/general_cache/service/service.h
  ydb/core/tx/general_cache/usage/events.h
  ydb/core/tx/general_cache/usage/service.h
  ydb/core/tx/limiter/grouped_memory/service/actor.cpp
  ydb/core/tx/limiter/grouped_memory/service/actor.h
  ydb/core/tx/limiter/grouped_memory/service/manager.cpp
  ydb/core/tx/limiter/grouped_memory/service/manager.h
  ydb/core/tx/limiter/grouped_memory/usage/events.h
  ydb/core/tx/limiter/grouped_memory/usage/service.h
  ydb/core/tx/limiter/grouped_memory/usage/stage_features.cpp
  ydb/core/tx/limiter/grouped_memory/usage/stage_features.h
Labels: improvement

#20712 Bridge Mode in SB: gracefully continue sync request execution in case of concurrent reconfiguration
  ydb/core/tx/scheme_board/subscriber.cpp
  ydb/core/tx/scheme_board/subscriber_ut.cpp
  ydb/core/tx/scheme_board/ut_helpers.cpp
  ydb/core/tx/scheme_board/ut_helpers.h
Labels: not-for-changelog

#20339 YQ-3899 Check peers size
  ydb/core/fq/libs/actors/nodes_manager.cpp
Labels: not-for-changelog

#20831 Tpcc import speedup (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/util.h
Labels: not-for-changelog

#20842 Analytics: Fix chunks determinition for test
  .github/scripts/analytics/data_mart_queries/test_history_fast_mart.sql
  .github/scripts/analytics/data_mart_queries/test_history_mart.sql
  .github/scripts/analytics/test_history_fast.py
  .github/scripts/analytics/tests_monitor.py
Labels: not-for-changelog

#20808 Prettify TPDisk.ToString output
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_data.h
Labels: not-for-changelog

#20847 Add ENV variables reading for S3 config in OLAP tests
  ydb/tests/olap/scenario/test_alter_tiering.py
Labels: not-for-changelog

#20848 Improve tiny ydb perfomance (#19909)
  ydb/core/driver_lib/run/auto_config_initializer.cpp
  ydb/core/driver_lib/run/config_helpers.cpp
  ydb/core/driver_lib/run/run.cpp
  ydb/core/protos/config.proto
  ydb/library/actors/core/config.h
  ydb/library/actors/core/cpu_manager.cpp
  ydb/library/actors/core/executor_pool_shared.cpp
  ydb/library/actors/core/executor_pool_shared.h
  ydb/library/actors/core/executor_thread_ctx.h
Labels: area/actorsystem

#20827 [C++ SDK] Separated proto accessor for public and private SDKs
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/transfer/ut/common/utils.h
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.h
  ydb/public/lib/ydb_cli/dump/util/util.cpp
  ydb/public/lib/ydb_cli/dump/util/ya.make
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/draft/accessor.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/draft/ydb_replication.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/draft/ydb_view.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/proto/accessor.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/proto/private.h
  ydb/public/sdk/cpp/src/client/draft/ydb_replication.cpp
  ydb/public/sdk/cpp/src/client/draft/ydb_view.cpp
  ydb/public/sdk/cpp/src/client/proto/ya.make
  ydb/public/sdk/cpp/src/client/topic/impl/direct_reader.cpp
  ydb/public/sdk/cpp/src/client/topic/impl/direct_reader.h
  ydb/public/sdk/cpp/src/client/topic/impl/read_session_impl.h
Labels: not-for-changelog

#20884 Add yaml_config_enabled: true on configuration v2
  ydb/library/yaml_config/yaml_config_parser.cpp
Labels: not-for-changelog

#20858 [KQP] Disable the ParallelPointReadConsolidation flag
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#20869 [NEW RBO] Removed Common Opt from query compilation
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/opt/rbo/kqp_rbo_transformer.cpp
Labels: not-for-changelog

#20834 Run MultiRestore on TTxProgress
  .github/config/muted_ya.txt
  ydb/core/tx/schemeshard/schemeshard__operation_create_restore_incremental_backup.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/schemeshard_incremental_restore_scan.cpp
  ydb/core/tx/schemeshard/ut_incremental_restore/ut_incremental_restore.cpp
  ydb/core/tx/schemeshard/ut_incremental_restore_reboots/ut_incremental_restore_reboots.cpp
Labels: not-for-changelog

#20914 YQ-4384 Clearing agg metrics in row dispatcher
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
Labels: not-for-changelog

#20916 main clickbench MergeReply(): requirement !Signature.HasReplicaSignature(replicaId) failed
  ydb/core/base/statestorage_proxy.cpp
  ydb/core/blobstorage/ut_blobstorage/statestorage.cpp
Labels: bugfix

#20891 Bridge Mode CMS: test for groups
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
Labels: not-for-changelog

#20885 [ICRDMA] Simple ibdrv test to ensure ibdrv present.
  ydb/library/actors/interconnect/rdma/ut/ibv_ut.cpp
  ydb/library/actors/interconnect/rdma/ut/ya.make
  ydb/library/actors/interconnect/rdma/ya.make
  ydb/library/actors/interconnect/ya.make
Labels: not-for-changelog

#20832 async ca: mon page: fix typos
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
Labels: not-for-changelog

#20917 schemas sysview
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/sys_view/common/schema.cpp
  ydb/core/sys_view/common/schema.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/constructor.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/schema.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/schema.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/source.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/ya.make
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/ya.make
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/filtered_scheme.h
  ydb/core/tx/columnshard/engines/scheme/versions/preset_schemas.h
  ydb/core/tx/columnshard/engines/scheme/versions/snapshot_scheme.h
  ydb/services/ydb/ydb_logstore_ut.cpp
Labels: improvement

#1113 YQ-2643 Disable coordinator if no ingress tasks
  ydb/core/fq/libs/checkpointing/checkpoint_coordinator.cpp
  ydb/core/fq/libs/checkpointing/checkpoint_coordinator.h
  ydb/core/fq/libs/checkpointing/ut/checkpoint_coordinator_ut.cpp
Labels: bugfix

#20929 fix incoming data chunk processing
  ydb/library/actors/http/http.cpp
  ydb/library/actors/http/http.h
  ydb/library/actors/http/http_proxy_outgoing.cpp
  ydb/library/actors/http/http_ut.cpp
Labels: bugfix

#20926 Tpcc improvements (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/task_queue.h
  ydb/library/workload/tpcc/terminal.h
Labels: not-for-changelog

#20918 Support volatile transactions without expectations
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/volatile_tx.cpp
  ydb/core/tx/datashard/volatile_tx.h
Labels: not-for-changelog

#20954 PRAGMA ForceImmediateEffectsExecution
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/kqp_physical.proto
Labels: not-for-changelog

#20913 [C++ SDK] Fixed vulnerabilities
  ydb/public/sdk/cpp/src/client/impl/ydb_internal/retry/retry_async.h
  ydb/public/sdk/cpp/src/client/table/table.cpp
Labels: not-for-changelog

#20940 GenerateExtendedInfo has options as an argument
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
Labels: not-for-changelog

#20912 [C++ SDK] Fixed flaky topic tests
  ydb/public/sdk/cpp/src/client/query/client.cpp
  ydb/public/sdk/cpp/src/client/topic/impl/read_session_impl.ipp
  ydb/public/sdk/cpp/src/client/topic/impl/write_session_impl.cpp
  ydb/public/sdk/cpp/tests/integration/topic/topic_to_table.cpp
Labels: not-for-changelog

#20948 Invalidate tablet resolver cache on tablet pipe disconnect
  ydb/core/tablet/tablet_pipe_client.cpp
  ydb/core/tablet/tablet_pipe_ut.cpp
  ydb/core/tablet/tablet_resolver.cpp
Labels: not-for-changelog

#20013 Improve Interactive CLI documentation
  ydb/docs/en/core/reference/ydb-cli/_assets/candidates.gif
  ydb/docs/en/core/reference/ydb-cli/_assets/general-example.gif
  ydb/docs/en/core/reference/ydb-cli/_assets/highlighting.jpg
  ydb/docs/en/core/reference/ydb-cli/_assets/hints.gif
  ydb/docs/en/core/reference/ydb-cli/_assets/history-search.gif
  ydb/docs/en/core/reference/ydb-cli/_assets/history.gif
  ydb/docs/en/core/reference/ydb-cli/interactive-cli.md
  ydb/docs/ru/core/reference/ydb-cli/_assets/candidates.gif
  ydb/docs/ru/core/reference/ydb-cli/_assets/general-example.gif
  ydb/docs/ru/core/reference/ydb-cli/_assets/highlighting.jpg
  ydb/docs/ru/core/reference/ydb-cli/_assets/hints.gif
  ydb/docs/ru/core/reference/ydb-cli/_assets/history-search.gif
  ydb/docs/ru/core/reference/ydb-cli/_assets/history.gif
  ydb/docs/ru/core/reference/ydb-cli/interactive-cli.md
Labels: documentation

#20928 [ICRDMA] Allow to run RDMA tests for interconnect.
  .github/actions/test_ya/action.yml
  ydb/library/actors/interconnect/rdma/ut/ibv_ut.cpp
  ydb/library/actors/interconnect/rdma/ya.make
Labels: not-for-changelog

#20888 Do not include actorsystem.h via wilson_span.h
  ydb/core/kqp/common/events/query.cpp
  ydb/core/kqp/common/events/query.h
  ydb/library/actors/wilson/wilson_span.cpp
  ydb/library/actors/wilson/wilson_span.h
Labels: not-for-changelog

#20934 Add stress & compatibility tests for Node Broker Delta Protocol
  ydb/tests/compatibility/test_node_broker_delta_protocol.py
  ydb/tests/compatibility/ya.make
  ydb/tests/stress/node_broker/tests/test_workload.py
Labels: not-for-changelog

#20985 Add --non-indexed parameter to vector workload to allow testing non-indexed search
  ydb/library/workload/vector/vector_workload_params.cpp
  ydb/library/workload/vector/vector_workload_params.h
Labels: not-for-changelog

#20987 Rebase prestable workflow
  .github/workflows/rebase_prestable.yml
Labels: not-for-changelog

#20974 YQ-4417 fixed url escape during schema inference
  ydb/core/external_sources/object_storage/inference/ut/ya.make
  ydb/core/external_sources/object_storage/s3_fetcher.cpp
  ydb/core/external_sources/object_storage/ya.make
  ydb/tests/fq/s3/test_s3_0.py
Labels: bugfix

#21005 [Kafka API] fix unititilized values
  ydb/core/kafka_proxy/actors/kafka_balancer_actor.h
Labels: not-for-changelog

#21007 Allow to enable default allocator for Arrow in MKQL
  ydb/core/driver_lib/run/run.cpp
Labels: new-feature

#21012 Fix TValueBuilderBase constructors
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/value/value.h
  ydb/public/sdk/cpp/src/client/value/value.cpp
Labels: not-for-changelog

#21037 Generic store detection for sys view
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/abstract/metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/chunks/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/chunks/metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/granules/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/granules/metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/optimizer/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/optimizer/metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/portions/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/portions/metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/metadata.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/metadata.h
Labels: not-for-changelog

#20595 Vector search SDK recipe
  ydb/docs/ru/core/recipes/ydb-sdk/index.md
  ydb/docs/ru/core/recipes/ydb-sdk/toc_i.yaml
  ydb/docs/ru/core/recipes/ydb-sdk/vector-search.md
  ydb/public/sdk/python/examples/vector_search/vector_search.py
Labels: documentation

#20966 Infer PDisk ExpectedSlotCount from drive size
  ydb/core/blobstorage/nodewarden/blobstorage_node_warden_ut.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_pdisk.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/mind/bscontroller/cmds_host_config.cpp
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/config_fit_pdisks.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/register_node.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/protos/blobstorage.proto
  ydb/core/protos/blobstorage_config.proto
  ydb/library/yaml_config/protos/config.proto
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_domains_config_dump_/multinode-missing-all.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_domains_config_dump_/multinode-unmatched-types.yaml.result.json
  ydb/library/yaml_config/yaml_config_parser.cpp
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_bs_controller_/flat_bs_controller.schema
Labels: new-feature

#20819 Document PRAGMA ydb.KMeansTreeSearchTopSize (#20374)
  ydb/docs/en/core/yql/reference/syntax/select/vector_index.md
  ydb/docs/ru/core/yql/reference/syntax/select/vector_index.md
Labels: documentation

#21041 ForceImmediateEffectsExecution monitoring
  ydb/core/kqp/counters/kqp_counters.cpp
  ydb/core/kqp/counters/kqp_counters.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#21035 [Kafka API] Fixes after e2e testing
  ydb/core/kafka_proxy/actors/kafka_api_versions_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_find_coordinator_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_find_coordinator_actor.h
  ydb/core/kafka_proxy/actors/kafka_offset_fetch_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_offset_fetch_actor.h
  ydb/core/kafka_proxy/actors/kafka_produce_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_read_session_actor.cpp
  ydb/core/kafka_proxy/kafka.h
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_messages_int.cpp
  ydb/core/kafka_proxy/ut/kafka_test_client.cpp
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/kafka_proxy/ut/ut_serialization.cpp
  ydb/core/raw_socket/sock_impl.h
  ydb/core/raw_socket/ut/buffered_writer_ut.cpp
  ydb/core/raw_socket/ut/ya.make
Labels: not-for-changelog

#21050 Fix uninit in StateStorageInfo
  ydb/core/base/statestorage.h
Labels: not-for-changelog

#20822 Translation after #12365 & #20387
  ydb/docs/en/core/concepts/async-replication.md
  ydb/docs/en/core/concepts/cdc.md
  ydb/docs/en/core/yql/reference/syntax/alter_table/changefeed.md
  ydb/docs/en/core/yql/reference/syntax/create-async-replication.md
Labels: documentation

#20081 YQ-4418 improved s3 read / write partitions validation
  ydb/core/external_sources/object_storage.cpp
  ydb/core/external_sources/object_storage_ut.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/library/yql/providers/s3/common/util.cpp
  ydb/library/yql/providers/s3/path_generator/yql_s3_path_generator.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_datasink_type_ann.cpp
  ydb/tests/fq/s3/test_insert.py
Labels: bugfix

#21039 Test move table stats
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: not-for-changelog

#21096 [KQP pipeline] Extend `PushCombineToStage`
  ydb/core/kqp/ut/opt/kqp_agg_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
Labels: not-for-changelog

#21098 Fix TestReconfigSchemeBoardWorkload
  ydb/core/tx/scheme_board/populator.cpp
Labels: not-for-changelog

#21054 ydb tools restore: fix restoration on windows
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
Labels: not-for-changelog

#21111 mute ydb/core/kqp/ut/scan KqpSplit.StreamLookupJoinDeliveryProblemAfterFirstResult
  .github/config/muted_ya.txt
Labels: not-for-changelog

#21090 Fix OOM in value builder
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/value/value.h
  ydb/public/sdk/cpp/src/client/value/value.cpp
Labels: not-for-changelog

#21079 remove unused function
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/provider/yql_kikimr_results.cpp
  ydb/core/kqp/provider/yql_kikimr_results.h
  ydb/core/ydb_convert/ydb_convert.cpp
  ydb/core/ydb_convert/ydb_convert.h
Labels: not-for-changelog

#21101 Fix BSC reporting for Bridge mode
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/cmds_storage_pool.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/config_fit_groups.cpp
  ydb/core/mind/bscontroller/group_metrics_exchange.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/mind/bscontroller/select_groups.cpp
  ydb/core/mind/bscontroller/sys_view.cpp
  ydb/core/mind/bscontroller/virtual_group.cpp
  ydb/core/mind/table_adapter.h
Labels: not-for-changelog

#21126 remove unused parse parameters methods
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/query_data/kqp_query_data.cpp
  ydb/core/kqp/query_data/kqp_query_data.h
Labels: not-for-changelog

#21018 Bridge Mode in CMS: testing storage groups
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/testlib/basics/helpers.h
  ydb/core/testlib/basics/services.cpp
Labels: not-for-changelog

#20629 local variable move to tablet
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/sys_view/schemas/constructor.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/versioned_index.h
  ydb/core/tx/columnshard/tables_manager.cpp
Labels: improvement

#21122 Set account type in ticket parser response
  ydb/core/security/ticket_parser_impl.h
  ydb/core/security/ticket_parser_ut.cpp
  ydb/library/aclib/aclib.h
  ydb/library/aclib/protos/aclib.proto
  ydb/library/testlib/service_mocks/nebius_access_service_mock.h
Labels: not-for-changelog

#21114 fix json requests
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/read.h
  ydb/core/tx/columnshard/blobs_reader/task.h
  ydb/core/tx/columnshard/data_reader/contexts.h
  ydb/core/tx/columnshard/data_reader/fetcher.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/fetcher.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/fetcher.h
Labels: bugfix

#21078 Disable by default RENAME for column table
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
  ydb/tests/fq/yt/kqp_yt_import/kqprun_import_config.conf
  ydb/tests/olap/s3_import/base.py
Labels: not-for-changelog

#21179 CI: support ydb qa down for test upload
  .github/scripts/analytics/upload_tests_results.py
Labels: not-for-changelog

#21169 Tpcc tui logs improvements (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/import_tui.cpp
  ydb/library/workload/tpcc/log.h
  ydb/library/workload/tpcc/log_backend.cpp
  ydb/library/workload/tpcc/log_backend.h
  ydb/library/workload/tpcc/logs_scroller.cpp
  ydb/library/workload/tpcc/logs_scroller.h
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/runner_tui.cpp
  ydb/library/workload/tpcc/ut/log_capture_ut.cpp
  ydb/library/workload/tpcc/ya.make
Labels: not-for-changelog

#21110 Add fingerprint for bridge
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_persistent_storage.cpp
  ydb/core/protos/bridge.proto
Labels: not-for-changelog

#21177 Add YDB CLI interactive mode greetings and connectivity check
  ydb/apps/ydb/CHANGELOG.md
  ydb/library/workload/tpcc/runner.cpp
  ydb/public/lib/ydb_cli/commands/interactive/interactive_cli.cpp
  ydb/public/lib/ydb_cli/commands/interactive/interactive_cli.h
  ydb/public/lib/ydb_cli/commands/ydb_command.cpp
  ydb/public/lib/ydb_cli/commands/ydb_command.h
  ydb/public/lib/ydb_cli/commands/ydb_root_common.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: area/cli, not-for-changelog

#21186 Fix accidentally added verify
  ydb/core/mind/table_adapter.h
Labels: not-for-changelog

#21187 fix timeout on serverless database healthcheck with enabled metadata …
  ydb/core/viewer/viewer_healthcheck.h
Labels: not-for-changelog

#21210 fix datamarts
  .github/scripts/analytics/data_mart_queries/perfomance_olap_mart.sql
  .github/scripts/analytics/data_mart_queries/perfomance_olap_suites_mart.sql
Labels: not-for-changelog

#21192 fix bad request in describe
  ydb/core/viewer/viewer_describe.h
Labels: not-for-changelog

#20789 Self-heal state storage
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_state_storage.cpp
  ydb/core/blobstorage/nodewarden/distconf_selfheal.cpp
  ydb/core/blobstorage/nodewarden/distconf_selfheal.h
  ydb/core/blobstorage/nodewarden/ya.make
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/library/actors/core/actor.h
  ydb/tests/functional/config/test_distconf_self_heal.py
  ydb/tests/functional/config/ya.make
  ydb/tests/library/harness/kikimr_config.py
Labels: not-for-changelog

#21176 Move bridge pile name to node location for convenience
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/grpc_services/rpc_node_registration.cpp
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/mind/dynamic_nameserver_impl.h
  ydb/core/mind/node_broker.cpp
  ydb/core/mind/node_broker__register_node.cpp
  ydb/core/mind/node_broker__scheme.h
  ydb/core/mind/node_broker_impl.h
  ydb/core/protos/config.proto
  ydb/core/protos/node_broker.proto
  ydb/library/actors/core/interconnect.cpp
  ydb/library/actors/core/interconnect.h
  ydb/library/actors/protos/interconnect.proto
  ydb/library/yaml_config/yaml_config_parser.cpp
  ydb/public/api/protos/ydb_discovery.proto
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/discovery/discovery.h
  ydb/public/sdk/cpp/src/client/discovery/discovery.cpp
  ydb/tests/library/harness/kikimr_config.py
  ydb/tools/ydbd_slice/yaml_configurator.py
Labels: not-for-changelog

#21204 [KQP] Compatibility changes for BATCH operations
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_partitioned_executer.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/protos/tx_datashard.proto
Labels: not-for-changelog

#21241 Unhardcode GroupMapper scoring penalties with ICB
  ydb/core/mind/bscontroller/group_mapper.cpp
Labels: not-for-changelog

#21255 fix signal and verification
  ydb/core/tx/general_cache/service/manager.h
Labels: bugfix
