Repository ydb-platform/ydb, pull requests merged in 2025-01, with the labels that each got.

#13149 Add option to restart PDisk without any checks
  ydb/core/blobstorage/base/blobstorage_events.h
  ydb/core/blobstorage/nodewarden/blobstorage_node_warden_ut.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_pdisk.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_http.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_actions.cpp
Labels: new-feature

#13148 Reduce throughput on overload special
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/tablet/write_queue.cpp
  ydb/core/tx/columnshard/tablet/write_queue.h
  ydb/core/tx/columnshard/tablet/ya.make
  ydb/core/tx/columnshard/ya.make
Labels: improvement

#13151 additional signals
  ydb/core/tx/columnshard/counters/scan.cpp
  ydb/core/tx/columnshard/counters/scan.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetch_steps.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
Labels: improvement

#13152 Switch kqp yt tests to yt suites
  ydb/tests/fq/yt/kqp_yt_file.make
  ydb/tests/fq/yt/kqp_yt_file.py
  ydb/tests/fq/yt/kqp_yt_file/part0/test.py
  ydb/tests/fq/yt/kqp_yt_file/part1/test.py
  ydb/tests/fq/yt/kqp_yt_file/part10/test.py
  ydb/tests/fq/yt/kqp_yt_file/part11/test.py
  ydb/tests/fq/yt/kqp_yt_file/part12/test.py
  ydb/tests/fq/yt/kqp_yt_file/part13/test.py
  ydb/tests/fq/yt/kqp_yt_file/part14/test.py
  ydb/tests/fq/yt/kqp_yt_file/part15/test.py
  ydb/tests/fq/yt/kqp_yt_file/part16/test.py
  ydb/tests/fq/yt/kqp_yt_file/part17/test.py
  ydb/tests/fq/yt/kqp_yt_file/part18/test.py
  ydb/tests/fq/yt/kqp_yt_file/part19/test.py
  ydb/tests/fq/yt/kqp_yt_file/part2/test.py
  ydb/tests/fq/yt/kqp_yt_file/part3/test.py
  ydb/tests/fq/yt/kqp_yt_file/part4/test.py
  ydb/tests/fq/yt/kqp_yt_file/part5/test.py
  ydb/tests/fq/yt/kqp_yt_file/part6/test.py
  ydb/tests/fq/yt/kqp_yt_file/part7/test.py
  ydb/tests/fq/yt/kqp_yt_file/part8/test.py
  ydb/tests/fq/yt/kqp_yt_file/part9/test.py
Labels: not-for-changelog

#12643 fix incorrect default storage id for count min sketch index
  ydb/core/tx/columnshard/blobs_action/counters/storage.h
  ydb/core/tx/columnshard/columnshard__statistics.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/count_min_sketch/constructor.cpp
Labels: bugfix

#13163 [ydbd_slice] add block-4-2-2 nodes and block-4-2-4 nodes
  ydb/tools/ydbd_slice/__init__.py
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-2-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-4-nodes.yaml
  ydb/tools/ydbd_slice/ya.make
Labels: new-feature

#13160 fix build with rigourous checks
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/tx/columnshard/data_accessor/local_db/collector.cpp
Labels: not-for-changelog

#13165 move tx_extension.h to a common place
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.h
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/data_sharing/common/transactions/ya.make
  ydb/core/tx/columnshard/data_sharing/common/ya.make
  ydb/core/tx/columnshard/data_sharing/destination/session/ya.make
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_data_from_source.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_finish_ack_from_initiator.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_finish_from_source.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_start_from_initiator.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/ya.make
  ydb/core/tx/columnshard/data_sharing/modification/tasks/ya.make
  ydb/core/tx/columnshard/data_sharing/modification/transactions/tx_change_blobs_owning.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_data_ack_to_source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_finish_ack_to_source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_source_cursor.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_to_source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_write_source_cursor.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/ya.make
  ydb/core/tx/columnshard/inflight_request_tracker.cpp
  ydb/core/tx/columnshard/tablet/ext_tx_base.cpp
  ydb/core/tx/columnshard/tablet/ext_tx_base.h
  ydb/core/tx/columnshard/tablet/ya.make
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
  ydb/core/tx/columnshard/transactions/operators/ev_write/secondary.h
Labels: not-for-changelog

#13157 unify portion change operations
  ydb/core/formats/arrow/special_keys.h
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/olap/sparsed_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/statistics/ut_common/ut_common.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/common/limits.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/abstract/changes.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/changes.h
  ydb/core/tx/columnshard/engines/changes/abstract/move_portions.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/move_portions.h
  ydb/core/tx/columnshard/engines/changes/abstract/remove_portions.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/remove_portions.h
  ydb/core/tx/columnshard/engines/changes/abstract/ya.make
  ydb/core/tx/columnshard/engines/changes/actualization/construction/context.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.h
  ydb/core/tx/columnshard/engines/changes/compaction.h
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/changes/ttl.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.h
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: improvement

#13169 Remove unnecessary template from TExtendedTransactionBase
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_data_from_source.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_finish_ack_from_initiator.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_finish_from_source.h
  ydb/core/tx/columnshard/data_sharing/destination/transactions/tx_start_from_initiator.h
  ydb/core/tx/columnshard/data_sharing/modification/transactions/tx_change_blobs_owning.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_data_ack_to_source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_finish_ack_to_source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_source_cursor.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_start_to_source.h
  ydb/core/tx/columnshard/data_sharing/source/transactions/tx_write_source_cursor.h
  ydb/core/tx/columnshard/inflight_request_tracker.cpp
  ydb/core/tx/columnshard/tablet/ext_tx_base.cpp
  ydb/core/tx/columnshard/tablet/ext_tx_base.h
  ydb/core/tx/columnshard/tablet/ya.make
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
  ydb/core/tx/columnshard/transactions/operators/ev_write/secondary.h
Labels: not-for-changelog

#13171 [ydbd_slice] fix Namespace exception(args.confirm) on update
  ydb/tools/ydbd_slice/__init__.py
Labels: bugfix

#13167 pacify static code analyzer
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/abstract.h
Labels: not-for-changelog

#13172 ut for deleting absent rows
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.cpp
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/tablet/ext_tx_base.cpp
Labels: bugfix

#13153 Swith dq_file/hybrid_file to yt suites
  ydb/library/yql/tests/sql/dq_file.make
  ydb/library/yql/tests/sql/dq_file.py
  ydb/library/yql/tests/sql/dq_file/part0/test.py
  ydb/library/yql/tests/sql/dq_file/part1/test.py
  ydb/library/yql/tests/sql/dq_file/part10/test.py
  ydb/library/yql/tests/sql/dq_file/part11/test.py
  ydb/library/yql/tests/sql/dq_file/part12/test.py
  ydb/library/yql/tests/sql/dq_file/part13/test.py
  ydb/library/yql/tests/sql/dq_file/part14/test.py
  ydb/library/yql/tests/sql/dq_file/part15/test.py
  ydb/library/yql/tests/sql/dq_file/part16/test.py
  ydb/library/yql/tests/sql/dq_file/part17/test.py
  ydb/library/yql/tests/sql/dq_file/part18/test.py
  ydb/library/yql/tests/sql/dq_file/part19/test.py
  ydb/library/yql/tests/sql/dq_file/part2/test.py
  ydb/library/yql/tests/sql/dq_file/part3/test.py
  ydb/library/yql/tests/sql/dq_file/part4/test.py
  ydb/library/yql/tests/sql/dq_file/part5/test.py
  ydb/library/yql/tests/sql/dq_file/part6/test.py
  ydb/library/yql/tests/sql/dq_file/part7/test.py
  ydb/library/yql/tests/sql/dq_file/part8/test.py
  ydb/library/yql/tests/sql/dq_file/part9/test.py
  ydb/library/yql/tests/sql/hybrid_file.make
  ydb/library/yql/tests/sql/hybrid_file.py
  ydb/library/yql/tests/sql/hybrid_file/part0/test.py
  ydb/library/yql/tests/sql/hybrid_file/part1/test.py
  ydb/library/yql/tests/sql/hybrid_file/part10/test.py
  ydb/library/yql/tests/sql/hybrid_file/part2/test.py
  ydb/library/yql/tests/sql/hybrid_file/part3/test.py
  ydb/library/yql/tests/sql/hybrid_file/part4/test.py
  ydb/library/yql/tests/sql/hybrid_file/part5/test.py
  ydb/library/yql/tests/sql/hybrid_file/part6/test.py
  ydb/library/yql/tests/sql/hybrid_file/part7/test.py
  ydb/library/yql/tests/sql/hybrid_file/part8/test.py
  ydb/library/yql/tests/sql/hybrid_file/part9/test.py
Labels: not-for-changelog

#13168 Send heartbeat message after writing the data
  ydb/core/tx/replication/service/base_table_writer.cpp
  ydb/core/tx/replication/service/table_writer_ut.cpp
Labels: not-for-changelog

#13181 Recover lost locks as broken
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/operations/manager.cpp
  ydb/core/tx/columnshard/operations/manager.h
  ydb/core/tx/columnshard/transactions/locks/interaction.h
Labels: bugfix

#13097 oidc cookie cleanup handler
  ydb/mvp/oidc_proxy/oidc_cleanup_page.cpp
  ydb/mvp/oidc_proxy/oidc_cleanup_page.h
  ydb/mvp/oidc_proxy/oidc_client.cpp
  ydb/mvp/oidc_proxy/oidc_impersonate_stop_page_nebius.cpp
  ydb/mvp/oidc_proxy/oidc_impersonate_stop_page_nebius.h
  ydb/mvp/oidc_proxy/ya.make
Labels: new-feature

#13182 batch portions on write
  ydb/core/formats/arrow/reader/position.h
  ydb/core/kqp/ut/olap/helpers/typed_local.cpp
  ydb/core/kqp/ut/olap/helpers/typed_local.h
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.h
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/columnshard_private_events.h
  ydb/core/tx/columnshard/engines/scheme/abstract/index_info.h
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
  ydb/core/tx/columnshard/engines/writer/buffer/actor.h
  ydb/core/tx/columnshard/engines/writer/buffer/actor2.cpp
  ydb/core/tx/columnshard/engines/writer/buffer/actor2.h
  ydb/core/tx/columnshard/engines/writer/buffer/events.h
  ydb/core/tx/columnshard/engines/writer/buffer/ya.make
  ydb/core/tx/columnshard/operations/batch_builder/builder.cpp
  ydb/core/tx/columnshard/operations/batch_builder/builder.h
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.h
  ydb/core/tx/columnshard/operations/common/context.h
  ydb/core/tx/columnshard/operations/events.h
  ydb/core/tx/columnshard/operations/slice_builder/builder.cpp
  ydb/core/tx/columnshard/operations/slice_builder/builder.h
  ydb/core/tx/columnshard/operations/slice_builder/pack_builder.cpp
  ydb/core/tx/columnshard/operations/slice_builder/pack_builder.h
  ydb/core/tx/columnshard/operations/slice_builder/ya.make
  ydb/core/tx/columnshard/operations/write.cpp
  ydb/core/tx/columnshard/tablet/write_queue.cpp
Labels: new-feature

#13162 Fix TSlay and THarakiri in ReadOnly mode
  ydb/apps/dstool/lib/dstool_cmd_cluster_workload_run.py
  ydb/core/blobstorage/nodewarden/node_warden_pdisk.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/mock/pdisk_mock.cpp
  ydb/core/blobstorage/ut_blobstorage/read_only_pdisk.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/protos/blobstorage_config.proto
Labels: bugfix

#13189 Do not clear shard lists
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
Labels: bugfix

#13187 simultaneous writing session for tests
  ydb/core/kqp/ut/olap/helpers/typed_local.cpp
  ydb/core/kqp/ut/olap/helpers/typed_local.h
  ydb/core/kqp/ut/olap/write_ut.cpp
Labels: improvement

#13188 correct commit processing for immediate writing
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.h
Labels: improvement

#13195 positive integer class
  ydb/core/tx/columnshard/data_accessor/manager.cpp
  ydb/core/tx/columnshard/data_accessor/manager.h
  ydb/core/tx/columnshard/engines/changes/abstract/compaction_info.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/compaction_info.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/abstract.h
  ydb/core/tx/limiter/grouped_memory/usage/abstract.h
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/manager.h
  ydb/library/accessor/positive_integer.cpp
  ydb/library/accessor/positive_integer.h
  ydb/library/accessor/ya.make
Labels: improvement

#13138 Fix -Wunused-parameter
  ydb/core/cms/console/console_handshake.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/filters/filters_set.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/format_handler_ut.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/topic_filter_ut.cpp
  ydb/core/grpc_services/rpc_ping.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_impl.h
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_indexes.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_sort.cpp
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/mind/bscontroller/console_interaction.cpp
  ydb/core/mon/mon.cpp
  ydb/core/persqueue/partition.cpp
  ydb/core/public_http/fq_handlers.h
  ydb/core/statistics/service/ut/ut_http_request.cpp
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/move_portions.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/remove_portions.cpp
  ydb/core/tx/columnshard/engines/changes/general_compaction.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/constructor/read_metadata.cpp
  ydb/core/tx/columnshard/engines/storage/granule/portions_index.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
  ydb/core/tx/columnshard/normalizer/portion/leaked_blobs.cpp
  ydb/core/tx/columnshard/tablet/write_queue.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/transactions/operators/ev_write/secondary.h
  ydb/core/tx/datashard/datashard_kqp.cpp
  ydb/core/tx/schemeshard/schemeshard__login.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_restore_incremental_backup.cpp
  ydb/core/viewer/json_handlers.h
  ydb/library/yql/dq/runtime/dq_tasks_counters.cpp
  ydb/services/metadata/secret/snapshot.cpp
Labels: not-for-changelog, external

#13193 Insert into nullable PK
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/engines/scheme/versions/abstract_scheme.cpp
Labels: not-for-changelog

#13183 Enable insert delete olap workload
  ydb/tests/workloads/olap_workload/__main__.py
Labels: bugfix

#13194 Embed short blobs in TCell, fix empty string
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: bugfix

#13211 add conflict ut
  ydb/core/kqp/ut/opt/kqp_returning_ut.cpp
Labels: not-for-changelog

#13208 [ydbd_slice] add erasure none for slice creation
  ydb/tools/ydbd_slice/__init__.py
  ydb/tools/ydbd_slice/baremetal/templates/none-1-node.yaml
  ydb/tools/ydbd_slice/ya.make
Labels: new-feature

#13120 Improve roaring UDF
  ydb/library/yql/udfs/common/roaring/roaring.cpp
  ydb/library/yql/udfs/common/roaring/test/canondata/result.json
  ydb/library/yql/udfs/common/roaring/test/canondata/test.test_intersect_/results.txt
  ydb/library/yql/udfs/common/roaring/test/canondata/test.test_run_optimize_/results.txt
  ydb/library/yql/udfs/common/roaring/test/canondata/test.test_serialize_deserialize_/results.txt
  ydb/library/yql/udfs/common/roaring/test/cases/intersect.sql
  ydb/library/yql/udfs/common/roaring/test/cases/run_optimize.sql
  ydb/library/yql/udfs/common/roaring/test/cases/serialize_deserialize.sql
Labels: improvement

#13109 Support Console interoperation through distconf
  ydb/core/blobstorage/base/blobstorage_console_events.h
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_console.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/ya.make
  ydb/core/cms/console/console_handshake.cpp
  ydb/core/config/init/init.cpp
  ydb/core/grpc_services/rpc_bsconfig.cpp
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/console_interaction.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/protos/blobstorage.proto
  ydb/core/protos/blobstorage_distributed_config.proto
Labels: new-feature

#13213 improve writing test for control portions count and compaction disable
  ydb/core/kqp/ut/olap/write_ut.cpp
Labels: improvement

#13216 roaring_bitmap_add_bulk
  ydb/library/yql/udfs/common/roaring/roaring.cpp
  ydb/library/yql/udfs/common/roaring/test/canondata/test.test_serialize_deserialize_/results.txt
  ydb/library/yql/udfs/common/roaring/test/cases/serialize_deserialize.sql
Labels: not-for-changelog

#13207 Remove excessive check from DS proxy mock
  ydb/core/blobstorage/dsproxy/mock/model.h
Labels: not-for-changelog

#13225 Deleted unnecessary anchors
  ydb/docs/en/core/integrations/ingestion/index.md
  ydb/docs/ru/core/integrations/ingestion/index.md
Labels: documentation

#12985 Fixed bug in S3 Physical Optimizer
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_phy_opt.cpp
Labels: bugfix

#13200 new wf for fast history
  .github/scripts/analytics/test_history_fast.py
  .github/workflows/collect_analytics_fast.yml
Labels: not-for-changelog

#13232 Apply changes in the correct order
  ydb/core/tx/datashard/ut_common/datashard_ut_common.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
  ydb/core/tx/replication/service/base_table_writer.cpp
  ydb/core/tx/replication/service/table_writer_ut.cpp
  ydb/core/tx/replication/service/ut_table_writer/ya.make
  ydb/core/tx/replication/ut_helpers/write_topic.h
Labels: not-for-changelog

#13204 Adapt suite tests for cs
  ydb/tests/functional/suite_tests/postgres/create_table.test
  ydb/tests/functional/suite_tests/postgres/jointest/join1.test
  ydb/tests/functional/suite_tests/postgres/jointest/join2.test
  ydb/tests/functional/suite_tests/postgres/jointest/join4.test
  ydb/tests/functional/suite_tests/postgres/select_distinct.test
  ydb/tests/functional/suite_tests/postgres/window.test
  ydb/tests/functional/suite_tests/sqllogictest/select2-1.test
  ydb/tests/functional/suite_tests/sqllogictest/select2-2.test
  ydb/tests/functional/suite_tests/sqllogictest/select2-3.test
  ydb/tests/functional/suite_tests/sqllogictest/select2-4.test
  ydb/tests/functional/suite_tests/test_base.py
Labels: not-for-changelog

#13241 [ydbd_slice] add confirmation before ydbd build
  ydb/tools/ydbd_slice/__init__.py
  ydb/tools/ydbd_slice/handlers.py
Labels: not-for-changelog

#13244 fix coverity complains
  ydb/core/kqp/host/kqp_host.cpp
Labels: not-for-changelog

#13236 Return consistency settings in the description
  ydb/core/grpc_services/rpc_replication.cpp
  ydb/core/protos/replication.proto
  ydb/core/tx/replication/controller/tx_describe_replication.cpp
  ydb/public/api/protos/draft/ydb_replication.proto
Labels: not-for-changelog

#13250 [ydbd_slice] add TMemoryControllerConfig to options
  ydb/tools/cfg/base.py
  ydb/tools/cfg/static.py
Labels: improvement

#13252 Make selector_config and allowed_labels optional
  ydb/core/cms/console/console_ut_configs.cpp
  ydb/library/yaml_config/public/yaml_config.cpp
Labels: not-for-changelog

#13021 Fix viewer nodes
  ydb/core/viewer/viewer_nodes.h
  ydb/core/viewer/viewer_ut.cpp
Labels: bugfix

#13235 Don't migrate uninitialized in-memory vars between datashards
  ydb/core/tx/datashard/create_table_unit.cpp
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/memory_state_migration.cpp
Labels: not-for-changelog

#13245 validate invalid curly brace
  ydb/library/yql/udfs/common/clickhouse/client/src/Formats/JSONEachRowUtils.cpp
Labels: not-for-changelog

#13255 Replication consistency levels support in C++ SDK
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/sdk/cpp/client/draft/ydb_replication.cpp
  ydb/public/sdk/cpp/client/draft/ydb_replication.h
Labels: not-for-changelog

#13256 Add forgotten clear()
  ydb/core/tx/replication/controller/controller.cpp
Labels: not-for-changelog

#12856 fix parsing of s3 settings on CS
  ydb/core/tx/tiering/tier/object.cpp
  ydb/core/tx/tiering/ut/ut_object.cpp
  ydb/core/tx/tiering/ut/ya.make
Labels: bugfix

#13214 Fix ColumnShardArbiter shard sets
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
Labels: bugfix

#13262 Update muted_ya.txt
  .github/config/muted_ya.txt
Labels: not-for-changelog

#13243 clickhouse udf: fix errno access without error
  ydb/library/yql/udfs/common/clickhouse/client/src/IO/WriteBufferFromFileDescriptor.cpp
  ydb/library/yql/udfs/common/clickhouse/client/src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp
Labels: bugfix

#13228 Add LookupSrc InFlight counter
  ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
Labels: not-for-changelog

#13261 Add sensors
  ydb/core/protos/counters_replication.proto
  ydb/core/tx/replication/controller/controller.cpp
  ydb/core/tx/replication/controller/tx_assign_tx_id.cpp
  ydb/core/tx/replication/controller/tx_heartbeat.cpp
  ydb/core/tx/replication/controller/ya.make
Labels: not-for-changelog

#13270 ACL test for olap
  ydb/core/kqp/ut/scheme/kqp_acl_ut.cpp
Labels: not-for-changelog

#13246 batch writing fixes
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/engines/writer/buffer/actor2.cpp
  ydb/core/tx/columnshard/operations/manager.cpp
  ydb/core/tx/columnshard/operations/manager.h
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
Labels: improvement

#13271 The test TPQTest::TestReadAndDeleteConsumer
  ydb/core/persqueue/ut/pq_ut.cpp
Labels: bugfix

#13227 Fix ForceBlockTabletData behaviour in BlobDepot and DS proxy mock
  ydb/core/base/blobstorage.h
  ydb/core/blob_depot/agent/agent_impl.h
  ydb/core/blob_depot/agent/query.cpp
  ydb/core/blob_depot/agent/storage_collect_garbage.cpp
  ydb/core/blob_depot/agent/storage_discover.cpp
  ydb/core/blob_depot/agent/storage_get.cpp
  ydb/core/blob_depot/agent/storage_get_block.cpp
  ydb/core/blob_depot/agent/storage_put.cpp
  ydb/core/blobstorage/dsproxy/mock/model.h
  ydb/core/blobstorage/vdisk/common/vdisk_events.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_block_and_get.cpp
Labels: not-for-changelog

#13275 Unlock last YT test in dq_file/hybrid_file
  ydb/library/yql/tests/sql/dq_file.py
  ydb/library/yql/tests/sql/hybrid_file.py
Labels: not-for-changelog

#13274 reuse built-in sensors from http_proxy via adapter over dynamic counters
  ydb/core/mon/counters_adapter_impl.h
  ydb/core/mon/mon.cpp
  ydb/core/mon/mon.h
Labels: backward-incompatible

#13249 fix coverity complains
  ydb/core/kqp/host/kqp_host.cpp
Labels: not-for-changelog

#12909 Validate checksums on import from s3
  ydb/apps/ydb/CHANGELOG.md
  ydb/core/backup/common/checksum.cpp
  ydb/core/backup/common/checksum.h
  ydb/core/backup/common/metadata.cpp
  ydb/core/backup/common/metadata.h
  ydb/core/backup/common/ya.make
  ydb/core/backup/ya.make
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/datashard/backup_restore_common.cpp
  ydb/core/tx/datashard/backup_restore_common.h
  ydb/core/tx/datashard/backup_restore_traits.cpp
  ydb/core/tx/datashard/backup_restore_traits.h
  ydb/core/tx/datashard/export_checksum.h
  ydb/core/tx/datashard/export_s3_buffer_raw.cpp
  ydb/core/tx/datashard/export_s3_buffer_raw.h
  ydb/core/tx/datashard/export_s3_uploader.cpp
  ydb/core/tx/datashard/export_scan.h
  ydb/core/tx/datashard/import_s3.cpp
  ydb/core/tx/datashard/ya.make
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_import.cpp
  ydb/core/tx/schemeshard/schemeshard_import_flow_proposals.cpp
  ydb/core/tx/schemeshard/schemeshard_import_scheme_getter.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/public/api/protos/ydb_import.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.h
  ydb/public/lib/ydb_cli/common/print_operation.cpp
  ydb/public/sdk/cpp/client/ydb_import/import.h
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: new-feature

#13280 Correct BSC teardown on Console race
  ydb/core/mind/bscontroller/console_interaction.cpp
Labels: not-for-changelog

#13282 Fix group resolver bug
  ydb/core/blobstorage/nodewarden/node_warden_group_resolver.cpp
Labels: not-for-changelog

#13287 Fix version of python in workflow
  .github/workflows/update_dstool_package.yaml
Labels: not-for-changelog

#13190 strict writing data validation
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/transactions/operators/ev_write/primary.h
Labels: improvement

#13290 fix portions cleanup
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.cpp
  ydb/core/tx/columnshard/engines/changes/cleanup_portions.h
Labels: bugfix

#13281 scanner simple speed up
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.h
  ydb/library/accessor/positive_integer.cpp
  ydb/library/accessor/positive_integer.h
Labels: improvement

#13292 fix scanner
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
Labels: bugfix

#12889 Update docs for Digest
  ydb/docs/en/core/yql/reference/yql-core/udf/list/digest.md
  ydb/docs/ru/core/yql/reference/yql-core/udf/list/digest.md
Labels: documentation, area/yql

#13304 fix decoding version output in sql tests
  ydb/tests/sql/lib/test_base.py
Labels: not-for-changelog

#13177 KqpRun improved multi query mode and storage settings
  ydb/core/driver_lib/run/config_helpers.cpp
  ydb/core/driver_lib/run/config_helpers.h
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/testlib/basics/helpers.h
  ydb/core/testlib/basics/storage.h
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/kqprun/.gitignore
  ydb/tests/tools/kqprun/flame_graph.sh
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/actors.cpp
  ydb/tests/tools/kqprun/src/actors.h
  ydb/tests/tools/kqprun/src/common.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/proto/storage_meta.proto
  ydb/tests/tools/kqprun/src/proto/ya.make
  ydb/tests/tools/kqprun/src/ya.make
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/ya.make
Labels: improvement

#13310 Add shred stub into BSC
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/base/blobstorage_shred_events.h
  ydb/core/blobstorage/ut_blobstorage/shred.cpp
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/defs.h
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/mind/bscontroller/shred.cpp
  ydb/core/mind/bscontroller/ya.make
  ydb/core/protos/blobstorage.proto
  ydb/core/protos/counters_bs_controller.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_bs_controller_/flat_bs_controller.schema
Labels: not-for-changelog

#13296 IGNIETFERRO-2114: correction of a debug check in the sorting predicate, a false positive of which leads to an abort
  ydb/core/tx/scheme_board/cache.cpp
Labels: bugfix, external

#13303 IGNIETFERRO-2114: fix the sorting predicate in the partition_chooser, which violates the strict-weak-ordering requirement
  ydb/core/persqueue/writer/partition_chooser_impl.h
Labels: bugfix, external

#13301 [docs][ydbops] add documentation for delay-between-restarts and nodes-inflight
  ydb/docs/en/core/reference/ydbops/reference.md
Labels: documentation

#13224 Added test that checks if simple aggregations are handled by block engine
  ydb/core/kqp/ut/olap/aggregations_ut.cpp
Labels: not-for-changelog

#13336 Unmute stable tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#13316 Make use of poller actor straight in http subsystem
  ydb/core/blobstorage/ut_vdisk/lib/astest.h
  ydb/library/actors/http/http_proxy.cpp
  ydb/library/actors/http/http_proxy.h
  ydb/library/actors/http/http_proxy_acceptor.cpp
  ydb/library/actors/http/http_proxy_outgoing.cpp
  ydb/library/actors/testlib/test_runtime.cpp
Labels: not-for-changelog

#13300 Add missed include <cstdlib>
  ydb/library/yql/udfs/common/clickhouse/client/base/common/demangle.h
  ydb/library/yql/utils/simd/exec/tuples_to_bucket/main.cpp
Labels: not-for-changelog

#13351 Support distconf shutdown
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
Labels: not-for-changelog

#13248 SystemView Auth Owners
  ydb/core/sys_view/auth/auth_scan_base.h
  ydb/core/sys_view/auth/group_members.cpp
  ydb/core/sys_view/auth/groups.cpp
  ydb/core/sys_view/auth/owners.cpp
  ydb/core/sys_view/auth/owners.h
  ydb/core/sys_view/auth/users.cpp
  ydb/core/sys_view/auth/ya.make
  ydb/core/sys_view/common/schema.cpp
  ydb/core/sys_view/common/schema.h
  ydb/core/sys_view/scan.cpp
  ydb/core/sys_view/ut_kqp.cpp
  ydb/core/sys_view/ut_large.cpp
  ydb/core/sys_view/ut_large/ya.make
  ydb/core/sys_view/ya.make
  ydb/core/tx/scheme_cache/scheme_cache.cpp
Labels: not-for-changelog

#13339 Fix UndoShardLock sometimes crashing when restoring in-memory locks
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/locks/locks.cpp
Labels: not-for-changelog

#13324 YQ-4017 Use real threds / try to fix asan tests
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/common/ut_common.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
Labels: not-for-changelog

#13205 YQ-3988 Add UnreadBytes sensor / fix labels for other sensors
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#12846 YQ-39-47 Add EgressDataRate sensor to pq write actor
  ydb/library/yql/providers/pq/async_io/dq_pq_write_actor.cpp
Labels: not-for-changelog

#13354 Support dynamic config propagation when distconf is off
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf_dynamic.cpp
Labels: not-for-changelog

#13360 fix network filter any
  ydb/core/viewer/viewer_nodes.h
Labels: bugfix

#13044 Add column CreatedAt to table Sids schemeshard localdb
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__init_root.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_login.cpp
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
  ydb/library/login/login.cpp
  ydb/library/login/login.h
  ydb/library/login/login_ut.cpp
  ydb/library/login/protos/login.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: improvement

#13362 Redefine flags for win32
  build/internal/ya.conf
  build/internal/ya.make.windows.conf
Labels: external

#12897 Only call DqOptimizeEquiJoinWithCosts when DQ connections are present
  ydb/library/yql/providers/dq/opt/logical_optimize.cpp
Labels: new-feature

#13269 Add account_type parameter for audit logs
  ydb/core/grpc_services/audit_logins.cpp
  ydb/core/grpc_services/audit_logins.h
  ydb/core/grpc_services/rpc_login.cpp
  ydb/core/protos/flat_tx_scheme.proto
  ydb/core/tx/schemeshard/schemeshard__login.cpp
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
Labels: not-for-changelog

#12149 add reason to lost lock message
  ydb/core/base/hive.h
  ydb/core/mind/hive/hive_events.h
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/tx__delete_tablet_result.cpp
  ydb/core/mind/hive/tx__disconnect_node.cpp
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__lock_tablet.cpp
  ydb/core/mind/hive/tx__release_tablets.cpp
  ydb/core/mind/hive/tx__unlock_tablet.cpp
  ydb/core/protos/hive.proto
Labels: improvement

#13389 Delete records with l_suppkey = 9999 before running
  ydb/tests/sql/large/test_insert_delete_duplicate_records.py
Labels: new-feature

#13367 builtin security: add CreateQueue permission to DDL-ADMINS
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/block-4-2.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/mirror-3dc-3-nodes-in-memory.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/mirror-3dc-3-nodes.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/mirror-3dc-9-nodes.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/simple.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/single-node-in-memory.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_basic_args0-dump_/single-node-with-file.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/block-4-2.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/disk.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/drive.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/mirror-3dc-3-nodes-distconf.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/mirror-3dc-3-nodes-in-memory.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/mirror-3dc-3-nodes.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/mirror-3dc-9-nodes.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/ram.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/single-node-in-memory.yaml.result.json
  ydb/library/yaml_config/ut_transform/canondata/test_transform.TestYamlConfigTransformations.test_simplified_dump_/single-node-with-file.yaml.result.json
  ydb/library/yaml_config/yaml_config_parser.cpp
Labels: not-for-changelog

#13357 Fix reading messages from Kafka API in no authentication mode
  ydb/core/kafka_proxy/actors/actors.h
  ydb/core/kafka_proxy/kafka_connection.cpp
Labels: not-for-changelog

#13376 Allow to configure the backtrace tracing for failed allocation
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/rm_service/kqp_rm_service.h
  ydb/core/kqp/rm_service/kqp_rm_ut.cpp
  ydb/core/protos/table_service_config.proto
Labels: new-feature

#13394 Fix race on table create delete
  ydb/tests/stress/olap_workload/__main__.py
Labels: not-for-changelog

#12872 YMQ tags
  ydb/core/grpc_services/service_ymq.h
  ydb/core/http_proxy/events.h
  ydb/core/http_proxy/http_req.cpp
  ydb/core/http_proxy/http_req.h
  ydb/core/http_proxy/ut/datastreams_fixture.h
  ydb/core/http_proxy/ut/ymq_ut.h
  ydb/core/protos/msgbus.proto
  ydb/core/protos/sqs.proto
  ydb/core/ymq/actor/action.h
  ydb/core/ymq/actor/actor.cpp
  ydb/core/ymq/actor/auth_multi_factory.cpp
  ydb/core/ymq/actor/create_queue.cpp
  ydb/core/ymq/actor/error.cpp
  ydb/core/ymq/actor/events.h
  ydb/core/ymq/actor/get_queue_attributes.cpp
  ydb/core/ymq/actor/index_events_processor.cpp
  ydb/core/ymq/actor/index_events_processor.h
  ydb/core/ymq/actor/list_queue_tags.cpp
  ydb/core/ymq/actor/metering.cpp
  ydb/core/ymq/actor/metering.h
  ydb/core/ymq/actor/proxy_actor.cpp
  ydb/core/ymq/actor/queue_leader.cpp
  ydb/core/ymq/actor/queue_leader.h
  ydb/core/ymq/actor/queue_schema.cpp
  ydb/core/ymq/actor/queue_schema.h
  ydb/core/ymq/actor/tag_queue.cpp
  ydb/core/ymq/actor/untag_queue.cpp
  ydb/core/ymq/actor/ut/metering_ut.cpp
  ydb/core/ymq/actor/ya.make
  ydb/core/ymq/actor/yc_search_ut/index_events_processor_ut.cpp
  ydb/core/ymq/base/acl.cpp
  ydb/core/ymq/base/action.cpp
  ydb/core/ymq/base/action.h
  ydb/core/ymq/base/helpers.cpp
  ydb/core/ymq/base/helpers.h
  ydb/core/ymq/base/limits.h
  ydb/core/ymq/base/processed_request_attributes.h
  ydb/core/ymq/base/query_id.h
  ydb/core/ymq/http/http.cpp
  ydb/core/ymq/http/http.h
  ydb/core/ymq/http/params.h
  ydb/core/ymq/http/parser.rl6
  ydb/core/ymq/http/types.h
  ydb/core/ymq/http/xml.cpp
  ydb/core/ymq/queues/common/db_queries_maker.cpp
  ydb/core/ymq/queues/common/queries.cpp
  ydb/core/ymq/queues/fifo/queries.cpp
  ydb/core/ymq/queues/std/queries.cpp
  ydb/public/api/grpc/draft/ydb_ymq_v1.proto
  ydb/public/api/protos/draft/ymq.proto
  ydb/services/ymq/grpc_service.cpp
  ydb/services/ymq/ymq_proxy.cpp
  ydb/services/ymq/ymq_proxy.h
  ydb/tests/functional/sqs/common/test_queue_tags.py
  ydb/tests/functional/sqs/common/test_queues_managing.py
  ydb/tests/functional/sqs/common/ya.make
  ydb/tests/library/sqs/requests_client.py
  ydb/tests/library/sqs/tables.py
  ydb/tests/library/sqs/test_base.py
Labels: run-sanitizer-tests

#12771 Docs: authorization
  ydb/docs/en/core/concepts/_includes/connect_overlay/auth_choose.md
  ydb/docs/en/core/concepts/auth.md
  ydb/docs/redirects.yaml
  ydb/docs/ru/core/_includes/do-not-create-users-in-ldap.md
  ydb/docs/ru/core/changelog-server.md
  ydb/docs/ru/core/concepts/_includes/connect_overlay/auth_choose.md
  ydb/docs/ru/core/concepts/datamodel/_includes/dir.md
  ydb/docs/ru/core/concepts/federated_query/ydb.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/concepts/toc_i.yaml
  ydb/docs/ru/core/dev/example-app/go/_includes/run_custom.md
  ydb/docs/ru/core/dev/example-app/java/_includes/run_custom.md
  ydb/docs/ru/core/dev/example-app/java/index.md
  ydb/docs/ru/core/dev/example-app/python/_includes/run_custom.md
  ydb/docs/ru/core/dev/terraform.md
  ydb/docs/ru/core/devops/manual/initial-deployment.md
  ydb/docs/ru/core/integrations/ingestion/logstash.md
  ydb/docs/ru/core/integrations/migration/liquibase.md
  ydb/docs/ru/core/integrations/orchestration/airflow.md
  ydb/docs/ru/core/integrations/visualization/grafana.md
  ydb/docs/ru/core/reference/configuration/index.md
  ydb/docs/ru/core/reference/configuration/tls.md
  ydb/docs/ru/core/reference/kafka-api/auth.md
  ydb/docs/ru/core/reference/kafka-api/read-write.md
  ydb/docs/ru/core/reference/ydb-cli/_includes/commands.md
  ydb/docs/ru/core/reference/ydb-cli/_includes/connect.md
  ydb/docs/ru/core/reference/ydb-cli/commands/_includes/scheme-describe.md
  ydb/docs/ru/core/reference/ydb-cli/commands/_includes/scheme-ls.md
  ydb/docs/ru/core/reference/ydb-cli/commands/config-info.md
  ydb/docs/ru/core/reference/ydb-cli/commands/scheme-permissions.md
  ydb/docs/ru/core/reference/ydb-cli/profile/_includes/create.md
  ydb/docs/ru/core/reference/ydb-cli/toc_i.yaml
  ydb/docs/ru/core/reference/ydb-dstool/global-options.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/auth.md
  ydb/docs/ru/core/reference/ydb-sdk/topic.md
  ydb/docs/ru/core/security/access-management.md
  ydb/docs/ru/core/security/authentication.md
  ydb/docs/ru/core/security/authorization.md
  ydb/docs/ru/core/security/encryption/data-in-transit.md
  ydb/docs/ru/core/security/index.md
  ydb/docs/ru/core/security/toc_p.yaml
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_assets/builtin_groups.svg
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/builtin_groups.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/permissions/permissions_list.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-group.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/alter-user.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/create-user.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/drop-user.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/grant.md
Labels: not-for-changelog

#13364 Fix some ubsan issues related to double vs ui64
  ydb/core/sys_view/service/ext_counters.cpp
  ydb/core/tablet_flat/ut/ut_stat.cpp
Labels: not-for-changelog

#13337 support folders in S3 uri in CS tiers
  ydb/core/tx/tiering/tier/object.cpp
  ydb/core/tx/tiering/tier/s3_uri.cpp
  ydb/core/tx/tiering/tier/s3_uri.h
  ydb/core/tx/tiering/tier/ya.make
  ydb/core/tx/tiering/ut/ut_object.cpp
Labels: improvement

#13077 Refactoring FillTopicDescription & FillChangefeedDescription
  ydb/core/ydb_convert/table_description.cpp
  ydb/core/ydb_convert/table_description.h
  ydb/core/ydb_convert/topic_description.cpp
  ydb/core/ydb_convert/topic_description.h
  ydb/core/ydb_convert/ya.make
  ydb/services/persqueue_v1/actors/schema_actors.cpp
  ydb/services/persqueue_v1/actors/ya.make
Labels: not-for-changelog

#12840 Description in the changelog about changefeed backup/restore
  ydb/apps/ydb/CHANGELOG.md
Labels: not-for-changelog

#13399 prepare move yt/comp_nodes/dq to llvm16
  ydb/core/kqp/federated_query/ya.make
  ydb/library/yql/tools/dq/worker_node/ya.make
  ydb/library/yql/tools/dqrun/ya.make
  ydb/library/yql/tools/mrrun/ya.make
  ydb/library/yql/yt/dq_vanilla_job.lite/ya.make
  ydb/library/yql/yt/dq_vanilla_job/ya.make
  ydb/library/yql/yt/native/ya.make
Labels: not-for-changelog

#13382 Support TString = std::string in TSerializedCellVec
  ydb/core/scheme/scheme_tablecell.cpp
  ydb/core/scheme/scheme_tablecell.h
Labels: not-for-changelog

#13408 Fix possible node crash in HTML rendering code
  ydb/core/blobstorage/nodewarden/node_warden_mon.cpp
Labels: bugfix

#13402 Fix docs for Way
  ydb/docs/en/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
  ydb/docs/ru/core/yql/reference/yql-core/builtins/_includes/basic/variant.md
Labels: documentation

#12135 YQ-3871 Restart session on query stopping (if query read historical data)
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/ya.make
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_blocking_queue.h
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_file_topic_client.cpp
  ydb/tests/fq/pq_async_io/mock_pq_gateway.cpp
  ydb/tests/fq/pq_async_io/mock_pq_gateway.h
  ydb/tests/fq/pq_async_io/ya.make
Labels: not-for-changelog

#13398 Docs: ydb.access.grant fix
  ydb/docs/ru/core/yql/reference/yql-core/syntax/_includes/permissions/permissions_list.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/grant.md
Labels: documentation

#13414 support pdisk build with musl
  ydb/library/pdisk_io/aio_linux.cpp
  ydb/library/pdisk_io/file_params_linux.cpp
  ydb/library/pdisk_io/wcache.cpp
Labels: not-for-changelog

#13409 Safe operation convertations
  ydb/core/grpc_services/rpc_export_base.h
  ydb/core/grpc_services/rpc_import_base.h
  ydb/core/grpc_services/rpc_operation_conv_base.h
  ydb/services/ydb/ydb_import_ut.cpp
Labels: not-for-changelog

#13307 return grandchildren flag
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/schemeshard/olap/operations/create_store.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_store.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_table.cpp
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_blob_depot.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_common.h
  ydb/core/tx/schemeshard/schemeshard__operation_copy_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_copy_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_backup_collection.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_bsv.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_cdc_stream.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_external_data_source.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_external_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_extsubdomain.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_fs.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_kesus.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_pq.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_replication.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_resource_pool.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_rtmr.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_solomon.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_subdomain.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_create_view.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_backup_collection.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_bsv.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_cdc_stream.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_external_data_source.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_external_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_fs.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_indexed_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_kesus.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_pq.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_replication.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_resource_pool.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_drop_view.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_mkdir.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_sequence.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_table_index.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_rmdir.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_path_describer.cpp
  ydb/core/tx/schemeshard/schemeshard_path_element.cpp
  ydb/core/tx/schemeshard/schemeshard_path_element.h
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
  ydb/core/tx/schemeshard/ut_cdc_stream/ut_cdc_stream.cpp
  ydb/core/tx/schemeshard/ut_reboots/ut_reboots.cpp
  ydb/core/tx/schemeshard/ut_subdomain/ut_subdomain.cpp
  ydb/core/tx/schemeshard/ut_subdomain_reboots/ut_subdomain_reboots.cpp
  ydb/core/tx/schemeshard/ut_user_attributes/ut_user_attributes.cpp
  ydb/core/tx/schemeshard/ut_user_attributes_reboots/ut_user_attributes_reboots.cpp
Labels: new-feature

#13119 generic lookup: handle retrievable errors in grpc
  ydb/library/yql/providers/generic/actors/yql_generic_base_actor.h
  ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
Labels: not-for-changelog

#12881 Validate blob size 0 on puts in DSProxy and VDisk
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
  ydb/core/blobstorage/ut_blobstorage/incorrect_queries.cpp
  ydb/core/blobstorage/ut_blobstorage/validation.cpp
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
Labels: improvement

#13238 Add icb configurable defrag inflight
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/defrag/defrag_actor.cpp
  ydb/core/blobstorage/vdisk/defrag/defrag_actor.h
  ydb/core/protos/config.proto
Labels: not-for-changelog

#13411 Explicit control of SelfManagement enabling in distconf
  ydb/core/blobstorage/base/blobstorage_events.cpp
  ydb/core/blobstorage/base/blobstorage_events.h
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_console.cpp
  ydb/core/blobstorage/nodewarden/distconf_dynamic.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/blobstorage/nodewarden/distconf_mon.cpp
  ydb/core/blobstorage/nodewarden/distconf_persistent_storage.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_mon.cpp
  ydb/core/blobstorage/nodewarden/node_warden_resource.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_bsc.cpp
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/console_interaction.cpp
  ydb/core/mind/bscontroller/console_interaction.h
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/mind/bscontroller/ut_bscontroller/main.cpp
  ydb/core/mind/bscontroller/ut_selfheal/node_warden_mock.h
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/mind/dynamic_nameserver_impl.h
Labels: not-for-changelog

#13118 generic lookup: enable tcp keep-alive on connector connection
  ydb/library/grpc/client/grpc_client_low.cpp
  ydb/library/grpc/client/grpc_client_low.h
  ydb/library/yql/providers/generic/connector/libcpp/client.cpp
Labels: bugfix

#13430 fix space color order in quota record
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_quota_record.h
Labels: not-for-changelog

#13436 Build YDB CLI arm binaries for linux and mac
  .github/workflows/build_ydb_cli.yml
Labels: area/cli, improvement

#12833 use canonized storage path as tier id
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/tx/columnshard/blobs_action/abstract/storages_manager.cpp
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.cpp
  ydb/core/tx/columnshard/engines/scheme/tiering/tier_info.h
  ydb/core/tx/columnshard/engines/scheme/tiering/ya.make
  ydb/core/tx/tiering/abstract/manager.cpp
  ydb/core/tx/tiering/abstract/manager.h
  ydb/core/tx/tiering/abstract/ya.make
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/manager.h
  ydb/core/tx/tiering/tier/identifier.cpp
  ydb/core/tx/tiering/tier/identifier.h
  ydb/core/tx/tiering/tier/ya.make
  ydb/core/tx/tiering/ut/ut_tiers.cpp
Labels: bugfix

#13433 avoid underflow on requests count
  ydb/core/viewer/json_pipe_req.cpp
Labels: bugfix

#13371 Multiprocess scenario test
  ydb/tests/olap/scenario/conftest.py
  ydb/tests/olap/scenario/helpers/scenario_tests_helper.py
  ydb/tests/olap/scenario/multitest.sh
  ydb/tests/olap/scenario/test.mk
  ydb/tests/olap/scenario/test_insert.py
Labels: new-feature

#13386 switching query to native http handler
  ydb/core/viewer/json_handlers.h
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/viewer.cpp
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/viewer_ut.cpp
Labels: improvement

#13239 Generic lookup add timeouts
  ydb/library/yql/providers/generic/actors/ut/yql_generic_lookup_actor_ut.cpp
  ydb/library/yql/providers/generic/actors/yql_generic_lookup_actor.cpp
  ydb/library/yql/providers/generic/connector/libcpp/client.cpp
  ydb/library/yql/providers/generic/connector/libcpp/client.h
  ydb/library/yql/providers/generic/connector/libcpp/ut_helpers/connector_client_mock.h
  ydb/library/yql/providers/generic/provider/ut/pushdown/pushdown_ut.cpp
Labels: not-for-changelog

#13444 Fix uncommitted changes leak and clean them up on startup
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__cleanup_uncommitted.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/execute_kqp_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
  ydb/core/tx/datashard/ya.make
Labels: bugfix

#11834 Change install instruction for ydb-dstool
  ydb/docs/en/core/reference/ydb-dstool/_includes/test.md
  ydb/docs/en/core/reference/ydb-dstool/_includes/unix_install.md
  ydb/docs/en/core/reference/ydb-dstool/_includes/unix_install_command.md
  ydb/docs/en/core/reference/ydb-dstool/install.md
  ydb/docs/ru/core/reference/ydb-dstool/_includes/test.md
  ydb/docs/ru/core/reference/ydb-dstool/_includes/unix_install.md
  ydb/docs/ru/core/reference/ydb-dstool/_includes/unix_install_command.md
  ydb/docs/ru/core/reference/ydb-dstool/install.md
Labels: documentation

#13197 Kafka port assignment through discoveryCache
  ydb/core/discovery/discovery.cpp
  ydb/core/discovery/discovery.h
  ydb/core/driver_lib/run/config_parser.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/grpc_services/grpc_endpoint.h
  ydb/core/kafka_proxy/actors/actors.h
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.h
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_connection.h
  ydb/core/kafka_proxy/kafka_listener.h
  ydb/core/kafka_proxy/ut/metarequest_ut.cpp
  ydb/core/kafka_proxy/ut/port_discovery_ut.cpp
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/kafka_proxy/ut/ya.make
  ydb/core/testlib/test_client.cpp
  ydb/services/persqueue_v1/actors/events.h
  ydb/services/persqueue_v1/actors/schema_actors.cpp
  ydb/services/persqueue_v1/actors/schema_actors.h
  ydb/services/persqueue_v1/ut/describes_ut/describe_topic_ut.cpp
Labels: new-feature

#13471 Muted unstable and unmute stable tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#13455 Detailed Shared Cache logs
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
Labels: not-for-changelog

#13488 add support for multipart response in viewer query
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/viewer_query.h
Labels: new-feature

#13407 fix nbs tests build
  ydb/core/base/hive.h
Labels: not-for-changelog

#13486 Library import 250117-1049
  build/conf/java.conf
  build/mapping.conf.json
  build/platform/java/jdk/jdk21/jdk.json
  build/platform/test_tool/host.ya.make.inc
  build/platform/test_tool/host_os.ya.make.inc
  build/plugins/java.py
  build/scripts/resolve_java_srcs.py
  ya
  ydb/ci/rightlib.txt
  yql/essentials/core/expr_nodes/yql_expr_nodes.json
  yql/essentials/core/type_ann/type_ann_core.cpp
  yql/essentials/core/type_ann/type_ann_impl.h
  yql/essentials/core/type_ann/type_ann_join.cpp
  yql/essentials/core/yql_expr_type_annotation.cpp
  yql/essentials/core/yql_expr_type_annotation.h
  yql/essentials/minikql/aligned_page_pool.cpp
  yql/essentials/minikql/comp_nodes/mkql_block_map_join.cpp
  yql/essentials/minikql/comp_nodes/mkql_rh_hash.h
  yql/essentials/minikql/mkql_block_map_join_utils.cpp
  yql/essentials/minikql/mkql_block_map_join_utils.h
  yql/essentials/minikql/mkql_rh_hash_utils.cpp
  yql/essentials/minikql/mkql_rh_hash_utils.h
  yql/essentials/minikql/ya.make
  yql/essentials/providers/common/mkql/yql_provider_mkql.cpp
  yt/yql/providers/yt/common/yql_yt_settings.cpp
  yt/yql/providers/yt/common/yql_yt_settings.h
  yt/yql/providers/yt/opt/yql_yt_join.h
  yt/yql/providers/yt/provider/yql_yt_join_impl.cpp
  yt/yt/client/table_client/unittests/serialization_ut.cpp
  yt/yt/client/table_client/unittests/ya.make
  yt/yt/client/table_client/unversioned_row.cpp
  yt/yt/library/profiling/solomon/public.h
  yt/yt/library/profiling/solomon/tag_registry.cpp
  yt/yt/library/profiling/unittests/solomon_ut.cpp
Labels: rightlib

#13496 Change link to dstool install page in a download page
  ydb/docs/en/core/downloads/index.md
  ydb/docs/ru/core/downloads/index.md
Labels: documentation

#13391 fixed bug in S3 Physical Optimizer 2
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_phy_opt.cpp
Labels: bugfix

#12999 Improve BufferActor
  ydb/core/kqp/common/buffer/events.cpp
  ydb/core/kqp/common/buffer/events.h
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/common/kqp_tx_manager.h
  ydb/core/kqp/counters/kqp_counters.cpp
  ydb/core/kqp/counters/kqp_counters.h
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: bugfix

#13462 move core/client tests to simple mkql invoker
  ydb/core/client/cancel_tx_ut.cpp
  ydb/core/client/client_ut.cpp
  ydb/core/client/flat_ut.cpp
  ydb/core/client/flat_ut_client.h
  ydb/core/client/locks_ut.cpp
  ydb/core/client/object_storage_listing_ut.cpp
  ydb/core/client/query_stats_ut.cpp
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server_proxy.cpp
  ydb/core/client/server/msgbus_server_proxy.h
  ydb/core/client/server/msgbus_server_request.cpp
  ydb/core/client/server/ya.make
  ydb/core/client/ut/ya.make
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/core/tx/tx_proxy/proxy_ext_tenant_ut.cpp
  ydb/core/tx/tx_proxy/proxy_ut.cpp
  ydb/core/tx/tx_proxy/proxy_ut_helpers.cpp
  ydb/core/tx/tx_proxy/storage_tenant_ut.cpp
Labels: not-for-changelog

#13457 Wilson uploader sensors
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/library/actors/wilson/wilson_uploader.cpp
  ydb/library/actors/wilson/wilson_uploader.h
Labels: not-for-changelog

#13123 Prepare login lockout info in order to use it in system view
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__login.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
  ydb/library/login/account_lockout/account_lockout.cpp
  ydb/library/login/account_lockout/account_lockout.h
  ydb/library/login/account_lockout/account_lockout_ut.cpp
  ydb/library/login/account_lockout/ut/ya.make
  ydb/library/login/account_lockout/ya.make
  ydb/library/login/login.cpp
  ydb/library/login/login.h
  ydb/library/login/login_ut.cpp
  ydb/library/login/protos/login.proto
  ydb/library/login/ya.make
Labels: improvement

#13507 descrease rows number in tests
  ydb/core/client/object_storage_listing_ut.cpp
Labels: not-for-changelog

#13508 switch ui32 to ui64
  ydb/core/fq/libs/compute/common/utils.cpp
Labels: not-for-changelog

#13421 Renamed the audit log parameter account_type to login_user_level
  ydb/core/grpc_services/audit_logins.cpp
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
Labels: not-for-changelog

#11458 Docs: Compression for Column Table
  ydb/docs/en/core/_includes/codec_zstd_allow_for_olap_note.md
  ydb/docs/en/core/_includes/codec_zstd_allow_for_olap_text.md
  ydb/docs/en/core/_includes/only_allow_for_olap_note.md
  ydb/docs/en/core/_includes/only_allow_for_olap_text.md
  ydb/docs/en/core/_includes/only_allow_for_oltp_note.md
  ydb/docs/en/core/_includes/only_allow_for_oltp_text.md
  ydb/docs/en/core/concepts/datamodel/_includes/table.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/alter_table/family.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/create_table/family.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/create_table/index.md
  ydb/docs/ru/core/_includes/codec_zstd_allow_for_olap_note.md
  ydb/docs/ru/core/_includes/codec_zstd_allow_for_olap_text.md
  ydb/docs/ru/core/_includes/not_allow_for_olap_text.md
  ydb/docs/ru/core/_includes/only_allow_for_olap_note.md
  ydb/docs/ru/core/_includes/only_allow_for_olap_text.md
  ydb/docs/ru/core/_includes/only_allow_for_oltp_note.md
  ydb/docs/ru/core/_includes/only_allow_for_oltp_text.md
  ydb/docs/ru/core/concepts/datamodel/_includes/table.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/alter_table/family.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/family.md
  ydb/docs/ru/core/yql/reference/yql-core/syntax/create_table/index.md
Labels: documentation

#13522 fix thread sanitizer alarms
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.h
Labels: bugfix

#13428 Eng docs: authorization
  ydb/docs/en/core/_includes/do-not-create-users-in-ldap.md
  ydb/docs/en/core/changelog-server.md
  ydb/docs/en/core/concepts/datamodel/_includes/dir.md
  ydb/docs/en/core/concepts/federated_query/ydb.md
  ydb/docs/en/core/concepts/glossary.md
  ydb/docs/en/core/concepts/toc_i.yaml
  ydb/docs/en/core/dev/example-app/go/_includes/run_custom.md
  ydb/docs/en/core/dev/example-app/java/_includes/run_custom.md
  ydb/docs/en/core/dev/example-app/java/index.md
  ydb/docs/en/core/dev/example-app/python/_includes/run_custom.md
  ydb/docs/en/core/dev/terraform.md
  ydb/docs/en/core/devops/manual/initial-deployment.md
  ydb/docs/en/core/integrations/ingestion/logstash.md
  ydb/docs/en/core/integrations/migration/liquibase.md
  ydb/docs/en/core/integrations/visualization/grafana.md
  ydb/docs/en/core/reference/configuration/index.md
  ydb/docs/en/core/reference/configuration/tls.md
  ydb/docs/en/core/reference/ydb-cli/_includes/commands.md
  ydb/docs/en/core/reference/ydb-cli/_includes/connect.md
  ydb/docs/en/core/reference/ydb-cli/commands/_includes/scheme-describe.md
  ydb/docs/en/core/reference/ydb-cli/commands/_includes/scheme-ls.md
  ydb/docs/en/core/reference/ydb-cli/commands/config-info.md
  ydb/docs/en/core/reference/ydb-cli/commands/scheme-permissions.md
  ydb/docs/en/core/reference/ydb-cli/profile/_includes/create.md
  ydb/docs/en/core/reference/ydb-cli/toc_i.yaml
  ydb/docs/en/core/reference/ydb-dstool/global-options.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/auth.md
  ydb/docs/en/core/reference/ydb-sdk/topic.md
  ydb/docs/en/core/security/access-management.md
  ydb/docs/en/core/security/authentication.md
  ydb/docs/en/core/security/authorization.md
  ydb/docs/en/core/security/encryption/data-in-transit.md
  ydb/docs/en/core/security/index.md
  ydb/docs/en/core/security/toc_p.yaml
  ydb/docs/en/core/yql/reference/yql-core/syntax/_assets/builtin_groups.svg
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/builtin_groups.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/_includes/permissions/permissions_list.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/alter-group.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/alter-user.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/create-user.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/drop-user.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/grant.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/revoke.md
  ydb/docs/en/core/yql/reference/yql-core/syntax/toc_i.yaml
  ydb/docs/ru/core/reference/ydb-cli/commands/scheme-permissions.md
Labels: documentation

#13510 remove rpc call Request from deprecated api code
  ydb/core/protos/grpc.proto
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/kicli/kikimr.cpp
Labels: not-for-changelog

#13494 FQ: Reduce buckets in histogram sensors
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
Labels: not-for-changelog

#13355 YQ-4017 / YQ-3947 / YQ-3988 / YQ-3871 to stable
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/common/ut_common.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/ya.make
  ydb/library/yql/providers/pq/async_io/dq_pq_write_actor.cpp
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_blocking_queue.h
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_file_topic_client.cpp
  ydb/tests/fq/pq_async_io/mock_pq_gateway.cpp
  ydb/tests/fq/pq_async_io/mock_pq_gateway.h
  ydb/tests/fq/pq_async_io/ya.make
Labels: not-for-changelog

#13491 RowDispatcher: split log messages by 64k
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
Labels: not-for-changelog
