Repository ydb-platform/ydb, pull requests merged in 2025-03, with the labels that each got.

#15175 indexes data extractor for providing subcolumns info
  .github/config/muted_ya.txt
  ydb/core/formats/arrow/accessor/sub_columns/stats.h
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/columnshard/bg_tasks/abstract/status_channel.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/common.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/common.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/coverage.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/coverage.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/tree.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/tree.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/ut/ut_program.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/ya.make
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/checker.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/checker.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/constructor.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/constructor.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/count_min_sketch/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/count_min_sketch/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/count_min_sketch/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/max/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/max/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/abstract.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/abstract.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/default.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/default.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/sub_column.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/sub_column.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/ya.make
  ydb/core/tx/columnshard/engines/storage/indexes/portions/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/ya.make
  ydb/core/tx/columnshard/splitter/chunks.h
  ydb/core/tx/columnshard/test_helper/program_constructor.cpp
  ydb/core/tx/columnshard/test_helper/program_constructor.h
  ydb/services/bg_tasks/abstract/interface.h
Labels: new-feature

#15216 Retry info status in dq_cli
  ydb/library/yql/tools/dq/dq_cli/main.cpp
Labels: not-for-changelog

#15186 Increase QUERY_TEXT_LIMIT for query stats to 10KB.
  ydb/core/kqp/session_actor/kqp_query_stats.cpp
Labels: improvement

#15138 Add UNAUTHORIZED status to dq
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/sys_view/ut_kqp.cpp
  ydb/library/yql/dq/actors/dq.cpp
  ydb/library/yql/dq/actors/dq.h
  ydb/library/yql/dq/actors/protos/dq_status_codes.proto
  ydb/tests/functional/tenants/test_auth_system_views.py
Labels: not-for-changelog

#14972 [KIKIMR-22738] (=) split ydb/core/control circular dependencies with ydb/core/base
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata.h
  ydb/core/blobstorage/common/immediate_control_defaults.h
  ydb/core/blobstorage/dsproxy/ya.make
  ydb/core/blobstorage/nodewarden/ya.make
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actorsystem_creator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/ya.make
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/common/vdisk_performance_params.h
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_overload_handler.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_overload_handler.h
  ydb/core/cms/console/immediate_controls_configurator.h
  ydb/core/cms/console/ya.make
  ydb/core/control/immediate_control_board_actor_ut.cpp
  ydb/core/control/immediate_control_board_impl.h
  ydb/core/control/lib/defs.h
  ydb/core/control/lib/immediate_control_board_control.cpp
  ydb/core/control/lib/immediate_control_board_control.h
  ydb/core/control/lib/immediate_control_board_impl.cpp
  ydb/core/control/lib/immediate_control_board_impl.h
  ydb/core/control/lib/immediate_control_board_ut.cpp
  ydb/core/control/lib/immediate_control_board_wrapper.h
  ydb/core/control/lib/ut/ya.make
  ydb/core/control/lib/ya.make
  ydb/core/control/ut/ya.make
  ydb/core/control/ya.make
  ydb/core/grpc_services/grpc_helper.h
  ydb/core/grpc_services/ya.make
  ydb/core/kqp/common/control.cpp
  ydb/core/kqp/common/control.h
  ydb/core/kqp/gateway/kqp_gateway.h
  ydb/core/kqp/session_actor/kqp_session_actor.h
  ydb/core/load_test/keyvalue_write.cpp
  ydb/core/load_test/pdisk_log.cpp
  ydb/core/load_test/pdisk_read.cpp
  ydb/core/load_test/pdisk_write.cpp
  ydb/core/load_test/ya.make
  ydb/core/mon_alloc/monitor.h
  ydb/core/mon_alloc/ya.make
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/ya.make
  ydb/core/testlib/actors/test_runtime.h
  ydb/core/testlib/basics/ya.make
  ydb/core/tx/columnshard/defs.h
  ydb/core/tx/columnshard/ya.make
  ydb/core/tx/coordinator/coordinator_impl.cpp
  ydb/core/tx/coordinator/coordinator_impl.h
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/tx_proxy/proxy.h
  ydb/core/util/actorsys_test/single_thread_ic_mock.cpp
  ydb/core/util/actorsys_test/testactorsys.cpp
Labels: improvement, external

#15228 Add access control on bootstrap
  ydb/core/base/appdata_fwd.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/grpc_services/rpc_config.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#15222 correct indexation and fix json construction
  ydb/core/formats/arrow/accessor/abstract/accessor.cpp
  ydb/core/formats/arrow/accessor/abstract/accessor.h
  ydb/core/formats/arrow/accessor/abstract/constructor.h
  ydb/core/formats/arrow/accessor/composite/accessor.h
  ydb/core/formats/arrow/accessor/composite/ut/ya.make
  ydb/core/formats/arrow/accessor/composite_serial/accessor.cpp
  ydb/core/formats/arrow/accessor/composite_serial/accessor.h
  ydb/core/formats/arrow/accessor/plain/accessor.cpp
  ydb/core/formats/arrow/accessor/plain/accessor.h
  ydb/core/formats/arrow/accessor/sparsed/accessor.cpp
  ydb/core/formats/arrow/accessor/sparsed/accessor.h
  ydb/core/formats/arrow/accessor/sparsed/ut/ya.make
  ydb/core/formats/arrow/accessor/sub_columns/accessor.cpp
  ydb/core/formats/arrow/accessor/sub_columns/accessor.h
  ydb/core/formats/arrow/accessor/sub_columns/data_extractor.cpp
  ydb/core/formats/arrow/accessor/sub_columns/data_extractor.h
  ydb/core/formats/arrow/accessor/sub_columns/others_storage.cpp
  ydb/core/formats/arrow/accessor/sub_columns/partial.cpp
  ydb/core/formats/arrow/accessor/sub_columns/partial.h
  ydb/core/formats/arrow/accessor/sub_columns/ut/ya.make
  ydb/core/formats/arrow/arrow_helpers.cpp
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/hash/calcer.cpp
  ydb/core/formats/arrow/hash/calcer.h
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/tx/columnshard/engines/predicate/container.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/sub_columns_fetching.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/default.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/meta.h
  ydb/library/formats/arrow/size_calcer.cpp
  ydb/library/formats/arrow/size_calcer.h
Labels: improvement

#15191 Unmute tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#15214 Fix limit tests for EvWrite
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
Labels: not-for-changelog

#15038 Get topic data handler
  ydb/core/http_proxy/ut/internal_counters.json
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/subscriber.h
  ydb/core/protos/msgbus_pq.proto
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/topic_data_ut.cpp
  ydb/core/viewer/ut/ut_utils.cpp
  ydb/core/viewer/ut/ut_utils.h
  ydb/core/viewer/ut/ya.make
  ydb/core/viewer/viewer_topic_data.cpp
  ydb/core/viewer/viewer_topic_data.h
  ydb/core/viewer/viewer_ut.cpp
  ydb/core/viewer/ya.make
Labels: new-feature

#15213 [C++ SDK] Added metrics for QueryClient
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/extensions/solomon_stats/README.md
  ydb/public/sdk/cpp/src/client/impl/ydb_stats/stats.h
  ydb/public/sdk/cpp/src/client/query/client.cpp
  ydb/public/sdk/cpp/src/client/query/impl/exec_query.cpp
  ydb/public/sdk/cpp/src/client/table/impl/table_client.cpp
  ydb/public/sdk/cpp/src/client/table/impl/table_client.h
Labels: not-for-changelog

#15245 Revert "Get topic data handler (#15038)"
  ydb/core/http_proxy/ut/internal_counters.json
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/subscriber.h
  ydb/core/protos/msgbus_pq.proto
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/topic_data_ut.cpp
  ydb/core/viewer/ut/ut_utils.cpp
  ydb/core/viewer/ut/ut_utils.h
  ydb/core/viewer/ut/ya.make
  ydb/core/viewer/viewer_topic_data.cpp
  ydb/core/viewer/viewer_topic_data.h
  ydb/core/viewer/viewer_ut.cpp
  ydb/core/viewer/ya.make
Labels: not-for-changelog

#15134 handle follower dying while being promoted to leader
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/local.cpp
Labels: bugfix

#15231 do not filter out dead tablets, set proper hive for dead tablets
  ydb/core/viewer/viewer_tabletinfo.h
Labels: not-for-changelog

#15212 #9056 Format module commands/interactive
  ydb/public/lib/ydb_cli/commands/interactive/interactive_cli.cpp
  ydb/public/lib/ydb_cli/commands/interactive/interactive_cli.h
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.cpp
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.h
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight.h
  ydb/public/lib/ydb_cli/commands/interactive/yql_highlight_ut.cpp
  ydb/public/lib/ydb_cli/commands/interactive/yql_position.cpp
  ydb/public/lib/ydb_cli/commands/interactive/yql_position.h
Labels: not-for-changelog, external

#15233 The counter value for `UserInfo` is leaking
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/ut/partition_ut.cpp
Labels: bugfix

#15237 filter chains optimization
  ydb/core/formats/arrow/program/abstract.cpp
  ydb/core/formats/arrow/program/abstract.h
  ydb/core/formats/arrow/program/aggr_keys.cpp
  ydb/core/formats/arrow/program/aggr_keys.h
  ydb/core/formats/arrow/program/assign_const.cpp
  ydb/core/formats/arrow/program/assign_const.h
  ydb/core/formats/arrow/program/assign_internal.cpp
  ydb/core/formats/arrow/program/assign_internal.h
  ydb/core/formats/arrow/program/chain.cpp
  ydb/core/formats/arrow/program/filter.cpp
  ydb/core/formats/arrow/program/filter.h
  ydb/core/formats/arrow/program/graph.cpp
  ydb/core/formats/arrow/program/graph.h
  ydb/core/formats/arrow/program/original.cpp
  ydb/core/formats/arrow/program/original.h
  ydb/core/formats/arrow/program/projection.cpp
  ydb/core/formats/arrow/program/projection.h
  ydb/core/formats/arrow/program/ya.make
  ydb/core/formats/arrow/ut/ut_program_step.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/sub_columns_fetching.h
Labels: new-feature

#15258 correct uptime group-by in viewer/nodes
  ydb/core/tablet/node_whiteboard.cpp
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/tests/test.py
  ydb/core/viewer/viewer_nodes.h
Labels: bugfix

#15268 fix tests flaky window
  .github/scripts/analytics/flaky_tests_history.py
Labels: not-for-changelog

#15055 Do not use OlapApply for known functions pushdown
  ydb/core/kqp/opt/physical/kqp_opt_phy_olap_filter.cpp
  ydb/core/kqp/opt/physical/predicate_collector.cpp
  ydb/core/kqp/opt/physical/predicate_collector.h
  ydb/core/kqp/ut/olap/aggregations_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-40
Labels: not-for-changelog

#15271 optimize sub columns iterations
  ydb/core/formats/arrow/accessor/sub_columns/columns_storage.h
  ydb/core/formats/arrow/accessor/sub_columns/iterators.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/sub_columns_fetching.h
Labels: performance

#15266 Add CleanupEC2MetadataClient()
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/driver_lib/run/ya.make
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
  ydb/core/tx/columnshard/ut_schema/ya.make
  ydb/core/tx/schemeshard/ut_backup/ut_backup.cpp
  ydb/core/tx/schemeshard/ut_backup/ya.make
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_export/ya.make
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ut_export_reboots_s3.cpp
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ya.make
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/core/tx/schemeshard/ut_restore/ya.make
  ydb/core/util/aws.cpp
  ydb/core/util/aws.h
  ydb/core/util/ya.make
  ydb/core/wrappers/s3_wrapper_ut.cpp
  ydb/core/wrappers/ut/ya.make
  ydb/services/ydb/backup_ut/ya.make
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#15168 If optional is empty, get proper JSON value
  ydb/core/ymq/actor/index_events_processor.cpp
  ydb/core/ymq/actor/yc_search_ut/index_events_processor_ut.cpp
  ydb/core/ymq/queues/common/queries.cpp
Labels: not-for-changelog

#15277 Fix use-of-uninitialized-value
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.h
Labels: not-for-changelog

#15227 make std::greater great again
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.h
Labels: not-for-changelog

#15293 Change MAX_REORDER_TX_KEYS from 100 to 1000 (main)
  ydb/core/tx/datashard/const.h
Labels: not-for-changelog

#15290 switch to scheme shard describe to get storage stats
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/viewer_tenantinfo.h
Labels: area/ui, bugfix

#14816 YQ kqprun added scripts for starting prometheus and connector
  ydb/tests/tools/fqrun/flame_graph.sh
  ydb/tests/tools/kqprun/README.md
  ydb/tests/tools/kqprun/configuration/app_config.conf
  ydb/tests/tools/kqprun/configuration/prometheus_config.yaml
  ydb/tests/tools/kqprun/flame_graph.sh
  ydb/tests/tools/kqprun/scripts/cleanup_docker.sh
  ydb/tests/tools/kqprun/scripts/flame_graph.sh
  ydb/tests/tools/kqprun/scripts/start_connector.sh
  ydb/tests/tools/kqprun/scripts/start_grafana.sh
  ydb/tests/tools/kqprun/scripts/start_prometheus.sh
Labels: improvement

#15298 Temporary mute all TSharedPageCache tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#15313 Comment failing CS re-sharding tests
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
Labels: not-for-changelog

#15311 Changed alias handling in CBO
  ydb/library/yql/dq/opt/dq_opt_join_hypergraph.h
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
Labels: bugfix

#15329 Update muted_ya.txt
  .github/config/muted_ya.txt
Labels: not-for-changelog

#15316 unmute test for kernels providing into CS
  .github/config/muted_ya.txt
Labels: improvement

#15331 Add --foreign-on-nosem for generate sem-graphs
  generate_cmake
Labels: bugfix

#15324 Library import 250304-1619
  library/python/monlib/metric_registry.pxd
  library/python/monlib/metric_registry.pyx
  library/python/monlib/ut/py2/test.py
  library/python/monlib/ut/py3/test.py
  ydb/ci/rightlib.txt
  ydb/library/yql/dq/transform/yql_common_dq_transform.cpp
  ydb/library/yql/providers/dq/runtime/task_command_executor.cpp
  ydb/library/yql/providers/dq/task_runner/tasks_runner_local.cpp
  ydb/library/yql/providers/ydb/comp_nodes/yql_ydb_dq_transform.cpp
  yql/essentials/core/dq_integration/transform/yql_dq_task_transform.cpp
  yql/essentials/core/dq_integration/transform/yql_dq_task_transform.h
  yql/essentials/tests/s-expressions/minirun/part8/canondata/result.json
  yql/essentials/tests/s-expressions/suites/Udf/PythonAvg.yqls
  yql/essentials/udfs/common/python/bindings/py_resource.cpp
  yt/yql/providers/yt/mkql_dq/yql_yt_dq_transform.cpp
  yt/yql/providers/yt/mkql_dq/yql_yt_dq_transform.h
Labels: rightlib

#15299 Support pausing TestShard writes through ICB
  ydb/core/protos/config.proto
  ydb/core/test_tablet/load_actor_impl.cpp
  ydb/core/test_tablet/load_actor_impl.h
Labels: not-for-changelog

#15319 Fix tests for default EvWrite
  .github/config/muted_ya.txt
  ydb/core/kqp/query_data/kqp_query_data.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/data_integrity/kqp_data_integrity_trails_ut.cpp
  ydb/core/kqp/ut/opt/kqp_not_null_ut.cpp
  ydb/core/kqp/ut/pg/pg_catalog_ut.cpp
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
  ydb/core/kqp/ut/query/kqp_params_ut.cpp
  ydb/library/yql/dq/actors/dq.cpp
Labels: not-for-changelog

#15297 don't return childrenExist prop for databases
  ydb/core/tx/schemeshard/schemeshard_path_describer.cpp
  ydb/core/viewer/tests/canondata/result.json
Labels: bugfix

#15327 FetchScriptResults. Fix crash on parsing of incorrect operation id
  ydb/core/grpc_services/query/rpc_fetch_script_results.cpp
  ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp
Labels: bugfix

#15328 Dump/resotore changefeeds tests
  ydb/core/tx/schemeshard/schemeshard_import_scheme_getter.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#15193 Add BuildStats B-Tree detailed logging
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table.h
  ydb/core/tablet_flat/flat_stat_table_btree_index.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.h
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.cpp
  ydb/core/tablet_flat/ya.make
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/library/services/services.proto
Labels: not-for-changelog

#15161 Refactor cache miss in `DynamicNameserver` to use one pipe
  ydb/core/base/tablet_pipe.h
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/mind/dynamic_nameserver_impl.h
  ydb/core/mind/node_broker_ut.cpp
  ydb/library/actors/core/interconnect.cpp
  ydb/library/actors/core/interconnect.h
  ydb/library/actors/interconnect/interconnect.h
  ydb/library/actors/interconnect/interconnect_handshake.cpp
  ydb/library/actors/interconnect/interconnect_impl.h
  ydb/library/actors/interconnect/interconnect_nameserver_base.h
  ydb/library/actors/interconnect/interconnect_nameserver_dynamic.cpp
  ydb/library/actors/interconnect/interconnect_resolve.cpp
  ydb/library/actors/testlib/test_runtime.cpp
  ydb/library/services/services.proto
  ydb/library/yql/providers/dq/actors/dynamic_nameserver.cpp
Labels: not-for-changelog

#15341 add subdomain key to required fiels for non-database requests
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/viewer_nodes.h
Labels: bugfix

#15347 Interactive Tx + uncommitted changes test
  ydb/core/kqp/ut/effects/kqp_immediate_effects_ut.cpp
Labels: not-for-changelog

#15003 Flush sink on INSERT
  ydb/core/kqp/common/kqp_tx.cpp
  ydb/core/kqp/common/kqp_tx.h
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/tx/kqp_locks_ut.cpp
  ydb/core/kqp/ut/tx/kqp_sink_tx_ut.cpp
Labels: not-for-changelog

#11580 Stop writing to column tables if quota is exceeded
  ydb/core/protos/counters_columnshard.proto
  ydb/core/protos/tx_columnshard.proto
  ydb/core/tx/columnshard/columnshard.h
  ydb/core/tx/columnshard/columnshard__init.cpp
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/columnshard_subdomain_path_id.cpp
  ydb/core/tx/columnshard/columnshard_subdomain_path_id.h
  ydb/core/tx/columnshard/loading/stages.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.h
  ydb/core/tx/columnshard/ya.make
  ydb/core/tx/datashard/datashard_subdomain_path_id.cpp
  ydb/core/tx/schemeshard/olap/operations/alter_store.cpp
  ydb/core/tx/schemeshard/olap/operations/alter_table.cpp
  ydb/core/tx/schemeshard/olap/operations/create_store.cpp
  ydb/core/tx/schemeshard/olap/operations/create_table.cpp
  ydb/core/tx/schemeshard/olap/operations/drop_table.cpp
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
  ydb/tests/functional/serverless/conftest.py
  ydb/tests/functional/serverless/test_serverless.py
  ydb/tests/library/harness/kikimr_config.py
Labels: new-feature

#15320 Column Shard Bytes Time Series
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/executer_actor/kqp_executer_stats.cpp
  ydb/core/kqp/executer_actor/kqp_executer_stats.h
Labels: new-feature

#15253 Fix fetch and replace for database config
  ydb/apps/ydb/CHANGELOG.md
  ydb/core/cms/console/console_configs_manager.h
  ydb/core/grpc_services/rpc_config.cpp
  ydb/core/grpc_services/rpc_config_base.h
  ydb/core/protos/console_config.proto
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.cpp
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.h
Labels: bugfix

#15354 Improve BlobDepot observability
  ydb/core/base/counters.cpp
  ydb/core/blob_depot/agent/agent.cpp
  ydb/core/blob_depot/agent/agent_impl.h
  ydb/core/blob_depot/agent/comm.cpp
  ydb/core/blob_depot/agent/query.cpp
  ydb/core/blob_depot/agent/read.cpp
  ydb/core/blob_depot/agent/storage_block.cpp
  ydb/core/blob_depot/agent/storage_collect_garbage.cpp
  ydb/core/blob_depot/agent/storage_discover.cpp
  ydb/core/blob_depot/agent/storage_get.cpp
  ydb/core/blob_depot/agent/storage_get_block.cpp
  ydb/core/blob_depot/agent/storage_patch.cpp
  ydb/core/blob_depot/agent/storage_put.cpp
  ydb/core/blob_depot/agent/storage_range.cpp
  ydb/core/blob_depot/agent/storage_status.cpp
  ydb/core/blob_depot/assimilator.cpp
  ydb/core/blob_depot/blob_depot_tablet.h
  ydb/core/blob_depot/data_load.cpp
  ydb/core/blob_depot/op_load.cpp
  ydb/core/protos/counters_blob_depot.proto
Labels: not-for-changelog

#15239 additional deadline checkers and info
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/actor/actor.h
Labels: bugfix

#15364 Fix error status for Oltp Sink
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/services/ydb/ydb_common_ut.h
  ydb/services/ydb/ydb_ut.cpp
Labels: not-for-changelog

#15366 Check yaml version in BSC mode
  ydb/core/mind/bscontroller/console_interaction.cpp
Labels: not-for-changelog

#15349 Increment YDB CLI version to 2.20.0
  ydb/apps/ydb/CHANGELOG.md
  ydb/apps/ydb/version.txt
Labels: area/cli, not-for-changelog

#15375 Fix authentification in BSC/Distconf
  ydb/core/cms/console/console_handshake.cpp
  ydb/core/grpc_services/rpc_config.cpp
Labels: bugfix

#15362 #9056 Switch YDB CLI complete to yql/essentials
  ydb/public/lib/ydb_cli/commands/interactive/antlr_ast/gen/v1_ansi_antlr4/epilogue.cmake
  ydb/public/lib/ydb_cli/commands/interactive/antlr_ast/gen/v1_ansi_antlr4/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/antlr_ast/gen/v1_antlr4/epilogue.cmake
  ydb/public/lib/ydb_cli/commands/interactive/antlr_ast/gen/v1_antlr4/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/antlr_ast/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
  ydb/public/lib/ydb_cli/commands/interactive/antlr_ast/org/antlr/v4/tool/templates/codegen/Cpp/Files.stg
  ydb/public/lib/ydb_cli/commands/interactive/complete/c3_engine.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_antlr4.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_antlr4.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_complete.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_complete.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_complete_ut.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_context.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_context.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_syntax.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/sql_syntax.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/string_util.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/string_util.h
  ydb/public/lib/ydb_cli/commands/interactive/complete/string_util_ut.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/ut/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/complete/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.cpp
  ydb/public/lib/ydb_cli/commands/interactive/ya.make
Labels: not-for-changelog, external

#15390 Reuse S3 locators to prevent false trash accumulation
  ydb/core/blob_depot/agent/agent_impl.h
  ydb/core/blob_depot/agent/comm.cpp
  ydb/core/blob_depot/agent/storage_put.cpp
  ydb/core/blob_depot/op_commit_blob_seq.cpp
  ydb/core/blob_depot/s3_write.cpp
  ydb/core/blob_depot/types.h
Labels: not-for-changelog

#15370 ydb-configure missing features, part 3
  ydb/tools/cfg/base.py
  ydb/tools/cfg/static.py
  ydb/tools/cfg/utils.py
  ydb/tools/cfg/validation.py
Labels: bugfix

#15396 Fix error message in auth check
  ydb/core/grpc_services/rpc_config.cpp
Labels: not-for-changelog

#15152 Show modal dialog in Hive UI before disabling/enabling tablets starting
  ydb/core/mind/hive/hive_statics.cpp
  ydb/core/mind/hive/monitoring.cpp
Labels: improvement

#15399 Nitpick use Cerr only in debug build
  ydb/core/tablet_flat/flat_stat_table.h
Labels: not-for-changelog

#15398 DataShard: prioritize cancellation processing for reads
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_trace.cpp
  ydb/core/tx/datashard/read_iterator.h
Labels: not-for-changelog

#15400 Fix VDisk premature donor drop
  ydb/core/blobstorage/vdisk/repl/blobstorage_repl.cpp
Labels: bugfix

#15414 [ydbd_slice] fixed AttributeError for sample-config command
  ydb/tools/ydbd_slice/__init__.py
Labels: not-for-changelog

#15416 YQ added YDB_AUTH_TICKET_HEADER for fq proxy ydb requests
  ydb/core/fq/libs/compute/ydb/control_plane/cms_grpc_client_actor.cpp
  ydb/core/fq/libs/compute/ydb/control_plane/monitoring_grpc_client_actor.cpp
  ydb/core/fq/libs/compute/ydb/control_plane/ya.make
  ydb/core/fq/libs/compute/ydb/control_plane/ydb_grpc_helpers.h
Labels: improvement

#15434 YQ kqprun enable generic pushdown by default
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: improvement

#15004 Remove legacy kv api (#10614)
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/msgbus_server_keyvalue.cpp
  ydb/core/client/server/msgbus_server_local_enumerate_tablets.cpp
  ydb/core/client/server/ya.make
  ydb/core/driver_lib/cli_utils/cli.h
  ydb/core/protos/grpc.proto
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/kicli/kikimr.cpp
Labels: not-for-changelog

#15411 EnableChangefeedsOnIndexTables is true by default
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#15418 Fix metadata processing on SectorMap
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_metadata.cpp
  ydb/library/pdisk_io/sector_map.h
Labels: not-for-changelog

#15429 Fix distconf automatic box management
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/impl.h
Labels: not-for-changelog

#15041 [docs] add version() to changelog-server.md
  ydb/docs/en/core/changelog-server.md
  ydb/docs/ru/core/changelog-server.md
Labels: documentation

#13121 Added information on the Prometheus configuration file
  ydb/docs/en/core/devops/manual/monitoring.md
  ydb/docs/ru/core/devops/manual/monitoring.md
Labels: documentation

#15439 Fix the bug on pipe failure in read proxy
  ydb/services/persqueue_v1/actors/partition_actor.cpp
Labels: bugfix

#15352 24-4 Add BuildStats B-Tree detailed logging
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table.h
  ydb/core/tablet_flat/flat_stat_table_btree_index.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.h
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.cpp
  ydb/core/tablet_flat/ya.make
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/library/services/services.proto
Labels: not-for-changelog

#15356 24-4-hotfix Add BuildStats B-Tree detailed logging
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table.h
  ydb/core/tablet_flat/flat_stat_table_btree_index.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.h
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.cpp
  ydb/core/tablet_flat/ya.make
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/library/services/services.proto
Labels: not-for-changelog

#15353 25-1 Add BuildStats B-Tree detailed logging
  ydb/core/tablet_flat/flat_stat_table.cpp
  ydb/core/tablet_flat/flat_stat_table.h
  ydb/core/tablet_flat/flat_stat_table_btree_index.cpp
  ydb/core/tablet_flat/flat_stat_table_btree_index.h
  ydb/core/tablet_flat/flat_stat_table_btree_index_histogram.cpp
  ydb/core/tablet_flat/ya.make
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/library/services/services.proto
Labels: not-for-changelog

#15265 [KIKIMR-22738] (-) minor fixes merge first decoupling ydb/core/control <-> ydb/core/base
  ydb/core/control/lib/ya.make
  ydb/core/control/ya.make
  ydb/core/mon_alloc/ya.make
Labels: improvement, external

#15342 YQ-4148 support yt parallel reading
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.cpp
  ydb/core/kqp/federated_query/kqp_federated_query_helpers.h
  ydb/core/kqp/federated_query/ya.make
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/session_actor/kqp_worker_common.cpp
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/protos/kqp_physical.proto
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/kqprun/src/ya.make
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tools/query_replay/query_compiler.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
Labels: performance

#15421 YMQ: Update format of labels in search events
  ydb/core/ymq/actor/index_events_processor.cpp
  ydb/core/ymq/actor/yc_search_ut/index_events_processor_ut.cpp
Labels: not-for-changelog

#15409 Fix index errors (sink)
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/opt/kqp_opt_kql.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_multishard_ut.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/kqp/ut/opt/kqp_not_null_ut.cpp
  ydb/core/kqp/ut/tx/kqp_tx_ut.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/dq.cpp
  ydb/library/yql/dq/actors/dq.h
Labels: not-for-changelog

#15449 Ignore case when comparing fifo suffix
  ydb/core/http_proxy/http_req.cpp
  ydb/core/ymq/base/queue_attributes.cpp
Labels: not-for-changelog

#15415 CreateDatabase: support specifying the number of coordinators/mediators
  ydb/core/cms/console/console__create_tenant.cpp
  ydb/public/api/protos/ydb_cms.proto
  ydb/tests/functional/tenants/test_dynamic_tenants.py
  ydb/tests/library/common/protobuf_console.py
  ydb/tests/library/harness/kikimr_cluster_interface.py
  ydb/tools/cfg/base.py
  ydb/tools/cfg/dynamic.py
Labels: not-for-changelog

#15464 Prepare datashard tests for default OltpSink=true + fixes
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
Labels: not-for-changelog

#15470 Allure report: pssh commands for additional info in tests
  ydb/tests/olap/lib/allure_utils.py
Labels: not-for-changelog

#15376 allow parsing out-of-range doubles in bulk-upsert
  ydb/core/formats/arrow/converter.cpp
  ydb/core/formats/arrow/converter.h
  ydb/core/grpc_services/rpc_load_rows.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
  ydb/core/ydb_convert/ydb_convert.cpp
  ydb/core/ydb_convert/ydb_convert.h
Labels: new-feature

#14860 healthcheck config
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/driver_lib/run/run.cpp
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/console_config.proto
Labels: improvement

#15097 scan compilation has been fixed
  ydb/core/tx/program/program.cpp
  ydb/core/tx/program/program.h
Labels: bug

#14085 Diagnostics of overloaded shards
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/aftermath-grafana-latencies.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/aftermath-grafana-latency-percentiles.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/aftermath-grafana-overloaded-shards.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/aftermath-grafana-shard-distribution-by-workload.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/aftermath-ui-cpu.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/aftermath-ui-top-shards.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-api-section-request-size.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-api-section-requests.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-api-section-response-size.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-api-section.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-by-execution-pool.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-1.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-2.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-3.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-4.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-ic-pool-by-host.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-ic-pool.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-cpu-dashboard-user-pool-by-actors.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-latencies.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-latency-percentiles.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-overloaded-shards.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-shard-distribution-by-workload.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-grafana-throughput-rows.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-ui-cpu-usage.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-ui-table-info.png
  ydb/docs/en/core/troubleshooting/examples/schemas/_assets/overloaded-shard-simple-case/incident-ui-top-shards.png
  ydb/docs/en/core/troubleshooting/examples/schemas/overloaded-shard-simple-case.md
  ydb/docs/en/core/troubleshooting/performance/schemas/overloaded-shards.md
  ydb/docs/en/core/troubleshooting/toc_p.yaml
Labels: documentation

#15448 Optimize index sorting in BSC SysView
  ydb/core/mind/bscontroller/sys_view.cpp
Labels: not-for-changelog

#14614 Read from single column shard
  ydb/core/kqp/common/kqp_yql.cpp
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/executer_actor/kqp_partition_helper.cpp
  ydb/core/kqp/opt/kqp_opt_kql.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/kqp_physical.proto
Labels: experimental-feature

#15314 Fix handle password complexity default values
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
  ydb/library/login/login_ut.cpp
  ydb/library/login/password_checker/password_checker.cpp
  ydb/library/login/password_checker/password_checker.h
  ydb/library/login/password_checker/password_checker_ut.cpp
Labels: bugfix

#15498 Fix uninitialized value in BSC
  ydb/core/mind/bscontroller/bsc.cpp
Labels: not-for-changelog

#15488 Revert "Make DEFAULT_EVENTS_PER_MAILBOX unreachable (#14843)"
  ydb/library/actors/core/config.h
Labels: bugfix

#8613 Remove legacy tablet APIs
  ydb/core/client/server/grpc_server.cpp
  ydb/core/client/server/msgbus_server.cpp
  ydb/core/client/server/msgbus_server.h
  ydb/core/client/server/msgbus_server_local_minikql.cpp
  ydb/core/client/server/msgbus_server_local_scheme_tx.cpp
  ydb/core/client/server/msgbus_server_tablet_kill.cpp
  ydb/core/client/server/ya.make
  ydb/core/driver_lib/cli_base/cli_kicli.cpp
  ydb/core/driver_lib/cli_base/cli_kicli.h
  ydb/core/protos/grpc.proto
  ydb/core/protos/msgbus.proto
  ydb/public/lib/base/msgbus.h
  ydb/public/lib/deprecated/client/grpc_client.cpp
  ydb/public/lib/deprecated/client/grpc_client.h
  ydb/public/lib/deprecated/kicli/kicli.h
  ydb/public/lib/deprecated/kicli/kikimr.cpp
Labels: not-for-changelog

#15501 improve test canonization
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/tests/test.py
Labels: not-for-changelog

#15524 Allure report: fix date format for filtering journalctrl
  ydb/tests/olap/lib/allure_utils.py
Labels: not-for-changelog

#15526 Remove formating in config fetch
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.cpp
Labels: not-for-changelog

#15435 Fix for a bug with backward compatibility in the export of changefeeds
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/datashard/export_s3_uploader.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#15338 fix SendChannelData(): requirement !outputChannel.RetryState in async CA
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
Labels: not-for-changelog

#15461 Fix cli vulnerabilities 2
  ydb/library/benchmarks/gen/tpcds-dbgen/build_support.c
  ydb/library/benchmarks/gen/tpcds-dbgen/tdefs.c
  ydb/library/benchmarks/gen/tpcds-dbgen/w_datetbl.c
  ydb/library/benchmarks/gen/tpcds-dbgen/w_item.c
  ydb/library/benchmarks/gen/tpch-dbgen/print.c
Labels: not-for-changelog

#15510 Move realization of pool stats collector to cpp files
  ydb/core/base/pool_stats_collector.cpp
  ydb/library/actors/helpers/collector_counters.cpp
  ydb/library/actors/helpers/collector_counters.h
  ydb/library/actors/helpers/pool_stats_collector.cpp
  ydb/library/actors/helpers/pool_stats_collector.h
  ydb/library/actors/helpers/ya.make
Labels: area/actorsystem, not-for-changelog

#15541 Update muted_ya.txt
  .github/config/muted_ya.txt
Labels: not-for-changelog

#15537 fix safe operation check in hive
  ydb/core/mind/hive/monitoring.cpp
Labels: not-for-changelog

#15358 Add functional tests for spilling
  ydb/tests/functional/tpc/large/test_tpcds.py
  ydb/tests/functional/tpc/large/test_tpch_spilling.py
  ydb/tests/functional/tpc/large/ya.make
  ydb/tests/functional/tpc/lib/conftest.py
  ydb/tests/olap/load/lib/tpch.py
Labels: improvement

#15542 fix tabletid in TBuildSlicesTask
  ydb/core/tx/columnshard/operations/slice_builder/builder.h
Labels: bugfix

#15540 Enable XDC by default, fix ut to use XDC transfers
  ydb/core/protos/config.proto
  ydb/library/actors/interconnect/interconnect_common.h
  ydb/library/actors/interconnect/ut/lib/test_events.h
  ydb/library/actors/interconnect/ut/protos/interconnect_test.proto
  ydb/library/actors/interconnect/ut_fat/main.cpp
Labels: performance

#15483 Add --backport-to-template functionality
  ydb/tools/cfg/base.py
  ydb/tools/cfg/bin/__main__.py
  ydb/tools/cfg/configurator_setup.py
  ydb/tools/cfg/static.py
  ydb/tools/cfg/utils.py
Labels: new-feature

#15516 Fix segfault in Group Layout Sanitizer, add stress tests with INACTIVE/FAULTY disks
  ydb/core/blobstorage/ut_blobstorage/sanitize_groups.cpp
  ydb/core/mind/bscontroller/group_mapper.cpp
Labels: bugfix

#15550 Fix datashard sink tests
  ydb/core/kqp/common/kqp_tx_manager.cpp
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/tx/datashard/datashard_ut_order.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_replication.cpp
  ydb/core/tx/datashard/datashard_ut_rs.cpp
  ydb/core/tx/datashard/datashard_ut_snapshot.cpp
  ydb/core/tx/datashard/ut_common/datashard_ut_common.h
Labels: not-for-changelog

#15081 Importing from PG example update
  ydb/docs/en/core/postgresql/docker-connect.md
  ydb/docs/en/core/postgresql/functions.md
  ydb/docs/en/core/postgresql/import.md
  ydb/docs/ru/core/postgresql/functions.md
  ydb/docs/ru/core/postgresql/import.md
Labels: documentation

#15561 fixing the ydbops config.yaml reference
  ydb/docs/en/core/reference/ydbops/configuration.md
  ydb/docs/ru/core/reference/ydbops/configuration.md
Labels: documentation

#15557 Initializing the configuration of the partition
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/pq_impl.cpp
Labels: bugfix

#13477 basic example query service
  ydb/docs/en/core/dev/example-app/go/_includes/run_custom.md
  ydb/docs/en/core/dev/example-app/go/_includes/run_docker.md
  ydb/docs/en/core/dev/example-app/go/index.md
  ydb/docs/ru/core/dev/example-app/go/_includes/run_custom.md
  ydb/docs/ru/core/dev/example-app/go/_includes/run_docker.md
  ydb/docs/ru/core/dev/example-app/go/index.md
Labels: documentation

#13902 Tests with reboots when exporting changefeeds to S3
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/datashard/export_s3_uploader.cpp
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ut_export_reboots_s3.cpp
  ydb/core/tx/schemeshard/ut_helpers/export_reboots_common.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#14522 Fix busywait on adding to full async input buffer
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/compute/dq_sync_compute_actor_base.h
Labels: not-for-changelog

#15479 direct read fix
  ydb/core/persqueue/dread_cache_service/caching_service.cpp
  ydb/services/persqueue_v1/actors/events.h
  ydb/services/persqueue_v1/actors/partition_actor.cpp
  ydb/services/persqueue_v1/actors/read_session_actor.cpp
Labels: bugfix

#15563 Remove unused virtual actors and related logic
  ydb/core/viewer/json_handlers.h
  ydb/core/viewer/scheme_directory.h
  ydb/library/actors/core/actor.cpp
  ydb/library/actors/core/actor.h
  ydb/library/actors/core/actor_virtual.cpp
  ydb/library/actors/core/actor_virtual.h
  ydb/library/actors/core/av_bootstrapped.cpp
  ydb/library/actors/core/av_bootstrapped.h
  ydb/library/actors/core/event.cpp
  ydb/library/actors/core/event.h
  ydb/library/actors/core/ut/mailbox_lockfree_ut.cpp
  ydb/library/actors/core/ut/performance_ut.cpp
  ydb/library/actors/core/ya.make
Labels: not-for-changelog

#15575 Add per-tx inflight counter to tablets and fix follower per-tx counters
  ydb/core/protos/counters.proto
  ydb/core/tablet_flat/flat_exec_seat.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor_txloglogic.cpp
Labels: not-for-changelog

#15578 Correct distconf enabling sequence
  ydb/core/blobstorage/base/blobstorage_console_events.h
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_console.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/cms/console/console_handshake.cpp
  ydb/core/cms/console/console_impl.h
  ydb/core/grpc_services/rpc_config_base.h
  ydb/core/protos/blobstorage.proto
  ydb/core/protos/blobstorage_distributed_config.proto
Labels: not-for-changelog

#15585 Increment YDB C++ SDK version to v3.2.2
  ydb/public/sdk/cpp/src/client/resources/ydb_sdk_version.txt
Labels: not-for-changelog

#15377 Fix compacted pages offload race
  ydb/core/tablet_flat/flat_boot_bundle.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_ops_compact.h
  ydb/core/tablet_flat/flat_part_loader.cpp
  ydb/core/tablet_flat/flat_part_loader.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
  ydb/core/tablet_flat/flat_scan_actor.h
  ydb/core/tablet_flat/shared_cache_events.h
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
  ydb/core/tablet_flat/ya.make
Labels: not-for-changelog

#14416 add health check overload shard hint
  ydb/core/health_check/health_check.cpp
  ydb/core/protos/sys_view.proto
  ydb/core/sys_view/partition_stats/partition_stats.cpp
  ydb/core/viewer/viewer_healthcheck.h
  ydb/public/api/protos/ydb_monitoring.proto
Labels: new-feature

#14741 increase logging around tablet unlocks
  ydb/core/base/hive.h
  ydb/core/mind/hive/hive.h
  ydb/core/mind/hive/tx__lock_tablet.cpp
  ydb/core/mind/hive/tx__unlock_tablet.cpp
Labels: not-for-changelog

#15477 check that we are not migrating tablets to ourselves
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/monitoring.cpp
Labels: improvement

#15614 Refactor short option handling
  ydb/public/lib/ydb_cli/common/command.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: area/cli, not-for-changelog

#15453 Unifying column names validation for both row and column tables #14722
  ydb/core/tx/schemeshard/olap/columns/update.cpp
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: bugfix

#15587 Yield fullsync processing when it takes too long
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_syncfull.cpp
Labels: improvement

#15617 Fix show create table with darwin
  ydb/core/sys_view/show_create/create_table_formatter.cpp
Labels: not-for-changelog

#15373 Removed alias stripping from CBO
  ydb/library/yql/dq/opt/dq_opt_join_hypergraph.h
Labels: bugfix

#15455 Fix Windows build
  ydb/core/blob_depot/agent/agent_impl.h
  ydb/core/blob_depot/agent/comm.cpp
  ydb/core/blob_depot/agent/read.cpp
  ydb/core/blob_depot/agent/s3.cpp
  ydb/core/blob_depot/agent/storage_put.cpp
  ydb/core/blob_depot/agent/ya.make
  ydb/core/blob_depot/s3.cpp
  ydb/core/blob_depot/s3.h
  ydb/core/blob_depot/s3_delete.cpp
  ydb/core/blob_depot/s3_scan.cpp
  ydb/core/blob_depot/s3_upload.cpp
  ydb/core/blob_depot/s3_windows_stub.cpp
  ydb/core/blob_depot/ya.make
  ydb/core/util/aws.cpp
  ydb/core/util/aws_windows_stub.cpp
  ydb/core/util/ya.make
Labels: not-for-changelog

#15625 view: tests with UDFs in the view query
  ydb/core/kqp/ut/view/input/cases/udf/create_view.sql
  ydb/core/kqp/ut/view/input/cases/udf/drop_view.sql
  ydb/core/kqp/ut/view/input/cases/udf/etalon_query.sql
  ydb/core/kqp/ut/view/input/cases/udf/select_from_view.sql
Labels: not-for-changelog

#15640 Refactor includes to YDB C++ SDK for schemeshard
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.h
  ydb/core/tx/schemeshard/ut_index/ut_async_index.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_index_build.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
  ydb/core/tx/tx_proxy/schemereq_ut.cpp
Labels: not-for-changelog

#15634 Refactor includes to YDB C++ SDK for ydb/core/viewer and ydb/mvp
  ydb/core/viewer/viewer.h
  ydb/core/viewer/viewer_query.h
  ydb/core/viewer/viewer_query_old.h
  ydb/mvp/core/core_ydb.h
  ydb/mvp/core/core_ydb_impl.h
  ydb/mvp/meta/meta_cloud.h
  ydb/mvp/meta/meta_cluster.h
  ydb/mvp/meta/meta_clusters.h
  ydb/mvp/meta/meta_cp_databases.h
  ydb/mvp/meta/meta_db_clusters.h
Labels: not-for-changelog

#15639 Refactor includes to YDB C++ SDK for core/config and core/tx/replication
  ydb/core/config/init/init_impl.h
  ydb/core/tx/replication/controller/private_events.h
  ydb/core/tx/replication/controller/stream_consumer_remover.cpp
  ydb/core/tx/replication/controller/stream_remover.cpp
  ydb/core/tx/replication/controller/util.h
  ydb/core/tx/replication/service/topic_reader_ut.cpp
  ydb/core/tx/replication/service/worker_ut.cpp
  ydb/core/tx/replication/ut_helpers/write_topic.h
  ydb/core/tx/replication/ydb_proxy/topic_message.h
  ydb/core/tx/replication/ydb_proxy/ydb_proxy.cpp
  ydb/core/tx/replication/ydb_proxy/ydb_proxy.h
  ydb/core/tx/replication/ydb_proxy/ydb_proxy_ut.cpp
Labels: not-for-changelog

#15633 Refactor includes to YDB C++ SDK for topics
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/persqueue/actor_persqueue_client_iface.h
  ydb/core/persqueue/cluster_tracker.cpp
  ydb/core/persqueue/codecs/pqv1.h
  ydb/core/persqueue/mirrorer.h
  ydb/core/persqueue/write_meta.h
  ydb/core/persqueue/writer/partition_chooser_impl__partition_helper.h
  ydb/core/persqueue/writer/partition_chooser_impl__table_helper.h
  ydb/core/persqueue/writer/source_id_encoding.h
  ydb/core/ymq/actor/auth_factory.h
  ydb/core/ymq/actor/auth_multi_factory.cpp
  ydb/core/ymq/actor/cleanup_queue_data.h
  ydb/core/ymq/actor/index_events_processor.cpp
  ydb/core/ymq/actor/index_events_processor.h
  ydb/core/ymq/actor/service.cpp
  ydb/core/ymq/actor/service.h
  ydb/core/ymq/base/run_query.h
  ydb/services/datastreams/datastreams_ut.cpp
  ydb/services/deprecated/persqueue_v0/grpc_pq_clusters_updater_actor.cpp
  ydb/services/persqueue_v1/actors/write_session_actor.cpp
  ydb/services/persqueue_v1/first_class_src_ids_ut.cpp
  ydb/services/persqueue_v1/persqueue_compat_ut.cpp
  ydb/services/persqueue_v1/persqueue_ut.cpp
  ydb/services/persqueue_v1/ut/demo_tx.cpp
  ydb/services/persqueue_v1/ut/persqueue_test_fixture.h
  ydb/services/persqueue_v1/ut/topic_service_ut.cpp
Labels: not-for-changelog

#15636 Refactor includes to YDB C++ SDK for columnshards
  ydb/core/kqp/ut/olap/blobs_sharing_ut.cpp
  ydb/core/kqp/ut/olap/datatime64_ut.cpp
  ydb/core/kqp/ut/olap/decimal_ut.cpp
  ydb/core/kqp/ut/olap/helpers/get_value.h
  ydb/core/kqp/ut/olap/helpers/query_executor.cpp
  ydb/core/kqp/ut/olap/helpers/query_executor.h
  ydb/core/kqp/ut/olap/helpers/typed_local.h
  ydb/core/kqp/ut/olap/indexes_ut.cpp
  ydb/core/kqp/ut/olap/optimizer_ut.cpp
  ydb/core/tx/columnshard/bg_tasks/abstract/session.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: not-for-changelog

#15641 Refactor includes to YDB C++ SDK for yql
  ydb/library/yql/providers/common/token_accessor/client/bearer_credentials_provider.h
  ydb/library/yql/providers/common/token_accessor/client/factory.h
  ydb/library/yql/providers/common/token_accessor/client/token_accessor_client.h
  ydb/library/yql/providers/common/token_accessor/client/token_accessor_client_factory.h
  ydb/library/yql/providers/dq/provider/yql_dq_gateway.h
  ydb/library/yql/providers/ydb/actors/yql_ydb_read_actor.h
  ydb/library/yql/providers/ydb/actors/yql_ydb_source_factory.h
  ydb/library/yql/providers/ydb/comp_nodes/yql_kik_scan.h
  ydb/library/yql/providers/ydb/comp_nodes/yql_ydb_factory.h
  ydb/library/yql/providers/ydb/provider/yql_ydb_provider.h
  ydb/library/yql/providers/ydb/provider/yql_ydb_provider_impl.h
Labels: not-for-changelog

#15588 Testing the full export/import pipeline of changefeeds
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
Labels: not-for-changelog

#15678 Fix validate PR description script
  .github/actions/update_changelog/update_changelog.py
  .github/workflows/validate_pr_description.yml
Labels: not-for-changelog

#15673 fix ydb/tests/olap/ttl_tiering build
  .github/config/muted_ya.txt
  ydb/tests/olap/ttl_tiering/data_correctness.py
  ydb/tests/olap/ttl_tiering/data_migration_when_alter_ttl.py
  ydb/tests/olap/ttl_tiering/ttl_delete_s3.py
  ydb/tests/olap/ttl_tiering/ttl_unavailable_s3.py
  ydb/tests/olap/ttl_tiering/unstable_connection.py
Labels: not-for-changelog

#15676 Revert removing executable options
  ydb/public/lib/ydb_cli/common/command.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: area/cli, not-for-changelog

#15677 Edit pq write actor logs
  ydb/library/yql/providers/pq/async_io/dq_pq_write_actor.cpp
Labels: not-for-changelog

#15620 docs: describe if exists / if not exists clauses for views
  ydb/docs/en/core/yql/reference/syntax/create-view.md
  ydb/docs/en/core/yql/reference/syntax/drop-view.md
  ydb/docs/ru/core/yql/reference/syntax/create-view.md
  ydb/docs/ru/core/yql/reference/syntax/drop-view.md
Labels: documentation

#15646 Fix get external source exception
  ydb/core/kqp/gateway/kqp_metadata_loader.cpp
Labels: not-for-changelog

#15600 Inefficient work with PQ Cache L2
  ydb/core/persqueue/cache_eviction.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/pq_l2_cache.cpp
  ydb/core/persqueue/pq_l2_cache.h
  ydb/core/persqueue/pq_l2_service.h
  ydb/core/persqueue/read.h
  ydb/services/persqueue_v1/persqueue_ut.cpp
Labels: not-for-changelog

#15679 Fix Console version handling
  ydb/core/cms/console/console_handshake.cpp
  ydb/core/mind/bscontroller/console_interaction.cpp
Labels: not-for-changelog

#15536 Make possible to set local ld_library_path in dq
  ydb/library/yql/providers/dq/config/config.proto
  ydb/library/yql/tools/dq/worker_job/dq_worker.cpp
Labels: not-for-changelog

#15698 extract test client to a separate file
  ydb/core/kafka_proxy/ut/kafka_test_client.cpp
  ydb/core/kafka_proxy/ut/kafka_test_client.h
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/kafka_proxy/ut/ya.make
Labels: not-for-changelog

#15691 [C++ SDK] Changed names for resources
  ydb/public/sdk/cpp/src/client/resources/ya.make
  ydb/public/sdk/cpp/src/client/resources/ydb_ca.cpp
  ydb/public/sdk/cpp/src/client/resources/ydb_resources.cpp
Labels: not-for-changelog

#15650 Return option to disable spilling (in channels in particular)
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/ut/spilling/kqp_scan_spilling_ut.cpp
Labels: not-for-changelog

#15703 Fix gui and add config metrics
  ydb/core/base/counters.cpp
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/config/init/init_impl.h
Labels: not-for-changelog
