Repository ydb-platform/ydb, pull requests merged in 2025-04, with the labels that each got.

#16559 YQ-4084 Remove new fields from harness
  ydb/tests/functional/ydb_cli/test_ydb_recursive_remove.py
  ydb/tests/library/harness/kikimr_config.py
  ydb/tests/library/harness/resources/default_yaml.yml
  ydb/tests/olap/ttl_tiering/base.py
Labels: not-for-changelog

#16565 fix latency aggregation, fix segfault on empty set
  ydb/core/graph/shard/backends.cpp
  ydb/core/sys_view/service/ext_counters.cpp
Labels: not-for-changelog

#16570 YQL-19747 Use configurable completion engine factory method
  ydb/public/lib/ydb_cli/commands/interactive/complete/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/complete/yql_completer.cpp
Labels: external

#16512 Sources collections separate from scanner
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/ya.make
Labels: performance

#16580 add GITHUB_TOKEN to wf Create issue to muted tests
  .github/workflows/create_issues_for_muted_tests.yml
Labels: not-for-changelog

#16485 Remove upload on page fault "optimization"
  ydb/core/tx/datashard/local_kmeans.cpp
  ydb/core/tx/datashard/prefix_kmeans.cpp
  ydb/core/tx/datashard/reshuffle_kmeans.cpp
Labels: not-for-changelog

#16585 use cpu limit from conveyor for writing
  ydb/core/tx/columnshard/engines/writer/buffer/actor2.cpp
  ydb/core/tx/columnshard/operations/batch_builder/builder.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/operations/write.cpp
  ydb/core/tx/conveyor/service/service.cpp
Labels: improvement

#16408 add new requests and responses containers for Kafka API
  ydb/core/kafka_proxy/kafka_messages.cpp
  ydb/core/kafka_proxy/kafka_messages.h
Labels: not-for-changelog

#15451 DataShard and SchemeShard: handle borrowed parts in data erasure
  ydb/core/protos/tx_datashard.proto
  ydb/core/testlib/storage_helpers.cpp
  ydb/core/testlib/storage_helpers.h
  ydb/core/testlib/test_client.h
  ydb/core/testlib/ya.make
  ydb/core/tx/datashard/datashard__data_cleanup.cpp
  ydb/core/tx/datashard/datashard_ut_data_cleanup.cpp
  ydb/core/tx/schemeshard/schemeshard__delete_tablet_reply.cpp
  ydb/core/tx/schemeshard/schemeshard__root_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/schemeshard__tenant_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/ut_data_erasure/ut_data_erasure.cpp
  ydb/core/tx/schemeshard/ut_helpers/data_erasure_helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/data_erasure_helpers.h
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/core/tx/schemeshard/ut_helpers/test_env.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.h
  ydb/core/tx/schemeshard/ut_stats/ut_stats.cpp
  ydb/core/tx/schemeshard/ut_subdomain/ut_subdomain.cpp
Labels: not-for-changelog

#16222 Muted zip bomb test
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.cpp
  ydb/tests/olap/ya.make
  ydb/tests/olap/zip_bomb.py
Labels: improvement

#15850 Fix optional columns handling in read_rows rpc
  ydb/core/grpc_services/rpc_read_rows.cpp
  ydb/core/kqp/ut/opt/kqp_kv_ut.cpp
  ydb/core/statistics/service/service_impl.cpp
Labels: bugfix

#16605 Fix workflow update muted_ya.txt
  .github/scripts/tests/update_mute_issues.py
  .github/workflows/collect_analytics.yml
  .github/workflows/create_issues_for_muted_tests.yml
  .github/workflows/update_muted_ya.yml
Labels: not-for-changelog

#16579 fixed typo in property name
  ydb/docs/en/core/reference/kafka-api/examples.md
  ydb/docs/ru/core/reference/kafka-api/examples.md
Labels: documentation

#16520 use PDisk id in VERIFYs
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_blockdevice_async.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_chunk_tracker.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_data.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_driveestimator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_free_chunks.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_metadata.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_keeper.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_log_cache.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_logreader.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_params.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_quota_record.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_req_creator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_sectorrestorator.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_syslogreader.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_tools.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_actions.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_helpers.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_run.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_flightcontrol.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_flightcontrol.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_sector.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_util_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_writer.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_writer.h
  ydb/core/blobstorage/pdisk/mock/pdisk_mock.cpp
Labels: not-for-changelog

#16018 Test cs read-write. Log scenario (write in the end)
  ydb/tests/olap/test_log_scenario.py
  ydb/tests/olap/ya.make
Labels: not-for-changelog

#16509 Show create table (Column-oriented tables)
  ydb/core/sys_view/show_create/create_table_formatter.cpp
  ydb/core/sys_view/show_create/create_table_formatter.h
  ydb/core/sys_view/show_create/show_create.cpp
  ydb/core/sys_view/show_create/ya.make
  ydb/core/sys_view/ut_common.cpp
  ydb/core/sys_view/ut_kqp.cpp
  ydb/core/sys_view/ya.make
  ydb/core/ydb_convert/table_description.cpp
  ydb/core/ydb_convert/table_description.h
Labels: not-for-changelog

#16611 Fix bug with ssl
  ydb/public/lib/ydb_cli/commands/ydb_root_common.cpp
Labels: not-for-changelog

#16631 WF `Create issues for muted tests`: fix filepath for created issues
  .github/scripts/tests/create_new_muted_ya.py
  .github/workflows/create_issues_for_muted_tests.yml
Labels: not-for-changelog

#16438 Fix for reading from column shard without specifying any columns
  ydb/core/kqp/opt/logical/kqp_opt_log_extract.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_olap_filter.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_rules.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/tests/functional/clickbench/canondata/test.test_plans_column_/queries-original-plan-column-0
Labels: bugfix

#16266 Add --no-discovery option to YDB cli
  ydb/apps/ydb/CHANGELOG.md
  ydb/apps/ydb/ut/parse_command_line.cpp
  ydb/public/lib/ydb_cli/commands/ydb_command.cpp
  ydb/public/lib/ydb_cli/commands/ydb_root_common.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: new-feature

#16583 YQ fixed bugs with grpc endpoints in kqprun
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/fqrun/src/fq_runner.cpp
  ydb/tests/tools/fqrun/src/fq_setup.cpp
  ydb/tests/tools/kqprun/README.md
  ydb/tests/tools/kqprun/configuration/app_config.conf
  ydb/tests/tools/kqprun/runlib/application.cpp
  ydb/tests/tools/kqprun/runlib/settings.h
  ydb/tests/tools/kqprun/runlib/utils.cpp
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/ya.make
Labels: bugfix

#16588 Fix vanishing node bug
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
Labels: bugfix

#16643 fix not linux build
  ydb/core/util/cpuinfo.cpp
Labels: new-feature

#16125 Fix bugs in DR restore
  ydb/core/persqueue/pq_impl.cpp
  ydb/services/persqueue_v1/actors/partition_actor.cpp
Labels: bugfix

#16575 TOptionsParseResult: throwing an exception in case of options parsing errors
  ydb/public/lib/ydb_cli/common/client_command_options.h
Labels: not-for-changelog

#16568 add get_settings action to graph shard
  ydb/core/graph/shard/tx_monitoring.cpp
  ydb/core/graph/shard/ya.make
Labels: not-for-changelog

#16603 dont control internal CS timeout
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
Labels: improvement

#16616 Extract index scan settings class
  ydb/core/protos/index_builder.proto
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/buffer_data.h
  ydb/core/tx/datashard/build_index.cpp
  ydb/core/tx/datashard/datashard_ut_prefix_kmeans.cpp
  ydb/core/tx/datashard/local_kmeans.cpp
  ydb/core/tx/datashard/prefix_kmeans.cpp
  ydb/core/tx/datashard/reshuffle_kmeans.cpp
  ydb/core/tx/datashard/sample_k.cpp
  ydb/core/tx/datashard/scan_common.h
  ydb/core/tx/datashard/upload_stats.h
  ydb/core/tx/schemeshard/schemeshard_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__create.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index_tx_base.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_index_build.cpp
Labels: not-for-changelog

#16563 ydb_configure features, part 5
  ydb/tools/cfg/base.py
  ydb/tools/cfg/bin/__main__.py
  ydb/tools/cfg/static.py
  ydb/tools/cfg/utils.py
  ydb/tools/cfg/ya.make
Labels: not-for-changelog

#16459 Fixed ACL docs
  ydb/docs/en/core/yql/reference/_includes/permissions_list.md
  ydb/docs/ru/core/yql/reference/_includes/permissions_list.md
Labels: documentation

#16457 Replace s3 acc name with s3 acc id
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_conn.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/auth-s3.md
Labels: documentation

#16645 Sync build dstool to build cli
  .github/workflows/build_ydb_dstool.yml
Labels: area/blobstorage, not-for-changelog

#16659 regularize ttl test definitions
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: not-for-changelog

#16602 dont validate program result (#16247)
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
Labels: not-for-changelog

#16600 dont validate program result (#16247)
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
Labels: not-for-changelog

#16669 Fix the swaager
  ydb/core/viewer/viewer_topic_data.h
Labels: not-for-changelog

#16626 extend VDisk log and verify prefix
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.h
  ydb/core/blobstorage/vdisk/common/vdisk_context.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_context.h
  ydb/core/blobstorage/vdisk/common/vdisk_log.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_log.h
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeletonfront.cpp
Labels: not-for-changelog

#15939 add compression to grpc server
  ydb/core/driver_lib/run/run.cpp
  ydb/core/protos/config.proto
  ydb/library/grpc/server/grpc_server.h
Labels: not-for-changelog

#16642 case unsensitive index
  ydb/core/formats/arrow/program/abstract.h
  ydb/core/formats/arrow/program/assign_internal.cpp
  ydb/core/formats/arrow/program/execution.h
  ydb/core/formats/arrow/program/graph_optimization.cpp
  ydb/core/formats/arrow/program/index.h
  ydb/core/formats/arrow/program/kernel_logic.cpp
  ydb/core/formats/arrow/program/kernel_logic.h
  ydb/core/formats/arrow/ut/ut_program_step.cpp
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.h
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/collection.cpp
  ydb/core/tx/columnshard/engines/scheme/indexes/abstract/collection.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/constructor.h
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/bloom_ngramm/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/categories_bloom/meta.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/categories_bloom/meta.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/abstract.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/default.cpp
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/default.h
  ydb/core/tx/columnshard/engines/storage/indexes/portions/extractor/sub_column.h
  ydb/core/tx/columnshard/engines/storage/indexes/skip_index/meta.h
  ydb/core/tx/columnshard/operations/slice_builder/pack_builder.cpp
  ydb/core/tx/program/builder.cpp
  ydb/core/tx/program/builder.h
Labels: new-feature

#16674 properly print table (adjust columns width)
  ydb/tools/stress_tool/device_test_tool.h
  ydb/tools/stress_tool/device_test_tool_pdisk_test.h
Labels: not-for-changelog

#16653 add tests for directory operations
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/tests/test.py
Labels: area/ui, not-for-changelog

#16614 Configure cluster access resource Id for Nebius_v1
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/protos/auth.proto
  ydb/core/security/ticket_parser_impl.h
  ydb/core/security/ticket_parser_ut.cpp
Labels: improvement

#16707 [docs] update toc_p.yaml
  ydb/docs/ru/core/contributor/documentation/toc_p.yaml
Labels: documentation

#16696 Support multicluster in dq_file/hybrid_file tests
  ydb/library/yql/tests/sql/dq_file.py
  ydb/library/yql/tests/sql/hybrid_file.py
Labels: not-for-changelog

#16686 enable gzip compression in main by default
  ydb/core/protos/config.proto
Labels: improvement

#16708 Group multiple blobs into single commit when assimilating
  ydb/core/blob_depot/assimilator.cpp
  ydb/core/blob_depot/assimilator.h
  ydb/core/blob_depot/data.h
  ydb/core/blob_depot/data_decommit.cpp
Labels: not-for-changelog

#16136 Fix lint for new diplodoc cli version
  ydb/docs/en/core/concepts/topic.md
  ydb/docs/en/core/contributor/load-actors-kqp.md
  ydb/docs/en/core/contributor/load-actors-memory.md
  ydb/docs/en/core/contributor/load-actors-pdisk-log.md
  ydb/docs/en/core/contributor/load-actors-pdisk-read.md
  ydb/docs/en/core/contributor/load-actors-pdisk-write.md
  ydb/docs/en/core/contributor/load-actors-stop.md
  ydb/docs/en/core/contributor/load-actors-storage.md
  ydb/docs/en/core/contributor/load-actors-vdisk.md
  ydb/docs/en/core/contributor/localdb-uncommitted-txs.md
  ydb/docs/en/core/reference/configuration/index.md
  ydb/docs/en/core/reference/ydb-cli/interactive-cli.md
  ydb/docs/en/core/reference/ydb-cli/operation-get.md
  ydb/docs/en/core/reference/ydb-cli/operation-list.md
  ydb/docs/en/core/reference/ydb-cli/parameterized-queries-cli.md
  ydb/docs/en/core/reference/ydb-cli/table-attribute-add.md
  ydb/docs/en/core/reference/ydb-cli/table-attribute-drop.md
  ydb/docs/en/core/reference/ydb-cli/table-drop.md
  ydb/docs/en/core/reference/ydb-cli/table-ttl-set.md
  ydb/docs/en/core/reference/ydb-cli/tools-copy.md
  ydb/docs/en/core/reference/ydb-cli/topic-alter.md
  ydb/docs/en/core/reference/ydb-cli/topic-consumer-add.md
  ydb/docs/en/core/reference/ydb-cli/topic-consumer-drop.md
  ydb/docs/en/core/reference/ydb-cli/topic-consumer-offset-commit.md
  ydb/docs/en/core/reference/ydb-cli/topic-create.md
  ydb/docs/en/core/reference/ydb-cli/topic-read.md
  ydb/docs/en/core/reference/ydb-cli/topic-write.md
  ydb/docs/en/core/reference/ydb-cli/version.md
  ydb/docs/en/core/reference/ydb-cli/workload-click-bench.md
  ydb/docs/en/core/reference/ydb-cli/workload-topic.md
  ydb/docs/en/core/reference/ydb-cli/workload-tpcds.md
  ydb/docs/en/core/reference/ydb-cli/workload-tpch.md
  ydb/docs/en/core/reference/ydb-sdk/feature-parity.md
  ydb/docs/ru/core/concepts/federated_query/s3/formats.md
  ydb/docs/ru/core/contributor/load-actors-kqp.md
  ydb/docs/ru/core/contributor/load-actors-memory.md
  ydb/docs/ru/core/contributor/load-actors-overview.md
  ydb/docs/ru/core/contributor/load-actors-pdisk-log.md
  ydb/docs/ru/core/contributor/load-actors-pdisk-read.md
  ydb/docs/ru/core/contributor/load-actors-pdisk-write.md
  ydb/docs/ru/core/contributor/load-actors-stop.md
  ydb/docs/ru/core/contributor/load-actors-storage.md
  ydb/docs/ru/core/contributor/load-actors-vdisk.md
  ydb/docs/ru/core/contributor/localdb-uncommitted-txs.md
  ydb/docs/ru/core/postgresql/import.md
  ydb/docs/ru/core/reference/configuration/index.md
  ydb/docs/ru/core/reference/ydb-cli/topic-read.md
  ydb/docs/ru/core/reference/ydb-cli/workload-click-bench.md
  ydb/docs/ru/core/reference/ydb-cli/workload-tpcds.md
  ydb/docs/ru/core/reference/ydb-cli/workload-tpch.md
  ydb/docs/ru/core/security/audit-log.md
  ydb/docs/ru/core/security/short-access-control-notation.md
  ydb/docs/ru/core/yql/reference/syntax/lexer.md
  ydb/docs/ru/core/yql/reference/types/primitive.md
  ydb/docs/ru/core/yql/reference/types/serial.md
  ydb/docs/ru/core/yql/reference/types/special.md
  ydb/docs/ru/core/yql/reference/udf/list/postgres.md
Labels: documentation, external

#16675 Fill TaskGraph Stages in Executer for consistency
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_table_resolver.cpp
  ydb/core/kqp/executer_actor/kqp_table_resolver.h
Labels: new-feature

#16706 clean yql operation id usage in CS scan
  ydb/core/formats/arrow/program/assign_internal.cpp
  ydb/core/formats/arrow/program/assign_internal.h
  ydb/core/formats/arrow/program/graph_optimization.cpp
  ydb/core/formats/arrow/program/graph_optimization.h
  ydb/core/formats/arrow/program/kernel_logic.cpp
  ydb/core/formats/arrow/program/kernel_logic.h
  ydb/core/formats/arrow/ut/ut_program_step.cpp
  ydb/core/tx/program/builder.cpp
Labels: improvement

#16721 YQL-19767: Realloc udf fix
  ydb/library/yql/udfs/common/roaring/roaring.cpp
Labels: not-for-changelog

#16722 Fix ut ALTER DATABASE OWNER TO in KQP
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
Labels: bugfix

#16682 Storage billing labels
  ydb/core/tx/schemeshard/schemeshard__serverless_storage_billing.cpp
  ydb/core/tx/schemeshard/ut_serverless/ut_serverless.cpp
Labels: not-for-changelog

#16414 YDB topics [Kafka API] add kafka transactions coordinator actor
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/kafka_proxy/actors/actors.h
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.h
  ydb/core/kafka_proxy/actors/kafka_transaction_actor.h
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_connection.h
  ydb/core/kafka_proxy/kafka_events.h
  ydb/core/kafka_proxy/kafka_listener.h
  ydb/core/kafka_proxy/kafka_transactions_coordinator.cpp
  ydb/core/kafka_proxy/kafka_transactions_coordinator.h
  ydb/core/kafka_proxy/ut/ut_transaction_coordinator.cpp
  ydb/core/kafka_proxy/ut/ya.make
  ydb/core/kafka_proxy/ya.make
  ydb/core/testlib/test_client.cpp
Labels: not-for-changelog

#16730 Clean up kmeans state
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/protos/out/out.cpp
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/datashard_ut_local_kmeans.cpp
  ydb/core/tx/datashard/datashard_ut_prefix_kmeans.cpp
  ydb/core/tx/datashard/datashard_ut_reshuffle_kmeans.cpp
  ydb/core/tx/datashard/kmeans_helper.cpp
  ydb/core/tx/datashard/kmeans_helper.h
  ydb/core/tx/datashard/local_kmeans.cpp
  ydb/core/tx/datashard/prefix_kmeans.cpp
  ydb/core/tx/datashard/reshuffle_kmeans.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: not-for-changelog

#16711 Fix ydb_configure generating dummy yaml
  ydb/tools/cfg/utils.py
Labels: not-for-changelog

#16729 Refactoring after PR 16434: rename schemeshard_import_scheme_getter.h -> schemeshard_import_getters.h
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_import_getters.h
  ydb/core/tx/schemeshard/schemeshard_import_scheme_getter.cpp
  ydb/core/tx/schemeshard/schemeshard_import_scheme_getter_fallback.cpp
Labels: not-for-changelog

#16734 Fix TStartPartitionSessionEvent::Confirm
  ydb/public/sdk/cpp/client/ydb_topic/impl/read_session_impl.ipp
  ydb/public/sdk/cpp/src/client/topic/impl/read_session_impl.ipp
  ydb/public/sdk/cpp/src/client/topic/ut/basic_usage_ut.cpp
Labels: bugfix

#16746 update all tests to use <string, ui64> tuples; add markdown-table result printer
  ydb/core/kqp/tools/combiner_perf/bin/main.cpp
  ydb/core/kqp/tools/combiner_perf/bin/ya.make
  ydb/core/kqp/tools/combiner_perf/converters.h
  ydb/core/kqp/tools/combiner_perf/printout.h
  ydb/core/kqp/tools/combiner_perf/run_params.h
  ydb/core/kqp/tools/combiner_perf/simple.cpp
  ydb/core/kqp/tools/combiner_perf/simple.h
  ydb/core/kqp/tools/combiner_perf/simple_block.cpp
  ydb/core/kqp/tools/combiner_perf/simple_block.h
  ydb/core/kqp/tools/combiner_perf/simple_last.cpp
  ydb/core/kqp/tools/combiner_perf/simple_last.h
  ydb/core/kqp/tools/combiner_perf/streams.cpp
  ydb/core/kqp/tools/combiner_perf/streams.h
  ydb/core/kqp/tools/combiner_perf/ya.make
Labels: not-for-changelog

#13916 add lwtracks for dsproxy get requests
  ydb/core/blobstorage/dsproxy/dsproxy_get.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
  ydb/core/blobstorage/dsproxy/root_cause.h
  ydb/core/blobstorage/dsproxy/ut/dsproxy_sequence_ut.cpp
  ydb/core/blobstorage/lwtrace_probes/blobstorage_probes.h
Labels: new-feature

#16654 SysView Auth Documentation (ru)
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/dev/system-views.md
Labels: documentation

#16693 Make config validation enforcement configurable
  ydb/core/cms/console/console_configs_manager.cpp
  ydb/core/config/init/init_impl.h
  ydb/library/yaml_config/ya.make
  ydb/library/yaml_config/yaml_config.cpp
  ydb/library/yaml_config/yaml_config.h
Labels: new-feature

#16758 another build fix for Darwin
  ydb/core/kqp/tools/combiner_perf/simple_block.cpp
Labels: not-for-changelog

#16692 log spam has been reduced
  ydb/services/metadata/ds_table/accessor_snapshot_base.cpp
  ydb/services/metadata/ds_table/accessor_snapshot_base.h
Labels: not-for-changelog

#16717 [Kafka API] Add interaction between kafka txn coordinator and init producer id actor
  ydb/core/kafka_proxy/actors/kafka_init_producer_id_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_init_producer_id_actor.h
  ydb/core/kafka_proxy/kafka_events.h
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/kafka_proxy/ut/ut_transaction_coordinator.cpp
Labels: not-for-changelog

#16757 fix optimizer for fetching merger
  ydb/core/formats/arrow/program/graph_optimization.cpp
  ydb/core/formats/arrow/program/graph_optimization.h
Labels: bugfix

#16745 kqp cursors withno sorting and unsorted collection
  ydb/core/kqp/common/kqp_yql.cpp
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/compute_actor/kqp_scan_fetcher_actor.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_partition_helper.cpp
  ydb/core/kqp/executer_actor/kqp_partition_helper.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.h
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_limit.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_sort.cpp
  ydb/core/kqp/query_compiler/kqp_mkql_compiler.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/columnshard/engines/predicate/filter.cpp
  ydb/core/tx/columnshard/engines/predicate/filter.h
  ydb/core/tx/columnshard/engines/reader/abstract/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/constructor.h
  ydb/core/tx/columnshard/engines/reader/abstract/read_metadata.h
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/common/description.h
  ydb/core/tx/columnshard/engines/reader/common/ya.make
  ydb/core/tx/columnshard/engines/reader/common_reader/constructor/read_metadata.cpp
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/iterator.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/constructor/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/constructor/constructor.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/constructor/constructor.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/chunks/chunks.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/granules/granules.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/optimizer/optimizer.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/portions/portions.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_internal_scan.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/operations/batch_builder/restore.cpp
  ydb/core/tx/columnshard/transactions/locks/read_start.cpp
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage.script-script_/write_multi_usage.script.plan
Labels: improvement

#16749 Refactoring after PR 16434: rename schemeshard_import_scheme_getter.cpp -> schemeshard_import_getters.cpp
  ydb/core/tx/schemeshard/schemeshard_import_getters.cpp
  ydb/core/tx/schemeshard/schemeshard_import_getters_fallback.cpp
  ydb/core/tx/schemeshard/ya.make
Labels: not-for-changelog

#16772 test for unsorted request case
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: improvement

#16752 dont validate program result (#16247)
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.h
Labels: not-for-changelog

#16764 hotfix: redirects in describe
  ydb/core/viewer/viewer_describe.h
Labels: bugfix

#16751 [C++ SDK] Added build for gcc-13
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/rate_limiter/rate_limiter.h
  ydb/public/sdk/cpp/src/client/topic/impl/proto_accessor.cpp
  ydb/public/sdk/cpp/src/client/topic/impl/ya.make
  ydb/public/sdk/cpp/src/client/topic/ya.make
Labels: new-feature

#16744 Implement safe compaction.
  ydb/apps/etcd_proxy/readme.txt
  ydb/apps/etcd_proxy/service/etcd_impl.cpp
  ydb/apps/etcd_proxy/service/ut/etcd_service_ut.cpp
Labels: improvement

#16771 [CLI] Fixed yql_parser build for windows
  ydb/public/lib/ydb_cli/common/yql_parser/ya.make
  ydb/public/lib/ydb_cli/common/yql_parser/yql_parser.cpp
Labels: not-for-changelog

#16769 Get rid of TCoroTx in decommission resolution routines
  ydb/core/blob_depot/data.h
  ydb/core/blob_depot/data_decommit.cpp
  ydb/core/blob_depot/data_load.cpp
  ydb/core/protos/counters_blob_depot.proto
Labels: not-for-changelog

#16770 additional signals for conveyor
  ydb/core/tx/conveyor/service/service.cpp
  ydb/core/tx/conveyor/service/service.h
Labels: improvement

#16786 Remove temporary patch from cmake build
  .github/actions/build/action.yml
Labels: not-for-changelog

#16792 Make DQ use only WideStream for ReplicateScalars
  ydb/library/yql/dq/opt/dq_opt_build.cpp
Labels: improvement

#16795 YQ kqprun, fixed storage setup with domains
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: bugfix

#16293 pq: add logbroker federation support
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.h
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor_base.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor_base.h
  ydb/library/yql/providers/pq/async_io/ya.make
  ydb/library/yql/providers/pq/common/pq_partition_key.cpp
  ydb/library/yql/providers/pq/common/pq_partition_key.h
  ydb/library/yql/providers/pq/common/ya.make
  ydb/library/yql/providers/pq/common/yql_names.h
  ydb/library/yql/providers/pq/expr_nodes/yql_pq_expr_nodes.json
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_dummy_gateway.cpp
  ydb/library/yql/providers/pq/gateway/dummy/yql_pq_dummy_gateway.h
  ydb/library/yql/providers/pq/gateway/native/ya.make
  ydb/library/yql/providers/pq/gateway/native/yql_pq_gateway.cpp
  ydb/library/yql/providers/pq/gateway/native/yql_pq_session.cpp
  ydb/library/yql/providers/pq/gateway/native/yql_pq_session.h
  ydb/library/yql/providers/pq/proto/dq_io.proto
  ydb/library/yql/providers/pq/provider/yql_pq_datasource_type_ann.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_gateway.h
  ydb/library/yql/providers/pq/provider/yql_pq_helpers.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_load_meta.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_provider.h
  ydb/library/yql/providers/pq/provider/yql_pq_topic_client.h
  ydb/tests/fq/pq_async_io/mock_pq_gateway.cpp
  ydb/tests/fq/pq_async_io/ut/dq_pq_rd_read_actor_ut.cpp
  ydb/tests/fq/pq_async_io/ut/dq_pq_read_actor_ut.cpp
Labels: not-for-changelog

#16773 Support progress stats with basic stats mode
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_executer_stats.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/protos/dq_events.proto
Labels: not-for-changelog

#16801 fix build
  ydb/public/sdk/cpp/client/ydb_topic/impl/read_session_impl.ipp
Labels: new-feature

#16765 Fix cli vulnerabilities 3
  ydb/library/benchmarks/gen/tpcds-dbgen/tdefs.c
  ydb/library/benchmarks/gen/tpcds-dbgen/w_datetbl.c
Labels: not-for-changelog

#16804 non sorted collection usage
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/plain_read_data.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
Labels: improvement

#16807 correct logs and branches priority
  ydb/core/formats/arrow/program/assign_internal.cpp
  ydb/core/formats/arrow/program/kernel_logic.cpp
  ydb/core/formats/arrow/program/kernel_logic.h
Labels: improvement

#16704 YQ-3903 Fix quota count (yq.streamingQuery.count)
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_impl.h
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_quotas.cpp
Labels: not-for-changelog

#16809 fix intervals counter for limit control
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/collections.cpp
Labels: bugfix

#16785 Revert "enable gzip compression in main by default (#16686)"
  ydb/core/protos/config.proto
Labels: not-for-changelog

#16810 optimize objects initialization
  ydb/core/formats/arrow/accessor/plain/accessor.cpp
  ydb/core/formats/arrow/accessor/sparsed/accessor.cpp
  ydb/core/formats/arrow/accessor/sparsed/accessor.h
Labels: performance

#13794 test disk exhaustion by duplicates
  ydb/tests/olap/data_quotas/test_quota_exhaustion.py
  ydb/tests/olap/data_quotas/ya.make
  ydb/tests/olap/ya.make
Labels: not-for-changelog

#16825 Library import 250407-0050
  contrib/python/argcomplete/py3/.dist-info/METADATA
  contrib/python/argcomplete/py3/argcomplete/finders.py
  contrib/python/argcomplete/py3/argcomplete/packages/_shlex.py
  contrib/python/argcomplete/py3/argcomplete/scripts/activate_global_python_argcomplete.py
  contrib/python/argcomplete/py3/argcomplete/shell_integration.py
  contrib/python/argcomplete/py3/ya.make
  library/cpp/blockcodecs/codecs.h
  library/cpp/json/json_value.h
  library/cpp/svnversion/svnversion.h
  library/cpp/testing/gtest_extensions/gtest_extensions.h
  library/cpp/threading/future/future.h
  library/cpp/threading/local_executor/local_executor.h
  library/cpp/threading/local_executor/tbb_local_executor.cpp
  library/cpp/threading/local_executor/tbb_local_executor.h
  ydb/ci/rightlib.txt
  yt/yt/client/api/rpc_proxy/public.h
  yt/yt/client/driver/etc_commands.cpp
  yt/yt/client/driver/etc_commands.h
  yt/yt/client/driver/proxy_discovery_cache.cpp
Labels: rightlib

#16826 Moved the parameter throw-on-parse-error from the options
  ydb/public/lib/ydb_cli/common/client_command_options.cpp
  ydb/public/lib/ydb_cli/common/client_command_options.h
  ydb/public/lib/ydb_cli/common/command.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: not-for-changelog

#16790 YDB FQ: fix creation of MySQL connections
  ydb/core/fq/libs/control_plane_proxy/actors/query_utils.cpp
  ydb/tests/fq/generic/analytics/docker-compose.yml
  ydb/tests/fq/generic/analytics/mysql/custom.cnf
  ydb/tests/fq/generic/analytics/mysql/init/init_db.sql
  ydb/tests/fq/generic/analytics/test_join.py
  ydb/tests/fq/generic/analytics/test_mysql.py
  ydb/tests/fq/generic/analytics/ya.make
  ydb/tests/fq/generic/utils/settings.py
  ydb/tests/tools/fq_runner/fq_client.py
  ydb/tests/tools/fq_runner/kikimr_utils.py
  ydb/tests/tools/mdb_mock/__main__.py
Labels: bugfix

#16836 Fix stats collection for long tasks
  ydb/core/kqp/executer_actor/kqp_executer_stats.cpp
Labels: not-for-changelog

#16794 Extra logs for Lost PlanStep #15494 debug
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
Labels: not-for-changelog

#16840 Fix log message
  ydb/core/persqueue/pq_impl.cpp
Labels: not-for-changelog

#16812 writing slowing with compaction criteria
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/counters/columnshard.cpp
  ydb/core/tx/columnshard/counters/columnshard.h
  ydb/core/tx/columnshard/counters/counters_manager.h
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/abstract.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.h
Labels: improvement

#16829 dont use filter. only result construction
  ydb/core/formats/arrow/accessor/abstract/accessor.cpp
  ydb/core/formats/arrow/accessor/abstract/accessor.h
  ydb/core/formats/arrow/accessor/abstract/common.cpp
  ydb/core/formats/arrow/accessor/abstract/common.h
  ydb/core/formats/arrow/accessor/abstract/ya.make
  ydb/core/formats/arrow/accessor/composite/accessor.cpp
  ydb/core/formats/arrow/accessor/composite/accessor.h
  ydb/core/formats/arrow/accessor/composite_serial/accessor.cpp
  ydb/core/formats/arrow/accessor/composite_serial/accessor.h
  ydb/core/formats/arrow/accessor/plain/accessor.h
  ydb/core/formats/arrow/accessor/sub_columns/accessor.cpp
  ydb/core/formats/arrow/accessor/sub_columns/accessor.h
  ydb/core/formats/arrow/accessor/sub_columns/columns_storage.cpp
  ydb/core/formats/arrow/accessor/sub_columns/columns_storage.h
  ydb/core/formats/arrow/accessor/sub_columns/constructor.cpp
  ydb/core/formats/arrow/accessor/sub_columns/iterators.h
  ydb/core/formats/arrow/accessor/sub_columns/others_storage.h
  ydb/core/formats/arrow/arrow_helpers.h
  ydb/core/formats/arrow/common/container.cpp
  ydb/core/formats/arrow/common/container.h
  ydb/core/formats/arrow/program/collection.h
  ydb/core/formats/arrow/program/filter.cpp
  ydb/core/formats/arrow/program/header.cpp
  ydb/core/formats/arrow/program/index.cpp
  ydb/core/formats/arrow/program/projection.cpp
  ydb/core/formats/arrow/program/stream_logic.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/sub_columns_fetching.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/library/formats/arrow/arrow_helpers.cpp
Labels: performance

#16837 Fix comp nodes logging in case when it's disabled
  ydb/core/kqp/ut/runtime/kqp_scan_logging_ut.cpp
  ydb/library/yql/dq/runtime/dq_tasks_runner.cpp
Labels: bugfix

#16851 Use INFO log level by default in dqrun
  ydb/library/yql/tools/dqrun/lib/dqrun_lib.cpp
Labels: area/yql, not-for-changelog

#16766 refactor describe handler
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/viewer_describe.h
Labels: not-for-changelog

#16841 Always use EvWrite
  ydb/core/protos/table_service_config.proto
  ydb/tests/functional/api/test_insert.py
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_dynumber_insert_from_table.sql-plan_/dynumber_insert_from_table.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_dynumber_insert_literal.sql-plan_/dynumber_insert_literal.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_dynumber_insert_params.sql-plan_/dynumber_insert_params.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_explain.script-script_/explain.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_join_group_by_lookup.script-script_/join_group_by_lookup.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_json_insert_from_table.sql-plan_/json_insert_from_table.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_json_insert_literal.sql-plan_/json_insert_literal.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_json_insert_params.sql-plan_/json_insert_params.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_simple_ct.script-script_/simple_ct.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_table_types.script-script_/table_types.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_insert.sql-plan_/write_insert.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_insert_revert.sql-plan_/write_insert_revert.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage.script-script_/write_multi_usage.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage_key.script-script_/write_multi_usage_key.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_write.sql-plan_/write_multi_write.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_replace.sql-plan_/write_replace.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_update.sql-plan_/write_update.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_update_on.sql-plan_/write_update_on.sql.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_write_group_by.script-script_/write_write_group_by.script.plan
Labels: not-for-changelog

#16855 one path will not reduce write speed for another
  ydb/core/tx/columnshard/tablet/write_queue.cpp
  ydb/core/tx/columnshard/tablet/write_queue.h
Labels: improvement

#16845 YDB: How to implement streaming RAG
  ydb/docs/en/core/public-materials/_includes/conferences/2025/fossasia.md
  ydb/docs/en/presets.yaml
  ydb/docs/ru/presets.yaml
Labels: documentation

#16652 Add ddl to create an iceberg data source
  ydb/core/external_sources/external_source_builder.cpp
  ydb/core/external_sources/external_source_builder.h
  ydb/core/external_sources/external_source_builder_ut.cpp
  ydb/core/external_sources/external_source_factory.cpp
  ydb/core/external_sources/iceberg_ddl_ut.cpp
  ydb/core/external_sources/iceberg_fields.h
  ydb/core/external_sources/ut/ya.make
  ydb/core/external_sources/ya.make
  ydb/core/kqp/gateway/behaviour/external_data_source/manager.cpp
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/federated_query/common/common.h
  ydb/core/kqp/ut/federated_query/generic_ut/iceberg_ut_data.cpp
  ydb/core/kqp/ut/federated_query/generic_ut/iceberg_ut_data.h
  ydb/core/kqp/ut/federated_query/generic_ut/kqp_generic_provider_ut.cpp
  ydb/core/kqp/ut/federated_query/generic_ut/ya.make
  ydb/library/yql/providers/common/db_id_async_resolver/database_type.cpp
  ydb/library/yql/providers/common/db_id_async_resolver/database_type.h
  ydb/library/yql/providers/generic/actors/yql_generic_provider_factories.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: new-feature

#16834 YDB FQ: enable pushdown of string types in Generic provider
  ydb/library/yql/providers/generic/provider/ut/pushdown/pushdown_ut.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_physical_opt.cpp
Labels: new-feature

#15287 YDB CLI 2.20.0 release notes
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/darwin_arm64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/linux_amd64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/linux_arm64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/windows.md
  ydb/docs/ru/core/changelog-cli.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/darwin_arm64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/linux_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/linux_arm64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/windows.md
Labels: documentation

#16895 add GraphShardExists setting to capabilities handler
  ydb/core/viewer/viewer_capabilities.h
Labels: not-for-changelog

#16484 Vector index docs
  ydb/docs/en/core/concepts/_includes/vector_indexes.md
  ydb/docs/en/core/concepts/column-table.md
  ydb/docs/en/core/concepts/datamodel/_includes/table.md
  ydb/docs/en/core/concepts/glossary.md
  ydb/docs/en/core/concepts/toc_i.yaml
  ydb/docs/en/core/concepts/vector_indexes.md
  ydb/docs/en/core/dev/toc_p.yaml
  ydb/docs/en/core/dev/vector-indexes.md
  ydb/docs/en/core/reference/observability/metrics/index.md
  ydb/docs/en/core/reference/ydb-cli/commands/_includes/secondary_index.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_export.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/tools_restore.md
  ydb/docs/en/core/yql/reference/syntax/alter_table/index.md
  ydb/docs/en/core/yql/reference/syntax/alter_table/indexes.md
  ydb/docs/en/core/yql/reference/syntax/alter_table/toc_i.yaml
  ydb/docs/en/core/yql/reference/syntax/create_table/index.md
  ydb/docs/en/core/yql/reference/syntax/create_table/toc_i.yaml
  ydb/docs/en/core/yql/reference/syntax/create_table/vector_index.md
  ydb/docs/en/core/yql/reference/syntax/select/toc_i.yaml
  ydb/docs/en/core/yql/reference/syntax/select/vector_index.md
  ydb/docs/ru/core/concepts/_includes/vector_indexes.md
  ydb/docs/ru/core/concepts/datamodel/_includes/table.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/concepts/toc_i.yaml
  ydb/docs/ru/core/concepts/vector_indexes.md
  ydb/docs/ru/core/dev/toc_p.yaml
  ydb/docs/ru/core/dev/vector-indexes.md
  ydb/docs/ru/core/reference/observability/metrics/index.md
  ydb/docs/ru/core/reference/ydb-cli/commands/_includes/secondary_index.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/export-s3.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/index.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/indexes.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/toc_i.yaml
  ydb/docs/ru/core/yql/reference/syntax/create_table/index.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/toc_i.yaml
  ydb/docs/ru/core/yql/reference/syntax/create_table/vector_index.md
  ydb/docs/ru/core/yql/reference/syntax/select/toc_i.yaml
  ydb/docs/ru/core/yql/reference/syntax/select/vector_index.md
Labels: documentation

#16377 Doc for TLI & Follower sysview
  ydb/docs/en/core/concepts/glossary.md
  ydb/docs/en/core/dev/system-views.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/dev/system-views.md
Labels: documentation

#16894 Add TablePathPrefix.
  ydb/apps/etcd_proxy/proxy.cpp
  ydb/apps/etcd_proxy/proxy.h
  ydb/apps/etcd_proxy/service/etcd_base_init.cpp
  ydb/apps/etcd_proxy/service/etcd_base_init.h
  ydb/apps/etcd_proxy/service/etcd_impl.cpp
  ydb/apps/etcd_proxy/service/etcd_shared.h
  ydb/apps/etcd_proxy/service/etcd_watch.cpp
  ydb/apps/etcd_proxy/service/ut/etcd_service_ut.cpp
Labels: improvement

#16897 Fixed move errors
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
Labels: not-for-changelog

#16867 use binsearch to find predicate bound in portion
  ydb/core/formats/arrow/arrow_filter.cpp
  ydb/core/formats/arrow/arrow_filter.h
  ydb/core/formats/arrow/ut/ut_arrow.cpp
  ydb/core/tx/columnshard/engines/predicate/container.cpp
  ydb/core/tx/columnshard/engines/predicate/container.h
  ydb/core/tx/columnshard/engines/predicate/filter.cpp
  ydb/core/tx/columnshard/engines/predicate/filter.h
  ydb/core/tx/columnshard/engines/predicate/range.cpp
  ydb/core/tx/columnshard/engines/predicate/range.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/sys_view/abstract/iterator.cpp
Labels: performance

#16437 YQ-4188 Add task controller config and add new sensors
  ydb/core/fq/libs/actors/run_actor.cpp
  ydb/core/fq/libs/config/protos/fq_config.proto
  ydb/core/fq/libs/config/protos/task_controller.proto
  ydb/core/fq/libs/config/protos/ya.make
  ydb/core/fq/libs/control_plane_storage/internal/task_ping.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_impl.h
  ydb/library/db_pool/db_pool.cpp
  ydb/tests/tools/fq_runner/kikimr_runner.py
Labels: not-for-changelog

#16869 Print expected cluster & version mismatches on configure
  ydb/core/cms/console/console__drop_yaml_config.cpp
  ydb/core/cms/console/console_configs_manager.cpp
Labels: not-for-changelog

#16929 refactoring in unit tests of SHOW CREATE TABLE
  ydb/core/sys_view/ut_common.h
  ydb/core/sys_view/ut_kqp.cpp
Labels: not-for-changelog

#16842 Fix histograms usage in KQP
  ydb/core/kqp/counters/kqp_counters.cpp
Labels: bugfix

#16909 Local-kmeans-one-scan
  ydb/core/tx/datashard/datashard_ut_local_kmeans.cpp
  ydb/core/tx/datashard/datashard_ut_prefix_kmeans.cpp
  ydb/core/tx/datashard/local_kmeans.cpp
  ydb/core/tx/datashard/prefix_kmeans.cpp
  ydb/core/tx/datashard/reshuffle_kmeans.cpp
  ydb/core/tx/datashard/sample_k.cpp
Labels: not-for-changelog

#16821 YQ supported compute databases in fqrun and in memory cp storage
  ydb/core/fq/libs/compute/common/config.h
  ydb/core/fq/libs/compute/ydb/control_plane/compute_database_control_plane_service.cpp
  ydb/core/fq/libs/config/protos/compute.proto
  ydb/core/fq/libs/control_plane_storage/events/events.h
  ydb/core/fq/libs/control_plane_storage/in_memory_control_plane_storage.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_bindings.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_compute_database.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_connections.cpp
  ydb/core/fq/libs/control_plane_storage/ydb_control_plane_storage_impl.h
  ydb/tests/fq/control_plane_storage/in_memory_control_plane_storage_ut.cpp
  ydb/tests/fq/streaming_optimize/cfg/app_config.conf
  ydb/tests/fq/streaming_optimize/cfg/fq_config.conf
  ydb/tests/fq/streaming_optimize/test_sql_streaming.py
  ydb/tests/fq/tools/fqrun.py
  ydb/tests/fq/yt/kqp_yt_import/kqprun_import_config.conf
  ydb/tests/fq/yt/kqp_yt_import/test_ctas.py
  ydb/tests/tools/fqrun/README.md
  ydb/tests/tools/fqrun/configuration/app_config.conf
  ydb/tests/tools/fqrun/configuration/as_config.conf
  ydb/tests/tools/fqrun/configuration/fq_config.conf
  ydb/tests/tools/fqrun/fqrun.cpp
  ydb/tests/tools/fqrun/src/common.h
  ydb/tests/tools/fqrun/src/fq_runner.cpp
  ydb/tests/tools/fqrun/src/fq_runner.h
  ydb/tests/tools/fqrun/src/fq_setup.cpp
  ydb/tests/tools/fqrun/src/fq_setup.h
  ydb/tests/tools/fqrun/src/ya.make
  ydb/tests/tools/kqprun/runlib/kikimr_setup.cpp
  ydb/tests/tools/kqprun/runlib/kikimr_setup.h
  ydb/tests/tools/kqprun/runlib/settings.h
  ydb/tests/tools/kqprun/runlib/ya.make
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: not-for-changelog

#16954 helper for combinatorial tests
  ydb/core/tx/columnshard/test_helper/test_combinator.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: not-for-changelog

#15992 Check ActorLibCollectUsageStats to reduce utils metric count
  ydb/library/actors/core/mailbox_lockfree.cpp
  ydb/library/actors/helpers/collector_counters.cpp
Labels: not-for-changelog

#16806 Lower log verbosity for schemeshard
  ydb/core/tx/schemeshard/schemeshard__operation_side_effects.cpp
  ydb/core/tx/schemeshard/schemeshard__pq_stats.cpp
  ydb/core/tx/schemeshard/schemeshard__table_stats.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
Labels: not-for-changelog

#16963 test overload with WritePortionsOnInsert
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
Labels: not-for-changelog

#16974 YQ kqprun, fixed settings passing
  ydb/tests/tools/fqrun/fqrun.cpp
  ydb/tests/tools/fqrun/src/fq_setup.cpp
  ydb/tests/tools/kqprun/runlib/kikimr_setup.cpp
  ydb/tests/tools/kqprun/runlib/kikimr_setup.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: bugfix

#16943 Fix `-d /Root` in `ydb admin cluster dump`
  ydb/apps/ydb/CHANGELOG.md
  ydb/library/backup/backup.cpp
  ydb/tests/functional/ydb_cli/test_ydb_backup.py
  ydb/tests/library/harness/kikimr_config.py
Labels: bugfix

#16977 Tpcds q73 order by ss_ticket_number
  ydb/library/benchmarks/queries/tpcds/pg/q73.sql
  ydb/library/benchmarks/queries/tpcds/yql/q73.sql
Labels: new-feature

#15351 Added parameter which sets fixed number of seconds to subtract from c…
  ydb/library/workload/log/log.cpp
  ydb/library/workload/log/log.h
Labels: improvement

#16978 recanonize tests (for suite tests)
  .github/config/muted_ya.txt
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join2.test_/query_10.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join2.test_/query_12.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join2.test_/query_5.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join2.test_/query_6.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-select.test_/query_1.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-select.test_/query_15.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-select.test_/query_16.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-select.test_/query_8.plan
  ydb/tests/functional/suite_tests/canondata/test_sql_logic.TestSQLLogic.test_sql_suite_plan-select1-1.test_/query_10.plan
  ydb/tests/functional/suite_tests/canondata/test_sql_logic.TestSQLLogic.test_sql_suite_plan-select2-1.test_/query_120.plan
  ydb/tests/functional/suite_tests/canondata/test_sql_logic.TestSQLLogic.test_sql_suite_plan-select2-3.test_/query_106.plan
  ydb/tests/functional/suite_tests/canondata/test_sql_logic.TestSQLLogic.test_sql_suite_plan-select2-4.test_/query_64.plan
  ydb/tests/functional/suite_tests/canondata/test_sql_logic.TestSQLLogic.test_sql_suite_plan-select3-9.test_/query_103.plan
  ydb/tests/functional/suite_tests/canondata/test_sql_logic.TestSQLLogic.test_sql_suite_plan-select3-9.test_/query_104.plan
  ydb/tests/functional/suite_tests/ya.make
Labels: not-for-changelog

#16958 Fix database restore failure when there are two database admins
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/tests/functional/ydb_cli/test_ydb_backup.py
Labels: bugfix

#16960 Retuned Value and Params tests to ydb-cpp-sdk CI
  ydb/public/sdk/cpp/src/library/retry/retry.h
  ydb/public/sdk/cpp/src/library/string_utils/base64/base64_decode_uneven_ut.cpp
  ydb/public/sdk/cpp/src/library/string_utils/base64/base64_ut.cpp
  ydb/public/sdk/cpp/tests/unit/client/params/params_ut.cpp
  ydb/public/sdk/cpp/tests/unit/client/params/ya.make
  ydb/public/sdk/cpp/tests/unit/client/value/value_ut.cpp
  ydb/public/sdk/cpp/tests/unit/client/value/ya.make
Labels: not-for-changelog

#16968 Reduce dq logs size
  ydb/library/yql/providers/dq/planner/execution_planner.cpp
Labels: area/yql, not-for-changelog

#16991 Added deviation param for test_log_scenario
  ydb/tests/olap/test_log_scenario.py
Labels: not-for-changelog

#16995 fix replay with query parameter types
  ydb/tools/query_replay_yt/main.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
  ydb/tools/query_replay_yt/query_replay.h
Labels: not-for-changelog

#16820 YQL-19747 Improve YDB CLI completion
  ydb/public/lib/ydb_cli/commands/interactive/complete/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/complete/yql_completer.cpp
  ydb/public/lib/ydb_cli/commands/interactive/complete/yql_completer.h
  ydb/public/lib/ydb_cli/commands/interactive/highlight/color/schema.cpp
  ydb/public/lib/ydb_cli/commands/interactive/highlight/color/schema.h
  ydb/public/lib/ydb_cli/commands/interactive/highlight/color/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/highlight/ya.make
  ydb/public/lib/ydb_cli/commands/interactive/highlight/yql_highlighter.cpp
  ydb/public/lib/ydb_cli/commands/interactive/highlight/yql_highlighter.h
  ydb/public/lib/ydb_cli/commands/interactive/line_reader.cpp
  ydb/public/lib/ydb_cli/commands/interactive/ya.make
Labels: not-for-changelog, external

#16922 Change exception to error in spilling queue
  ydb/library/yql/dq/actors/spilling/spilling_file.cpp
  ydb/library/yql/dq/actors/spilling/spilling_file_ut.cpp
Labels: not-for-changelog

#14163 Mixed stress test
  ydb/library/workload/mixed/mixed.cpp
  ydb/library/workload/mixed/mixed.h
  ydb/library/workload/mixed/registrar.cpp
  ydb/library/workload/mixed/ya.make
  ydb/library/workload/ya.make
  ydb/public/lib/ydb_cli/commands/ydb_workload.cpp
  ydb/tests/stress/mixedpy/test_mixed.py
  ydb/tests/stress/mixedpy/ya.make
  ydb/tests/stress/ya.make
Labels: new-feature

#16992 optimized SST index for blobs (index and iterator part)
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hullwritesst.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst.cpp
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst_it.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sstvec_it.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_buildslice.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullload.h
  ydb/core/blobstorage/vdisk/query/query_statalgo.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_shred.cpp
  ydb/core/blobstorage/vdisk/synclog/blobstorage_synclogkeeper_state.cpp
Labels: not-for-changelog

#17011 one more fix to query parameter types handling
  ydb/tools/query_replay_yt/query_compiler.cpp
Labels: not-for-changelog

#17008 Github workflows: Fix Regression runs multibranch support
  .github/actions/build_and_test_ya/action.yml
  .github/workflows/regression_run.yml
  .github/workflows/regression_run_compatibility.yml
  .github/workflows/regression_run_large.yml
  .github/workflows/regression_run_small_medium.yml
  .github/workflows/run_tests.yml
Labels: not-for-changelog

#16972 change parameter database to database_name in cp_databases
  ydb/mvp/meta/meta_cp_databases.h
Labels: not-for-changelog

#16986 YQ-4232 added validation for ShuffleLeftSideBy / ShuffleRightSideBy
  ydb/core/kqp/ut/join/kqp_join_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_join.cpp
Labels: bugfix

#16940 Set BSC LayoutCorrect default true
  ydb/core/health_check/health_check_ut.cpp
  ydb/core/protos/sys_view.proto
Labels: bugfix

#16902 YQ-4221 fixed s3 write with large path
  ydb/core/kqp/proxy_service/kqp_script_executions.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
Labels: bugfix

#17004 Don't pass expired failure injections to the child process
  ydb/library/yql/providers/dq/task_runner/tasks_runner_pipe.cpp
Labels: area/yql, not-for-changelog

#16994 Reduce column count under santizer to reduce execution time
  ydb/core/kqp/ut/olap/sparsed_ut.cpp
Labels: improvement

#16957 YDB FQ: support `Redis` as an external data source
  ydb/core/external_sources/external_source_factory.cpp
  ydb/library/yql/providers/common/db_id_async_resolver/database_type.cpp
  ydb/library/yql/providers/common/db_id_async_resolver/database_type.h
  ydb/library/yql/providers/generic/actors/yql_generic_provider_factories.cpp
  ydb/library/yql/providers/generic/connector/tests/utils/run/kqprun.py
  ydb/library/yql/providers/generic/provider/yql_generic_cluster_config.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: new-feature, external

#17056 Update regression_whitelist_run.yml shedule rules for branches
  .github/workflows/regression_whitelist_run.yml
Labels: not-for-changelog

#17055 Make diffs critical for tpch 10k and tpcds 10
  ydb/tests/olap/load/lib/tpcds.py
  ydb/tests/olap/load/lib/tpch.py
Labels: new-feature

#17000 Better BadRequest in index builders
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/build_index.cpp
  ydb/core/tx/datashard/datashard_ut_build_index.cpp
  ydb/core/tx/datashard/datashard_ut_local_kmeans.cpp
  ydb/core/tx/datashard/datashard_ut_prefix_kmeans.cpp
  ydb/core/tx/datashard/datashard_ut_reshuffle_kmeans.cpp
  ydb/core/tx/datashard/datashard_ut_sample_k.cpp
  ydb/core/tx/datashard/kmeans_helper.cpp
  ydb/core/tx/datashard/kmeans_helper.h
  ydb/core/tx/datashard/local_kmeans.cpp
  ydb/core/tx/datashard/prefix_kmeans.cpp
  ydb/core/tx/datashard/reshuffle_kmeans.cpp
  ydb/core/tx/datashard/sample_k.cpp
Labels: not-for-changelog

#15444 Fill MinStep for Tx
  ydb/core/tx/columnshard/columnshard__propose_transaction.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/common/snapshot.cpp
  ydb/core/tx/columnshard/common/snapshot.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.h
  ydb/core/tx/columnshard/test_helper/shard_writer.cpp
  ydb/core/tx/columnshard/test_helper/shard_writer.h
  ydb/core/tx/columnshard/transactions/tx_controller.cpp
  ydb/core/tx/columnshard/transactions/tx_controller.h
  ydb/core/tx/columnshard/ut_rw/ut_backup.cpp
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
  ydb/core/tx/columnshard/ut_rw/ut_normalizer.cpp
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
  ydb/library/accessor/positive_integer.cpp
  ydb/library/accessor/positive_integer.h
Labels: not-for-changelog

#16989 Add operation details in audit logging of operation 'MODIFY USER'
  ydb/core/tx/schemeshard/schemeshard_audit_log.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log_fragment.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log_fragment.h
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
Labels: improvement
