Repository ydb-platform/ydb, pull requests merged in 2025-08, with the labels that each got.

#21698 YQ-4454 fixed clickhouse udf includes
  ydb/library/yql/providers/s3/actors/yql_arrow_column_converters.h
  ydb/library/yql/providers/s3/actors/yql_s3_actors_factory_impl.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_source_queue.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_write_actor.cpp
  ydb/library/yql/providers/s3/common/source_context.h
  ydb/library/yql/providers/s3/compressors/brotli.cpp
  ydb/library/yql/providers/s3/compressors/brotli.h
  ydb/library/yql/providers/s3/compressors/bzip2.cpp
  ydb/library/yql/providers/s3/compressors/bzip2.h
  ydb/library/yql/providers/s3/compressors/factory.cpp
  ydb/library/yql/providers/s3/compressors/factory.h
  ydb/library/yql/providers/s3/compressors/gz.cpp
  ydb/library/yql/providers/s3/compressors/gz.h
  ydb/library/yql/providers/s3/compressors/lz4io.cpp
  ydb/library/yql/providers/s3/compressors/lz4io.h
  ydb/library/yql/providers/s3/compressors/ut/decompressor_ut.cpp
  ydb/library/yql/providers/s3/compressors/xz.cpp
  ydb/library/yql/providers/s3/compressors/xz.h
  ydb/library/yql/providers/s3/compressors/ya.make
  ydb/library/yql/providers/s3/compressors/zstd.cpp
  ydb/library/yql/providers/s3/compressors/zstd.h
  ydb/library/yql/providers/s3/events/events.cpp
  ydb/library/yql/providers/s3/events/events.h
  ydb/library/yql/providers/s3/serializations/serialization_interval.cpp
  ydb/library/yql/udfs/common/clickhouse/client/base/common/defines.h
Labels: bugfix

#21959 Use unique_ptr to allocate TInterconnectListenerTCP in kikimr_services_initializers.cpp to aviod memory leak on Bind() failure
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
Labels: not-for-changelog

#22094 Refactor Memory Controller Column Tables memory
  ydb/core/base/memory_controller_iface.h
  ydb/core/driver_lib/run/config_helpers.cpp
  ydb/core/memory_controller/memory_controller.cpp
  ydb/core/memory_controller/memory_controller.h
  ydb/core/memory_controller/memory_controller_config.h
  ydb/core/memory_controller/memory_controller_ut.cpp
  ydb/core/tx/columnshard/blob_cache.cpp
  ydb/core/tx/columnshard/column_fetching/cache_policy.h
  ydb/core/tx/columnshard/common/limits.h
  ydb/core/tx/columnshard/data_accessor/cache_policy/policy.h
  ydb/core/tx/limiter/grouped_memory/usage/service.h
Labels: not-for-changelog

#22160 YQ-4447 disabled thread pool in s3 by default
  ydb/library/yql/providers/s3/provider/yql_s3_settings.cpp
Labels: bugfix

#21299 fix compaction max inflight
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompactworker.h
Labels: bugfix

#20481 Add BSC validation on distconf/BSC replace request
  ydb/core/blobstorage/base/blobstorage_events.h
  ydb/core/blobstorage/base/blobstorage_host_record.h
  ydb/core/blobstorage/base/ya.make
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/config_cmd.cpp
  ydb/core/mind/bscontroller/config_fit_pdisks.cpp
  ydb/core/mind/bscontroller/console_interaction.cpp
  ydb/core/mind/bscontroller/console_interaction.h
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/storage_stats_calculator.cpp
  ydb/core/mind/bscontroller/storage_stats_calculator.h
  ydb/core/mind/bscontroller/sys_view.cpp
  ydb/core/mind/bscontroller/sys_view.h
  ydb/core/protos/blobstorage_config.proto
  ydb/services/config/bsconfig_ut.cpp
  ydb/tests/functional/config/test_distconf.py
  ydb/tests/functional/config/ya.make
Labels: not-for-changelog

#22190 Update update_muted_ya.yml (25-1-3)
  .github/workflows/update_muted_ya.yml
Labels: not-for-changelog

#22168 increase retry delay for tier config fetching
  ydb/core/tx/tiering/manager.cpp
Labels: bugfix

#21856 Use tablet state subscriptions in tablet resolver
  ydb/core/base/statestorage_proxy.cpp
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/cms/console/feature_flags_configurator_ut.cpp
  ydb/core/cms/console/immediate_controls_configurator_ut.cpp
  ydb/core/cms/console/jaeger_tracing_configurator_ut.cpp
  ydb/core/cms/console/log_settings_configurator_ut.cpp
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/node_broker_ut.cpp
  ydb/core/quoter/kesus_quoter_ut.cpp
  ydb/core/tablet/tablet_pipe_ut.cpp
  ydb/core/tablet/tablet_resolver.cpp
  ydb/core/tablet/tablet_sys.cpp
  ydb/core/tablet/ya.make
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/basics/services.cpp
  ydb/library/actors/testlib/test_runtime.cpp
  ydb/library/actors/testlib/test_runtime.h
Labels: not-for-changelog

#22135 Fix multple external channels are not being reused
  ydb/core/tx/datashard/datashard_ut_ext_blobs_multiple_channels.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
Labels: improvement

#22215 Fix MSVC not compiling due to no_unique_address warning
  ydb/library/actors/async/task_group.h
Labels: not-for-changelog

#22224 move dump applied rule to cpp file
  ydb/core/kqp/opt/kqp_opt.cpp
  ydb/core/kqp/opt/kqp_opt_impl.h
Labels: not-for-changelog

#22220 appearance snapshot
  ydb/core/tx/columnshard/columnshard_schema.h
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/merge_subset.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.cpp
  ydb/core/tx/columnshard/engines/changes/with_appended.h
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/portions/compacted.cpp
  ydb/core/tx/columnshard/engines/portions/compacted.h
  ydb/core/tx/columnshard/engines/portions/constructor_portion.cpp
  ydb/core/tx/columnshard/engines/portions/constructor_portion.h
  ydb/core/tx/columnshard/engines/portions/write_with_blobs.h
  ydb/core/tx/columnshard/engines/protos/portion_info.proto
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/portion/restore_appearance_snapshot.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_appearance_snapshot.h
  ydb/core/tx/columnshard/normalizer/portion/ya.make
Labels: improvement

#22048 Docs: KNN serialization format
  ydb/docs/en/core/yql/reference/udf/list/knn.md
  ydb/docs/ru/core/yql/reference/udf/list/knn.md
Labels: documentation

#22140 Docs: rename prefixed to filtered vector index
  ydb/docs/en/core/dev/vector-indexes.md
  ydb/docs/en/core/yql/reference/syntax/create_table/vector_index.md
  ydb/docs/en/core/yql/reference/syntax/select/vector_index.md
  ydb/docs/ru/core/dev/vector-indexes.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/vector_index.md
  ydb/docs/ru/core/yql/reference/syntax/select/vector_index.md
Labels: documentation

#22137 Fix config reading sequence
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_persistent_storage.cpp
Labels: not-for-changelog

#21627 [OLAP Predicate pushdown] Add block date arithmetics
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/kqp_statistics_transformer.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_olap_filter.cpp
  ydb/core/kqp/opt/physical/predicate_collector.cpp
  ydb/core/kqp/query_compiler/kqp_olap_compiler.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#22219 Remove protovalidate library dependency from Nebius Api as it's annotation are not used in YDB server code
  ydb/public/api/client/nc_private/buf/validate/expression.proto
  ydb/public/api/client/nc_private/buf/validate/priv/private.proto
  ydb/public/api/client/nc_private/buf/validate/validate.proto
  ydb/public/api/client/nc_private/buf/validate/ya.make
  ydb/public/api/client/nc_private/buf/ya.make
  ydb/public/api/client/nc_private/common/v1/metadata.proto
  ydb/public/api/client/nc_private/common/v1/operation.proto
  ydb/public/api/client/nc_private/common/v1/ya.make
  ydb/public/api/client/nc_private/iam/v1/profile_service.proto
  ydb/public/api/client/nc_private/iam/v1/service_account.proto
  ydb/public/api/client/nc_private/iam/v1/tenant_user_account.proto
  ydb/public/api/client/nc_private/iam/v1/user_account.proto
  ydb/public/api/client/nc_private/iam/v1/ya.make
  ydb/public/api/client/nc_private/ya.make
Labels: not-for-changelog

#21952 basic bridge support in cluster and nodes handlers
  ydb/core/viewer/json_handlers_storage.cpp
  ydb/core/viewer/json_handlers_viewer.cpp
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/storage_groups.h
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/viewer_capabilities.h
  ydb/core/viewer/viewer_cluster.h
  ydb/core/viewer/viewer_nodes.h
Labels: improvement

#22249 fix distributed cache destruction
  ydb/core/tx/general_cache/service/manager.h
Labels: bugfix

#21893 Extend SysView with GroupSizeInUnits and inferred PDisk settings
  ydb/core/mind/bscontroller/config_fit_groups.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/storage_stats_calculator.cpp
  ydb/core/mind/bscontroller/sys_view.cpp
  ydb/core/protos/sys_view.proto
  ydb/core/sys_view/common/schema.h
  ydb/core/sys_view/storage/groups.cpp
  ydb/core/sys_view/storage/pdisks.cpp
  ydb/core/sys_view/storage/storage_pools.cpp
  ydb/core/sys_view/ut_kqp.cpp
Labels: not-for-changelog

#22295 Fix state storage self heal tests
  ydb/tests/functional/config/test_distconf_self_heal.py
Labels: not-for-changelog

#21997 Use new HDRF compute scheduler
  ydb/core/kqp/common/ya.make
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.h
  ydb/core/kqp/compute_actor/kqp_compute_actor_impl.h
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_pure_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
  ydb/core/kqp/proxy_service/kqp_proxy_service_impl.h
  ydb/core/kqp/runtime/scheduler/fwd.h
  ydb/core/kqp/runtime/scheduler/kqp_compute_actor.h
  ydb/core/kqp/runtime/scheduler/kqp_compute_scheduler_service.cpp
  ydb/core/kqp/runtime/scheduler/kqp_compute_scheduler_service.h
  ydb/core/kqp/runtime/scheduler/kqp_schedulable_actor.cpp
  ydb/core/kqp/runtime/scheduler/kqp_schedulable_actor.h
  ydb/core/kqp/runtime/scheduler/new/kqp_schedulable_actor.h
  ydb/core/kqp/runtime/scheduler/old/kqp_compute_scheduler.cpp
  ydb/core/kqp/runtime/scheduler/old/kqp_compute_scheduler.h
  ydb/core/kqp/runtime/scheduler/old/kqp_compute_scheduler_ut.cpp
  ydb/core/kqp/runtime/scheduler/tree/common.h
  ydb/core/kqp/runtime/scheduler/tree/dynamic.cpp
  ydb/core/kqp/runtime/scheduler/tree/dynamic.h
  ydb/core/kqp/runtime/scheduler/tree/snapshot.cpp
  ydb/core/kqp/runtime/scheduler/tree/snapshot.h
  ydb/core/kqp/runtime/ut/ya.make
  ydb/core/kqp/runtime/ya.make
  ydb/core/protos/kqp.proto
  ydb/core/protos/table_service_config.proto
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
Labels: new-feature

#22264 Refactor bridge api according to negotiation
  ydb/core/grpc_services/rpc_bridge.cpp
  ydb/public/api/protos/draft/ydb_bridge.proto
  ydb/public/lib/ydb_cli/commands/ydb_bridge.cpp
  ydb/public/lib/ydb_cli/commands/ydb_bridge.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/draft/ydb_bridge.h
  ydb/public/sdk/cpp/src/client/draft/ydb_bridge.cpp
  ydb/tests/functional/bridge/test_bridge.py
  ydb/tests/functional/bridge/ya.make
  ydb/tests/library/clients/kikimr_bridge_client.py
  ydb/tests/library/harness/kikimr_config.py
Labels: not-for-changelog

#22234 Use version info from git in config dump
  .github/actions/test_ya/action.yml
  .github/workflows/nightly_build.yml
  ydb/tests/library/compatibility/configs/dump/dumper/main.cpp
  ydb/tests/library/compatibility/configs/dump/dumper/ya.make
  ydb/tests/library/compatibility/configs/dump/ya.make
  ydb/tests/library/compatibility/configs/ya.make
Labels: not-for-changelog

#22299 Add parallel tpch
  ydb/tests/functional/tpc/medium/tpch/test_parallel.py
  ydb/tests/functional/tpc/medium/tpch/ya.make
  ydb/tests/olap/load/lib/clickbench.py
  ydb/tests/olap/load/lib/conftest.py
  ydb/tests/olap/load/lib/tpch.py
Labels: not-for-changelog

#22226 meta forward authorize header
  ydb/mvp/core/core_ydb_impl.h
  ydb/mvp/meta/meta_cp_databases.h
  ydb/mvp/meta/mvp.cpp
  ydb/mvp/meta/mvp.h
Labels: improvement

#22310 Fix reassign node logic in self-heal
  ydb/core/blobstorage/nodewarden/distconf_invoke_state_storage.cpp
  ydb/core/blobstorage/nodewarden/distconf_selfheal.cpp
  ydb/core/blobstorage/nodewarden/distconf_selfheal.h
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.cpp
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.h
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/tests/functional/config/test_distconf_sentinel_node_status.py
Labels: not-for-changelog

#22273 Stream index: write tasks
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_buffer_lookup_actor.h
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.h
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/tx/datashard/datashard_ut_trace.cpp
Labels: not-for-changelog

#22327 [Kafka API transactions] Fix several bugs
  ydb/core/kafka_proxy/actors/kafka_produce_actor.cpp
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_producer_instance_id.h
  ydb/core/kafka_proxy/kafka_transactions_coordinator.cpp
  ydb/core/kafka_proxy/ut/ut_produce_actor.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/ut/pqtablet_ut.cpp
  ydb/core/persqueue/write_id.cpp
  ydb/core/persqueue/write_id.h
Labels: not-for-changelog

#22331 fq: cp: v2/v1 stats conversion: fix copying json in the inner loop
  ydb/core/fq/libs/compute/common/utils.cpp
Labels: not-for-changelog

#21875 Report fair VDisk AvailableSize
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_chunk_tracker.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_keeper.h
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/protos/blobstorage.proto
Labels: not-for-changelog

#22350 Add missing wh argument (#17333)
  ydb/docs/en/core/reference/ydb-cli/workload-tpcc.md
  ydb/docs/ru/core/reference/ydb-cli/_assets/tpcc-import.gif
  ydb/docs/ru/core/reference/ydb-cli/_assets/tpcc-run.gif
  ydb/docs/ru/core/reference/ydb-cli/workload-tpcc.md
Labels: documentation

#22348 Fix self heal tests
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.cpp
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.h
  ydb/tests/functional/config/test_distconf_sentinel_node_status.py
Labels: not-for-changelog

#22306 Account GroupSizeInUnits in JSON Viewer
  ydb/core/viewer/storage_groups.h
Labels: not-for-changelog

#22362 Add waiting for stats ready in upload tests
  ydb/tests/olap/load/lib/upload.py
Labels: not-for-changelog

#22242 Make BridgePileId natural number
  ydb/core/base/blobstorage.cpp
  ydb/core/base/blobstorage_common.h
  ydb/core/base/bridge.h
  ydb/core/blobstorage/bridge/syncer/syncer.cpp
  ydb/core/blobstorage/dsproxy/bridge/bridge.cpp
  ydb/core/blobstorage/groupinfo/blobstorage_groupinfo.cpp
  ydb/core/blobstorage/groupinfo/blobstorage_groupinfo.h
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
  ydb/core/blobstorage/nodewarden/distconf_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_connectivity.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_static_group.cpp
  ydb/core/blobstorage/nodewarden/distconf_quorum.cpp
  ydb/core/blobstorage/nodewarden/distconf_quorum.h
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.cpp
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.h
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/grpc_services/rpc_bridge.cpp
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/config_fit_groups.cpp
  ydb/core/mind/bscontroller/group_geometry_info.h
  ydb/core/mind/bscontroller/group_mapper.cpp
  ydb/core/mind/bscontroller/group_mapper.h
  ydb/core/mind/bscontroller/group_mapper_ut.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/mind/bscontroller/sys_view.cpp
  ydb/core/mind/bscontroller/virtual_group.cpp
  ydb/core/mind/dynamic_nameserver.cpp
  ydb/core/mind/hive/bridge_pile_info.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/node_info.h
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__register_node.cpp
  ydb/core/mind/hive/tx__update_pile.cpp
  ydb/core/mind/local.cpp
  ydb/core/node_whiteboard/node_whiteboard.h
  ydb/core/tablet_flat/flat_cxx_database.h
  ydb/core/viewer/storage_groups.h
  ydb/core/viewer/viewer_cluster.h
Labels: not-for-changelog

#22373 add_vcs_info in compare_configs.yml
  .github/workflows/compare_configs.yml
Labels: not-for-changelog

#22374 YQ-4144 disabled nodes check in import/export test
  ydb/tests/olap/s3_import/large/test_large_import.py
Labels: not-for-changelog

#22061 side by side oltp sink comparision in replay
  ydb/tools/query_replay_yt/main.cpp
  ydb/tools/query_replay_yt/query_compiler.cpp
  ydb/tools/query_replay_yt/query_replay.cpp
  ydb/tools/query_replay_yt/query_replay.h
Labels: not-for-changelog

#22298 QueryService: graceful shutdown session using attach stream
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
Labels: bugfix

#22287 Replace pages pinning with TSharedPageRef
  ydb/core/tablet_flat/flat_exec_seat.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
  ydb/core/tablet_flat/shared_cache_events.h
  ydb/core/tablet_flat/shared_page.h
  ydb/core/tablet_flat/ut/ut_shared_sausagecache.cpp
Labels: not-for-changelog

#22029 Use set instead of tuple for acceptable errros in test
  ydb/tests/olap/scenario/helpers/scenario_tests_helper.py
  ydb/tests/olap/scenario/test_insert.py
Labels: not-for-changelog

#22347 Do not progress vector index builds when EnableVectorIndex is disabled
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__monitoring.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
Labels: not-for-changelog

#22353 optimize portion border usage in deduplication
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/merge.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/merge.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/splitter.h
Labels: not-for-changelog

#22398 Fix s3 sync for config dumps
  .github/workflows/nightly_build.yml
  ydb/tests/library/compatibility/configs/dump/ya.make
  ydb/tests/library/compatibility/configs/ya.make
Labels: not-for-changelog

#22401 In compare config add local report storage and fix global one
  .github/workflows/compare_configs.yml
Labels: not-for-changelog

#21705 Split PDisk's huge write priorities into two
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_config.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_gate.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_mon.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_mon.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_req_creator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/protos/blobstorage_pdisk_config.proto
Labels: performance

#22436 Calculate quasi gross time for suites
  .github/scripts/analytics/data_mart_queries/perfomance_olap_suites_mart.sql
Labels: not-for-changelog

#22458 Use temporary var for pr description in validate_pr_description
  .github/actions/validate_pr_description/action.yaml
  .github/actions/validate_pr_description/validate_pr_description.py
Labels: not-for-changelog

#22260 Add pruneKeys for kqp
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
Labels: not-for-changelog, external

#21848 Add incremental backup to operation API
  ydb/core/grpc_services/rpc_backup_base.h
  ydb/core/grpc_services/rpc_cancel_operation.cpp
  ydb/core/grpc_services/rpc_forget_operation.cpp
  ydb/core/grpc_services/rpc_get_operation.cpp
  ydb/core/grpc_services/rpc_list_operations.cpp
  ydb/core/grpc_services/rpc_operation_conv_base.h
  ydb/core/persqueue/offload_actor.cpp
  ydb/core/protos/backup.proto
  ydb/core/protos/counters_schemeshard.proto
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/protos/pqconfig.proto
  ydb/core/protos/schemeshard/operations.proto
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__op_traits.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_continuous_backup.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_backup_incremental_backup_collection.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_db_changes.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_db_changes.h
  ydb/core/tx/schemeshard/schemeshard__operation_memory_changes.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_memory_changes.h
  ydb/core/tx/schemeshard/schemeshard__operation_part.h
  ydb/core/tx/schemeshard/schemeshard_audit_log_fragment.cpp
  ydb/core/tx/schemeshard/schemeshard_backup.cpp
  ydb/core/tx/schemeshard/schemeshard_backup.h
  ydb/core/tx/schemeshard/schemeshard_backup_incremental__forget.cpp
  ydb/core/tx/schemeshard/schemeshard_backup_incremental__get.cpp
  ydb/core/tx/schemeshard/schemeshard_backup_incremental__list.cpp
  ydb/core/tx/schemeshard/schemeshard_backup_incremental__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_continuous_backup_cleaner.cpp
  ydb/core/tx/schemeshard/schemeshard_continuous_backup_cleaner.h
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.h
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_private.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/schemeshard_tx_infly.h
  ydb/core/tx/schemeshard/ut_backup_collection/ut_backup_collection.cpp
  ydb/core/tx/schemeshard/ut_continuous_backup/ut_continuous_backup.cpp
  ydb/core/tx/schemeshard/ut_continuous_backup_reboots/ut_continuous_backup_reboots.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_helpers/helpers.h
  ydb/core/tx/schemeshard/ya.make
  ydb/core/tx/tx_proxy/schemereq.cpp
  ydb/public/api/protos/draft/ydb_backup.proto
  ydb/public/api/protos/out/out.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_operation.cpp
  ydb/public/lib/ydb_cli/common/print_operation.cpp
  ydb/public/lib/ydb_cli/common/print_operation.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/draft/ydb_backup.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/library/operation_id/operation_id.h
  ydb/public/sdk/cpp/src/client/draft/ya.make
  ydb/public/sdk/cpp/src/client/draft/ydb_backup.cpp
  ydb/public/sdk/cpp/src/client/operation/operation.cpp
  ydb/public/sdk/cpp/src/client/operation/ya.make
  ydb/public/sdk/cpp/src/library/operation_id/operation_id.cpp
  ydb/public/sdk/cpp/src/library/operation_id/protos/operation_id.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#21468 [docs/stable-25-1] backport contributor/documentation/ folder
  ydb/docs/en/core/contributor/documentation/_assets/automerge-and-dismiss.png
  ydb/docs/en/core/contributor/documentation/_assets/excluding-primary-reviewer.jpeg
  ydb/docs/en/core/contributor/documentation/_assets/lgtm.png
  ydb/docs/en/core/contributor/documentation/genres.md
  ydb/docs/en/core/contributor/documentation/index.md
  ydb/docs/en/core/contributor/documentation/review.md
  ydb/docs/en/core/contributor/documentation/structure.md
  ydb/docs/en/core/contributor/documentation/style-guide.md
  ydb/docs/en/core/contributor/documentation/toc_p.yaml
  ydb/docs/en/core/contributor/toc_i.yaml
  ydb/docs/en/core/reference/index.md
  ydb/docs/en/core/toc_i.yaml
  ydb/docs/ru/core/contributor/documentation/_assets/automerge-and-dismiss.png
  ydb/docs/ru/core/contributor/documentation/_assets/excluding-primary-reviewer.jpeg
  ydb/docs/ru/core/contributor/documentation/_assets/lgtm.png
  ydb/docs/ru/core/contributor/documentation/genres.md
  ydb/docs/ru/core/contributor/documentation/index.md
  ydb/docs/ru/core/contributor/documentation/review.md
  ydb/docs/ru/core/contributor/documentation/structure.md
  ydb/docs/ru/core/contributor/documentation/style-guide.md
  ydb/docs/ru/core/contributor/documentation/toc_p.yaml
  ydb/docs/ru/core/contributor/toc_i.yaml
  ydb/docs/ru/core/reference/index.md
  ydb/docs/ru/core/toc_i.yaml
Labels: documentation

#22289 Remove domains_config mentions from initial-deployment.md
  ydb/docs/en/core/devops/deployment-options/manual/initial-deployment.md
  ydb/docs/ru/core/devops/deployment-options/manual/initial-deployment.md
Labels: documentation

#22449 Fix bug in DispatchEvent
  ydb/library/actors/testlib/test_runtime.cpp
Labels: not-for-changelog

#22498 [Perf TPCDS] Decorrelate tpcds query 6 with inner join
  ydb/library/benchmarks/queries/tpcds/yql/q6.sql
Labels: not-for-changelog

#22492 Update vector search python sdk example
  ydb/public/sdk/python/examples/vector_search/vector_search.py
Labels: not-for-changelog

#22363 [OLAP predicate pushdown] Add kqp phy opt for tx transformer
  ydb/core/kqp/opt/kqp_opt_build_txs.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy.h
  ydb/core/kqp/opt/physical/kqp_opt_phy_olap_filter.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#21863 Replace intermediate WideCombine with DqHashCombine (enabled with the UseDqHashCombine pragma)
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/opt/peephole/kqp_opt_peephole.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/query_compiler/kqp_mkql_compiler.cpp
  ydb/core/kqp/ut/opt/kqp_hash_combine_ut.cpp
  ydb/core/kqp/ut/opt/ya.make
  ydb/library/yql/dq/expr_nodes/dq_expr_nodes.json
  ydb/library/yql/dq/opt/dq_opt_peephole.cpp
  ydb/library/yql/dq/opt/dq_opt_peephole.h
  ydb/library/yql/dq/type_ann/dq_type_ann.cpp
  ydb/library/yql/dq/type_ann/dq_type_ann.h
Labels: not-for-changelog

#22393 Add new bridge commands according to negotiation
  ydb/core/grpc_services/rpc_bridge.cpp
  ydb/public/lib/ydb_cli/commands/ydb_bridge.cpp
  ydb/public/lib/ydb_cli/commands/ydb_bridge.h
Labels: not-for-changelog

#22496 Add ci and test tools vesion to report and qa db
  ydb/tests/olap/lib/allure_utils.py
  ydb/tests/olap/lib/results_processor.py
  ydb/tests/olap/lib/utils.py
  ydb/tests/olap/lib/ya.make
Labels: not-for-changelog

#18484 YDB CLI: Add support for encrypted export. Shorten options descriptions
  ydb/public/lib/ydb_cli/commands/ydb_service_export.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_export.h
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.h
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/lib/ydb_cli/commands/ydb_tools.cpp
  ydb/public/lib/ydb_cli/common/client_command_options.cpp
  ydb/public/lib/ydb_cli/common/client_command_options.h
  ydb/public/lib/ydb_cli/common/format.cpp
  ydb/public/lib/ydb_cli/common/parseable_struct.h
Labels: not-for-changelog

#22545 portion write controller fix
  ydb/core/tx/columnshard/operations/slice_builder/builder.cpp
Labels: not-for-changelog

#22533 remove self include
  ydb/core/mon/mon.h
Labels: not-for-changelog

#22497 deduplication fixes
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/splitter.h
Labels: not-for-changelog

#22535 deduplication abortion handling
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.h
Labels: not-for-changelog

#22470 Add more try-catch blocks to avoid unhandled exception (#17333)
  ydb/library/workload/tpcc/import.cpp
  ydb/library/workload/tpcc/import_tui.cpp
  ydb/library/workload/tpcc/import_tui.h
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/runner_tui.cpp
  ydb/library/workload/tpcc/runner_tui.h
  ydb/library/workload/tpcc/terminal.cpp
Labels: not-for-changelog

#22532 deduplication memory fixes
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/driver_lib/run/kikimr_services_initializers.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/console_config.proto
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/tests/library/harness/kikimr_config.py
Labels: not-for-changelog

#22556 healthcheck: fix handling of response from a disconnected node
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: bugfix

#22475 EnableTempTables flag
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/host/kqp_statement_rewrite.cpp
  ydb/core/kqp/provider/yql_kikimr_datasink.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/pg/kqp_pg_ut.cpp
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_acl_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/table_service_config.proto
  ydb/core/sys_view/ut_common.cpp
Labels: not-for-changelog

#22539 Topic SDK: fix in direct reader
  ydb/public/sdk/cpp/src/client/topic/impl/direct_reader.cpp
  ydb/public/sdk/cpp/tests/integration/topic/direct_read.cpp
Labels: not-for-changelog

#22468 enable simple reader in cs
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/olap/delete_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/olap/locks_ut.cpp
  ydb/core/kqp/ut/olap/optimizer_ut.cpp
  ydb/core/kqp/ut/olap/sparsed_ut.cpp
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/kqp/ut/tx/kqp_sink_common.h
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_move_table.cpp
  ydb/tests/olap/oom/overlapping_portions.py
Labels: not-for-changelog

#22555 reduce memory usage by splitter in deduplication
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.h
Labels: not-for-changelog

#22411 [YQ-4427] Watermarks: RD: pushdown watermark expr to RD
  ydb/library/yql/providers/clickhouse/provider/yql_clickhouse_dq_integration.cpp
  ydb/library/yql/providers/common/pushdown/collection.cpp
  ydb/library/yql/providers/common/pushdown/collection.h
  ydb/library/yql/providers/common/pushdown/settings.h
  ydb/library/yql/providers/generic/connector/api/service/protos/connector.proto
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.h
  ydb/library/yql/providers/generic/pushdown/yql_generic_match_predicate.cpp
  ydb/library/yql/providers/pq/expr_nodes/yql_pq_expr_nodes.json
  ydb/library/yql/providers/pq/proto/dq_io.proto
  ydb/library/yql/providers/pq/provider/yql_pq_datasource.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_datasource_type_ann.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_dq_integration.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_logical_opt.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_topic_key_parser.cpp
  ydb/library/yql/providers/pq/provider/yql_pq_topic_key_parser.h
  ydb/library/yql/providers/s3/provider/yql_s3_dq_integration.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
  ydb/library/yql/providers/ydb/provider/yql_ydb_dq_integration.cpp
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHop-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopByStringKey-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopExprKey-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopListKey-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopNoKey-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopPercentile-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopTimeExtractorUnusedColumns-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHopWithDataWatermarks-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-GroupByHoppingWithDataWatermarks-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopic-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopicGroupWriteToSolomon-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopicWithMetadata-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopicWithMetadataInsideFilter-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopicWithMetadataNestedDeep-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopicWithMetadataWithFilter-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTopicWithSchema-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadTwoTopics-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadWriteSameTopic-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadWriteTopic-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-ReadWriteTopicWithSchema-default.txt_/ast.txt
  ydb/tests/fq/streaming_optimize/canondata/test_sql_streaming.test_suites-WriteTwoTopics-default.txt_/ast.txt
Labels: not-for-changelog

#22606 Speed up Scheme Board unit tests
  ydb/core/tx/scheme_board/populator_ut.cpp
  ydb/core/tx/scheme_board/subscriber_ut.cpp
  ydb/core/tx/scheme_board/ut_helpers.h
Labels: not-for-changelog

#22485 Handle DependsOn with tuple arg in optimizers - YDB part
  ydb/core/kqp/opt/logical/kqp_opt_log_helpers.cpp
  ydb/library/yql/dq/opt/dq_opt_log.cpp
  ydb/library/yql/dq/opt/dq_opt_phy.cpp
Labels: not-for-changelog, external

#22626 Fix codeowners for CHANGELOG.md
  .github/CODEOWNERS
Labels: not-for-changelog

#22628 Mute flaky CS test_log
  .github/config/muted_ya.txt
Labels: not-for-changelog

#22625 use query service in ydb/tests/olap/scenario/test_alter_tiering
  .github/config/muted_ya.txt
  ydb/tests/olap/scenario/test_alter_tiering.py
Labels: not-for-changelog

#22624 trailing spaces have been removed
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: not-for-changelog

#22640 mute chunks for ydb/tests/olap
  .github/config/muted_ya.txt
Labels: not-for-changelog

#22620 perf improvement for ttl validation
  ydb/core/tx/schemeshard/olap/ttl/validator.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: performance

#22664 Kafka protocol: fix test
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
Labels: not-for-changelog

#22659 add invert pk over sort unit test
  ydb/core/kqp/ut/opt/kqp_sort_ut.cpp
Labels: not-for-changelog

#22657 add feature flag for empty programs optimization
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_source.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#22618 use masked token
  ydb/core/fq/libs/cloud_audit/ya.make
  ydb/core/fq/libs/cloud_audit/yq_cloud_audit_service.cpp
Labels: not-for-changelog

#21593 Add manual request approval to CMS
  ydb/core/cms/cluster_info.h
  ydb/core/cms/cms.cpp
  ydb/core/cms/cms_impl.h
  ydb/core/cms/cms_ut.cpp
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/cms/cms_ut_common.h
  ydb/core/driver_lib/cli_utils/cli_cmds_cms.cpp
  ydb/core/protos/cms.proto
Labels: experimental-feature

#22616 Add possibility to skip tests
  ydb/tests/olap/scenario/helpers/__init__.py
  ydb/tests/olap/scenario/helpers/skip_test.py
  ydb/tests/olap/scenario/helpers/ya.make
  ydb/tests/olap/scenario/test_alter_tiering.py
Labels: not-for-changelog

#22538 change VDisk compaction params when working on a tiny PDisk
  ydb/core/blobstorage/pdisk/blobstorage_pdisk.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_data.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_params.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_params.h
  ydb/core/blobstorage/pdisk/mock/pdisk_mock.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_hulldefs.cpp
  ydb/core/blobstorage/vdisk/hulldb/base/blobstorage_hulldefs.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_ut.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullactor.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcommit.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_public.cpp
  ydb/core/blobstorage/vdisk/repl/blobstorage_hullreplwritesst_ut.cpp
  ydb/core/protos/blobstorage_vdisk_internal.proto
Labels: not-for-changelog

#22473 Resume throttled tasks when the pool has under-utilized fair-share
  ydb/core/kqp/compute_actor/kqp_compute_actor_factory.cpp
  ydb/core/kqp/runtime/scheduler/fwd.h
  ydb/core/kqp/runtime/scheduler/kqp_compute_actor.h
  ydb/core/kqp/runtime/scheduler/kqp_compute_scheduler_service.cpp
  ydb/core/kqp/runtime/scheduler/kqp_schedulable_actor.cpp
  ydb/core/kqp/runtime/scheduler/kqp_schedulable_actor.h
  ydb/core/kqp/runtime/scheduler/kqp_schedulable_task.cpp
  ydb/core/kqp/runtime/scheduler/kqp_schedulable_task.h
  ydb/core/kqp/runtime/scheduler/tree/common.h
  ydb/core/kqp/runtime/scheduler/tree/dynamic.cpp
  ydb/core/kqp/runtime/scheduler/tree/dynamic.h
  ydb/core/kqp/runtime/scheduler/tree/snapshot.cpp
  ydb/core/kqp/runtime/scheduler/tree/snapshot.h
  ydb/core/kqp/runtime/ya.make
Labels: performance

#22638 fix ssl error processing for gracefull close
  ydb/library/actors/http/http_proxy_sock_impl.h
Labels: not-for-changelog

#22690 Unmute fixed tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#22714 Verbose error string
  ydb/core/kqp/ut/common/columnshard.cpp
  ydb/core/kqp/ut/common/columnshard.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/testlib/cs_helper.cpp
  ydb/core/testlib/cs_helper.h
  ydb/core/tx/data_events/shard_writer.cpp
Labels: not-for-changelog

#22311 Invoke TRope::Compact in OnVGetResult only when occupied memory exceeds threshold
  ydb/core/blobstorage/dsproxy/dsproxy_get_impl.h
Labels: performance

#22679 Unify Private Cache counters behaviour
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
Labels: not-for-changelog

#20611 [docs] translate #19307 to Russian
  ydb/docs/en/core/devops/deployment-options/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/deployment-options/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/deployment-options/ansible/toc_p.yaml
  ydb/docs/ru/core/devops/deployment-options/ansible/update-executable.md
Labels: documentation

#22729 Analytics: postcommit test retry
  .github/scripts/analytics/data_mart_queries/datamart_postcommit_retry.sql
  .github/workflows/collect_analytics_fast.yml
Labels: not-for-changelog

#22709 modify LSM level counters
  ydb/core/blobstorage/vdisk/common/vdisk_mongroups.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_idx.h
Labels: not-for-changelog

#22738 fix native decimals in tpch
  ydb/library/workload/tpc_base/tpc_base.cpp
  ydb/public/lib/ydb_cli/commands/benchmark_utils.cpp
  ydb/tests/functional/tpc/medium/tpch/test_decimal.py
Labels: not-for-changelog

#22705 subscribe to tier config once on shard init
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/tx/columnshard/columnshard.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/loading/stages.cpp
  ydb/core/tx/tiering/manager.cpp
  ydb/core/tx/tiering/manager.h
  ydb/core/tx/tiering/ut/ut_tiers.cpp
Labels: bugfix

#21931 [docs] fixes for YQL reference around secondary and vector indices
  ydb/docs/en/core/yql/reference/syntax/_includes/index_grammar_explanation.md
  ydb/docs/en/core/yql/reference/syntax/_includes/vector_index_parameters.md
  ydb/docs/en/core/yql/reference/syntax/alter_table/indexes.md
  ydb/docs/en/core/yql/reference/syntax/create_table/index.md
  ydb/docs/en/core/yql/reference/syntax/create_table/secondary_index.md
  ydb/docs/en/core/yql/reference/syntax/create_table/vector_index.md
  ydb/docs/ru/core/yql/reference/syntax/_includes/index_grammar_explanation.md
  ydb/docs/ru/core/yql/reference/syntax/_includes/vector_index_parameters.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/indexes.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/index.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/secondary_index.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/vector_index.md
Labels: documentation

#22730 improve ssl errors handling
  ydb/library/actors/http/http_proxy_sock_impl.h
Labels: not-for-changelog

#22752 Fix use-after-free in CMS remove permission
  ydb/core/cms/cms_tx_remove_permissions.cpp
Labels: bugfix

#22766 Fix Bridge syncer merging algorithm
  ydb/core/blobstorage/bridge/proxy/bridge_proxy.cpp
  ydb/core/blobstorage/bridge/syncer/syncer.cpp
  ydb/core/blobstorage/bridge/syncer/syncer_impl.h
Labels: not-for-changelog

#22713 Add Bridge CLI documentation
  ydb/docs/ru/core/concepts/bridge.md
  ydb/docs/ru/core/reference/ydb-cli/commands/_includes/danger-warning.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/failover.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/index.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/list.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/rejoin.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/switchover.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/takedown.md
  ydb/docs/ru/core/reference/ydb-cli/commands/bridge/toc_p.yaml
  ydb/docs/ru/core/reference/ydb-cli/commands/configuration/cluster/index.md
  ydb/docs/ru/core/reference/ydb-cli/commands/configuration/cluster/replace.md
  ydb/docs/ru/core/reference/ydb-cli/commands/configuration/node/index.md
  ydb/docs/ru/core/reference/ydb-cli/toc_i.yaml
Labels: documentation

#22742 Rename TPrivatePageCache::TInfo to TPageCollection
  ydb/core/tablet_flat/flat_boot_back.h
  ydb/core/tablet_flat/flat_boot_bundle.h
  ydb/core/tablet_flat/flat_dbase_sz_env.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_executor_bootlogic.cpp
  ydb/core/tablet_flat/flat_executor_bootlogic.h
  ydb/core/tablet_flat/flat_executor_tx_env.h
  ydb/core/tablet_flat/flat_ops_compact.h
  ydb/core/tablet_flat/flat_part_loader.cpp
  ydb/core/tablet_flat/flat_part_loader.h
  ydb/core/tablet_flat/flat_part_outset.cpp
  ydb/core/tablet_flat/flat_part_outset.h
  ydb/core/tablet_flat/flat_part_store.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
  ydb/core/tablet_flat/flat_scan_actor.h
  ydb/core/tablet_flat/flat_store_hotdog.cpp
  ydb/core/tablet_flat/flat_store_hotdog.h
  ydb/core/tablet_flat/flat_writer_blocks.h
  ydb/core/tablet_flat/ut/ut_slice_loader.cpp
Labels: not-for-changelog

#22724 [docs] minor improvements for system-views.md
  ydb/docs/en/core/devops/observability/system-views.md
  ydb/docs/ru/core/devops/observability/system-views.md
Labels: documentation

#22772 Increase CS memlimit for spilling tests
  ydb/tests/functional/tpc/large/test_tpch_spilling.py
Labels: not-for-changelog

#22743 YQ Fix InFlySubscribe metric
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#22809 Update behaviour with the `--newline-delimited` option: fix possible stuck and use arenas
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/import/import.cpp
Labels: area/cli, not-for-changelog

#22827 Cleanup interrupted TPC-C warmup case (#17333)
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/terminal.cpp
Labels: not-for-changelog

#22838 [C++ SDK] Fixed vector example performance
  ydb/public/sdk/cpp/examples/vector_index_builtin/vector_index.cpp
Labels: not-for-changelog

#22839 fix ignored message in test_alter_tiering
  ydb/tests/olap/scenario/test_alter_tiering.py
Labels: not-for-changelog

#22849 Fix win build
  ydb/public/lib/ydb_cli/commands/benchmark_utils.cpp
Labels: not-for-changelog

#22280 solomon: working inflight restriction, retry policy tweaks & quality of life changes
  ydb/library/yql/providers/solomon/actors/dq_solomon_read_actor.cpp
  ydb/library/yql/providers/solomon/common/util.cpp
  ydb/library/yql/providers/solomon/common/util.h
  ydb/library/yql/providers/solomon/common/util_ut.cpp
  ydb/library/yql/providers/solomon/expr_nodes/yql_solomon_expr_nodes.json
  ydb/library/yql/providers/solomon/proto/dq_solomon_shard.proto
  ydb/library/yql/providers/solomon/provider/yql_solomon_datasource_type_ann.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_io_discovery.cpp
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_accessor_client.cpp
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-Basic-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-BasicExtractMembers-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-Downsampling-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-DownsamplingValidSettings-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-HistResponse-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-LabelColumns-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-Subquery-default.txt_/opt.yql
Labels: not-for-changelog

#20593 YDBOPS-12179 Correct paths and names for Kubernetes deployment
  ydb/docs/en/core/devops/deployment-options/kubernetes/initial-deployment.md
  ydb/docs/ru/core/devops/deployment-options/kubernetes/initial-deployment.md
Labels: documentation

#22852 priority for inactive portions
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
Labels: not-for-changelog

#21699 hive handler to set tablet's domain
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/monitoring.cpp
  ydb/core/protos/counters_hive.proto
Labels: not-for-changelog

#22850 UnMute test_disposition.py.TestContinueMode.test_disposition_from_time[v1-mvp_external_ydb_endpoint0]
  .github/config/muted_ya.txt
  ydb/tests/fq/yds/test_disposition.py
Labels: not-for-changelog

#22837 Remove finished queries from compute scheduler
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/node_service/kqp_node_service.h
  ydb/core/kqp/node_service/kqp_node_state.h
  ydb/core/kqp/runtime/scheduler/kqp_compute_scheduler_service.cpp
  ydb/core/kqp/runtime/scheduler/kqp_compute_scheduler_service.h
  ydb/core/kqp/runtime/scheduler/tree/dynamic.cpp
  ydb/core/kqp/runtime/scheduler/tree/dynamic.h
  ydb/core/kqp/runtime/scheduler/tree/snapshot.cpp
  ydb/core/kqp/runtime/scheduler/tree/snapshot.h
Labels: improvement

#22881 YQ-4521 fixed memory monitoring in kqprun and added threads flag
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: bugfix

#22812 Fix get implementation and route gets through bridge proxy when in Bridge mode
  ydb/core/blobstorage/bridge/proxy/bridge_proxy.cpp
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_binding.cpp
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_storage_config.cpp
  ydb/core/blobstorage/nodewarden/distconf_scatter_gather.cpp
  ydb/core/blobstorage/pdisk/mock/pdisk_mock.cpp
  ydb/core/blobstorage/ut_blobstorage/bridge_get.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/env.h
  ydb/core/blobstorage/ut_blobstorage/ut_bridge/ya.make
  ydb/core/blobstorage/ut_blobstorage/ya.make
  ydb/core/util/actorsys_test/testactorsys.h
Labels: not-for-changelog

#21459 dq/runtime/output_channel: relax requirement on double watermark
  ydb/library/yql/dq/runtime/dq_output_channel.cpp
Labels: not-for-changelog

#22890 Reduce hashmap allocations
  ydb/library/yql/dq/comp_nodes/dq_hash_combine.cpp
Labels: not-for-changelog

#22891 Fix build against clang20
  ydb/core/base/statestorage_guardian.cpp
  ydb/core/blobstorage/vdisk/common/memusage.h
  ydb/library/formats/arrow/replace_key.h
  ydb/library/yaml_config/validator/validator_checks.h
  ydb/library/yql/utils/simd/simd_avx2.h
  ydb/library/yql/utils/simd/simd_sse42.h
  ydb/services/datastreams/put_records_actor.h
Labels: not-for-changelog

#22900 Hide pile states under flag in ydb discovery list
  ydb/public/lib/ydb_cli/commands/ydb_service_discovery.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_discovery.h
Labels: not-for-changelog

#22901 Fixed java build for public API protos
  ydb/public/api/protos/ydb_bridge_common.proto
Labels: not-for-changelog

#22907 fix simple reader destruction
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/context.cpp
Labels: bugfix

#22892 deduplication memory control and signals
  ydb/core/tx/columnshard/columnshard_private_events.h
  ydb/core/tx/columnshard/counters/duplicate_filtering.cpp
  ydb/core/tx/columnshard/counters/duplicate_filtering.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/private_events.h
  ydb/library/signals/object_counter.h
Labels: not-for-changelog

#22915 add link to code in config dumps comparations
  ydb/tests/library/compatibility/configs/comparator/__main__.py
Labels: not-for-changelog

#22914 add info about source to config dump
  ydb/tests/library/compatibility/configs/dump/dumper/main.cpp
Labels: not-for-changelog

#22695 Support IN-PROCESS record for grpc calls
  ydb/core/audit/audit_config/audit_config.cpp
  ydb/core/audit/audit_config/audit_config.h
  ydb/core/audit/audit_config/audit_config_ut.cpp
  ydb/core/grpc_services/audit_log.cpp
  ydb/core/grpc_services/audit_log.h
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/mon/audit/audit.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#22909 Added a condition to fix the arcadia import
  ydb/docs/ru/core/concepts/index.md
Labels: documentation

#22800 Change grants for secondary index creation
  ydb/core/grpc_services/rpc_alter_table.cpp
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/tests/functional/security/test_grants.py
Labels: improvement

#22232 Configuration for the result set format in QueryService with Arrow
  ydb/core/formats/arrow/arrow_batch_builder.cpp
  ydb/core/formats/arrow/arrow_batch_builder.h
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/kqp/common/events/query.h
  ydb/core/kqp/common/kqp_event_impl.cpp
  ydb/core/kqp/common/kqp_result_set_format_settings.h
  ydb/core/kqp/common/kqp_row_builder.cpp
  ydb/core/kqp/common/kqp_row_builder.h
  ydb/core/kqp/common/ya.make
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_partitioned_executer.cpp
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/query_data/kqp_query_data.cpp
  ydb/core/kqp/query_data/kqp_query_data.h
  ydb/core/kqp/runtime/kqp_transport.cpp
  ydb/core/kqp/runtime/kqp_transport.h
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/arrow/kqp_result_set_format_arrow.cpp
  ydb/core/kqp/ut/arrow/ya.make
  ydb/core/protos/feature_flags.proto
  ydb/core/protos/kqp.proto
  ydb/public/api/protos/ydb_formats.proto
  ydb/public/api/protos/ydb_query.proto
  ydb/public/api/protos/ydb_value.proto
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/arrow/accessor.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/query/query.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/result/result.h
  ydb/public/sdk/cpp/src/client/arrow/accessor.cpp
  ydb/public/sdk/cpp/src/client/arrow/ya.make
  ydb/public/sdk/cpp/src/client/query/impl/exec_query.cpp
  ydb/public/sdk/cpp/src/client/result/result.cpp
  ydb/public/sdk/cpp/src/client/result/ya.make
  ydb/public/sdk/cpp/tests/integration/basic_example/main.cpp
  ydb/services/ydb/ydb_ut.cpp
Labels: new-feature

#22732 Always release partition on graceful TEvReleased
  ydb/services/persqueue_v1/actors/read_session_actor.cpp
  ydb/services/persqueue_v1/persqueue_ut.cpp
Labels: not-for-changelog

#22927 Retain RACE responses in bridge proxy
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/backpressure/ut_client/skeleton_front_mock.h
  ydb/core/blobstorage/base/blobstorage_events.h
  ydb/core/blobstorage/bridge/proxy/bridge_proxy.cpp
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
  ydb/core/blobstorage/ut_blobstorage/lib/node_warden_mock_vdisk.h
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeletonfront.cpp
Labels: not-for-changelog

#22689 stop using TFsPath in backup / restore for db paths
  ydb/library/backup/backup.cpp
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
Labels: not-for-changelog

#22853 YQ-4513 fix & some api/parsing tweaks
  ydb/library/yql/providers/solomon/common/util.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_logical_optimize.cpp
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_accessor_client.cpp
  ydb/library/yql/tests/sql/solomon/canondata/result.json
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-LabelColumnAliases-default.txt_/opt.yql
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-LabelColumnAliases-default.txt_/plan.txt
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-LabelColumnAliases-default.txt_/results.txt
  ydb/library/yql/tests/sql/suites/solomon/LabelColumnAliases.sql
  ydb/tests/fq/solomon/canondata/result.json
  ydb/tests/fq/solomon/canondata/test.test_solomon-LabelColumnAliases-default.txt_/results.txt
Labels: not-for-changelog

#22833 Olap backpressure tx proxy ydb
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/overload/overload_subscribers.h
  ydb/core/tx/data_events/shard_writer.cpp
  ydb/core/tx/data_events/shard_writer.h
Labels: not-for-changelog

#22777 fix local upload tests
  ydb/tests/olap/lib/remote_execution.py
  ydb/tests/olap/load/lib/upload.py
Labels: not-for-changelog

#22942 Fix zero creation time in keyvalue volume
  ydb/core/keyvalue/keyvalue_state.cpp
  ydb/core/keyvalue/keyvalue_ut.cpp
Labels: area/blobstorage, not-for-changelog

#22829 Fix GroupConfigurationPropagation::Reassign unit test
  .github/config/muted_ya.txt
  ydb/core/blobstorage/ut_blobstorage/bsc_cache.cpp
Labels: not-for-changelog

#22947 Fix OutputHtml function declaration
  ydb/core/tablet/tablet_counters.h
Labels: not-for-changelog

#22949 Add meta attribute to enable topic compactification
  ydb/services/lib/actors/pq_schema_actor.cpp
  ydb/services/persqueue_v1/actors/schema_actors.cpp
Labels: not-for-changelog

#22967 Log the number of saturated TPC-C threads (#17333)
  ydb/library/workload/tpcc/runner.cpp
  ydb/library/workload/tpcc/runner_display_data.h
  ydb/library/workload/tpcc/runner_tui.cpp
Labels: not-for-changelog

#22963 test_simple has been skipped for version less than (25, 1, 3)
  ydb/tests/compatibility/test_compatibility.py
Labels: not-for-changelog

#22973 24-4 support fix
  ydb/tests/compatibility/test_compatibility.py
Labels: not-for-changelog

#22975 [C++ SDK] Fix compatibility for VALUE format
  ydb/public/sdk/cpp/src/client/query/impl/exec_query.cpp
Labels: not-for-changelog

#22948 Add meta attribute to enable topic compactification: ydb-cli & stress test
  ydb/public/lib/ydb_cli/commands/topic_operations_scenario.cpp
  ydb/public/lib/ydb_cli/commands/topic_operations_scenario.h
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_init.cpp
  ydb/tests/stress/topic_kafka/__main__.py
  ydb/tests/stress/topic_kafka/workload/workload_topic.py
Labels: not-for-changelog
