Repository ydb-platform/ydb, pull requests merged in 2025-09, with the labels that each got.

#23843 TEvInternalScan::ToString for investigation
  ydb/core/tx/columnshard/columnshard.h
Labels: not-for-changelog

#23854 add compilation time to datamart
  .github/scripts/analytics/data_mart_queries/perfomance_olap_mart.sql
  .github/scripts/analytics/data_mart_queries/perfomance_olap_suites_mart.sql
Labels: not-for-changelog

#23080 autopartitioning of mirrored topics: describe and compare target topic with remote source
  ydb/core/persqueue/actor_persqueue_client_iface.h
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_key_range/partition_key_range_sequence.cpp
  ydb/core/persqueue/partition_key_range/partition_key_range_sequence.h
  ydb/core/persqueue/partition_key_range/partition_key_range_sequence_ut.cpp
  ydb/core/persqueue/partition_key_range/ut/ya.make
  ydb/core/persqueue/partition_key_range/ya.make
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/pqrb/mirror_describer.cpp
  ydb/core/persqueue/pqrb/mirror_describer.h
  ydb/core/persqueue/pqrb/partition_scale_manager.cpp
  ydb/core/persqueue/pqrb/partition_scale_manager.h
  ydb/core/persqueue/pqrb/partition_scale_manager_graph_cmp.cpp
  ydb/core/persqueue/pqrb/partition_scale_manager_graph_cmp.h
  ydb/core/persqueue/pqrb/partition_scale_request.cpp
  ydb/core/persqueue/pqrb/partition_scale_request.h
  ydb/core/persqueue/pqrb/read_balancer.cpp
  ydb/core/persqueue/pqrb/read_balancer.h
  ydb/core/persqueue/pqrb/ya.make
  ydb/core/persqueue/ut/common/autoscaling_ut_common.cpp
  ydb/core/persqueue/ut/partition_scale_manager_graph_cmp_ut.cpp
  ydb/core/persqueue/ut/ut_with_sdk/mirrorer_autoscaling_ut.cpp
  ydb/core/persqueue/ut/ya.make
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/protos/pqconfig.proto
  ydb/core/tx/schemeshard/schemeshard__operation_alter_pq.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/ut_topic_set_boundaries/ut_topic_set_boundaries.cpp
  ydb/core/tx/schemeshard/ut_topic_set_boundaries/ya.make
  ydb/core/tx/schemeshard/ya.make
  ydb/library/services/services.proto
Labels: not-for-changelog

#23787 restrict database nodes for databases whiteboard queries
  ydb/core/viewer/json_wb_req.h
  ydb/core/viewer/viewer_tabletinfo.h
  ydb/core/viewer/wb_req.h
Labels: not-for-changelog

#23789 YQ-4594 fixes for kqprun and fqrun
  ydb/tests/fq/control_plane_storage/in_memory_control_plane_storage_ut.cpp
  ydb/tests/tools/fqrun/configuration/app_config.conf
  ydb/tests/tools/fqrun/fqrun.cpp
  ydb/tests/tools/fqrun/src/common.h
  ydb/tests/tools/fqrun/src/fq_runner.cpp
  ydb/tests/tools/fqrun/src/fq_setup.cpp
  ydb/tests/tools/fqrun/src/ya.make
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/runlib/actors.h
  ydb/tests/tools/kqprun/runlib/application.cpp
  ydb/tests/tools/kqprun/runlib/application.h
  ydb/tests/tools/kqprun/runlib/kikimr_setup.cpp
  ydb/tests/tools/kqprun/runlib/kikimr_setup.h
  ydb/tests/tools/kqprun/runlib/settings.h
  ydb/tests/tools/kqprun/runlib/utils.cpp
  ydb/tests/tools/kqprun/runlib/utils.h
  ydb/tests/tools/kqprun/scripts/flame_graph.sh
  ydb/tests/tools/kqprun/src/actors.cpp
  ydb/tests/tools/kqprun/src/actors.h
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: not-for-changelog

#23828 sys view for resource pools has been fixed
  ydb/tests/compatibility/test_system_views.py
Labels: not-for-changelog

#23921 multi users have been fixed
  ydb/tests/stability/tool/__main__.py
Labels: not-for-changelog

#23380 structure refactoring and small fixes of datamodel section in concepts
  ydb/docs/redirects.yaml
  ydb/docs/ru/core/changelog-cli.md
  ydb/docs/ru/core/changelog-server.md
  ydb/docs/ru/core/concepts/_includes/transactions.md
  ydb/docs/ru/core/concepts/architecture.md
  ydb/docs/ru/core/concepts/async-replication.md
  ydb/docs/ru/core/concepts/cdc.md
  ydb/docs/ru/core/concepts/datamodel/_includes/object-naming-rules.md
  ydb/docs/ru/core/concepts/datamodel/_includes/table.md
  ydb/docs/ru/core/concepts/datamodel/cluster-namespace.md
  ydb/docs/ru/core/concepts/datamodel/index.md
  ydb/docs/ru/core/concepts/datamodel/toc_i.yaml
  ydb/docs/ru/core/concepts/datamodel/topic.md
  ydb/docs/ru/core/concepts/federated_query/s3/formats.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/concepts/toc_i.yaml
  ydb/docs/ru/core/concepts/transfer.md
  ydb/docs/ru/core/dev/cdc.md
  ydb/docs/ru/core/dev/getting-started.md
  ydb/docs/ru/core/dev/terraform.md
  ydb/docs/ru/core/integrations/ingestion/logstash.md
  ydb/docs/ru/core/reference/kafka-api/examples.md
  ydb/docs/ru/core/reference/kafka-api/index.md
  ydb/docs/ru/core/reference/observability/metrics/index.md
  ydb/docs/ru/core/reference/ydb-cli/topic-alter.md
  ydb/docs/ru/core/reference/ydb-cli/topic-consumer-add.md
  ydb/docs/ru/core/reference/ydb-cli/topic-consumer-offset-commit.md
  ydb/docs/ru/core/reference/ydb-cli/topic-create.md
  ydb/docs/ru/core/reference/ydb-cli/topic-read.md
  ydb/docs/ru/core/reference/ydb-cli/workload-topic.md
  ydb/docs/ru/core/reference/ydb-sdk/coordination.md
  ydb/docs/ru/core/reference/ydb-sdk/topic.md
  ydb/docs/ru/core/yql/reference/syntax/alter-topic.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/changefeed.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/rename.md
  ydb/docs/ru/core/yql/reference/syntax/create-topic.md
  ydb/docs/ru/core/yql/reference/syntax/create-transfer.md
  ydb/docs/ru/core/yql/reference/syntax/create-view.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/index.md
  ydb/docs/ru/core/yql/reference/syntax/drop-topic.md
  ydb/docs/ru/core/yql/reference/syntax/drop-transfer.md
Labels: documentation

#23924 Point prefix autochooser & sort removal
  ydb/core/kqp/common/kqp_yql.cpp
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/opt/kqp_opt.cpp
  ydb/core/kqp/opt/kqp_opt_impl.h
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_sort.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
  ydb/core/protos/table_service_config.proto
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_simple_multi_select.sql-plan_/simple_multi_select.sql.plan
Labels: not-for-changelog

#23944 Tests TxUsage::Sinks_*_WriteToTopicAndTable_*
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
Labels: not-for-changelog

#23922 Hash join utils: tuple layout
  ydb/library/yql/dq/comp_nodes/hash_join_utils/hashes_calc.h
  ydb/library/yql/dq/comp_nodes/hash_join_utils/packing.h
  ydb/library/yql/dq/comp_nodes/hash_join_utils/tuple.cpp
  ydb/library/yql/dq/comp_nodes/hash_join_utils/tuple.h
  ydb/library/yql/dq/comp_nodes/hash_join_utils/ut/packed_tuple_ut.cpp
  ydb/library/yql/dq/comp_nodes/hash_join_utils/ut/ya.make
  ydb/library/yql/dq/comp_nodes/hash_join_utils/ya.make
  ydb/library/yql/dq/comp_nodes/ya.make
  ydb/library/yql/minikql/comp_nodes/packed_tuple/tuple.cpp
  ydb/library/yql/minikql/comp_nodes/packed_tuple/tuple.h
  ydb/library/yql/minikql/comp_nodes/ya.make
  ydb/library/yql/minikql/ya.make
  ydb/library/yql/ya.make
Labels: experimental-feature, external

#23913 Do not allow non-bootstrap command as first config-changing for cluster
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_fsm.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_storage_config.cpp
Labels: not-for-changelog

#23959 enable enable_topic_compactification_by_key in the stress test
  ydb/tests/stress/topic_kafka/tests/test_workload_topic.py
Labels: not-for-changelog

#23552 Drop the assertion for input value in IntervalTo* functions
  ydb/library/yql/udfs/common/datetime/datetime_udf.cpp
Labels: area/yql, not-for-changelog

#22836 Add SUSPENDED state to distconf
  ydb/core/base/bridge.h
  ydb/core/blobstorage/nodewarden/distconf_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_bridge.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/cms/cms.cpp
  ydb/core/cms/cms_impl.h
  ydb/core/discovery/discovery.cpp
  ydb/core/grpc_services/rpc_bridge.cpp
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/core/protos/bridge.proto
  ydb/tests/functional/bridge/test_bridge.py
  ydb/tests/functional/bridge/ya.make
Labels: not-for-changelog

#23969 fix test compatibility #23772
  ydb/tests/compatibility/test_simple_reader.py
Labels: not-for-changelog

#23856 use stream lookup for vector indexes
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.h
  ydb/core/kqp/opt/logical/kqp_opt_log_indexes.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_vector_ut.cpp
Labels: not-for-changelog

#23997 also account sort & skip & take chain
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
Labels: not-for-changelog

#23977 Changed the cluster version check in the compatibility test
  ydb/tests/compatibility/s3_backups/test_export_import_s3.py
Labels: not-for-changelog

#23908 fix deduplication context destruction
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.h
Labels: bugfix

#23995 compaction settings improvement
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.cpp
Labels: not-for-changelog

#23993 [row dispatcher] fix use-after-free
  ydb/core/fq/libs/row_dispatcher/format_handler/filters/filters_set.cpp
Labels: not-for-changelog

#23985 Report Bridge group syncing progress through system views
  ydb/core/blobstorage/nodewarden/node_warden_group.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_pipe.cpp
  ydb/core/mind/bscontroller/bridge.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/register_node.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/mind/bscontroller/sys_view.cpp
  ydb/core/protos/counters_bs_controller.proto
  ydb/core/protos/sys_view.proto
  ydb/core/sys_view/common/registry.h
  ydb/core/sys_view/storage/groups.cpp
  ydb/core/sys_view/ut_registry.cpp
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_bs_controller_/flat_bs_controller.schema
Labels: not-for-changelog

#24010 Fix node warden assertion
  ydb/core/blobstorage/nodewarden/node_warden_group.cpp
Labels: bugfix

#23958 Fixed #23771
  ydb/core/kqp/session_actor/kqp_temp_tables_manager.cpp
Labels: not-for-changelog

#23203 New solomon/reading testcases implementation
  ydb/library/yql/tools/solomon_emulator/client/client.py
  ydb/library/yql/tools/solomon_emulator/lib/multi_shard.py
  ydb/library/yql/tools/solomon_emulator/lib/shard.py
  ydb/library/yql/tools/solomon_emulator/lib/webapp.py
  ydb/tests/solomon/reading/base.py
  ydb/tests/solomon/reading/basic_reading.py
  ydb/tests/solomon/reading/data_paging.py
  ydb/tests/solomon/reading/listing_paging.py
  ydb/tests/solomon/reading/settings_validation.py
  ydb/tests/solomon/reading/ya.make
Labels: not-for-changelog

#23798 solomon data source plan properties
  ydb/library/yql/providers/solomon/actors/dq_solomon_read_actor.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
Labels: not-for-changelog

#23948 gml optimizations and fixes
  ydb/core/tx/limiter/grouped_memory/service/group.cpp
  ydb/core/tx/limiter/grouped_memory/service/manager.cpp
  ydb/core/tx/limiter/grouped_memory/service/process.h
  ydb/core/tx/limiter/grouped_memory/usage/abstract.cpp
  ydb/core/tx/limiter/grouped_memory/ut/ut_manager.cpp
  ydb/core/tx/limiter/grouped_memory/ya.make
  ydb/core/tx/ya.make
Labels: not-for-changelog

#24030 fix for access denied in /viewer/capabilities handler
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/viewer_capabilities.h
Labels: bugfix, hotfix

#23954 Request full (and same) permissions set for all requests
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/library/cloud_permissions/cloud_permissions.h
  ydb/services/datastreams/grpc_service.cpp
  ydb/services/persqueue_v1/actors/persqueue_utils.h
  ydb/services/persqueue_v1/topic.cpp
Labels: not-for-changelog

#24079 fix for access denied in /viewer/capabilities handler (#24030)
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/json_pipe_req.h
  ydb/core/viewer/viewer_capabilities.h
Labels: bugfix, hotfix

#24090 Mute unstable tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#24089 fix for pr body limit
  .github/scripts/create_or_update_pr.py
Labels: not-for-changelog

#24097 Add stable-25-2 and stable-25-2-1 to update muted_ya
  .github/workflows/update_muted_ya.yml
Labels: not-for-changelog

#23136 Improvment test monitoring collecting for mute
  .github/scripts/analytics/flaky_tests_history.py
  .github/scripts/analytics/tests_monitor.py
Labels: not-for-changelog

#24044 provide additional debug info for index auto selection
  ydb/core/kqp/common/kqp_yql.cpp
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/opt/kqp_opt.cpp
  ydb/core/kqp/opt/kqp_opt_impl.h
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
Labels: not-for-changelog

#23722 Pass audit log subject, sanitized token, peer name fields for export and import operations and suboperations
  ydb/core/protos/flat_tx_scheme.proto
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard_audit_log.cpp
  ydb/core/tx/schemeshard/schemeshard_export.cpp
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/schemeshard_export_flow_proposals.cpp
  ydb/core/tx/schemeshard/schemeshard_import.cpp
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_import_flow_proposals.cpp
  ydb/core/tx/schemeshard/schemeshard_import_flow_proposals.h
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/schemeshard_xxport__helpers.cpp
  ydb/core/tx/schemeshard/schemeshard_xxport__helpers.h
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#17892 Tests for restoring unique indexes
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ut_export_reboots_s3.cpp
  ydb/core/tx/schemeshard/ut_helpers/export_reboots_common.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
  ydb/tests/datashard/dump_restore/test_dump_restore.py
  ydb/tests/sql/lib/test_base.py
Labels: not-for-changelog

#24048 Bootstrap system tablets only in primary pile
  ydb/core/base/appdata_fwd.h
  ydb/core/cms/cms_ut_common.cpp
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/tablet/bootstrapper.cpp
Labels: not-for-changelog

#24126 Disable asan test of prototype spilling
  ydb/library/yql/core/spilling/ut/ya.make
Labels: not-for-changelog

#24062 Fix EvWrite Reattach
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/ut/effects/kqp_reattach_ut.cpp
  ydb/core/kqp/ut/effects/ya.make
Labels: not-for-changelog

#23936 Support cache modes in KQP
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/provider/yql_kikimr_gateway.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/ydb_convert/column_families.h
  ydb/core/ydb_convert/table_description.cpp
  ydb/core/ydb_convert/table_description_ut.cpp
  ydb/public/api/protos/ydb_table.proto
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table_enum.h
  ydb/public/sdk/cpp/src/client/table/table.cpp
  ydb/services/ydb/ydb_table_ut.cpp
Labels: not-for-changelog

#24175 Unmute CTAS tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#24130 improve clock skew calculations and reporting
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
  ydb/public/api/protos/ydb_monitoring.proto
Labels: not-for-changelog

#24164 Fix replication query error in Bridge mode
  ydb/core/blobstorage/vdisk/repl/blobstorage_hullrepljob.cpp
Labels: bugfix

#24086 wait for connection has been increased
  ydb/tests/compatibility/test_workload_manager.py
Labels: not-for-changelog

#23715 Add cluster permissions for check in cloud
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/grpc_services/grpc_request_check_actor_ut/grpc_request_check_actor_ut.cpp
  ydb/core/grpc_services/grpc_request_check_actor_ut/ya.make
  ydb/core/grpc_services/ya.make
Labels: not-for-changelog

#23799 Configurable blobstorage common histogram bounds
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/base/config_metrics.h
  ydb/core/blobstorage/base/common_latency_hist_bounds.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/protos/config.proto
  ydb/core/protos/config_metrics.proto
  ydb/core/protos/ya.make
  ydb/core/testlib/actor_helpers.cpp
  ydb/core/testlib/actor_helpers.h
Labels: improvement

#24205 Don't allow SetActivityType after actor registration
  ydb/core/client/server/msgbus_server_pq_metarequest_ut.cpp
  ydb/core/keyvalue/keyvalue_flat_impl.h
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/test_tablet/test_shard_impl.h
  ydb/library/actors/core/actor.cpp
  ydb/library/actors/core/actor.h
Labels: not-for-changelog

#24080 Improve kafka streams test main
  ydb/tests/stress/kafka/__main__.py
  ydb/tests/stress/kafka/workload/__init__.py
Labels: not-for-changelog

#24088 Data race has been fixed between two TEvProposeTransaction
  ydb/core/tx/columnshard/transactions/tx_controller.h
Labels: not-for-changelog

#24230 fix hanging read and get prepared for rows reuse
  ydb/core/kqp/runtime/kqp_stream_lookup_worker.cpp
Labels: not-for-changelog

#23575 Use mvcc snapshot in restore task on writes
  ydb/core/kqp/ut/tx/kqp_sink_mvcc_ut.cpp
  ydb/core/tx/columnshard/columnshard__write.cpp
  ydb/core/tx/columnshard/tablet/write_queue.cpp
  ydb/core/tx/columnshard/tablet/write_queue.h
Labels: not-for-changelog

#24064 Don't allow StaleRO/OnlineRO for Olap
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/kqp/ut/tx/kqp_sink_tx_ut.cpp
Labels: not-for-changelog

#24251 Fix race in ICB
  ydb/core/control/lib/immediate_control_board_control.cpp
Labels: bugfix

#24132 Fixed redirects from v24.4 to main
  ydb/docs/redirects.yaml
Labels: documentation

#24254 YQ-4639 fixed CPU limiting in composite conveyor
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/ya.make
  ydb/core/tx/conveyor_composite/usage/config.cpp
  ydb/core/tx/conveyor_composite/usage/config.h
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: bugfix

#24282 Unpoison trace id to prevent false msan alert
  ydb/library/actors/interconnect/interconnect_channel.cpp
Labels: bugfix

#24297 Skipper fixes, stateful skipper (#23455)
  ydb/apps/bridge_skipper_demo/README_ru.md
  ydb/apps/bridge_skipper_demo/bridge.py
  ydb/apps/bridge_skipper_demo/health.py
  ydb/apps/bridge_skipper_demo/skipper.py
  ydb/apps/bridge_skipper_demo/skipper_tui.py
  ydb/apps/bridge_skipper_demo/test_async_healthcheck_runner.py
  ydb/apps/bridge_skipper_demo/test_bridgekeeper.py
Labels: not-for-changelog

#24293 [C++ SDK] Fixed usage of destroyed grpc context in IAM cred provider
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/iam/common/generic_provider.h
Labels: not-for-changelog

#24296 [C++ SDK] Fixed operation client build on darwin
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/operation/operation.h
Labels: not-for-changelog

#24308 Fix race in TUI rendering (#23455)
  ydb/apps/bridge_skipper_demo/skipper_tui.py
Labels: not-for-changelog

#24298 [C++ SDK] Changed grpc load balancing policy to round_robin
  ydb/public/sdk/cpp/src/client/impl/ydb_internal/grpc_connections/grpc_connections.h
  ydb/services/ydb/ydb_register_node_ut.cpp
Labels: not-for-changelog

#24235 Ignore overloads in stress test
  ydb/tests/stress/olap_workload/workload/type/rename_tables.py
Labels: not-for-changelog

#24287 Send dst path for renamed column tables
  ydb/core/protos/tx_columnshard.proto
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_table.cpp
Labels: not-for-changelog

#24344 make wakeup callback thread safe
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_async_io.h
Labels: not-for-changelog

#24345 Switch CS to DS TEvCancelTransactionProposal
  ydb/core/protos/tx_columnshard.proto
  ydb/core/tx/columnshard/columnshard.h
  ydb/core/tx/columnshard/columnshard__propose_cancel.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/long_tx_service/commit_impl.cpp
Labels: not-for-changelog

#24302 Reduce EstablishingSessions state timeout
  ydb/core/blobstorage/dsproxy/dsproxy.h
Labels: not-for-changelog

#23674 [YQ-4583] Watermarks: RD: pq read actor support
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/library/yql/dq/actors/compute/dq_source_watermark_tracker.h
  ydb/library/yql/dq/actors/compute/ut/dq_source_watermark_tracker_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_hopping.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor.cpp
  ydb/tests/fq/pq_async_io/ut/dq_pq_rd_read_actor_ut.cpp
  ydb/tests/fq/pq_async_io/ut/dq_pq_read_actor_ut.cpp
  ydb/tests/fq/pq_async_io/ut_helpers.cpp
  ydb/tests/fq/pq_async_io/ut_helpers.h
  ydb/tests/fq/yds/test_watermarks.py
  ydb/tests/fq/yds/ya.make
Labels: not-for-changelog

#23400 Add database attribute to more spans
  ydb/core/grpc_services/query/rpc_execute_query.cpp
  ydb/core/grpc_services/rpc_deferrable.h
  ydb/core/kqp/session_actor/kqp_query_state.h
Labels: improvement

#24033 Do not mix scalar and block HashShuffle connections
  ydb/core/kqp/opt/peephole/kqp_opt_peephole.cpp
Labels: bugfix

#24374 Fix ydb update timeout
  ydb/public/lib/ydb_cli/common/ydb_updater.cpp
Labels: not-for-changelog

#24294 Fix kafka api read bug static nodes main
  ydb/core/kafka_proxy/actors/actors.h
  ydb/core/kafka_proxy/actors/kafka_balancer_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_balancer_actor.h
  ydb/core/kafka_proxy/actors/kafka_describe_groups_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_init_producer_id_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_list_groups_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_offset_fetch_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_produce_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_sasl_auth_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_sasl_auth_actor.h
  ydb/core/kafka_proxy/actors/kafka_transaction_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_transaction_actor.h
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_events.h
  ydb/core/kafka_proxy/kafka_transactions_coordinator.cpp
  ydb/core/kafka_proxy/ut/actors_ut.cpp
  ydb/core/kafka_proxy/ut/metarequest_ut.cpp
  ydb/core/kafka_proxy/ut/ut_produce_actor.cpp
  ydb/core/kafka_proxy/ut/ut_transaction_actor.cpp
  ydb/core/kafka_proxy/ut/ut_transaction_coordinator.cpp
  ydb/core/tx/scheme_cache/scheme_cache.h
  ydb/services/metadata/abstract/kqp_common.cpp
  ydb/services/metadata/abstract/kqp_common.h
Labels: not-for-changelog

#24414 Fix canonical results for q49 and q75 tpcds s100 with decimals
  ydb/library/workload/tpc_base/tpc_base.cpp
  ydb/library/workload/tpc_base/tpc_base.h
  ydb/library/workload/tpcds/s100_canonical/q49.decimal.result
  ydb/library/workload/tpcds/s100_canonical/q49.double.result.gz
  ydb/library/workload/tpcds/s100_canonical/q75.decimal.result
  ydb/library/workload/tpcds/s100_canonical/q75.double.result.gz
Labels: not-for-changelog

#24072 identify intersections by rows in deduplication
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/core/tx/columnshard/columnshard_private_events.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/common.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/common.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/context.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/events.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/manager.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/merge.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/merge.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/private_events.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/duplicates/splitter.h
Labels: not-for-changelog

#24329 YQ-4645 supported monitoring and grpc links printing in kqprun / fqrun
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/fqrun/src/fq_setup.cpp
  ydb/tests/tools/kqprun/runlib/application.cpp
  ydb/tests/tools/kqprun/runlib/kikimr_setup.cpp
  ydb/tests/tools/kqprun/runlib/kikimr_setup.h
  ydb/tests/tools/kqprun/runlib/ya.make
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: not-for-changelog

#24392 Option `init-seqno-timeout`
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
  ydb/public/lib/ydb_cli/topic/topic_write.cpp
  ydb/public/lib/ydb_cli/topic/topic_write.h
  ydb/public/lib/ydb_cli/topic/topic_write_ut.cpp
Labels: improvement

#24325 Small CS column types issues (UUID is unsupported, Interval64 is supported)
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/tx/schemeshard/olap/columns/update.cpp
  ydb/tests/datashard/lib/types_of_variables.py
Labels: not-for-changelog

#24450 Add event for token agent
  ydb/core/base/events.h
Labels: not-for-changelog

#24361 Check src stage to be WideChannel-enabled for block propagation
  ydb/core/kqp/opt/peephole/kqp_opt_peephole.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#24468 add reverse methods
  ydb/library/actors/http/http.cpp
  ydb/library/actors/http/http.h
Labels: not-for-changelog

#24470 update unittest: Read topic by timestamp
  ydb/core/persqueue/ut/ut_with_sdk/topic_timestamp_ut.cpp
  ydb/core/persqueue/ut/ut_with_sdk/topic_ut.cpp
  ydb/core/persqueue/ut/ut_with_sdk/ya.make
Labels: not-for-changelog

#24252 Topic SDK: change type of ServerBytesSize to atomic
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/public/sdk/cpp/src/client/topic/impl/read_session_impl.h
  ydb/public/sdk/cpp/src/client/topic/impl/read_session_impl.ipp
Labels: not-for-changelog

#24449 Blob key filter
  ydb/core/persqueue/common/key.cpp
  ydb/core/persqueue/common/key.h
  ydb/core/persqueue/pqtablet/partition/partition_init.cpp
Labels: not-for-changelog

#23992 Update TESTOWNERS
  .github/TESTOWNERS
Labels: not-for-changelog

#24286 added shared mutex #24149
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
Labels: not-for-changelog

#18952 TOPICS: tests for export / import S3
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ut_export_reboots_s3.cpp
  ydb/core/tx/schemeshard/ut_helpers/ls_checks.cpp
  ydb/core/tx/schemeshard/ut_helpers/ls_checks.h
  ydb/core/tx/schemeshard/ut_helpers/ut_backup_restore_common.h
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
Labels: not-for-changelog

#24534 Fix timeout error message
  ydb/public/lib/ydb_cli/commands/ydb_benchmark.cpp
Labels: not-for-changelog

#24539 Improve brigded group proxy a bit
  ydb/core/blobstorage/bridge/proxy/bridge_proxy.cpp
Labels: not-for-changelog

#24065 Add system tablet backup to config
  ydb/core/base/appdata.cpp
  ydb/core/base/appdata_fwd.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/protos/config.proto
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_executor_backup.cpp
  ydb/core/tablet_flat/flat_executor_backup.h
  ydb/core/tablet_flat/tablet_flat_executor.cpp
  ydb/core/tablet_flat/tablet_flat_executor.h
  ydb/core/tablet_flat/ya.make
  ydb/library/services/services.proto
Labels: not-for-changelog

#22970 Explain plan docs
  ydb/docs/ru/core/concepts/optimizer.md
  ydb/docs/ru/core/dev/query-hints.md
  ydb/docs/ru/core/dev/query-plans-optimization.md
  ydb/docs/ru/core/dev/toc_p.yaml
  ydb/docs/ru/core/reference/ydb-cli/commands/explain-plan.md
  ydb/docs/ru/core/yql/reference/syntax/pragma.md
Labels: documentation

#24456 Increase query service default query timeout to 2h.
  ydb/core/protos/config.proto
  ydb/docs/en/core/concepts/_includes/limits-ydb.md
  ydb/docs/ru/core/concepts/_includes/limits-ydb.md
Labels: improvement

#24554 In case of import retries, make sure history PK is the same (#17333)
  ydb/library/workload/tpcc/import.cpp
Labels: not-for-changelog

#23949 Cleanup legacy macros
  ydb/core/kqp/tests/tpch/lib/ya.make
  ydb/library/benchmarks/report/ut/ya.make
  ydb/library/benchmarks/report/ya.make
Labels: not-for-changelog, external

#24241 Make messages about timeouts in DSProxy more elaborate
  ydb/core/blobstorage/dsproxy/dsproxy_impl.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_impl.h
  ydb/core/blobstorage/dsproxy/dsproxy_state.cpp
Labels: improvement

#23919 Add test for Workload Manager Sheduler
  ydb/tests/functional/tpc/medium/test_workload_manager.py
  ydb/tests/olap/lib/ydb_cli.py
  ydb/tests/olap/load/lib/workload_manager.py
  ydb/tests/olap/load/lib/ya.make
Labels: not-for-changelog

#24578 Expanded constant folding to hide the problem with If pushdown into CS
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
  ydb/library/yql/dq/opt/dq_opt_stat.cpp
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join3.test_/query_1.plan
Labels: bugfix

#24209 [YDB Topics] Add docs for new kafka api features
  ydb/docs/en/core/reference/configuration/index.md
  ydb/docs/en/core/reference/configuration/kafka.md
  ydb/docs/en/core/reference/configuration/toc_p.yaml
  ydb/docs/en/core/reference/kafka-api/_includes/flink-constraints.md
  ydb/docs/en/core/reference/kafka-api/_includes/spark-constraints.md
  ydb/docs/en/core/reference/kafka-api/constraints.md
  ydb/docs/en/core/reference/kafka-api/examples.md
  ydb/docs/ru/core/reference/configuration/index.md
  ydb/docs/ru/core/reference/configuration/kafka.md
  ydb/docs/ru/core/reference/configuration/toc_p.yaml
  ydb/docs/ru/core/reference/kafka-api/_includes/flink-constraints.md
  ydb/docs/ru/core/reference/kafka-api/_includes/spark-constraints.md
  ydb/docs/ru/core/reference/kafka-api/connect/connect-step-by-step.md
  ydb/docs/ru/core/reference/kafka-api/connect/index.md
  ydb/docs/ru/core/reference/kafka-api/constraints.md
  ydb/docs/ru/core/reference/kafka-api/examples.md
Labels: documentation

#23838 MaxReadStaleness_ms has been increased
  ydb/core/kqp/ut/olap/write_ut.cpp
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
Labels: not-for-changelog

#24868 segfault and seqno have been fixed in case of Abort
  ydb/core/tx/columnshard/tablet/write_queue.cpp
Labels: not-for-changelog

#23849 do not register with poller on errors
  ydb/library/actors/http/http_proxy_outgoing.cpp
Labels: not-for-changelog

#23912 fixes for cs tables transaction behaviour
  ydb/docs/en/core/_includes/limitation-column-row-in-read-only-tx.md
  ydb/docs/en/core/concepts/_includes/transactions.md
  ydb/docs/ru/core/concepts/_includes/transactions.md
  ydb/docs/ru/core/yql/reference/_includes/limitation-column-row-in-read-only-tx.md
Labels: documentation

#24759 detect that db does not exist in healthcheck
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: improvement

#24913 Fix windows build in Github runners using toolchain from ya tool
  .github/workflows/build_ydb_cli.yml
Labels: not-for-changelog

#24621 YQ-4658 fixed streaming queries synchronization
  ydb/core/kqp/gateway/behaviour/streaming_query/queries.cpp
Labels: bugfix

#24933 Force tablet counters update before passing away
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
Labels: not-for-changelog

#24949 Set threads of TestWorkloadManagerTpchComputeShedulerS100 to 1
  ydb/tests/olap/load/lib/workload_manager.py
Labels: not-for-changelog

#24748 Pass read offset in the PartitionStatus response
  ydb/public/api/protos/ydb_topic.proto
  ydb/public/sdk/cpp/src/client/topic/impl/read_session_impl.ipp
  ydb/services/deprecated/persqueue_v0/api/protos/persqueue.proto
  ydb/services/persqueue_v1/actors/events.h
  ydb/services/persqueue_v1/actors/partition_actor.cpp
  ydb/services/persqueue_v1/actors/read_session_actor.cpp
  ydb/services/persqueue_v1/persqueue_ut.cpp
Labels: not-for-changelog

#24944 YQ-4676 optimized forget operation for script executions
  ydb/core/kqp/common/kqp.cpp
  ydb/core/kqp/common/kqp.h
  ydb/core/kqp/proxy_service/kqp_script_executions.cpp
  ydb/core/kqp/proxy_service/kqp_script_executions_impl.h
  ydb/core/kqp/ut/federated_query/large_results/kqp_scriptexec_results_ut.cpp
Labels: performance

#24842 ydb_cli: add an option to specify the memory usage limit for the topic workload scenarios, and lower the default read buffer size because it discards all incomming data anyway
  ydb/public/lib/ydb_cli/commands/topic_operations_scenario.cpp
  ydb/public/lib/ydb_cli/commands/topic_operations_scenario.h
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_reader.cpp
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_reader.h
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_run_full.cpp
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_run_read.cpp
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_run_write.cpp
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_writer.cpp
  ydb/public/lib/ydb_cli/commands/topic_workload/topic_workload_writer.h
  ydb/public/lib/ydb_cli/commands/topic_workload/ya.make
Labels: not-for-changelog

#24942 Refactor TKqpTasksGraph as new class
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_executer_stats.h
  ydb/core/kqp/executer_actor/kqp_literal_executer.cpp
  ydb/core/kqp/executer_actor/kqp_partition_helper.cpp
  ydb/core/kqp/executer_actor/kqp_partition_helper.h
  ydb/core/kqp/executer_actor/kqp_partitioned_executer.cpp
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.h
Labels: not-for-changelog

#24983 Import from S3: recursive import filter
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_utils.h
  ydb/core/tx/schemeshard/ut_base/ut_info_types.cpp
  ydb/library/actors/testlib/test_runtime.h
  ydb/services/ydb/backup_ut/backup_path_ut.cpp
Labels: not-for-changelog

#25007 UT for lost update on column update in CS
  ydb/core/kqp/ut/tx/kqp_sink_mvcc_ut.cpp
Labels: not-for-changelog

#24736 Fixed Column Shard write stats
  .github/config/muted_ya.txt
  ydb/core/kqp/ut/query/kqp_stats_ut.cpp
  ydb/core/tx/columnshard/blobs_action/common/statistics.cpp
  ydb/core/tx/columnshard/blobs_action/common/statistics.h
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.cpp
Labels: bugfix

#25043 Make sure that state generation is no ahead of cluster generation (#2…
  ydb/apps/bridge_skipper_demo/bridge.py
Labels: not-for-changelog

#24599 Reintroduce DSProxy timeout fixes
  ydb/core/blobstorage/dsproxy/dsproxy.h
  ydb/core/blobstorage/dsproxy/dsproxy_put.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_request.cpp
  ydb/core/blobstorage/ut_blobstorage/deadlines.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_vmovedpatch_actor.cpp
Labels: improvement

#25048 Supoport auth, update/translate README (#23455)
  ydb/apps/bridge_skipper_demo/README.md
  ydb/apps/bridge_skipper_demo/README_ru.md
  ydb/apps/bridge_skipper_demo/bridge.py
  ydb/apps/bridge_skipper_demo/cli_wrapper.py
  ydb/apps/bridge_skipper_demo/health.py
  ydb/apps/bridge_skipper_demo/skipper.py
Labels: not-for-changelog

#25036 fix(viewer): add missing tablet status
  ydb/core/viewer/viewer.cpp
Labels: not-for-changelog

#25030 Allow missing blobs in IndexRestoreGet query
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/bridge/syncer/syncer.cpp
  ydb/core/blobstorage/dsproxy/dsproxy_indexrestoreget.cpp
Labels: not-for-changelog

#23807 CTAS mkdir
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/gateway/kqp_ic_gateway.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/query/kqp_query_ut.cpp
Labels: not-for-changelog

#25067 describe has been fixed
  ydb/core/viewer/viewer_describe.h
Labels: not-for-changelog

#25083 fix msan test
  ydb/library/testlib/pq_helpers/mock_pq_gateway.cpp
Labels: not-for-changelog

#24835 Add transactions for tablets with many partitions main
  ydb/core/persqueue/pqtablet/pq_impl.cpp
  ydb/core/persqueue/pqtablet/pq_impl.h
  ydb/core/persqueue/ut/pqtablet_ut.cpp
Labels: not-for-changelog

#25091 Unmute pq_async_io ut
  .github/config/muted_ya.txt
  ydb/tests/fq/pq_async_io/ut/dq_pq_read_actor_ut.cpp
Labels: not-for-changelog

#25084 Optimize TEvAssimilate
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/vdisk/query/assimilation.cpp
Labels: performance

#12143 Update Superset docs after adding native driver support
  ydb/docs/en/core/integrations/visualization/_assets/superset-sample-chart.png
  ydb/docs/en/core/integrations/visualization/_assets/superset-sql-query.png
  ydb/docs/en/core/integrations/visualization/_assets/superset-ydb-connection-details.png
  ydb/docs/en/core/integrations/visualization/_assets/superset-ydb-pg-connection-details.png
  ydb/docs/en/core/integrations/visualization/_includes/toc-table.md
  ydb/docs/en/core/integrations/visualization/superset.md
  ydb/docs/ru/core/integrations/visualization/_assets/superset-sample-chart.png
  ydb/docs/ru/core/integrations/visualization/_assets/superset-sql-query.png
  ydb/docs/ru/core/integrations/visualization/_assets/superset-ydb-connection-details.png
  ydb/docs/ru/core/integrations/visualization/_assets/superset-ydb-pg-connection-details.png
  ydb/docs/ru/core/integrations/visualization/_includes/toc-table.md
  ydb/docs/ru/core/integrations/visualization/superset.md
Labels: documentation

#24639 Release notes 25.1.4
  ydb/docs/en/core/changelog-server.md
  ydb/docs/en/core/downloads/ydb-open-source-database.md
  ydb/docs/en/core/reference/configuration/feature_flags.md
  ydb/docs/ru/core/changelog-server.md
  ydb/docs/ru/core/downloads/ydb-open-source-database.md
  ydb/docs/ru/core/reference/configuration/feature_flags.md
Labels: documentation

#24784 Reorder the description of transaction modes by strictness
  ydb/docs/en/core/concepts/_includes/transactions.md
  ydb/docs/ru/core/concepts/_includes/transactions.md
Labels: documentation

#24016 docs: spark ca settings fix
  ydb/docs/en/core/integrations/ingestion/spark.md
  ydb/docs/ru/core/integrations/ingestion/spark.md
Labels: documentation

#25079 add string key types support
  ydb/core/kqp/tools/combiner_perf/joins.cpp
Labels: not-for-changelog

#25062 Add PreferLessOccupiedRack and WithAttentionToReplication to dstool
  ydb/apps/dstool/lib/dstool_cmd_cluster_balance.py
Labels: experimental-feature

#25099 fix partition StartOffset response after compaction
  ydb/core/persqueue/pqtablet/partition/partition.cpp
  ydb/core/persqueue/pqtablet/partition/partition_monitoring.cpp
  ydb/core/persqueue/ut/ut_with_sdk/describe_ut.cpp
  ydb/core/persqueue/ut/ut_with_sdk/ya.make
Labels: not-for-changelog

#25108 Report total network utilization for node
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/tablet/node_whiteboard.cpp
  ydb/library/actors/interconnect/interconnect_common.h
  ydb/library/actors/interconnect/interconnect_tcp_session.cpp
Labels: not-for-changelog

#25199 YQ-4683 explicitly enabled 'enable_pg_syntax' in fq tests
  ydb/tests/tools/fq_runner/kikimr_utils.py
Labels: not-for-changelog

#25201 Fix background cleaning
  ydb/core/tx/schemeshard/schemeshard__background_cleaning.cpp
Labels: not-for-changelog

#25055 Fix bootstrap auth doc
  ydb/docs/ru/core/devops/deployment-options/manual/initial-deployment.md
Labels: documentation

#25225 add base statistics check to statistics_workload
  ydb/tests/stress/statistics_workload/workload/__init__.py
Labels: not-for-changelog

#25221 Adjust cpu requirements
  ydb/tests/functional/autoconfig/ya.make
  ydb/tests/functional/security/ya.make
  ydb/tests/functional/sqs/common/ya.make
  ydb/tests/functional/sqs/large/ya.make
  ydb/tests/functional/sqs/merge_split_common_table/fifo/ya.make
  ydb/tests/functional/tenants/ya.make
Labels: external

#25113 YQ-4449 unmuted tests on s3 url escaping
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_actors_util.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_actors_util.h
  ydb/library/yql/providers/s3/actors/yql_s3_raw_read_actor.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_read_actor.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_write_actor.cpp
  ydb/library/yql/providers/s3/common/util.cpp
  ydb/library/yql/providers/s3/common/util_ut.cpp
  ydb/tests/tools/s3_recipe/.gitignore
Labels: bugfix

#25053 [KQP] Eliminate widemap for large olap table
  ydb/core/kqp/opt/peephole/kqp_opt_peephole.cpp
  ydb/core/kqp/opt/peephole/kqp_opt_peephole_rules.h
  ydb/core/kqp/opt/peephole/kqp_opt_peephole_wide_read.cpp
Labels: not-for-changelog

#24029 Исправления документации трансфера
  ydb/docs/ru/core/concepts/transfer.md
  ydb/docs/ru/core/reference/configuration/tls.md
  ydb/docs/ru/core/security/encryption/data-in-transit.md
  ydb/docs/ru/core/yql/reference/_includes/secret_tip.md
  ydb/docs/ru/core/yql/reference/_includes/transfer_flush.md
  ydb/docs/ru/core/yql/reference/syntax/alter-transfer.md
  ydb/docs/ru/core/yql/reference/syntax/create-async-replication.md
  ydb/docs/ru/core/yql/reference/syntax/create-transfer.md
  ydb/docs/ru/core/yql/reference/syntax/drop-transfer.md
Labels: documentation

#24659 YQ-4661 optimized streaming queries starting
  ydb/core/fq/libs/init/init.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.cpp
  ydb/core/fq/libs/row_dispatcher/actors_factory.h
  ydb/core/fq/libs/row_dispatcher/format_handler/format_handler.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/format_handler.h
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/json_parser.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/json_parser.h
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/parser_abstract.h
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/parser_base.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/parser_base.h
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/raw_parser.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/raw_parser.h
  ydb/core/fq/libs/row_dispatcher/format_handler/parsers/ya.make
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/common/ut_common.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/format_handler_ut.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/topic_parser_ut.cpp
  ydb/core/fq/libs/row_dispatcher/leader_election.cpp
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.h
  ydb/core/fq/libs/row_dispatcher/row_dispatcher_service.cpp
  ydb/core/fq/libs/row_dispatcher/row_dispatcher_service.h
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.h
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/topic_session_ut.cpp
  ydb/core/fq/libs/row_dispatcher/ut/ya.make
  ydb/core/fq/libs/test_connection/test_connection.h
  ydb/core/kqp/proxy_service/kqp_proxy_service.cpp
Labels: not-for-changelog

#25258 Fix unmute tests rules (4 days thresholds -> 7 days)
  .github/config/mute_rules.md
  .github/scripts/tests/create_new_muted_ya.py
Labels: not-for-changelog

#25223 Fix log handling and out of range string access (#17333)
  ydb/library/workload/tpcc/log_backend.cpp
  ydb/library/workload/tpcc/logs_scroller.cpp
Labels: not-for-changelog

#25000 Always set ArrayBufferMinFillPercentage from default value
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
Labels: performance

#25312 Revert "Add SIMD-based pack/unpack implementation (#23996)"
  ydb/library/yql/dq/comp_nodes/hash_join_utils/packing.h
  ydb/library/yql/dq/comp_nodes/hash_join_utils/tuple.cpp
  ydb/library/yql/dq/comp_nodes/hash_join_utils/tuple.h
  ydb/library/yql/utils/simd/simd_avx2.h
  ydb/library/yql/utils/simd/simd_fallback.h
  ydb/library/yql/utils/simd/simd_sse42.h
Labels: not-for-changelog

#25237 Set and show pdisk maintenance status in dstool
  ydb/apps/dstool/lib/dstool_cmd_pdisk_list.py
  ydb/apps/dstool/lib/dstool_cmd_pdisk_set.py
  ydb/core/mind/bscontroller/monitoring.cpp
  ydb/core/protos/blobstorage_config.proto
Labels: improvement

#25014 Base statistics compatibility test
  ydb/tests/compatibility/README.md
  ydb/tests/compatibility/test_statistics.py
  ydb/tests/library/compatibility/fixtures.py
  ydb/tests/library/compatibility/ya.make
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#25232 YQ-4684 added kikimr init waiting and fixed ULID gen usage
  ydb/core/kqp/gateway/actors/analyze_actor.cpp
  ydb/core/kqp/gateway/actors/analyze_actor.h
  ydb/core/kqp/rm_service/kqp_resource_info_exchanger.cpp
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_federated_query_ut.cpp
  ydb/core/statistics/service/http_request.cpp
  ydb/core/statistics/service/http_request.h
Labels: bugfix

#25262 Fix UMU in TStateStorageRingGroupProxyRequest
  ydb/core/base/statestorage_proxy.cpp
Labels: not-for-changelog
