Repository ydb-platform/ydb, pull requests merged in 2025-10, with the labels that each got.

#26018 Parse bool case insensitive for CSV
  ydb/public/lib/ydb_cli/common/csv_parser.cpp
  ydb/public/lib/ydb_cli/common/csv_parser_ut.cpp
Labels: not-for-changelog

#26157 Fix cpp include in yaml_config_proto2yaml_ut
  ydb/library/yaml_config/yaml_config_proto2yaml_ut.cpp
Labels: not-for-changelog

#26151 YQ-4745 fixed streaming queries sync after fail
  ydb/core/kqp/gateway/behaviour/streaming_query/initializer.cpp
  ydb/core/kqp/gateway/behaviour/streaming_query/queries.cpp
  ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp
Labels: bugfix

#26167 [KQP RBO] Add test canonization
  ydb/core/kqp/ut/rbo/kqp_rbo_ut.cpp
Labels: not-for-changelog

#26128 remove usage of datetime udf in ydbd
  ydb/apps/ydbd/ya.make
  ydb/core/kqp/tests/kikimr_tpch/ya.make
  ydb/tools/query_replay/common_deps.inc
  ydb/tools/query_replay_yt/common_deps.inc
Labels: not-for-changelog

#26125 lower initial delay before sending base statistics from schemeshard to statistics aggregator
  ydb/core/statistics/aggregator/tx_schemeshard_stats.cpp
  ydb/core/statistics/service/ut/ut_basic_statistics.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
Labels: not-for-changelog

#26099 EXT-1555 Add audit log on receive for unauthorized requests
  ydb/core/mon/mon.cpp
  ydb/tests/functional/audit/canondata/test_canonical_records.test_dml_through_http/audit_log.json
  ydb/tests/functional/audit/canondata/test_canonical_records.test_kill_tablet_using_developer_ui/audit_log.json
  ydb/tests/functional/audit/canondata/test_canonical_records.test_restart_pdisk/audit_log.json
Labels: bugfix

#26194 Add description to key mesuarments
  ydb/tests/olap/load/lib/conftest.py
  ydb/tests/olap/load/lib/workload_manager.py
Labels: not-for-changelog

#26120 Do not crash on new (unknown) build states during index build, add a test for it
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
Labels: not-for-changelog

#26079 Skip metering report with ydb_size=0 and topic category
  ydb/core/persqueue/pqtablet/metering_sink.cpp
  ydb/core/persqueue/pqtablet/metering_sink.h
  ydb/core/persqueue/ut/metering_sink_ut.cpp
  ydb/core/tx/schemeshard/ut_cdc_stream/ut_cdc_stream.cpp
Labels: not-for-changelog

#25874 Ensure snapshot read only does not take locks
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
  ydb/core/kqp/ut/service/kqp_snapshot_readonly.cpp
  ydb/core/kqp/ut/service/ya.make
  ydb/core/protos/kqp.proto
  ydb/core/protos/tx_datashard.proto
Labels: not-for-changelog

#26169 add tests for new huge blob keeper bucket scheme; use feature flag
  ydb/core/blobstorage/ut_vdisk/lib/test_huge.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge_ut.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap_ctx_ut.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap_ut.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugerecovery.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_public.cpp
Labels: not-for-changelog

#26096 Fix data race on Checksumming field in TGroupSessions
  ydb/core/blobstorage/dsproxy/group_sessions.cpp
  ydb/core/blobstorage/dsproxy/group_sessions.h
Labels: bugfix

#26193 Nemesis: send build and sanitizer to db
  .github/scripts/analytics/data_mart_queries/stability_aggregate_mart.sql
  .github/scripts/analytics/data_mart_queries/stability_per_run_mart.sql
  ydb/tests/olap/lib/results_processor.py
Labels: not-for-changelog

#25352 [DOCS RU] Alter database owner to
  ydb/docs/ru/core/yql/reference/syntax/alter_database/index.md
  ydb/docs/ru/core/yql/reference/syntax/alter_database/owner.md
  ydb/docs/ru/core/yql/reference/syntax/alter_database/toc_i.yaml
  ydb/docs/ru/core/yql/reference/syntax/alter_database/toc_p.yaml
  ydb/docs/ru/core/yql/reference/syntax/toc_i.yaml
Labels: documentation

#26215 Extract should delay helper for batch requests
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard__op_rows.cpp
  ydb/core/tx/datashard/datashard_impl.h
Labels: not-for-changelog

#26127 Update certification info in docs
  ydb/docs/ru/core/toc_i.yaml
Labels: documentation

#26269 Fix broken links in documentation
  ydb/docs/ru/core/integrations/migration/liquibase.md
  ydb/docs/ru/core/reference/ydbops/rolling-restart-scenario.md
  ydb/docs/ru/core/yql/reference/syntax/create-view.md
  ydb/docs/ru/core/yql/reference/syntax/drop-resource-pool.md
Labels: documentation

#26281 Darwin fixes for NFormats::NTestUtils
  ydb/core/kqp/common/result_set_format/kqp_result_set_arrow.cpp
Labels: not-for-changelog

#22275 bugfix prune out lambda in extract predicate in case of parameters
  ydb/core/kqp/common/simple/settings.h
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/executer_actor/kqp_executer.h
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_host.h
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_source.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.h
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/session_actor/kqp_query_state.cpp
  ydb/core/kqp/session_actor/kqp_query_state.h
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/query/kqp_params_ut.cpp
  ydb/core/kqp/ut/query/kqp_stats_ut.cpp
  ydb/core/protos/table_service_config.proto
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_coalesce-and-join.test_/query_4.plan
  ydb/tests/functional/suite_tests/canondata/test_postgres.TestPGSQL.test_sql_suite_plan-jointest_join4.test_/query_1.plan
Labels: not-for-changelog

#26235 Hide ydb yql command
  ydb/public/lib/ydb_cli/commands/ydb_root_common.cpp
Labels: not-for-changelog

#26233 Improve error handling in build stats
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_impl.h
Labels: not-for-changelog

#26188 EXT-1551. Remove obsolete UsageByActivity sensor from ActorSystem
  ydb/library/actors/core/actor.cpp
  ydb/library/actors/core/actor.h
  ydb/library/actors/core/defs.h
  ydb/library/actors/core/executor_pool_base.cpp
  ydb/library/actors/core/executor_pool_base.h
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/mailbox_lockfree.cpp
  ydb/library/actors/core/mon_stats.cpp
  ydb/library/actors/core/mon_stats.h
  ydb/library/actors/helpers/collector_counters.cpp
  ydb/library/actors/helpers/collector_counters.h
Labels: not-for-changelog

#26309 link ydb/core/kqp/tools/join_perf to tree
  ydb/core/kqp/ya.make
Labels: not-for-changelog

#26242 more inner join tests for scalar hash join
  ydb/library/yql/dq/comp_nodes/ut/dq_scalar_hash_join_ut.cpp
Labels: not-for-changelog

#25512 Topic APIs for metrics level
  ydb/core/persqueue/pqtablet/partition/partition_init.cpp
  ydb/core/persqueue/pqtablet/partition/user_info.cpp
  ydb/core/persqueue/public/constants.h
  ydb/core/persqueue/ut/counters_ut.cpp
  ydb/core/protos/pqconfig.proto
  ydb/core/ydb_convert/topic_description.cpp
  ydb/public/api/protos/ydb_common.proto
  ydb/public/api/protos/ydb_persqueue_v1.proto
  ydb/public/api/protos/ydb_topic.proto
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/topic/control_plane.h
  ydb/public/sdk/cpp/src/client/topic/impl/topic.cpp
  ydb/public/sdk/cpp/src/client/topic/impl/topic_impl.h
  ydb/public/sdk/cpp/tests/integration/topic/describe_topic.cpp
  ydb/public/sdk/cpp/tests/integration/topic/utils/describe.cpp
  ydb/services/lib/actors/pq_schema_actor.cpp
Labels: new-feature

#26328 Introduce TFastLookupUniqueList
  ydb/core/util/fast_lookup_unique_list.h
  ydb/core/util/fast_lookup_unique_list_ut.cpp
  ydb/core/util/ut/ya.make
Labels: improvement

#26117 Support for persistent row locks in LocalDB
  ydb/core/tablet_flat/flat_abi_evol.h
  ydb/core/tablet_flat/flat_database.cpp
  ydb/core/tablet_flat/flat_database.h
  ydb/core/tablet_flat/flat_dbase_naked.h
  ydb/core/tablet_flat/flat_iterator.h
  ydb/core/tablet_flat/flat_mem_eggs.h
  ydb/core/tablet_flat/flat_mem_iter.h
  ydb/core/tablet_flat/flat_mem_warm.h
  ydb/core/tablet_flat/flat_ops_compact.h
  ydb/core/tablet_flat/flat_page_data.h
  ydb/core/tablet_flat/flat_page_writer.h
  ydb/core/tablet_flat/flat_part_iter.h
  ydb/core/tablet_flat/flat_part_writer.h
  ydb/core/tablet_flat/flat_redo_layout.h
  ydb/core/tablet_flat/flat_redo_player.h
  ydb/core/tablet_flat/flat_redo_writer.h
  ydb/core/tablet_flat/flat_row_eggs.h
  ydb/core/tablet_flat/flat_row_state.h
  ydb/core/tablet_flat/flat_scan_feed.h
  ydb/core/tablet_flat/flat_scan_iface.h
  ydb/core/tablet_flat/flat_table.cpp
  ydb/core/tablet_flat/flat_table.h
  ydb/core/tablet_flat/flat_table_observer.h
  ydb/core/tablet_flat/test/libs/table/test_comp.h
  ydb/core/tablet_flat/test/libs/table/test_dbase.h
  ydb/core/tablet_flat/test/libs/table/test_steps.h
  ydb/core/tablet_flat/test/libs/table/wrap_dbase.h
  ydb/core/tablet_flat/test/tool/surg/main.cpp
  ydb/core/tablet_flat/ut/ut_charge.cpp
  ydb/core/tablet_flat/ut/ut_rowlocks.cpp
  ydb/core/tablet_flat/ut/ya.make
Labels: not-for-changelog

#24774 Topic key compaction counters
  ydb/core/http_proxy/ut/internal_counters.json
  ydb/core/persqueue/pqrb/read_balancer.cpp
  ydb/core/persqueue/pqrb/read_balancer.h
  ydb/core/persqueue/pqtablet/partition/partition.cpp
  ydb/core/persqueue/pqtablet/partition/partition.h
  ydb/core/persqueue/pqtablet/partition/partition_compactification.cpp
  ydb/core/persqueue/pqtablet/partition/partition_compactification.h
  ydb/core/persqueue/pqtablet/partition/partition_init.cpp
  ydb/core/persqueue/ut/common/pq_ut_common.cpp
  ydb/core/persqueue/ut/common/pq_ut_common.h
  ydb/core/persqueue/ut/counters_ut.cpp
  ydb/core/persqueue/ut/resources/counters_datastreams.html
  ydb/core/persqueue/ut/resources/counters_topics_extended.html
  ydb/core/persqueue/ut/ya.make
  ydb/core/protos/counters_pq.proto
  ydb/core/protos/pqconfig.proto
  ydb/services/persqueue_v1/persqueue_new_schemecache_ut.cpp
Labels: improvement

#26352 Small fixes of tests for Arrow result set
  ydb/core/kqp/ut/arrow/kqp_result_set_formats_ut.cpp
  ydb/core/kqp/ut/arrow/ya.make
  ydb/core/kqp/ya.make
Labels: not-for-changelog

#26342 Fix empty JSON keys verify
  ydb/core/formats/arrow/accessor/sub_columns/accessor.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: not-for-changelog

#26361 Fix state storage replicas selection
  ydb/core/base/statestorage.cpp
  ydb/core/base/statestorage_ringwalker.h
  ydb/core/base/statestorage_ut.cpp
Labels: bugfix

#26261 Fix empty payload deserialization
  ydb/core/persqueue/pqtablet/blob/blob.h
  ydb/core/persqueue/pqtablet/blob/blob_serialization.cpp
  ydb/core/persqueue/pqtablet/blob/blob_ut.cpp
  ydb/core/persqueue/pqtablet/blob/ut/ya.make
Labels: bugfix

#26282 add backoff on retry when s3 is unavailable
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/wrappers/abstract.h
  ydb/core/wrappers/retry_policy.cpp
  ydb/core/wrappers/retry_policy.h
  ydb/core/wrappers/unavailable_storage.h
Labels: not-for-changelog

#26288 [docs] Edited CTAS documentation
  ydb/docs/ru/core/yql/reference/syntax/create_table/as_select.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/index.md
Labels: documentation, external

#25452 Added docs for C++ SDK balancing policies
  ydb/docs/en/core/recipes/ydb-sdk/balancing-prefer-local.md
  ydb/docs/en/core/recipes/ydb-sdk/balancing-prefer-location.md
  ydb/docs/en/core/recipes/ydb-sdk/balancing-prefer-pile.md
  ydb/docs/en/core/recipes/ydb-sdk/balancing-random-choice.md
  ydb/docs/en/core/recipes/ydb-sdk/balancing.md
  ydb/docs/en/core/recipes/ydb-sdk/toc_i.yaml
  ydb/docs/ru/core/recipes/ydb-sdk/balancing-prefer-local.md
  ydb/docs/ru/core/recipes/ydb-sdk/balancing-prefer-location.md
  ydb/docs/ru/core/recipes/ydb-sdk/balancing-prefer-pile.md
  ydb/docs/ru/core/recipes/ydb-sdk/balancing-random-choice.md
  ydb/docs/ru/core/recipes/ydb-sdk/balancing.md
  ydb/docs/ru/core/recipes/ydb-sdk/toc_i.yaml
Labels: documentation

#26305 Add replicas specific volume option
  ydb/core/blobstorage/nodewarden/distconf.h
  ydb/core/blobstorage/nodewarden/distconf_generate.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_state_storage.cpp
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.cpp
  ydb/core/blobstorage/nodewarden/distconf_statestorage_config_generator.h
  ydb/core/blobstorage/nodewarden/distconf_ut.cpp
  ydb/core/cms/config.h
  ydb/core/cms/sentinel.cpp
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/core/protos/cms.proto
  ydb/tests/functional/config/test_distconf_sentinel_node_status.py
Labels: not-for-changelog

#23788 Olap s3 import export new test cases
  ydb/tests/olap/common/ydb_client.py
  ydb/tests/olap/s3_import/test_simple_table.py
  ydb/tests/olap/s3_import/ya.make
Labels: not-for-changelog

#26264 Simplify build stats by removing obtain-release resources on each pause
  ydb/core/tx/datashard/datashard__stats.cpp
Labels: not-for-changelog

#26353 Reuse common space checks for S3 upload rows
  ydb/core/tx/datashard/datashard.cpp
  ydb/core/tx/datashard/datashard.h
  ydb/core/tx/datashard/datashard__op_rows.cpp
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_overload.cpp
  ydb/core/tx/datashard/import_s3.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
  ydb/core/tx/tx_proxy/upload_rows_common_impl.h
Labels: not-for-changelog

#26412 YQL-20425: Move RH Hash Map to new api
  ydb/core/kqp/tools/combiner_perf/hashmaps.h
  ydb/library/formats/arrow/replace_key.h
  ydb/library/yql/dq/comp_nodes/dq_hash_combine.cpp
Labels: not-for-changelog

#26440 drop old datetime udf
  ydb/library/yql/udfs/common/datetime/datetime_udf.cpp
  ydb/library/yql/udfs/common/datetime/ya.make
  ydb/library/yql/udfs/common/ya.make
Labels: not-for-changelog

#26345 Move LWTRACK before co_await to prevent ResponseEv race
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/ut/kqp_executer_ut.cpp
  ydb/core/kqp/executer_actor/ut/ya.make
Labels: bugfix

#26213 YQ-4750 supported solomon writing in KQP
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/gateway/behaviour/streaming_query/optimization.cpp
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/opt/kqp_opt_effects.cpp
  ydb/core/kqp/ut/federated_query/common/common.cpp
  ydb/core/kqp/ut/federated_query/datastreams/datastreams_ut.cpp
  ydb/core/kqp/ut/federated_query/datastreams/ya.make
  ydb/library/testlib/solomon_helpers/solomon_emulator_helpers.cpp
  ydb/library/testlib/solomon_helpers/solomon_emulator_helpers.h
  ydb/library/testlib/solomon_helpers/ya.make
  ydb/library/testlib/ya.make
  ydb/library/yql/providers/solomon/actors/ut/dq_solomon_write_actor_ut.cpp
  ydb/library/yql/providers/solomon/actors/ut/ut_helpers.cpp
  ydb/library/yql/providers/solomon/actors/ut/ut_helpers.h
  ydb/library/yql/providers/solomon/actors/ut/ya.make
  ydb/library/yql/providers/solomon/expr_nodes/yql_solomon_expr_nodes.json
  ydb/library/yql/providers/solomon/provider/yql_solomon_datasink_type_ann.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_physical_optimize.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_provider.h
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_accessor_client.cpp
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: new-feature

#26441 Fix BlobScrubbing UT
  .github/config/muted_ya.txt
  ydb/core/blobstorage/ut_blobstorage/scrub.cpp
Labels: not-for-changelog

#26460 Fix view broken link
  ydb/docs/en/core/yql/reference/syntax/create-view.md
Labels: documentation

#26340 Mark sorting when we made it up as fake
  ydb/core/tx/columnshard/engines/reader/abstract/read_metadata.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/scanner.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
Labels: bugfix

#26478 Fix HugeCluster::AllToAll test
  .github/config/muted_ya.txt
  ydb/library/actors/interconnect/ut_huge_cluster/huge_cluster.cpp
Labels: not-for-changelog

#26451 Empty blobs for compaction
  ydb/core/persqueue/pqtablet/partition/partition_compaction.cpp
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
Labels: not-for-changelog

#26367 overload diagnostics
  ydb/core/tx/columnshard/engines/storage/optimizer/abstract/optimizer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/level/abstract.h
Labels: not-for-changelog

#26489 Fix upsert to table with unique index
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_upsert_index.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
Labels: bugfix

#26481 Add prefixed vector index and vector index update to compatibility tests
  ydb/tests/compatibility/test_vector_index.py
Labels: not-for-changelog

#26319 Solomon external data source bugfixes
  ydb/library/yql/providers/solomon/actors/dq_solomon_read_actor.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
  ydb/library/yql/providers/solomon/provider/yql_solomon_load_meta.cpp
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_accessor_client.cpp
  ydb/library/yql/tests/sql/solomon/canondata/test.test_solomon-InvalidProject-_/extracted
  ydb/tests/fq/solomon/canondata/test.test_solomon-InvalidProject-_/extracted
  ydb/tests/solomon/reading/base.py
  ydb/tests/solomon/reading/basic_reading.py
  ydb/tests/solomon/reading/listing_paging.py
  ydb/tests/solomon/reading/settings_validation.py
Labels: not-for-changelog

#26493 Some fixes in Bridge GRPC disconnect
  ydb/core/driver_lib/run/grpc_servers_manager.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/driver_lib/run/ya.make
  ydb/core/grpc_services/rpc_bridge.cpp
  ydb/tests/functional/bridge/test_bridge.py
Labels: not-for-changelog

#26510 Make it possible to backup out-of-range decimal values
  ydb/core/tx/datashard/type_serialization.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
Labels: bugfix

#26479 viewer stress test
  ydb/tests/stress/viewer/__main__.py
  ydb/tests/stress/viewer/tests/test_workload.py
  ydb/tests/stress/viewer/tests/ya.make
  ydb/tests/stress/viewer/workload/__init__.py
  ydb/tests/stress/viewer/workload/ya.make
  ydb/tests/stress/viewer/ya.make
Labels: not-for-changelog

#26531 Fix HugeBlobOnlineSizeChange test timeout
  .github/config/muted_ya.txt
  ydb/core/blobstorage/ut_blobstorage/huge.cpp
Labels: not-for-changelog

#26541 [ICRDMA] Set mlock limits for ci
  ydb/ci/gh-runner-image/image.pkr.hcl
Labels: not-for-changelog

#26551 YQ-4780 fixed fault in node service on kikimr process stop
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/node_service/kqp_node_service.h
  ydb/core/kqp/node_service/kqp_node_state.h
Labels: bugfix

#26522 Solomon data source: additional time range validation & stats collection
  ydb/library/yql/providers/solomon/actors/dq_solomon_metrics_queue.cpp
  ydb/library/yql/providers/solomon/actors/dq_solomon_read_actor.cpp
  ydb/library/yql/providers/solomon/events/events.h
  ydb/library/yql/providers/solomon/proto/metrics_queue.proto
  ydb/library/yql/providers/solomon/provider/yql_solomon_dq_integration.cpp
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_accessor_client.cpp
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_client_utils.cpp
  ydb/library/yql/providers/solomon/solomon_accessor/client/solomon_client_utils.h
  ydb/tests/solomon/reading/base.py
  ydb/tests/solomon/reading/settings_validation.py
Labels: not-for-changelog

#26351 support consumer's availability_period in the ydb_cli
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/commands/ydb_service_scheme.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_topic.h
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
Labels: not-for-changelog
