Repository ydb-platform/ydb, pull requests merged in 2025-02, with the labels that each got.

#13809 Fix bugs in global kmeans
  ydb/core/kqp/opt/logical/kqp_opt_log_indexes.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/ut/indexes/kqp_indexes_ut.cpp
  ydb/core/scheme/scheme_tablecell.cpp
  ydb/core/scheme/scheme_tablecell.h
  ydb/core/tx/datashard/kmeans_helper.h
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
Labels: not-for-changelog

#14012 correct scripts initialization
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/context.h
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/context.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/context.h
Labels: improvement

#13666 Add docs for backup checksums
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/file_structure.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_import.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/file-structure.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/import-s3.md
Labels: documentation

#14020 BulkUpsert - update note
  ydb/docs/en/core/dev/batch-upload.md
  ydb/docs/ru/core/dev/batch-upload.md
Labels: documentation

#14105 Increment YDB CLI version to 2.19.0
  ydb/apps/ydb/CHANGELOG.md
  ydb/apps/ydb/version.txt
Labels: area/cli, not-for-changelog

#13969 Use the root domain as a database for all operations with users and groups
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/tests/functional/tenants/test_users_groups_with_acl.py
  ydb/tests/functional/tenants/ya.make
Labels: not-for-changelog

#13807 new documentation on type inferring with fq
  ydb/docs/en/core/concepts/federated_query/s3/external_data_source.md
  ydb/docs/ru/core/concepts/federated_query/s3/external_data_source.md
Labels: documentation

#13880 Ydbdocs 1008 transactions topics tables en
  ydb/docs/en/core/concepts/_includes/transactions.md
  ydb/docs/en/core/concepts/topic.md
  ydb/docs/en/core/reference/ydb-sdk/topic.md
Labels: documentation

#14055 YQ-4071 Fix exception handling in topic session
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#14058 YQ: Added force refresh by reconnects in topic_session
  ydb/core/fq/libs/row_dispatcher/format_handler/format_handler.cpp
  ydb/core/fq/libs/row_dispatcher/format_handler/format_handler.h
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#13368 add notification about close reader
  ydb/docs/en/core/reference/ydb-sdk/topic.md
  ydb/docs/ru/core/reference/ydb-sdk/topic.md
Labels: documentation

#14113 YQ-3924 Add CA notify to update SourceCpu
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
Labels: not-for-changelog

#14047 Fix flaky test ShouldRollbackTransactionWhenCheckFails2
  ydb/core/fq/libs/ydb/ut/ydb_ut.cpp
Labels: not-for-changelog

#13867 Add node interlace in TScore for group mapper
  ydb/core/mind/bscontroller/group_layout_checker.h
  ydb/core/mind/bscontroller/group_mapper.cpp
  ydb/core/mind/bscontroller/group_mapper_ut.cpp
Labels: bugfix

#14118 TOPIC: do not save topic attributes to backups
  ydb/library/backup/backup.cpp
Labels: not-for-changelog

#14075 Feature flag EnableStrictAclCheck
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/schemeshard/schemeshard__operation_alter_login.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_modify_acl.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.cpp
  ydb/core/tx/schemeshard/ut_helpers/test_env.h
  ydb/core/tx/schemeshard/ut_login/ut_login.cpp
Labels: experimental-feature

#14086 YDB FQ: switch connector integration tests to LARGE
  ydb/core/external_sources/hive_metastore/ut/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/clickhouse/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/ms_sql_server/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/mysql/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/oracle/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/postgresql/ya.make
  ydb/library/yql/providers/generic/connector/tests/datasource/ydb/ya.make
  ydb/library/yql/providers/generic/connector/tests/join/ya.make
  ydb/tests/fq/generic/analytics/ya.make
  ydb/tests/fq/generic/streaming/ya.make
Labels: not-for-changelog

#13790 Remove unsupported read replicas settings from an error message
  ydb/core/kqp/provider/yql_kikimr_gateway.cpp
Labels: not-for-changelog

#14060 YQ-4053 support parallel s3 import
  ydb/core/kqp/ut/federated_query/s3/kqp_s3_plan_ut.cpp
  ydb/library/yql/providers/s3/actors/yql_s3_write_actor.cpp
  ydb/library/yql/providers/s3/provider/yql_s3_phy_opt.cpp
Labels: improvement

#13606 Test create users on tenant
  ydb/tests/functional/tenants/test_create_users.py
  ydb/tests/functional/tenants/ya.make
Labels: not-for-changelog

#14035 fix flaky tests in ydb workload
  ydb/apps/ydb/ut/workload-topic.cpp
  ydb/apps/ydb/ut/workload-transfer-topic-to-table.cpp
Labels: not-for-changelog

#14101 Fix deadlock
  ydb/library/yql/yt/native/plugin.cpp
Labels: bugfix

#13890 handle s3 errors in GC
  ydb/core/kqp/ut/common/columnshard.cpp
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/tx/columnshard/blobs_action/tier/common.cpp
  ydb/core/tx/columnshard/blobs_action/tier/common.h
  ydb/core/tx/columnshard/blobs_action/tier/gc.h
  ydb/core/tx/columnshard/blobs_action/tier/gc_actor.cpp
  ydb/core/tx/columnshard/blobs_action/tier/gc_actor.h
  ydb/core/tx/columnshard/blobs_action/tier/storage.cpp
  ydb/core/tx/columnshard/blobs_action/tier/storage.h
  ydb/core/tx/columnshard/blobs_action/tier/ya.make
  ydb/core/tx/columnshard/hooks/abstract/abstract.h
  ydb/core/tx/columnshard/hooks/testing/controller.h
Labels: bugfix

#14141 core/testlib: unify some client operation methods
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
Labels: not-for-changelog

#14080 unify logic around executers
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_planner.cpp
  ydb/core/kqp/executer_actor/kqp_planner.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.h
  ydb/core/kqp/ut/scan/kqp_scan_ut.cpp
Labels: not-for-changelog

#13323 Add data cleanup logic in localDB
  ydb/core/base/tablet.h
  ydb/core/tablet/tablet_sys.cpp
  ydb/core/tablet/tablet_sys.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_executor_data_cleanup_logic.cpp
  ydb/core/tablet_flat/flat_executor_data_cleanup_logic.h
  ydb/core/tablet_flat/flat_executor_gclogic.cpp
  ydb/core/tablet_flat/flat_executor_gclogic.h
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_executor_ut_common.h
  ydb/core/tablet_flat/tablet_flat_executor.cpp
  ydb/core/tablet_flat/tablet_flat_executor.h
  ydb/core/tablet_flat/test/libs/exec/dummy.h
  ydb/core/tablet_flat/test/libs/exec/events.h
  ydb/core/tablet_flat/test/libs/exec/helper.h
  ydb/core/tablet_flat/test/libs/exec/nanny.h
  ydb/core/tablet_flat/test/libs/exec/runner.h
  ydb/core/tablet_flat/test/libs/exec/storage.h
  ydb/core/tablet_flat/test/libs/exec/warden.h
  ydb/core/tablet_flat/ut/ut_data_cleanup.cpp
  ydb/core/tablet_flat/ut/ya.make
  ydb/core/tablet_flat/ya.make
Labels: not-for-changelog

#14119 TOPICS: ydb tools restore support
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/restore_impl.h
Labels: not-for-changelog

#14040 signals for stages of column engine changes
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.cpp
  ydb/core/tx/columnshard/engines/changes/abstract/abstract.h
  ydb/core/tx/columnshard/engines/changes/abstract/ya.make
  ydb/core/tx/columnshard/engines/changes/counters/changes.cpp
  ydb/core/tx/columnshard/engines/changes/counters/changes.h
  ydb/core/tx/columnshard/engines/changes/counters/ya.make
Labels: not-for-changelog

#13664 YQ-3858 RowDispatcher / Add new public metrics
  ydb/core/fq/libs/compute/common/ut/utils_ut.cpp
  ydb/core/fq/libs/compute/common/utils.cpp
  ydb/core/fq/libs/row_dispatcher/events/topic_session_stats.h
  ydb/core/fq/libs/row_dispatcher/probes.h
  ydb/core/fq/libs/row_dispatcher/protos/events.proto
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
  ydb/library/yql/dq/actors/compute/dq_async_compute_actor.cpp
  ydb/library/yql/dq/actors/compute/dq_compute_actor_impl.h
  ydb/library/yql/dq/actors/compute/dq_compute_actor_stats.cpp
  ydb/library/yql/dq/actors/protos/dq_stats.proto
  ydb/library/yql/dq/runtime/dq_async_stats.h
  ydb/library/yql/providers/dq/actors/task_controller_impl.h
  ydb/library/yql/providers/dq/counters/task_counters.h
  ydb/library/yql/providers/dq/runtime/task_command_executor.cpp
  ydb/library/yql/providers/dq/task_runner/tasks_runner_pipe.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#14156 Fixed CMake build for SDK test server_restart
  ydb/public/sdk/cpp/tests/integration/server_restart/main.cpp
Labels: not-for-changelog

#13834 DDL for ALTER OBJECT TYPE TABLESTORE
  ydb/core/kqp/gateway/behaviour/tablestore/manager.cpp
  ydb/core/kqp/gateway/behaviour/tablestore/manager.h
  ydb/core/kqp/gateway/behaviour/tablestore/operations/abstract.h
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: improvement

#14160 The test is temporarily disabled
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
Labels: bugfix

#14158 TOPIC: add tests for local backups
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#14159 VIEW: refactoring in tests, remove an unused feature flag
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#14165 Little refactoring & cosmetic changes
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
Labels: not-for-changelog

#14125 use seqno to dedup drain requests from root hive to tenant hive
  ydb/core/mind/hive/drain.cpp
  ydb/core/mind/hive/hive_impl.cpp
  ydb/core/mind/hive/hive_impl.h
  ydb/core/mind/hive/hive_schema.h
  ydb/core/mind/hive/hive_ut.cpp
  ydb/core/mind/hive/node_info.h
  ydb/core/mind/hive/tx__load_everything.cpp
  ydb/core/mind/hive/tx__switch_drain.cpp
  ydb/core/protos/hive.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_hive_/flat_hive.schema
Labels: improvement

#14167 [docs] fix mistype in changelog-cli.md
  ydb/docs/ru/core/changelog-cli.md
Labels: documentation

#14056 Return PQRB tablet in UI
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/tests/test.py
  ydb/core/viewer/viewer_tabletinfo.h
Labels: improvement

#13965 En version of Airflow docs
  ydb/docs/en/core/integrations/index.md
  ydb/docs/en/core/integrations/orchestration/_assets/airflow_dag.png
  ydb/docs/en/core/integrations/orchestration/_assets/ydb_connection.png
  ydb/docs/en/core/integrations/orchestration/_includes/toc-table.md
  ydb/docs/en/core/integrations/orchestration/airflow.md
  ydb/docs/en/core/integrations/orchestration/index.md
  ydb/docs/en/core/integrations/orchestration/toc-orchestration.yaml
  ydb/docs/en/core/integrations/toc_i.yaml
Labels: documentation

#14169 improve handling of query cancelling
  ydb/core/viewer/viewer_query.h
Labels: area/ui, bugfix

#14122 FQ: add commit tx in test
  ydb/core/fq/libs/ydb/ut/ydb_ut.cpp
Labels: not-for-changelog

#14179 Commit metrics by timer
  ydb/core/mind/bscontroller/bsc.cpp
  ydb/core/mind/bscontroller/disk_metrics.cpp
  ydb/core/mind/bscontroller/impl.h
Labels: not-for-changelog

#14168 Fix schedule actor events for self
  ydb/core/blobstorage/vdisk/skeleton/skeleton_vpatch_actor_ut.cpp
  ydb/library/actors/core/actor.cpp
Labels: new-feature

#14115 Always call LogPrefix under Lock
  ydb/public/sdk/cpp/src/client/topic/impl/write_session_impl.cpp
  ydb/public/sdk/cpp/src/client/topic/impl/write_session_impl.h
Labels: bugfix

#14178 YQ-4085 FQ: Add partition id check in row dispatcher
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/core/fq/libs/row_dispatcher/ut/row_dispatcher_ut.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_read_actor_base.cpp
Labels: not-for-changelog

#14190 [ydbd_slice] fixed actor_system_config -> sys
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-2-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-4-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-8-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/mirror-3-dc-3-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/mirror-3-dc-9-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/none-1-node.yaml
Labels: bugfix

#14182 Fix mediator merge for out-of-order transactions
  ydb/core/tx/mediator/mediator_ut.cpp
  ydb/core/tx/mediator/tablet_queue.cpp
Labels: not-for-changelog

#14161 make throttling inplaced size parameters configurable depending on disk type
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_overload_handler.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#13929 Kafka api better client errors
  ydb/core/kafka_proxy/actors/actors.h
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/public/api/protos/persqueue_error_codes_v1.proto
  ydb/services/persqueue_v1/actors/persqueue_utils.cpp
  ydb/services/persqueue_v1/actors/read_init_auth_actor.cpp
Labels: improvement

#14196 Fix docs/en/core/yql/reference/index.md
  ydb/docs/en/core/yql/reference/index.md
Labels: documentation, external

#14208 Delete rows with decimal in PK
  ydb/core/kqp/ut/query/kqp_params_ut.cpp
  ydb/core/tx/datashard/datashard_kqp_delete_rows.cpp
Labels: not-for-changelog

#14200 Drop excess assumptions in KQP peephole optimizer
  ydb/core/kqp/opt/peephole/kqp_opt_peephole.cpp
Labels: improvement

#14185 TOPIC: drop topics if an error has occured on ydb tools restore
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
Labels: not-for-changelog

#14110 List all topics in kafka metaRequest
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_metadata_actor.h
  ydb/core/kafka_proxy/ut/metarequest_ut.cpp
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/list_all_topics_actor.cpp
  ydb/core/persqueue/list_all_topics_actor.h
  ydb/core/persqueue/ut/list_all_topics_ut.cpp
  ydb/core/persqueue/ut/ya.make
  ydb/core/persqueue/ya.make
  ydb/services/datastreams/datastreams_proxy.cpp
Labels: new-feature

#14215 fix macro usage for win build
  ydb/core/wrappers/unavailable_storage.h
Labels: not-for-changelog

#14206 add dry run mode to vdisk throttling
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_overload_handler.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#14199 KESUS: local backups (ydb tools dump / restore)
  ydb/library/backup/backup.cpp
  ydb/library/backup/db_iterator.h
  ydb/library/backup/ya.make
  ydb/public/lib/ydb_cli/dump/files/files.cpp
  ydb/public/lib/ydb_cli/dump/files/files.h
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/restore_impl.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/coordination/coordination.h
  ydb/public/sdk/cpp/src/client/coordination/coordination.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#14204 Fix find login provider with empty database
  ydb/core/security/ticket_parser_impl.h
Labels: not-for-changelog

#14136 Doc fixes for Import 714
  ydb/docs/ru/core/troubleshooting/performance/schemas/overloaded-shards.md
  ydb/docs/ru/core/yql/reference/_includes/intro.md
  ydb/docs/ru/core/yql/reference/index.md
Labels: documentation

#14078 feature flags: enable EnableAlterDatabaseCreateHiveFirst
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/coordinator/coordinator_ut.cpp
  ydb/core/tx/schemeshard/ut_serverless/ut_serverless.cpp
  ydb/core/tx/schemeshard/ut_serverless/ya.make
Labels: not-for-changelog

#14222 YDB FQ: enable Timestamp pushdown for Generic provider
  ydb/library/yql/providers/generic/provider/yql_generic_physical_opt.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_predicate_pushdown.cpp
Labels: new-feature

#14212 Fixed SDK CMake build in topics
  ydb/public/sdk/cpp/src/client/topic/impl/topic.cpp
Labels: not-for-changelog

#14162 Refactor bsconfig SDK client
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/bsconfig/storage_config.h
  ydb/public/sdk/cpp/src/client/bsconfig/storage_config.cpp
Labels: not-for-changelog

#14233 fix uninitialized value
  ydb/core/mind/hive/node_info.h
Labels: not-for-changelog

#14189 Add CMS client to CPP SDK
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/cms/cms.h
  ydb/public/sdk/cpp/src/client/cms/cms.cpp
  ydb/public/sdk/cpp/src/client/cms/ya.make
  ydb/public/sdk/cpp/src/client/ya.make
Labels: not-for-changelog

#14236 Purge YQL_UDF_YDB_TEST macro usage
  ydb/library/yql/udfs/common/clickhouse/client/test/ya.make
  ydb/library/yql/udfs/common/datetime/test/ya.make
  ydb/library/yql/udfs/common/knn/test/ya.make
  ydb/library/yql/udfs/common/roaring/test/ya.make
Labels: improvement

#14229 Introduce scheme operation factory
  ydb/apps/ydbd/main.cpp
  ydb/apps/ydbd/ya.make
  ydb/core/base/appdata_fwd.h
  ydb/core/driver_lib/run/factories.h
  ydb/core/driver_lib/run/run.cpp
  ydb/core/testlib/actors/test_runtime.cpp
  ydb/core/testlib/basics/appdata.cpp
  ydb/core/testlib/basics/appdata.h
  ydb/core/testlib/basics/ya.make
  ydb/core/tx/schemeshard/schemeshard__operation.cpp
  ydb/core/tx/schemeshard/schemeshard_operation_factory.h
Labels: not-for-changelog

#14246 don't require token for login page
  ydb/core/driver_lib/run/run.cpp
Labels: bugfix

#11695 Edited the Error Handling article
  ydb/docs/_assets/tags.css
  ydb/docs/en/core/dev/getting-started.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/error_handling.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/index.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tags.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tooltips/condretryable.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tooltips/fast_backoff.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tooltips/instant.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tooltips/nonretryable.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tooltips/retryable.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/tooltips/slow_backoff.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/ydb-status-codes-note.md
  ydb/docs/en/core/reference/ydb-sdk/error_handling.md
  ydb/docs/en/core/reference/ydb-sdk/grpc-status-codes.md
  ydb/docs/en/core/reference/ydb-sdk/toc_i.yaml
  ydb/docs/en/core/reference/ydb-sdk/ydb-status-codes.md
  ydb/docs/ru/core/dev/getting-started.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/error_handling.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tags.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tooltips/condretryable.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tooltips/fast_backoff.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tooltips/instant.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tooltips/nonretryable.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tooltips/retryable.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/tooltips/slow_backoff.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/ydb-status-codes-note.md
  ydb/docs/ru/core/reference/ydb-sdk/error_handling.md
  ydb/docs/ru/core/reference/ydb-sdk/grpc-status-codes.md
  ydb/docs/ru/core/reference/ydb-sdk/index.md
  ydb/docs/ru/core/reference/ydb-sdk/toc_i.yaml
  ydb/docs/ru/core/reference/ydb-sdk/ydb-status-codes.md
Labels: documentation

#7413 hive docs
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/contributor/general-schema.md
  ydb/docs/ru/core/contributor/hive.md
  ydb/docs/ru/core/contributor/toc_i.yaml
Labels: documentation

#14219 Increase MaxTableKeyColumns to 30
  ydb/core/tx/schemeshard/schemeshard_types.h
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
Labels: improvement

#14041 add tablet start time sensor
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor.h
  ydb/core/tablet_flat/flat_executor_counters.h
  ydb/core/tablet_flat/tablet_flat_executed.cpp
  ydb/core/tablet_flat/tablet_flat_executed.h
  ydb/core/tablet_flat/tablet_flat_executor.h
Labels: new-feature

#14250 More PK diversity in OLTP stress test
  ydb/tests/stress/oltp_workload/__main__.py
Labels: not-for-changelog

#14223 Use an empty AckTo for plans from mediator to tablets
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/tx/columnshard/columnshard__plan_step.cpp
  ydb/core/tx/datashard/datashard__plan_step.cpp
  ydb/core/tx/mediator/mediator_ut.cpp
  ydb/core/tx/mediator/tablet_queue.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_side_effects.cpp
Labels: not-for-changelog

#14228 YDB FQ: introduce new `TGenTable` expr node
  ydb/library/yql/providers/generic/expr_nodes/yql_generic_expr_nodes.json
  ydb/library/yql/providers/generic/provider/yql_generic_datasource.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_datasource_type_ann.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_dq_integration.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
  ydb/library/yql/providers/generic/provider/yql_generic_physical_opt.cpp
Labels: improvement

#14230 replay fixes (ignore ast query type as it misses parameters and avoid symbols duplication with external so)
  ydb/tools/query_replay_yt/common_deps.inc
  ydb/tools/query_replay_yt/main.cpp
Labels: not-for-changelog

#14265 fix scan scripts initialization
  ydb/core/tx/columnshard/engines/reader/common_reader/iterator/fetching.h
Labels: bugfix

#14273 Little cosmetic changes
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/restore_import_data.cpp
Labels: not-for-changelog

#13937 PQ tablet removes blobs asynchronously
  ydb/core/persqueue/blob_refcounter.h
  ydb/core/persqueue/events/internal.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/subscriber.cpp
  ydb/core/persqueue/subscriber.h
  ydb/core/persqueue/ut/common/pq_ut_common.cpp
  ydb/core/persqueue/ut/common/pq_ut_common.h
  ydb/core/persqueue/ut/partition_ut.cpp
  ydb/core/persqueue/ut/pq_ut.cpp
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
Labels: new-feature

#14264 counterts for throttling params; consistent naming
  ydb/core/blobstorage/nodewarden/node_warden_impl.cpp
  ydb/core/blobstorage/nodewarden/node_warden_impl.h
  ydb/core/blobstorage/nodewarden/node_warden_vdisk.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_config.h
  ydb/core/blobstorage/vdisk/common/vdisk_mongroups.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_overload_handler.cpp
  ydb/core/protos/config.proto
Labels: not-for-changelog

#14284 Tests for Decimal PK
  ydb/core/tx/replication/service/table_writer_ut.cpp
  ydb/core/tx/schemeshard/ut_restore/ut_restore.cpp
Labels: not-for-changelog

#14291 Update CODEOWNERS
  .github/CODEOWNERS
Labels: not-for-changelog

#14294 Increment YDB C++ SDK version to 3.1.0
  ydb/public/sdk/cpp/src/client/resources/ydb_sdk_version.txt
Labels: not-for-changelog

#14295 Added a condition for the corp audience
  ydb/docs/ru/core/concepts/glossary.md
Labels: documentation

#14286 Fix for Decimal PK in CDC
  ydb/core/tx/datashard/datashard_ut_change_exchange.cpp
  ydb/core/tx/scheme_board/cache.cpp
Labels: not-for-changelog

#13816 remove kafka cloud role check
  ydb/core/kafka_proxy/actors/kafka_sasl_auth_actor.cpp
  ydb/library/testlib/service_mocks/access_service_mock.h
  ydb/services/persqueue_v1/actors/persqueue_utils.h
Labels: not-for-changelog

#13492 Add examples and update constraints for Kafka API
  ydb/docs/_includes/bash/kafka-api-console-read-no-auth.md
  ydb/docs/_includes/bash/kafka-api-console-read-with-sasl-creds-on-prem.md
  ydb/docs/_includes/bash/kafka-api-console-write-no-auth.md
  ydb/docs/_includes/bash/kafka-api-kcat-read-no-auth.md
  ydb/docs/_includes/bash/kafka-api-kcat-read-with-sasl-creds-on-prem.md
  ydb/docs/_includes/bash/kafka-api-kcat-write-no-auth.md
  ydb/docs/_includes/java/kafka-api-flink-read-no-auth.md
  ydb/docs/_includes/java/kafka-api-flink-write-no-auth.md
  ydb/docs/_includes/java/kafka-api-java-read-no-auth.md
  ydb/docs/_includes/java/kafka-api-java-read-with-sasl-creds-on-prem.md
  ydb/docs/_includes/java/kafka-api-java-write-no-auth.md
  ydb/docs/_includes/java/kafka-api-spark-read-no-auth.md
  ydb/docs/_includes/java/kafka-api-spark-write-no-auth.md
  ydb/docs/_includes/logs-to-kafka/kafka-api-fluent-bit.md
  ydb/docs/_includes/logs-to-kafka/kafka-api-logstash.md
  ydb/docs/en/core/reference/kafka-api/_includes/flink-constraints.md
  ydb/docs/en/core/reference/kafka-api/_includes/flink-version-notice.md
  ydb/docs/en/core/reference/kafka-api/_includes/kafka-console-utillities-java23-fix.md
  ydb/docs/en/core/reference/kafka-api/_includes/spark-constraints.md
  ydb/docs/en/core/reference/kafka-api/_includes/spark-version-notice.md
  ydb/docs/en/core/reference/kafka-api/auth.md
  ydb/docs/en/core/reference/kafka-api/constraints.md
  ydb/docs/en/core/reference/kafka-api/examples.md
  ydb/docs/en/core/reference/kafka-api/toc_i.yaml
  ydb/docs/ru/core/reference/kafka-api/_includes/flink-constraints.md
  ydb/docs/ru/core/reference/kafka-api/_includes/flink-version-notice.md
  ydb/docs/ru/core/reference/kafka-api/_includes/kafka-console-utillities-java23-fix.md
  ydb/docs/ru/core/reference/kafka-api/_includes/spark-constraints.md
  ydb/docs/ru/core/reference/kafka-api/_includes/spark-version-notice.md
  ydb/docs/ru/core/reference/kafka-api/auth.md
  ydb/docs/ru/core/reference/kafka-api/constraints.md
  ydb/docs/ru/core/reference/kafka-api/examples.md
  ydb/docs/ru/core/reference/kafka-api/index.md
  ydb/docs/ru/core/reference/kafka-api/read-write.md
  ydb/docs/ru/core/reference/kafka-api/toc_i.yaml
Labels: documentation

#14279 YQ-4092 KqpRun improve tenants flags
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/proto/storage_meta.proto
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: improvement

#14288 YQ-4091 Delete public metrics if automatic query
  ydb/core/fq/libs/actors/pending_fetcher.cpp
Labels: not-for-changelog

#14261 YQ-4091 Fix log message size in coordinator
  ydb/core/fq/libs/row_dispatcher/coordinator.cpp
Labels: not-for-changelog

#14275 Stream write setting
  ydb/core/kqp/common/kqp_yql.cpp
  ydb/core/kqp/common/kqp_yql.h
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/host/kqp_type_ann.cpp
  ydb/core/kqp/opt/kqp_opt.cpp
  ydb/core/kqp/opt/kqp_opt.h
  ydb/core/kqp/opt/kqp_opt_effects.cpp
  ydb/core/kqp/opt/kqp_opt_kql.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#14312 Update muted_ya.txt
  .github/config/muted_ya.txt
Labels: not-for-changelog

#14296 remove enable sequences & enable default values feature flags
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/host/kqp_gateway_proxy.cpp
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/provider/yql_kikimr_type_ann.cpp
  ydb/core/kqp/ut/opt/kqp_returning_ut.cpp
  ydb/core/kqp/ut/pg/kqp_pg_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_constraints_ut.cpp
  ydb/core/protos/table_service_config.proto
  ydb/core/tx/datashard/ut_sequence/datashard_ut_sequence.cpp
Labels: not-for-changelog

#14280 Catching exceptions
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/restore_import_data.cpp
  ydb/public/lib/ydb_cli/dump/util/util.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/types/status/status.h
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: bugfix

#14316 switch default cost based optimization level -> 2
  ydb/tools/query_replay_yt/query_compiler.cpp
Labels: not-for-changelog

#14267 Avoid committed and removed volatile txs in the TxMap
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_pipeline.cpp
  ydb/core/tx/datashard/datashard_ut_volatile.cpp
  ydb/core/tx/datashard/volatile_tx.cpp
  ydb/core/tx/datashard/volatile_tx.h
Labels: not-for-changelog

#14309 Explicit antlr3 mode for KQP
  ydb/core/kqp/host/kqp_translate.cpp
Labels: not-for-changelog

#14257 [docs] add 24.3.11.14 to documentation
  ydb/docs/en/core/changelog-server.md
  ydb/docs/en/core/downloads/_includes/server/docker.md
  ydb/docs/en/core/downloads/_includes/server/linux.md
  ydb/docs/en/core/downloads/_includes/server/source_code.md
  ydb/docs/ru/core/changelog-server.md
  ydb/docs/ru/core/downloads/_includes/server/docker.md
  ydb/docs/ru/core/downloads/_includes/server/linux.md
  ydb/docs/ru/core/downloads/_includes/server/source_code.md
Labels: documentation

#14311 additional logging on verify
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
Labels: improvement

#14318 Test CreatePersQueueGroup with decimal PK
  ydb/core/tx/schemeshard/ut_base/ut_base.cpp
Labels: not-for-changelog

#14148 build.sh has been improved
  ydb/docs/build.sh
Labels: documentation

#13717 Docs: Add information about 'WITH' in CREATE GROUP
  ydb/docs/en/core/yql/reference/syntax/create-group.md
  ydb/docs/ru/core/yql/reference/syntax/create-group.md
Labels: documentation

#14277 don't limit volume of evicted data
  ydb/core/tx/columnshard/counters/aggregation/table_stats.h
  ydb/core/tx/columnshard/engines/column_engine.h
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
Labels: improvement

#14249 Remove redundant TActorContext passing
  ydb/core/keyvalue/keyvalue_flat_impl.h
  ydb/core/keyvalue/keyvalue_helpers.cpp
  ydb/core/keyvalue/keyvalue_helpers.h
  ydb/core/keyvalue/keyvalue_simple_db.h
  ydb/core/keyvalue/keyvalue_simple_db_flat.cpp
  ydb/core/keyvalue/keyvalue_simple_db_flat.h
  ydb/core/keyvalue/keyvalue_state.cpp
  ydb/core/keyvalue/keyvalue_state.h
  ydb/core/keyvalue/keyvalue_state_collect.cpp
  ydb/core/keyvalue/keyvalue_storage_request.cpp
Labels: area/blobstorage, not-for-changelog

#14307 YDB FQ: simplify `yql_generic_load_meta.cpp` code
  ydb/library/yql/providers/generic/connector/libcpp/error.cpp
  ydb/library/yql/providers/generic/connector/libcpp/error.h
  ydb/library/yql/providers/generic/connector/libcpp/ya.make
  ydb/library/yql/providers/generic/provider/yql_generic_load_meta.cpp
Labels: not-for-changelog

#14321 Explicit antlr3 mode for YQ
  ydb/core/fq/libs/actors/run_actor.cpp
Labels: not-for-changelog

#14322 Disable Snapshot Isolation RW for oltp
  .github/config/muted_ya.txt
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#14117 Support shredding in VDisk
  ydb/core/base/blobstorage.h
  ydb/core/blobstorage/vdisk/balance/handoff_map.h
  ydb/core/blobstorage/vdisk/balance/utils.cpp
  ydb/core/blobstorage/vdisk/balance/utils.h
  ydb/core/blobstorage/vdisk/common/vdisk_events.h
  ydb/core/blobstorage/vdisk/common/vdisk_private_events.h
  ydb/core/blobstorage/vdisk/defrag/defrag_actor.cpp
  ydb/core/blobstorage/vdisk/defrag/defrag_actor.h
  ydb/core/blobstorage/vdisk/defrag/defrag_quantum.cpp
  ydb/core/blobstorage/vdisk/defrag/defrag_quantum.h
  ydb/core/blobstorage/vdisk/defrag/defrag_rewriter.cpp
  ydb/core/blobstorage/vdisk/defrag/defrag_search.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhuge.h
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.cpp
  ydb/core/blobstorage/vdisk/huge/blobstorage_hullhugeheap.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_barrier.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_block.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullbase_logoblob.h
  ydb/core/blobstorage/vdisk/hulldb/base/hullds_heap_it.h
  ydb/core/blobstorage/vdisk/hulldb/compstrat/hulldb_compstrat_defs.h
  ydb/core/blobstorage/vdisk/hulldb/compstrat/hulldb_compstrat_explicit.h
  ydb/core/blobstorage/vdisk/hulldb/compstrat/hulldb_compstrat_selector.cpp
  ydb/core/blobstorage/vdisk/hulldb/compstrat/ya.make
  ydb/core/blobstorage/vdisk/hulldb/fresh/fresh_segment_impl.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hulldatamerger.h
  ydb/core/blobstorage/vdisk/hulldb/generic/blobstorage_hullrecmerger.h
  ydb/core/blobstorage/vdisk/hulldb/generic/hullds_sst_it.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hull.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullactor.cpp
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcommit.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompact.h
  ydb/core/blobstorage/vdisk/hullop/blobstorage_hullcompactworker.h
  ydb/core/blobstorage/vdisk/hullop/hullcompdelete/blobstorage_hullcompdelete.cpp
  ydb/core/blobstorage/vdisk/ingress/blobstorage_ingress.cpp
  ydb/core/blobstorage/vdisk/ingress/blobstorage_ingress.h
  ydb/core/blobstorage/vdisk/localrecovery/localrecovery_public.cpp
  ydb/core/blobstorage/vdisk/scrub/restore_corrupted_blob_actor.cpp
  ydb/core/blobstorage/vdisk/scrub/scrub_actor_huge_blob_merger.h
  ydb/core/blobstorage/vdisk/scrub/scrub_actor_sst_blob_merger.h
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_capturevdisklayout.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_compactionstate.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_compactionstate.h
  ydb/core/blobstorage/vdisk/skeleton/skeleton_shred.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_shred.h
  ydb/core/blobstorage/vdisk/skeleton/ya.make
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer_localwriter.cpp
  ydb/core/util/stlog.h
Labels: not-for-changelog

#14173 Add per database configs
  ydb/core/blobstorage/nodewarden/distconf.cpp
  ydb/core/blobstorage/nodewarden/distconf_console.cpp
  ydb/core/cms/console/configs_dispatcher.cpp
  ydb/core/cms/console/console.cpp
  ydb/core/cms/console/console.h
  ydb/core/cms/console/console__drop_yaml_config.cpp
  ydb/core/cms/console/console__get_yaml_config.cpp
  ydb/core/cms/console/console__get_yaml_metadata.cpp
  ydb/core/cms/console/console__replace_yaml_config.cpp
  ydb/core/cms/console/console__scheme.h
  ydb/core/cms/console/console_audit.cpp
  ydb/core/cms/console/console_audit.h
  ydb/core/cms/console/console_configs_manager.cpp
  ydb/core/cms/console/console_configs_manager.h
  ydb/core/cms/console/console_configs_provider.cpp
  ydb/core/cms/console/console_configs_provider.h
  ydb/core/cms/console/console_configs_subscriber.cpp
  ydb/core/cms/console/console_configs_subscriber.h
  ydb/core/cms/console/console_handshake.cpp
  ydb/core/cms/console/console_impl.h
  ydb/core/cms/console/console_tenants_manager.cpp
  ydb/core/cms/console/console_tenants_manager.h
  ydb/core/cms/console/console_ut_configs.cpp
  ydb/core/cms/console/ut_helpers.h
  ydb/core/cms/console/util/config_index.cpp
  ydb/core/cms/console/util/config_index.h
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init.h
  ydb/core/config/init/init_impl.h
  ydb/core/grpc_services/rpc_dynamic_config.cpp
  ydb/core/protos/console.proto
  ydb/core/protos/console_config.proto
  ydb/core/protos/feature_flags.proto
  ydb/core/viewer/viewer_feature_flags.h
  ydb/library/yaml_config/public/yaml_config.cpp
  ydb/library/yaml_config/public/yaml_config.h
  ydb/library/yaml_config/yaml_config.cpp
  ydb/library/yaml_config/yaml_config.h
  ydb/library/yaml_config/yaml_config_ut.cpp
  ydb/public/api/protos/draft/ydb_dynamic_config.proto
  ydb/public/lib/deprecated/kicli/configurator.cpp
  ydb/public/lib/deprecated/kicli/kicli.h
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.cpp
  ydb/public/sdk/cpp/client/draft/ydb_dynamic_config.cpp
  ydb/public/sdk/cpp/src/client/draft/ydb_dynamic_config.cpp
  ydb/tests/functional/audit/test_auditlog.py
  ydb/tests/functional/audit/ya.make
Labels: new-feature

#14332 Support shredding in VDisk
  ydb/core/blobstorage/vdisk/hullop/blobstorage_buildslice.h
Labels: not-for-changelog

#14099 Delete confusing TEvKqpScan rename
  ydb/core/tx/columnshard/columnshard.h
  ydb/core/tx/columnshard/columnshard__scan.cpp
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/ut_rw/ut_columnshard_read_write.cpp
Labels: not-for-changelog

#14338 Fixed broken URL to ydb-go-sdk repo
  ydb/docs/en/core/dev/example-app/go/index.md
  ydb/docs/ru/core/dev/example-app/go/index.md
Labels: bugfix

#14346 Explicit antlr3 mode for row dispatcher
  ydb/core/fq/libs/row_dispatcher/purecalc_compilation/compile_service.cpp
Labels: not-for-changelog

#14259 YQ-3561 first version of FQ run tool
  ydb/core/testlib/test_client.cpp
  ydb/core/testlib/test_client.h
  ydb/tests/tools/fqrun/.gitignore
  ydb/tests/tools/fqrun/configuration/fq_config.conf
  ydb/tests/tools/fqrun/fqprun.cpp
  ydb/tests/tools/fqrun/src/common.h
  ydb/tests/tools/fqrun/src/fq_runner.cpp
  ydb/tests/tools/fqrun/src/fq_runner.h
  ydb/tests/tools/fqrun/src/fq_setup.cpp
  ydb/tests/tools/fqrun/src/fq_setup.h
  ydb/tests/tools/fqrun/src/ya.make
  ydb/tests/tools/fqrun/ya.make
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/runlib/application.cpp
  ydb/tests/tools/kqprun/runlib/application.h
  ydb/tests/tools/kqprun/runlib/settings.h
  ydb/tests/tools/kqprun/runlib/utils.cpp
  ydb/tests/tools/kqprun/runlib/utils.h
  ydb/tests/tools/kqprun/runlib/ya.make
  ydb/tests/tools/kqprun/src/common.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/kqp_runner.cpp
  ydb/tests/tools/kqprun/src/ya.make
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
  ydb/tests/tools/kqprun/src/ydb_setup.h
  ydb/tests/tools/kqprun/ya.make
  ydb/tests/tools/ya.make
Labels: new-feature

#14342 Fix Import 719
  ydb/docs/en/core/reference/kafka-api/_includes/bash/kafka-api-console-read-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/bash/kafka-api-console-read-with-sasl-creds-on-prem.md
  ydb/docs/en/core/reference/kafka-api/_includes/bash/kafka-api-console-write-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/bash/kafka-api-kcat-read-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/bash/kafka-api-kcat-read-with-sasl-creds-on-prem.md
  ydb/docs/en/core/reference/kafka-api/_includes/bash/kafka-api-kcat-write-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-flink-read-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-flink-write-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-java-read-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-java-read-with-sasl-creds-on-prem.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-java-write-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-spark-read-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/java/kafka-api-spark-write-no-auth.md
  ydb/docs/en/core/reference/kafka-api/_includes/logs-to-kafka/kafka-api-fluent-bit.md
  ydb/docs/en/core/reference/kafka-api/_includes/logs-to-kafka/kafka-api-logstash.md
  ydb/docs/en/core/reference/kafka-api/examples.md
  ydb/docs/ru/core/reference/kafka-api/_includes/bash/kafka-api-console-read-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/bash/kafka-api-console-read-with-sasl-creds-on-prem.md
  ydb/docs/ru/core/reference/kafka-api/_includes/bash/kafka-api-console-write-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/bash/kafka-api-kcat-read-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/bash/kafka-api-kcat-read-with-sasl-creds-on-prem.md
  ydb/docs/ru/core/reference/kafka-api/_includes/bash/kafka-api-kcat-write-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-flink-read-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-flink-write-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-java-read-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-java-read-with-sasl-creds-on-prem.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-java-write-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-spark-read-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/java/kafka-api-spark-write-no-auth.md
  ydb/docs/ru/core/reference/kafka-api/_includes/logs-to-kafka/kafka-api-fluent-bit.md
  ydb/docs/ru/core/reference/kafka-api/_includes/logs-to-kafka/kafka-api-logstash.md
  ydb/docs/ru/core/reference/kafka-api/examples.md
Labels: documentation

#11319 Added info on table naming rules
  ydb/docs/en/core/concepts/datamodel/_includes/index.md
  ydb/docs/en/core/concepts/datamodel/_includes/object-naming-rules.md
  ydb/docs/en/core/concepts/datamodel/_includes/table.md
  ydb/docs/en/core/concepts/datamodel/index.md
  ydb/docs/en/core/yql/reference/syntax/alter_table/rename.md
  ydb/docs/en/core/yql/reference/syntax/create-topic.md
  ydb/docs/en/core/yql/reference/syntax/create-view.md
  ydb/docs/en/core/yql/reference/syntax/create_table/index.md
  ydb/docs/ru/core/concepts/datamodel/_includes/index.md
  ydb/docs/ru/core/concepts/datamodel/_includes/object-naming-rules.md
  ydb/docs/ru/core/concepts/datamodel/index.md
  ydb/docs/ru/core/yql/reference/syntax/alter_table/rename.md
  ydb/docs/ru/core/yql/reference/syntax/create-topic.md
  ydb/docs/ru/core/yql/reference/syntax/create-view.md
  ydb/docs/ru/core/yql/reference/syntax/create_table/index.md
Labels: documentation

#14339 Test: split shard with decimal PK
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_split_merge/ut_split_merge.cpp
Labels: not-for-changelog

#14357 fixes after review
  ydb/core/tablet/node_whiteboard.cpp
  ydb/core/viewer/viewer_tenantinfo.h
Labels: not-for-changelog

#14360 Fix console interaction bug in migration case
  ydb/core/mind/bscontroller/console_interaction.cpp
Labels: not-for-changelog

#14361 fix group state calculation for missing disks
  ydb/core/viewer/storage_groups.h
Labels: bugfix

#14352 fix followers with query service
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_scan_executer.cpp
  ydb/core/kqp/ut/service/kqp_qs_queries_ut.cpp
Labels: not-for-changelog

#14224 Make test more stable
  ydb/tests/olap/scenario/helpers/scenario_tests_helper.py
  ydb/tests/olap/scenario/test_insert.py
Labels: new-feature

#14248 YQ-3924 Fix actor name (FQ_ROW_DISPATCHER_FORMAT_HANDLER)
  ydb/core/fq/libs/row_dispatcher/format_handler/format_handler.cpp
  ydb/tests/fq/yds/test_row_dispatcher.py
Labels: not-for-changelog

#14298 YQ-4095 Add meta to Heartbeats to fix memory leak
  ydb/core/fq/libs/row_dispatcher/events/data_plane.h
  ydb/core/fq/libs/row_dispatcher/protos/events.proto
  ydb/core/fq/libs/row_dispatcher/row_dispatcher.cpp
  ydb/library/yql/providers/pq/async_io/dq_pq_rd_read_actor.cpp
Labels: not-for-changelog

#14091 Read config from cache dir
  ydb/core/blobstorage/nodewarden/node_warden.h
  ydb/core/config/init/init.cpp
  ydb/core/config/init/init_impl.h
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/protos/blobstorage.proto
  ydb/core/protos/config.proto
  ydb/tests/functional/config/test_config_with_metadata.py
  ydb/tests/library/harness/kikimr_config.py
  ydb/tests/library/harness/kikimr_runner.py
Labels: experimental-feature

#14362 Add monitoring for shred
  ydb/core/blobstorage/vdisk/anubis_osiris/blobstorage_anubis.cpp
  ydb/core/blobstorage/vdisk/anubis_osiris/blobstorage_anubisrunner.cpp
  ydb/core/blobstorage/vdisk/anubis_osiris/blobstorage_osiris.cpp
  ydb/core/blobstorage/vdisk/common/blobstorage_status.cpp
  ydb/core/blobstorage/vdisk/common/vdisk_mon.h
  ydb/core/blobstorage/vdisk/query/query_barrier.cpp
  ydb/core/blobstorage/vdisk/query/query_base.h
  ydb/core/blobstorage/vdisk/query/query_statdb.h
  ydb/core/blobstorage/vdisk/query/query_stathuge.cpp
  ydb/core/blobstorage/vdisk/query/query_stattablet.cpp
  ydb/core/blobstorage/vdisk/repl/blobstorage_repl.cpp
  ydb/core/blobstorage/vdisk/repl/blobstorage_replmonhandler.cpp
  ydb/core/blobstorage/vdisk/repl/query_donor.h
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_monactors.cpp
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeletonfront.cpp
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_syncfull.cpp
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_syncfullhandler.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_mon_dbmainpage.cpp
  ydb/core/blobstorage/vdisk/skeleton/skeleton_shred.cpp
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer.cpp
  ydb/core/blobstorage/vdisk/syncer/blobstorage_syncer_scheduler.cpp
Labels: not-for-changelog

#14330 kesus resources: dump
  ydb/library/backup/backup.cpp
  ydb/library/backup/ya.make
  ydb/public/lib/ydb_cli/dump/files/files.cpp
  ydb/public/lib/ydb_cli/dump/files/files.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/rate_limiter/rate_limiter.h
  ydb/public/sdk/cpp/src/client/rate_limiter/rate_limiter.cpp
Labels: not-for-changelog

#14369 Add check to make static analyzer happy
  ydb/core/tx/schemeshard/schemeshard__table_stats_histogram.cpp
Labels: not-for-changelog

#14320 Evwrite better errors
  .github/config/muted_ya.txt
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/cost/kqp_cost_ut.cpp
  ydb/core/kqp/ut/tx/kqp_locks_ut.cpp
  ydb/core/kqp/ut/tx/kqp_sink_tx_ut.cpp
  ydb/core/protos/data_events.proto
  ydb/core/tx/data_events/common/error_codes.cpp
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
Labels: improvement

#14370 Sinks postgres types support
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/ut/pg/kqp_pg_ut.cpp
Labels: not-for-changelog

#14379 Fix lock hash type
  ydb/core/kqp/compute_actor/kqp_scan_compute_actor.h
Labels: bugfix

#14374 rate limiter client refactoring: deduplicate structs representing HDRR settings
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/rate_limiter/rate_limiter.h
  ydb/public/sdk/cpp/src/client/rate_limiter/rate_limiter.cpp
Labels: not-for-changelog

#14358 [docs] extra comment about recommended node count for cluster topologies
  ydb/docs/en/core/concepts/topology.md
  ydb/docs/ru/core/concepts/topology.md
Labels: documentation

#14164 Add release notes for YDB CLI 2.19.0
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/darwin_arm64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/linux_amd64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/linux_arm64.md
  ydb/docs/en/core/downloads/_includes/ydb-cli/windows.md
  ydb/docs/ru/core/changelog-cli.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/darwin_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/darwin_arm64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/linux_amd64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/linux_arm64.md
  ydb/docs/ru/core/downloads/_includes/ydb-cli/windows.md
Labels: documentation

#14384 Test stability: workload_log fixes
  ydb/tests/library/wardens/factories.py
  ydb/tests/library/wardens/logs.py
  ydb/tests/stability/tool/__main__.py
  ydb/tests/stability/tool/how_to.md
Labels: not-for-changelog

#14391 Update TESTOWNERS
  .github/TESTOWNERS
Labels: not-for-changelog

#14395 Fix backward compatibility and ui for per-database configs
  ydb/core/cms/console/console.cpp
  ydb/core/cms/console/console__get_yaml_config.cpp
  ydb/core/cms/console/console_configs_manager.cpp
  ydb/core/cms/console/console_configs_manager.h
  ydb/core/cms/console/console_impl.h
  ydb/core/cms/console/console_tenants_manager.h
  ydb/core/cms/ui/yaml_config.js
Labels: bugfix

#14336 Test report: added test error
  .github/scripts/tests/generate-summary.py
  .github/scripts/tests/templates/summary.html
Labels: not-for-changelog

#13553 The keys in the block cache
  ydb/core/persqueue/cache_eviction.h
  ydb/core/persqueue/map_subrange.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_id.h
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/pq_l2_cache.cpp
  ydb/core/persqueue/pq_l2_cache.h
  ydb/core/persqueue/pq_l2_service.h
  ydb/core/persqueue/read.h
  ydb/core/persqueue/ut/cache_eviction_ut.cpp
  ydb/core/persqueue/ut/partition_ut.cpp
  ydb/core/persqueue/ut/ya.make
  ydb/core/testlib/test_pq_client.h
  ydb/public/sdk/cpp/src/client/topic/ut/topic_to_table_ut.cpp
  ydb/services/persqueue_v1/persqueue_ut.cpp
Labels: improvement

#14351 Disabled pushing OLAP Apply with no arguments
  ydb/core/kqp/opt/physical/kqp_opt_phy_olap_filter.cpp
Labels: bugfix

#14331 fix arrow schema in tests
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/testlib/cs_helper.cpp
Labels: not-for-changelog

#14394 Mute unstable tests
  .github/config/muted_ya.txt
Labels: not-for-changelog

#14387 Single credentials provider for YDB CLI commands
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/commands/topic_operations_scenario.cpp
  ydb/public/lib/ydb_cli/commands/topic_operations_scenario.h
  ydb/public/lib/ydb_cli/commands/ydb_command.cpp
  ydb/public/lib/ydb_cli/commands/ydb_command.h
  ydb/public/lib/ydb_cli/commands/ydb_service_auth.cpp
  ydb/public/lib/ydb_cli/common/command.cpp
  ydb/public/lib/ydb_cli/common/command.h
Labels: area/cli, bugfix

#14407 Added the feature_view condition for the related item
  ydb/docs/ru/core/changelog-cli.md
Labels: documentation

#14404 Fix ydb cli adjust path usage
  ydb/public/lib/ydb_cli/commands/ydb_service_export.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_export.h
  ydb/public/lib/ydb_cli/commands/ydb_service_import.cpp
  ydb/public/lib/ydb_cli/commands/ydb_service_import.h
  ydb/public/lib/ydb_cli/commands/ydb_tools.cpp
  ydb/public/lib/ydb_cli/commands/ydb_tools.h
Labels: bugfix

#14364 add network throughput aggregation
  ydb/core/protos/node_whiteboard.proto
  ydb/core/tablet/node_whiteboard.cpp
  ydb/core/viewer/protos/viewer.proto
  ydb/core/viewer/tests/canondata/result.json
  ydb/core/viewer/tests/test.py
  ydb/core/viewer/viewer_cluster.h
  ydb/core/viewer/viewer_tenantinfo.h
Labels: improvement

#14415 YQ-4103 fixed overflow in kqp write actor CalculateNextAttemptDelay
  ydb/core/kqp/runtime/kqp_write_actor.cpp
Labels: bugfix

#14423 some fixes applied to query replay tool
  ydb/tools/query_replay_yt/query_compiler.cpp
Labels: not-for-changelog

#14405 Support all rate limiter's properties in cpp sdk
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/rate_limiter/rate_limiter.h
  ydb/public/sdk/cpp/src/client/rate_limiter/rate_limiter.cpp
Labels: not-for-changelog

#14393 fix loading ttl settings
  ydb/core/kqp/ut/olap/tiering_ut.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/tables_manager.cpp
Labels: bugfix
