Repository ydb-platform/ydb, pull requests merged in 2025-05, with the labels that each got.

#17925 Fix ydb read rows timeout after ds tablets restart
  ydb/core/grpc_services/rpc_read_rows.cpp
  ydb/services/ydb/ut/ya.make
  ydb/services/ydb/ydb_read_rows_ut.cpp
Labels: bugfix

#17758 Added EnableAutoDropping flag
  ydb/core/protos/feature_flags.proto
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ut_export_reboots_s3.cpp
Labels: not-for-changelog

#17956 Add secondary index on leases.
  ydb/apps/etcd_proxy/service/create.sql
  ydb/apps/etcd_proxy/service/etcd_impl.cpp
  ydb/apps/etcd_proxy/service/etcd_watch.cpp
  ydb/apps/etcd_proxy/service/ut/etcd_service_ut.cpp
Labels: performance

#17780 Handle PDisk stop event if PDisk is in error or init state
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_actor.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.h
  ydb/library/pdisk_io/aio_linux.cpp
Labels: bugfix

#17976 dont fill deprecated field
  ydb/core/tx/columnshard/data_sharing/protos/data.proto
  ydb/core/tx/columnshard/engines/db_wrapper.cpp
  ydb/core/tx/columnshard/engines/portions/constructor_portion.cpp
  ydb/core/tx/columnshard/engines/portions/constructor_portion.h
  ydb/core/tx/columnshard/engines/portions/portion_info.cpp
  ydb/core/tx/columnshard/engines/portions/portion_info.h
  ydb/core/tx/columnshard/engines/portions/read_with_blobs.cpp
  ydb/core/tx/columnshard/engines/portions/write_with_blobs.cpp
  ydb/core/tx/columnshard/engines/storage/granule/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule/stages.cpp
  ydb/core/tx/columnshard/engines/ut/ut_logs_engine.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.cpp
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/portion/normalizer.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_portion_from_chunks.cpp
  ydb/core/tx/columnshard/normalizer/portion/restore_portion_from_chunks.h
  ydb/core/tx/columnshard/normalizer/portion/snapshot_from_chunks.cpp
  ydb/core/tx/columnshard/normalizer/portion/snapshot_from_chunks.h
  ydb/core/tx/columnshard/normalizer/portion/ya.make
Labels: improvement

#17389 [docs] updates to documentation review instructions based on feedback
  ydb/docs/en/core/contributor/documentation/_assets/lgtm.png
  ydb/docs/en/core/contributor/documentation/review.md
  ydb/docs/en/core/contributor/documentation/style-guide.md
  ydb/docs/ru/core/contributor/documentation/_assets/lgtm.png
  ydb/docs/ru/core/contributor/documentation/review.md
  ydb/docs/ru/core/contributor/documentation/style-guide.md
Labels: documentation

#17334 Docs feature security
  ydb/docs/en/core/_includes/builtin-groups-graph.md
  ydb/docs/en/core/concepts/datamodel/_assets/cluster-scheme.drawio
  ydb/docs/en/core/concepts/datamodel/_assets/cluster-scheme.png
  ydb/docs/en/core/concepts/datamodel/index.md
  ydb/docs/en/core/concepts/glossary.md
  ydb/docs/en/core/concepts/toc_i.yaml
  ydb/docs/en/core/dev/system-views.md
  ydb/docs/en/core/devops/manual/node-authorization.md
  ydb/docs/en/core/reference/configuration/auth_config.md
  ydb/docs/en/core/reference/configuration/client_certificate_authorization.md
  ydb/docs/en/core/reference/configuration/index.md
  ydb/docs/en/core/reference/configuration/security_config.md
  ydb/docs/en/core/reference/configuration/toc_p.yaml
  ydb/docs/en/core/security/_assets/security-overview.png
  ydb/docs/en/core/security/_assets/security-overview.pptx
  ydb/docs/en/core/security/authentication.md
  ydb/docs/en/core/security/builtin-security.md
  ydb/docs/en/core/security/index.md
  ydb/docs/en/core/security/toc_p.yaml
  ydb/docs/redirects.yaml
  ydb/docs/ru/core/concepts/datamodel/_assets/cluster-scheme.drawio
  ydb/docs/ru/core/concepts/datamodel/_assets/cluster-scheme.png
  ydb/docs/ru/core/concepts/datamodel/index.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/concepts/toc_i.yaml
  ydb/docs/ru/core/dev/system-views.md
  ydb/docs/ru/core/devops/deployment-options/manual/node-authorization.md
  ydb/docs/ru/core/reference/configuration/auth_config.md
  ydb/docs/ru/core/reference/configuration/client_certificate_authorization.md
  ydb/docs/ru/core/reference/configuration/index.md
  ydb/docs/ru/core/reference/configuration/security_config.md
  ydb/docs/ru/core/reference/configuration/toc_p.yaml
  ydb/docs/ru/core/security/_assets/security-overview.png
  ydb/docs/ru/core/security/_assets/security-overview.pptx
  ydb/docs/ru/core/security/authentication.md
  ydb/docs/ru/core/security/authorization.md
  ydb/docs/ru/core/security/builtin-security.md
  ydb/docs/ru/core/security/index.md
  ydb/docs/ru/core/security/toc_p.yaml
  ydb/docs/ru/core/yql/reference/_includes/initial_groups_and_users.md
Labels: documentation

#17967 Fix total in workload stats
  ydb/public/lib/ydb_cli/commands/ydb_workload.cpp
Labels: not-for-changelog

#17913 Don't wait for TEvReadSetAck from non-existent tablets
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
  ydb/core/persqueue/ut/pqtablet_ut.cpp
Labels: bugfix

#17982 Rename vector index
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_index.cpp
Labels: bugfix

#17997 CI: fix seaching existed `Update muted_ya` PR
  .github/scripts/create_or_update_pr.py
Labels: not-for-changelog

#17884 Expanded generic pushdown to more types of filters
  .github/config/muted_ya.txt
  ydb/core/kqp/opt/physical/predicate_collector.cpp
  ydb/core/kqp/ut/join/kqp_join_order_ut.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: performance

#17864 issue-17863: added file name and line number to log
  ydb/core/blob_depot/types.h
  ydb/core/blobstorage/vdisk/common/vdisk_log.h
  ydb/core/kqp/ut/data_integrity/kqp_data_integrity_trails_ut.cpp
  ydb/core/tx/ctor_logger.h
  ydb/core/util/stlog.h
  ydb/library/actors/core/log.cpp
  ydb/library/actors/core/log.h
  ydb/library/actors/core/log_iface.h
  ydb/library/grpc/server/actors/logger.cpp
Labels: improvement, external

#18010 Support for selectable hashmap implementation in the combiner_perf
  ydb/core/kqp/tools/combiner_perf/bin/format_markdown.py
  ydb/core/kqp/tools/combiner_perf/bin/main.cpp
  ydb/core/kqp/tools/combiner_perf/converters.h
  ydb/core/kqp/tools/combiner_perf/hashmaps.h
  ydb/core/kqp/tools/combiner_perf/printout.cpp
  ydb/core/kqp/tools/combiner_perf/printout.h
  ydb/core/kqp/tools/combiner_perf/run_params.h
  ydb/core/kqp/tools/combiner_perf/simple.cpp
  ydb/core/kqp/tools/combiner_perf/simple_block.cpp
  ydb/core/kqp/tools/combiner_perf/simple_last.cpp
  ydb/core/kqp/tools/combiner_perf/streams.cpp
  ydb/core/kqp/tools/combiner_perf/streams.h
  ydb/core/kqp/tools/combiner_perf/value_wrapper.h
Labels: not-for-changelog

#17729 separate schema caches by tenant
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/column_engine_logs.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.cpp
  ydb/core/tx/columnshard/engines/scheme/index_info.h
  ydb/core/tx/columnshard/engines/scheme/objects_cache.h
  ydb/core/tx/columnshard/loading/stages.cpp
  ydb/core/tx/columnshard/tables_manager.cpp
  ydb/core/tx/columnshard/tables_manager.h
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.h
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: bugfix

#17999 Analytics branch support update
  .github/scripts/analytics/data_mart_queries/test_monitor_mart.sql
  .github/scripts/analytics/data_mart_queries/test_muted_monitor_mart.sql
  .github/scripts/analytics/upload_testowners.py
  .github/workflows/collect_analytics.yml
  .github/workflows/collect_analytics_fast.yml
  .github/workflows/create_issues_for_muted_tests.yml
  .github/workflows/regression_run.yml
  .github/workflows/regression_run_compatibility.yml
  .github/workflows/regression_run_large.yml
  .github/workflows/regression_run_small_medium.yml
  .github/workflows/regression_whitelist_run.yml
Labels: not-for-changelog

#18012 Fix BSC VDisk metrics unknown fields exchange
  ydb/core/blobstorage/vdisk/skeleton/blobstorage_skeleton.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#18030 Refactoring after PR #16320: Move TS3Export::CreateBuffer() implementation to cpp
  ydb/core/tx/datashard/export_s3.h
  ydb/core/tx/datashard/export_s3_buffer.cpp
Labels: not-for-changelog

#17998 set of fixes/improvements for http proxy
  ydb/library/actors/http/http.cpp
  ydb/library/actors/http/http.h
  ydb/library/actors/http/http_proxy.cpp
  ydb/library/actors/http/http_proxy.h
  ydb/library/actors/http/http_proxy_outgoing.cpp
  ydb/library/actors/http/http_static.cpp
  ydb/library/actors/http/http_static.h
  ydb/library/actors/http/http_ut.cpp
Labels: area/ui

#17965 KIKIMR-21403: add followers support for secondary indexes
  ydb/core/kqp/provider/yql_kikimr_exec.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.cpp
  ydb/core/kqp/ut/common/kqp_ut_common.h
  ydb/core/kqp/ut/opt/kqp_ne_ut.cpp
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_alter_table.cpp
  ydb/core/tx/schemeshard/schemeshard_utils.cpp
  ydb/core/ydb_convert/table_description.cpp
  ydb/core/ydb_convert/table_description.h
  ydb/core/ydb_convert/table_settings.cpp
  ydb/public/api/protos/ydb_table.proto
  ydb/public/sdk/cpp/client/ydb_table/table.cpp
  ydb/public/sdk/cpp/client/ydb_table/table.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/table/table.h
  ydb/public/sdk/cpp/src/client/table/table.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: new-feature, external

#18050 YQ kqprun, added query parameters
  ydb/tests/tools/kqprun/.gitignore
  ydb/tests/tools/kqprun/kqprun.cpp
  ydb/tests/tools/kqprun/src/common.h
  ydb/tests/tools/kqprun/src/ydb_setup.cpp
Labels: not-for-changelog

#17759 Support partition policy for Index Table in SHOW CREATE TABLE
  ydb/core/sys_view/show_create/create_table_formatter.cpp
  ydb/core/sys_view/show_create/create_table_formatter.h
  ydb/core/sys_view/show_create/show_create.cpp
  ydb/core/sys_view/ut_kqp.cpp
Labels: not-for-changelog

#17920 Add MaintenanceStatus to evict VDisks from PDisk for long term maintenance
  ydb/core/blobstorage/ut_blobstorage/self_heal.cpp
  ydb/core/mind/bscontroller/cmds_drive_status.cpp
  ydb/core/mind/bscontroller/config.cpp
  ydb/core/mind/bscontroller/config_fit_pdisks.cpp
  ydb/core/mind/bscontroller/impl.h
  ydb/core/mind/bscontroller/load_everything.cpp
  ydb/core/mind/bscontroller/scheme.h
  ydb/core/mind/bscontroller/self_heal.cpp
  ydb/core/mind/bscontroller/self_heal.h
  ydb/core/mind/bscontroller/ut_selfheal/self_heal_actor_ut.cpp
  ydb/core/protos/blobstorage_config.proto
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_bs_controller_/flat_bs_controller.schema
Labels: new-feature

#17830 fix pk usage in writing v0 chunks
  ydb/core/tx/columnshard/blobs_action/transaction/tx_blobs_written.cpp
  ydb/core/tx/columnshard/engines/storage/granule/granule.cpp
  ydb/core/tx/columnshard/engines/storage/granule/granule.h
  ydb/core/tx/columnshard/normalizer/abstract/abstract.h
  ydb/core/tx/columnshard/normalizer/portion/chunks_v0_meta.cpp
  ydb/core/tx/columnshard/normalizer/portion/chunks_v0_meta.h
  ydb/core/tx/columnshard/normalizer/portion/ya.make
  ydb/core/tx/columnshard/ut_rw/ut_normalizer.cpp
Labels: bugfix

#18062 fixing crash in /viewer/storage handler
  ydb/core/viewer/viewer_storage.h
Labels: area/ui, bugfix, bug/crash

#18068 CI: Fix 'Update_muted_ya' workflow
  .github/workflows/update_muted_ya.yml
Labels: not-for-changelog

#17865 get rid of kqp lookup
  ydb/core/kqp/executer_actor/kqp_data_executer.cpp
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/host/kqp_type_ann.cpp
  ydb/core/kqp/opt/kqp_opt_effects.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_extract.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_indexes.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_ranges_predext.cpp
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_effects_impl.h
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_returning.cpp
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_update.cpp
  ydb/core/kqp/opt/physical/effects/kqp_opt_phy_upsert_defaults.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_build_stage.cpp
  ydb/core/kqp/opt/physical/kqp_opt_phy_rules.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
Labels: not-for-changelog

#18090 Add snaury to Node Broker code owners
  .github/CODEOWNERS
Labels: not-for-changelog

#17962 ci: image: use latest cmake, conan 2.4.1, add gcc, update bundled github runner version
  ydb/ci/gh-runner-image/build-local.sh
  ydb/ci/gh-runner-image/image.pkr.hcl
  ydb/ci/gh-runner-image/ydbtech.pkr.hcl
Labels: not-for-changelog

#18059 implement reverse lower bound
  ydb/core/formats/arrow/reader/position.cpp
  ydb/core/kqp/ut/olap/kqp_olap_ut.cpp
Labels: bugfix

#18038 added a new path type for system views
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/scheme_board/cache.cpp
  ydb/core/tx/scheme_cache/scheme_cache.h
  ydb/core/tx/schemeshard/schemeshard__operation_upgrade_subdomain.cpp
  ydb/core/tx/schemeshard/schemeshard_impl.cpp
  ydb/core/tx/schemeshard/schemeshard_path_describer.cpp
  ydb/core/viewer/browse.h
  ydb/core/viewer/protos/viewer.proto
  ydb/public/lib/deprecated/kicli/kicli.h
  ydb/public/lib/deprecated/kicli/schema.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#18085 Batch change deltas broadcasting in `NodeBroker`
  ydb/core/mind/node_broker.cpp
  ydb/core/mind/node_broker__extend_lease.cpp
  ydb/core/mind/node_broker__migrate_state.cpp
  ydb/core/mind/node_broker__register_node.cpp
  ydb/core/mind/node_broker__update_epoch.cpp
  ydb/core/mind/node_broker_impl.h
  ydb/core/mind/node_broker_ut.cpp
Labels: not-for-changelog

#18092 Remove unnecessary debug-verify in CMS
  ydb/core/cms/cluster_info.cpp
Labels: not-for-changelog

#18088 Disallow inconsistent reads with broken write locks
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_user_db.cpp
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/datashard/read_iterator.h
  ydb/core/tx/locks/locks.cpp
  ydb/core/tx/locks/locks.h
Labels: bugfix

#16672 The details of writing to the partition are collected in TPartitionBlobEncoder
  ydb/core/persqueue/blob_refcounter.h
  ydb/core/persqueue/partition.cpp
  ydb/core/persqueue/partition.h
  ydb/core/persqueue/partition_blob_encoder.cpp
  ydb/core/persqueue/partition_blob_encoder.h
  ydb/core/persqueue/partition_init.cpp
  ydb/core/persqueue/partition_monitoring.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/partition_write.cpp
  ydb/core/persqueue/writer/writer.cpp
  ydb/core/persqueue/ya.make
Labels: not-for-changelog

#18054 Correct SchemeRoot determination based on bootstrap config
  ydb/library/yaml_config/yaml_config_parser.cpp
Labels: not-for-changelog

#18100 [ydbd_slice] fixed node_id for templates
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-2-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-4-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/block-4-2-8-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/mirror-3-dc-3-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/mirror-3-dc-9-nodes.yaml
  ydb/tools/ydbd_slice/baremetal/templates/none-1-node.yaml
Labels: not-for-changelog

#17881 YQ-4278 Add TableClientMaxActiveSessions to checkpoint config
  ydb/core/fq/libs/checkpoint_storage/storage_proxy.cpp
  ydb/core/fq/libs/checkpoint_storage/ut/gc_ut.cpp
  ydb/core/fq/libs/checkpoint_storage/ut/ydb_checkpoint_storage_ut.cpp
  ydb/core/fq/libs/checkpoint_storage/ut/ydb_state_storage_ut.cpp
  ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.cpp
  ydb/core/fq/libs/checkpoint_storage/ydb_checkpoint_storage.h
  ydb/core/fq/libs/checkpoint_storage/ydb_state_storage.cpp
  ydb/core/fq/libs/checkpoint_storage/ydb_state_storage.h
  ydb/core/fq/libs/config/protos/storage.proto
  ydb/core/fq/libs/ydb/ydb.h
Labels: not-for-changelog

#15904 Private Cache remove page collection Lock/Unlock logic and respond on Detach immediately
  ydb/core/tablet_flat/flat_boot_bundle.h
  ydb/core/tablet_flat/flat_executor.cpp
  ydb/core/tablet_flat/flat_executor_bootlogic.cpp
  ydb/core/tablet_flat/flat_executor_ut.cpp
  ydb/core/tablet_flat/flat_ops_compact.h
  ydb/core/tablet_flat/flat_sausage_fetch.h
  ydb/core/tablet_flat/flat_sausage_solid.h
  ydb/core/tablet_flat/flat_sausagecache.cpp
  ydb/core/tablet_flat/flat_sausagecache.h
  ydb/core/tablet_flat/flat_scan_actor.h
  ydb/core/tablet_flat/shared_cache_events.h
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/tablet_flat/shared_sausagecache.h
  ydb/core/tablet_flat/ut/ut_shared_sausagecache_actor.cpp
  ydb/core/tablet_flat/ut/ya.make
  ydb/core/testlib/actors/block_events.h
  ydb/core/testlib/actors/wait_events.h
  ydb/core/tx/datashard/datashard__stats.cpp
  ydb/core/tx/datashard/datashard_ut_stats.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
Labels: not-for-changelog

#17668 Kafka proxy refactoring: remove kafka from actors names
  ydb/core/driver_lib/run/kikimr_services_initializers.cpp
  ydb/core/kafka_proxy/actors/kafka_init_producer_id_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_transaction_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_transaction_actor.h
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_transactions_coordinator.cpp
  ydb/core/kafka_proxy/kafka_transactions_coordinator.h
  ydb/core/kafka_proxy/ut/ut_transaction_actor.cpp
  ydb/core/kafka_proxy/ut/ut_transaction_coordinator.cpp
  ydb/core/testlib/test_client.cpp
Labels: not-for-changelog

#18079 fix sending big messages
  ydb/core/kafka_proxy/kafka_connection.cpp
  ydb/core/kafka_proxy/kafka_messages_int.cpp
  ydb/core/kafka_proxy/ut/ut_serialization.cpp
  ydb/core/raw_socket/sock_impl.h
Labels: bugfix

#18024 Recursive export and validation
  ydb/core/grpc_services/rpc_export.cpp
  ydb/core/grpc_services/rpc_import.cpp
  ydb/core/grpc_services/ya.make
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/schemeshard_import.cpp
  ydb/core/tx/schemeshard/schemeshard_import__create.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/services/ydb/backup_ut/backup_path_ut.cpp
  ydb/services/ydb/backup_ut/encrypted_backup_ut.cpp
  ydb/services/ydb/backup_ut/s3_backup_test_base.h
  ydb/services/ydb/backup_ut/ya.make
  ydb/services/ydb/ydb_common_ut.h
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: not-for-changelog

#18070 Sinks: Don't allow to split buffer into several messages
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/runtime/kqp_write_actor_settings.h
  ydb/core/kqp/runtime/kqp_write_table.cpp
  ydb/core/kqp/runtime/kqp_write_table.h
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#18104 make logging source location optional
  ydb/library/actors/core/log.cpp
  ydb/library/actors/core/log_settings.h
Labels: not-for-changelog

#17354 YQ-4188 Refactoring to reduce memory in Topic session
  ydb/core/fq/libs/row_dispatcher/format_handler/format_handler.h
  ydb/core/fq/libs/row_dispatcher/format_handler/ut/format_handler_ut.cpp
  ydb/core/fq/libs/row_dispatcher/topic_session.cpp
Labels: not-for-changelog

#16491 Support progress stats for ydb_cli (hidden option)
  ydb/public/lib/ydb_cli/commands/benchmark_utils.cpp
  ydb/public/lib/ydb_cli/commands/ydb_sql.cpp
  ydb/public/lib/ydb_cli/commands/ydb_sql.h
  ydb/public/lib/ydb_cli/common/print_utils.cpp
  ydb/public/lib/ydb_cli/common/progress_indication.cpp
  ydb/public/lib/ydb_cli/common/progress_indication.h
Labels: new-feature

#18044 [docs] use new S3 bucket
  ydb/docs/.yfm
Labels: documentation

#18121 Rename table with vector index
  ydb/core/kqp/ut/scheme/kqp_scheme_ut.cpp
  ydb/core/tx/schemeshard/schemeshard__operation_move_tables.cpp
Labels: bugfix

#18136 A little simplify of kuber's optimistics requests.
  ydb/apps/etcd_proxy/service/etcd_impl.cpp
Labels: performance

#18127 allow configuration of CS wakeup interval
  ydb/core/protos/config.proto
  ydb/core/tx/columnshard/columnshard_impl.h
  ydb/core/tx/columnshard/hooks/abstract/abstract.cpp
Labels: not-for-changelog

#18132 Prefix vector impl table has its own settings
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_index/ut_vector_index.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_vector_index_build.cpp
  ydb/core/ydb_convert/table_description.cpp
  ydb/core/ydb_convert/table_settings.cpp
  ydb/public/api/protos/ydb_table.proto
  ydb/public/sdk/cpp/client/ydb_table/table.cpp
  ydb/public/sdk/cpp/src/client/table/table.cpp
Labels: not-for-changelog

#18081 Support progress stats in workload query
  ydb/public/lib/ydb_cli/commands/query_workload.cpp
  ydb/public/lib/ydb_cli/commands/query_workload.h
Labels: new-feature

#17027 Bug fixes for direct read in topics (main)
  ydb/core/persqueue/dread_cache_service/caching_service.cpp
  ydb/core/persqueue/partition_blob_encoder.cpp
  ydb/core/persqueue/partition_read.cpp
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/ut/common/pq_ut_common.cpp
  ydb/core/persqueue/ut/common/pq_ut_common.h
  ydb/core/persqueue/ut/pq_ut.cpp
  ydb/core/protos/msgbus_pq.proto
  ydb/core/testlib/test_pq_client.h
  ydb/core/viewer/tests/test.py
  ydb/public/api/protos/ydb_topic.proto
  ydb/services/persqueue_v1/actors/partition_actor.cpp
  ydb/services/persqueue_v1/actors/partition_actor.h
  ydb/services/persqueue_v1/persqueue_ut.cpp
Labels: bugfix

#17907 splitted feature-parity table to few tables
  ydb/docs/en/core/reference/ydb-sdk/feature-parity.md
  ydb/docs/ru/core/reference/ydb-sdk/feature-parity.md
Labels: documentation

#17687 healthcheck vdisk use state2
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: improvement

#13704 New RBO prototype
  ydb/core/kqp/compile_service/kqp_compile_actor.cpp
  ydb/core/kqp/compile_service/kqp_compile_service.cpp
  ydb/core/kqp/expr_nodes/kqp_expr_nodes.json
  ydb/core/kqp/host/kqp_host.cpp
  ydb/core/kqp/host/kqp_runner.cpp
  ydb/core/kqp/host/kqp_type_ann.cpp
  ydb/core/kqp/opt/kqp_convert_to_physical.cpp
  ydb/core/kqp/opt/kqp_new_rbo.cpp
  ydb/core/kqp/opt/kqp_new_rbo.h
  ydb/core/kqp/opt/kqp_new_rbo_rules.cpp
  ydb/core/kqp/opt/kqp_new_rbo_rules.h
  ydb/core/kqp/opt/kqp_new_rbo_transformer.cpp
  ydb/core/kqp/opt/kqp_new_rbo_transformer.h
  ydb/core/kqp/opt/kqp_operator.cpp
  ydb/core/kqp/opt/kqp_operator.h
  ydb/core/kqp/opt/ya.make
  ydb/core/kqp/provider/yql_kikimr_settings.h
  ydb/core/kqp/ut/new_rbo/kqp_newrbo_ut.cpp
  ydb/core/kqp/ut/new_rbo/ya.make
  ydb/core/protos/table_service_config.proto
Labels: not-for-changelog

#17836 healthcheck segfault while retrying Whiteboard
  ydb/core/health_check/health_check.cpp
  ydb/core/health_check/health_check_ut.cpp
Labels: bugfix

#18139 dictionary accessor implement and usage
  .github/config/muted_ya.txt
  ydb/core/formats/arrow/accessor/abstract/accessor.h
  ydb/core/formats/arrow/accessor/common/const.h
  ydb/core/formats/arrow/accessor/dictionary/accessor.cpp
  ydb/core/formats/arrow/accessor/dictionary/accessor.h
  ydb/core/formats/arrow/accessor/dictionary/constructor.cpp
  ydb/core/formats/arrow/accessor/dictionary/constructor.h
  ydb/core/formats/arrow/accessor/dictionary/request.cpp
  ydb/core/formats/arrow/accessor/dictionary/request.h
  ydb/core/formats/arrow/accessor/dictionary/ut/ut_dictionary.cpp
  ydb/core/formats/arrow/accessor/dictionary/ut/ya.make
  ydb/core/formats/arrow/accessor/dictionary/ya.make
  ydb/core/formats/arrow/accessor/sub_columns/direct_builder.cpp
  ydb/core/formats/arrow/accessor/sub_columns/stats.cpp
  ydb/core/formats/arrow/accessor/ya.make
  ydb/core/kqp/ut/olap/combinatory/abstract.cpp
  ydb/core/kqp/ut/olap/combinatory/abstract.h
  ydb/core/kqp/ut/olap/combinatory/actualization.cpp
  ydb/core/kqp/ut/olap/combinatory/actualization.h
  ydb/core/kqp/ut/olap/combinatory/bulk_upsert.cpp
  ydb/core/kqp/ut/olap/combinatory/bulk_upsert.h
  ydb/core/kqp/ut/olap/combinatory/compaction.cpp
  ydb/core/kqp/ut/olap/combinatory/compaction.h
  ydb/core/kqp/ut/olap/combinatory/execute.cpp
  ydb/core/kqp/ut/olap/combinatory/execute.h
  ydb/core/kqp/ut/olap/combinatory/executor.cpp
  ydb/core/kqp/ut/olap/combinatory/executor.h
  ydb/core/kqp/ut/olap/combinatory/select.cpp
  ydb/core/kqp/ut/olap/combinatory/select.h
  ydb/core/kqp/ut/olap/combinatory/variator.cpp
  ydb/core/kqp/ut/olap/combinatory/variator.h
  ydb/core/kqp/ut/olap/combinatory/ya.make
  ydb/core/kqp/ut/olap/dictionary_ut.cpp
  ydb/core/kqp/ut/olap/helpers/typed_local.cpp
  ydb/core/kqp/ut/olap/helpers/typed_local.h
  ydb/core/kqp/ut/olap/json_ut.cpp
  ydb/core/kqp/ut/olap/optimizer_ut.cpp
  ydb/core/kqp/ut/olap/sys_view_ut.cpp
  ydb/core/kqp/ut/olap/ya.make
  ydb/core/tx/columnshard/engines/changes/compaction/abstract/merger.h
  ydb/core/tx/columnshard/engines/changes/compaction/dictionary/logic.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/dictionary/logic.h
  ydb/core/tx/columnshard/engines/changes/compaction/dictionary/ya.make
  ydb/core/tx/columnshard/engines/changes/compaction/merger.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/sub_columns/builder.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/sub_columns/builder.h
  ydb/core/tx/columnshard/engines/changes/compaction/ya.make
  ydb/core/tx/columnshard/engines/portions/column_record.h
  ydb/core/tx/columnshard/engines/scheme/column/info.cpp
  ydb/core/tx/columnshard/engines/storage/chunks/column.h
  ydb/core/tx/columnshard/engines/storage/chunks/data.cpp
  ydb/core/tx/columnshard/engines/storage/chunks/data.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
  ydb/core/tx/columnshard/splitter/abstract/chunk_meta.h
  ydb/core/tx/columnshard/splitter/abstract/chunks.h
  ydb/library/formats/arrow/protos/accessor.proto
  ydb/library/formats/arrow/switch/switch_type.h
Labels: improvement

#18161 mute KqpExplain.CreateTableAs+Stats
  .github/config/muted_ya.txt
Labels: not-for-changelog

#18164 mute KqpExplain.CreateTableAs-Stats
  .github/config/muted_ya.txt
Labels: not-for-changelog

#17436 Fix TTL on non-1st pk column with write_portions_on_insert
  ydb/core/tx/columnshard/columnshard__statistics.cpp
  ydb/core/tx/columnshard/engines/portions/data_accessor.h
  ydb/core/tx/columnshard/engines/storage/actualizer/tiering/tiering.cpp
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: not-for-changelog

#18165 Test CountMinSketch with compaction in CS
  ydb/core/statistics/aggregator/ut/ut_traverse_columnshard.cpp
  ydb/core/statistics/ut_common/ut_common.cpp
Labels: not-for-changelog

#18170 Remove tiering test duplicates
  ydb/core/tx/columnshard/ut_schema/ut_columnshard_schema.cpp
Labels: not-for-changelog

#17952 Add user attribute to keep gizmo resource id
  ydb/core/grpc_services/grpc_request_check_actor.h
  ydb/core/grpc_services/grpc_request_proxy.cpp
  ydb/core/grpc_services/grpc_request_proxy_simple.cpp
  ydb/core/protos/auth.proto
  ydb/core/security/ticket_parser_impl.h
Labels: improvement

#18056 keep precision of double values on serialization
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/proxy_service/kqp_script_executions.cpp
  ydb/core/viewer/json_pipe_req.cpp
  ydb/core/viewer/viewer_query.h
Labels: bugfix

#18120 don't report fake limit as total node memory
  ydb/core/driver_lib/run/run.cpp
  ydb/core/tablet/node_whiteboard.cpp
Labels: not-for-changelog, area/ux

#18063 Add Patch component to version definition
  ydb/core/driver_lib/version/ut/version_ut.cpp
  ydb/core/driver_lib/version/version.cpp
  ydb/core/driver_lib/version/version.h
  ydb/core/protos/config.proto
Labels: new-feature

#18175 allow reading from followers for vector index tables
  ydb/core/kqp/executer_actor/kqp_executer_impl.h
  ydb/core/kqp/executer_actor/kqp_tasks_graph.cpp
  ydb/core/kqp/provider/yql_kikimr_datasource.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.cpp
  ydb/core/kqp/provider/yql_kikimr_provider.h
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/runtime/kqp_read_actor.cpp
  ydb/core/kqp/runtime/kqp_stream_lookup_actor.cpp
  ydb/core/protos/kqp.proto
  ydb/core/protos/kqp_physical.proto
  ydb/core/protos/tx_datashard.proto
Labels: not-for-changelog

#17804 YQ-4253 added CPU limit per process in CS
  ydb/core/kqp/compute_actor/kqp_compute_actor.cpp
  ydb/core/kqp/compute_actor/kqp_compute_actor.h
  ydb/core/kqp/compute_actor/kqp_scan_fetcher_actor.cpp
  ydb/core/kqp/compute_actor/kqp_scan_fetcher_actor.h
  ydb/core/kqp/node_service/kqp_node_service.cpp
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.cpp
  ydb/core/tx/columnshard/engines/reader/abstract/read_context.h
  ydb/core/tx/columnshard/engines/reader/abstract/ya.make
  ydb/core/tx/columnshard/engines/reader/actor/actor.cpp
  ydb/core/tx/columnshard/engines/reader/actor/actor.h
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/merge.cpp
  ydb/core/tx/columnshard/engines/reader/plain_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/fetching.cpp
  ydb/core/tx/columnshard/engines/reader/simple_reader/iterator/source.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_internal_scan.cpp
  ydb/core/tx/columnshard/engines/reader/transaction/tx_scan.cpp
  ydb/core/tx/conveyor/service/service.cpp
  ydb/core/tx/conveyor/service/service.h
  ydb/core/tx/conveyor/service/worker.cpp
  ydb/core/tx/conveyor/service/worker.h
  ydb/core/tx/conveyor/usage/config.cpp
  ydb/core/tx/conveyor/usage/config.h
  ydb/core/tx/conveyor/usage/events.h
  ydb/core/tx/conveyor/usage/service.h
  ydb/tests/tools/kqprun/configuration/app_config.conf
Labels: improvement

#18206 fix test message
  ydb/core/kqp/ut/opt/kqp_returning_ut.cpp
  ydb/core/kqp/ut/pg/kqp_pg_ut.cpp
Labels: not-for-changelog

#18157 Add pdisk error handler for NoSpaceLeft(ENOSPC)
  ydb/library/pdisk_io/aio.h
  ydb/library/pdisk_io/aio_linux.cpp
Labels: bugfix

#18205 Do not disable compacton in CS quota test
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: not-for-changelog

#17747 add test to check metadata
  ydb/core/kafka_proxy/ut/kafka_test_client.cpp
  ydb/core/kafka_proxy/ut/kafka_test_client.h
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
Labels: not-for-changelog, external

#18171 fix IMMEDIATE_TX_COMPLETED counting
  ydb/core/tx/columnshard/blobs_action/transaction/tx_write.cpp
  ydb/core/tx/columnshard/test_helper/columnshard_ut_common.cpp
  ydb/core/tx/schemeshard/ut_olap/ut_olap.cpp
Labels: not-for-changelog

#18150 visualize portions tools
  ydb/core/tx/columnshard/tools/visualize_portions/__main__.py
Labels: not-for-changelog

#13406 Refactor Wilson Tracing in PDisk
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_completion_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_req_creator.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_requestimpl.h
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut.cpp
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_ut_env.h
  ydb/library/wilson_ids/wilson.h
Labels: improvement

#18102 [CBO] MaxDPHypDPTableSize threshold raised
  ydb/library/yql/dq/opt/dq_opt_join_cost_based.cpp
  ydb/library/yql/providers/dq/common/yql_dq_settings.h
Labels: area/queryprocessor

#18199 Fix deprecated TCMalloc API usage
  ydb/core/mon_alloc/tcmalloc.cpp
Labels: not-for-changelog, external

#17901 Fix YDB Import 799
  ydb/docs/en/core/concepts/_includes/vector_search_exact.md
  ydb/docs/en/core/concepts/vector_search.md
  ydb/docs/en/core/yql/reference/_includes/vector_search_approximate.md
  ydb/docs/en/core/yql/reference/_includes/vector_search_exact.md
  ydb/docs/en/core/yql/reference/udf/list/knn.md
  ydb/docs/ru/core/concepts/_includes/vector_search_exact.md
  ydb/docs/ru/core/concepts/vector_search.md
  ydb/docs/ru/core/yql/reference/_includes/vector_search_approximate.md
  ydb/docs/ru/core/yql/reference/_includes/vector_search_exact.md
  ydb/docs/ru/core/yql/reference/udf/list/knn.md
Labels: documentation

#18093 Description of format response of monitoring healthcheck
  ydb/docs/en/core/reference/ydb-cli/commands/monitoring-healthcheck.md
  ydb/docs/ru/core/reference/ydb-cli/commands/monitoring-healthcheck.md
Labels: documentation

#18220 Fix the memory profiling compilation
  ydb/core/memory_controller/memory_controller.cpp
Labels: not-for-changelog

#17924 Kikimr 20806 add cache metrics
  ydb/docs/en/core/reference/observability/metrics/index.md
  ydb/docs/ru/core/reference/observability/metrics/index.md
Labels: documentation

#18213 Check iter index access slice bounds
  ydb/core/tablet_flat/flat_fwd_cache.h
  ydb/core/tablet_flat/flat_page_btree_index.h
  ydb/core/tablet_flat/flat_part_iter.h
  ydb/core/tablet_flat/test/libs/table/test_envs.h
  ydb/core/tablet_flat/ut/ut_btree_index_iter_charge.cpp
Labels: not-for-changelog

#18129 [docs] add DataLens integration
  ydb/docs/en/core/integrations/visualization/_assets/datalens.jpeg
  ydb/docs/en/core/integrations/visualization/_includes/toc-table.md
  ydb/docs/en/core/integrations/visualization/datalens.md
  ydb/docs/en/core/integrations/visualization/toc-visualization.yaml
  ydb/docs/ru/core/integrations/visualization/_assets/datalens.jpeg
  ydb/docs/ru/core/integrations/visualization/_includes/toc-table.md
  ydb/docs/ru/core/integrations/visualization/datalens.md
  ydb/docs/ru/core/integrations/visualization/toc-visualization.yaml
Labels: documentation

#18226 fix leak in persqueue write session actor
  ydb/services/persqueue_v1/actors/write_session_actor.cpp
  ydb/services/persqueue_v1/actors/write_session_actor.h
Labels: bugfix

#17751 Add StartTime/EndTime/UserSID for BuildIndex (#16971)
  ydb/core/grpc_services/operation_helpers.cpp
  ydb/core/grpc_services/rpc_alter_table.cpp
  ydb/core/kqp/executer_actor/kqp_scheme_executer.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_vector_ut.cpp
  ydb/core/protos/index_builder.proto
  ydb/core/tx/schemeshard/schemeshard__init.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index__create.cpp
  ydb/core/tx/schemeshard/schemeshard_build_index_tx_base.cpp
  ydb/core/tx/schemeshard/schemeshard_export.cpp
  ydb/core/tx/schemeshard/schemeshard_import.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.cpp
  ydb/core/tx/schemeshard/schemeshard_info_types.h
  ydb/core/tx/schemeshard/schemeshard_schema.h
  ydb/core/tx/schemeshard/ut_helpers/helpers.cpp
  ydb/core/tx/schemeshard/ut_index_build/ut_index_build.cpp
  ydb/public/sdk/cpp/src/client/types/operation/operation.cpp
  ydb/tests/functional/scheme_tests/canondata/tablet_scheme_tests.TestTabletSchemes.test_tablet_schemes_flat_schemeshard_/flat_schemeshard.schema
Labels: improvement

#18249 DOCSSUP-2020: update docs_build.yaml
  .github/workflows/docs_build.yaml
Labels: documentation

#18203 speed-up tiering tests
  ydb/tests/olap/ttl_tiering/base.py
  ydb/tests/olap/ttl_tiering/data_migration_when_alter_ttl.py
  ydb/tests/olap/ttl_tiering/tier_delete.py
  ydb/tests/olap/ttl_tiering/ttl_delete_s3.py
  ydb/tests/olap/ttl_tiering/ttl_unavailable_s3.py
Labels: not-for-changelog

#18254 Fix schemeshard's view tests
  ydb/core/tx/schemeshard/ut_view/ut_view.cpp
Labels: not-for-changelog

#18155 Library import 250509-0050
  ydb/ci/rightlib.txt
  ydb/library/yql/udfs/common/knn/test/canondata/test.test_ErrorDistanceSameTag_/extracted
  ydb/library/yql/udfs/common/knn/test/canondata/test.test_ErrorFloatFromBinaryStringBitVector_/extracted
  ydb/tests/fq/http_api/test_http_api.py
  yql/essentials/core/type_ann/type_ann_expr.cpp
  yql/essentials/tests/s-expressions/minirun/part5/canondata/test.test_Casts-AlterToOverDataTypes-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part0/canondata/test.test_bitcast_implicit-sub_bitcast-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part0/canondata/test.test_expr-dict_common_type--Results_/extracted
  yql/essentials/tests/sql/minirun/part0/canondata/test.test_json-json_query_common_syntax-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part1/canondata/test.test_params-param_in_json_api--Results_/extracted
  yql/essentials/tests/sql/minirun/part1/canondata/test.test_params-primitives--Results_/extracted
  yql/essentials/tests/sql/minirun/part2/canondata/test.test_json-json_query_on_empty-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part2/canondata/test.test_json-json_query_wrapper-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part3/canondata/test.test_bitcast_implicit-add_bitcast-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part3/canondata/test.test_bitcast_implicit-div_bitcast-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part3/canondata/test.test_params-no_optional_param-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part4/canondata/test.test_in-in_with_nulls_and_optionals-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part4/canondata/test.test_json-json_query_on_error-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part4/canondata/test.test_pg-in_sorted-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part5/canondata/test.test_bitcast_implicit-mul_bitcast-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part5/canondata/test.test_expr-list_flat_map_deprecated_opt-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part5/canondata/test.test_in-in_with_cast-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part5/canondata/test.test_json-jsonpath_unicode-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part6/canondata/test.test_bitcast_implicit-mod_bitcast-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part6/canondata/test.test_coalesce-coalesce_symmetry-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part6/canondata/test.test_json-combination_nested-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part6/canondata/test.test_json-json_query_passing-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part6/canondata/test.test_lambda-list_aggregate_flatmap-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part7/canondata/test.test_datetime-date_tz_expand_gmt-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part7/canondata/test.test_json-jsondocument_json_query-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part8/canondata/test.test_aggregate-aggregate_distinct_in_access_node_exprs-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part8/canondata/test.test_expr-list_builtins--Results_/extracted
  yql/essentials/tests/sql/minirun/part8/canondata/test.test_udf-logger_resolve--Results_/extracted
  yql/essentials/tests/sql/minirun/part9/canondata/test.test_expr-as_set-default.txt-Results_/extracted
  yql/essentials/tests/sql/minirun/part9/canondata/test.test_json-combination_unwrapped-default.txt-Results_/extracted
  yql/essentials/tests/sql/sql2yql/canondata/result.json
  yql/essentials/tests/sql/sql2yql/canondata/test_sql_format.test_aggregate-yql-19929_/formatted.sql
  yql/essentials/tests/sql/suites/aggregate/yql-19929.cfg
  yql/essentials/tests/sql/suites/aggregate/yql-19929.sql
  yql/essentials/udfs/common/datetime2/test/canondata/test.test_Error_/extracted
  yql/essentials/udfs/common/protobuf/test/canondata/result.json
  yql/essentials/udfs/common/protobuf/test/canondata/test.test_recursion_fail_/extracted
  yql/essentials/udfs/common/re2/test/canondata/test.test_MultipleCaptureGroups_/extracted
  yql/essentials/udfs/common/string/test/canondata/test.test_AsciiCmpIgnoreCase_2025_02_/extracted
  yql/essentials/udfs/common/string/test/canondata/test.test_Reverse_2025.02_/extracted
  yql/essentials/udfs/common/yson2/test/canondata/test.test_FromTooManyArgs_/extracted
  yt/yt/client/chunk_client/chunk_replica-inl.h
  yt/yt/client/chunk_client/chunk_replica.cpp
  yt/yt/client/chunk_client/chunk_replica.h
  yt/yt/client/chunk_client/helpers.cpp
  yt/yt/client/chunk_client/helpers.h
  yt/yt/client/chunk_client/public.h
  yt/yt_proto/yt/client/chunk_client/proto/chunk_spec.proto
Labels: rightlib

#18232 Improve column table quota test in serverless
  ydb/tests/functional/serverless/test_serverless.py
Labels: not-for-changelog

#15017 YQ-3984 Group by hop docs to ydb
  ydb/docs/en/core/yql/reference/syntax/group_by.md
  ydb/docs/ru/core/yql/reference/syntax/group_by.md
Labels: documentation

#18284 Portion visualizer improvement
  ydb/core/tx/columnshard/tools/visualize_portions/__main__.py
Labels: not-for-changelog

#18046 Enable VDisk throttling report by default
  ydb/core/protos/feature_flags.proto
Labels: not-for-changelog

#18237 Limit deferred effects count
  ydb/core/kqp/common/kqp_tx.h
Labels: not-for-changelog

#17932 Ydb topics kafka proxy add metadata commit fetch actors
  ydb/core/kafka_proxy/actors/kafka_offset_commit_actor.cpp
  ydb/core/kafka_proxy/actors/kafka_offset_fetch_actor.cpp
  ydb/core/kafka_proxy/kafka_events.h
  ydb/core/kafka_proxy/ut/kafka_test_client.cpp
  ydb/core/kafka_proxy/ut/kafka_test_client.h
  ydb/core/kafka_proxy/ut/ut_protocol.cpp
  ydb/core/protos/msgbus_pq.proto
  ydb/core/protos/pqconfig.proto
Labels: not-for-changelog

#18241 Change error for sink: out of buffer memory
  ydb/core/kqp/runtime/kqp_write_actor.cpp
  ydb/core/kqp/ut/query/kqp_limits_ut.cpp
Labels: not-for-changelog

#18277 cleanup apply extract opt rules
  ydb/core/kqp/opt/logical/kqp_opt_log.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_extract.cpp
  ydb/core/kqp/opt/logical/kqp_opt_log_rules.h
Labels: not-for-changelog

#18201 schemeshard: fix split key selection from access sample
  ydb/core/tx/schemeshard/schemeshard__table_stats_histogram.cpp
  ydb/core/tx/schemeshard/ut_split_merge/ut_find_split_key.cpp
  ydb/core/tx/schemeshard/ut_split_merge/ya.make
Labels: bugfix

#18287 Fix stranded PDisk actor while using testlib
  ydb/core/testlib/basics/helpers.cpp
  ydb/library/actors/testlib/test_runtime.cpp
  ydb/library/actors/testlib/test_runtime.h
Labels: not-for-changelog

#18138 TOPICS: export configuration to S3
  ydb/core/tx/schemeshard/schemeshard_export__create.cpp
  ydb/core/tx/schemeshard/schemeshard_export_uploaders.cpp
  ydb/core/tx/schemeshard/schemeshard_path.cpp
  ydb/core/tx/schemeshard/ut_export/ut_export.cpp
  ydb/core/tx/schemeshard/ut_export_reboots_s3/ut_export_reboots_s3.cpp
  ydb/core/tx/schemeshard/ut_helpers/export_reboots_common.cpp
Labels: new-feature

#17900 [docs] reference for https://github.com/ydb-platform/ydb-mcp
  ydb/docs/en/core/reference/languages-and-apis/index.md
  ydb/docs/en/core/reference/languages-and-apis/mcp/_assets/example-usage.png
  ydb/docs/en/core/reference/languages-and-apis/mcp/index.md
  ydb/docs/en/core/reference/languages-and-apis/toc_p.yaml
  ydb/docs/ru/core/reference/languages-and-apis/index.md
  ydb/docs/ru/core/reference/languages-and-apis/mcp/_assets/example-usage.png
  ydb/docs/ru/core/reference/languages-and-apis/mcp/index.md
  ydb/docs/ru/core/reference/languages-and-apis/toc_p.yaml
Labels: documentation

#17105 actualize tablet types doc
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/reference/configuration/hive.md
Labels: documentation

#18293 Disable OLAP support for BATCH operations, add tests for ON and OLAP
  ydb/core/kqp/session_actor/kqp_session_actor.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_delete_ut.cpp
  ydb/core/kqp/ut/batch_operations/kqp_batch_update_ut.cpp
Labels: not-for-changelog

#18107 Allow fetching extra sections through distconf to revert automatic configuration changes
  ydb/core/blobstorage/nodewarden/distconf_invoke.h
  ydb/core/blobstorage/nodewarden/distconf_invoke_common.cpp
  ydb/core/blobstorage/nodewarden/distconf_invoke_storage_config.cpp
  ydb/core/grpc_services/rpc_config.cpp
  ydb/core/grpc_services/rpc_config_base.h
  ydb/core/protos/blobstorage_distributed_config.proto
  ydb/library/fyamlcpp/fyamlcpp.cpp
  ydb/library/fyamlcpp/fyamlcpp.h
  ydb/public/api/protos/ydb_config.proto
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.cpp
  ydb/public/lib/ydb_cli/commands/ydb_dynamic_config.h
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/config/config.h
  ydb/public/sdk/cpp/src/client/config/config.cpp
Labels: not-for-changelog

#18303 remove unused things in datashard
  ydb/core/tx/datashard/datashard_impl.h
  ydb/core/tx/datashard/datashard_kqp_compute.cpp
  ydb/core/tx/datashard/datashard_kqp_compute.h
  ydb/core/tx/datashard/datashard_kqp_lookup_table.cpp
  ydb/core/tx/datashard/datashard_kqp_read_table.cpp
  ydb/core/tx/datashard/ya.make
Labels: not-for-changelog

#18313 Added a missing endlist tag
  ydb/docs/ru/core/reference/configuration/index.md
Labels: documentation

#18306 Decrease PrintLogChunksInfo logging priority NOTICE->DEBUG
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl_log.cpp
Labels: not-for-changelog

#18234 Don't lose unpersisted read locks across restarts
  ydb/core/tx/datashard/datashard__read_iterator.cpp
  ydb/core/tx/datashard/datashard_ut_common_kqp.h
  ydb/core/tx/datashard/datashard_ut_read_iterator.cpp
  ydb/core/tx/locks/locks.cpp
  ydb/core/tx/locks/locks.h
  ydb/core/tx/locks/locks_db.h
Labels: bugfix

#18149 Allow to send duplicates through TDedicatedPipePool
  ydb/core/tx/schemeshard/dedicated_pipe_pool.h
  ydb/core/tx/schemeshard/schemeshard_build_index__progress.cpp
  ydb/core/tx/schemeshard/schemeshard_cdc_stream_scan.cpp
Labels: not-for-changelog

#18222 Fix `ydb operation get` not working for running operations (#17001)
  ydb/apps/ydb/CHANGELOG.md
  ydb/public/lib/ydb_cli/commands/ydb_service_operation.cpp
Labels: bugfix

#18200 Refactoring in `ydb tools restore` code
  ydb/library/backup/backup.cpp
  ydb/public/lib/ydb_cli/dump/restore_impl.cpp
  ydb/public/lib/ydb_cli/dump/restore_impl.h
  ydb/public/lib/ydb_cli/dump/util/util.cpp
  ydb/public/lib/ydb_cli/dump/util/util.h
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#18279 Fix PDisk shred free chunks in transit and after vdisk deletion
  ydb/core/blobstorage/pdisk/blobstorage_pdisk_impl.cpp
Labels: not-for-changelog

#18320 Update README.md
  ydb/library/actors/README.md
Labels: documentation

#18315 Update daemon.py
  ydb/tests/library/harness/daemon.py
Labels: not-for-changelog

#18314 Fix "Page collection request should not be in pending requests" fail
  ydb/core/tablet_flat/shared_sausagecache.cpp
  ydb/core/tablet_flat/ut/ut_shared_sausagecache_actor.cpp
Labels: not-for-changelog

#18269 Make reconnect to kesus work again
  .github/config/muted_ya.txt
  ydb/core/quoter/kesus_quoter_proxy.cpp
  ydb/core/quoter/ut_helpers.cpp
Labels: not-for-changelog

#18312 Use Y_UNIT_TEST_QUAD for vector index tests to reduce copy-paste
  ydb/core/kqp/ut/indexes/kqp_indexes_prefixed_vector_ut.cpp
  ydb/core/kqp/ut/indexes/kqp_indexes_vector_ut.cpp
Labels: not-for-changelog

#18095 Add audit logging on `create tenant` database in console tablet
  ydb/core/client/server/msgbus_server_console.cpp
  ydb/core/cms/console/console__create_tenant.cpp
  ydb/core/cms/console/console__remove_tenant.cpp
  ydb/core/cms/console/console__scheme.h
  ydb/core/cms/console/console_audit.cpp
  ydb/core/cms/console/console_audit.h
  ydb/core/cms/console/console_tenants_manager.cpp
  ydb/core/cms/console/console_tenants_manager.h
  ydb/core/grpc_services/rpc_cms.cpp
  ydb/core/protos/console_tenant.proto
  ydb/tests/functional/audit/test_auditlog.py
Labels: improvement

#18316 draw intersections
  ydb/core/tx/columnshard/tools/visualize_portions/__main__.py
Labels: not-for-changelog

#18285 Fix cpu counters in case with stuck actors
  ydb/library/actors/core/execution_stats.h
  ydb/library/actors/core/executor_thread.cpp
  ydb/library/actors/core/mon_stats.h
Labels: area/actorsystem, not-for-changelog

#18247 Fix #16475
  ydb/core/kqp/opt/kqp_query_plan.cpp
  ydb/core/kqp/ut/federated_query/s3/kqp_s3_plan_ut.cpp
  ydb/core/kqp/ut/query/kqp_stats_ut.cpp
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_explain.script-script_/explain.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_join_group_by_lookup.script-script_/join_group_by_lookup.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_simple_ct.script-script_/simple_ct.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_table_types.script-script_/table_types.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage.script-script_/write_multi_usage.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_multi_usage_key.script-script_/write_multi_usage_key.script.plan
  ydb/tests/functional/canonical/canondata/test_sql.TestCanonicalFolder1.test_case_write_write_group_by.script-script_/write_write_group_by.script.plan
Labels: not-for-changelog

#18252 [KQP] Add support for multi labels input for KqpJoinToIndexLookup
  ydb/core/kqp/opt/logical/kqp_opt_log_join.cpp
  ydb/core/kqp/ut/join/kqp_join_ut.cpp
Labels: not-for-changelog

#18305 multi layers compaction configuration
  ydb/core/protos/flat_scheme_op.proto
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/one_layer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/one_layer.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/zero_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/common_level.h
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/optimizer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/zero_level.h
Labels: improvement

#18337 Remove FileNotFoundError
  ydb/tests/library/harness/kikimr_runner.py
Labels: not-for-changelog

#18307 The serialized TEvReadSet takes up a lot of memory
  ydb/core/persqueue/pq_impl.cpp
  ydb/core/persqueue/pq_impl.h
  ydb/core/persqueue/transaction.cpp
  ydb/core/persqueue/transaction.h
  ydb/core/persqueue/ut/pqtablet_ut.cpp
Labels: bugfix

#18251 Create simple counter to count success data erasure and timeouts in one iteration of data erasure
  ydb/core/tx/schemeshard/schemeshard__data_erasure_manager.h
  ydb/core/tx/schemeshard/schemeshard__root_data_erasure_manager.cpp
  ydb/core/tx/schemeshard/schemeshard__tenant_data_erasure_manager.cpp
Labels: not-for-changelog

#18364 hotfix pr-check long queue
  .github/workflows/pr_check.yml
Labels: not-for-changelog

#18346 fix long errors on vdisk evict when no pdisks are available
  ydb/core/viewer/viewer.cpp
Labels: not-for-changelog

#18361 DOCSTOOLS-4233: enable strict
  ydb/docs/.yfm
Labels: documentation

#18384 Make lazy server start for backup tests in order to quickly list tests
  ydb/services/ydb/backup_ut/encrypted_backup_ut.cpp
  ydb/services/ydb/backup_ut/s3_backup_test_base.h
Labels: not-for-changelog

#18380 dump: handle no auth replications correctly
  ydb/library/backup/backup.cpp
  ydb/services/ydb/backup_ut/ydb_backup_ut.cpp
Labels: not-for-changelog

#18061 Test for vector index for all types
  ydb/tests/datashard/lib/create_table.py
  ydb/tests/datashard/lib/dml_operations.py
  ydb/tests/datashard/lib/vector_base.py
  ydb/tests/datashard/lib/ya.make
  ydb/tests/datashard/vector_index/test_vector_index.py
  ydb/tests/datashard/vector_index/ya.make
  ydb/tests/datashard/ya.make
Labels: not-for-changelog

#17605 Test for secondary indexes for all types
  ydb/tests/datashard/lib/dml_operations.py
  ydb/tests/datashard/secondary_index/test_secondary_index.py
  ydb/tests/datashard/secondary_index/ya.make
  ydb/tests/datashard/ya.make
Labels: not-for-changelog

#17549 Test for partitioning for all types
  ydb/tests/datashard/partitioning/test_partitioning.py
  ydb/tests/datashard/partitioning/ya.make
  ydb/tests/datashard/ya.make
Labels: not-for-changelog

#18374 Add support for data_shard_config in cluster.yaml
  ydb/tools/cfg/static.py
Labels: not-for-changelog

#18228 Tablet sys: Retry failed GC requests
  ydb/core/tablet/tablet_impl.h
  ydb/core/tablet/tablet_sys.cpp
  ydb/core/tablet/tablet_sys.h
  ydb/core/tablet_flat/flat_executor_gclogic.cpp
  ydb/core/tablet_flat/flat_executor_gclogic.h
  ydb/core/tablet_flat/ut/ut_data_cleanup.cpp
Labels: not-for-changelog

#18345 improve vdisk evict swagger and parameters handling
  ydb/core/viewer/vdisk_evict.h
Labels: not-for-changelog

#18351 Add commit version to datashard replies
  ydb/core/protos/data_events.proto
  ydb/core/protos/tx_datashard.proto
  ydb/core/tx/datashard/datashard.h
  ydb/core/tx/datashard/datashard_ut_write.cpp
  ydb/core/tx/datashard/execute_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_kqp_data_tx_unit.cpp
  ydb/core/tx/datashard/execute_write_unit.cpp
Labels: not-for-changelog

#18397 Muted ydb/core/kqp/ut/olap KqpOlapLocks.DeleteAbsentMultipleShards+Reboot
  .github/config/muted_ya.txt
Labels: not-for-changelog

#18402 Fixed errors in links
  ydb/docs/en/core/concepts/_includes/secondary_indexes.md
  ydb/docs/en/core/dev/query-plans-optimization.md
  ydb/docs/en/core/downloads/yandex-enterprise-database.md
  ydb/docs/en/core/downloads/ydb-ansible.md
  ydb/docs/en/core/reference/languages-and-apis/ado-net/basic-usage.md
  ydb/docs/en/core/reference/observability/tracing/setup.md
  ydb/docs/en/core/reference/ydb-cli/commands/_includes/secondary_index.md
  ydb/docs/ru/core/concepts/_includes/limits-ydb.md
  ydb/docs/ru/core/concepts/_includes/secondary_indexes.md
  ydb/docs/ru/core/concepts/glossary.md
  ydb/docs/ru/core/contributor/hive.md
  ydb/docs/ru/core/dev/query-plans-optimization.md
  ydb/docs/ru/core/devops/configuration-management/_includes/node-authorization.md
  ydb/docs/ru/core/devops/configuration-management/migration/index.md
  ydb/docs/ru/core/devops/configuration-management/migration/migration-to-v1.md
  ydb/docs/ru/core/devops/deployment-options/ansible/initial-deployment.md
  ydb/docs/ru/core/devops/deployment-options/manual/node-authorization.md
  ydb/docs/ru/core/downloads/yandex-enterprise-database.md
  ydb/docs/ru/core/downloads/ydb-ansible.md
  ydb/docs/ru/core/reference/configuration/hive.md
  ydb/docs/ru/core/reference/configuration/index.md
  ydb/docs/ru/core/reference/embedded-ui/hive.md
  ydb/docs/ru/core/reference/observability/tracing/setup.md
  ydb/docs/ru/core/reference/ydb-cli/commands/_includes/secondary_index.md
  ydb/docs/ru/core/reference/ydb-cli/commands/configuration/index.md
  ydb/docs/ru/core/reference/ydb-cli/configs.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-dump.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/tools-restore.md
Labels: documentation

#18354 simplify feature flags calculation
  ydb/core/viewer/viewer_feature_flags.h
Labels: not-for-changelog

#18403 CI: fix update muted ya workflow + create issues for muted test
  .github/workflows/create_issues_for_muted_tests.yml
  .github/workflows/update_muted_ya.yml
Labels: not-for-changelog

#18342 compaction speed up
  ydb/core/kqp/ut/olap/optimizer_ut.cpp
  ydb/core/tx/columnshard/columnshard_impl.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/abstract/merger.h
  ydb/core/tx/columnshard/engines/changes/compaction/dictionary/logic.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/dictionary/logic.h
  ydb/core/tx/columnshard/engines/changes/compaction/merger.cpp
  ydb/core/tx/columnshard/engines/changes/compaction/sparsed/logic.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/constructor.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/constructor/one_layer.cpp
  ydb/core/tx/columnshard/engines/storage/optimizer/lcbuckets/planner/common_level.h
  ydb/core/tx/columnshard/hooks/testing/ro_controller.h
Labels: performance

#16237 Test for TTL on all types
  ydb/tests/datashard/lib/dml_operations.py
  ydb/tests/datashard/lib/types_of_variables.py
  ydb/tests/datashard/ttl/test_ttl.py
  ydb/tests/datashard/ttl/ya.make
  ydb/tests/datashard/ya.make
Labels: not-for-changelog

#18382 cleanup optimizer and stuff
  ydb/core/kqp/opt/peephole/kqp_opt_peephole_wide_read.cpp
  ydb/core/kqp/query_compiler/kqp_mkql_compiler.cpp
  ydb/core/kqp/query_compiler/kqp_query_compiler.cpp
  ydb/core/kqp/query_data/kqp_predictor.cpp
  ydb/core/kqp/runtime/kqp_program_builder.cpp
  ydb/core/kqp/runtime/kqp_program_builder.h
  ydb/core/kqp/ut/effects/kqp_inplace_update_ut.cpp
Labels: not-for-changelog

#18343 YQL-19940: Fix msan tests
  ydb/core/kqp/runtime/kqp_scan_data_ut.cpp
Labels: not-for-changelog

#18282 [docs] fix/update many legacy external links
  ydb/apps/ydb/CHANGELOG.md
  ydb/docs/en/core/_includes/parameterized-query.md
  ydb/docs/en/core/changelog-cli.md
  ydb/docs/en/core/concepts/federated_query/s3/_includes/date_formats.md
  ydb/docs/en/core/devops/ansible/initial-deployment.md
  ydb/docs/en/core/devops/kubernetes/initial-deployment.md
  ydb/docs/en/core/integrations/ingestion/import-jdbc.md
  ydb/docs/en/core/reference/ydb-cli/_includes/result_format_csv_tsv.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/import-file.md
  ydb/docs/en/core/reference/ydb-cli/export-import/_includes/s3_conn.md
  ydb/docs/en/core/reference/ydb-cli/operation-get.md
  ydb/docs/en/core/reference/ydb-cli/profile/_includes/create.md
  ydb/docs/en/core/reference/ydb-cli/topic-read.md
  ydb/docs/en/core/reference/ydb-cli/topic-write.md
  ydb/docs/en/core/reference/ydb-sdk/_includes/auth.md
  ydb/docs/en/core/security/audit-log.md
  ydb/docs/en/core/security/authentication.md
  ydb/docs/en/core/yql/reference/builtins/aggregation.md
  ydb/docs/en/core/yql/reference/syntax/select/match_recognize.md
  ydb/docs/ru/core/_includes/parameterized-query.md
  ydb/docs/ru/core/concepts/_includes/transactions.md
  ydb/docs/ru/core/concepts/_includes/ttl.md
  ydb/docs/ru/core/concepts/connect.md
  ydb/docs/ru/core/concepts/topic.md
  ydb/docs/ru/core/dev/secondary-indexes.md
  ydb/docs/ru/core/reference/ydb-cli/export-import/_includes/import-file.md
  ydb/docs/ru/core/reference/ydb-cli/operation-list.md
  ydb/docs/ru/core/reference/ydb-cli/parameterized-queries-cli.md
  ydb/docs/ru/core/reference/ydb-cli/parameterized-query-execution.md
  ydb/docs/ru/core/reference/ydb-cli/table-query-execute.md
  ydb/docs/ru/core/reference/ydb-sdk/_includes/auth.md
  ydb/docs/ru/core/security/audit-log.md
  ydb/docs/ru/core/yql/reference/syntax/join.md
Labels: documentation

#17765 [Kafka API] Add forwarding of txn requests to coordinator
  ydb/core/kafka_proxy/kafka_connection.cpp
Labels: not-for-changelog

#18366 TImportClient::ListObjectsInS3Export in C++ SDK
  ydb/public/sdk/cpp/include/ydb-cpp-sdk/client/import/import.h
  ydb/public/sdk/cpp/src/client/import/import.cpp
  ydb/public/sdk/cpp/src/client/import/out.cpp
Labels: not-for-changelog
